### ISSUE TITLE
If excalidraw pane is closed, opening a drawing doesn’t work

### ISSUE THREAD

**Issue by roamhacker** [zsviczian/obsidian-excalidraw-plugin#1]
**To Reproduce**
1. Close he excalidraw pane in the sidebar
2. Try to use command palette or menu icon shortcut to open an excalidraw draw of

**Expected behavior**
Window pane will open itself if not open upon using one of the methods for opening a drawing

**Desktop (please complete the following information):**
 - OS: chrome is

**Comment by zsviczian** [comment]
hm... this worked before.
I was able to reproduce the issue. Will solve tonight.

**Comment by zsviczian** [comment]
fixed in 0.0.2
