### ISSUE TITLE
After a while the pointer position on the canvas becomes inaccurate

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#101]
Hack workaround to reset canvas positioning as part of autosave.

**Comment by dwelle** [comment]
Have you checked if this is fixed in the latest build? Something like this was fixed recently: https://github.com/excalidraw/excalidraw/issues/3798

**Comment by zsviczian** [comment]
Yes, I am using 0.9.0. It seems as if the issue happens more frequently if I zoom in to edit something and then zoom out... but this is just a feeling, I haven't tested it in detail.

**Comment by dwelle** [comment]
That fix hasn't landed in stable yet, so to test it out you'll need to use `@excalidraw/excalidraw-next`.

**Comment by zsviczian** [comment]
@dwelle since using the latest Excalidraw build, the issue seems to have been resolved. Thanks!
