### ISSUE TITLE
FR: 

### ISSUE THREAD

**Issue by johannesCmayer** [zsviczian/obsidian-excalidraw-plugin#1011]
I would like an embedded .excalidraw file to not open when I click on it in the mobile app, I have very large image files, that fill the entire page, and I open them accidentally all the time. I would like to have it that they only open on a double click or a long click. It is hard to scroll without clicking the image. Another solution might be to click with two fingers perhaps.

**Comment by zsviczian** [comment]
this has been resolved in the meantime.
