### ISSUE TITLE
Settings for excalidraw plugin not saved

### ISSUE THREAD

**Issue by zFrostz** [zsviczian/obsidian-excalidraw-plugin#103]
**Describe the bug**
Whenever obsidian is closed all the settings for the excalidraw plugin are reset to default. I have noticed that all the content in the data.json file is automatically deleted when obsidian closes hence causing this issue. I tried to delete data.json but didn't fix it after it was recreated. I am using the latest obsidian public release and the latest excalidraw release from the community plugins browser.

**Update**
The issue was temporarily fixed but I am not sure how... I created a new data.json file myself, copied and pasted my settings into it and the problem was fixed but I am not sure if creating the file myself did something. However the problem reappeared later.. it seems like the problem occurs randomly at times when you close obsidian sometimes it does sometimes it doesn't.. 

**To Reproduce**
1. Change settings for the plugin
2. Close obsidian
3. Relaunch obsidian

**Comment by zsviczian** [comment]
Thanks for raising. 

Are you using obsidian sync?
On what device/operating system are you using Obsidian?

**Comment by zFrostz** [comment]
I am not using obsidian sync however I sync my vault google drive.. and I am using obsidian v0.12.10 on windows 10

Also currently I am dealing with the situation by making the data.json file read-only and it is not causing any issues for now however it does mean I have to go to the data.json file every time I want to tweak something.

**Comment by zsviczian** [comment]
I can see what might be causing the issue, but unfortunately, I won't be able to compile a new release for another week or so. 

It is strange, however, that you have regular issues with settings not getting saved. Can you try closing all the Excalidraw workspace panes before exiting Obsidian? Does that make saving more reliable for you?

**Comment by zsviczian** [comment]
so I found a way to "compile" a new version... Can you test this version of the main.js?
[main.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/6870343/main.zip)

**Comment by zsviczian** [comment]
I just released 1.2.9 update which corrects this error. Please confirm if it works for you. Thanks!

**Comment by zFrostz** [comment]
Yes, the new 1.2.9 update fixes the issue now! The settings are saved even when obsidian is relaunched.

Thank you very much for the help and also for building this amazing plugin which has been an indispensable part of the workflows of many people of the community including me. Best of luck to you for the future development of this plugin!
