### ISSUE TITLE
BUG: Failed to save library locally

### ISSUE THREAD

**Issue by matbun** [zsviczian/obsidian-excalidraw-plugin#1032]
**Your environment**
```text
SYSTEM INFO:
	Obsidian version: v1.1.15
	Installer version: v1.1.9
	Operating system: Windows 10 Pro 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 4
	Plugins enabled: 4
		1: Excalidraw v1.8.14
		2: Full Calendar v0.9.5
		3: Drag-n-Drop for blocks v1.2.0
		4: Advanced Tables v0.18.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```
**NOTE:** I am actually running Win 11!

```text
Edition	Windows 11 Pro
Version	22H2
Installed on	‎24/‎01/‎2023
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0
```

**Describe the bug**
Failed to save library on local system. I get the error message:
```text
The request is not allowed by the user agent or the platform in the current context.
```
Running Obsidian with Administrator rights did not solve the issue.

**To Reproduce**
1. Open a new sketch
2. Select one or more items from the side library (also your personal ones)
3. Click on the 3 dots above, in the library tab
4. Click on "Save to..."
5. Select save path
6. Error message appears and an empty library file is created.

**Expected behavior**
The custom library is correclty saved to disk.

**Screenshots**
To reproduce:
![image](https://user-images.githubusercontent.com/48362942/221145676-bef99516-a3b3-462d-b80c-7c0e2fec4982.png)

Error message:
![image](https://user-images.githubusercontent.com/48362942/221145171-f85b76a6-4f33-4ace-8a26-e77ee2fb8a5a.png)

**Comment by zsviczian** [comment]
yes, that does not work because it is prevented by the Obsidian framework. I will hide that menu option.
Instead use Command Palette `Excalidraw: Export Stencil Library`

**Comment by zsviczian** [comment]
I actually went ahead and properly implemented the save to... function instead of removing it from the menu and having you rely on the command palette. I will release it in 1.8.17
