### ISSUE TITLE
FR: 

### ISSUE THREAD

**Issue by why50** [zsviczian/obsidian-excalidraw-plugin#1033]
- Add a shortcut key to the setting panel of the element
You can switch the setting panel of the specified element freely with a simple shortcut key.

![image](https://user-images.githubusercontent.com/63858324/221364588-5a48aa58-5d31-436b-93df-557ec0033e1c.png)

**Comment by zsviczian** [comment]
add this script to Excalidraw/Scripts (or what ever you've set your script folder to be).
Assign a hotkey using Obsidian Settings.
Enjoy.
[Puppeteer.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/10831576/Puppeteer.md)

**Comment by why50** [comment]
Thanks for your help
