### ISSUE TITLE
BUG: Typo in SuggesterInfo

### ISSUE THREAD

**Issue by pokir** [zsviczian/obsidian-excalidraw-plugin#1035]
Typo [here](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/3a2d0640246c26c78ef5fcede5bb8e59d296250a/src/dialogs/SuggesterInfo.ts#L142-L143): 'toCliboard' should be 'toClipboard'

**Comment by zsviczian** [comment]
Thanks. fixed in 1.8.17
