### ISSUE TITLE
BUG: Typo in LINK_BUTTON_CLICK_NO_TEXT

### ISSUE THREAD

**Issue by pokir** [zsviczian/obsidian-excalidraw-plugin#1039]
Typo [here](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/41b1a170f775f365906a127b6c9ad249358c23f8/src/lang/locale/en.ts#L84): "Select a an ImageElement" should be "Select an ImageElement"

**Comment by zsviczian** [comment]
Thanks! fixed.
