### ISSUE TITLE
Feature Request: When [[ entered in text box filter list of Obsidian Notes

### ISSUE THREAD

**Issue by adxsoft** [zsviczian/obsidian-excalidraw-plugin#104]
Obsidian will filter and display selections after **[[** is typed in. 

Would be great if you could do this when entering Obsidian links into Excalidraw Text boxes.

Use case for me is that I am creating concept maps and it would be very handy to be able to choose the link target in the same way Obsidian filters and displays potential link targets.

If the same Obsidian logic could be used then could search note, blocks and lines etc.

My workaround is to open a temporary note in a separate pane and type links and choose what you require and then paste it into the Excalidraw drawing text box

Thank you for all the hard work .. its a brilliant plugin for Obsidian

**Comment by zsviczian** [comment]
Have you tried `CTRL+SHIFT+K` - or if the shortcut does not work: `Command Palette/Excalidraw: Insert link to file?`

I agree the feature would be great, but the Excalidraw component does not publish the events that would allow me to implement the feature.

One related feature which I hope to develop in the foreseeable future is drag and drop from the file explorer to create links.
