### ISSUE TITLE
BUG: Text Edit Problem

### ISSUE THREAD

**Issue by YIRU69** [zsviczian/obsidian-excalidraw-plugin#1048]
**Your environment**
New vision, Windows 10

**Describe the bug**
When I what to edit text. The text display too small or to big. I wish is fix the screen and easy to edit.
**To Reproduce**

![1](https://user-images.githubusercontent.com/48148292/222997272-a42edf4a-3a3f-4812-8d38-27499b2e221b.gif)

**Comment by zsviczian** [comment]
Please test 1.8.19 and let me know if it resolves your issue. I will release 1.8.19 in a few minutes.

**Comment by YIRU69** [comment]
I test and it not solve the problem.

**Comment by YIRU69** [comment]
I revisited this issue and observed a few things that I hope will be helpful to you. In Obsidian, the font for typing remains the same regardless of any changes made to the editing font. However, in the Excalidraw website, changing the font size also changes the editing font. You can verify this. @zsviczian

**Comment by YIRU69** [comment]
Obsidian
![1](https://user-images.githubusercontent.com/48148292/223638957-14a7b619-13c3-4d5a-965e-1ae002f24df4.gif)
Excalidraw
![2](https://user-images.githubusercontent.com/48148292/223638996-88df8f0f-78f8-45b5-bf7f-ff18c3ac650e.gif)

**Comment by zsviczian** [comment]
I am unable to reproduce the issue. Can I ask you to create a new Obsidian Vault, leave everything with default settings, install the Excalidraw plugin and see if you can reproduce the issue.

Also please run Command Palette / Show debug info and share the results with me.

**Comment by YIRU69** [comment]
I have located the problem myself based on your suggestions. The problem was that I added CSS to it. 
```
textarea{
	font-size: 15px !important;
}
```
Thank you.
