### ISSUE TITLE
BUG: LaTeX equation containing just a single vector in Excalidraw is not rendered fully

### ISSUE THREAD

**Issue by pokir** [zsviczian/obsidian-excalidraw-plugin#1053]
**Your environment**
```
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.0.0
	Operating system: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Obsidian gruvbox v0.1.8
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 5
		1: Quick Latex for Obsidian v2.5.1
		2: Advanced Tables v0.18.1
		3: MathJax WikiLinks v0.0.2
		4: Find orphaned files and broken links v1.8.0
		5: Excalidraw v1.8.19
```

**Describe the bug**
LaTeX equations which only include a single character vector such as $\vec f$, $\vec d$, and $\vec p$ are not shown fully to the end of the vector arrow. It looks as if the equation is cropped from the right side.

**To Reproduce**
1. Create an Excalidraw drawing
2. Press CTRL + L to enter LaTeX
3. Type `\vec f` and press enter
4. See result

**Expected behavior**
The vector arrow should be fully shown.

**Screenshots**
<img width="538" alt="Capture d’écran 2023-03-10 à 00 56 45" src="https://user-images.githubusercontent.com/80112484/224187909-3a5bfd6d-aac7-4b74-9f6b-a1c48bc98e20.png">

**Comment by zsviczian** [comment]
this seems to be an issue in the MathJax package. I added heuristics that for short formulas (less than 2ex long) I add 1ex extra to the width of the SVG.
