### ISSUE TITLE
BUG: Excalidraw file crashes Obsidian

### ISSUE THREAD

**Issue by keolo** [zsviczian/obsidian-excalidraw-plugin#1054]
## Environment

```
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.1.9
	Operating system: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 22.3.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 6
	Plugins enabled: 6
		1: Calendar v1.5.10
		2: Dataview v0.5.55
		3: Periodic Notes v0.0.17
		4: Templater v1.16.0
		5: Excalidraw v1.8.19
		6: Readwise Official v2.0.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

## Issue

Loading the attached file (which was created with the Excalidraw plugin) crashes Obsidian and I'm not able to do anything except close the window.

I'm only able to get Obsidian working again by removing `"obsidian-excalidraw-plugin"` in `community-plugins.json`.

This is a fairly detailed diagram and it's 538kb, do you think that might be source of the issue?

## Reproduction

1. Install Excalidraw extension
2. Open the attached file

**Expected behavior**

File loads and I can use Obsidian/Excalidraw normally.

## File

[Lesson - System Design.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/10937388/Lesson.-.System.Design.excalidraw.md)

**Comment by zsviczian** [comment]
First, I am really sorry about the issue.  It is proving to be a challenging one to resolve. I know the element that is causing the issue but do not yet know why... in the meantime, here's the drawing. this will open without issues.

[fixed.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/11011088/fixed.zip)

The read label attached to the arrow is the culprit. Is there anything special you can tell me about how you created this?

![image](https://user-images.githubusercontent.com/14358394/226177268-2dc5656f-533d-4ba5-b6a8-9077db120ec3.png)

**Comment by zsviczian** [comment]
Got it fixed. Took the entire day. Will release in 1.8.20 later on today

**Comment by keolo** [comment]
I'm glad you were able to track down the issue. Thank you both for this plug-in, it's very useful!
