### ISSUE TITLE
FR: Add shortcut to create link

### ISSUE THREAD

**Issue by jzhang-brex** [zsviczian/obsidian-excalidraw-plugin#1056]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

When select an element, press ⌘K will add a link to the selected elements. This will either override Obsidian's global hotkey or allow user to specify another if there is a conflict.

**Describe alternatives you've considered**

**Additional context**

**Comment by zsviczian** [comment]
Yes, the conflict with Obsidain shortcuts is a difficulty. I don't have a quick solution for you, I'll think about the issuue.

**Comment by zsviczian** [comment]
Fixed in 1.8.20
