### ISSUE TITLE
Bug: error loading LZString compressed excalidraw drawing

### ISSUE THREAD

**Issue by PhysicsBeyond** [zsviczian/obsidian-excalidraw-plugin#1062]
Hello,

Firstly, thanks for all the hard work on this amazing plugin!

I have encountered a nasty error today: 
![image](https://user-images.githubusercontent.com/104894069/225900304-83422c87-e327-4fbd-8f2c-275aa3503af4.png)
Said file was displaying and working perfectly fine this morning. It now opens in Obsidian with the LZ-compressed json data (attached).

I have tried to recover previously saved versions of the file by Obsidian, but am getting the same error for the majority of them. Only the saved versions previous to the 16:05 GMT+1 timestamp yesterday afternoon do work. There were no issues while working on it yesterday and this morning, as I said.

Since the excalidraw plugin does not decompress the LZ-string, I suspect the fault lies there; but don't understand why it would suddenly stop working today, as it has been fine yesterday and I haven't installed or updated anything on Obsidian since then. CHKDSK does not report any issues either, so it shouldn't be a HDD issue.

I have tried to decompress the LZString on the website provided by the plugin: [here](https://pieroxy.net/blog/pages/lz-string/demo.html) as well as [here](https://lzstring.azurewebsites.net/Decompress?handler=ConvertLzStringCompress). None did work, but also didn't work on the compressed strings, which do work in Obsidian.

Is there a way to check whether the compressed LZ-string is compromised? 

Thanks!

Obsidian version 1.1.6
Excalidraw plugin version 1.8.19
OS: Windows 11 Pro Version 10.0.22621 Build 22621
 
[compressed json of excalidraw file UTF-8.txt](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/11001323/compressed.json.of.excalidraw.file.UTF-8.txt)

**Comment by zsviczian** [comment]
Very strange. Thank you for raising this. This was an unexpected error (well... all errors are such :) )
This is the culprit, but I don't yet know why:
![image](https://user-images.githubusercontent.com/14358394/226158211-60838e9b-72da-414a-8f81-35b23a24e73c.png)

This should now load correctly. I will release an update today that addresses this error.

[Drawing 2023-03-04 18.56.excalidraw.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/11010389/Drawing.2023-03-04.18.56.excalidraw.zip)

**Comment by zsviczian** [comment]
can you tell me more about this "See this counter example" element. How did you create it?
