### ISSUE TITLE
BUG: (Mobile). Copy group reference button action doesn't work

### ISSUE THREAD

**Issue by pikatwinky** [zsviczian/obsidian-excalidraw-plugin#1063]
Hi, I'm sorry if this is a FR instead of a bug report, but i think with the arrive of the side bar in the Obsidian command palette the gesture to create a "group" reference has stopped working
![Screenshot_2023-03-19-08-06-22-488-edit_md obsidian](https://user-images.githubusercontent.com/31860235/226181485-003219b2-705a-4d35-80f6-2220e46eee45.jpg)
...
I guess in previous versions were something like a long press, but now a long press allows you to pin commands in the side bar

I wish it could be possible to select the area/section/group options once you were in this part of the command
![Screenshot_2023-03-19-08-12-23-547-edit_md obsidian](https://user-images.githubusercontent.com/31860235/226181950-3326edcb-0cd2-4ce0-a695-14215b9b2a54.jpg)

My workaround just now is adding the "group=" sintax directly on my markdown file links, but that is kinda time consuming 

Im using excalidraw 1.8.16 on the latest obsidian public release

SO: Android 12

Thank you for your hard work!

**Comment by zsviczian** [comment]
This is probably a feature request, however, it is a good idea, I'll add additional buttons to this window for the different type of links. I think it is also more intuitive even for desktop users.

**Comment by zsviczian** [comment]
I've added this feature to 1.8.22. Hope to release the update this weekend
