### ISSUE TITLE
BUG: Add to Excalidraw button from libraries.excalidraw.com seems not work on mac

### ISSUE THREAD

**Issue by broven** [zsviczian/obsidian-excalidraw-plugin#1064]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 22.2.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 12
	Plugins enabled: 12
		1: Calendar v1.5.10
		2: Advanced Tables v0.17.3
		3: Dataview v0.5.47
		4: Tasks v1.15.1
		5: Paste URL into selection v1.7.0
		6: Folder Note v0.7.3
		7: Local images v0.14.2
		8: Templater v1.14.3
		9: Kanban v1.4.6
		10: Banners v1.3.3
		11: Editor Syntax Highlight v0.1.3
		12: Excalidraw v1.8.20

**Describe the bug**
I was try to import some icon from [excalidaraw library](https://libraries.excalidraw.com/?target=_blank&referrer=app%3A%2F%2Fobsidian.md&useHash=true&token=VuX-QSoe_FsP_kw-ssnX9&theme=light&version=2&sort=default), after click the `➡️ Add to Excalidraw` button, I got a schema, It seems not work (just hang), the link is: 

```
app://obsidian.md#addLibrary=https%3A%2F%2Flibraries.excalidraw.com%2Flibraries%2Fchildishgirl%2Faws-architecture-icons.excalidrawlib&token=VuX-QSoe_FsP_kw-ssnX9
```

In my limited understanding, the obsidian schme should be like `obsidian://open?xx`

**To Reproduce**
1. Click "Browse libraries" from Library panel
2. Pick one libaray, then click "➡️ Add to Excalidraw"

**Expected behavior**
should add to obsidian-excalidraw

**Additional context**
Sorry about the pool english, let me know if some sentence is confused you, thank you!
1

**Comment by zsviczian** [comment]
The "add library" feature on the excalidraw library site does not work with Obsidian, regardless of your operating system. This is due to the Obsidian architecture.

Do this: 
- download the library to your local downloads folder
- in obsidian-excalidraw click open library and load it manually.

![image](https://user-images.githubusercontent.com/14358394/229287585-253f8e5a-f04e-42f4-86b7-adf9d1f99b9a.png)
