### ISSUE TITLE
BUG: unable to insert section of the embed document (ctrl +alt)

### ISSUE THREAD

**Issue by Dennyyusuf** [zsviczian/obsidian-excalidraw-plugin#1070]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.1.16
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v6.3.2
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 51
	Plugins enabled: 19
		1: MAKE.md v0.6.23
		2: Media Extended v2.11.1
		3: Minimal Theme Settings v6.3.1
		4: obsidian markmind v1.6.8
		5: Outliner v4.3.0
		6: Readwise Official v2.0.1
		7: Surfing v0.8.16
		8: Tag Wrangler v0.5.7
		9: Zoom v1.1.1
		10: Multi-Column Markdown v0.7.7
		11: Metadata Menu v0.4.21
		12: ExcaliBrain v0.1.11
		13: Excalidraw v1.8.20
		14: Dataview v0.5.55
		15: Style Settings v1.0.3
		16: Customizable Page Header and Title Bar v4.7.2
		17: Hover Editor v0.11.9
		18: Frontmatter Links v1.2.7
		19: Obsidian42 - Strange New Worlds v1.1.4

**Describe the bug**
Unable to insert section of the Markdown Embeds with using ctrl +alt click of the document

**To Reproduce**
1. Go to 'Excalidraw drawing and insert markdown'
2. hold ctrl + alt + Click on 'embed document'
3. it opens the document on the new pane

**Expected behavior**
it should open a box to insert the section of the document.

**Comment by zsviczian** [comment]
shortcuts were updated and aligned between Mac and Win in [1.8.16](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.8.16). 

The new key combo is CTRL+WIN

![](https://raw.githubusercontent.com/zsviczian/obsidian-excalidraw-plugin/master/images/excalidraw-modifiers.png)
