### ISSUE TITLE
BUG: Drawings are not in dark mode

### ISSUE THREAD

**Issue by matteoturini** [zsviczian/obsidian-excalidraw-plugin#1080]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.1.16
	Operating system: Arch Linux
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 16
		1: Dataview v0.5.55
		2: Calendar v1.5.10
		3: Kanban v1.5.2
		4: Advanced Tables v0.18.1
		5: Templater v1.16.0
		6: Admonition v9.2.1
		7: Natural Language Dates v0.6.1
		8: Editor Syntax Highlight v0.1.3
		9: LanguageTool Integration v0.3.3
		10: Execute Code v1.7.1
		11: Dictionary v2.22.0
		12: Obsidian Functionplot v1.2.1
		13: Excalidraw v1.8.19
		14: Annotator v0.2.10
		15: Tasks v1.25.0
		16: Spaced Repetition v1.10.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
When embedding drawings, they always appear in light mode, regardless of the drawing's or obsidian's theme.
**To Reproduce**
1. Make a drawing
2. Switch it to dark mode
3. Embed it
4. It's light in the preview/embed
**Expected behavior**
1. Make a drawing
2. Switch it to dark mode
3. Embed it
4. It's dark in the preview/embed
**Screenshots**
![2023-04-03_12:23:10](https://user-images.githubusercontent.com/69425093/229555146-c422e861-352b-4525-993c-9107fded0319.png)
![2023-04-03_12:22:51](https://user-images.githubusercontent.com/69425093/229555137-b0f9b9e9-cb7c-4915-99aa-aabc89ab0665.png)

**Additional context**
Additionally, Dark mode is reset every time the drawing is opened.

**Comment by zsviczian** [comment]
This behavior is influenced by a number of plugin settings, plus settings in the front matter of your drawing. 

Please play with these settings a little and if the issue persists let me know.

![image](https://user-images.githubusercontent.com/14358394/229774008-6464c86c-9186-4922-bd55-6fd505bcfd26.png)

![image](https://user-images.githubusercontent.com/14358394/229774159-cba8414e-f4e2-49e0-91b0-89cfd5866d64.png)

**Comment by matteoturini** [comment]
That also explains when reopening the drawing why it goes back to light mode.

**Comment by zsviczian** [comment]
In 1.8.23 the file will get automatically saved when the theme changes.
