### ISSUE TITLE
FR: 

### ISSUE THREAD

**Issue by zb5700** [zsviczian/obsidian-excalidraw-plugin#1086]
As you say in the problem #995                  As Obsidian added new ways of opening documents, the Excalidraw plugin did not keep up, resulting in the current, somewhat chaotic approach.   It is time to solve that chao now.  The old option of opening in adjacent panel is prefect for me. Although the option is still here but it is not working now. It will be better if you can fix it!!

**Comment by zsviczian** [comment]
have you reviewed this before raising the FR?
https://github.com/zsviczian/obsidian-excalidraw-plugin#hyperlinks-and-drag--drop-support
Obsidian-Excalidraw 1.8.16 - QoL Improvements: Keyboard Shortcuts
https://youtu.be/9HlipSIzRhc

**Comment by zb5700** [comment]
It is great to find that you have already to solve that problem.but I find difficult to open the video in China. What is the shortcut to open the markdown link in splitting panel in the same window?



发自我的iPhone


------------------ Original ------------------
From: zsviczian ***@***.***&gt;
Date: Sun,Apr 9,2023 2:47 AM
To: zsviczian/obsidian-excalidraw-plugin ***@***.***&gt;
Cc: zb5700 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [zsviczian/obsidian-excalidraw-plugin] FR:  (Issue #1086)

**Comment by zsviczian** [comment]
Use this cheat sheet.
Try CTRL+ALT (CMD + OPT).

![](https://raw.githubusercontent.com/zsviczian/obsidian-excalidraw-plugin/master/images/excalidraw-modifiers.png)

**Comment by zb5700** [comment]
It is done,That is amazing! Thank you very much, excalidraw is a great work!&nbsp;



发自我的iPhone


------------------ Original ------------------
From: zsviczian ***@***.***&gt;
Date: Sun,Apr 9,2023 1:37 PM
To: zsviczian/obsidian-excalidraw-plugin ***@***.***&gt;
Cc: zb5700 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [zsviczian/obsidian-excalidraw-plugin] FR:  (Issue #1086)
