### ISSUE TITLE
FR: turn off the full screen feature on the F key

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#1095]
Hello, @zsviczian ! I am writing to you, not Excalidraw, because sometimes they take a very long time to make changes (which is normal because development is complex and there are many things to consider), but 

- [x] could you temporarily implement this function or is it better to write to the official guys ?

**Is your request for an opportunity related to the problem? Please describe it.**
When I draw something, I use the s/g + q/w/e/r/t/a/s/d/**F**/g etc. keys, to change colors. Sometimes I don't pay attention to what tool I have in my hand, whether I have the tool settings palette open or not, I press s/g + **F** and it causes a full screen command that freezes (adjusting the program to new size) the entire obsidian for a second, if there are multiple drawings open, it can take 5 seconds... it takes you out of your thinking.

**Describe the solution you would like to have**.
I would like to disable the full screen function from the **F** key as it causes the entire workflow to freeze and you can enter full screen mode by pressing the f11 key. 

**Describe the alternatives you have considered**.
I don't see any alternatives. Maybe I'm too tired of this problem. 
Please remove the function from this key, even if the word "full screen" starts with F

**Additional Context**.
Demonstration freezes (adjusting the program to new size) of using the F and F11 keys. 
1. First, I forget to open the command palette to make the color change hotkeys work (sometimes this also triggers the full screen function)
2. I accidentally press the F key when the palette is closed, which causes a full screen (I don't need it and makes me wait...). 
3. Demonstrate that I can go to full screen via the f11 key

https://user-images.githubusercontent.com/71871141/232025101-5167ae61-ed0b-407f-bdad-385bfc757cbe.mp4

Thank you for your attention !🪴

**Comment by zsviczian** [comment]
I agree, F feels like an unfortunate key for going to full screen. 
Shortcuts altogether are a problem with Excalidraw in Obsidian.
F11 is a viable alternative, though I don't know the alternatives on Mac and Linux and Obsidian mobile... however I have a command palette action for going full-screen as well, so people should have plenty of other options. I will remove the shortcut and see if anyone complains 😉

**Comment by zsviczian** [comment]
will release in the next update.

**Comment by anatoliibakhtin** [comment]
now the quick color change keys don't work unless I first activate (click) the color picker. 

https://user-images.githubusercontent.com/71871141/232229376-d82b5157-0b53-4a70-a040-1b8d3a950361.mp4
