### ISSUE TITLE
FR: Copy block reference of text-less element to embed the bounding box in Obsidian note

### ISSUE THREAD

**Issue by jshph** [zsviczian/obsidian-excalidraw-plugin#1096]
**Is your feature request related to a problem? Please describe.**
When I'm making a large diagram, and I want to visually reference parts of it within an existing Obsidian note, I have to create a box, then a heading within that box, and link it manually

**Describe the solution you'd like**
I'd like to see whether it's possible to have an Excalidraw Script to copy a reference to a box element, even if it doesn't have text in it -- just an id.

**Comment by zsviczian** [comment]
Good news! The feature is already available.

Select the element you want to reference. Click the `copy markdown link for selected element` button, and click the link button.

Once you copy the link to the clipboard you can add the link to any element (not only text elements) or to any of your markdown documents.

Watch this video to understand the meaning of the Group and Area buttons: https://youtu.be/yZQoJg2RCKI

![image](https://user-images.githubusercontent.com/14358394/232188427-d22cefcf-b259-4fb6-bc71-8d1ad85ea5f7.png)

**Comment by jshph** [comment]
That's great news :)

Thanks for walking through that!
