### ISSUE TITLE
BUG: hotkeys change colors don't work in 1.8.23

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#1097]
Wrote here: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1095#issuecomment-1509848171
If you do not have such a problem, I will attach additional info.

**Comment by zsviczian** [comment]
You probably want to open an issue with the main package as based on my testing hotkeys also do not work on excalidraw.com... this issue has no relation the #1095

**Comment by anatoliibakhtin** [comment]
Just to clarify, did you check on the public version of excalidraw.com ? If so, it works for me:

https://user-images.githubusercontent.com/71871141/232325612-18c82a41-d985-4a8c-9799-c7e6fc94ea07.mp4


If not, where could I also check it myself first and then write to you or to excalidraw ?

**Comment by zsviczian** [comment]
ah... I can now reproduce... 
when was this last working?

**Comment by anatoliibakhtin** [comment]
1.8.22

**Comment by zsviczian** [comment]
The issue is lots of changes happened between 1.8.22 and 1.8.23... I will investigate. I hope to release an update tonight, if that does not work out, then the earliest is end of the week... due to travel and work.
