### ISSUE TITLE
BUG: Area embed link of svg inside excalidraw embed entire svg instead of area

### ISSUE THREAD

**Issue by ml-koch** [zsviczian/obsidian-excalidraw-plugin#1098]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.1.9
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Things v2.1.6
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 27
	Plugins enabled: 26
		1: Dataview v0.5.55
		2: Kanban v1.5.1
		3: Calendar v1.5.10
		4: Obsidian Git v2.16.0
		5: Templater v1.16.0
		6: Tasks v1.25.0
		7: Advanced Tables v0.18.1
		8: Tag Wrangler v0.5.6
		9: Periodic Notes v0.0.17
		10: Homepage v2.7.3
		11: Pandoc Plugin v0.4.1
		12: Rollover Daily Todos v1.1.4
		13: Zotero Integration v2.3.2
		14: Citations v0.4.5
		15: Outliner v4.2.1
		16: Obsidian Charts v3.7.1
		17: Admonition v9.2.1
		18: Icon Folder v1.6.0
		19: Natural Language Dates v0.6.1
		20: Reminder v1.1.15
		21: Pandoc Reference List v1.2.11
		22: cMenu v1.1.2
		23: Style Settings v1.0.2
		24: Excalidraw v1.8.14
		25: Obsidian Functionplot v1.2.1
		26: Extended MathJax v0.4.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
I am trying to insert a large svg file (10MB) created from 50 pages of pdf slides in Excalidraw.
Then I want to draw rectangles around every single slide to embed them later into other notes. 
The problem is the are links always embed the entire svg in the notes and not just the area of the rectangle field.

**To Reproduce**
1. Insert large svg in Excalidraw
2. Create rectangle field with text
3. Select rectangle field
4. Create area type markdown link
5. move to other note
6. Embed link with ![[]] format
7. Embedded image is either blank or the entire svg file instead of the area around the rectangle field

**Expected behavior**
I expect an embedded image of just the area in the rectangle.

**Screenshots**
Excalidraw drawing with svg file and rectangle
![grafik](https://user-images.githubusercontent.com/120103502/232590735-8246a303-56e2-463a-837b-74ba4c92a627.png)
Link
![grafik](https://user-images.githubusercontent.com/120103502/232591010-02b1950c-5f67-449a-b115-a0a30a835b51.png)
Resulting very long complete svg file instead of just area
![grafik](https://user-images.githubusercontent.com/120103502/232591043-24f339cb-aa7f-4bc0-b56b-2edece00b22b.png)

**Additional context**
Using the group link only outputs the rectangle with a blank background
![grafik](https://user-images.githubusercontent.com/120103502/232591270-ca376d4c-5603-49a3-8618-1aa205c0a4ee.png)

**Comment by zsviczian** [comment]
Fixed in 1.8.24
