### ISSUE TITLE
Line Endings affect usage of excalidraw plugin

### ISSUE THREAD

**Issue by mohanen** [zsviczian/obsidian-excalidraw-plugin#111]
# Files are identical except for differing line endings:
	Drawing.excalidraw.md: UNIX (LF)
	Drawing.excalidraw.md: DOS/Windows (CR-LF)

UNIX (LF) line endings works, 
DOS/Windows (CR-LF) The plugin fails to recognize the file contents.

Why the line endings changed, I sync my notes with github and different client is handling in different way based on platform.

![image](https://user-images.githubusercontent.com/20907037/127541796-f676d69f-1a1b-4de6-bdc3-b3d798840ccb.png)

**Comment by mohanen** [comment]
To fix in git, set this 

`git config --global core.autocrlf input`

But still I think it should be handled in plugin,

**Comment by zsviczian** [comment]
Thanks! will look into this

**Comment by zsviczian** [comment]
@mohanen I made some minor tweaks to the application logic. Can you double-check if with the latest version the issue still persists?

**Comment by zsviczian** [comment]
Hi @mohanen, did you have a chance to check if the tweaks in 1.2.14 resolved the line endings issue?

**Comment by mohanen** [comment]
Hi @zsviczian, Sorry was busy for a while, Tested with 1.2.16. Still not fixed it seems. 

Reproduction Steps:
1. Open Drawing VS Code
2. Click "Select End of Line Sequence" From the right bottom of vs code status bar
3. Change From LF to CRLF
4. Save the Drawing "Ctrl + S" 
5. Open the Diagram in obsidian -> "Won't Open"

**Comment by HueLiu** [comment]
Obsidian version: 0.12.15
Excalidraw  plugin vesion: 1.3.11

The CRLF and LF issue could be reproduced. I use git for Windows and Working Copy on iOS. The file will not open after each Git push and pull.

**Comment by zsviczian** [comment]
@mohanen, sorry I missed your reply from a month ago. Great tip on reproducing the issue. I'll try to get this fixed over the coming weekend.

**Comment by zsviczian** [comment]
See [v1.3.12](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.3.12)
