### ISSUE TITLE
templater_mindmap.md example in docs error

### ISSUE THREAD

**Issue by adxsoft** [zsviczian/obsidian-excalidraw-plugin#112]
**Describe the bug**

**templater_mindmap.md** example templater script fails with console.log message

_Template parsing error, aborting. Cannot read property '1' of null
log_error_

**To Reproduce**
1. Download sample file and templater script
2. In Sample File go to end of file and invoke the templater script

**Expected behavior**
Should execute the templater script and create the mindmap

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS High Sierra
 - Obsidian 0.12.11
 -
![Screen Shot 2021-07-30 at 4 19 58 pm](https://user-images.githubusercontent.com/24862237/127609652-7f163b59-3f08-48e4-a241-58329a0c871e.png)

**Comment by zsviczian** [comment]
The script works for me without issues, I just downloaded the sample from [here](https://zsviczian.github.io/obsidian-excalidraw-plugin/Examples/templater_mindmap.html).

The provided Templater script is just an example, it does not include any proper error/exception handling.

You write: *"In Sample File go to end of file and invoke the templater script"* 
- I was able to reproduce your error by adding an empty line after Test 3.1.
- Make sure there are no empty lines after the last bullet of the input file and try the script again. Does it work now?
- If you need to have an empty line after Test 3.1, make the necessary changes to the provided example.

Thanks!

**Comment by adxsoft** [comment]
Hi

I followed your instructions and ensured there was no empty line after Test 3.1 and it worked!

Thanks
Allan @ adxsoft



I
