### ISSUE TITLE
BUG: Hardware eraser not working

### ISSUE THREAD

**Issue by Janderhacker** [zsviczian/obsidian-excalidraw-plugin#1120]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.2.7
	Installer version: v1.1.16
	Operating system: #1 SMP PREEMPT_DYNAMIC Fri, 28 Apr 2023 17:09:57 +0000 6.2.13-arch1-1-surface
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Things v2.1.6
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 7
		1: Obsidian Git v2.19.1
		2: Advanced Tables v0.18.1
		3: Excalidraw v1.8.26
		4: Quick Latex for Obsidian v2.6.1
		5: LanguageTool Integration v0.3.3
		6: Mathpad v0.8.14
		7: Mermaid Tools v0.2.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
The hardware eraser script is not working for my surface pen. I also installed the auto-draw script and it works.

**Expected behavior**
Hardware eraser should erase, but it doesn't register. It works on other drawing apps such as xournal++.

**Additional context**
Running arch linux with the newest surface kernel.

**Comment by zsviczian** [comment]
Are you referring to the [Hardware Eraser Support](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Hardware%20Eraser%20Support.md) script? Maybe @threethan can help.

**Comment by threethan** [comment]
Try disabling my AutoDraw script. They *should* work together, but can sometimes interfere.

The script detects the eraser by looking for pointer button 32. If it's not activating, that's because it's not seeing that input. It's possible that linux uses a different method to differentiate the eraser, or that chromium handles it differently than on Windows.

I only have an active linux install on my desktop. Could you run:
 `function ppe(e) {console.log(e);}; window.addEventListener('pointerdown',ppe);`
 in the console, then give reply with example outputs of 1. pen tip touch and 2. pen eraser touch?

**Comment by Janderhacker** [comment]
The output for the pen tip is:
```
VM185:1 PointerEvent {isTrusted: true, pointerId: 2, width: 1, height: 1, pressure: 0, …}
isTrusted: true
altKey: false
altitudeAngle: 1.5707963267948966
azimuthAngle: 0
bubbles: true
button: 0
buttons: 1
cancelBubble: false
cancelable: true
clientX: 429.1429443359375
clientY: 247.42861938476562
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
fromElement: null
height: 1
isPrimary: true
layerX: 84
layerY: 168
metaKey: false
movementX: 0
movementY: 0
offsetX: 84.14292907714844
offsetY: 168.9911346435547
pageX: 429.1429443359375
pageY: 247.42861938476562
path: (17) 
[canvas.excalidraw__canvas, main, div.excalidraw.excalidraw-container.excalidraw--mobile, div.excalidraw-wrapper, div.view-content.excalidraw-view, div.workspace-leaf-content.node-insert-event, div.workspace-leaf.mod-active, div.workspace-tab-container, div.workspace-tabs.mod-active.mod-top, div.workspace-split.mod-vertical.mod-root, div.workspace.is-right-sidedock-open.is-left-sidedock-open, div.horizontal-main-container, div.app-container, body.theme-dark.mod-linux.is-frameless.is-hidden-frameless.obsidian-app.show-inline-title.show-view…, html, document, global]
pointerId: 2
pointerType: "pen"
pressure: 0
relatedTarget: null
returnValue: true
screenX: 429.14288330078125
screenY: 247.4285888671875
shiftKey: false
sourceCapabilities: null
srcElement: canvas.excalidraw__canvastangential
Pressure: 0
target: canvas.excalidraw__canvas
tiltX: 0
tiltY: 0
timeStamp: 344696.1
toElement: null
twist: 0
type: "pointerdown"
view: global {0: global, 1: Window, window: global, self: global, document: document, name: '', location: Location, …}
which: 1
width: 1
x: 429.1429443359375
y: 247.42861938476562
doc: (...)
targetNode: (...)
win: (...)[[Prototype]]: PointerEvent
```

The output for the eraser is:
```
VM185:1 PointerEvent {isTrusted: true, pointerId: 2, width: 1, height: 1, pressure: 0, …}
isTrusted: true
altKey: false
altitudeAngle: 1.5707963267948966
azimuthAngle: 0
bubbles: true
button: 0
buttons: 1
cancelBubble: false
cancelable: true
clientX: 505.1429443359375
clientY: 277.71429443359375
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
fromElement: null
height: 1
isPrimary: true
layerX: 160
layerY: 199
metaKey: false
movementX: 0
movementY: 0
offsetX: 160.14292907714844
offsetY: 199.27679443359375
pageX: 505.1429443359375
pageY: 277.71429443359375
path: (17) [canvas.excalidraw__canvas, main, div.excalidraw.excalidraw-container.excalidraw--mobile, div.excalidraw-wrapper, div.view-content.excalidraw-view, div.workspace-leaf-content.node-insert-event, div.workspace-leaf.mod-active, div.workspace-tab-container, div.workspace-tabs.mod-top.mod-active, div.workspace-split.mod-vertical.mod-root, div.workspace.is-right-sidedock-open.is-left-sidedock-open, div.horizontal-main-container, div.app-container, body.theme-dark.mod-linux.is-frameless.is-hidden-frameless.obsidian-app.show-inline-title.show-view…, html, document, global]
pointerId: 2
pointerType: "pen"
pressure: 0
relatedTarget: null
returnValue: true
screenX: 505.14288330078125
screenY: 277.71429443359375
shiftKey: false
sourceCapabilities: null
srcElement: canvas.excalidraw__canvastangential
Pressure: 0
target: canvas.excalidraw__canvas
tiltX: 0
tiltY: 0
timeStamp: 1038164.1
toElement: null
twist: 0
type: "pointerdown"
view: global {0: global, 1: Window, window: global, self: global, document: document, name: '', location: Location, …}
which: 1
width: 1
x: 505.1429443359375
y: 277.71429443359375
doc: (...)
targetNode: (...)
win: (...)[[Prototype]]: PointerEvent
```
