### ISSUE TITLE
FR: paste style from custom pencil panel to selected elements

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#1125]
**Is your feature request related to a problem? Please describe.**
When I use drawing, I mainly use the colors that are in my customized pens.To recolor other objects in the same colors I have to open the panel choose a color close the panel and it still takes up the whole screen I thought it would be great to just click on these customized pens.

**Describe the solution you'd like**
I want to select objects with one click on the custom pen to recolo, resize them all according to the value set in the custom pencil settings.

The pencils themselves are the same as the customized material type or style settings. So it seems to me that in the future they will turn into materials, and tools are on top.

**Describe alternatives you've considered**
I don't know yet

**Additional context**
An example of how I see it

https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/71871141/c24fcce7-f24b-46d0-a5a2-d91fee719f1a

(It is important to note that the elements remain selected after they are recolored so that I can later move them or recolor them again)

Upd: Most likely, the paste style function should be used here (It can be found from the context menu).

Thank you for your attention! 🌳

**Comment by zsviczian** [comment]
this is a nice idea. Fully doable. I add it to the list.

**Comment by anatoliibakhtin** [comment]
No longer necessary, since I made my own pie menu script: [Paint pie menu.md](https://github.com/user-attachments/files/17346008/Paint.pie.menu.md)

When the script is called, depending on where you move the mouse, one of 4 functions will be called: up - move to the topmost layer or bottom; down - select color; left - change transparency; right - chan
ge ink thickness (does not affect the font). Directions can be easily changed in the code itself if other variations are needed. The script itself is written with gpt. 

maybe I'll change it in the future
