### ISSUE TITLE
The suggestions for browsing.

### ISSUE THREAD

**Issue by kin30528** [zsviczian/obsidian-excalidraw-plugin#1140]
Hi, zsviczian. thanku ur pluging. I propose to add the functions：

1. At present, when I use the plug-in of excalidraw, I can only use <kbd>Ctrl</kbd>+ <kbd>+</kbd> to zoom in first, and then use the hand tool to move to the part I want to see. I hope to add a function like Photoshop's magnifying glass. Just by using this tool, I can zoom in and browse the part I want to see at the same time.

With the shortcut <kbd>Ctrl</kbd> + <kbd>left mouse button</kbd> (zoom in) and <kbd>Ctrl</kbd> + <kbd>alt</kbd> + <kbd>left mouse button</kbd> (zoom out) would be perfect.

**Comment by anatoliibakhtin** [comment]
Hi @kin30528, I'm not zsviczian, but I want to help take the idea further, as the hotkeys interest me too.

In other words, you want to 1) add the ability to change the excalidraw hotkeys; and 2) add to obsidian the ability to use the mouse as a hotkey; maybe also 3) make the obsidian and obsidian-excalidraw plugin hotkeys not argue with each other.

But you can select part of the drawing with the cursor and 1) press the excalidraw hotkey or 2) call the script (with any of your keys, but not the mouse) to get even closer:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/71871141/1edf9251-4a40-428b-90cc-30a224ddd37c)

**Comment by kin30528** [comment]
> Hi @kin30528, I'm not zsviczian, but I want to help take the idea further, as the hotkeys interest me too.
> 
> In other words, you want to 1) add the ability to change the excalidraw hotkeys; and 2) add to obsidian the ability to use the mouse as a hotkey; maybe also 3) make the obsidian and obsidian-excalidraw plugin hotkeys not argue with each other.
> 
> But you can select part of the drawing with the cursor and 1) press the excalidraw hotkey or 2) call the script (with any of your keys, but not the mouse) to get even closer: ![image](https://user-images.githubusercontent.com/71871141/239510412-1edf9251-4a40-428b-90cc-30a224ddd37c.png)

Wow, The method is very helpful to me, thx u!😊

**Comment by anatoliibakhtin** [comment]
Cool!) Then you can close this thread, I'll create a new one later on the request to add the ability to edit hotkeys in excalidraw.
