### ISSUE TITLE
FR: Can you add a button to change frontmatter excalidraw export padding in canvas settings?

### ISSUE THREAD

**Issue by hua03** [zsviczian/obsidian-excalidraw-plugin#1147]
If you want to change  excalidraw export padding in frontmatter, you have to switch markdown mode, it's a bit inconvenient to operate. And I sometime forget how to set frontmatter excalidraw export padding up.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/19561959/d49dabbe-0c16-4a7e-b491-591521780f0e)

**Comment by zsviczian** [comment]
You can change these settings in the Export Image dialog. See the Export image button on your screenshot. You can choose to save these settings or have them as one time export settings.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/5561c428-5fa4-42d5-8694-da6ef2bd0cb9)

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/90eb546b-9996-461e-a627-fd32e27592f4)

**Comment by hua03** [comment]
Thank you, it's very nice 👍  . It seems that I need to spend more time familiarizing myself with this plugin.
