### ISSUE TITLE
How can I achieve that when I want to use Chinese handwritten fonts?

### ISSUE THREAD

**Issue by cuijiahuawx** [zsviczian/obsidian-excalidraw-plugin#115]
I want to use Chinese handwritten fonts in obsidian-excalidraw-plugin.
Could you give a menu to change fonts in the setting?
Thank you very much for your amazing work!

**Comment by zsviczian** [comment]
There is already an open issue for this #14. 
There is now a solution approach that I plan to implement in the coming few weeks.
