### ISSUE TITLE
Add possibility to remove automatic "excalidraw" tag in YAML frontmatter.

### ISSUE THREAD

**Issue by ronny3** [zsviczian/obsidian-excalidraw-plugin#1152]
Hello. As we [can't](https://forum.obsidian.md/t/exclude-a-specific-tag-from-the-graph-view/33842) [exclude](https://forum.obsidian.md/t/exclude-known-template-locations-from-tag-counting/7061) tags on a higher level, I hope to be able to remove the "excalidraw" tag that is added automatically to new drawings. I recently have gotten into tags, and very unnecessarily the excalidraw is topping my list. I tried to manually delete it from a drawing and saw no issues, so I guess it should be fine to simply not add it automatically?

I found no other issues relating to this, only [this](https://forum.obsidian.md/t/how-to-prevent-excalidraw-from-generating-a-yaml-tag-in-each-file/45898) dead post.

I see no reason to not add this feature to give us more control over our tags?
Thanks.

**Comment by anatoliibakhtin** [comment]
Hello! Remove it from the template for the excalidraw file (I just commented it out myself)
https://www.youtube.com/watch?v=ibdS7ykwpW4&ab_channel=Zsolt%27sVisualPersonalKnowledgeManagement

**Comment by ronny3** [comment]
@anatoliibakhtin thats great. Thanks!
