### ISSUE TITLE
BUG: Latex equation seems to get "linked" when you duplicate it

### ISSUE THREAD

**Issue by declanoller** [zsviczian/obsidian-excalidraw-plugin#1153]
**Your environment**
```
SYSTEM INFO:
	Obsidian version: v1.3.4
	Installer version: v0.15.9
	Operating system: #43~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 21 16:51:08 UTC 2 5.19.0-42-generic
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Obsidian Nord
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 6
	Plugins enabled: 6
		1: Obsidian Git v2.19.1
		2: Excalidraw v1.8.22
		3: Extended MathJax v0.4.1
		4: Mousewheel Image zoom v1.0.18
		5: Advanced Tables v0.18.1
		6: Dataview v0.5.55

RECOMMENDATIONS:
	Update installer: installer version too low, please download from https://obsidian.md/download?os=linux&arch=x64 and reinstall.
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Describe the bug**
When I insert a latex equation into obsidian excalidraw, and then duplicate it, sometimes it appears that changing the duplicated one and then undoing it, changes the original one

**To Reproduce**
1. open new excalidraw drawing in obsidian
2. Ctrl-P, insert latex equation, write some equation
3. alt-click on the equation and drag to duplicate it
4. ctrl-click on new equation, modify it in some way
5. move the new equation
6. press ctrl-Z to try and undo the move
7. note that it has changed the original equation now

**Expected behavior**
It to only undo the last action, and not change the original equation

**Screenshots**
See attached video:
[Screencast from 06-07-2023 11:14:31 AM.webm](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/32557146/b811d854-e8a0-4bef-9b83-8edd9e53ddea)

**Additional context**
in the vid above, you can see that after I change the R^n to R^k, and then move the R^k, I press ctrl-Z to try and undo the move. Instead, it changes both.

**Comment by zsviczian** [comment]
I hope to have solved some of the residual issues with this in 1.9.24, the rest earlier. Please reopen if this is still a problem.

**Comment by declanoller** [comment]
Hi @zsviczian , it fixed it, thank you so much! Love the plugin, and it's getting better all the time :)
