### ISSUE TITLE
Frame Tool Missing in Plugin

### ISSUE THREAD

**Issue by robkisk** [zsviczian/obsidian-excalidraw-plugin#1172]
Is there a way to get the frame tool encapsulation with the plugin similar to web feature?

<img width="1102" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/113189551/c9b781b9-3ebf-47b2-8cce-9a3840789e37">

**Comment by anatoliibakhtin** [comment]
https://twitter.com/zsviczian/status/1670541160501194758

**Comment by anatoliibakhtin** [comment]
@robkisk you probably should close this question as the frame is available https://youtu.be/ICpoyMv6KSs

**Comment by robkisk** [comment]
thank you.
