### ISSUE TITLE
BUG: excalidraw-plugin doesn't work on iPad

### ISSUE THREAD

**Issue by Milamber07** [zsviczian/obsidian-excalidraw-plugin#1176]
**Your environment**
SYSTEM INFO:
 Operating system: ios 16.5 (Apple iPad)
 Obsidian version: 1.4.6 (105)
 API version: v1.3.5
 Login status: not logged in
 Live preview: on
 Legacy editor: off
 Base theme: dark
 Community theme: none
 Snippets enabled: 0
 Restricted mode: off
 Plugins installed: 1
 Plugins enabled: 1
  1: Excalidraw v1.9.3

**Describe the bug**
obsidian-excalidraw-plugin doesn't work on iPad.
I installed excalidraw-plugin on a freshly created vault and the only available actions with it - excalidraw options. Nothing on the left ribbon (checked Ribbon menu settings - nothing) or commands. Debug startup time shows it is loaded.
Tried excali-brain plugin - excali-brain says "Excalidraw Plugin not found".

**To Reproduce**
1. create new vault
2. install obsidian-excalidraw-plugin
3. turn on obsidian-excalidraw-plugin

**Expected behavior**
- excalidraw icon on the left ribbon to create new drawings
- excalidraw commands
- create\edit excalidraw files

**Screenshots**
![IMG_0206](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/25886632/31eb1c89-ada0-42db-91f9-15f2d97528f5)

**Comment by Milamber07** [comment]
Updated to iPad OS 16.5.1 -- same bug

**Comment by DudeThatsErin** [comment]
I have my iPad on iOS 17 beta 2 and the plugin does not work on my iPad Pro either. This is disappointing.

**Comment by DudeThatsErin** [comment]
@Milamber07 The dev updated excalidraw 2 hours ago and now it is working for me.

**Comment by Milamber07** [comment]
@DudeThatsErin thanks for letting me know!

Freshly create vault, tried on\off plugin, reload app etc -- issue still persist :(

One interesting behaviour - the plugin doesn't unload properly. The error appears with these steps:
- "freshly" open Obsidian with turned on excalidraw plugin
- go to settings and turn off the plugin
- message about failed unload appear (screenshot attached)

If I try to turn on\off again after above steps - no error. Only after completely closing obsidian app and complete above steps - error appears.

![IMG_0219](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/25886632/f3d8b03f-7b75-4e7a-a4c4-0e5f9a64a43c)


SYSTEM INFO:
 Operating system: ios 16.5.1 (Apple iPad)
 Obsidian version: 1.4.6 (105)
 API version: v1.3.5
 Login status: not logged in
 Live preview: on
 Legacy editor: off
 Base theme: dark
 Community theme: none
 Snippets enabled: 0
 Restricted mode: off
 Plugins installed: 1
 Plugins enabled: 1
  1: Excalidraw v1.9.5

RECOMMENDATIONS:
 Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by DudeThatsErin** [comment]
@Milamber07 Under the filename settings do you have a name in the first box? It wasn't working when I did that.
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/2681022/3c9d4e82-3df3-41d3-a259-2af5ba59a686)

Also in that screenshot Excalidraw is disabled....

**Comment by Milamber07** [comment]
@DudeThatsErin
Under the filename settings do you have a name in the first box? It wasn't working when I did that.
=== tried different scenarios -  no change.

Also in that screenshot Excalidraw is disabled....
=== that's correct, my intention was to show an obsidian error notification in upper right corner after turning the plugin off :)
if you look closely excalidraw plugin was loaded in 1,698 ms on startup.

**Comment by DudeThatsErin** [comment]
What do you use to sync between devices? I'm thinking *maybe* your sync solution is causing issues with the plugin... Is this test vault created in iCloud or directly on your iPad?

Does it have the little cloud next to it in the vault switcher?

**Comment by Milamber07** [comment]
What do you use to sync between devices? I'm thinking maybe your sync solution is causing issues with the plugin... Is this test vault created in iCloud or directly on your iPad?
=== clean setup with freshly created vault directly on iPad. No sync at the moment - will look into git sync once obsidian is setup properly on ipad.

Does it have the little cloud next to it in the vault switcher?
=== nope, iCloud is disabled for obsidian on my devices.

**Comment by DudeThatsErin** [comment]
Since the original report have you tried uninstalling and reinstalling in this vault?

Last thing I can suggest. If that doesn't work the dev definitely needs to take a look. Weird that it works on the iPad OS 17 beta 2 but not the production release of 16.5.1... One would think it would be the opposite.

Have you also restarted obsidian?
I would uninstall, reinstall, restart obsidian, then enable and then *hopefully* it works.

**Comment by Milamber07** [comment]
I would uninstall, reinstall, restart obsidian, then enable and then hopefully it works.
=== done multiple times on 16.5 and latest/current 16.5.1 🙈  no result...

**Comment by DudeThatsErin** [comment]
There was another update, try that?

If that doesn't work you need the dev. Sorry about that.

**Comment by Milamber07** [comment]
1.9.6 - same issue and same unload error after turning off the plugin 🧐

P.S. out of curiosity I've just installed obsidian and plugin on iohone - same problem :)

**Comment by Milamber07** [comment]
@DudeThatsErin thanks for participating in this troubleshooting quest 😎

**Comment by Milamber07** [comment]
@zsviczian hi!
any chance you can have a look at this issue?

P.S. considering it is the most downloaded plugin, it is strange only a handful of users have reported this issue with iPadOS 🧐 perhaps, there is a workaround, but I didn't find any myself or searching on forums\web.

**Comment by zsviczian** [comment]
This is super strange. My device info matches @Milamber07's. I created a new vault, enabled plugins, installed Excalidraw and enabled it. It works without a glitch. I've also had 1.9.3... and all earlier versions work on my ipad since ... forever.

I also installed Obsidian and Excalidraw on my iPhone with an old iOS version (15.7.1). Also worked without any issues. I am now updating the phone to iOS 16.5 to see if any issues will surface (I doubt).

@Milamber07 there was no change to code that should impact iPad compatibility between 1.9.3 and 1.9.5 or 1.9.6. I doubt that the solution is in the new version. Maybe you changed some settings on your iPad in the time in between. Maybe a security setting somewhere?

I'd love to help, however I am unable to reproduce the problem and unfortunately Apple is meticulous about limiting user's (and developer's) ability to debug, so I can't even guide you to any activity that would provide me with further debug info.

Since Obsidian runs on Safari in the background you can maybe check via appstore if there is a Safari update.

Are you able to run excalidraw.com in your Safari browser?

--------

For info, here's my system info:

SYSTEM INFO:
	Operating system: ios 16.5 (Apple iPad)
	Obsidian version: 1.4.6 (105)
	API version: v1.3.5
	Login status: logged in
	Catalyst license: supporter
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v1.9.6

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by Milamber07** [comment]
@zsviczian After reading below line, the problem was uncovered. I wasn't aware obsidian uses Safari in the background on iOS and iPadOS... 
"Since Obsidian runs on Safari in the background you can maybe check via appstore if there is a Safari update."

All my apple devices have Lockdown mode enabled, which in hand limits Safari capabilities.
That doesn't affect MacOS with Lockdown mode enabled.
But! According to apple:
"To exclude an app, turn that app off in the menu. Only apps that you have opened since enabling Lockdown Mode and which have limited functionality appear on this list."
obsidian should have been listed as an exclusion option in Lockdown Mode. 

It seems there is one solution - to turn off Lockdown Mode.

@zsviczian Thanks for making everything clear. 
I'll tinker later on and get back here to post news to close this "bug" thread :)

**Comment by Milamber07** [comment]
After disabling Lockdown Mode in iPad -- everything works as intended.
