### ISSUE TITLE
BUG: help shortcuts are really hard to see

### ISSUE THREAD

**Issue by 1C0D** [zsviczian/obsidian-excalidraw-plugin#1179]
![help](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/63018905/6634b869-7473-4e14-ae96-77eacce9afa0)

**Comment by zsviczian** [comment]
So I see the issue, I am using the accent color... which is not a good choice. I'll get this fixed in the next release.

**Comment by zsviczian** [comment]
Will be fixed in 1.9.6
