### ISSUE TITLE
Enhancement - Wrapping text in a box

### ISSUE THREAD

**Issue by danieltomasz** [zsviczian/obsidian-excalidraw-plugin#118]
**Is your feature request related to a problem? Please describe.**

I would like to request the possibility to automatically wrap text.
When I put normal text I could use line breaks.
When I want to include long  wikilinks [[,  I cannot use linebreaks  because it will break the  links 

**Describe the solution you'd like**

Possibility to resize textbox in which the text automatically wraps 
(When  reducing the width of the text block  it should have the same size font, moving some words line below)

**Comment by zsviczian** [comment]
This is an interesting but complex idea. How would the program know when to resize the font and when to resize the text block and wrap text? 
Have you tried using aliases? `[[This is my very long wiki link that would need to be wrapped|my short link]]` If you take this approach, and use Excalidraw in "preview" mode instead of "raw" mode, then links will still work, but only the short text will be displayed and it will better fit your drawing.

**Comment by danieltomasz** [comment]
If this involve substantial work and complex implementation I might use aliases as well.


> How would the program know when to resize the font and when to resize the text block and wrap text?
Maybe a solution to that would  add  option to lock the text (size) of the object? 

What I am trying to achieve is to to use excalidraw functionally as mindmapping tool, simarly to scapple 
https://www.literatureandlatte.com/scapple/overview

But this will involve  substantially more work I think,  and is really out of scope of this issue.

If I may  request another  enhancment that may be a relatively easier to implement, maybe the autocomplention of wikilinks ? I may create another issue for that.

**Comment by danieltomasz** [comment]
I have in mind somwrhing simalar to this https://github.com/excalidraw/excalidraw/issues/1428

**Comment by zsviczian** [comment]
Regarding autocomplete, have you tried the command palette action: `Excalidraw: Insert link to file`? 
I know it is not a perfect solution, but if you add a hotkey, it can go a long way in solving the issue of wiki links.

I am trying to avoid changing the core Excalidraw product, I only build around it. The logic behind this design decision is to benefit from the ongoing rapid development of Excalidraw.

Mindmaps are on my longer-term plan. The closest I got to mind mapping support until now is with [ExcalidrawAutomate](https://zsviczian.github.io/obsidian-excalidraw-plugin/Examples/templater_mindmap.html). You first create an outline, which you can convert to a mindmap... but without word wrap. However, the example script could be easily tweaked to support word wrapping.

Again thinking about the distant future, I am thinking to create a script to process [argdown](https://argdown.org/), that looks relatively simple, and maybe later Mermaid.

**Comment by danieltomasz** [comment]
Great, thanks for the `Excalidraw: Insert link to file` tip!

I understand that much depends on upstream Excalidraw development.

Your plans for the distant future seems really promising. Thanks for developing the plugin!

**Comment by zsviczian** [comment]
Hi @danieltomasz , 
It is not a 100% solution, but I implemented an initial version of text wrapping in 1.2.20.
If you transclude text from another document you can now specify the line wrap length after the transclusion: `![[document#^blockref]]{40}` will wrap the transcluded text to 40 characters per line max. 

![image](https://user-images.githubusercontent.com/14358394/131221826-528e5a79-7a8a-454f-a921-282d3acf09a2.png)

**Comment by danieltomasz** [comment]
Thanks, I will try this!
