### ISSUE TITLE
BUG: Not able to embed links to playlists and search results from YouTube

### ISSUE THREAD

**Issue by ankified** [zsviczian/obsidian-excalidraw-plugin#1187]
**Describe the bug**
When trying to embed the webpage for any YouTube playlist or search results the iframe returns an error. However, if I embed the link to the Playlists tab then click on any playlist it works as expected.

**To Reproduce**
1. Open Obsidian.md;
2. Open any drawing or create a new one;
3. Create a new web embed inside this drawing;
4. Paste the link to a playlist of your choice (e.g. https://www.youtube.com/playlist?list=PL6mqgtMZ4NP1o3urKVf0j-s6sjP7yPE1R) or search results (e.g. https://www.youtube.com/results?search_query=excalidraw)
5. Click in the iFrame.
6. See the error message.

**Additional context**
Version of Excalidraw: 1.9.6
Version of Obsidian: 1.3.5
O.S.: Windows 11

**Comment by zsviczian** [comment]
A fix will be included in the next release. I hope to issue the release in a few days. I am still working on some other fixes as well.
