### ISSUE TITLE
FR: Add support for frame section links in "copy group markdown link" feature

### ISSUE THREAD

**Issue by pastafizia** [zsviczian/obsidian-excalidraw-plugin#1194]
**Is your feature request related to a problem? Please describe.**
When using the frame tool in Excalidraw, I found that the "copy group markdown link" feature does not currently support frames. It would only feel more natural if it did.

**Describe the solution you'd like**
I would like to suggest adding a new command that specifically copies the frame section link. Alternatively, if the current command could be modified to include frames, that would also be helpful.

**Additional context**
Here is a screenshot of the feature request:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/59926997/b6e28c93-11a0-40f9-8839-7c0e630d4476)

**Comment by zsviczian** [comment]
implemented in 1.9.7
