### ISSUE TITLE
New drawing in subfolder

### ISSUE THREAD

**Issue by davidedellagiustina** [zsviczian/obsidian-excalidraw-plugin#121]
Would it be possible to add the feature of placing a new drawing in a specific subfolder of the currently open folder? Something like Obsidian already does for images/attachments.

For example, I like to have my drawings in a `/drawings` subfolder in order to reference and embed them in my `notes.`

**Comment by zsviczian** [comment]
yes, this is absolutely doable. If you have Templater and/or QuickAdd you can also quickly implement this feature for yourself. But I will also add it to my todo list.

**Comment by zsviczian** [comment]
Hi @davidedellagiustina,

I was going to implement your suggestion just now but ended up deciding against it. It would add further complexity to an already complex plugin. I did however write the Templater script that does this for you... let me know if you need more help with this.

```javascript
<%*
  // the attachments subfolder
  // use the default from settings
  const attachments = app.vault.config.attachmentFolderPath.substring(1) == "/" 
                      ? "" : app.vault.config.attachmentFolderPath.substring(1); 
  // const attachments = "/drawings";
  
 
  const folder = tp.file.folder(true) == "/" ? attachments + "/" : tp.file.folder(true) + attachments + "/";
  const settings = app.plugins.getPlugin("obsidian-excalidraw-plugin").settings;
  const defaultTitle = tp.file.title + ' - '
                       + moment().format(settings.drawingFilenameDateTime);
  const title = await tp.system.prompt("What title do you want to give your drawing?",defaultTitle);
  if(title == "") return;
  tR += "!["+"["+folder+title+".excalidraw]]\n"; //the .excalidraw extension is automatically added by EA.create
  
  const ea = ExcalidrawAutomate;
  ea.reset();
  ea.create({
    filename:title, 
	foldername:folder, 
	templatePath: app.plugins.getPlugin("obsidian-excalidraw-plugin").settings.templateFilePath,
	onNewPane: true
  });
%>
```

**Comment by davidedellagiustina** [comment]
@zsviczian I never felt the need to use Templater, guess the time has come now :)
I'll check your script out when I'll start University again, but thank you so much!
