### ISSUE TITLE
BUG: Pasting while panning due to Linux Middle Click paste

### ISSUE THREAD

**Issue by Aeases** [zsviczian/obsidian-excalidraw-plugin#1215]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 16 13:30:11 UTC 2023 5.19.0-46-generic
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Border v1.3.7
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 30
	Plugins enabled: 26
		1: Advanced Tables v0.18.1
		2: Highlightr v1.2.2
		3: Admonition v9.3.2
		4: Obsidian Charts v3.7.1
		5: Obsidian Git v2.20.4
		6: Excalidraw v1.9.3
		7: Dataview v0.5.56
		8: Spaced Repetition v1.10.1
		9: Kanban v1.5.3
		10: Contextual Typography v2.2.5
		11: Minimal Theme Settings v6.3.1
		12: Surfing v0.8.16
		13: Vault Statistics v0.1.3
		14: Numerals v1.2.0
		15: Style Settings v1.0.6
		16: Projects v1.16.0
		17: Banners v1.3.3
		18: Weaver v0.5.3
		19: AI Commander v1.3.2
		20: Digital Garden v2.45.1
		21: Obsidian matrix v1.4.0
		22: File Diff v1.0.13
		23: Text Generator v0.3.20
		24: Obsidian42 - BRAT v0.7.0
		25: Desmos v0.6.6
		26: Folder notes v1.3.4

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
When using middle mouse button to pan the view on linux *sometimes* it will paste text wherever your mouse is.

**To Reproduce**
1. Be on linux
2. Copy Something
3. Attempt to pan around excalidraw using middle mouse button, sometimes text will be pasted

**Expected behavior**
to be able to pan without pasting stuff everywhere
**Screenshots**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/96164686/32508a5d-5593-4a71-8a72-9914b1e3e9d2)

**Additional context**
To fix maybe prevent pasting while panning?

**Comment by zsviczian** [comment]
Can you reproduce this effect on excalidraw.com? If yes, then probably better to raise the issue there as the fix needs to be made in the core package. 
https://github.com/excalidraw/excalidraw/issues

You can also drag with click + space.
