### ISSUE TITLE
BUG: The cached png breaks after restarting the app if the cursor is in a special position

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#1216]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Windows 10 Pro 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v1.9.8

**Describe the bug**
If I use cache mode for PNG, then every time I restart the application, if the cursor is in a special position (on an open inserted excalidraw file, so that both the name and the picture of the inserted file are visible) before restarting and immediately after restarting the application, then turning off/on the display of the rendered png produces a broken picture. 

What bothers me is that the same result occurs once in a while in my other files where the cursor was out of the special position, but in the example described here I tried to point to an always reproducible result.

**To Reproduce**
1. enable cache
2. enable PNG auto-export (there is no problem with svg)
3. create a note
4. create an excalidraw
5. close an excalidraw window (if this is not done, as far as I understand, the excalidraw will be re-rendered and there is no problem)
6. add excalidraw to note
7. open a note with an open drawing inside `![[file.excalidraw]]`
	- there are 2 rendered caches, 1 for dark, 2 for light, I will break both, for this they need to be created in one and the other theme
8. place your cursor to a special position ( right before or on the title `![[fil👇🏻e.excalidraw]]`, to display the image and its file name)
9. restart the application
10. and do without moving the cursor from drawing title (step 8)
	- remove and return `!` to turn off the display of the picture or
	- move to move to another note in the same window so that some mechanism works as a result of which the picture breaks.

To return everything to working condition, open the drawing and save, but the caching function loses its meaning if it needs to be done for each image.

**Expected behavior**
- the rendered png image to be displayed rather than a broken icon even when restarting the app.

**video step-by-step**

https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/71871141/eb655236-a439-4e52-8643-e8fb6ec51e5c

**Additional context**
I like png because svg rendering is too heavy and the `file.canvas` hangs because of this (if the cache function is transferred to excalidraw, then speed is also important to me).

**Comment by zsviczian** [comment]
Thanks for describing the bug. I learned something today. `URL. createObjectURL()` creates a local Obsidian resource object which is recycled by Obsidian in the situation you describe. I will fix this. On the upside.... this is likely why PNGs perform better in Canvas then SVGs.

**Comment by anatoliibakhtin** [comment]
https://discord.com/channels/1026825302900494357/1124663173706944572/1131130686053552169
