### ISSUE TITLE
Sync Theme with Excalidraw Pane

### ISSUE THREAD

**Issue by phibr0** [zsviczian/obsidian-excalidraw-plugin#122]
**Is your feature request related to a problem? Please describe.**
When switching the Theme inside Obsidian the Excalidraw Theme doesn't automatically change.

**Describe the solution you'd like**
I think it would be best if the Excalidraw Theme would automatically adapt to Obsidian's Theme.

**Comment by zsviczian** [comment]
This is a nice idea. I'll play around with it.

**Comment by zsviczian** [comment]
you would like this only for new drawings or for active drawings as well?

**Comment by phibr0** [comment]
Personally I would like to have it for the active drawing as well. Even better would be if it would sync with transclusions but I guess that's not really feasible if you have to edit the files for that

**Comment by zsviczian** [comment]
I implemented one more setting in 1.4.11.
Excalidraw preview to match Obsidian theme. 
![image](https://user-images.githubusercontent.com/14358394/142767894-a5f2a827-30bc-4a48-94f0-aa8f2f149289.png)

**Comment by zsviczian** [comment]
I've added the other feature to settings as well. With 1.4.11 you can enable Excalidraw to follow theme changes.
![image](https://user-images.githubusercontent.com/14358394/142769517-65c56b63-c327-4007-bbd8-26cbd25fa84d.png)
