### ISSUE TITLE
FR: Support Editing(Drawing) and Laser Pointer while presenting in slideshow.

### ISSUE THREAD

**Issue by you-n-g** [zsviczian/obsidian-excalidraw-plugin#1220]
**Is your feature request related to a problem? Please describe.**
Hi, @zsviczian  , I watched your latest youtube video about [slideshow 3.0 ](https://www.youtube.com/watch?v=JwgtCrIVeEU&t=19s)
I'm very excited about this feature. Thanks for your great efforts.

I come up with two new requirements which might be helpful to many users.

In microsoft's PPT,  features like Editing(Drawing) and Laser Pointer are provided while presenting. 
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/465606/f8d56c6b-0fab-4193-b4a6-52e3df58bce9)

I think these two features  might be helpful to users.
1) I think it would be great if it support editing while presenting! (e.g. It triggers some discussions while presenting and people start to draw and edit while presenting)
2) Supporting lazer pointer would be a very helpful to me when presenting.

**Describe the solution you'd like**
Similar to PPT. 

**Describe alternatives you've considered**
Office PPT

**Comment by you-n-g** [comment]
If we can create a pen which could draw soemthing that would automatically disappear after you stop drawing for about several seconds, it would be very helpful when we are demo sth.

![test](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/465606/c0e94432-156b-4fbf-a5d6-35fc3a11faa2)

**Comment by karuturi** [comment]
@zsviczian Thanks for the great work. I recently discovered slideshow script and loving it so far. One thing I miss is the ability to write on slide while presenting. Currently, I exit the presentation, write and then restart. It would be great if you could support writing in presentation mode.

**Comment by zsviczian** [comment]
Did you try the laser pointer? There is a button for it on the slideshow controls and you can also turn it on and off by double tapping on the canvas

**Comment by karuturi** [comment]
@zsviczian yes, I did. That disappears quite fast. https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1408

**Comment by zsviczian** [comment]
I added configuration options in 1.9.28  to change laser pointer color, decay speed and length. Please test that. If that is not sufficient, then please open another FR.
