### ISSUE TITLE
FR: 

### ISSUE THREAD

**Issue by FeiLZX3Km** [zsviczian/obsidian-excalidraw-plugin#1221]
**Is your feature request related to a problem? Please describe.**
Anyway, Excalidraw already supports 2D drawing and inserting images. So why not be bolder and have it support inserting 3D models and associating notes with them? Some might argue that the official core plugins already provide a 3D model note relationship diagram. But no, what I'm proposing is different from the 3D relationship graph plugin in Obsidian. At least, it would be more interactive and practical. Based on the current situation with the official core plugins, it's basically just for show. It only consolidates and displays the relationships between all the notes. But for someone like me who uses Obsidian, it's not useful at all, except for making me realize, "Oh, I've created so many notes." So I turned it off early on.
However, while using the Excalidraw plugin, I saw my own needs and also saw the potential for it to generate more excitement and possibilities. That's why I proposed the above feature request. I think the main application scenario for this feature is to associate more notes around a model, where the spatial logic of the model becomes the logic of the notes, rather than just being flat. I believe this spatial aspect brought by the model will make learners' thinking more active.

**Describe the solution you'd like**
In specific usage scenarios, you can create or import 3D models in Excalidraw notes. You can freely drag, zoom in, and zoom out on this model to see its different surfaces, and each surface can be associated with different notes that you create. These models can be geographical representations of certain areas. Then, you can directly create notes on the surface of the 3D model or stick notes on it like sticky notes. You can also create a point or enclose an area with a box and connect it to notes outside the model. This effect is like wearing AR glasses where everything in the high-tech world displayed inside the glasses comes with information. I hope I have explained the feature request clearly.

**Describe alternatives you've considered**
I haven't found a similar solution.

**Additional context**
Maybe it's not achievable, but I still want to say it. ^-^
![image](https://s201.q4cdn.com/390615539/files/news_thumbnails/AI.png)

**Comment by zsviczian** [comment]
This would be really cool... but difficult.
You might like my video on spatial thinking: https://youtu.be/oRMh-5S0zoE
Have you tried ExcaliBrain? https://youtu.be/gOkniMkDPyM and https://youtu.be/7rnsULzez-g

**Comment by FeiLZX3Km** [comment]
> This would be really cool... but difficult. You might like my video on spatial thinking: https://youtu.be/oRMh-5S0zoE Have you tried ExcaliBrain? https://youtu.be/gOkniMkDPyM and https://youtu.be/7rnsULzez-g







> This would be really cool... but difficult. You might like my video on spatial thinking: https://youtu.be/oRMh-5S0zoE Have you tried ExcaliBrain? https://youtu.be/gOkniMkDPyM and https://youtu.be/7rnsULzez-g

Haha, I think it is obvious that this cannot be achieved in recent years. However, I am still glad that you can respond to this idea. Good luck to you~
