### ISSUE TITLE
BUG: from 1.9.8 can't select multiple items dragging with shift

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#1224]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Windows 10 Pro 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v1.9.8

**Describe the bug**
Starting from version 1.9.8 I can't select multiple items while holding down a key `shift`

**To Reproduce**

https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/71871141/6c140bbd-123c-4ce2-82bb-370ae4a33876

if you click on objects, then everything works, but if you drag selection - no (see video above)

**Expected behavior**
Everything is as it was in version 1.9.7

https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/71871141/19eac603-63b8-4932-9b4b-918805a0a3ac

**Comment by zsviczian** [comment]
Does this work on Excalidraw.com?

**Comment by zsviczian** [comment]
I wonder if this is related.... https://github.com/excalidraw/excalidraw/pull/6747

**Comment by anatoliibakhtin** [comment]
> Does this work on Excalidraw.com?

Everything works on the excalidraw.com. The problem first appeared in version 1.9.8.

**Comment by zsviczian** [comment]
> Everything works on the excalidraw.com. The problem first appeared in plugin version 1.9.8.

not for me... I opened an issue for this: https://github.com/excalidraw/excalidraw/issues/6806

**Comment by anatoliibakhtin** [comment]
Sorry, apparently my site had an old version saved in cookies or somewhere I tidied up the computer and had to reinstall the browser...  I also have this problem on the site. Thank you for moving the issue to their repository!
