### ISSUE TITLE
BUG:  Menus displayed in the middle of the screen

### ISSUE THREAD

**Issue by nicolasmarc1** [zsviczian/obsidian-excalidraw-plugin#1236]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.

SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.1.9
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Royal Velvet
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 139
	Plugins enabled: 78
		1: Note Refactor v1.7.1
		2: Buttons v0.4.17
		3: Templater v1.14.3
		4: MetaEdit v1.7.2
		5: Dataview v0.5.47
		6: QuickAdd v1.0.2
		7: Admonition v9.0.5
		8: Kanban v1.4.5
		9: Tag Wrangler v0.5.3
		10: Quick Switcher++ v3.0.1
		11: obsidian markmind v1.5.9
		12: Hotkey Helper v0.3.16
		13: Hotkeys++ v0.2.7
		14: Enhancing Mindmap v0.2.4
		15: Quick Explorer v0.2.2
		16: File Tree Alternative Plugin v2.2.3
		17: Pluck v1.0.1
		18: Footnote Shortcut v0.0.9
		19: Better footnote v1.0.1
		20: Icon Folder v1.3.31
		21: Advanced Tables v0.17.3
		22: Image Toolkit v1.3.1
		23: Zoom v1.0.1
		24: Youglish Plugin v0.0.3
		25: Dangling links v0.3.0
		26: Timeline v1.1.0
		27: Obsidian Git v2.6.0
		28: Convert url to preview (iframe) v0.5.0
		29: Dictionary v2.21.1
		30: Natural Language Dates v0.6.1
		31: Unique attachments v1.0.3
		32: Folder Note v0.7.3
		33: File Explorer Note Count v1.2.0
		34: Obsidian42 - Text Transporter v1.0.3
		35: Local images v0.14.2
		36: Obsidian42 - BRAT v0.6.35
		37: Graph Analysis v0.15.4
		38: Obsidian Link Converter v0.1.4
		39: Plugin Changelogs v1.3.0
		40: Get Info v1.1.0
		41: Diagrams v1.5.0
		42: Rich Links v1.1.0
		43: Metadata Extractor v1.0.2
		44: Pane Relief v0.4.0
		45: Excalidraw v1.9.8
		46: Mind Map v1.1.0
		47: Cycle through Panes v0.1.0
		48: Structured Plugin v1.0.4
		49: Full Calendar v0.6.1
		50: Vantage - Advanced search builder v1.4.2
		51: LanguageTool Integration v0.3.0
		52: Quiet Outline v0.3.2
		53: Hover Editor v0.11.11
		54: Calendar v1.5.10
		55: Remember cursor position v1.0.7
		56: Version History Diff v2.0.9
		57: Creases v0.6.5
		58: Custom Frames v2.4.4
		59: Imgur Plugin v2.2.1
		60: Settings Search v1.2.0
		61: Charts View v1.1.9
		62: Obsidian42 - Jump-to-Date v1.0.13
		63: Insert Heading Link v1.0.1
		64: DB Folder v2.7.1
		65: Outliner v4.7.1
		66: Style Settings v0.4.12
		67: Media DB Plugin v0.3.2
		68: Extract PDF Annotations v1.0.4
		69: Simple Embeds v1.14.1
		70: Open Link With v0.1.7
		71: Linter v1.7.1
		72: Gist v0.9.0
		73: Obsidian42 - Strange New Worlds (SNW) v1.2.0
		74: Better Word Count v0.9.1
		75: Auto Link Title v1.4.1
		76: Query Control v0.5.0
		77: Annotator v0.2.10
		78: PodNotes v2.10.7

**Describe the bug**

Hi, I just updated excalidraw from to the current 1.9 ( i think from a 1.8.something version) but now the menus seems to be placed in the middle of the screen (like if the top of the excalidraw page was lower). I also noticed that if i shorten the width of the tab the menus were displayed at bit higher (cf both screenshots).

I tried with a sandbox vault but it seemed to work well, so there might be a conflict with another plugin but it didn't do that before the update so also maybe you changed how the menus were displayed in the page recently ? 

Also i don't if it's relevant but  when i updated excalidraw, excalidraw tabs crashed and were converted in empty "new page" tabs. i used a previous version of my workspace.json to refind my previous excalidraw tabs.

The expected behavior is to have the menus at the top like before.

Thanks!

**Screenshots**

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/51007222/0f4ca7c5-40d6-4810-9353-84dbaf23c71e)
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/51007222/3a7feb3b-dd8d-446e-b64c-262ec409edc7)

**Comment by zsviczian** [comment]
I see you are using a custom theme. Did you try with the default obsidian theme?

**Comment by nicolasmarc1** [comment]
> I see you are using a custom theme. Did you try with the default obsidian theme?

Thanks for the very insightful reply! It was not because of my theme but a custom snippet where there was a conflict with a css variable
--sat: 20% !important; in my snippet conflicting with 
--sat: env(safe-area-inset-top); 

I fixed it and it works. Thanks
