### ISSUE TITLE
BUG: When using the “Frame tool”, text search cannot be carried out.

### ISSUE THREAD

**Issue by xuuou** [zsviczian/obsidian-excalidraw-plugin#1239]
**Your environment**
SYSTEM INFO:
Obsidian version: v1.3.5
Install version: v1.1.16
Operating system: Windows 10 Home China 10.0.22621
Login status: not logged in
Insider build toggle: off
Live preview: Wed
Legacy editor: off
Base theme: dark
Community theme: none
Snippets enabled: 3
Restricted mode: off
Plugins installed: 40
Plugins enabled: 30
1: Excalidraw v1.9.9
2: Advanced Tables v0.19.0
3: Bartender v0.5.7
4: Calendar v1.5.10
5: Citations v0.4.5
6: Clear Unused Images v1.1.0
7: Copy Block Link v1.0.4
8: Diagrams v1.5.0
9: Drag-n-Drop for blocks v1.2.0
10: Dynamic Table of Contents v0.0.27
11: Easy Typing v5.1.10
12: Editing Toolbar v2.3.1
13: floating toc v2.3.0
14: Hypothes.is v0.1.19
15: Markdown prettifier v0.1.3
16: Mind Map v1.1.0
17: MySnippets v1.2.3
18: Note Refactor v1.7.1
19: Obsidian42 - BRAT v0.7.0
20: Obsidian42 - Text Transporter v1.0.3
21: Ozan's Image in Editor Plugin v2.2.3
22: Pandoc Plugin v0.4.1
23: Paste URL into selection v1.7.0
24: Recent Files v1.3.6
25: Style Settings v1.0.6
26: Table Extended v1.6.1
27: Table Generator v1.3.1
28: Tag Wrangler v0.5.11
29: Various Complements v8.3.2
30: Zotero Integration v3.0.6

**Describe the bug**
When using the “Frame tool”, text search cannot be carried out.

**To Reproduce**
1. Go to 'More tools'
2. Click on 'Frame tool'
3. Click the left mouse button to circle a part of the content
4. Press "Ctrl+F" to search for content, but the result is that nothing can be found

**Expected behavior**
No results found

I have retested this bug in the sandbox.

**Comment by xuuou** [comment]
> **Your environment** SYSTEM INFO: Obsidian version: v1.3.5 Install version: v1.1.16 Operating system: Windows 10 Home China 10.0.22621 Login status: not logged in Insider build toggle: off Live preview: Wed Legacy editor: off Base theme: dark Community theme: none Snippets enabled: 3 Restricted mode: off Plugins installed: 40 Plugins enabled: 30 1: Excalidraw v1.9.9 2: Advanced Tables v0.19.0 3: Bartender v0.5.7 4: Calendar v1.5.10 5: Citations v0.4.5 6: Clear Unused Images v1.1.0 7: Copy Block Link v1.0.4 8: Diagrams v1.5.0 9: Drag-n-Drop for blocks v1.2.0 10: Dynamic Table of Contents v0.0.27 11: Easy Typing v5.1.10 12: Editing Toolbar v2.3.1 13: floating toc v2.3.0 14: Hypothes.is v0.1.19 15: Markdown prettifier v0.1.3 16: Mind Map v1.1.0 17: MySnippets v1.2.3 18: Note Refactor v1.7.1 19: Obsidian42 - BRAT v0.7.0 20: Obsidian42 - Text Transporter v1.0.3 21: Ozan's Image in Editor Plugin v2.2.3 22: Pandoc Plugin v0.4.1 23: Paste URL into selection v1.7.0 24: Recent Files v1.3.6 25: Style Settings v1.0.6 26: Table Extended v1.6.1 27: Table Generator v1.3.1 28: Tag Wrangler v0.5.11 29: Various Complements v8.3.2 30: Zotero Integration v3.0.6
> 
> **Describe the bug** When using the “Frame tool”, text search cannot be carried out.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'More tools'
> 2. Click on 'Frame tool'
> 3. Click the left mouse button to circle a part of the content
> 4. Press "Ctrl+F" to search for content, but the result is that nothing can be found
> 
> **Expected behavior** No results found

**Comment by zsviczian** [comment]
I can reproduce it. Will try to fix it today.

**Comment by zsviczian** [comment]
fixed in 1.9.10 - will release it today
