### ISSUE TITLE
Incompatibility with RTL plugin

### ISSUE THREAD

**Issue by yuvve** [zsviczian/obsidian-excalidraw-plugin#124]
So I'm not 100% sure plugin incompatibilities are considered bugs, but I hope it's ok posting it here.

**Bug Description**
Excalidraw does not run properly when both this plugin and [obsidian-rtl](https://github.com/esm7/obsidian-rtl) are enabled (**although the text direction in the current document does not affect this bug!**). 
Everything in the Excalidraw window is misaligned, and it is stuck in some kind of perpetual scrolling. You cannot draw or use any tools.

**To Reproduce**
1. Install obsidian-excalidraw-plugin from inside Obsidian, and enable it.
2. Install obsidian-rtl from inside Obsidian, and enable it.
3. Create a new Excalidraw drawing.

**Expected behavior**
The Excalidraw window should open properly and be usable.

**Screenshots**
![Obsidian_AO72WTtz7H - Copy](https://user-images.githubusercontent.com/37124628/129598772-ee9e5970-0d22-4f24-96f3-0cf94767bbdd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by zsviczian** [comment]
Thanks for raising this issue. Unfortunately, I am not able to solve this from Excalidraw. The RTL plugin needs to make the necessary checks to avoid modifying non-markdown views.  I raised an issue with RTL: https://github.com/esm7/obsidian-rtl/issues/20
