### ISSUE TITLE
BUG: Can not send "Web Embed" elements to back.

### ISSUE THREAD

**Issue by marsvet** [zsviczian/obsidian-excalidraw-plugin#1241]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.1.16
	Operating system: Windows 10 Home China 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.0.7
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 43
	Plugins enabled: 43
		1: Trash Explorer v1.2.1
		2: Auto Link Title v1.4.1
		3: Text Extractor v0.4.6
		4: Find orphaned files and broken links v1.9.0
		5: Weread Plugin v0.5.1
		6: Custom Frames v2.4.6
		7: Dataview v0.5.56
		8: Admonition v9.3.3
		9: Emoji Shortcodes v2.2.0
		10: Word Splitting for Simplified Chinese in Edit Mode and Vim Mode v1.10.0
		11: Reading comments v1.0.22
		12: Outliner v4.7.1
		13: Hover Editor v0.11.13
		14: Omnisearch v1.15.0
		15: Commander v0.5.0
		16: Quiet Outline v0.3.15
		17: Calendar v1.5.10
		18: Emoji Toolbar v0.4.1
		19: Icon Folder v2.1.2
		20: Annotator v0.2.10
		21: Convert url to preview (iframe) v0.5.0
		22: Custom Attachment Location v0.0.9
		23: Local Images Plus v0.15.7
		24: Surfing v0.8.16
		25: Recent Files v1.3.7
		26: Text Generator v0.3.20
		27: Minimal Theme Settings v6.3.2
		28: Style Settings v1.0.6
		29: Kanban v1.5.3
		30: Douban v1.8.8
		31: Diagrams v1.5.0
		32: Advanced Slides v1.20.0
		33: Banners v1.3.3
		34: Obsidian42 - BRAT v0.7.0
		35: Templater v1.16.0
		36: QuickAdd v1.2.1
		37: Media Extended v2.11.1
		38: Media Extended BiliBili Plugin v0.3.1
		39: Remember cursor position v1.0.7
		40: SimpRead Sync v2.1.1
		41: Excalidraw v1.9.10
		42: ExcaliBrain v0.2.0
		43: Advanced Tables v0.19.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
Can not send "Web Embed" elements to back, they're always on front layer.
"Send to back" button and "Send backward" button don't work.

**To Reproduce**
1. Open a excalidraw file.
2. Draw a "Web Embed" element and any other element.
3. Click "Web Embed" element, click "Send to back" button or "Send backward" button.

**Expected behavior**
"Web Embed" element have been on back layer.

**Screenshots**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/36563356/3b366e81-a150-44d9-b135-7bd3a64ded61)

**Comment by zsviczian** [comment]
that is not a bug, but a feature... or rather, the way the Excalidraw canvas and web embeds on top are implemented, this technically cannot be solved. I am sorry.
