### ISSUE TITLE
FR: insert markdown link of a grouped excalidraw elements and it doesn't show the elements, it shows just the link.

### ISSUE THREAD

**Issue by Deus333** [zsviczian/obsidian-excalidraw-plugin#1243]
I use the "copy markdown link" option to insert an element of a drawing into another and by putting a "!" at the beginning of the link you can have the image of the element right there, not just the link itself just like how it works In markdown note but when you group elements and trying to make a markdown link for the group it doesn't show the image of the group and you just have the link and putting "!" don't work in drawing. can you fix this? It improves my workflow a lot...

thanks

**Comment by zsviczian** [comment]
I implemented partial support for this in 1.9.12 for this. Will release soon.

**Comment by Deus333** [comment]
You are incredible man I really appreciate your works

**Comment by Deus333** [comment]
Hi Zsolt I think I may have conveyed my meaning incorrectly I decided to record it 
to get clear what I'm trying to say
https://www.youtube.com/watch?v=gXXQ2YXf6r4

**Comment by zsviczian** [comment]
Thanks for the explanation! For these types of use-cases, you should deconstruct the desired elements into a sub-drawing. The other is deliberately not implemented due to performance implications.

Watch this video: https://youtu.be/HRtaaD34Zzg
