### ISSUE TITLE
BUG: Slide Plugin Rendering Frame Numbers Inconsistently

### ISSUE THREAD

**Issue by bjrice21** [zsviczian/obsidian-excalidraw-plugin#1244]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.1.9
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Blue Topaz v20230509
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 46
	Plugins enabled: 45
		1: Dataview v0.5.56
		2: Natural Language Dates v0.6.1
		3: Open with v0.3.1
		4: Periodic Notes v0.0.17
		5: QuickAdd v1.2.1
		6: Tag Wrangler v0.5.11
		7: Templater v1.16.0
		8: Book Search v0.5.10
		9: Editor Syntax Highlight v0.1.3
		10: Hotkeys for specific files v1.3.1
		11: Local REST API v1.6.0
		12: Plugin Update Tracker v1.5.1
		13: Tasks v4.3.0
		14: Advanced URI v1.36.4
		15: Focus Active Sentence v1.1.0
		16: Global Hotkeys v0.1.2
		17: Draw Harada Method v1.0.14
		18: Timestamp Notes v1.0.8
		19: Dice Roller v9.2.0
		20: Calendar v1.5.10
		21: Obsidian Columns v1.5.0
		22: Checklist v2.2.12
		23: ExcaliBrain v0.1.15
		24: Zotero Bridge v1.3.0
		25: Zotero Link v1.0.0
		26: Dangerzone Writing v0.0.11
		27: Style Settings v1.0.6
		28: Callout Manager v1.0.1
		29: Omnivore v1.5.3
		30: Icon Folder v2.1.2
		31: Recent Files v1.3.6
		32: Translate v1.4.4
		33: Advanced Tables v0.19.0
		34: Interlinear Glossing v1.3.0
		35: Table Sorting v1.3.0
		36: Copilot v2.3.5
		37: Zoom v1.1.2
		38: Heatmap Calendar v0.6.0
		39: Metatable v0.14.6
		40: Spotlight v0.2.0
		41: Inline Scripts v0.24.12
		42: Advanced Slides v1.20.0
		43: Tracker v1.10.9
		44: Creases v0.7.0
		45: Excalidraw v1.9.10

**Describe the bug**
I have an Excalidraw file in Obsidian. Using "Insert ANY file from your vault...", I add 32 portions from an Obsidian Markdown file in my vault. I put Frames around each of those (for the purpose of using the Slides 3.0 plugin).

I left the default frame naming/numbering (i.e. Frame 1, Frame 2, Frame 3... Frame 32).

When I go to present the slideshow, my show goes Frame 1 -> Frame 2 -> Frame 11... 19 -> Frame 3
I also had it go from Frame 25 to Frame 27 and then end with Frame 26.

I have not edited anything else with the Frames, just used them to wrap around the imported portion from my Obsidian markdown file.

Suspecting that this might be an issue of single digit (Frame 1, Frame 2, etc.) to double digit (Frame 11, Frame 12, etc.), I renamed Frames 1-9 as (Frame 01, Frame 02, etc.). This helped in that the slideshow then went from Frames 1-9... but then jumped to Frame 11 and then placed Frame 10 as the very last slide (after Frame 32). 

I solved this by naming Frame 9 as Frame 9a and then naming Frame 10 as Frame 9b. 
I also did the same for the odd jumping from Frame 25 to Frame 27 by naming Frame 26 as Frame 25b.
This solved the issue and got all of my Frames in order.

So it seems that there's an issue with how Slides is reading the Frame numbers?

**Expected behavior**
I would except the slides to render Frame 1-9, 10-19, 20-29, etc in numerical order (without the need to rename Frames 1-9 as 01, 02, 03, etc.).

**Screenshots**
Screenshot sample of the Excalidraw file I'm working with included.

![Screenshot 2023-07-25 112925](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/123499620/1d4ce1a8-6eb5-4470-a113-fdecbddbfb60)

**Comment by zsviczian** [comment]
I released an update to the slideshow script, and an update to Excalidraw. Hopefully, these two together will resolve the frame sequence in presentations.
