### ISSUE TITLE
BUG: The pen palette is displayed incorrectly.

### ISSUE THREAD

**Issue by kazdonkai** [zsviczian/obsidian-excalidraw-plugin#1245]
[iPad Pro 11inches]
![IMG_2727](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/90127278/c33ed96c-fd29-47ae-b635-29402bc7b879)

Until a while ago, the pen palette was displayed vertically.
However, in recent versions, it is displayed horizontally, cut off from the top of the screen, and only a portion of it is displayed.

(In addition. As you can see in the attached image, the web site is not displayed. )

**Comment by zsviczian** [comment]
For some reason, your Excalidraw switched from tray mode to normal mode. Simply press CTRL/CMD + P to open the command palette, and select `toggle property-panel tray-mode` 

Based on my testing Obsidain.md won't load even if you add an iframe to a markdown document like this

```markdown
<iframe width=600 src="https://obsidian.md" height=500 ></iframe>
```

I also tried canvas, obsidian.md does not load there either. 

Servers can control on which platforms they allow their sites to be included in iframes. Some sites do not allow this at all, others allow it only on desktops. There is nothing I can do about this on the client side.

While android/chrome returns an error stating that the server has blocked the content, unfortunately iOS/Safari apparently does not. Again, nothing I can do about this on the client side.
