### ISSUE TITLE
New splash screen flashes in Excalibrain panel every time I navigate in content panel

### ISSUE THREAD

**Issue by KillyMXI** [zsviczian/obsidian-excalidraw-plugin#1248]
**Your environment**

<details><summary>Click to unfold</summary>

```
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.1.16
	Operating system: Windows 10 Pro 10.0.19044
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 30
	Plugins enabled: 24
		1: Calendar v1.5.10
		2: Advanced Tables v0.19.1
		3: Link Nodes In Canvas v0.0.5
		4: Link Exploder v0.3.0
		5: Canvas Filter v0.9.2
		6: Optimize Canvas Connections v1.0.0
		7: Dataview v0.5.56
		8: Excalidraw v1.9.12
		9: ExcaliBrain v0.2.1
		10: Note Refactor v1.7.1
		11: Icon Folder v2.1.2
		12: File Explorer Note Count v1.2.1
		13: Templater v1.16.0
		14: Pane Relief v0.5.1
		15: Relation Pane v0.0.4
		16: Min Width v1.0.4
		17: Ghost Fade Focus v3.0.0
		18: Tomorrow's Daily Note v1.0.2
		19: Custom File Extensions Plugin v1.0.1
		20: Regex Find/Replace v1.2.0
		21: Sort & Permute lines v0.7.0
		22: Open vault in VSCode v1.2.1
		23: File Color v1.0.3
		24: Heatmap Calendar v0.6.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

</details>

**Describe the bug**
Annoying flash in Excalibrain panel (which is based on Excalidraw).
Was it there before but not as notiable? I'm not sure.
New splashscreen either introduced the issue or made it worse with new contrast artwork.

Note: I use dark theme. Momentary change in brightness might be not as drastic in a light theme.

**To Reproduce**
1. Have Excalibrain panel and content tab visible in some way (I pin Excalibrain to the side panel)
2. Navigate between tabs, links within a tab, etc;
3. Excalibrain panel flashes the new Excalidraw splashscreen briefly before showing the new active page connections graph.

**Expected behavior**
No flashing unrelated content on navigation events.

Not sure whether this is mainly Excalidraw or Excalibrain issue.
I'm not familiar with what happens in the background on navigation events.
Unless there is a way to update content without panel reinitialization, Excalidraw might need to delay the splashscreen content appearance a little. (But make sure background color is correct to avoid even bigger splash.)

**Comment by zsviczian** [comment]
It was there before. It could be that the new artwork made the existing issue more visible. 
I haven't yet had the time to figure it out - and I am also not sure if this comes from ExcaliBrain or Excalidraw.

**Comment by zsviczian** [comment]
Your issue was a good nudge. I think I found the source of the problem. I published a quick ExcaliBrain update. try 0.2.2

**Comment by KillyMXI** [comment]
No splash screen on page switches after update.
Thank you

**Comment by zsviczian** [comment]
It still flashes up sometimes for me... I've made some further changes. Will release likely today.
