### ISSUE TITLE
QUESTION: Is it possible to render a table from a transcluded text?

### ISSUE THREAD

**Issue by foreversun69** [zsviczian/obsidian-excalidraw-plugin#1249]
Hey :-),

first of all, this my setting:
![grafik](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/44213573/a2f07f48-ee4e-4dae-a114-5f52dded2772)

now my question:
- Is it possible to render a table from a transcluded text-file like in the reading view?

this is my result:
![grafik](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/44213573/79e3eef0-b8b7-48cf-b022-61315f41def6)

I'm thinking of something like that:
![grafik](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/44213573/fb5cb1fd-26b5-4644-a0ae-1371e57e464b)

P.S. when i outsource the table in a extra file, then this is the result:
![grafik](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/44213573/a7a264af-da9f-4db1-8e0b-585530568f51)

Mit freundlichen Grüßen
Foreversun

**Comment by zsviczian** [comment]
You have two options, both involve rendering the table in a markdown document.
You can create a markdown document with the table and using the "Insert any file" command either insert the markdown as an image or as an embedded frame. However, inserting as an image, formulas will not render :(

<img width="1258" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/72eb3fb9-5506-40bd-882a-01239ab5a522">

**Comment by foreversun69** [comment]
Hey,

it works :-D

![grafik](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/44213573/af61c580-fc5d-4119-9ada-108f05799bc6)

thank you!

Mit freundlichen Grüßen
Foreversun
