### ISSUE TITLE
Can you add the handle function, press and hold the mouse can drag the screen at will. 

### ISSUE THREAD

**Issue by MILKMILKKING** [zsviczian/obsidian-excalidraw-plugin#125]
Can you add the handle function, press and hold the mouse can drag the screen at will. Because many times you need to drag the screen to view the content, but currently it seems that you can only drag the screen by dragging the scroll bar.

**Comment by zsviczian** [comment]
You can drag by pushing down the scroller (middle button) on your mouse.

**Comment by MILKMILKKING** [comment]
Thanks for the tip!
