### ISSUE TITLE
BUG: Excalidraw does not mantain the configured theme

### ISSUE THREAD

**Issue by David7ce** [zsviczian/obsidian-excalidraw-plugin#1255]
**Your environment**
Obsidian v1.3.7

**Describe the bug**
Obsidian Excalidraw does not maintain the theme

**To Reproduce**
1. Just open Exacalidraw, which is default light theme
2. Turn the theme to "dark mode"
3. Open a new tab, and the Excalidraw stills in "light mode"

**Expected behavior**
I want to use the same theme in all windows, in my case "dark mode"

**Screenshots**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/79609649/40a5d8b9-267b-4c67-86e1-60adc0520e5c)

**Comment by anatoliibakhtin** [comment]
Hello!
Play around with these settings https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1080#issuecomment-1495781971
You may also find this useful: https://www.youtube.com/watch?v=ibdS7ykwpW4&ab_channel=Zsolt%27sVisualPersonalKnowledgeManagement
