### ISSUE TITLE
FR: Import Excalidraw.com supported files(png, svg)

### ISSUE THREAD

**Issue by V4G4X** [zsviczian/obsidian-excalidraw-plugin#1259]
**Is your feature request related to a problem? Please describe.**
It's very frustrating when you want to start using Obsidian for note taking, while having a lot of scenes already created in Excalidraw but being unable to import them into Obsidian because Excalidraw.com supports: 
 - `.excalidraw`
 - `.excalidraw.png`(embeded)
 - `.excalidraw.svg`(embeded)
 While the Obsidian plugin only supports ``.excalidraw.md`( which THEY don't support).

**Describe the solution you'd like**
While it would have been nice to have interoperability between all of them. Since the Obsidian plugin has more features(Obsidian specific) I feel we should atleast have the ability to import from pre-existing Excalidraw scenes into our vaults.

**Describe alternatives you've considered**
I tried looking for features that could import existing drawings in Obsidian but it didn't work, similarly I tried looking for a way to import an excalidraw.com link but I didn't seem to find this.

**Comment by zsviczian** [comment]
You can drag and drop .PNG and .SVG into the scene and if they include an Excalidraw scene then it will convert into the scene.

You can place your. Excalidraw files in your vault and run convert them to .MD using the command palette (excalidraw: convert...). This action is only visible if you have .excalidraw files in some of your vault folders.

**Comment by V4G4X** [comment]
Wow neat! Thanks this happened to work. It will help if you mention this in the readme.
Will close this. 

On a side note, on dragging pre-existing scenes into Obsidian, I've noticed that it doesn't seem to import the internal code-styled text inside of a rectangle. Is this a known bug?
