### ISSUE TITLE
How do I paste the image?

### ISSUE THREAD

**Issue by MILKMILKKING** [zsviczian/obsidian-excalidraw-plugin#126]
How do I paste the image? I have some important images that I want to collect, but it seems that copying and pasting images into Excalidraw is not supported yet.

**Comment by mure** [comment]
There's an issue tracking this in the excalidraw repo: https://github.com/excalidraw/excalidraw/issues/19

**Comment by nhaouari** [comment]
I hope this PR (https://github.com/excalidraw/excalidraw/pull/3424) will be merged soon to Excalidraw, meanwhile, It would be very useful if it is added as an experimental feature.

**Comment by zsviczian** [comment]
1.4.0 resolves this.
