### ISSUE TITLE
BUG: "Insert File From Vault" -> "Select section heading", don't works when heading is a date

### ISSUE THREAD

**Issue by Astro1963** [zsviczian/obsidian-excalidraw-plugin#1262]
Hi,
I have a file in my vault where I put some notes for each day, somelike this:

## 02.08.2023
...some notes
## 03.08.2023
...some notes

---

Now, if I insert this file in Excalidraw with "Insert File From Vault" and choose "Select section heading" (for example ## 03.08.2023), I have an error "_Unable to find section # 03.08.2023_".

Note:
The error also appears if I write the dates in the form 03/08/2023. 
Instead, if I write the dates in the form 03-08-2023 it works!

Thanks for attention.
Regards,
Luigi

**Comment by zsviczian** [comment]
it's actually not the date, but the dot ".".  And there were a number of other characters that caused problems. I fixed this in 1.9.14

**Comment by Astro1963** [comment]
Yes, I figured it because 02-08-2023 works.
Thanks
