### ISSUE TITLE
I want the preview box to appear after hovering over the [[note]] notes added inside the Excalidraw drawing board.

### ISSUE THREAD

**Issue by MILKMILKKING** [zsviczian/obsidian-excalidraw-plugin#127]
Hover over the [[Notes]] to bring up the preview box. It's just like in the usual OBSIDIAN notes.
Excalidraw is really great! She is my important notes organizing tool, but currently I can only open it separately to view the [[notes]] inside, which is still a bit inconvenient.
It would be a great upgrade to be able to hover over [[notes]] and then have a preview box appear!

**Comment by zsviczian** [comment]
Hm... it does for me. CTRL+Hover should work for you as well.

I also recommend installing [Ozan's Image in Editor plugin](https://github.com/ozntel/oz-image-in-editor-obsidian). It supports Excalidraw drawings as well.

Do you have the Page Preview core plugin enabled?
![image](https://user-images.githubusercontent.com/14358394/130141980-c0f7efd3-d12c-4f7f-b469-c31e498082fd.png)

**Comment by MILKMILKKING** [comment]
Sorry I didn't explain clearly, what I meant was: I want the preview box to appear after hovering over the [[note]] notes added inside the Excalidraw drawing board.

![微信图片_20210820101021](https://user-images.githubusercontent.com/69726213/130168265-97de647b-3a60-4a97-8e58-1f04ed3fa361.png)

**Comment by zsviczian** [comment]
I understand.
I managed to implement a solution. There are still a few issues to work out, but I hope to release it within the next day.

**Comment by zsviczian** [comment]
solved in 1.2.15
