### ISSUE TITLE
FR: Support for images outside of the vault (file:/// links)

### ISSUE THREAD

**Issue by Krakor92** [zsviczian/obsidian-excalidraw-plugin#1273]
I’m surprised nobody ask for that yet but It would be super useful to handle external images (from outside the vault).

Right now when I open the file explorer app and drag an image in one of my excalidraw.md files while pressing Ctrl, it copies the image inside the vault. 

Do you think it would be possible to not copy the file, and have a `file:///` link pointing to it instead which would work as in regular .md files?

**Comment by zsviczian** [comment]
I am actually not sure that the Obsidian/Electron security will allow that. Would be more reassuring if it didn't, but I can check.

**Comment by Krakor92** [comment]
That's what I thought at first too but the following works in markdown file inside Obsidian: `![](file:///link/to/the/file.jpg)`. 

You can close this issue if you deem it would entail a too big security risk to do the same in Excalidraw.

Besides, I've searched for a workaround and it's very easy to just run a local file server using any 3rd party utility (with the --cors flag enabled). It works like a charm even with audio and video.

Sorry for the inconvenience 🙏

**Comment by PlayerMiller109** [comment]
I found that the recent Excalidraw Plugin Api `addImage()` method allows for adding images from outside of the vault if the string provided starts with `file://`. Note that all spaces within the string must be replaced with `%20`. Cool.

**Comment by zsviczian** [comment]
Yes, and you can encode filename with `encodeURI("file://this is my file")`

I should have closed this issue a long ago. The plugin supports file:// links for a long time now.

**Comment by pipme** [comment]
Could you please give some pointers on the best way to do it at the moment? @Krakor92 @zsviczian  Sorry I am pretty newcomer to excalidraw. Thanks for the excellent plugin! 
(Related to https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1365 I just replied)

**Comment by pipme** [comment]
I found it [here](https://www.youtube.com/watch?v=CpSwwv1CPMM&t=2651s). In MAC it's to hold `option` key when dragging. It works great thanks!
