### ISSUE TITLE
BUG: Excalidraw not working on Samnsung Galaxy Tab S6

### ISSUE THREAD

**Issue by pikatwinky** [zsviczian/obsidian-excalidraw-plugin#1274]
I don't know how to exactly describe this problem but yesterday i decided to sync my vault with my android tablet (for the first time ever) and realized Excalidraw was not working in the same way as in my mobile or my pc.
It was showing this message being in the live preview and with the Excalidraw plugin activated on notes having excalidraw attachments
![SmartSelect_20230810-092108_Obsidian](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/31860235/2042f851-a1a5-418f-9064-eaec2c210bfd)
i was running the latest Obsidian public release and excalidraw 1.9.12 at this moment (the same vault was showing normally on my phone and pc)
After that I updated to the latest Obsidian Insider build and Excalidraw 1.9.14 but when tried to enable the second i received this error 
![SmartSelect_20230810-093825_Obsidian](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/31860235/a1884253-2462-4135-a40c-c005fc327258)
At this moment i realized other plugins were working normally, and also tried to create a new empty vault with only the excalidraw plugin installed but the same message still kept coming up

I could install manually a previous excalidraw version (Excalidraw 1.8.26) but when i created a new draw and opened it, the Excalidraw interface appeared as if not loading
![SmartSelect_20230810-095226_Obsidian](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/31860235/3fd053e7-5123-4ae7-b898-43fcceffebe2)

I experienced this on a Samnsung Galaxy Tab S6 runnning Android 10

Thanks for your valuable help and this fantastic plugin

**Comment by zsviczian** [comment]
You probably need to update android webview.

for reference see #181

**Comment by pikatwinky** [comment]
Solved updating Android Webview from the Play Store as you said Zsolt. 
Thank you so much for your valuable help and all your hard work!
