### ISSUE TITLE
FR: Ability to customize default Obsidian tag for drawings

### ISSUE THREAD

**Issue by Compg** [zsviczian/obsidian-excalidraw-plugin#1276]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to customize default Obsidian tag applied to drawings from plugin settings

**Describe alternatives you've considered**
Manual overwrite, per drawing, in markdown view

**Additional context**
I have a defined tag ontology in my vault. My tables, drawings, etc are organized under a parent tag. Would be great if there was a setting that would allow to set this for the plugin.

**Comment by zsviczian** [comment]
Create a template. I recommend watching the whole video, but the part that you are interested in is at this timestamp: https://youtu.be/jgUpYznHP9A?t=216

**Comment by Compg** [comment]
Thank you, this worked perfectly! I created a new drawing, updated tag in markdown view, and set path to file in plugin settings per video. I then used tag wrangler to update my legacy drawings.
