### ISSUE TITLE
FR: Lock selected elements on canvas

### ISSUE THREAD

**Issue by Captain-Pumpkinhead** [zsviczian/obsidian-excalidraw-plugin#1277]
**Is your feature request related to a problem? Please describe.**
If you draw on top of an image and you pull out an eraser, this erases both the stroke and the image.

**Describe the solution you'd like**
When an element is selected, under the Actions tab next to Copy, Delete, and Link, there should be a Lock option.  When active, this lock would prevent an element from being moved, resized, or deleted.

**Describe alternatives you've considered**
A current workaround is to use the select tool to highlight the stroke and press the delete key.  This is not as elegant, but it does work just fine.

**Additional context**
This actually arose from a workaround for something else.  There appears to be no way to move or delete PDF pages.  I'm filling out my college course's lecture notes on Obsidian-Excalidraw, and not every page is used.  I could select specific pages when importing, but I don't know which pages will be skipped until my professor gets to that point in the lesson.  To workaround this, I've been importing the PDF as images, so I can delete or move the pages as needed.  I suppose I should probably submit a different FR for that specifically.

**Comment by zsviczian** [comment]
I might be misunderstanding you... there is already a lock option. Right-click the locked element and select unlock to unlock.

<img width="271" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/3d8b1cc4-3b39-4c68-9620-e504c7c2d048">

**Comment by Captain-Pumpkinhead** [comment]
I feel embarrassed that I missed that.  I think I should've searched the documentation before opening this FR.  My apologies.  Thank you!

What I had in mind was something like this, but if it's already implemented, then it doesn't matter too much where it is.
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/74560023/539a03f0-822f-4187-b063-1d55c8109ea0)
