### ISSUE TITLE
Cannot see the drawing panel when I create an excalidraw 

### ISSUE THREAD

**Issue by erdemalpkaya** [zsviczian/obsidian-excalidraw-plugin#128]
When I create a new Excalidraw it opens a blank page but there is no drawing panel.

I tried in many ways but still the same.

I use a MacBook pro
Obsidian version: v0.12.13
Excalidraw version: 1.2.14

![2021-08-21_14-15-16](https://user-images.githubusercontent.com/24259112/130307447-a6faaf21-b103-4260-a162-36a902b29a2b.jpg)

Update: When I create an excalidraw file on my phone everything is fine but I cannot see the file in macbook however when I create a new excalidraw on my MacBook I can see the file as a .md file on my phone.

**Comment by zsviczian** [comment]
very strange...

Can you click the ... in the top right and switch to Markdown view and send a screenshot.
Also, can you press CTRL+SHIFT+I and send me the error you see in the console?

**Comment by erdemalpkaya** [comment]
Hi thank you for a quick response.

1. Here is the markdown file:
![2021-08-22_07-15-29](https://user-images.githubusercontent.com/24259112/130332868-4f4fb75a-d9fa-42c0-aebb-f53f00b66e84.jpg)

2. Console result:
![2021-08-22_07-29-15](https://user-images.githubusercontent.com/24259112/130332937-c44cd4a8-6177-427d-85bb-a2fd9dda711e.jpg)

3. Yes I am using Obsidian and excalidraw long time (Windows 10) but the first time I tired to create a excalidraw on my macbook. I am going to re-install obsidian no problem

4. The same result. test.excalidraw was blank and no drawing panel.

**Comment by erdemalpkaya** [comment]
Yes, you are right. I re-installed the obsidian and now everything is fine. Thank you for your help.

**Comment by zsviczian** [comment]
Thanks for the confirmation. Seems there was some issue with the Electron version.
