### ISSUE TITLE
BUG: Latex/MathJax color directives aren't working anymore since the latest release

### ISSUE THREAD

**Issue by Altaks** [zsviczian/obsidian-excalidraw-plugin#1289]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.

SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.1.9
	Operating system: Windows 10 Home 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 9
	Plugins enabled: 9
		1: 3D Graph v1.0.3
		2: Advanced Tables v0.19.1
		3: Charts View v1.2.5
		4: Completr v3.2.0
		5: Obsidian Functionplot v1.2.1
		6: Smarter Markdown Hotkeys v1.16.4
		7: TikZJax v0.5.1
		8: Underline v1.2.1
		9: Excalidraw v1.9.17

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**

The \color and \textcolor tags don't work anymore in latex formulas integration within the canvas

**To Reproduce**
1. Go on a obsidian-excalidraw canvas
2. Add a colored mathjax/latex equation
3. Observe that the color directives are not processed

**Expected behavior**

As it worked like 2 days ago, the latex/mathjax output should be colored

**Screenshots**

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/57632793/14ad5e7c-9d4a-4a12-81c9-2bccf919476f)

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/57632793/b89ee926-437d-4bf0-8b4f-cf2db0502845)

**Additional context**
None

**Comment by YandLiu** [comment]
Check this answer to solve it.
https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1240#issuecomment-1648593720

**Comment by zsviczian** [comment]
Resolved in 1.9.25. From 1.9.25 the mathjax package is included in the plungin source and works without (or with slow) Internet connection.
