### ISSUE TITLE
How to set the menu language, have you removed the multi-language support?BUG: 

### ISSUE THREAD

**Issue by Ghost-Cavendish** [zsviczian/obsidian-excalidraw-plugin#1294]
How to set the menu language, have you removed the multi-language support?

**Comment by zsviczian** [comment]
same as #1297
Unfortunately, the Excalidraw package does not include the language files.  This has been very low on my list of priorities. Adding them requires development. I haven't found the time yet.

 I will track the resolution under #1297 and close this one.
