### ISSUE TITLE
FR: Multilingual menu

### ISSUE THREAD

**Issue by QSC707** [zsviczian/obsidian-excalidraw-plugin#1297]
I'm sorry my English is not very good

The English of the menu options and right-click menus in Excalidraw affected my experience

Hope to add multi-language support

Please add my native language if you can. Chinese is my native language

**Comment by zsviczian** [comment]
yes, this needs a little work. Unfortunately, the translations are not included in the Excalidraw package by default. I haven't yet had the time to get to the bottom of this feature.

**Comment by zsviczian** [comment]
I think I found the solution. Will release it in 1.9.18 tonight.

**Comment by Ghost-Cavendish** [comment]
Why is there still no multi-language support?

**Comment by zsviczian** [comment]
@Ghost-Cavendish - depends on what you are looking for.
If you switch the language in Obsidian Settings, the Excalidraw package will follow the language change. That works, I've just tried it.

<img width="1074" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/b5327c3e-d658-4b16-a526-abdb95e81a84">

The plugin only supports languages for which someone created a translation. That is limited to Chinese support at the moment. It seems local language support is not so important to others.
If you feel the energy to create a translation I welcome PRs.

**Comment by Ghost-Cavendish** [comment]
支持中文吗，我需要的就是中文，但是我切换了 Obsidian 语言为中文，Excalidraw 并没有切换为中文。

**Comment by Ghost-Cavendish** [comment]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/56330712/94e911a1-6ac3-44a7-966e-701ef9822220)
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/56330712/315a6578-cb99-4b43-b5a4-796de557b98b)
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/56330712/b588ccf7-d00d-4933-ae89-275a339552dc)

**Comment by zsviczian** [comment]
language support is only there for zh-cn. Not sure if that is what you are using or not.
