### ISSUE TITLE
BUG: Background grid jitters when panning

### ISSUE THREAD

**Issue by Crusher50** [zsviczian/obsidian-excalidraw-plugin#1298]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.

SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.3.7
	Operating system: #1 SMP PREEMPT_DYNAMIC Wed Aug 16 17:42:12 UTC 2023 6.4.11-200.fc38.x86_64
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Border v1.4
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 18
	Plugins enabled: 15
		1: HTML Tags Autocomplete v0.0.7
		2: Meld Calc v1.0.2
		3: Various Complements v8.4.1
		4: Mind Map v1.1.0
		5: Excalidraw v1.9.17
		6: Advanced Tables v0.19.1
		7: Style Settings v1.0.6
		8: Omnisearch v1.15.2
		9: Text Extractor v0.4.6
		10: Better Word Count v0.10.0
		11: Homepage v3.5.1
		12: Find orphaned files and broken links v1.9.0
		13: Quick Latex for Obsidian v2.6.2
		14: Latex Suite v1.7.4
		15: LanguageTool Integration v0.3.4

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**

The background grid jitters when panned.

**To Reproduce**
1. create a new drawing
2. Enable background grid
3. pan the workspace

**Expected behavior**

The background should pan correctly and not jitter.

**Screenshots**

**Additional context**

**Comment by zsviczian** [comment]
I noticed as well. Fixed it in 1.9.18. Will release over the weekend.
