### ISSUE TITLE
BUG: Excalidraw crash when moving to popout window

### ISSUE THREAD

**Issue by cricrou** [zsviczian/obsidian-excalidraw-plugin#1300]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.1.16
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Blue Topaz v20230704
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 24
	Plugins enabled: 24
		1: Jira Issue v1.54.0
		2: Kanban v1.5.3
		3: Tasks v4.6.0
		4: Calendar v1.5.10
		5: Banners v1.3.3
		6: Dataview v0.5.56
		7: DB Folder v3.4.0
		8: Paste image Png to Jpeg v1.0.4
		9: Tag Wrangler v0.5.11
		10: Omnisearch v1.15.2
		11: Text Extractor v0.4.6
		12: MetaEdit v1.8.0
		13: Metadata Menu v0.5.1
		14: Icons v0.3.0
		15: Multi-Column Markdown v0.8.3
		16: Obsidian Columns v1.5.0
		17: Global Search and Replace v0.3.0
		18: ReadItLater v0.3.1
		19: Open Gate v1.9.1
		20: Excalidraw v1.9.17
		21: ExcaliBrain v0.2.8
		22: Contacts v1.1.0
		23: Local REST API v1.6.0
		24: Advanced Tables v0.19.1

**Describe the bug**
An excalidraw drawing is opened in a tab, I click on the tab and select the option Move to new window. Quickly a new window open and obsidian crashes soon after.
The drawing contains 3 iFrame displaying websites and 2 vault's pages

**To Reproduce**
1. Go to an excalidraw containing Iframe displaying websites
2. Click on the tab with a right click
3. Select the "Move to new window" option
4. A new blank window open and obsidian crashed

**Expected behavior**
The window opens and displays my excalidraw drawing, the tab is removed from the main obsidian window

**Screenshots**
N/A

**Additional context**
Doing the same with an excalidraw drawing only having shapes on it doesn't get the same behaviour, the windows opens correctly and the tab is removed from the main obsidian window.
Also opens the drawing containing iFrame directly to a new window (i.e. not from an existing tab) works perfectly

**Comment by zsviczian** [comment]
Can you reproduce the issue? I tried reproducing but could not.

**Comment by cricrou** [comment]
Yes I do this morning, having a drawing already opened in the main windows of obsidian, right-click on it and select "Move to new window" begin to open a new window = obsidian crash

**Comment by zsviczian** [comment]
Are you also able to reproduce the error in a blank vault, or when you disable all the other plugins? If you disable plugins please restart Obsidian before testing because sometimes plugins don't do a good job of offloading all their components.

**Comment by cricrou** [comment]
Just tested with a new vault enhanced with excalidraw and excalibrain only, works perfectly. So it seems to occurs when some others plugins are installed, sorry for the inconvenience.
