### ISSUE TITLE
FR: Unify the size of mutiple images

### ISSUE THREAD

**Issue by GYC-lab** [zsviczian/obsidian-excalidraw-plugin#1306]
Firstly, I would appreciate this excellent plugin for Obsidian. It brings me a lot of convenience. 

To the best of my knowledge, when manipulating multiple images, this plugin can align them very well. However, the size of images may be different. And it seems that Excalidraw has not supported the adjustment of the size of many images in one time. 

So the feature I want to suggest is that the plugin can **unify the size of multiple images**, if possible.

Thank you very much.

**Comment by zsviczian** [comment]
This could be done with a simple Excalidraw script.  I think this script does what you need. Copy the file to Excalidraw/Scripts, select the images you want to resize on the canvas and use the command palette to run the script.

[resize images.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/12565353/resize.images.md)

This is the chatGPT prompt I used to generate this script: https://chat.openai.com/share/3f7aa783-2f2e-4ad6-a782-a3b068cb35dc

**Comment by zsviczian** [comment]
I just noticed there is already a script in the script library "Uniform Size" Install it and it will do the job for you.

**Comment by GYC-lab** [comment]
Thanks for your helpful reply! 

I've tried to installed `resize images.md` that your provided and it works well. 

BTW, the already existing script `Uniform Size` seems only able to handle simple patterns like diamonds, not images.

Again thanks for this brilliant plugin!

**Comment by jiajiala** [comment]
@zsviczian 
This plugin will change the original length-to-width ratio of the image, resulting in image distortion. Is there any way to make the height and size of all pictures the same without changing the ratio of the image

**Comment by jiajiala** [comment]
Grid selected images        This function can be completed
