### ISSUE TITLE
BUG: Can't see the frame-border

### ISSUE THREAD

**Issue by foreversun69** [zsviczian/obsidian-excalidraw-plugin#1310]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.4.5
	Installer version: v1.4.5
	Operating system: #91~20.04.1-Ubuntu SMP Fri Aug 18 16:24:39 UTC 2023 5.15.0-82-generic
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: 80s Neon v0.0.0
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 31
	Plugins enabled: 16
		1: Footnote Shortcut v0.1.3
		2: Note Refactor v1.8.1
		3: obsidian-title-index v0.4.0
		4: Reminder v1.1.15
		5: Templater v1.16.0
		6: Remember cursor position v1.0.7
		7: Calendar v1.5.10
		8: Dataview v0.5.56
		9: Supercharged Links v0.10.0
		10: Kanban v1.5.3
		11: Snippets plugin v0.0.4
		12: Excalidraw v1.9.19
		13: Periodic Notes v0.0.17
		14: Advanced Tables v0.19.1
		15: Outliner v4.8.0
		16: Diagrams v1.5.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
Hi, i can't see any frame-border. e.g. example 1 i have 30 Frames, i can start and choice the frames in slideshow, but i cant see (or rename it) the frames.

## 1. Example 
the json-code for Frame 02, what i will take for the screenshots:
```json
{
			"type": "frame",
			"version": 1222,
			"versionNonce": 54886182,
			"isDeleted": false,
			"id": "iRkSlNXCNZIkeqfylFAlv",
			"fillStyle": "solid",
			"strokeWidth": 1,
			"strokeStyle": "solid",
			"roughness": 0,
			"opacity": 100,
			"angle": 0,
			"x": -2454.8920665722794,
			"y": -1608.8644756080942,
			"strokeColor": "#bbb",
			"backgroundColor": "transparent",
			"width": 549.2066449308181,
			"height": 450.9245429672595,
			"seed": 1386541144,
			"groupIds": [],
			"frameId": null,
			"roundness": null,
			"boundElements": [],
			"updated": 1693920085004,
			"link": null,
			"locked": false,
			"name": "Frame 02"
		},
```
**Screenshots**
- i can click the Frame02:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/44213573/47a33816-89ea-4f1b-89a6-16afbafde185)

- but i can see it:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/44213573/a0cf4313-cbf9-4067-b09f-4b693aefa8b8)

- here a image, you can see the slideshow:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/44213573/148fdc4c-3c8b-424c-9625-327f9ca87c4d)

## 2. Example

![grafik](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/44213573/a7a5a84c-f931-4c28-8267-ed2754a0fe81)

Example 2 i have created yesterday 06.09.2023 ( yesterday the frame-border was visible ), but today, the frame-borders are invisible.

Best regards.

**Comment by zsviczian** [comment]
Depending on how the presentation script terminates sometimes it does not reset frame rendering. This typically happens when you close the tab without first stopping the presentation. Try command palette toggle frame rendering.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/e9088331-b1f4-4497-8fc3-7cf0b95142db)

**Comment by foreversun69** [comment]
i can see the frames, thank you! :-)
