### ISSUE TITLE
FR: Show exist links when typing link

### ISSUE THREAD

**Issue by wiztensai** [zsviczian/obsidian-excalidraw-plugin#1321]
Hi, thank you very much for making this plugin. However, there are features that I want to request to make this plugin even better

**Is your feature request related to a problem? Please describe.**
I really need this feature because I have so many links. so the link completion feature when typing a link is very useful for that

**Describe the solution you'd like**
When you type a link, a list of links will appear starting from that type. For example, when you type gl, the list that appears is glass, glare, etc.

[image](https://ibb.co/D4cBSw3)

**Comment by zsviczian** [comment]
This is a more invasive change that I am not planning to implement any time soon. Some day maybe. You can install the scribble helper script which offers an option to select links, or use the "Insert link" command palette action.

**Comment by wiztensai** [comment]
I really appreciate your suggestion to use the scribble helper script and the 'Insert link' option from the command palette. Thank you for providing this alternative. Nevertheless, I want to emphasize that the features I proposed for link completion would be very helpful in my work. I understand that these changes may take time, but if there is a plan to implement them in the future, that would be very helpful. Thank you for your attention
