### ISSUE TITLE
Cannot Create New Drawing in Obsidian v0.12.12

### ISSUE THREAD

**Issue by davidlee321** [zsviczian/obsidian-excalidraw-plugin#134]
**Describe the bug**
Cannot Create New Drawing in Obsidian v0.12.12 (Excalidraw v1.2.23)

**Screenshots**
Trying to create a new drawing gives a blank document with no drawing tools in sight.

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Browser: I'm not sure if Obsidian's Excalidraw plugin is using any particular browser to render within obsidian.

**Additional context**
New to excalidraw plugin. Watched the first video on it. I don't see the drawing tools when try to create new drawing.

**Comment by zsviczian** [comment]
hm... are you a long-time Obsidian user?

**Comment by zsviczian** [comment]
Please see this other issue: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/128 
A reinstall of Obsidian was the solution - it seems if you have an old installer version then there is a difference in the Electron browser that causes this

of course in your case the issue might be something different... just guessing.

**Comment by davidlee321** [comment]
Thanks for weighing in.

> process.versions.electron
"8.2.5"

**Comment by zsviczian** [comment]
So most probably that is the issue. You have an old Electron - probably an old installer. My version is "12.0.6"

I'll implement a popup notice based on the electron version.

**Comment by davidlee321** [comment]
Yeah that was the issue. Resolved after reinstalling obsidian. Great drawing app by the way.
