### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by Raboro** [zsviczian/obsidian-excalidraw-plugin#1342]
Hi, with a [grammer checker ](https://quillbot.com/grammar-check) I get the following issues:

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/88288557/29eedafb-943c-44fa-82e8-a7cc69242f6b)

I can do a PR fixing those or you can do it by yourself.

**Comment by zsviczian** [comment]
happy to receive a PR
