### ISSUE TITLE
FR: hand tool by default on mobile

### ISSUE THREAD

**Issue by ctwhome** [zsviczian/obsidian-excalidraw-plugin#1344]
While reviewing drawings on my mobile, it would be more convimient if the hand tool was selected by default instead of select. That way I could jump from drawing to drawing without accidentally moving things.

It would be nice to have a setting tool that defines what tool should be allways enabled by default after opening a drawing in mobile.

**Comment by zsviczian** [comment]
have you tried the below in Excalidraw plugin settings? 

Interestingly you could also achieve this by modifying your Excalidraw template file by adding the following to the YAML frontmatter of your Excalidraw Template file (you need to switch to markdown view mode). This will apply to all new drawings. You can of course go back to old drawings and modify the frontmatter with this...

```text
excalidraw-onload-script: "if(app.isMobile) ea.getExcalidrawAPI().setActiveTool({type: 'hand'});"
```

<img width="1265" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/b7c6a6db-1cd6-4e81-8900-94e255f8f5e2">

or if you are using the property editor (you can disable the property editor and view the frontmatter in the "old" style in Obsidian / Editor settings - that is my preference):

<img width="887" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/f4d6792b-24ae-4e13-8cd2-63e1b9fbfaf0">

and the setting how to open on mobile

<img width="1079" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/69949060-04dc-4dc6-9584-19706cfb52f9">

**Comment by ctwhome** [comment]
That worked beautifully! thank you very much. I also got rid of the sketchy font not that I am using the template for the first time 😅

**Comment by ctwhome** [comment]
Hi @zsviczian I have to reopen this issue because I didn't notice that the draws can't choose any other tool when opening on mobile (android). I can't edit the drawings on mobile if
`excalidraw-onload-script: "if(app.isMobile) ea.getExcalidrawAPI().setActiveTool({type: 'hand'});"` exists in the front matter. 

I still think it might be better if there is an option in settings to define open-in-hand mode on mobile, but ofcourse let other tools be selected to edit the note.

**Comment by zsviczian** [comment]
I am able to reproduce. This seems like an issue in the Excalidraw API. I am looking into it.

**Comment by zsviczian** [comment]
I have a solution that will enable the `excalidraw-onload-script:` recommended above to work.
I will release in 1.9.26

**Comment by ctwhome** [comment]
> I have a solution that will enable the `excalidraw-onload-script:` recommended above to work. I will release in 1.9.26

thank you for your time. 

In case it is useful for someone I created this nodejs script to add the property to all existing drawings.
Place the file at the root of the folders that contain the drawings (it can be the root folder of the vault) and run with `node filename.js`. It will recursively read subfolders as well. 

```js
const fs = require('fs');
const path = require('path');

function insertLineIntoFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');

  // Find the index where the "tags: [excalidraw]" line is
  const index = lines.findIndex(line => line.trim() === 'tags: [excalidraw]');

  // If found, insert the new line right after it
  if (index !== -1) {
    lines.splice(index + 1, 0, `excalidraw-onload-script: "if(app.isMobile) ea.getExcalidrawAPI().setActiveTool({type: 'hand'});"`); 
    fs.writeFileSync(filePath, lines.join('\n'));
  }
}

function readFilesRecursively(directory) {
  const files = fs.readdirSync(directory);

  for (const file of files) {
    const filePath = path.join(directory, file);
    const stat = fs.statSync(filePath);

    if (stat.isDirectory()) {
      readFilesRecursively(filePath);
    } else if (filePath.endsWith('.excalidraw.md')) {
      insertLineIntoFile(filePath);
    }
  }
}

// Start reading files from the current directory
readFilesRecursively(process.cwd());

```

**Comment by ctwhome** [comment]
I am sorry to report that it didn't work. I tried again, but I am afraid that doesn't work. If I add the line in the properties, I can't use anymore other elements of the interface, can't edit, or interact with anything. I strongly suggest to add this option as a feature in settings, otherwise is too complicated for people start using it, in case that finally works of course.

**Comment by zsviczian** [comment]
Hmm. Iv will need to do more testing. The issue is, that if I add this as a setting, technically the same issue will happen... Excalidraw will get stuck with the hand tool. I need to work out why the tools panel cannot focus if the hand tool is activated from code on startup. For now the view mode on mobile setting is what I can offer. Long pressing on the drawing you can turn off view mode from the context menu.

**Comment by zsviczian** [comment]
Check 1.9.28... I think I finally found the root cause. This should fix your situation as well.
In time I will try to find the time to add the hand configuration to settings, but for now, your onstart script should work properly.

**Comment by ctwhome** [comment]
Thank you @zsviczian ,I'll try it as soon as possible and I'll let you know. Thanks for your time and efforts

**Comment by zsviczian** [comment]
https://youtu.be/OX5_UYjXEvc
![Thumbnail - 20231109 Excalidraw on-load script (Custom)](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/8d741faf-9ce6-4d83-bb7a-fdc887a30918)

**Comment by ctwhome** [comment]
It works beautifully, thanks again for all the effort
