### ISSUE TITLE
BUG: freehand writing automatically closes a curve when the start and end comes close.

### ISSUE THREAD

**Issue by OB0NE** [zsviczian/obsidian-excalidraw-plugin#1357]
**Describe the bug**
When I want to draw a circle with a small gap using the freehand writing tool, it automatically draws a line between  the start and the end so that the circle becomes closed.
**To Reproduce**
1.Select the freehand writing tool(pens);
2.Try to draw a circle with a small gap; 
some thing look like this:(this is a picture drawn using  other note apps)
<img width="77" alt="截屏2023-10-07 21 24 54" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/144986313/9a8fbc83-3a2d-4867-b560-ccbaf8a6496b">
3.When you finished drawing and raise the pen tip or release the mouse, there will be a line drawn automatically between the start and the end of the curve, making it a closed circle.
some thing look like this:(this is a picture drawn using excalidraw)
<img width="77" alt="截屏2023-10-07 21 24 54" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/144986313/5ce580cf-47da-43f6-92d4-2f64462ab381">

**Expected behavior**
The line will stop exactly the place where you raise the pen tip or release the mouse .

**Additional context**
This is a video showing this situation:
https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/144986313/1971cc7d-cae2-4305-a0a0-3ecb8cd14b1e

**Comment by FegDotExe** [comment]
Same happens to me on my ipad; it can get pretty annoying when taking notes.

**Comment by zsviczian** [comment]
Which pen are you using: the default pen or one of the custom pens? Excalidraw does not add points to the line, however, it runs a smoothing function on the line when it is finalized. The relative impact of the effect depends on the zoom level and line width. 

You may want to try some of the alternative pens that you can configure via settings. Here's a video that explains it:
https://youtu.be/OjNhjaH2KjI?si=dNssXLIamye4vFZw&t=69

As for the "O" shape with a background filling... though this was not a question, but may be an issue as well. You can set the fill color to transparent in the element properties window. You can also configure custom pens such that they automatically set the stroke background color to transparent when you use the pen.

**Comment by anatoliibakhtin** [comment]
@OB0NE Hello, I think you meant to make a request to add this feature to the custom pens settings, as there is no such option in the custom pens so far to disable the autoclosing of the start and end of a line

The problem was also discussed here https://github.com/excalidraw/excalidraw/issues/5948

**Comment by OB0NE** [comment]
> Which pen are you using: the default pen or one of the custom pens? Excalidraw does not add points to the line, however, it runs a smoothing function on the line when it is finalized. The relative impact of the effect depends on the zoom level and line width.
> 
> You may want to try some of the alternative pens that you can configure via settings. Here's a video that explains it: https://youtu.be/OjNhjaH2KjI?si=dNssXLIamye4vFZw&t=69
> 
> As for the "O" shape with a background filling... though this was not a question, but may be an issue as well. You can set the fill color to transparent in the element properties window. You can also configure custom pens such that they automatically set the stroke background color to transparent when you use the pen.
@zsviczian 
I have tried the default pen, fine tip pen and the fountain pen, they all have the same problem. 
As for the smoothing function, do you mean the 'easing function' in the 'perfect freehand settings'? I have tried all the functions, and none of them solve the problem. So I wander if it's possible to add a smoothing function to the 'easing function' in the 'perfect freehand settings' so that after the function is run ,the start and end of a line will not autocolse?
And in my demonstration, I have already set the stroke background color to transparent.

> @OB0NE Hello, I think you meant to make a request to add this feature to the custom pens settings, as there is no such option in the custom pens so far to disable the autoclosing of the start and end of a line
> 
> The problem was also discussed here [excalidraw/excalidraw#5948](https://github.com/excalidraw/excalidraw/issues/5948)
@anatoliibakhtin 
I think you are right. I meant to add a smoothing function to the custom pens settings that will not autoclose the the start and end of a line.

**Comment by masoongkg05** [comment]
This is a problem I am also experiencing. I hope it gets resolved.

**Comment by OB0NE** [comment]
Problem solved.
See:
https://github.com/excalidraw/excalidraw/pull/7510
