### ISSUE TITLE
FR: one-finger scrolling when in pen mode from mobile

### ISSUE THREAD

**Issue by FegDotExe** [zsviczian/obsidian-excalidraw-plugin#1358]
**Is your feature request related to a problem? Please describe.**
I use obsidian-excalidraw to take handwritten notes from my ipad; I find it silly that when I'm in this mode I can enable double-finger pinching in order to zoom, but I have to press on the hand icon each time I want to move my view to someplace different, making what would be a pretty immediate operation turn into a slightly longer (but in the long time, much more annoying) task.

**Describe the solution you'd like**
I would like to be able to use a finger while in pen mode in order to move the view, just like I would with the hand tool but without the need of selecting it each time and then going back to my pen (in other words, I would like for this to be enabled while having a pen or a custom pen selected).

**Describe alternatives you've considered**
I've searched online for solutions, but I haven't really found them. I realized that this may involve palm-canceling and many complex things, but I just thought it would really be a great qol addition.

**Comment by ctwhome** [comment]
Somehow related to this https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1344 1

**Comment by wwwportal** [comment]
I second this. 

1. zooming and panning with fingers
2. drawing with tablet pen
3. without manually switching between the hand tool and the pen tool everytime.

With this feature I won't have to use the Concepts and thus be able to take all my notes on obsidian. I hope this will be resolved soon!

Much thanks

**Comment by danilobso** [comment]
I also think this is the most important feature to make Excalidraw on Obsidian my go to not taking app!
Thanks very much for the development do far!

**Comment by Kettenotter** [comment]
> I second this.
> 
> 1. zooming and panning with fingers
> 2. drawing with tablet pen
> 3. without manually switching between the hand tool and the pen tool everytime.
> 
> With this feature I won't have to use the Concepts and thus be able to take all my notes on obsidian. I hope this will be resolved soon!
> 
> Much thanks

I am also using concepts for the same reason. It’s just incredible frustrating that the basic navigation is missing for drawing properly in excalidraw.
Like you can move when holding two fingers and dragging but then it doesn’t move at the right speed. And one finger doesn’t work at all in pen mode.

It should use the fingers as reference points and always try to maintain their location. This how is it done in nearly every drawing application. (It already does it for one finger pan, two finger zoom but not two finger pan)

For now I can also recommend to export svg‘s from concepts (iPad app) and embed them into obsidian.

**Comment by ctwhome** [comment]
Since it is possible to detect both finger and pen simultaneously, how difficult would it be to implement this feature?

**Comment by SimBacon** [comment]
Single-finger panning while drawing is second nature to me, and it is an essential feature to quickly capturing your ideas.

I am a OneNote convert, thanks to the amazing Obsidian-Excalidraw plugin! This feature alone would make me never even think about using OneNote again.
