### ISSUE TITLE
CJK can't  wrap for transcluded text in curly brackets.

### ISSUE THREAD

**Issue by kazdonkai** [zsviczian/obsidian-excalidraw-plugin#136]
Since Japanese (CJK) is a language that does not write with spaces between words, it cannot be wrapped.

This is what I wrote on Twitter.

**Comment by zsviczian** [comment]
And I've been thinking about the issue since. 
Unfortunately, a CSS solution will not work, it would require a more invasive change to Excalidraw's text editing. I am currently thinking of a setting to specify that the {number} is a hard break, not a soft break.

**Comment by zsviczian** [comment]
See https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.3.3

**Comment by kazdonkai** [comment]
Thank you for your prompt response. I am now able to wrap around.
I don't know if this is related, but every time I edit a transcluded text, “#TextElements” or “Link prefix” is added to it.

**Comment by kazdonkai** [comment]
![2021-09-06 15 27 02](https://user-images.githubusercontent.com/90127278/132172032-1fb0bd88-38c3-4e72-8b4a-ef0a4da85c34.jpg)

**Comment by zsviczian** [comment]
Can you share a video / screen capture of the issue? Based on the image and description, I am not able to reproduce it.

**Comment by kazdonkai** [comment]
The problem of extra characters being inserted seems to have been resolved.
(I think this is the problem that was pointed out in 'String "# Text Elements" added to Text Box in group #142′).

By the way, I would like to point out another problem with wrapping.
As you can see in the image, the wrapping does not work well when Japanese and alphanumeric characters are mixed together.
So, when counting the number of characters, could you please add a process to determine the number of bytes in the character code so that multi-byte characters can be supported?
This way, all languages with different byte counts will be supported.
If you do this, please add a note in the character count section of the settings that says "Enter the number of bytes.

**Comment by kazdonkai** [comment]
![Uploading 65E20037-284F-4A48-910C-D270CC0D8E76.jpeg…]()

**Comment by zsviczian** [comment]
I opened a new issue (#151) for the multi-byte character issue.
