### ISSUE TITLE
FR: Embedding external images into an Excalidraw drawing

### ISSUE THREAD

**Issue by Lita-CF** [zsviczian/obsidian-excalidraw-plugin#1365]
I wish there were a way to embed external images into the Excalidraw drawing.

I have many projects with numerous files in various formats, from bitmap and vector to spreadsheets and PDFs. Some of the projects are related to each other. At each stage of a project, I use multiple images either from the web or my hard drive.
I need a way to see all the images at a glance in order to analyze, compare, group, and regroup them. Additionally, I want to add quick notes, ideas, TODOs, key points, links to websites, files, folders, Obsidian notes, and more.

I use Obsidian notes with Dataview and Advanced Tables plugins. However, I spend too much time to format, search, open, close, re-open, re-format, etc. Obsidian notes with Dataview and Advanced Tables are very good for the already finished projects but not so good for WIP. I also tried Obsidian Canvas but it's still quite rudimentary and doesn't have the features I need. The best tool I have found for this purpose is Excalidraw.

My files and folders follow my personal naming convention (I use their URIs in my Obsidian notes). Renaming and moving all of them into my Obsidian vault is too difficult and time-consuming, not to mention that the majority of them cannot be edited in Obsidian and will never have links in any of my Obsidian notes.

**Comment by zsviczian** [comment]
I am including some of these features in 1.9.24.

**Comment by zsviczian** [comment]
closed with 1.9.24

**Comment by pipme** [comment]
Is there a way to embed external images without copying? BTW it seems the copied image is with low-resolution. 

Thanks!
