### ISSUE TITLE
BUG: Context menu item "Create New Drawing" does not embed drawing into note

### ISSUE THREAD

**Issue by paulwalk** [zsviczian/obsidian-excalidraw-plugin#1366]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64 23.0.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 16
		1: Calendar v1.5.10
		2: Meld Encrypt v2.3.2
		3: Tag Wrangler v0.6.1
		4: Iconize v2.4.2
		5: Dataview v0.5.61
		6: Map View v4.0.0
		7: Mermaid Tools v1.1.0
		8: Custom File Explorer sorting v1.9.2
		9: Markdown Table Editor v0.3.1
		10: Emoji Shortcodes v2.2.0
		11: Obsidian jTab v1.2.2
		12: Plaintext v0.3.0
		13: Hide Folders v1.2.0
		14: Periodic Notes v0.0.17
		15: Excalidraw v1.9.23
		16: Actions URI v1.3.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
When opening a regular note in Obsidian and attempting to create a new *embedded* drawing, the drawing is instead just created as a new drawing in same folder, but not embedded into the note. I am doing this by selecting the "Create New Drawing" in the note's "More Options" menu which is a context menu for this note - therefore I would expect the new drawing to be embedded into the note.

**To Reproduce**
1. Open any regular Obsidian note
2. Click the note's "More Options" menu
3. Select "Create New Drawing"

**Expected behavior**
I expect the new note to be embedded into the note (I have enabled the settings to embed the SVG version of the drawing automatically, but I have also reproduced this behaviour with this feature switched off)

**Comment by zsviczian** [comment]
I recommend using instead one of these command palette actions. You can assign a hotkey to your favorite one in Obsidian settings.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/a105e8b2-f71b-4cc1-ba04-d4f6a4912805)

**Comment by paulwalk** [comment]
OK - thanks - I will do that.

For the record, I do think the context menu for the note should trigger one of these - i.e. it should be an action related to the note.

In any case, thanks very much for this excellent plugin!

I will close this now - you have enough open issues to deal with ;-)
