### ISSUE TITLE
BUG: Keep getting Confirmation modal when I open Excalidraw files with embeds

### ISSUE THREAD

**Issue by nicolasmarc1** [zsviczian/obsidian-excalidraw-plugin#1370]
Hi. How do I stop getting this message when i open excalidraw. I keep clicking ok, but every time i reopen the drawing i sill get this message. Thanks

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/51007222/c495a9b3-9d39-4120-b2e7-f923604eacf2)

**Comment by zsviczian** [comment]
after opening the drawing press CTRL+S to save it. It seems you are opening a drawing that you created some time back, but you make no modifications to it, and as a result, the drawing does not get saved and the next time you open it you see the warning again.

**Comment by nicolasmarc1** [comment]
Thanks, it make sense!
