### ISSUE TITLE
BUG: The original equation was changed after duplicate->edit->undo

### ISSUE THREAD

**Issue by Bowen-0x00** [zsviczian/obsidian-excalidraw-plugin#1374]
**Your environment**
obsidian-excalidraw-plugin 1.9.23

**Describe the bug**
origin equation changed after duplicate->edit->undo

**To Reproduce**
1. duplicate equationA to equationB (ctrl+c、ctrl+v)
2. edit equationB
3. undo
4. equationA has been modified

**Expected behavior**
equationA remains unchanged.

**Reason**
The new fileId is assigned to equationA instead of equationB.
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/120435922/c37af53f-19db-4b09-a323-3972ec03ccd4)
`const newId = fileid();
        (scene.elements.filter((el:ExcalidrawImageElement)=>el.fileId === fileId)[0] as any).fileId = newId;
        dirty = true;`

The elements should be sorted by modified time.

**Comment by zsviczian** [comment]
Sorting by modification time is a good heuristic, but not a foolproof solution. Imagine the scenario when you duplicate an equation, next change the size of the original equation, and next change the equation of the copy...  modified timestamp is arbitrary depending on the last edit action, which can be many other things not just changing the equation.

I added sorting based on element.updated. This will work in most cases, but not always.
I will release in the next update.

**Comment by zsviczian** [comment]
partially solved in 1.9.14. Please reopen if the partial solution does not work as expected.
