### ISSUE TITLE
FR: slideshow export

### ISSUE THREAD

**Issue by luooofan** [zsviczian/obsidian-excalidraw-plugin#1378]
**Is your feature request related to a problem? Please describe.**
I believe Slideshow is currently suitable for real-time presentation scenarios, but sometimes I need to share my presentation with others before or after the presentation.
PS: The reading experience of directly exporting an Excalidraw file is noticeably different from that of a presentation.

**Describe the solution you'd like**
Export a pdf file or other file with a format similar to ppt

**Describe alternatives you've considered**

**Additional context**

**Comment by zsviczian** [comment]
This sounds very doable. 
If you are using frames to organize slides, then you can use the image references function to reference slides. If you are using a line to define the presentation path, then the situation is not this simple. https://youtu.be/yZQoJg2RCKI

This is something on my radar and I've already made some steps to implement something like this. My thinking was to implement image references similar to`![[image#slide=1]]`

**Comment by luooofan** [comment]
Thanks! That's cool!
I do use frames to organize slides, and the image references function provides me with a solution.

The image references similar to `![[image#slide=1]]` is a great idea, and I'm really looking forward to it.
