### ISSUE TITLE
FR: Add underscore option for YAML keys

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [zsviczian/obsidian-excalidraw-plugin#1381]
**Is your feature request related to a problem? Please describe.**
I'm using a preprocessor in JS (mdsvex) that reads .md files including frontmatter. The problem is that `excalidraw-plugin` is not valid JS so it causes builds to fail.

**Describe the solution you'd like**
There could be a setting that changes the dash to an underscore eg. `excalidraw_plugin`.

**Describe alternatives you've considered**
I just moved the excalidraw.md file out of the folder which works but is slightly annoying because I can't use the .svg auto export, I have to move the exported .svg to my assets folder. Not a huge issue but would be nicer if I could have the exacildraw.md file in the same folder!

**Additional context**
N/A

**Comment by zsviczian** [comment]
I recommend looking for a preprocessor to preprocess before mdsvex to replaceAll("-","_"). Making "-" vs. "_" an option is absolutely doable, but introduces risk throughout the code, as I did not design my code with this type of optionality from the get go.  I am sorry, but this feels like a very niche requirement that I am afraid I will not have the time to work on. I am really sorry.

**Comment by henrikvilhelmberglund** [comment]
> I recommend looking for a preprocessor to preprocess before mdsvex to replaceAll("-","_"). Making "-" vs. "_" an option is absolutely doable, but introduces risk throughout the code, as I did not design my code with this type of optionality from the get go. I am sorry, but this feels like a very niche requirement that I am afraid I will not have the time to work on. I am really sorry.

No problem, it's pretty niche and I already modified mdsvex to replace hyphens with underscores. It was more if it was a simple thing to add but if it's not it's fine, no need to apologize! 😊
