### ISSUE TITLE
Error report with latex formular without internet connection.

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#1383]
Migrated to the Obsidian issue log from here: https://github.com/excalidraw/excalidraw/issues/7150

This is a big problem with latex formular! It seems better to be loaded locally. Or stop reporting that problem below
"LaTeX support did not load. Using fallback solution. Try checking your network connection."
My excalidraw version is 1.9.2

-----

This seems Obsidian related. Please note that the Obsidian issue log is here: https://github.com/zsviczian/obsidian-excalidraw-plugin

As for the issue, try selecting a different library host in the plugin settings and restarting obsidian afterward.
![image](https://github.com/excalidraw/excalidraw/assets/14358394/13db46fc-85d5-4fb4-ad29-414298e2c3e9)

**Comment by zb5700** [comment]
Could you give me a choice to use local mathjax?  I have already download the mathjax 3.2.1. May be better if you add a configuration for me to choose a local path pointing to mathjax.  Because I need to work with excalidraw without internet connection.  Thankyou very much.

**Comment by zsviczian** [comment]
ok. I've included the MathJax package in 1.9.25 (I was very reluctant until now because it significantly increases package size)
