### ISSUE TITLE
BUG: After I select the title, iframe embedding md file does not update

### ISSUE THREAD

**Issue by hiforrest** [zsviczian/obsidian-excalidraw-plugin#1387]
**Your environment**

Windows 10
excalidraw 1.9.24
obsidian 1.4.15

**Describe the bug**

After I select the title, iframe embedding md file does not update

**To Reproduce**

I utilized an iframe to embed an md file and then replicated it.  
Initially, when I selected the title, the document did not update. 
Only after selecting it again was I able to see the changes, and it worked properly the second time.

**Expected behavior**

The content should be updated when I select the title for the first time.

**Screenshots**

https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/2953848/5d3131f5-193b-4f86-a93b-7e3437c26382

**Comment by zsviczian** [comment]
fixed in 1.9.25
