### ISSUE TITLE
FR: partial region embedding of excalidraw into obsidian

### ISSUE THREAD

**Issue by clehene** [zsviczian/obsidian-excalidraw-plugin#1389]
**Is your feature request related to a problem? Please describe.**
I use large boards and I currently have to copy paste a part of the board into a new board in order to embed. This causes duplication and it's hard to maintain.

**Describe the solution you'd like**
I'd like to emed a group or region from a larger excalidraw.

**Describe alternatives you've considered**
Embedding obsidian deep links 

**Additional context**

**Comment by zsviczian** [comment]
Is this what you are looking for?
https://youtu.be/yZQoJg2RCKI

**Comment by clehene** [comment]
Zsolt, you're awesome! 🤗

It was the first one that I was looking for. I was assuming it's possible and searched the docs and googled, but didn't find it. 
Is there a place where I can contribute the docs?

Than you!
