### ISSUE TITLE
FR: Launch ExcalidrawAutomate Scripts with JS directly

### ISSUE THREAD

**Issue by rlolingo** [zsviczian/obsidian-excalidraw-plugin#1392]
Hi Zsolt,

Is it possible to run my EA scripts with JS directly?
The code below seems what i need to do so.
`ExcalidrawAutomate.plugin.scriptEngine.loadScript("Excalidraw/Scripts/edit-image.md")`

But is didnt work, I also tried using loadScript with the  script's `TFile` Object instead of the path, but yielded no results.
I also see theres an `executeScript` function, but it seems like `loadScript` is the wrapper for that i should use.

Am I using this correctly? or is this possible in the first place?

Thanks in advance,
also, I hope i've asked these question in the right place.

**Comment by zsviczian** [comment]
At this time EA is designed as a scripting interface for Excalidraw. The objects that are passed to the script are initialized from the active Obsidian view (your drawing)

The ExcalidrawAutomate object is available on `window.ExcalidrawAutomate`. So for example, if you have a Templater script or a dataviewjs script you can invoke ExcalidrawAutomate functions using this object.

my practice is the following:
```js
ea = ExcalidrawAutomate; // or ea = window.ExcalidrawAutomate if you want to be more explicit
ea.reset(); //you can also use ea.clear() which does not reset style settings, only clears the elements in EA
ea.setView(); // you can supply it the view object or leave it empty to find the first Excalidraw window
// your code
```

This will not give you access to my utils object though... that is something I could publish on EA. If the above is not helpful, then please tell me more about your use case so  I can think about a solution.

Just in case this is not enabled... I suggest turning the suggested on:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/6a497f2b-b5a5-4f84-8aa2-1663d6ada329)
