### ISSUE TITLE
BUG: font-family has changed of other files after opening the Excalidraw

### ISSUE THREAD

**Issue by kin30528** [zsviczian/obsidian-excalidraw-plugin#1397]
hi, zsviczian. thank the plugin u made, but i found a bug, I tried to create a new vault, but the bug is still there!

### SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Blue Topaz v2023101401
	Snippets enabled: 30
	Restricted mode: off
	Plugins installed: 23
	Plugins enabled: 23
		1: Excalidraw v1.9.26
		2: Advanced Tables v0.19.1
		3: Footnote Shortcut v0.1.3
		4: Copy Image and URL context menu v1.5.1
		5: Creases v0.7.0
		6: Force note view mode v1.2.0
		7: Custom Frames v2.4.6
		8: Emoji Toolbar v0.4.1
		9: Find orphaned files and broken links v1.9.1
		10: Map View v4.0.0
		11: Tidy Footnotes v0.1.1
		12: Text Format v2.2.8
		13: Quick Explorer v0.2.8
		14: Paste image rename v1.6.1
		15: ObsidianTweaks v0.4.0
		16: Obsidian Memos v1.9.7
		17: MySnippets v1.2.3
		18: Media Extended v2.11.1
		19: Language Learner v0.2.5
		20: Image Toolkit v1.4.0
		21: Hover Editor v0.11.14
		22: Editing Toolbar v2.3.1
		23: Style Settings v1.0.7

### RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

## Describe the bug
After opening the Excalidraw file and going back to the general text file, the title font setting of the file has changed. 

## To Reproduce

1. open any general file, The font-family setting from css is displayed correctly.
`.inline-title {
font-family: Noto Sans TC Blod, Noto Sans Blod, Noto Sans SC Blod;
}`
<img width="594" alt="1" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/121107652/6af6bb55-72f5-4e83-a0fb-0ef890d56a8b">

2. open any excalidraw, and go back, the font-family has changed.
<img width="584" alt="2" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/121107652/2da4bb67-ae7c-48f6-bf9e-ef0690a30b22">

**Comment by zsviczian** [comment]
You will need to tell me more.
Does this affect excalidraw files or other note files?
I am not familiar with the ".inline-title" syntax. Is this something provided by the Style Settings plugin or is this a default Obsidian feature? WHere to you place ".inline-title" into the note, or in settings?

**Comment by kin30528** [comment]
> You will need to tell me more. Does this affect excalidraw files or other note files? I am not familiar with the ".inline-title" syntax. Is this something provided by the Style Settings plugin or is this a default Obsidian feature? WHere to you place ".inline-title" into the note, or in settings?

The ".inline-title" syntax only affects any non-excalidraw files, I use it to change the font family of titles in the red box. 
<img width="574" alt="1" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/121107652/f57d063e-38ec-4b27-9d7f-774245c9b0af">

My procedure is to open the appearance in the ob settings and then open the syntax from the css snippet.

<img width="815" alt="2" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/121107652/7041a8e8-1813-465d-8dff-90fe5cb33022">

**Comment by kin30528** [comment]
> You will need to tell me more. Does this affect excalidraw files or other note files? I am not familiar with the ".inline-title" syntax. Is this something provided by the Style Settings plugin or is this a default Obsidian feature? WHere to you place ".inline-title" into the note, or in settings?

Here is a test of the vault and font files. When the ".inline-title" syntax in the title of a non-excalidraw file fails after open the excalidraw file, you can only restart obsidian.
[test vault.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/13197382/test.vault.zip)

**Comment by kin30528** [comment]
I realized that my css was wrong, probably when ob restarted some css after opening excaslidraw that made me realize it. im sorry and thx u.

Fixed css
`.inline-title {
font-family: Noto Sans TC, Noto Sans, Noto Sans SC;
font-weight: 500;
}`
