### ISSUE TITLE
BUG: Missing Extra-Thin stroke width in version 1.9.26

### ISSUE THREAD

**Issue by wenjie198** [zsviczian/obsidian-excalidraw-plugin#1399]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Things v2.1.14
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 10
	Plugins enabled: 10
		1: Calendar v1.5.10
		2: Dataview v0.5.61
		3: Excalidraw v1.9.26
		4: Kanban v1.5.3
		5: Obsidian Git v2.22.0
		6: Periodic Notes v0.0.17
		7: Tasks v5.0.0
		8: Highlightr v1.2.2
		9: Style Settings v1.0.7
		10: Latex Suite v1.8.7

**Describe the bug**
Latest obsidian-excalidraw version is missing the extra-thin stroke width that previous versions had

**To Reproduce**
1. Update from previous versions to 1.9.26

**Expected behavior**
When selecting the stroke width, there should be a total of four options, "Extra thin", "thin", "Bold" and "Extra bold"

**Screenshots**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/46380489/72b00ef7-ed35-43d9-b92d-fe5f0553b3f3)
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/46380489/60657bcd-830d-444b-bdde-5ae64621c416)

**Comment by wenjie198** [comment]
First screenshot is from v1.9.25, second screenshot is from v1.9.26

**Comment by zsviczian** [comment]
Thanks. Fixed. there was a refactoring of stroke widths on Excalidraw.com... which accidentally overrode this plugin feature.
