### ISSUE TITLE
Can the option to support Chinese handwriting fonts be supported? 

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#14]
If so that would be perfect!
![image](https://user-images.githubusercontent.com/29135984/115692610-b9ef8680-a391-11eb-82e4-b37baa3d4c13.png)
![image](https://user-images.githubusercontent.com/29135984/115692745-d5f32800-a391-11eb-914e-4930ba8f2140.png)
like this[方正徐静蕾行书 简字体免费下载和在线预览-字体天下](https://www.fonts.net.cn/font-34880279351.html)

**Comment by zsviczian** [comment]
I raised the question with the Excalidraw team. You may need to open a ticket with Excalidraw for this here: https://github.com/excalidraw/excalidraw/issues

**Comment by zsviczian** [comment]
@zhl111 What font do you have on your screenshot? Can you send me a link to the font?

**Comment by zhl111** [comment]
Many Chinese fonts need to be downloaded and installed, and I've searched long and hard for one like the one shown in your link. I don't know anything about programming, do I need to provide an API for the fonts? I'll post a link below with a font I like.[汉仪新蒂永乐大典体 - Yong'le Encyclopedia Calligraphy](https://sentyfont.com/yongle.htm)

**Comment by zsviczian** [comment]
I asked, but the Excalidraw team does not have Chinese characters on their roadmap as of now.

However I may be able to work with this... no promises, but I have an idea for a hack.
[https://sentyfont.com/index_htm_files/xr_fonts.css](https://sentyfont.com/index_htm_files/xr_fonts.css)

I did a test... the end result does not seem perfect. Some characters seem to be missing...
![image](https://user-images.githubusercontent.com/14358394/115822459-de387b00-a404-11eb-8a12-f7114bb71057.png)

let me know what you think of the test result

**Comment by zhl111** [comment]
These fonts are the most complete free and commercially available fonts in 2020, the commercial free fonts included here can be found with clear licensing sources and can be used with confidence (https://github.com/wordshub/free-font)

Sorry, I don't know anything about programming, I can ask for help on the obsidian Chinese channel

**Comment by dreamkidd** [comment]
> @zhl111 What font do you have on your screenshot? Can you send me a link to the font?
> 
> Sorry... I see you included the link...
> 
> I need a font I can include on a link like this
> 
> ```
> 
> <style>
> 
> @import url('https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@500&display=swap');
> 
> </style>
> 
> ```
> 
> [https://fonts.google.com/specimen/Noto+Serif+TC?subset=chinese-traditional](https://fonts.google.com/specimen/Noto+Serif+TC?subset=chinese-traditional)

can u support `font-face` which import font from local `.ttf` file？

**Comment by bagameow** [comment]
> I asked, but the Excalidraw team does not have Chinese characters on their roadmap as of now.
> 
> However I may be able to work with this... no promises, but I have an idea for a hack.
> https://sentyfont.com/index_htm_files/xr_fonts.css
> 
> I did a test... the end result does not seem perfect. Some characters seem to be missing...
> ![image](https://user-images.githubusercontent.com/14358394/115822459-de387b00-a404-11eb-8a12-f7114bb71057.png)
> 
> let me know what you think of the test result.
> 
> unpack the zip and you can also test sample.svg.
> 
> [sample.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/6362977/sample.zip)

how to test the sample.svg?

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/115950781-d7e2f580-a50f-11eb-86ad-87995c77fb6b.png)

Randomly get a font, the display seems to be normal

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/115951294-94d65180-a512-11eb-87d1-46677e52a312.png)
![image](https://user-images.githubusercontent.com/29135984/115951305-9dc72300-a512-11eb-8d79-86334557d5f0.png)I have this font installed on my computer and I removed the middle part and it works fine. I don't know if it is a web font you need

**Comment by dreamkidd** [comment]
https://fonts.google.com/specimen/Liu+Jian+Mao+Cao?preview.text=%E6%89%8B%E5%86%99&preview.text_type=custom&subset=chinese-simplified&preview.size=31#standard-styles

what about this font？

![image](https://user-images.githubusercontent.com/11213228/116645351-3abd0c80-a9a8-11eb-98d1-bb40657a8425.png)

**Comment by zhl111** [comment]
Cursive script, a little difficult to identify, I think

**Comment by zsviczian** [comment]
Ok. I'll see if I can build a feature where you can specify a font of your choice to override on of the default excalidraw fonts.

**Comment by dreamkidd** [comment]
> Cursive script, a little difficult to identify, I think

https://fonts.google.com/?preview.text=%E6%89%8B%E5%86%99&preview.text_type=custom&subset=chinese-simplified

u could choose here

**Comment by dreamkidd** [comment]
> Ok. I'll see if I can build a feature where you can specify a font of your choice to override on of the default excalidraw fonts.

i don not see any api in `@excalidraw/excalidraw` to change font ,  another way to hack this is fork from `excalidraw`  and change source code to build ， i don not think this is  good idea

**Comment by zsviczian** [comment]
For sure I wouldn't want to fork Excalidraw, I want to benefit from future releases. My idea is to hack the font in the SVG output and to override the Excalidraw css and use one of the fonts for the custom font.

**Comment by wongFanx** [comment]
> Ok. I'll see if I can build a feature where you can specify a font of your choice to override on of the default excalidraw fonts.

If this is true, it would be great!

**Comment by wongFanx** [comment]
![image](https://user-images.githubusercontent.com/14831158/117344933-8f94e180-aed8-11eb-99c4-dce6d7902a39.png)
https://board.oktangle.com/
This is an excalidraw version that supports Chinese handwritten fonts.

**Comment by wongFanx** [comment]
> Thanks! I'll contact the developers and ask if they are ok to share their solution.

There are some related links.
https://blog.magicdu.cn/744.html
https://github.com/Ethereal-Coder/excalidraw-zh_CN

**Comment by zhl111** [comment]
Is there any hope?

**Comment by jk110** [comment]
[http://cdn.ghost-jack.top/chinese.ttf](url) Is this Chinese handwriting OK?

**Comment by jk110** [comment]
Can you add another Chinese men thanks
![微信截图_20211123175513](https://user-images.githubusercontent.com/56330712/143003986-754fdec6-9675-42c3-96e4-e24a87a325c5.png)

**Comment by zsviczian** [comment]
This is not yet a full solution, but I hope it is a step in the right direction: https://youtu.be/XYLOLrriZC4

**Comment by tswwe** [comment]
@jk110 
Hi. I also met this problem, and I've made a tiny tool to provide another workaround. You can give it a try if needed: [Excalipatch](https://github.com/tswwe/excalipatch). Anyway, it's just a workaround - Use it at your own risk.
![preview](https://github.com/tswwe/excalipatch/blob/master/assets/preview.jpg?raw=true)

**Comment by jk110** [comment]
@tswwe 
感谢大佬👍👍👍

**Comment by zsviczian** [comment]
> @jk110 Hi. I also met this problem, and I've made a tiny tool to provide another workaround. You can give it a try if needed: [Excalipatch](https://github.com/tswwe/excalipatch). Anyway, it's just a workaround - Use it at your own risk. ![preview](https://github.com/tswwe/excalipatch/blob/master/assets/preview.jpg?raw=true)

This is great!
Instead of a patch, would you be open to contribute with a small pull request to the Excalidraw [for-obsidian](https://github.com/zsviczian/excalidraw/tree/for-obsidian) package that would add an API call to load of a custom font + add a generic 4th font button?

I would then implement a small change to [obsidian-excalidraw-plugin](https://github.com/zsviczian/obsidian-excalidraw-plugin) that extends plugin settings with an option to specify a custom font file in the vault, and loads that font as the 4th font using the API.

This would be a more generic solution, addressing the needs of a broader user community.

**Comment by zhl111** [comment]
Wow, this is fantastic!

**Comment by tswwe** [comment]
@zsviczian Hi, thanks for your compliment. It's my honor to contribute to the awesome obsidian-excalidraw-plugin directly. I will try that though I'm a new hand.

**Comment by zsviczian** [comment]
I will release 1.5.17 soon, that version will solve this issue. BIG THANKS TO @tswwe !!!
