### ISSUE TITLE
BUG: Multiline LaTeX expressions don't persist

### ISSUE THREAD

**Issue by feuerente** [zsviczian/obsidian-excalidraw-plugin#1403]
**Your environment**
Replicated in sandbox vault.

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: #1 SMP PREEMPT_DYNAMIC Thu, 19 Oct 2023 22:52:14 +0000 6.5.8-arch1-1
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v1.9.27

**Describe the bug**
When entering a LaTeX expression spanning multiple lines it is correctly rendered.
But after saving and reopening it is not rendered anymore and the reference in markdown is gone.
Single line LaTeX expression work fine.

**To Reproduce**
1. Enter a multiline LaTeX expression -> rendered correctly
2. Close & open again -> Not render

Example of multiline LaTex expression in markdown mode.
```
40919e9c95b988d963c913599c65db9539905ed7: $$\text{two line}
\text{ LaTeX expression} 123$$
```

**Comment by zsviczian** [comment]
resolved in 1.9.28 - will release it later this WE
