### ISSUE TITLE
FR: Configurable time to erase ink of laser pointer

### ISSUE THREAD

**Issue by karuturi** [zsviczian/obsidian-excalidraw-plugin#1408]
**Is your feature request related to a problem? Please describe.**
Laser pointer is a great edition. It enabled to quickly highlight things. But, it disappears quite fast and is difficult to get focus to a point in the diagram. 

**Describe the solution you'd like**
If it can stay a bit longer(or through a configuration) that would be helpful. The way PPT or some other tools handle is, the writing stays as long as you are continuing to write(don't know how they detect that) once you stop, it waits for few seconds and then disappears. 

**Describe alternatives you've considered**
PPT has laser pointer in presentation mode which stays longer.

**Additional context**
This happens when using laser pointer in regular mode and also while presenting using slideshow script.

**Comment by zsviczian** [comment]
Implemented in 1.9.28

**Comment by karuturi** [comment]
Wow, that was quite fast. Thank you so much @zsviczian. 
I think the behaviour currently is it waits for the configured seconds and then gets erased. 
Is it possible for it to stay as long as I am writing? The timeout should be applicable after I stopped writing. 
I was checking on how we this can be achieved. If there are any pointers(very little knowledge of UI), let me know. Will be happy to do this myself.

**Comment by karuturi** [comment]
This behaviour I think is coming from excalidraw. I opened a request there https://github.com/excalidraw/excalidraw/issues/7320
