### ISSUE TITLE
BUG: Excalidraw Folder with special character in name prevents embedding images from this folder

### ISSUE THREAD

**Issue by derycck** [zsviczian/obsidian-excalidraw-plugin#1416]
**Your environment**
```
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.1.11
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 5
		1: LanguageTool Integration v0.3.1
		2: Editor Syntax Highlight v0.1.3
		3: Minimal Theme Settings v6.1.0
		4: Execute Code v1.5.0
		5: Excalidraw v1.9.26

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Describe the bug**
"Excalidraw Folder" with a name containing a special character results in an error when including images that are within that folder.

**To Reproduce**
1. Excalidraw configured for the "Excalidraw Folder" to be a folder called "#Draw"
2. Added images in the "#Draw' folder
3. From a drawing, use function "Insert ANY file from your vault" to embed image
4. Select a image that is in the "#Draw" folder

The error appears that the image could be found.
When editing the "#Draw" folder by removing the special character and changing the Excalidraw configuration to indicate the new folder name, adding images from the "Excalidraw folder" will work again.

**Expected behavior**

1. When trying to include images from folders within the Vault, the operation should be successful regardless of whether the folder name contains a "#". Or:
2. When configuring the "Excalidraw Folder" option in the Excalidraw settings, an alert should appear stating that the folder name cannot have "#" or "^" or any other conflicting character.

**Comment by zsviczian** [comment]
It is generally not recommended to have these characters in folder and file names:
https://www.mtu.edu/umc/services/websites/writing/characters-avoid/

I would imagine Obsidian also gets confused with these filenames, because  # has a special purpose, so does ^
see here for details: https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note
