### ISSUE TITLE
String "# Text Elements" added to Text Box in group

### ISSUE THREAD

**Issue by adxsoft** [zsviczian/obsidian-excalidraw-plugin#142]
**Describe the bug**
On opening an existing excalidraw drawing a text field in a group has the phrase "# Text Elements" line added to it
**To Reproduce**
- Open an existing note which embeds an excalidraw drawing that has text fields in a group
- The drawing has been updated with "# Text Elements"

**Expected behavior**
Do not expect any data to be added to the text box other than my changes
**Screenshots**
before and after screenshots attached

**Desktop (please complete the following information):**
 - OS: Mac OSX High Sierra
 
BEFORE DOUBLE CLICKING THE DRAWING
![Before double clicking the drawing](https://user-images.githubusercontent.com/24862237/132978501-b0678bbd-cddd-4c11-af6d-769edbe844ad.png)

AFTER DRAWING OPENING
![After opening the drawing](https://user-images.githubusercontent.com/24862237/132978499-7656780a-51f7-4c42-8c5a-f025bb74b3aa.png)

**Comment by zsviczian** [comment]
I am sorry for that, however, I've been trying now for minutes, but I am unable to reproduce the error. 
Would you mind sending me an example file (before the # Text Elements is added to it)?

**Comment by zsviczian** [comment]
As a workaround, try placing a space in front of the # mark. i.e. instead of "# WIKI area" write " # WIKI area" (note the leading space). I would still like to have a sample file with the issue.

**Comment by zsviczian** [comment]
@adxsoft Can you check if the issue still persists after installing v1.2.13?

**Comment by adxsoft** [comment]
Sorry for late reply 

Here's the file I have the problem with

[My Obsidian Structure.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/7273062/My.Obsidian.Structure.excalidraw.md)

I have installed 1.2.16 problem but the problem still persists

To reproduce the problem do the following

1. Double click on the label containing _# WIKI area_
2. Double lick on the same label again to edit its text
3. Do a force save
4. _# Text Elements_ is added to the label

Hope this helps track down the problem :-)

**Comment by zsviczian** [comment]
Thanks. This will indeed help find the bug.

I cleaned up your file, now it works...
Before cleanup
[image: image.png]
After cleanup:
[image: image.png]

**Comment by zsviczian** [comment]
Solved in [1.3.17](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.3.17)
