### ISSUE TITLE
FR: Please add possibility to re-use opened documents when link is clicked

### ISSUE THREAD

**Issue by kosirm** [zsviczian/obsidian-excalidraw-plugin#1420]
I'm always frustrated when I click on the link (for example on the Excalidraw page) and the link opens in a new tab or in the same tab, even if I have this document already opened in a pane beside the Excalidraw image. Fortunately, there is a perfect plugin for this [obsidian-no-dupe-leaves](https://github.com/scambier/obsidian-no-dupe-leaves), which works fine for documents, but on Excalidraw it doesn't work.

Could you please make possible to use [obsidian-no-dupe-leaves](https://github.com/scambier/obsidian-no-dupe-leaves) with Excalidraw? Excalibrain has nice functionality to reuse adjacent pane to open links(documents) there. If only something like that would be possible in Excalidraw. If there is another way to open internal links in Excalidraw to re-use already opened documents, please let me know.

I don't have any alternative.

Thank you!

**Comment by kosirm** [comment]
I've found this in Excalidraw api: /** * Open a file in a new workspaceleaf or reuse an existing adjacent leaf depending on Excalidraw Plugin Settings * @param file * @returns */ openFileInNewOrAdjacentLeaf(file: TFile): WorkspaceLeaf;
There is also setting in Excalidraw: Links, Transclusions and TODOs > Reuse Adjacent Pane, but in my case it doesn't work. Maybe it is a bug.

**Comment by zsviczian** [comment]
Please review modifier key combinations in the plugin readme... if you still need help please reopen this issue. ![](https://raw.githubusercontent.com/zsviczian/obsidian-excalidraw-plugin/master/images/excalidraw-modifiers.png)

**Comment by kosirm** [comment]
Perfect, thank you!
