### ISSUE TITLE
BUG: Reuse Adjacent Pane not working

### ISSUE THREAD

**Issue by kosirm** [zsviczian/obsidian-excalidraw-plugin#1421]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Atom v0.0.0
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 6
		1: Excalidraw v1.9.28
		2: Dataview v0.5.64
		3: ExcaliBrain v0.2.11
		4: Copy Block Link v1.0.4
		5: Diagrams.net v1.0.4
		6: Merge Notes v0.0.6

**Describe the bug**
Reuse Adjacent Pane is **enabled** in Settings > Links, Transclusions and TODOs, but all links are opened either in new tab (Click on link) or same tab (CTRL+SHIFT+Click on link)

**To Reproduce**
1. Open Excalidraw image
2. Create Link to Note
3. Open Note in adjacent pane
4. CTRL+SHIFT+Click on link
5. Note is opened in new tab, even if it is already opened in adjacent tab

**Expected behavior**
I expect note to be opened in adjacent pane

**Screenshots**
![Screenshot 2023-11-06 190152](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/54502/53ae8e36-9be6-4a9a-a791-97e569eedc1f)
![Screenshot 2023-11-06 190528](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/54502/42142636-ced9-4bf0-b245-d961d779d906)

**Comment by zsviczian** [comment]
It is working - only the description is incorrect in settings. I updated modifier key combinations and forgot to update the text in settings.

**Comment by zsviczian** [comment]
I updated the text in Readme. Will be updated when I release the next update.

**Comment by kosirm** [comment]
Thank you so much!!!

**Comment by kosirm** [comment]
It's perfect!!! I'm happy camper again :) Thank you so much for sharing this amazing project!
