### ISSUE TITLE
Documentation on Attributes and functions overview is not formatted

### ISSUE THREAD

**Issue by kosirm** [zsviczian/obsidian-excalidraw-plugin#1423]
I'm trying to understand Excalidraw script engine, just reading through documentation and found this [page ](https://zsviczian.github.io/obsidian-excalidraw-plugin/API/attributes_functions_overview.html)which looks interesting, but unfortunately it is just a huge blob of text. Could you please pretty print / format code on this page: https://zsviczian.github.io/obsidian-excalidraw-plugin/API/attributes_functions_overview.html
Thank you in advance if you can do this!

**Comment by zsviczian** [comment]
fixed
