### ISSUE TITLE
BUG: Template {{date}} format don't work

### ISSUE THREAD

**Issue by jaanonim** [zsviczian/obsidian-excalidraw-plugin#1431]
**Describe the bug**
When creating drawing from template `{{date}}` and `{{time}}` values are not replaceced by corrcet values

**To Reproduce**
1. Create and template file for excalidraw drawing.
2. Add to templete markdown line:
```
Created: {{time}} {{date}}
```
3. Create drawing form template.

**Expected behavior**
In created drawing added line shoudl be for eg. 
```
Created: 11:11 2023-01-01
```

SYSTEM INFO:
```
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 6.2.0-36-generic
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 8
		1: Obsidian Git v2.22.0
		2: Dataview v0.5.64
		3: Bible Reference v2.3.4
		4: YTranscript v0.9.1
		5: Auto Note Mover v1.2.0
		6: File Creation and Last Modified Timestamps in Status Bar v1.2.0
		7: YouVersion Linker v1.0.3
		8: Excalidraw v1.9.28
```

**Comment by zsviczian** [comment]
I think I address this in https://youtu.be/jgUpYznHP9A
Please watch and let me know if you still have questions

**Comment by jaanonim** [comment]
Thank you for your answer. It helped. I was hoping for support of templates as is in the [templates core plugin](https://help.obsidian.md/Plugins/Templates), but I see that's irrelevant (I assumed it was due to the template file settings). For me it would be useful to create a template using the action button on the ribbon, which is not possible with the [Templater](https://github.com/SilentVoid13/Templater) plugin (and for this simple action I would have to install another plugin). I'm opening [FR](#) for this, but I will understand if it's out of scope.
