### ISSUE TITLE
BUG: Help and shortcuts show blank black boxes on dark and light themes

### ISSUE THREAD

**Issue by Hexara7777** [zsviczian/obsidian-excalidraw-plugin#1437]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.

**Describe the bug**
Help and shortcuts show blank black boxes on dark and light themes
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/130001839/102a26fa-b358-415c-a657-6febb88acbcd)
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/130001839/c73e888c-e02d-4657-8852-59325cda92d0)

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by zsviczian** [comment]
thanks solved in 2.0.1
