### ISSUE TITLE
BUG: Cannot copy area of selection of more than 1 element from pdf

### ISSUE THREAD

**Issue by PCesteban** [zsviczian/obsidian-excalidraw-plugin#1438]
**Your environment**
```
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Home Single Language 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal v6.1.0
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 5
		1: Minimal Theme Settings v7.3.0
		2: Advanced Tables v0.19.1
		3: Excalidraw v1.9.28
		4: LanguageTool Integration v0.3.4
		5: Discord Rich Presence v1.5.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Describe the bug**
When selecting more than 1 element even if they are grouped the 'copy markdown link for selected element to clipboard' copies the area of just 1 of the grouped elements. 

**To Reproduce**
1. Insert a PDF to excalidraw
2. Make a few annotations on the PDF
3. Select all the annotations (If grouped the behavior is the same)
4. use 'copy markdown link for selected element to clipboard' and select area
5. Paste it in an obsidian note.
6. You will notice it will paste the area of just 1 of the selected elements.

**Expected behavior**
Paste the area of all selected elements or the area of the grouped elements.

**Comment by zsviczian** [comment]
Overall, I don't recommend area references with many imported PDF pages because of performance implications...
You can add an transparent rectangle and group it with the other objects, the area link selects the area of the largest element in the group
