### ISSUE TITLE
BUG: Embedded markdown has lost css

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1443]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/eda8a60f-481a-4abf-97d6-11f1e77fdbc7)
On the left is my normal markdown display, and on the right is the result embedded in excalidraw. Hopefully, the two display exactly the same result

**Comment by zsviczian** [comment]
please include the debug info
Command Palette: Show Debug Info

**Comment by jiajiala** [comment]
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 21
	Restricted mode: off
	Plugins installed: 106
	Plugins enabled: 59
		1: Bartender v0.5.9
		2: Better Command Palette v0.17.1
		3: Plugin Manager v0.1.5
		4: Advanced Tables v0.19.1
		5: Attachment Manager v1.2.2
		6: Better Export PDF v1.0.5
		7: Better Search Views v0.2.2
		8: Clear Unused Images v1.1.0
		9: Command Alias v2.0.1
		10: Commander v0.5.1
		11: Copy Block Link v1.0.4
		12: Creases v0.7.0
		13: Custom list character v1.0.1
		14: Customizable Menu v2.2.0
		15: Dataview v0.5.64
		16: Easy Typing v5.1.10
		17: Editing Toolbar v2.3.1
		18: Editor Syntax Highlight v0.1.3
		19: Excel to Markdown Table v0.4.0
		20: File Color v1.0.3
		21: Find orphaned files and broken links v1.9.1
		22: Folder notes v1.6.11
		23: Front Matter Title v3.7.1
		24: Global Search and Replace v0.3.0
		25: Heading Shifter v1.5.1
		26: Image Toolkit v1.4.0
		27: Linter v1.20.1
		28: List Callouts v1.2.0
		29: Mousewheel Image zoom v1.0.19
		30: Note Refactor v1.8.2
		31: Obsidian42 - Strange New Worlds (SNW) v1.2.3
		32: Outliner v4.8.0
		33: Paste URL into selection v1.7.0
		34: Persistent Links v0.2.0
		35: Query Control v0.6.0
		36: Quick Switcher++ v3.3.8
		37: Quiet Outline v0.3.17
		38: Recent Files v1.3.8
		39: Reveal Active File Button v2.0.3
		40: Short links v1.1.5
		41: Supercharged Links v0.11.1
		42: Typing Transformer v0.4.0
		43: Various Complements v9.1.0
		44: Word Splitting for Simplified Chinese in Edit Mode and Vim Mode v1.10.0
		45: Zoom v1.1.2
		46: 增强编辑 v0.6.0
		47: Reading comments v1.0.27
		48: Style Settings v1.0.7
		49: Excalidraw v2.0.3
		50: Mononote v1.0.0
		51: Hover Editor v0.11.15
		52: Open In New Tab v1.0.9
		53: Close Similar Tabs v2.1.0
		54: Plugin Proxy v0.0.1
		55: Fullscreen mode plugin v0.1.2
		56: Breadcrumbs v3.6.4
		57: Floating Search v3.4.5
		58: Advanced URI v1.38.1
		59: Plugin Update Tracker v1.5.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
