### ISSUE TITLE
BUG: Excalidraw Plugin v2.0.2 in Obsidian v1.5.0 - Mermaid Diagram Rendering

### ISSUE THREAD

**Issue by Petesuchos** [zsviczian/obsidian-excalidraw-plugin#1450]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.0
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112 22.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: AnuPpuccin v1.4.4
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 24
	Plugins enabled: 19
		1: Calendar v1.5.10
		2: Outliner v4.8.0
		3: Tasks v5.1.0
		4: Templater v1.17.0
		5: Dataview v0.5.64
		6: Projects v1.17.0
		7: Advanced Tables v0.19.1
		8: Copilot v2.4.4
		9: Excalidraw v2.0.2
		10: ExcaliBrain v0.2.11
		11: Style Settings v1.0.7
		12: Code Block Enhancer v1.0.5
		13: Hider v1.3.1
		14: Editor Syntax Highlight v0.1.3
		15: Pandoc Plugin v0.4.1
		16: Auto Note Mover v1.2.0
		17: Paste image rename v1.6.1
		18: Linter v1.20.1
		19: Spaced Repetition v1.10.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
The Excalidraw plugin (v2.0.2) in Obsidian (v1.5.0) fails to render Mermaid diagrams, displaying a parse error: "Parse error on line 1: %%{init: {"flowchart ^ Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'NODE_STRING'". This occurs with any diagram, including default example.

**To Reproduce**
1. Open Obsidian (v1.5.0) with the Excalidraw plugin (v2.0.2) installed.
2. Attempt to create or view a Mermaid diagram within Excalidraw.
3. Observe the parse error as mentioned above.

**Expected behavior**
The plugin should render Mermaid diagrams without any errors.

**Comment by zsviczian** [comment]
I am able to reproduce

**Comment by zsviczian** [comment]
found the root cause, will release a fix later today

**Comment by zsviczian** [comment]
Releasing the solution in a few mins...
