### ISSUE TITLE
BUG: Wrong color in dark mode

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1459]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/7a53d207-67ed-48ad-a89b-85c4ea807f68)
In this image, the color of my image has changed from yellow to orange-red in dark night mode

The color change is a BUG and shouldn't change the color of my picture, it's weird
Color accuracy is very important to me and I want to be able to display colors correctly in black mode

**Comment by zsviczian** [comment]
There is not much I can do about this. This is how the excalidraw package treats color. I personally do not use dark mode, but use a color palette that looks nice when dark. You might find what you are looking for here:
- https://youtu.be/fypDth_-8q0
- https://youtu.be/diBT5iaoAYo

**Comment by zsviczian** [comment]
Agree.  This is not ideal. There are different uses for a virtual whiteboard, some require color accuracy others do not. If color accuracy is important to you, then I recommend sticking to light mode but using a dark color palette. See the referenced videos above on how-to.
