### ISSUE TITLE
FR: want to hide the file name when link the block

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1467]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/312ec284-4fac-43a3-aff0-71cce93058d4)
As shown in the figure,I want to display only "AA" and hide "Test"

**Comment by zsviczian** [comment]
`[[Test#AA|AA]]`

**Comment by jiajiala** [comment]
This can be a temporary fix, but once I change "AA" to "BB", the link doesn't change

**Comment by jiajiala** [comment]
> `[[Test#AA|AA]]`
This can be a temporary fix, but once I change "AA" to "BB", the link doesn't change
