### ISSUE TITLE
FR: Custom font size

### ISSUE THREAD

**Issue by Deus333** [zsviczian/obsidian-excalidraw-plugin#1474]
Being able to customize font size by entering a scale size number. I think it is one of the very important missing features in this great plug-in and I'm sure many people have this problem for example, someone described it in this feature request too. https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1350

**Comment by zsviczian** [comment]
You mean editing the font size of a text element? or an embedded markdown page?

**Comment by Deus333** [comment]
text element 

![Artboard 1](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/116972828/0b4743d2-721f-40dd-9d9a-ad3c72fe73c4)
I have been contemplating a solution similar to this. I've even considered implementing a starring mechanism to bookmark sizes that we frequently use. I believe these features would solve the challenges encountered with highly zoomed-in pages. In such scenarios, it is necessary to write with a small font size. However, the smallest font size available in Excalidraw is already quite large for zoomed-in situations. Consequently, one has to zoom out, resize the text element, and then zoom back in. This process can be tedious.

**Comment by Deus333** [comment]
It can also be something like adding custom pen system

**Comment by zsviczian** [comment]
A script is more likely - I don't want to change the UI too much else it makes it impossible to follow all the great developments on excalidraw.com in Obsidian.

**Comment by Deus333** [comment]
Hi, this addressed the issue, but I still think there's a problem with controlling the font size. Being able to control the font size allows for a more detailed classification of information.

**Comment by pbhopeful** [comment]
Kinda funny that they fixed a problem that was completely different than the one you asked about.
