### ISSUE TITLE
BUG: Internal link break

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1477]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/2c5335ff-3558-44b1-9220-0d36d517e838)
When I use this to create A link that points to "A"

Then I cut "A" into another EXcalidraw file, and all the links to "A" broke

There is also a plug-in, Persisten Links, that deals with keeping the link unbroken after the node is moved

It's also not helping me with broken links in EXcalidraw at the moment

**Comment by zsviczian** [comment]
I am unable to reproduce the issue. BTW - Obsidian by default keeps links intact. I don't know why you'd need a plugin for that. What happens if you uninstall "Persistent Links", restart Obsidian, and use the default Obsidian feature?

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/993ac6d9-6cd8-442b-9c66-d01e6bd94f61)

https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/2ad629f5-e719-4cd9-992b-b94839024c94

**Comment by jiajiala** [comment]
> I am unable to reproduce the issue. BTW - Obsidian by default keeps links intact. I don't know why you'd need a plugin for that. What happens if you uninstall "Persistent Links", restart Obsidian, and use the default Obsidian feature?我无法重现该问题。顺便说一句 - 默认情况下，黑曜石保持链接完好无损。我不知道为什么你需要一个插件。如果卸载“持久链接”，重新启动黑曜石，并使用默认的黑曜石功能，会发生什么情况？
> 
> ![image](https://private-user-images.githubusercontent.com/14358394/287505022-993ac6d9-6cd8-442b-9c66-d01e6bd94f61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjg4NzYsIm5iZiI6MTcwMTgyODU3NiwicGF0aCI6Ii8xNDM1ODM5NC8yODc1MDUwMjItOTkzYWM2ZDktNmNkOC00NDJiLTljNjYtZDAxZTZiZDk0ZjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAyMDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNDVmYWQ3NGZmNTAyNGJhODNjYjNlNjFlN2Y4MTQ5MDVhMjE0YzExYmRjYTg2ZmU5NzkwNDg5Y2Q4NjkwODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._y7iaieUgn2Ul_n6K7-dwWio7xcUGC7A30xV6tfwC8c)
> 
>  demo.mp4 演示.mp4

This bug prevents the flow of content between artboards

**Comment by jiajiala** [comment]
@zsviczian 
This bug prevents the flow of content between artboards
Links that break are unsettling

**Comment by jiajiala** [comment]
@zsviczian
There is no way that a linked content can be moved to other files, but the link will not be lost, and the linked content can still be found through the link

**Comment by zsviczian** [comment]
I don't understand. How are you moving stuff? Links are maintained. Set
relative Links in Obsidian settings

**Comment by jiajiala** [comment]
@zsviczian
![Honeycam 2023-12-03 21-17-29](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/8a0b88c0-2c86-4779-842a-c9b89038552f)
I set a link in file c2, which should be linked to aaaa, but in my work I found that aaaa should belong to another file, I cut aaaa into another file, and when I opened c2 again one day, I found that I could not find aaaa through the link.
