### ISSUE TITLE
BUG: Uncaught Promise Cannot Read Properties of Null

### ISSUE THREAD

**Issue by devinat1** [zsviczian/obsidian-excalidraw-plugin#1478]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.23550
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.3.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 39
	Plugins enabled: 32
		1: Admonition v10.1.1
		2: Advanced Tables v0.19.1
		3: Calendar v1.5.10
		4: Custom Frames v2.4.6
		5: Dataview v0.5.64
		6: Dice Roller v10.4.0
		7: Editor Syntax Highlight v0.1.3
		8: Excalidraw v2.0.4
		9: Google Photos v1.6.5
		10: Hider v1.3.1
		11: Homepage v3.6.0
		12: Image Toolkit v1.4.1
		13: Janitor v1.0.7
		14: LanguageTool Integration v0.3.4
		15: Linter v1.20.1
		16: Longform v2.0.4
		17: Minimal Theme Settings v7.3.0
		18: Mousewheel Image zoom v1.0.19
		19: Note Refactor v1.8.2
		20: Obsidian_to_Anki v3.4.2
		21: Pandoc Plugin v0.4.1
		22: Paste URL into selection v1.7.0
		23: Plugin Update Tracker v1.5.2
		24: Quick Switcher++ v3.3.9
		25: QuickAdd v1.6.0
		26: Readwise Official v2.0.1
		27: Recent Files v1.3.8
		28: Settings Search v1.3.10
		29: Templater v1.18.1
		30: Text Extractor v0.4.8
		31: Todoist Plugin v1.11.1
		32: Toggl Track v0.11.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/15788108/fbce77ed-c48d-4d95-beab-aa1fc89e0e73)

**To Reproduce**
Happens any time a drawing is created, edited, etc. (not sure exactly how to reproduce.

**Comment by zsviczian** [comment]
How do you create drawings?

**Comment by zsviczian** [comment]
Check 2.0.7 did it solve your issue?

**Comment by devinat1** [comment]
It seems to be ok for now, will use for a few days to double check.

**Comment by zsviczian** [comment]
solved in 2.0.7 
please reopen if it pops up again

**Comment by devinat1** [comment]
Issue still persists as of Excalidraw 2.0.10 I am getting  sometimes upon opening the Excalidraw document for the first time, and an error uncaught illegal access sometimes when closing the respective document.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/15788108/65cd4aab-a31c-4d5e-9a4e-fd4802675307)
