### ISSUE TITLE
How to use Dataview to automate the creation of drawings?

### ISSUE THREAD

**Issue by wenlzhang** [zsviczian/obsidian-excalidraw-plugin#148]
As can be seen from the screenshot below, I have the example code from the repository. However, when I switch the Dataview code into Preview mode, it shows as an empty page. Am I missing anything here?

I am using Excalidraw v1.3.10, Dataview v0.4.10 and Obsidian v0.12.16.

![Screenshot 2021-09-21 at 14 40 53](https://user-images.githubusercontent.com/44930227/134172193-b93763f2-4e59-4d89-b97d-a6ac2aedfa73.png)

**Comment by zsviczian** [comment]
I've looked into this. 
It seems I broke exportSVG. Will fix it tonight.
I will also publish an updated dataviewjs example, because since my script dataview has slightly changed.

**Comment by zsviczian** [comment]
See [1.3.11](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.3.11)
So there were two issues. 
1) Dataview has changed. I slightly updated the example. Note at the end: `ea.createSVG().then((svg)=>dv.span(svg.outerHTML));`
https://zsviczian.github.io/obsidian-excalidraw-plugin/Examples/dataviewjs_mindmap.html
2) I accidently left in an error in my lastet 1.3.10 release when creating the SVG. Now fixed.
