### ISSUE TITLE
BUG: The local URI is different from the default obsidian URI. As a result, the local URI cannot be correctly displayed during replication and pasting

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1481]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/0ef05fa0-6b5a-4803-b7e2-92c911013bc9)
As shown in the figure, URIs are displayed with different results for the same file
1 is the URI in EXcalidraw and 2 is the URI in MD

I was able to move images from MD to EXcalidraw, but I couldn't move files from EXcalidraw to MD

I copied the image in EXcalidraw and pasted it into MD and couldn't properly recognize it as a picture

As shown in the figure
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/a36c0045-bf1f-4473-a041-da63fb11f6bf)

**Comment by zsviczian** [comment]
Yes - incidentally I just fixed this last week for the next release - should be out later today.
