### ISSUE TITLE
FR: Ability to rotate canvas

### ISSUE THREAD

**Issue by AwaisBhatti1** [zsviczian/obsidian-excalidraw-plugin#1485]
Whenever I am drawing in excali-draw and I want to draw something slanted I am unable to rotate canvas in any way so it would be a massive improvement in experience of people who draw alot in excali-draw

**Comment by zsviczian** [comment]
I agree, this would be helpful. It also does not feel that difficult to implement. However this should be implemented in the core Excalidraw package, not the Obsidian plugin. Please raise this request with the core Excalidraw.com product team.

https://github.com/excalidraw/excalidraw/issues
