### ISSUE TITLE
FR: Automatically hides toolbars

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1490]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/11a9ba95-cd73-4a3a-ae34-ad237f10c677)
You want to be able to choose to hide the toolbar by default and only show it when the mouse moves over it

**Comment by zsviczian** [comment]
can probably be done with the right CSS code. I am happy to include the CSS in the plugin if you can provide me with it.

**Comment by jiajiala** [comment]
> can probably be done with the right CSS code. I am happy to include the CSS in the plugin if you can provide me with it.可能可以使用正确的CSS代码来完成。如果您能为我提供 CSS，我很乐意将 CSS 包含在插件中。

https://forum-zh.obsidian.md/t/topic/26848/4
Someone here helped write the css and share it with us
