### ISSUE TITLE
FR: Rectangle can be placed on top of the embedded document.

### ISSUE THREAD

**Issue by hiforrest** [zsviczian/obsidian-excalidraw-plugin#1495]
**Is your feature request related to a problem? Please describe.**

<img src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/2953848/a4685e7b-7525-4c6f-87ce-3954411b0d62" width="400">

 I tried to bring the rectangle to the front by right-clicking, but it just won't come to the top layer.

<img src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/2953848/93bbe68a-4654-4cf1-8f4b-3a8d804b4a39" width="400">

It's still stuck behind the embedded document.

**Describe the solution you'd like**

I hope I can move it to the very top without anything blocking it.

**Comment by zsviczian** [comment]
Can't be implemented with the current architecture.
