### ISSUE TITLE
FR: "Templater: Replace templates in the active file" does not work if file is opened as Excalidraw Drawing

### ISSUE THREAD

**Issue by SeLiEnisyst** [zsviczian/obsidian-excalidraw-plugin#1512]
Hi,

I assume, it is not a bug, that it's not possible to use the command "Templater: Replace templates in the active file", while Excalidraw is not opened in "Excalidraw Drawing"-mode. If I have opened the excalidraw file in "Markdown-mode" Templater is executed without errors (e.g. <% tp.file.title %>).

In excalidraw-mode I get the following error:
````
Templater Error:
Active editor is null, can't overwrite content
````

FR:
Making the Templater-command "Replace templates in the active file" compatible with excalidraw-drawing-mode.

**Comment by zsviczian** [comment]
you need to raise this with Templater. This is not an Excalidraw plugin issue.
