### ISSUE TITLE
BUG: Excalidraw Library just show blank page after updating to 2.0.11

### ISSUE THREAD

**Issue by HyunggyuJang** [zsviczian/obsidian-excalidraw-plugin#1516]
## Step to reproduce
Click the library button on the right side panel. 
Then, it renders blank as follows
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/27727031/73068b94-b3e6-427a-aaf9-d3712876dc9e)

**Comment by zsviczian** [comment]
I just noticed as well. Working on it.

**Comment by zsviczian** [comment]
This was a CSS issue. I've solve it. Will release soon
