### ISSUE TITLE
FR: can't import excalidraw libraries

### ISSUE THREAD

**Issue by honglingjinol** [zsviczian/obsidian-excalidraw-plugin#1517]
![Snipaste_2023-12-23_11-30-28](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/54520879/74664c00-8ffe-4438-af0c-fcf4bf0b3d0d)
I download some excalidraw libraries to my local personal computer from "https://libraries.excalidraw.com/". But I can't find how to import the libraries such as the picture. 
Thank you very much.

**Comment by zsviczian** [comment]
Do to a styling issue the stencil library is not visible in the 2.0.11 release. Solved it in 2.0.12 - will release soon.

Once it is fixed the process is to : download the library to your local PC
then click open to load it to Excalidraw.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/2b80226c-abed-4949-8bca-b37e5200d8d5)

**Comment by honglingjinol** [comment]
您好，您的邮件已收到，我会尽快回复，谢谢。
