### ISSUE TITLE
Ability to run a script or QuickAdd macro on file drop

### ISSUE THREAD

**Issue by dcoales** [zsviczian/obsidian-excalidraw-plugin#152]
When I drop a file onto an Excalidraw drawing I would like to be able to control how the link is added to the drawing.  At the moment I have a QuickAdd command mapped to a hotkey which I can use, after the link is created and I have selected it, to copy the link details onto a card and then delete the original link.  To avoid this step it would be great if there was a configuration option to run a js script or QuickAdd macro automatically on drop with the file details passed to the script/macro as a parameter.

With a js script I could automatically create a card with an embedded link to the file but one thing I do at the moment with my converter script is pop up a dialog box, pre-populated with the filename, to allow me to type something other than the filename to be used as the body of the card (since filenames on their own can be quite short and not very descriptive).

In an ideal world, I would also like to be able to create a list of options to choose from that would control what the final element to be added would look like but I don't know yet if that's possible with something like QuickAdd - I'm just starting to learn what it's capable of.

**Comment by dcoales** [comment]
It would also be really useful to provide details of any element the file is dropped onto.  That way I could make the new element look like the one I dropped the file onto.

**Comment by zsviczian** [comment]
Hi @dcoales, I implemented the MVP solution for the onDropHook. See [documentation](https://zsviczian.github.io/obsidian-excalidraw-plugin/API/utility.html#ondrophook) for details.

For now, you will need something like Templater startup templates to set the hook function. Since this is an advanced feature, I am not even sure I want to make it much easier to add a hook function.

Let me know if this does what you needed.

**Comment by dcoales** [comment]
Perfect.  Thank you so much.  I'm using a QuickAdd script, which runs when QuickAdd loads, in order to wire in the hook and that works great.  I'm not in control of the elements that get added when I drop a file - fantastic.  I think with this you are a step closer to creating something to rival project.meta 😃

**Comment by zsviczian** [comment]
Great, let me know if you are interested in other event hooks. 
On paste comes to mind...
