### ISSUE TITLE
BUG: "Stats for nerds" window no longer displays an object's size while it is being resized, when "Snap to objects" is off

### ISSUE THREAD

**Issue by TPO-POMGOM** [zsviczian/obsidian-excalidraw-plugin#1524]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.13
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: none
	Snippets enabled: 16
	Restricted mode: off
	Plugins installed: 30
	Plugins enabled: 26
		1: Hotkey Helper v0.3.18
		2: Paste URL into selection v1.7.0
		3: ObsidianTweaks v0.4.0
		4: Task Collector (TC) v1.0.14
		5: Smart Typography v1.0.18
		6: Excalidraw v2.0.13
		7: Lapel v0.1.1
		8: Longform v2.0.4
		9: Pane Relief v0.5.2
		10: Shell commands v0.20.1
		11: Wrap with shortcuts v1.3.0
		12: Vault Statistics v0.1.3
		13: Automatically reveal active file v1.0.2
		14: Plugin Update Tracker v1.5.2
		15: Map View v4.0.0
		16: Meld Encrypt v2.3.4
		17: Extract Highlights v0.0.18
		18: CSS Editor v0.5.0
		19: Image Toolkit v1.4.1
		20: Dataview v0.5.64
		21: Tag Wrangler v0.6.1
		22: Quick Preview v0.5.11
		23: Tasks v5.4.0
		24: Spaced Repetition v1.10.5
		25: Note Gallery v0.0.56
		26: Commander v0.5.1

**Describe the bug**
When "Snap to objects" is off, the "Stats for nerds" window will not display an object's size while it is being resized.

**To Reproduce**
1. Turn "Snap to objects" off
2. Display the "Stats for nerds" window
3. Select an object and resize it
4. The "Stats for nerds" window does not display the object's size live while it is being resized

**Expected behavior**
In previous versions of Excalidraw, the "Stats for nerds" window used to display the object's size live while it was being resized

**Discussion**
Seeing on object's size live while resizing it is an absolute requirement when using Excalidraw for floorplans and other drawings to scale. 

When "Snap to objects" is on, the "Stats for nerds" window *does* display the object's size live while it is being resized, but the object's size is constrained by the snap to object functionality, so this is not a usable workaround.

**Comment by zsviczian** [comment]
Yes - I also noticed. this must be a CSS side effect.

**Comment by zsviczian** [comment]
I was thinking of a different issue... I see this issue with the update of stats also affects excalidraw.com. Please raise it in the excalidraw.com issue list.

https://github.com/excalidraw/excalidraw/issues
