### ISSUE TITLE
BUG: Is there a way to use ScribbleHelper with a Surface?

### ISSUE THREAD

**Issue by daes10** [zsviczian/obsidian-excalidraw-plugin#1527]
**Describe the bug**
Is it right, that the scribble helper is only for IPad's?

Because on my Surface Book 2 the scribble helper will not allow me to write something in the scribblefield...
This is annoying.

Why is this only made and working on a IPad?

**Expected behavior**
Is there a way to give Scribble functionality on all Microsoft Surface Devices?
Because i think there are a lot of people using Exicalidraw on Microsoft Devices.

Or do i miss something?

**Comment by zsviczian** [comment]
Scribble is an Apple feature - all the script does is provider a larger text area to make it easier to scribble. You can use Microsoft handwriting with the on-screen keyboard.
