### ISSUE TITLE
FR: Add an option to open in full screen mode

### ISSUE THREAD

**Issue by HyunggyuJang** [zsviczian/obsidian-excalidraw-plugin#1528]
Similar to default mode option in preference, i.e., normal mode, view mode, zen mode, add an option to open in full screen mode.

**Comment by HyunggyuJang** [comment]
I mean when startup. I know that I can toggle it; but as like the mode setting I'd like to open excalidraw file in fullscreen model by default.

**Comment by zsviczian** [comment]
You can simply implement that with ExcalidrawAutomate. Here's the oneliner code you need:
```js
app.commands.executeCommandById("obsidian-excalidraw-plugin:fullscreen");
```

You can add this to the `ea.onFileOpenHook` by clicking the `Open Startup Script` button and editing the file:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/b0d5b020-2c29-49f9-8b57-60cec711b14c)

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/c68565db-0499-4921-a113-b8ae14706002)

For additional solution options watch: https://youtu.be/OX5_UYjXEvc?si=uuA2PTJ3UVKTmsG9

**Comment by HyunggyuJang** [comment]
Thanks a lot! Exactly what I needed.

**Comment by anatoliibakhtin** [comment]
@HyunggyuJang Hello, esteemed! Could you share your result?

Something is not working for me... I created the file through the ExcalidrawStartup settings, there are many examples commented out, I found the line with the code above and uncommented it: ea.onFileOpenHook = (data) => {app.commands.executeCommandById("obsidian-excalidraw-plugin:fullscreen");}; but when I open the file or switch from md to excalidraw mode, nothing happens...
