### ISSUE TITLE
BUG: I can't write words with the pen

### ISSUE THREAD

**Issue by HoodyEz** [zsviczian/obsidian-excalidraw-plugin#1529]
## Introduction
I usually use excalidraw to take notes for my university and I have the problem that when I try to make some words with the pen, the line closes automatically.

## To Reproduce**
Write with a graphic tablet or a tablet in Excalidraw with the pen words with small font.

## Expected behavior
I think that Excalidraw's pen it's configured to close the lines to do figures, but that's annoying when you tray to write like a notebook.

## Screenshots
**Example**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/95648139/577c61eb-d06b-4659-b13f-5e43ba5ad1bc)

**Example with zoom**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/95648139/13e4eae3-651f-44b4-b44a-21ed3678c4bf)

**Additional context**
Below you can see how when I write the “u” the line automatically closes and generates an “o”, it happens to me when I write with the smallest font, I would like to know how I can eliminate that automatic closing that makes the line.

I found this in Excalidraw/Excalidraw
https://github.com/excalidraw/excalidraw/issues/6303

**Comment by zsviczian** [comment]
I implemented a fix [#7510](https://github.com/excalidraw/excalidraw/pull/7510). Let's hope it gets incorporated into the main project. Regardless, I am releasing the fix to Obsidian.

Will include in 2.0.14

**Comment by HoodyEz** [comment]
Thank you!, but i still have the same problem, the line keeps closing, maybe it's because it continues to detect very little space between the end point and the start point. I don't know if you could add an option to change that value please.
