### ISSUE TITLE
FR: support vertical text arrangement

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1533]
want to support vertical text arrangement

**Comment by zsviczian** [comment]
you mean to rotate text by 90 degrees (simply rotate the text)
Arrange text vertically to top, bottom, middle. Add the text to a sticky note and it will work.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/866eb55c-c44c-4588-b009-3e0c00fbf50b)
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/e157bca0-d519-471b-a13b-93e098126fd6)

**Comment by jiajiala** [comment]
@zsviczian 
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/1b916808-5b2a-44ed-9950-a93ff68b293f)
Like this, the text is arranged vertically
