### ISSUE TITLE
BUG: Image disappears when opened for cropping

### ISSUE THREAD

**Issue by solita-laurini** [zsviczian/obsidian-excalidraw-plugin#1538]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103 23.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 14
		1: Calendar v1.5.10
		2: Excel to Markdown Table v0.4.0
		3: Advanced Tables v0.20.0
		4: Outliner v4.8.0
		5: Pandoc Plugin v0.4.1
		6: Importer v1.5.6
		7: Dataview v0.5.64
		8: Recent Files v1.3.9
		9: Tag Wrangler v0.6.1
		10: Templater v2.1.0
		11: File Tree Alternative Plugin v2.4.6
		12: Copy as HTML v1.1.3
		13: Excalidraw v2.0.15
		14: Text Format v2.3.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**

When I bring an image to Excalidraw from web (e.g. png image), make it active by selecting it, press CMD + P and choose 'Excalidraw: Crop image and mask images' I get and empty image in the new tab and the original is somehow disappeared from the original Excalidraw drawing.

**To Reproduce**

See previous section

**Expected behavior**

Image should be opened in the new tab

**Screenshots**

<img width="678" alt="Screenshot_2024_01_07_at_12_55_35" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/90904377/bc6d0826-a64b-40f6-9b14-86065f817c0e">
<img width="1076" alt="Screenshot_2024_01_07_at_12_55_49" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/90904377/fa92bb97-d309-4e7f-ba10-607e3d4727d6">

**Comment by zsviczian** [comment]
What happens if before selecting the image you press CTRL+S to force save?
Can you share the link to the image you are trying from the web?

**Comment by solita-laurini** [comment]
Link to the image is here: https://thenounproject.com/photo/blue-hologram-with-technology-information-on-screen-561px0/

But, it happens with all the images, not just this one. I just tried this:

0. Opened a new Excalidraw canvas
1. 'Insert ANY file'
2. Chose an image (png) from my vault
3. Inserted as image
4. Force saved the file
5. Made the image active by selecting it
6. CMD + P --> 'Excalidraw: Crop image and mask images'

same situation happens again.

**Comment by zsviczian** [comment]
Can you try it with an employee Vault, only Excalidraw installed? Though looking at your list of plugins nothing stands out as a potential culprit...

Also can you switch the the right hand file to markdown view mode and send a screenshot? 

If you press CMD+opt+I (developer console), do you see any errors?

**Comment by solita-laurini** [comment]
Please see the screenshots here, some error there in the developer console from Obsidian-outliner plugin. I disabled it but it did not have an effect on this.

<img width="1095" alt="Screenshot_2024_01_07_at_16_21_20" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/90904377/7f11b154-0120-4ab2-a3ea-e83e72474e53">
<img width="1107" alt="Screenshot_2024_01_07_at_16_22_32" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/90904377/1d21beca-eafc-407a-92b1-8484aee6631d">

**Comment by solita-laurini** [comment]
I think it might be some file sync / saving issue. I'm using my vault in the MS OneDrive folder which is syncing into the cloud. So, after some hard saves and reloads / reopening of the files, I get the pictures visible in both sides.

**Comment by zsviczian** [comment]
I am able to reproduce this issue by throtlling my PC by a factor of 6 and using a large JPG image.

**Comment by zsviczian** [comment]
I am releasing an update that I hope properly addresses this error.
