### ISSUE TITLE
excalidraw note wiki links

### ISSUE THREAD

**Issue by nhaouari** [zsviczian/obsidian-excalidraw-plugin#154]
I hope you consider the ability to add a link to an inexisting excalidraw note in excalidraw note. This will help in developing complex ideas visually without passing by md.

**Comment by zsviczian** [comment]
just to make sure I understand you correctly… Are you using excalidraw in compatibility mode?

If not… You can create links to non-existing documents. you need to alt+ctrl click the link to create it. Then you can use the command palette action to convert the empty md document to excalidraw. You can also add a hotkey to the command palette action to make the conversion of an empty note quicker.

**Comment by nhaouari** [comment]
> just to make sure I understand you correctly… Are you using excalidraw in compatibility mode?
> 
> If not… You can create links to non-existing documents. you need to alt+ctrl click the link to create it. Then you can use the command palette action to convert the empty md document to excalidraw. You can also add a hotkey to the command palette action to make the conversion of an empty note quicker.

Great! I didn't know there was a convert command. Thank you very much for your reply.
