### ISSUE TITLE
BUG: Error display when inserting Latex formula

### ISSUE THREAD

**Issue by 6209233** [zsviczian/obsidian-excalidraw-plugin#1541]
**Describe the bug**
Error display for latex inserting.

**To Reproduce**
1. Just using "Insert LaTeX formula"
2. See error

**Expected behavior**
A correct display.

**Screenshots**
The output:
![图片](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/132437196/785eb2ab-12b2-4b2e-b423-f5b2309cedcb)
With my input:
![图片](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/132437196/70eeada1-0225-4e20-ae66-a94e2712f77c)

**Additional context**
Well, I don't know if it only occurs on my PC. I have no idea about this. If cannot be reproduced, it is my problem. Apologize in advance.

**Comment by zsviczian** [comment]
This looks as if some extra packages are required. I typed this formula into obsidian markdown but nothing was displayed... Obsidian does not support the additional packages.

I am sorry, but I do not myself use LaTeX - thus I am also not familiar with how these packages should be loaded, how modules are normally added...

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/e2354b1a-95fc-4ff9-9bc0-4fa8fadf6b63)

**Comment by denisgorod** [comment]
The problem you are running into is that LaTeX code in Obsidian is compiled using MathJax and not full LaTeX. You cannot use \usepackage in MathJax directly, it has to be done in MathJax settings that are not directly available for editing.

You could try to use the Extended MathJax plugin: it allows you to add an additional header with the required packages using the standard \usepackage syntax.

**Comment by 6209233** [comment]
I get the point! Thanks very much and I must apologize for my bad care. 
If I had checked this error seriously enough, I should have discovered this problem.

The fault in my pic is just some part of my "preamble.sty" file which is just used in Extended MathJax plugin. So my mistake is that I have wrongly wroten this file by including
﻿$$
\usepackage{extarrow}
$$
Which is just the error! By deleting this, all is well. 

So I must apologizing for wasting your time, all is my fault. https://docs.github.com/articles/github-community-guidelines
Really sorry! A lesson learned!
