### ISSUE TITLE
FR: Convert Remote/External SVG to Excalidraw

### ISSUE THREAD

**Issue by MahmadSharaf** [zsviczian/obsidian-excalidraw-plugin#1543]
**Is your feature request related to a problem? Please describe.**
Yes, I upload all my media files on cloud, including SVG files. I would love to have this feature enabled for me without extra friction.

**Describe the solution you'd like**
Allow providing a URL of the SVG file to be converted instead of listing only the available SVGs in the vault

**Describe alternatives you've considered**
Download the file locally, convert it, and then delete it

**Additional context**
No

**Comment by zsviczian** [comment]
I agree, this is something I come across myself as well from time to time. Would pasting the url be a good solution for you?

**Comment by MahmadSharaf** [comment]
Yeah indeed, would be great. Or in a context menu for an inserted SVG file. Or any other solution that you see suitable. You have been spoiling us with features and flexibility, so I trust you with any solution convenient to you.

**Comment by zsviczian** [comment]
I like this idea about the context menu for SVG files. I think that will be more user friendly than pasting links.
