### ISSUE TITLE
BUG: Unable to see toolbar, tray, etc in excalidraw view on samsung s7

### ISSUE THREAD

**Issue by hauswio** [zsviczian/obsidian-excalidraw-plugin#1547]
**Your environment**
android 10
obsidian 1.4.16 (114)
excalidraw 2.0.16

**Describe the bug**
When I have an excalidraw drawing open in excalidraw view mode I can't see the tray, toolbar, etc in order to edit the drawing.

**To Reproduce**
1. Create new drawing
2. see no tools

**Expected behavior**
To be able to select tools and draw.

**Comment by zsviczian** [comment]
In view mode the toolbar is not visible. Long press on the canvas and untick view mode in the context menu.

You can set the default mode to open on a phone here:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/6e38cc04-b705-4195-a713-76428e4172f0)

**Comment by hauswio** [comment]
I already had always normal mode selected. Long press with finger or pen
does nothing on the canvas. The only interactivity I can make work is
switching between excalidraw and markdown modes in the 3dot menu. The
excalidraw commands also do nothing.

**Comment by zsviczian** [comment]
This is when creating a new file or when opening an existing file?
Are you using a custom theme or CSS snippets? Please test without them.
Did you manually install Excalidraw from GitHub or via Community Plugins from within Obsidian? If manually, then did you copy the style.css to the plugin folder?

**Comment by hauswio** [comment]
Creating new files with the excalidraw button on the left menu or opening
existing files that were made with that button. Nothing custom. It's a
brand new tablet. After initial setup I installed obsidian from google play
store, then installed excalidraw from community plugins in obsidian. I've
made no other setting or configuration changes.

**Comment by zsviczian** [comment]
can share a screenshot of what you are seeing?

**Comment by hauswio** [comment]
Not much unfortunately.

**Comment by hauswio** [comment]
![Screenshot_20240110-213250_Obsidian](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/92599939/b9f7b444-2799-4fcc-9157-5c7636fcc6f6)

**Comment by zsviczian** [comment]
Android 10 is pretty old. I recommend updating Android Web View.

see also: #181 ; #739 ; #1274

**Comment by hauswio** [comment]
Thanks for calling that out. After a few days of manually checking for updates until the device was actually up to date, everything works.

Sorry!
