### ISSUE TITLE
BUG: Script [Mindmap format] report an error and not working

### ISSUE THREAD

**Issue by SdKay** [zsviczian/obsidian-excalidraw-plugin#1549]
**Your environment**
ubuntu20.04, obsidian1.5.3, excalidraw:2.0.17.

**Describe the bug**
I use [Mindmap format.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Mindmap%20format.md) to format and an error occurs

**To Reproduce**
1. download [Mindmap format.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Mindmap%20format.md) to script folder
2. Create an excalidraw(show in picture below)
3. Run command to execute script

**Expected behavior**
Format successfully

**Screenshots**
![Screenshot from 2024-01-11 10-32-43](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/18526517/4db2eb82-45c6-42c6-acfe-aa479804eece)

![Screenshot from 2024-01-11 10-27-12](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/18526517/5f06d014-8d2a-46cd-a461-32ff635557df)

**Comment by zsviczian** [comment]
mindmap format is just a demo script. It is not built to be very robust.
Make sure that your input file does not have an empty line at the end.

**Comment by SdKay** [comment]
> mindmap format is just a demo script. It is not built to be very robust. Make sure that your input file does not have an empty line at the end.

Thanks for replying! Here is my input file and there is no empty line.
[Drawing 2024-01-11 10.04.31.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/13898517/Drawing.2024-01-11.10.04.31.excalidraw.md)

I found its possible use plantuml to create mindmap and support section link inside, but cannot set reference alias and other obsidian features
```plantuml
@startmindmap
* root
** step1
*** aa
*** bb
** step2
*** cc
*** dd [[#referece]]
@endmindmap
```
![Screenshot from 2024-01-11 15-12-59](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/18526517/6cccf8af-235b-4ea0-aad6-b7e14fa4accd)

**Comment by pandoralink** [comment]
I am the developer of mindmap format script, you can give me the original file and I will try to fix this for you @SdKay

**Comment by zsviczian** [comment]
@pandoralink 🙏
https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Mindmap%20format.md

**Comment by pandoralink** [comment]
I'm sorry, but I couldn't reproduce the issue. Here is my reproduction path. Please confirm if your mindmap format is the latest version. @SdKay 

![56](https://github.com/user-attachments/assets/b4185405-5eb9-47f3-a5ac-1490a88403de)

**Comment by pandoralink** [comment]
> @pandoralink 🙏 https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Mindmap%20format.md

You can @ me regarding any features or bugs related to the mindmap. I will do my best to fix them. The mindmap format was originally coded to help others. I'm very happy to see that it actually helps people. @zsviczian

**Comment by SdKay** [comment]
> I am the developer of mindmap format script, you can give me the original file and I will try to fix this for you @SdKay

I reproduce the issue on windows10, obsidian1.6.7, excalidraw:2.4.3
[Drawing 2024-09-25 09.34.27.excalidraw.md](https://github.com/user-attachments/files/17123110/Drawing.2024-09-25.09.34.27.excalidraw.md)

![image](https://github.com/user-attachments/assets/b93786ea-5ac4-452e-9951-ec03d7788760)

**Comment by pandoralink** [comment]
> > I am the developer of mindmap format script, you can give me the original file and I will try to fix this for you @SdKay
> 
> I reproduce the issue on windows10, obsidian1.6.7, excalidraw:2.4.3 [Drawing 2024-09-25 09.34.27.excalidraw.md](https://github.com/user-attachments/files/17123110/Drawing.2024-09-25.09.34.27.excalidraw.md)
> 
> ![image](https://private-user-images.githubusercontent.com/18526517/370521536-b93786ea-5ac4-452e-9951-ec03d7788760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzI5MzksIm5iZiI6MTcyNzI3MjYzOSwicGF0aCI6Ii8xODUyNjUxNy8zNzA1MjE1MzYtYjkzNzg2ZWEtNWFjNC00NTJlLTk5NTEtZWMwM2Q3Nzg4NzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDEzNTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNjNmMjhmMmIxNjRkODc3YWViMjZmMTJlYzZhN2Y4NjJmZDg1Njg4NGY0OTAwNmQ0NzNlZWI0MTg3ZDJhMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VBK5JGXy84zpkwU61257G9xnppLKl2R-OGQPS8-SBj0)

Your operation is incorrect. You must select the rectangles you want to format before executing the script. Additionally, the lack of a prompt for unselected rectangles is also a downside.

`bad case`
![57](https://github.com/user-attachments/assets/2bd311f9-d23c-4687-b4a5-8200c7f398c0)
`good case`
![58](https://github.com/user-attachments/assets/b12c625b-420d-497a-8112-869b48e0688d)

**Comment by SdKay** [comment]
> > > I am the developer of mindmap format script, you can give me the original file and I will try to fix this for you @SdKay
> > 
> > 
> > I reproduce the issue on windows10, obsidian1.6.7, excalidraw:2.4.3 [Drawing 2024-09-25 09.34.27.excalidraw.md](https://github.com/user-attachments/files/17123110/Drawing.2024-09-25.09.34.27.excalidraw.md)
> > ![image](https://private-user-images.githubusercontent.com/18526517/370521536-b93786ea-5ac4-452e-9951-ec03d7788760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzI5MzksIm5iZiI6MTcyNzI3MjYzOSwicGF0aCI6Ii8xODUyNjUxNy8zNzA1MjE1MzYtYjkzNzg2ZWEtNWFjNC00NTJlLTk5NTEtZWMwM2Q3Nzg4NzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDEzNTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNjNmMjhmMmIxNjRkODc3YWViMjZmMTJlYzZhN2Y4NjJmZDg1Njg4NGY0OTAwNmQ0NzNlZWI0MTg3ZDJhMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VBK5JGXy84zpkwU61257G9xnppLKl2R-OGQPS8-SBj0)
> 
> Your operation is incorrect. You must select the rectangles you want to format before executing the script. Additionally, the lack of a prompt for unselected rectangles is also a downside.
> 
> `bad case`
> 
> ![57](https://private-user-images.githubusercontent.com/71766324/370748799-2bd311f9-d23c-4687-b4a5-8200c7f398c0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjkyMjMsIm5iZiI6MTcyNzMyODkyMywicGF0aCI6Ii83MTc2NjMyNC8zNzA3NDg3OTktMmJkMzExZjktZDIzYy00Njg3LWI0YTUtODIwMGM3ZjM5OGMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA1MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4OTc2MmQwNmY3M2VkODVkZjkxMzI5NTg1OTRkYWM5NzRlNmI4M2M5MDc4Zjc2NDJlOWEzNzJlNWVkMjRlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OaiMGgzCZj6XNx5tuavb884NQtdfi7Og_YkzSxrSzYE) [ ![57](https://private-user-images.githubusercontent.com/71766324/370748799-2bd311f9-d23c-4687-b4a5-8200c7f398c0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjkyMjMsIm5iZiI6MTcyNzMyODkyMywicGF0aCI6Ii83MTc2NjMyNC8zNzA3NDg3OTktMmJkMzExZjktZDIzYy00Njg3LWI0YTUtODIwMGM3ZjM5OGMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA1MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4OTc2MmQwNmY3M2VkODVkZjkxMzI5NTg1OTRkYWM5NzRlNmI4M2M5MDc4Zjc2NDJlOWEzNzJlNWVkMjRlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OaiMGgzCZj6XNx5tuavb884NQtdfi7Og_YkzSxrSzYE) ](https://private-user-images.githubusercontent.com/71766324/370748799-2bd311f9-d23c-4687-b4a5-8200c7f398c0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjkyMjMsIm5iZiI6MTcyNzMyODkyMywicGF0aCI6Ii83MTc2NjMyNC8zNzA3NDg3OTktMmJkMzExZjktZDIzYy00Njg3LWI0YTUtODIwMGM3ZjM5OGMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA1MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4OTc2MmQwNmY3M2VkODVkZjkxMzI5NTg1OTRkYWM5NzRlNmI4M2M5MDc4Zjc2NDJlOWEzNzJlNWVkMjRlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OaiMGgzCZj6XNx5tuavb884NQtdfi7Og_YkzSxrSzYE) [ ](https://private-user-images.githubusercontent.com/71766324/370748799-2bd311f9-d23c-4687-b4a5-8200c7f398c0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjkyMjMsIm5iZiI6MTcyNzMyODkyMywicGF0aCI6Ii83MTc2NjMyNC8zNzA3NDg3OTktMmJkMzExZjktZDIzYy00Njg3LWI0YTUtODIwMGM3ZjM5OGMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA1MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4OTc2MmQwNmY3M2VkODVkZjkxMzI5NTg1OTRkYWM5NzRlNmI4M2M5MDc4Zjc2NDJlOWEzNzJlNWVkMjRlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OaiMGgzCZj6XNx5tuavb884NQtdfi7Og_YkzSxrSzYE)
> 
> `good case`
> 
> ![58](https://private-user-images.githubusercontent.com/71766324/370749104-b12c625b-420d-497a-8112-869b48e0688d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjkyMjMsIm5iZiI6MTcyNzMyODkyMywicGF0aCI6Ii83MTc2NjMyNC8zNzA3NDkxMDQtYjEyYzYyNWItNDIwZC00OTdhLTgxMTItODY5YjQ4ZTA2ODhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA1MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNjE2ZjkwNWMzOTAwZjFmYzMxNTE2MGJlMzZjYTg0NjFhYzI4OGIxNjJhMTEwYmM0MWY0NjM5Yjc4MWMxNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pAuJ-bx1YypSrApV__5HFgc3H0HFyFSn3-nSmy5oIyk) [ ![58](https://private-user-images.githubusercontent.com/71766324/370749104-b12c625b-420d-497a-8112-869b48e0688d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjkyMjMsIm5iZiI6MTcyNzMyODkyMywicGF0aCI6Ii83MTc2NjMyNC8zNzA3NDkxMDQtYjEyYzYyNWItNDIwZC00OTdhLTgxMTItODY5YjQ4ZTA2ODhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA1MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNjE2ZjkwNWMzOTAwZjFmYzMxNTE2MGJlMzZjYTg0NjFhYzI4OGIxNjJhMTEwYmM0MWY0NjM5Yjc4MWMxNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pAuJ-bx1YypSrApV__5HFgc3H0HFyFSn3-nSmy5oIyk) ](https://private-user-images.githubusercontent.com/71766324/370749104-b12c625b-420d-497a-8112-869b48e0688d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjkyMjMsIm5iZiI6MTcyNzMyODkyMywicGF0aCI6Ii83MTc2NjMyNC8zNzA3NDkxMDQtYjEyYzYyNWItNDIwZC00OTdhLTgxMTItODY5YjQ4ZTA2ODhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA1MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNjE2ZjkwNWMzOTAwZjFmYzMxNTE2MGJlMzZjYTg0NjFhYzI4OGIxNjJhMTEwYmM0MWY0NjM5Yjc4MWMxNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pAuJ-bx1YypSrApV__5HFgc3H0HFyFSn3-nSmy5oIyk) [ ](https://private-user-images.githubusercontent.com/71766324/370749104-b12c625b-420d-497a-8112-869b48e0688d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjkyMjMsIm5iZiI6MTcyNzMyODkyMywicGF0aCI6Ii83MTc2NjMyNC8zNzA3NDkxMDQtYjEyYzYyNWItNDIwZC00OTdhLTgxMTItODY5YjQ4ZTA2ODhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA1MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNjE2ZjkwNWMzOTAwZjFmYzMxNTE2MGJlMzZjYTg0NjFhYzI4OGIxNjJhMTEwYmM0MWY0NjM5Yjc4MWMxNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pAuJ-bx1YypSrApV__5HFgc3H0HFyFSn3-nSmy5oIyk)

没问题了, 确实是我的用的不对, 谢谢大佬
