### ISSUE TITLE
Conversion from Excalidraw.com appears corrupt

### ISSUE THREAD

**Issue by psarras** [zsviczian/obsidian-excalidraw-plugin#155]
**Describe the bug**
Converting files from Excalidraw.com doesn't seem to work. Getting error to manually fix the json file.

**To Reproduce**
1. Draw something on Excalidraw.com
2. Download xxx.excalidraw file
3. Move to your notes location for obsidian
4. Able to open the .excalidraw file
5. Convert to .excalidraw.md
6. Broken file as in screenshot

**Expected behavior**
I expect the conversion to show the same result as the Excalidraw.com does

**Screenshots**
![image](https://user-images.githubusercontent.com/3820417/135544751-0d4069d5-d610-43bf-ae82-7b3426e6e28f.png)

**Desktop (please complete the following information):**
 - OS: Windows Client
 - Version Excalidraw 1.3.15
 - Obsidian v0.12.15

**Comment by zsviczian** [comment]
Thanks. It seems that at some point, Excalidraw changed its file export, and I did not notice the change. I've fixed the issue. Will release the fix tonight.

**Comment by ruanwz** [comment]
Hi @zsviczian , here are the screenshots. What I have done are: 1. draw something on excalidraw.com, 2. export as a file, 3. open a new excalidraw drawing in obsidian, 4. edit in markdown mode and replace the json content with the exported file, 5. it shows the error. Thanks a lot for checking it!

![image](https://user-images.githubusercontent.com/4874/137833484-98493004-1cf9-493e-bcc4-69a001db71b8.png)

![image](https://user-images.githubusercontent.com/4874/137833614-a45df7fd-76a6-4c46-b1e8-fce30820404b.png)

![image](https://user-images.githubusercontent.com/4874/137833703-3cc3b3f8-1b73-49e6-84aa-c806febef7fb.png)

Here is the file exported from excalidraw.com:
```json
{
  "type": "excalidraw",
  "version": 2,
  "source": "https://excalidraw.com",
  "elements": [
    {
      "id": "al5NpL7kcEs4WJl4aK9-I",
      "type": "rectangle",
      "x": 499.65234375,
      "y": 202.21875,
      "width": 336.47265625,
      "height": 165.48828125,
      "angle": 0,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "groupIds": [],
      "strokeSharpness": "sharp",
      "seed": 856044078,
      "version": 16,
      "versionNonce": 18467826,
      "isDeleted": false,
      "boundElementIds": null
    }
  ],
  "appState": {
    "gridSize": null,
    "viewBackgroundColor": "#ffffff"
  }
}

```
