### ISSUE TITLE
FR: setting color + sending to the back/front of embedded files

### ISSUE THREAD

**Issue by SeLiEnisyst** [zsviczian/obsidian-excalidraw-plugin#1552]
**Is your feature request related to a problem? Please describe.**
I want to transclude drawings into another. 

I found two possibility to manage this:
1) to embed an excalidraw.md "as Image"
- This works very nice and I can send the embeded excalidraw.md-Image to the background or to the front, as I like to.
- The disadvantage of this way is, that I don't have the possibility to set the background color of the embedded excalidraw.md-Image to some different color than the excalidraw canvas. => This would be nice, to indicate, that here is an embedded Image an not part of the excalidraw canvas drawing.

2) to embed an exported excalidraw-svg "as Embeddable".
- Here I can set the background of the exported excalidraw-svg as I like, to get some difference to the background of the canvas
- Unfortunately I'm not able to send this embedded excalidraw-svg to the background...

**Describe the solution you'd like**
It would be nice if both ways would have both features: setting background color of the embedded file and also sending it to the back or to the front.

**Comment by zsviczian** [comment]
Embeddables work differently they will not adhere to the layering, or rather embeddable are at the top layer.
You can always add a rectangle behind the embedded excalidraw to set a background color. I use the [Box selected elements](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Box%20Selected%20Elements.md) script to add a rectangle around images or anything else I want to give a border or background color to.
