### ISSUE TITLE
BUG: Colors should not invert when I explicitly select them

### ISSUE THREAD

**Issue by Crowbrammer** [zsviczian/obsidian-excalidraw-plugin#1555]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.13
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 4
	Plugins enabled: 4
		1: Excalidraw v2.0.7
		2: Hotkeys for specific files v1.4.0
		3: Kanban v1.5.3
		4: Recent Files v1.3.8

**Describe the bug**

Dark mode > Pen tool > select color from eyedropper tool > inverts colors (don't want this)

**To Reproduce**
1. Enable dark mode
2. Open the pen tool
3. Try to select a color via the eye dropper
4. Draw stuff but in the opposite "lightness" you want >:o 😄

**Expected behavior**

For it to draw in the color I selected.

**Screenshots**

![invertedcolors](https://i.imgur.com/0LRuuBZ.gif)

**Additional context**

I did have french toast and chocolate milk before experiencing this issue >:o

**Comment by zsviczian** [comment]
This is something that needs to be addressed in the Excalidraw package. You can comment on the existing issue here: https://github.com/excalidraw/excalidraw/issues/6669

In obsidian this is my solution - I do not use dark mode, but instead use a dark color palette
- https://youtu.be/fypDth_-8q0
- https://youtu.be/diBT5iaoAYo
