### ISSUE TITLE
BUG: Incorrect styling on IPhone 13

### ISSUE THREAD

**Issue by FieryCod** [zsviczian/obsidian-excalidraw-plugin#1557]
**Your environment**

SYSTEM INFO:
	Operating system: ios 17.1.2 (Apple iPhone)
	Obsidian version: 1.4.16 (114)
	API version: v1.4.16
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 4
	Plugins enabled: 4
		1: Numerals v1.2.0
		2: Text Generator v0.6.2
		3: Image Captions v1.1.0
		4: Excalidraw v2.0.17

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**

**To Reproduce**
- Navigate to settings (maybe this bug is an upstream one?)
- Navigate to debug info
- Open drawing

**Expected behavior**
I expect exit buttons to be clickable and if possible I would like the buttons to not be emojis (maybe as an option in settings?).

I expect the actions icons to be easily accessible and not be covered by menu.

I expect the input to have consistent height.

I expect settings sections to have additional padding-bottom. 

**Screenshots**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14275210/b6fb204d-11b1-4ed1-8cae-962c4fe5e96e)
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14275210/8d38addd-a9ab-4bbd-932d-5c90baf5b143)
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14275210/c4bd0068-3f39-4e11-aead-6c9113ac46bf)
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14275210/8168ed69-8270-40ac-ad3e-39374e6eac96)

**Comment by zsviczian** [comment]
The emojis come from the plugin but I don't think it is a priority to change them. The full-screen dialog box comes from Obsidian. I am simply using an Obsidian built-in dialog box.
