### ISSUE TITLE
Option to open a page (from a link in excalidraw) in a pane that is already opened (instead of a new pane)

### ISSUE THREAD

**Issue by GitMurf** [zsviczian/obsidian-excalidraw-plugin#156]
I am liking experimenting with putting links into excalidraw drawings to allow to open other notes from it. One thing I would love to be able to do is instead of opening a link in another pane, I like to have excalidraw open in split screen mode with another regular markdown pane split to the right. I would love a way for opening a link in excalidraw drawing into that already open pane next to it. Basically so I can jump between links and see them side by side instead of having a new pane opened each time which then splits my screen in 3. So the "easy" quick logic would be just look for the next pane and use that one that is already opened instead of opening a new pane. Maybe instead of shift + click from the toolbar it is ctrl + shift + click to open in a pane that is already opened next to excalidraw? Does that make sense?

@zsviczian responded with the following on discord which is perfect solution to me: "I can also do the open in next page as well. I would make it a setting if you want to open a new page or open into an existing pane"

**Comment by zsviczian** [comment]
Solved in 1.3.17

**Comment by GitMurf** [comment]
Perfect! Exactly as I was hoping :) You amazing!
