### ISSUE TITLE
BUG: It's hard to see the frame header when I modify it in dark mode

### ISSUE THREAD

**Issue by guxiyuesi** [zsviczian/obsidian-excalidraw-plugin#1568]
obsidian: v1.5.3
obsidian-excalidraw: 2.0.18
os: Windows 10

when I switch to dark mode, althrough the color of the frame header is a little light, it is clear. But When I want to modify it, the font color become dark, which is hard to see.

normal dark mode:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/62014785/aed17242-fa3a-4892-b48c-a3804f56001f)

when modify:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/62014785/7bcc6907-e275-4673-a607-2785589c2aaf)

**Comment by zsviczian** [comment]
fixed in 2.0.19
will release in a few days.
