### ISSUE TITLE
FR: Slideshow Frame Transition Speed

### ISSUE THREAD

**Issue by mmadson** [zsviczian/obsidian-excalidraw-plugin#1571]
**Is your feature request related to a problem? Please describe.**

I'm trying to transition from excalidraw+ to obsidian + excalidraw plugin. The slideshow script has nearly the same feature set as the excalidraw+ slideshow capabilities except that transitions are not nearly as smooth / quick / or clear. When transitioning between slides in obsidian + excalidraw, text often becomes blurry and the transition speed is quite slow. It'd be great if we could increase the transition speed which would also make the blurry text less noticeable. 

**Describe the solution you'd like**
Some sort of configuration in the slideshow controls to set the transition speed.

**Describe alternatives you've considered**
Modifying the script directly or using excalidraw+

**Additional context**
N/A

**Comment by zsviczian** [comment]
You can change TRANSITION_DELAY in the downloaded script.

**Comment by mmadson** [comment]
> You can change TRANSITION_DELAY in the downloaded script.

absolutely perfect, sorry I didn't look closely enough at the consts. Wonderful work. =)
