### ISSUE TITLE
Allow click and drag of canvas to move left/right/up/down in the canvas, as opposed to selecting elements

### ISSUE THREAD

**Issue by GitMurf** [zsviczian/obsidian-excalidraw-plugin#158]
Also another question, with a mouse I can move left / right and up / down around the canvas with mouse wheel + shift mouse wheel. But is there a way / mode to put it in to click and drag/pull my way around the canvas instead of the default action of click and drag doing a selection box?

Would be nice if clicking and dragging by default moved you around the canvas (left/right/up/down) and then shift + click and drag would do the selection box to select elements. Does that make sense?

**Comment by GitMurf** [comment]
In discord @zsviczian told me that clicking the mouse wheel and dragging gives me what I want. It does, and I can make due with that although my mouse wheel button is super finicky. It isn't the easiest UX in the world for me. It is more natural for me to be able to click and drag normally to move around. Would it be possible to left Shift + Click and drag move around the canvas? Basically allowing Shift + Click be equivalent to the current Mouse Wheel click?

**Comment by zsviczian** [comment]
hi @GitMurf, this is a good suggestion - however, this needs a change to the core Excalidraw component. While I have given up on the "do-not-touch" the excalidraw component rule, I still want to keep custom changes to the absolute minimum to ensure Obsidian can continue to benefit from the core Excalidraw product development. Maybe you could open this issue with Excalidraw? https://github.com/excalidraw/excalidraw

**Comment by GitMurf** [comment]
Makes sense and I am completely fine with that and agree with your decision on this too :) Thanks for the update!

**Comment by GitMurf** [comment]
p.s. I have already started to get used to using the mouse wheel click to drag around and it is getting easier and easier as I do it more :)
