### ISSUE TITLE
FR: Able to toggle group/ungroup with hot key

### ISSUE THREAD

**Issue by davetorbeck** [zsviczian/obsidian-excalidraw-plugin#1584]
Would be nice to be able to set a hot key to quickly group elements without having to use visual menus.

EDIT:  Same for commands like "duplicate"

**Comment by k-shlomi** [comment]
this would be greatly appreciated if added to the plugin

**Comment by davetorbeck** [comment]
This is supported now with `Ctrl/CMD+G`
