### ISSUE TITLE
Handwriting optimization experience

### ISSUE THREAD

**Issue by MatilAlpha-1** [zsviczian/obsidian-excalidraw-plugin#1590]
I really like using this plug-in in obsidian, but this handwriting makes me feel uncomfortable and not very smooth. Can you please focus on optimizing the handwriting experience in future optimization to make handwriting smoother? No need For pressure sensitivity, etc., just refer to “goodnotes 5” to make your handwriting smoother.

**Comment by zsviczian** [comment]
I understand, and I am sorry... Excalidraw is a Vector illustration tool. It can do handwriting but it is not designed for long stretches of handwriting support, and even for short stretches, it is not the ideal tool for that. I might come across as blunt, but I just want to be upfront. In my opinion, no amount of attention will make Excalidraw handwriting friendly considering the current architecture. This is not in my focus.

**Comment by max-nothacker** [comment]
I second this. Given I am trying to organize math proof ideas sketches/practice exercises (and no, I am not typing out all of my intial thoughts in latex) in obsidian and then interlink it with theorems, PDFs of books, etc. 

Hmm... if this is not a focus then this is unfortunate but understandable.
