### ISSUE TITLE
Is it possible to insert part of one excalidraw file into another excalidraw file as an interactive element?

### ISSUE THREAD

**Issue by asckvas** [zsviczian/obsidian-excalidraw-plugin#1597]
I have a need to use one excalidraw file to make one large mindmap, parts of which would be convenient to use in other excalidraw files. Is there such functionality now? I know that it is possible to insert as an image, but this is not suitable, since the entire map is inserted. I tried to do this with frames, but it doesn't work. Thank you in advance!!

**Comment by zsviczian** [comment]
not at this time
