### ISSUE TITLE
BUG: Can't click on any toolbar icon

### ISSUE THREAD

**Issue by mathisgauthey** [zsviczian/obsidian-excalidraw-plugin#1604]
```
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.16
	Operating system: Windows 10 Pro 10.0.22631
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 36
	Plugins enabled: 2
		1: Excalidraw v2.0.21
		2: Github Publisher v6.15.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Describe the bug**
I can't click on any toolbar icon : 
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/46576952/ffa89561-5ca0-4c31-ae71-cccd099bf7c1)

**To Reproduce**
1. Install the [github-publisher plugin](https://github.com/ObsidianPublisher/obsidian-github-publisher) and Excalidraw
2. Try to use any icon. It doesn't work.

**Expected behavior**
I should be able to click on a toolbar icon (using a new vault, it works) : 
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/46576952/f59b9a97-0d73-4d60-8799-3a259d7108d7)

**Screenshots**
Provided in the text.

**Additional context**
Nope, but I'll take this space to thank you for your work.

**Comment by zsviczian** [comment]
Based on the linked bug... do I understand this correctly that you do not experience the issue when Obsidian Publisher is disabled? If that is the case, then indeed the issue needs to be addressed in the Obsidian github publisher plugin. 
This feels like a CSS issue.

**Comment by Lisandra-dev** [comment]
Hello!
It's effectively an issue with Publisher.

I used `@excalidraw/utils` for exporting from JSON into SVG. It seems it cause an issue with excalidraw, like that:
With Publisher:
![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/30244939/88d08640-6a4f-45a0-9c53-da4a5ac49540)

Without:
![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/30244939/a41d78e1-6706-4df0-8012-dce07bd9c364)

The version used is the `0.1.2` and i think it could lead to an issue.

How can I use directly the API of this plugin instead on relying on @excalidraw/utils? I just need to export to SVG.

**Comment by zsviczian** [comment]
Depending on how you call EA, you might want to start with ea.clear();
to create the SVG for a drawing just run await ea.createSVG(filepath); You can see further documentation with the ea.help function.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/b20fc8ba-30e0-414e-9124-82dfeae24c4b)

**Comment by Lisandra-dev** [comment]
Thanks for the quick reply!
How i call the ea in another plugin?
Need I install some dependencies?

**Comment by mathisgauthey** [comment]
It has been [fixed](https://github.com/ObsidianPublisher/obsidian-github-publisher/issues/315), thanks for your time !
