### ISSUE TITLE
FR: Alignment/sizing guides when moving/resizing elements

### ISSUE THREAD

**Issue by macintacos** [zsviczian/obsidian-excalidraw-plugin#1625]
**Is your feature request related to a problem? Please describe.**

When I was working on polishing up some diagrams for sharing with some colleagues, I realized that not having realtime feedback that "this object is the same size as that object over there" is a bit of a big drawback for me. I tend to make sure that all of my diagrams are "neat" by making sure that sizes are consistent, and I can't figure out a way to have that assurance in Excalidraw.

**Describe the solution you'd like**

It would be great if Excalidraw supported some kind of "alignment guides mode", similar to what you get when resizing shapes/objects in something like Google Slides (for example). This would be real-time feedback during moving/resizing elements that would show users when:

- Elements are aligned (top, bottom, center, etc.)
- Elements have identical widths/heights (or both)

**Describe alternatives you've considered**

I've considered using other tools like Google Slides for this. Ideally I would like to use Excalidraw.

**Additional context**

Just to demonstrate, below is a video of me resizing/moving objects in Google Slides, which inspired this feature request.

https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/8128941/09af1fe7-25a4-46a3-8925-8aa27891f603

**Comment by MalysMarcin** [comment]
Hi,
I think it works very good when You press Ctr (on Windows) during drawing or moving an objects like shapes.
If this is what You need :)
Best regards
Marcin

**Comment by macintacos** [comment]
Wow, had no idea that I needed to hold a key to do that, my bad! Closing this out. If other folks stumble upon this - on the Mac, you can get guides when you hold Command.

**Comment by Today20092** [comment]
Yes, holding ctrl does allow for snapping, but it doesn't detect when you're making the length or width the same of a similar object, you have to directly put it in line with that axi

![Not Snapping](https://github.com/user-attachments/assets/0c79bf0d-1586-4095-b697-6283573c0e14)
