### ISSUE TITLE
Default width of embedded (transcluded) image, inconsistent with mobile

### ISSUE THREAD

**Issue by mdroidian** [zsviczian/obsidian-excalidraw-plugin#163]
Would it be possible to have the `Default width of embedded (transcluded) image` act the same as images, if unset?

**Describe the bug**
For example, an image will go to max width.  On my theme, it looks like that is 700 on desktop.
![image](https://user-images.githubusercontent.com/3792666/135676551-85792a93-c836-4836-994f-33ffff23f325.png)

And on mobile, it will also be max width.  But as you can see, the excalidraw will break the horizontal scroll.
![image](https://user-images.githubusercontent.com/3792666/135676872-47db5454-e66f-432a-aaae-007e15b0f658.png)

**To Reproduce**
Embed Large image, do not specify width
Embed Excalidraw, 700 width
View on mobile

**Expected behavior**
Unset the default width, and have the embedded excalidraw resize like images do

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Obsidian .v12.15, excalidraw 1.3.16

**Smartphone (please complete the following information):**
 - Device: OnePlus7T
 - OS: Android 11

**Additional context**
I guess if this is not possible, then the solution is to set the widths at the appropriate number per device. 👍

**Comment by zsviczian** [comment]
This should be possible. Never tried this scenario before, but definitely sounds doable / not that difficult. I’ll look into this. I don’t yet know how I can distinguish between mobile == tablet and mobile == phone.

**Comment by mdroidian** [comment]
> I don’t yet know how I can distinguish between mobile == tablet and mobile == phone.

Ah, I meant I could turn off the `Installed community plugins` sync, and set the widths individually on my devices.

But, maybe no distinguishing needed?  It looks like the default for images, audio, and video is just css

```css
.markdown-preview-view img:not([width]), .markdown-preview-view audio, .markdown-preview-view video {
max-width: 100%;
}
```

...

in fact, I removed the width from 
![image](https://user-images.githubusercontent.com/3792666/135698864-66d0ebdc-781a-4e16-8510-16aa65ad9712.png)

I thought it was default at 400.  But it seems it doesn't actually apply a default width in the first place.
I am sorry.  I must have missed this originally.

Because now it is acting exactly as I would like it to 😆😆

**Comment by zsviczian** [comment]
Note you can also set a percentage in the default width setting. e.g. 90% to leave a bit of a margin.
