### ISSUE TITLE
FR: When the MD file is being edited, the text appears more blurred than normal

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1645]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/3e8b381c-08c5-45c0-968a-422c879d0b3b)
In the figure, the left is the MD text edited in excalidraw, and the right is the normal text, which is much clearer than the left

**Comment by jiajiala** [comment]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/c3889a62-473c-4a69-b958-03f0fe4ad05f)
It should be the blurring effect caused by this overflow. I hope to correct this problem, which has a great impact on the editing experience

**Comment by zsviczian** [comment]
I've also noticed. This has to do with scaling. Would be great if someone with some CSS skill could debug why.

**Comment by jiajiala** [comment]
https://github.com/aptend/typing-transformer-obsidian/issues/76
I screened it. It was caused by this problem
