### ISSUE TITLE
BUG: The embedded md file, when editing, will destroy my big title

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1648]
The embedded md file, when editing, will destroy my big title, as shown in the picture, my 2222 title, when I edit the file with the 111111 title, 2222 is destroyed
![Honeycam 2024-03-17 11-34-05](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/a6a882a7-0e88-423d-a739-aaaf62d4abe0)
This will cause all my links to 2222 to be broken

**Comment by zsviczian** [comment]
can you reproduce this with Obsidian Canvas?

**Comment by jiajiala** [comment]
yes
