### ISSUE TITLE
FR: Matching autosaveInterval options or removed redundancy

### ISSUE THREAD

**Issue by orlin** [zsviczian/obsidian-excalidraw-plugin#1652]
**Is your feature request related to a problem? Please describe.**

I sync Obsidian with git and sometimes open the vault on an iPad just to read some notes rather than make changes. Because the sync options for mobile vs desktop don’t match for intervals more frequent than 60 seconds, I ended up choosing that so as to not make pointless commits. There is a short list of plugins that write to their `data.json` every time. I usually exclude such config files from the repo, but in the case of Excalidraw I’d like to keep the options in sync, though it may also be good to auto-save more often as recommended.

**Describe the solution you'd like**

Is there a reason not to save often on Desktop? Could we add to the Desktop menu options below 1 minute or otherwise make them match?

**Describe alternatives you've considered**

Perhaps a bit less efficient solution would reduce `autosaveInterval` to a function that returns the interval for the current context as needed, rather than copying the data.

**Comment by zsviczian** [comment]
fixed in 2.2.4. No more pointless commits.
