### ISSUE TITLE
MigrationPrompt.ts typo

### ISSUE THREAD

**Issue by adxsoft** [zsviczian/obsidian-excalidraw-plugin#166]
Spotted this CSS class reference error

MigrationPrompt.ts line 24 has typo

div.addClass("excalidarw-prompt-div");

should be

div.addClass("excalidraw-prompt-div");

Cheers
Allan @ adxsoft

**Comment by zsviczian** [comment]
Thanks! I corrected it in the source, but it may take 1-2 weeks until I can publish it. I've started to implement/refine the image element I'll try to hold off changes until I am able to release 1.4.0.

**Comment by zsviczian** [comment]
Solved in [1.3.17](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.3.17)
