### ISSUE TITLE
FR: The markdown table embedded in the drawing cannot be displayed correctly when re-embedded into the notes.

### ISSUE THREAD

**Issue by zhoulonghao520** [zsviczian/obsidian-excalidraw-plugin#1663]
excalidraw :2.0.25

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/144794808/6cc774fe-94b9-4fc2-8bc1-860ec547c2f3)

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/144794808/c096462e-11f7-45d1-8b60-c08bf858171a)

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/144794808/9175bf85-940a-4ca6-bff1-4d7c726d8cc0)

The markdown table embedded in the drawing cannot be displayed correctly when re-embedded into the notes.

**Comment by zsviczian** [comment]
this is a feature request. And yes, currently markdown notes are not rendered when exporting images.
If you need an image, you can take a screenshot when Excalidraw is open.

Same as #1750
