### ISSUE TITLE
FR: Cursor '+' visibility option for drawing when using a tablet

### ISSUE THREAD

**Issue by BudderMaToast** [zsviczian/obsidian-excalidraw-plugin#1673]
In the latest update the cursor '+' is now gone when drawing with a screenless tablet making it hard to know where you are writing.

It would be awesome is there is an option to enable/disable the '+' cursor when drawing.

**Comment by zsviczian** [comment]
I will add an option.

**Comment by zsviczian** [comment]
Included in 2.1.0

**Comment by BudderMaToast** [comment]
I LOVE YOU :D

**Comment by Astro1963** [comment]
I wonder if this function works only with a tablet. I have a drawing tablet connected to a PC with Windows 10, but the cursor "+" is always visible even when I draw.

**Comment by zsviczian** [comment]
did you enable show crosshair in plugin settings?

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/196e4647-900f-4bd7-9a5b-7ee3f9086972)

**Comment by Astro1963** [comment]
> did you enable show crosshair in plugin settings?
> 
> ![image](https://private-user-images.githubusercontent.com/14358394/318660520-196e4647-900f-4bd7-9a5b-7ee3f9086972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTY5NjksIm5iZiI6MTcxMjA1NjY2OSwicGF0aCI6Ii8xNDM1ODM5NC8zMTg2NjA1MjAtMTk2ZTQ2NDctOTAwZi00YmQ3LTlhNWItN2VlM2Y5MDg2OTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDExMTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxM2NkNTU1ZjU3YTVmZWJhMTg1YjkxNmNmNWExMzc5YmNlYWVlNzBlY2Q1Njg2NGNiMzQzYzk4NzRmNDA4ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EaIjFJAbDn66pHh6Hdm8uHZ0YdRCJIL-RdxZclt6ofQ)

Yes, but nothing changes, whether the option is enabled or not, the cursor "+" is always visible when I drawing

**Comment by Astro1963** [comment]
> do you see the crosshair in the same situation pen + freedraw tool on excalidraw.com?

Yes, I see the crosshair in excalidraw.com too (pen + freedraw).

**Comment by zsviczian** [comment]
#1681

**Comment by Astro1963** [comment]
![Screenshot](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/140023950/c4c1c11b-c6b2-4b7f-9c20-afc25245f882)
I set the options as in the attached image. In excalidraw, when I click on pen tools (7) the cursor "+" appears, but it doesn't disappear when I start drawing, as I would like instead.
I have a Huion k58 graphics drawing tablet connected to PC with Windows 10.

**Comment by gaspatxo** [comment]
Thank you so much for this. Could this option perhaps be enabled by default?
