### ISSUE TITLE
FR: set a default drawing view when opening a file

### ISSUE THREAD

**Issue by PaoEsc** [zsviczian/obsidian-excalidraw-plugin#1675]
I have one excalidraw file quite big with mostly vertical drawings, when opening the file I get a zoomed out view of the center of the drawing. I would like to open it with the last view settings maybe, or set a default place to view when open it or open it in the last view.

**Comment by zsviczian** [comment]
you can control this with zoom settings under Excalidraw Appearance and Behvior

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/827df9e4-3a97-4da5-a770-aefb23a77f4f)
