### ISSUE TITLE
FR: Onyx Boox handwriting optimization

### ISSUE THREAD

**Issue by altwayme** [zsviczian/obsidian-excalidraw-plugin#1677]
**Is your feature request related to a problem? Please describe.**
I use Onyx Boox e-ink tablet and there is high latency when using Excalidraw in Obsidian.

**Describe the solution you'd like**
There is a way to manually add handwriting optimization with editing a specific system file with root access.  This is the article which describes the process:
https://gist.github.com/calliecameron/b3c62c601d255630468bd493380e3b7e

The problem which I have faced is that I need drawViewKey which would target a specific class related to drawing. 
For apps you can find by extracting apk, decomposing it and finding right xml. 4 options were found:

Ibis Paint: jp.ne.ibis.ibispaintx.app.glwtk.IbisPaintView
MediBang Paint: com.medibang.android.paint.tablet.ui.widget.CanvasView
Squid: com.steadfastinnovation.android.projectpapyrus.ui.widget.PageViewContainer
Xodo: com.pdftron.pdf.PDFViewCtrl

Exalidraw is a plugin and not standalone app, which could be analyzed in this way. I would greatly appreciate if you would able to help with finding the right drawViewKey.

**Comment by zsviczian** [comment]
I am afraid this sounds mission impossible. Excalidraw runs inside the Obsidian APK inside an Android WebView component on your Onyx. I don't see how this can be solved. Sorry...

**Comment by EmileHanau** [comment]
@altwayme could you try `android.webkit.WebView`?

**Comment by pstjohn** [comment]
in case anyone's interested: https://github.com/pstjohn/BooxDraw
