### ISSUE TITLE
BUG: pen cursor in excalidraw obsidian disappears with pen tool

### ISSUE THREAD

**Issue by roycordero** [zsviczian/obsidian-excalidraw-plugin#1681]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.16
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Things v2.1.20
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 13
	Plugins enabled: 12
		1: Excalidraw v2.0.26
		2: Kanban v1.5.3
		3: Mind Map v1.1.0
		4: Calibre v1.0.8
		5: Quick Plugin Switcher v8.0.0
		6: ReadItLater v0.4.0
		7: Mousewheel Image zoom v1.0.22
		8: Pomodoro Timer v1.2.0
		9: Dataview v0.5.66
		10: Tag Wrangler v0.6.1
		11: Google Calendar v1.10.14
		12: Raindrop Highlights v0.0.20

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**

when I use the pen with my device (gaomon S620 driver version v16.0.0.37 (latest version)) and I choose the pen tool the pen pointer "the cross" disappears and is not seen on the screen, it writes and it works but is not seen the pointer "the cross", but using the mouse yes it appears the pointer "the cross" but with the pen and in the pen tool is not seen....

**To Reproduce**
1. Go to 'excalidraw obsidian'
2. Click on 'pen tool (7)'
3. Scroll down to 'canvas using the pen of the gaomon S620'
4. See error "no appear the pointer, "the cross" or anithing else

**Expected behavior**

"I want to be able to use my gaomon S620 device in excalidraw in obsidian just like I use it in excalidraw WEB without any problem".

**Screenshots**
[img]https://i.imgur.com/6XmdVoV.jpg[/img]

**Additional context**
nothing else

**Comment by zsviczian** [comment]
You can enable the crosshair for pen in settings.
There was a feature request from some users to hide the crosshair. Seems this was a misjudgment on my side that everyone will want the crosshair gone...

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/50f8ea63-5d31-42e5-9831-9852068f4418)

**Comment by roycordero** [comment]
yeah! thanks its working now! :) thanks!

aaa ok I get it...

well I think the problem the people have with the cursor is that it is very ugly and big that's why I have seen that many people don't like it, I think it could be fixed not so much as disappearing the cursor which I don't think is the right thing to do. because you can't even see where the cursor is to be able to use it, but I do think it can be fixed by changing the crosshair because it is very big, thick and ugly and changing it to a smaller and thinner 'stylized' cursor that is not so thick so that it is more accurate or just a cleaner and more accurate arrow I believe that...

**Comment by zsviczian** [comment]
Yes, it is ugly. If someone can propose a nicer one that would be great.
Also, this request has now been raised at least 5 times in different channels... I wish people would read the release notes. I put lots of effort in trying to document releases. Every minute I spend responding to questions that are already addressed in the Release notes takes away time from improving the plugin...

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/9fb040dc-c9de-47c4-8405-21fe20687ccb)

**Comment by zsviczian** [comment]
my takeaway about fiddling with the crosshair... is to not touch it any more. I under estimated how important the crosshair is to people :)

**Comment by n30s4m** [comment]
I have a solution! 

I use a Wacom Intuos CTL-4100 and I was unable to see the cursor when I tried to operate the pen. To solve it, I went into the pen settings in the pen program and changed some settings. 

1. I added the Obsidian program.

2.In options, pen button mode, I chose click and tap.

3.I enabled pressure compatibility.

Now, i see the pointer.

**Comment by zsviczian** [comment]
@n30s4m, thank you for sharing. I published your solution on the Wiki: https://excalidraw-obsidian.online/wiki/pen-issues

**Comment by gerroon** [comment]
How did you enable the pressure mode in Excalidraw?

> 
> 2.In options, pen button mode, I chose click and tap.
> 
> 3.I enabled pressure compatibility.
> 
> Now, i see the crosshair.
