### ISSUE TITLE
FR: Writing in back of drawing and Obsidian Publish

### ISSUE THREAD

**Issue by devinat1** [zsviczian/obsidian-excalidraw-plugin#1682]
**Is your feature request related to a problem? Please describe.**
If I am to use an Excalidraw file for all my note creation purposes, I would ideally like to be able to publish the back of these notes as is without seeing the Excalidraw metadata (just the parts I wrote).

**Describe the solution you'd like**
Have a way to hide metadata altogether (perhaps by having a separate document for metadata that is not tied to the file, though I am not sure how this can be accomplished fullly).

**Describe alternatives you've considered**
Currently, I can embed an Excalidraw drawing to a different note and have that save as an SVG in which I then publish that note with the embedde document inside.

**Comment by zsviczian** [comment]
Simply add %% above text elements

```markdown
your note....

%%
# Text Elements
....
```
