### ISSUE TITLE
BUG: Cursor don't show up

### ISSUE THREAD

**Issue by picassothought** [zsviczian/obsidian-excalidraw-plugin#1685]
**My environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.8
	Operating system: Windows 10 Pro 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Big Sur Aesthetic v0.0.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 1
		1: Excalidraw v2.1.1
**The bug:**
Cursor doesn't show up in the drawing with the pen mode using tablet pen.

**To Reproduce**
1. Go to new drawing
2. Click on pen
3. Try to draw something

**Expected behavior**
The cursor is seen when drawing using tablet pen (it works just fine in the web version).

**Additional context**
I use wacom one tablet for drawing.

**Comment by FamedBear16** [comment]
HI,
This is a big problem for me too. it basically makes Excalidraw not usable for me! Is there any way to revert to the old version while this gets fixed?

**Comment by zsviczian** [comment]
Is this not working? I tested this with both of my Huion Kanvas and my Windows stylus and it works as expected.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/ded075e3-8cb8-4de3-8420-eb5b8f1c9fb8)

I encourage reading the release notes. It is documented there.

**Comment by zsviczian** [comment]
same as #1681
