### ISSUE TITLE
FR: Restore "+" while drawing on a pc screen and using a tablet

### ISSUE THREAD

**Issue by FamedBear16** [zsviczian/obsidian-excalidraw-plugin#1689]
**Is your feature request related to a problem? Please describe.**
In the last version you removed the "+" cursor when drawing with a pen. This make Exalidraw drawing not usable when usign a wacaom like pen tablet

**Describe the solution you'd like**
To restore the previous behaviour.

**Describe alternatives you've considered**
1. Restore the previous versoni
2. An option in setting to make it visible

**Additional context**

**Comment by zsviczian** [comment]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/d70d3e51-4fbe-480c-88d8-838912234636)

**Comment by zsviczian** [comment]
Same as #1861
