### ISSUE TITLE
FR: Support for deep linking for PDF++ plugins

### ISSUE THREAD

**Issue by Dennyyusuf** [zsviczian/obsidian-excalidraw-plugin#1692]
**Is your feature request related to a problem? Please describe.**
It would be great for visual note taker to be able to visualize our pdf highlight into Excalidraw, and it is possible with PDF++ plugin and Excalidraw.

**Describe the solution you'd like**
It would be great to have a deep linking when annotating pdf file with using PDF++ plugin, I have discussed with PDF++ creator here (https://github.com/RyotaUshio/obsidian-pdf-plus/issues/138)

**Additional context**

https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/65077044/e79f4134-641c-4ae3-b0b0-1498697b7c6f

**Comment by Rex-Diego** [comment]
Thanks for open this FR! Finally, 
I'm not the only person who want to use PDF++ and Excalidraw in this way. It will be awesome if this problem can be solved!

**Comment by Dennyyusuf** [comment]
> Thanks for open this FR! Finally, I'm not the only person who want to use PDF++ and Excalidraw in this way. It will be awesome if this problem can be solved!

Yes, Hopefully Mr. Zsolt is willing to take a look and give comment.

Finger crossed.

Cheers,
Denny

**Comment by zsviczian** [comment]
I think I addressed these requirements. Please open a new FR if you have further ideas for PDF integration.
