### ISSUE TITLE
BUG: The image in the MD file is always at the top

### ISSUE THREAD

**Issue by arias007** [zsviczian/obsidian-excalidraw-plugin#1699]
![屏幕截图(79)](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/90596315/671e8f38-b944-4a41-8a5f-8190d8301428)

**Comment by zsviczian** [comment]
Unfortunately, this is not a bug, but a "feature". This is a side-effect of how interactive frames are implemented. Given the technical background to all this, I don't see this being solved any time soon (ever, really - but never say never.

**Comment by arias007** [comment]
Thank you.The latest version of the json file is still 12, not updated to 13



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 6, 2024 22:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zsviczian/obsidian-excalidraw-plugin] BUG: The image in the MDfile is always at the top (Issue #1699)




 
Unfortunately, this is not a bug, but a "feature". This is a side-effect of how interactive frames are implemented. Given the technical background to all this, I don't see this being solved any time soon (ever, really - but never say never.
