### ISSUE TITLE
Wanna cooperate with you to create similar plugin for my mindmapping and diagramming service

### ISSUE THREAD

**Issue by assopri** [zsviczian/obsidian-excalidraw-plugin#17]
Hello! I'm building mindmapping and diagramming service https://app.mentalmaster.net . A short intro on its work available here   https://www.youtube.com/watch?v=SaPoyYcPhcA . I want to wrap it into the Obsidian plugin in the same way you`ve done with Excalidraw. I wanted to discuss the ways we could cooperate. How can we get in touch?

**Comment by zsviczian** [comment]
Sure, happy to help. Proper mindmapping in obsidian would be nice.
Is mentalmaster a React component?
Probably best first step is for you to review my code for excalidraw... then we can discuss if you have any questions.

Best way to discuss would be to connect on discord. I can't find you on the OMG server searching for assopri. Are you on OMG discord?

**Comment by zsviczian** [comment]
This is not an Excalidraw issue. Handling it further offline.
