### ISSUE TITLE
BUG: Option "CTRL+CLICK on text with [[links]] or [](links) to open them" is not working properly

### ISSUE THREAD

**Issue by FancyBEAST** [zsviczian/obsidian-excalidraw-plugin#1704]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.11
	Operating system: Windows 10 Home Single Language 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.1.3

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
The option "CTRL+CLICK on text with [[links]] or [](links) to open them" is supposed to disable Ctrl+Click on text/shape from opening the link. But even if disabled Ctrl+Click still opens the link which conflicts with Ctrl+Click to select and object inside a group.

**To Reproduce**
1. Create a Text or shape
2. Add a link to it (Ctrl+K)
3. Ctrl+Click on the shape/ Text

**Expected behavior**
Ctrl+Click on text/shape should be disabled

**Additional context**
All other settings are default except "CTRL+CLICK on text with [[links]] or [](links) to open them" which is turned off

**Comment by zsviczian** [comment]
Fixed in 2.1.4
