### ISSUE TITLE
BUG: Markdown not rendered in reading mode of hybrid excalidraw/markdown note.

### ISSUE THREAD

**Issue by 0phoff** [zsviczian/obsidian-excalidraw-plugin#1705]
<details>
<summary><b>Your environment</b></summary>

```
Obsidian version: v1.5.12
Installer version: v1.5.12
Operating system: #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 6.5.0-26-generic
Login status: not logged in
Insider build toggle: off
Live preview: on
Base theme: dark
Community theme: Minimal v7.2.1
Snippets enabled: 12
Restricted mode: off
Plugins installed: 16
Plugins enabled: 15
  1: Custom File Explorer sorting v2.1.8
  2: Dataview v0.5.65
  3: Minimal Theme Settings v7.3.1
  4: SideToggleCommand v1.0.0
  5: Templater v2.2.3
  6: Style Settings v1.0.8
  7: Recent Files v1.3.10
  8: Settings Search v1.3.10
  9: Tag Wrangler v0.6.1
  10: Iconize v2.11.5
  11: Text Format v3.0.1
  12: Janitor v1.0.7
  13: Homepage v3.8.0
  14: Excalidraw v2.1.1
  15: Creases v0.7.0
```

</details>

**Describe the bug**
When converting an existing markdown note to an excalidraw file, the reading mode stops working.
I would assume the reading mode still shows the original markdown file, but it instead only shows the excalidraw drawing.

**To Reproduce**
1. Open a markdown file with content
2. Run `Command Palette/Excalidraw: Convert markdown note to Excalidraw Drawing`
3. Open the file as markdown
4. Open the reading view

**Additional context**
I imagine this behaviour is logical, as this was the intended behviour for embedding the note in other markdown files, where you want the drawing to show up as an image.

A potential solution for this issue would be to set a YAML tag that tells the system this is a hybrid note. 
- When viewing the hybrid note in reading mode, you show the markdown content.
- When embedding the hybrid note, you show the markdown content, unless you specifically reference the `# Drawing` header (or another block if that's easier to code).

One additional issue to solve would then be to hide the `# Text Elements` content in reading mode (and potentially in the live preview mode).
Nonetheless, I think that even without this final fix (where the Text Elements are still visible in the markdown reading mode) it will be very usefull for people.

---

**Background**  
When I saw the "back of the note" concept, my mind jumped straight to a use case where I write normal markdown. If I then need an image or diagram, I can flip the page, create the diagram, go back to markdown and insert the drawing I just created as a group link on the page.  
However, for this to work it is imperative that I can view the markdown files in reading mode!

Sorry if this issue has already been reported, but I could not find it anywhere, except for a random youtube comment mentioning it in one of your videos.

**Comment by zsviczian** [comment]
fixed in 2.1.4 (includes 2 related new settings, one setting under appearance and behavior, the other under Export settings)

**Comment by zsviczian** [comment]
partially addressed. I have/will not address the part suggesting that referencing the # Drawing section should embed the drawing as technically there is no difference between "hybrid" notes and drawings. Every Excalidraw drawing is a "hybrid"... just sometimes you make use of the backside, at other times not. 
A drawing will embed as a drawing unless you reference a markdown section on the back side.

**Comment by 0phoff** [comment]
Thanks! I thought I had the latest version but it seems I have not... 🫣

I have no problems with your embedding solution. I think it would be very rare for me to need to embed the entire markdown content of a hybrid note, so embedding specific blocks/sections works out fine for me!

Thanks a lot for your work on this amazing plugin! I am dipping my toes into the world of visual PKM in the hopes of retaining and finding my information faster, and your plugin is the perfect gateway for this 😉
