### ISSUE TITLE
FR: enable manual view mode in markdown files that have excalidraw drawing metadata

### ISSUE THREAD

**Issue by UhlKlaus** [zsviczian/obsidian-excalidraw-plugin#1706]
**Is your feature request related to a problem? Please describe.**
I was eager to try out the new feature to convert any markdown note into an excalidraw drawing to utilize "both sides of the card". 🙂 
I do have an issue though. I do not use the live preview mode of Obsidian but instead switch between view-mode and edit-mode with a hotkey. When I convert any markdown note to an excalidraw drawing this embeds all excalidraw relevant metadata as expected and I can draw. When I look at the markdown I can see everything I expect (see screenshot), but when I use. my hotkey to switch to view-mode I only see the drawing (see other screenshot). I would assume that I see the rendered markdown and that I can of course embed the drawing into it.

**Describe the solution you'd like**
The markdown view mode should work just fine, best case would be to not show the excalidraw metadata. The drawing itself could get embedded with standard procedures if wanted. 

<img width="900" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/132888319/46613e3a-eb3f-4629-be4a-7902371152c5">
<img width="900" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/132888319/3faee9f2-3e0e-4b64-9f51-30120b078ad9">

**Comment by zsviczian** [comment]
I added a setting under "Appearance and Behavior" in 2.1.4. By default, markdown reading mode will display the markdown document.
