### ISSUE TITLE
BUG: Aspect Ratio of an Excalidraw Embedded in Another Excalidraw not updated

### ISSUE THREAD

**Issue by Cabjhegas** [zsviczian/obsidian-excalidraw-plugin#1707]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.3
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 9
	Plugins enabled: 7
		1: Kanban v1.5.3
		2: Calendar v1.5.10
		3: Imgur v2.5.2
		4: Excalidraw v2.1.3
		5: Git v2.24.1
		6: Iconize v2.11.9
		7: Minimal Theme Settings v7.5.0

**Describe the bug**
If an Excalidraw X is embedded in another Excalidraw Y, and you subsequently alter Excalidraw X (changing its aspect ratio), it will be displayed distorted in Excalidraw Y.

**To Reproduce**
    1. Create an Excalidraw X.
    2. Create an Excalidraw Y and embed Excalidraw X into it.
    3. Alter Excalidraw X so that its aspect ratio is changed.
    4. Verify that it appears distorted in Excalidraw Y.

**Expected behavior**
The version of Excalidraw X embedded in Excalidraw Y needs to be updated, correcting its aspect ratio if necessary.

**Screenshots**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/26459442/21d89852-9873-4c40-863d-43d46ad00656)

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/26459442/c6797867-5b0d-4d7c-b16f-152de3e3e770)

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/26459442/c2f143dc-cffd-4447-84c5-33445658c7c1)

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/26459442/cea92967-16e2-486c-9793-d5bd1775cb8d)

**Additional context**
If you use the Excalidraw X exported as SVG, any subsequent changes to it will correctly update its display in Excalidraw Y. However, it would be beneficial for the same to occur if you embed the ExcalidrawX.md.

**Comment by Cabjhegas** [comment]
Thanks for the awesome plugin!

**Comment by zsviczian** [comment]
Fixed in 2.1.4. Will release over the WE.
