### ISSUE TITLE
BUG: Old files not working 

### ISSUE THREAD

**Issue by AbdulrahmanElshafie** [zsviczian/obsidian-excalidraw-plugin#1708]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.16
	Operating system: Windows 10 Home Single Language 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 10
	Plugins enabled: 9
		1: Advanced Tables v0.21.0
		2: Link Embed v2.0.12
		3: RTL Support v1.2.1
		4: Various Complements v9.4.0
		5: Google Calendar v1.10.14
		6: Google Keep Import v1.1.3
		7: Excalidraw v2.1.3
		8: Tldraw v1.0.5
		9: Custom Frames v2.4.7

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
I updated the plugin to its latest version a few days ago, when I did so most of my old drawings weren't opening. I get an error message telling me that 'error loading drawing' and then telling me about an error in the JSON code, however, I've not made any edits to it, I'm just using the drawing tools without editing anything. I tried to disable the themes I installed and some plugins to see if there was some conflict but didn't find any solution.

**To Reproduce**
1. Go to an old file
2. Open it, it will open on the markdown not the drawing with the error message 
3. You can to right click in the file and choose open as drawing to see the error message again (sometimes the file open and sometimes not)

**Expected behavior**
I want to be able to use my previous drawing normally as I used to without encountering this issue

**Screenshots**
error message sample:
![Screenshot 2024-04-11 223616](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/101133020/f9cd074d-53a1-4c22-a25c-6172982ae864)

**Additional context**
file for the previous message 
[Plan for ML courses.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/14951157/Plan.for.ML.courses.md)

**Comment by zsviczian** [comment]
This is not a question of Excalidraw file version. 
From the looks of it, it seems as if another plugin automatically edited numbers in the markdown file.  All the numbers are crippled:
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/80e295e1-8513-4272-a9ca-e1baa8022571)

**Comment by zsviczian** [comment]
here's the fixed file:
[Plan.for.ML.courses.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/14955397/Plan.for.ML.courses.md)

My recommendation is to avoid all plugins that automatically modify large volume of files (such as add timestamps or other...)

To fix the file I ran this regular expression search and replace using the [regexp-replace](https://github.com/Gru80/obsidian-regex-replace) Obsidian plugin. If other files are effected you can do the same with them and hopefully they will also be fixed.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/ae58f3cd-2f6f-4b03-b850-00b8fbec5171)

**Comment by AbdulrahmanElshafie** [comment]
The issue is fixed, thank you so much for the help!
I don't know how this happened to the numbers but I'll try to be more careful next time. 

Thanks again.
