### ISSUE TITLE
FR: Embed Scene in PNG/SVG Exports

### ISSUE THREAD

**Issue by asford** [zsviczian/obsidian-excalidraw-plugin#1709]
**Is your feature request related to a problem? Please describe.**

I use Obsidian-Excalidraw to keep a running notebook of technical work,
and auto-export `.png` diagrams so I can easily share and embed these diagrams in docs/github/etc...

The auto-exported images don't currently embed exalidraw metadata,
so the images can't be re-opened in excalidraw, vscode-excalidraw or obsidian-excalidraw.

**Describe the solution you'd like**

It would be ideal to always embed the excalidraw scene in png and svg auto exports,
or (at least) provide an option to enable excalidraw scene embeds for all exports.

It would simplest to just globally enable scene embeds at:

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/b7652a41f8e15f78f3b401354c6fbf81464f61d4/src/ExcalidrawView.ts#L722-L733

However, we could also add a setting if there's a specific reason to embeds aren't desired.

**Describe alternatives you've considered**

The manual export dialog supports embeds, so I could always manually export,
but the auto-export feature is *really* useful to be able to easily embed diagrams from a shared drive.

**Additional context**

Happy to open a PR if you're 👍 on the feature.

**Comment by zsviczian** [comment]
Good point. I will add a frontmatter tag to control this.

**Comment by zsviczian** [comment]
implemented in 2.1.4

**Comment by asford** [comment]
Thank you, really appreciate the work and plugin!
