### ISSUE TITLE
BUG: OCR not working on Android

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#1710]
likely the same issue as was with OpenAI JSON

**Comment by zsviczian** [comment]
fixed in 2.1.4

**Comment by missmashing** [comment]
OCR doesn't work for me. But I am new to Obsidian and might be doing something wrong. Just don't know whom and where to ask. settings of Excalidraw are set as per tutorial... I really hope for some reply as this is the main feature I need in Obsidian in general. Thank You
