### ISSUE TITLE
FR: Include markdown card as text in exporte drawing as SVG / PNG 

### ISSUE THREAD

**Issue by TaylorSasser** [zsviczian/obsidian-excalidraw-plugin#1717]
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: Windows 10 Pro 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.1.3

Excalidraw Settings (that might be the problem):
      Image Type in Markdown Preview:  Native SVG
      Type of File to insert into Document: Excalidraw
      Embed using Wiki Link: True
      Immersive Embedding: True,
      Image Caching: True
      Keep .SVG and or  .PNG filenames in sync:  True
      Auto Export SVG: True

**Describe the bug**
Exporting with inline markdown inside of excalidraw drawing. Could be user error and not bug

**To Reproduce**
1. Create an excalidraw drawing
2. Open drawing as markdown
3. Add some text to markdown like so

```
# Introduction
---- 

- Bullet Point one!
- Bullet point two!
- Bullet point three!

> Wow!, Some indented text!
> This is amazing!
```

4. Switch back to drawing mode, then right click to add back of note card
5. Link back of note card to Text added in markdown (In this case the #introduction)
6. Export the drawing
	

**Expected behavior**
The exported drawing displays links to files in obsidian vault, instead of what is rendered in obsidian

**Screenshots**
![Rendered](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/19296240/4488a5c6-9f84-4e94-9d84-559b0a1f44d8)
![Exported](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/19296240/e302ea45-00dd-45f6-bba5-28a4763186c9)

**Additional context**
A MVCE:
[Poster.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/14968842/Poster.excalidraw.md)

**Comment by zsviczian** [comment]
same as #1750
