### ISSUE TITLE
Adding new line between ``` and %%, in the markdown.

### ISSUE THREAD

**Issue by cristianvasquez** [zsviczian/obsidian-excalidraw-plugin#172]
**Is your feature request related to a problem? Please describe.**

First of all, I thank you for this plugin! :)

A detail that could be fixed: 

The drawing data is stored in code fences, using JSON syntax.  I love this approach, but it seems that the closing the fence (\`\`\`) is besides an obsidian comment (```%%) 
 
<img width="862" alt="image" src="https://user-images.githubusercontent.com/361916/135848313-121b5986-e30e-4df6-b6fa-000239d6495b.png">

This makes the markdown difficult to parse by some markdown libraries. 

**Describe the solution you'd like**

To add a new line (\n) after the end of the fence.

%% 

```
Data
```
%%

Cheers!

**Describe alternatives you've considered**

**Additional context**

**Comment by zsviczian** [comment]
Thanks for raising this, I was not aware this is an issue for markdown parsers. I'll change it.

**Comment by cristianvasquez** [comment]
Hi! Thanks for changing this :)

Question: I noticed that the JSON is not found anymore when I add a \n after the #drawing header, and the drawing is not displayed. Looking into the code and I found the pattern that fetches the JSON:

./ExcalidrawData.ts

```javascript
const DRAWING_REG = /\n%%\n# Drawing\n(```json\n)(.*)\n```%%/gm;
const DRAWING_REG_FALLBACK = /\n# Drawing\n(```json\n)?(.*)(```)?(%%)?/gm;
```
I was thinking about relaxing the pattern to fetch the first ```json fence that it finds. 

However, I wonder what would be a  future-proof pattern/mechanism to fetch such Excalidraw JSONs. What about a unique name for the code fences, something along the lines 'excalidraw' or 'json/excalidraw' (like plantuml does). A fence would allow us to distinguish Excalidraw drawing without depending on the # Drawing header. It would also be a bit clearer how to export to HTML, for example.   

Does that make sense?
