### ISSUE TITLE
FR: Switch to automatic LaTeX compiling in all text cells

### ISSUE THREAD

**Issue by denisgorod** [zsviczian/obsidian-excalidraw-plugin#1720]
**Is your feature request related to a problem? Please describe.**
Most of my work in Obsidian Excalidraw is writing math. It is quite time-consuming to align and enter each individual LaTeX formula whenever I need to use one in a text cell. I understand that the Excalidraw API does not allow for a painless inclusion of LaTeX support (or, more precisely, MathJax), but I have a suggestion that might work.

**Describe the solution you'd like**
I propose to add a "Math" switch that would work in the following way:
- whenever the switch is on, any created text field is considered to be LaTeX and is rendered through the "Insert LaTeX formula" wonderful option; one would still have to use stuff like \text in LaTeX to properly render text and equations, but this is easier than aligning each individual symbol (like math notations) within a body of text.
- whenever the switch is off, this shouldn't undo the fields that were previously compiled as MathJax.

I am not sure if this can be implemented easily enough, but that most definitely would be a serious quality of life feature for me individually.

**Comment by zsviczian** [comment]
Why don't you add an obsidian hotkey to the insert latex formula action?
That would make it quicker to add formulas.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/42b2380a-ca0e-42e1-9887-27bf28fbf876)

**Comment by xjtusjtu** [comment]
I understand [denisgorod](https://github.com/denisgorod)'s idea, what he's trying to accomplish is to type `this is a formula $x+y$` into any textbox, and press a switch that causes that textbox to automatically render the formula in it, like https://math.preview.excalidraw.com does (https://github.com/excalidraw/excalidraw/issues/1176)

Currently the plugin works with `this is a formula` and `x+y` inserted separately, hopefully it will be possible to support mixed text input as well on top of that!

![image](https://github.com/user-attachments/assets/aa7bf797-0dd9-4b7c-aa16-42ede49fec41)

⬇️

![image](https://github.com/user-attachments/assets/61b2591c-8824-4b28-9e79-a47948d65228)

**Comment by zsviczian** [comment]
I am aware of the MathJax Excalidraw fork and I am not planning to bring it over to Obsidian, nor plan to spend much time on the LaTeX feature altogether. I think the current solution is good enough. You can insert, edit, copy LaTeX formulas, and on the back end the current approach is causing minimal amount of overhead effort for me whenever a new Excalidraw update is published. Also, with the current approach you can copy your formulas to Excalidraw.com to share with others. So, until there is out of the box LaTeX support on excalidraw.com the current approach will remain in Obsidian.

**Comment by xjtusjtu** [comment]
I get it. Thanks again for all you do.

> I am aware of the MathJax Excalidraw fork and I am not planning to bring it over to Obsidian, nor plan to spend much time on the LaTeX feature altogether. I think the current solution is good enough. You can insert, edit, copy LaTeX formulas, and on the back end the current approach is causing minimal amount of overhead effort for me whenever a new Excalidraw update is published. Also, with the current approach you can copy your formulas to Excalidraw.com to share with others. So, until there is out of the box LaTeX support on excalidraw.com the current approach will remain in Obsidian.

**Comment by diego898** [comment]
Just found this - personally, the math.preview.excalidraw approach is more useful as the latex remains text/editable. 

~~Currently, it becomes a flat image and is not editable.~~

~~I understand what @zsviczian said about not supporting this - just noting down this limitation explicitly here for others who come across this issue.~~

Thanks!

EDIT: This is wrong! Thanks @denisgorod

**Comment by denisgorod** [comment]
@diego898 It is editable: Ctrl+click the image to edit the LaTeX code.
