### ISSUE TITLE
BUG: When copying content, if there is embedded content, it will cause other parts of the text to be copied twice

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1723]
![Honeycam 2024-04-17 07-21-13](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/141d955e-9b34-4e1e-b784-ad5220e096b4)
As shown in the figure, there is an extra test when copying
An error is bound to occur whenever there is an embedded module in the copied content

**Comment by zsviczian** [comment]
this was fixed in 2.1.5
