### ISSUE TITLE
BUG: editing an existing LaTeX formula causes it to render incorrectly

### ISSUE THREAD

**Issue by yuvve** [zsviczian/obsidian-excalidraw-plugin#1724]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: Windows 10 Home 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.1.4

**Describe the bug**
Editing an existing LaTeX formula causes it to render incorrectly. It looks like the letters are stretched or compressed to fit inside the formula "box", instead of the box itself resizing. The letters then stay incorrectly rendered no matter how you resize the box.

**To Reproduce**
1. Add a new LaTeX formula to any drawing
2. Ctrl + click the formula to edit it
3. Change it to something longer or shorter

**Expected behavior**
Either the box or the letters should be resized (but not stretched or compressed), and resizing the box afterwards should work properly. Personally I would prefer the box resizing and the letter size being constant.

**Screenshots**
Here I started with `x=\text{before (no change)}`, then created two identical expressions (did not copy the existing one) and edited one of them to a shorter expression and the other to a longer expression. This problem happens even if you don't use `\text` inside LaTeX, just in case you wonder.

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/37124628/6171fc97-5ae4-48c3-aa01-63f87f70845b)

**Comment by zsviczian** [comment]
fixed in 2.1.6
