### ISSUE TITLE
BUG: Embedded content, which produces errors when the compilation is made, causes the entire embedding to collapse

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1726]
![Honeycam 2024-04-19 06-46-01](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/95900deb-86a9-4c91-b12e-d1b27bd09b68)
As shown in the figure, the eeee insert block collapsed when 11111 was entered under xxxxx
This is a BUG that is bound to happen
This will cause incorrect rollback problems

The reproduction method is shown in the figure

**Comment by zsviczian** [comment]
leave an empty row after 11111 under xxxxx

your example does not follow proper Markdown rules.

**Comment by jiajiala** [comment]
@zsviczian 
![Honeycam 2024-04-20 06-32-37](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/4ab5c0fe-bd53-486c-b9b4-e347fab22451)
Following the correct Markdown will still cause an error
