### ISSUE TITLE
BUG: Cursor disappears when using pen pad(drawing pad). 

### ISSUE THREAD

**Issue by HeisSteve** [zsviczian/obsidian-excalidraw-plugin#1727]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.3
	Operating system: Windows 10 Home 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 8
		1: Annotator v0.2.11
		2: Minimal Theme Settings v7.5.0
		3: Dataview v0.5.66
		4: DB Folder v3.5.1
		5: QuickAdd v1.8.1
		6: Style Settings v1.0.8
		7: Excalidraw v2.1.4
		8: Iconize v2.11.12

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
when using the drawing pad, the Cursor is invisible. 
However, when I Switch to using mouse, It normal again. 

**To Reproduce**
1. Use a Drawing pad

**Expected behavior**
able to see the cursor.

**Comment by zsviczian** [comment]
I am sorry, but I will be a little blunt in my response. Please help me by searching the issue log for similar issues and reading the plugin release notes. It is all documented there. This is at least the 10th time this question has come up, and it does not help my time management and motivation to support this plugin if I answer the same question 10 times...

search for crosshair 

<img width="1272" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/d50b8bcf-19de-4381-80d6-0af72158632b">
