### ISSUE TITLE
FR: better custom theme support for embedded markdown notes

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1728]
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/2dbdb85e-66f4-4fc0-a0ec-05ab5f7cd4cf)
As shown in the figure, when embedding the article, H1~4 will lose color, and H5~6 is correct

**Comment by zsviczian** [comment]
This is likely something you need to raise with the developer of the custom CSS/theme you are using. 
The way markdown is embedded in Excalidraw is slightly different from other parts of Obsidian. I did not aim for 100% match, just a good enough 80%.

**Comment by jiajiala** [comment]
@zsviczian     
Isn't H1-4 defined by excalidraw? Isn't it just necessary to let excalidraw not define these four values and directly use obsidian's own css?
More I do not understand, really hope can support obsidian in the belt css system

**Comment by zsviczian** [comment]
I am using gruvbox theme. It works as expected. You will need to consult with the Theme developer.
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/53c6637c-b197-4c72-bb67-9e17f3781c16)
