### ISSUE TITLE
FR: Save settings like show grid or snap to objects

### ISSUE THREAD

**Issue by ramarivera** [zsviczian/obsidian-excalidraw-plugin#1732]
**Is your feature request related to a problem? Please describe.**
Every time I open a drawing I need to set back the `snap to objects` mode because it is not saved.

**Describe the solution you'd like**
Maybe a per drawing setting?
Or a default mode for all drawings?

**Comment by zsviczian** [comment]
Excellent point!  It will work just as show grid and other settings. You'll be able to set snap to objects in your template.
I'll add this to 2.1.5
