### ISSUE TITLE
BUG:  Performance drop when using markdown mode of an obsidian excalidraw drawing

### ISSUE THREAD

**Issue by ramarivera** [zsviczian/obsidian-excalidraw-plugin#1733]
**Your environment**
```
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 22.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: AnuPpuccin v1.4.5
	Snippets enabled: 9
	Restricted mode: off
	Plugins installed: 70
	Plugins enabled: 50
		1: Tracker v1.13.3
		2: Text Generator v0.7.11
		3: Templater v2.2.3
		4: Tasks v7.0.0
		5: Style Settings v1.0.8
		6: Spaced Repetition v1.12.3
		7: Show Current File Path v0.5.2
		8: Settings Search v1.3.10
		9: Advanced Tables v0.21.0
		10: Annotator v0.2.11
		11: Book Search v0.6.3
		12: Calendar v1.5.10
		13: Colorful Tag v1.3.2
		14: CustomJS v1.0.19
		15: Dataview v0.5.66
		16: Emoji Toolbar v0.4.1
		17: Emotion Picker v1.0.2
		18: Iconize v2.11.12
		19: Meta Bind v1.1.0
		20: Natural Language Dates v0.6.2
		21: Omnivore v1.10.1
		22: Periodic Notes v0.0.17
		23: Quick Switcher++ v4.1.0
		24: QuickAdd v1.8.1
		25: ReadItLater v0.4.0
		26: Recent Files v1.3.10
		27: Update modified date v1.3.2
		28: Linter v1.23.2
		29: Enhancing Export v1.10.4
		30: Paste URL into selection v1.7.0
		31: Kanban v1.5.3
		32: BRAT v1.0.1
		33: CSS Editor v1.1.0
		34: Shell commands v0.21.0
		35: Banners v2.0.5-beta
		36: PARA Toolkit v1.0.0
		37: Modal forms v1.40.2
		38: Folder notes v1.7.20
		39: Pane Relief v0.5.3
		40: Buttons v0.5.1
		41: Local Images Plus v0.15.9
		42: Admonition v10.2.0
		43: Excalidraw v2.1.4
		44: Sortable v0.3.1
		45: Meld Encrypt v2.3.7
		46: Hot Reload v0.1.10
		47: Johnny Decimal v1.1.0
		48: Image Toolkit v1.4.1
		49: Obsidian Columns v1.5.2
		50: Readwise Official v2.0.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Describe the bug**
When using markdown notes as excalidraw drawings, and switching back and forth, I noticed that:
- sometimes there is issues with panning and zooming in drawing mode
- Typing in markdown mode is quite slow, each keydown and keyup event handler is taking almost 100ms to execute

**To Reproduce**
- Create an excalidraw drawing
- Fill it with some meaningful content
- Switch to markdown mode
- Try to type in markdown mode, it should be a bit slower than usual

**Expected behavior**
- Either a way to increase performance on my notes by doing some action on my side
- or a fix on excalidraw obsidian to improve performance, but I believe in this case it will not be possible since the core issue is that obsidian itself is taking too long to process keyboard events due to the markdwon document being too long

**Comment by zsviczian** [comment]
These performance issues are often created by
- custom themes, check if you experience the issue with the default theme
- I see you are using MANY plugins (as a comparison I have 15 plugins enabled). Try to see if you experience the same with other plugins turned off. The impact can be created by any of your other plugins... I do am not familiar with many of them, thus it is hard to say which one. Many, based on their name are possible culprits for some CSS that can impact performance.

**Comment by ramarivera** [comment]
I know I use many plugins 😅 
However, I reported the issue after doing a performance recording, and I could not see either CSS code (mostly scripting) and plugin code (mostly obsidian app.js code).
I would share it with you, but obsidian doesn't allow me to download the performance recording :( 

Just to clarify, if you go into markdown mode of a heavy drawing, and try to type, do you experience any significant slowdown?

**Comment by zsviczian** [comment]
Did you test with plugins turned off? Please do so before we continue this discussion.

I do not experience slowdown in markdown mode even with very large drawings.

Plugins that add markdown editor features (such as coloring or other real-time formatting) and are poorly written will create a lag with large documents.

**Comment by ramarivera** [comment]
You were right, I turned off all plugins, snippets and themes except excallidraw and I cannot experience the slowdown anymore. I thought it couldn't be them since the performance recording didn't show it, but I was wrong. Now I have to figure out which plugin is doing this :( 

Thank you for your time and patience with this issue :)

**Comment by zsviczian** [comment]
Ok. I tested with my largest file, an 8.7MB large file with lots of freedraw lines. I can experience the lag.

**Comment by zsviczian** [comment]
With this very large drawing Obsidian is slow with all plugins disabled - out of the box.

**Comment by ramarivera** [comment]
For reference, in case it helps someone else, I found that my issue reduced by a lot when turning off Templater's syntax highlighting feature (which is a shame, but I can activate it on demand so I rather have nice performance)

**Comment by ramarivera** [comment]
Other thing I noticed, which was dumb of me...
I had the same file opened in different tabs. One in drawing mode, and one in markdown mode. Closing one and working with a single file also helped me :)

**Comment by zsviczian** [comment]
This is my Templater hack. I started using this before Templater implemented syntax highlighting. This works perfectly for me... I use the same approach for Excalidraw Scripts as well. There is no need for anything else. I also don't apply the closing part of the codeblock, just treat the whole file as code...

<img width="269" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/a49d77be-5909-4b1a-a65d-28950916d6d2">
