### ISSUE TITLE
BUG: Screenshot / Paste / Crop resulting in image Distorsion on Mac OS

### ISSUE THREAD

**Issue by laurentbonet** [zsviczian/obsidian-excalidraw-plugin#1740]
First congrat for the work done with Excalidraw for Obsidian !!!

**My environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112 23.4.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: laurent v1.0.0
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 14
		1: Calendar v1.5.10
		2: Terminal v3.14.0
		3: Shell commands v0.21.0
		4: Excalidraw v2.1.3
		5: Advanced URI v1.40.1
		6: Actions URI v1.5.1
		7: Dataview v0.5.66
		8: Buttons v0.5.1
		9: Daily Notes Viewer v0.2.1
		10: Laurent Bonet Plugin v1.0.0
		11: Homepage v3.8.0
		12: Hot Reload v0.1.11
		13: Templater v2.2.3
		14: Copy document as HTML v0.6.0

Mac OS Sonoma 14.4.1

**Describe the bug**

A Screenshot / Paste / Crop sequence lead to image distorsion on Mac OS
Same problem when saving the screenshot to a file then dragging dropping it in excalidraw
(I attached the file at the end of this issue description)

**To Reproduce**

1. Make a screenshot Shift-Ctrl-Cmd-3 shortcut
2. Paste in Excalidraw
3. Launch Crop and mask Image through the commande palette
4. Observe the result ...

**Expected behavior**
Image in excalidraw without distorsion

**Screenshots**
<img width="1470" alt="Pasted image 20240424074000" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/41547595/25fcd98b-f7c2-4b80-9ee5-b7a0e96a613d">

<img width="948" alt="Pasted image 20240424074249" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/41547595/5a24fa8f-717a-42aa-9690-d116cc832123">

**Additional context**
The cropping process work well in other context:
- In Obsidian either directly in a note or in canvas
- In powerpoint and google

<img width="1470" alt="Capture d’écran 2024-04-24 à 08 27 42" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/41547595/819efeeb-9c24-4e16-9313-2e0e64a7ea79">

**Comment by zsviczian** [comment]
Please update the Excalidraw plugin. I see you are using 2.1.3. This issue was resolved in 2.15.

**Comment by laurentbonet** [comment]
Beginners mistake ... always upgrade to the last version...
Sorry for that.
As "punishement" I will give a like of all the videos I watched from your channel ... and they are a lot !!! Amazing quality content.
Many thx for the job you are doing.
