### ISSUE TITLE
BUG：When there are too many “ _ ” in the Embedded Files , each operation causes a re-index and shows that the index is running too long and the CPU is running at high speed

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1743]
When there are too many local image links in the drawing board, each operation causes a re-index and shows that the index is running too long and the CPU is running at high speed
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/b39ca722-dd67-4873-a065-f67a929c136f)
I don't quite understand that my link is a local link, not a link in the obsidian folder, why it needs to be indexed
for example
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/35e7d612-9185-493b-95b7-c718276af6ce)

**Comment by zsviczian** [comment]
Try changing auto save to be less frequent. In this case, you will need to be a bit more careful closing Obsidian (my best practice is to press CTRL+S before closing). I've set autosave to practically never...

<img width="872" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/bc283eec-8148-442f-add7-4868c3f2ea7b">

**Comment by jiajiala** [comment]
@zsviczian 
Even if I set autosave to 15 minutes it didn't do anything, as long as I taped a new local file link, it definitely caused the cpu to run at high speed and showed the following results. This is a must-see BUG
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/b39ca722-dd67-4873-a065-f67a929c136f)

**Comment by zsviczian** [comment]
which plugin is throwing this message for you? where do you see the "Indexing taking a long time?
Do you experience the same if you disable all other plugins (leave only Excalidraw), then restart Obsidian?

**Comment by zsviczian** [comment]
Metadata Menu plugin?
Others have raised issues regarding that. When turned off everything is back to normal. If it is the metadata menu plugin, then please raise an issue with its developer, nothing I can do to help...

**Comment by jiajiala** [comment]
@zsviczian 
I closed all the plugins, including the core obsidian plugins, and the same problem occurred when I only opened excalidraw
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/8bc2c9bb-7df6-47b4-ace9-97c11393aa8c)

This is my file, but I have tried, once the file link cannot be found, the problem will disappear, so even if the file is uploaded, it should not be repeated in your side, but as long as there are enough local files linked, the number is about 500, the problem can be repeated, and the index will be constantly performed
[Dr20240417065620.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/15147773/Dr20240417065620.excalidraw.md)

**Comment by zsviczian** [comment]
do you experience the same when you have all of these referenced internally in Obsidian?
i.e. what I am interested in is if this is an issue with having the file:/// reference or an issue with having so many image.

> This is a must-see BUG

BTW. you have 524 images here. I am amazed that Excalidraw even works with this many. I definitely do not see this as a priority (must-see BUG) to resolve performance issues of this size as this looks like an edge use case. I recommend splitting your drawing into multiple files.

That said, I would still like to understand if there is a difference if the files are referenced from internal to Obsidian or External.

I have no idea where the indexing message comes from, could be an Obsidian message when the file is saved and related to the file:/// references. Frankly, I do not know. I am certainly not doing any indexing in Excalidraw.

**Comment by jiajiala** [comment]
I tested it and it should have nothing to do with excalidraw, as long as it is a local link, it will raise index, even if it is an md file
I will go to the authorities to solve this problem. Sorry to bother you.
