### ISSUE TITLE
BUG: Performance issue with larger drawings

### ISSUE THREAD

**Issue by koenbunders** [zsviczian/obsidian-excalidraw-plugin#1744]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 23.4.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: none
	Snippets enabled: 7
	Restricted mode: off
	Plugins installed: 41
	Plugins enabled: 28
		1: Calendar v1.5.10
		2: Commander v0.5.1
		3: Dataview v0.5.66
		4: Excalidraw v2.1.6
		5: ExcaliBrain v0.2.15
		6: Longform v2.0.7
		7: Natural Language Dates v0.6.2
		8: Note Refactor v1.8.2
		9: Outliner v4.8.1
		10: Paste URL into selection v1.7.0
		11: Periodic Notes v0.0.17
		12: Plugin Update Tracker v1.5.2
		13: QuickAdd v1.8.1
		14: Remember cursor position v1.0.8
		15: Sortable v0.3.1
		16: Style Settings v1.0.8
		17: Tag Wrangler v0.6.1
		18: Templater v2.2.3
		19: Workspaces Plus v0.3.3
		20: Minimal Theme Settings v7.5.0
		21: Supercharged Links v0.12.1
		22: BRAT v1.0.1
		23: Auto Note Mover v1.2.3
		24: Callout Manager v1.0.1
		25: Metadata Menu v0.8.7
		26: Hider v1.3.1
		27: Linter v1.23.2
		28: Tracker v1.13.3

**Describe the bug**
I've created many drawings. I noticed a while ago (sorry, wasn't able to report this earlier) that the performance of Excalidraw reduced a lot. Earlier there were no performance issues for some of my larger drawings, no there are serious performance issues. Obsidian as a whole responds way slower when such a drawing is open on a tab.

**To Reproduce**
1. Load a larg drawing

**Expected behavior**
Swift performance as it was earlier.

**Screenshots**
![screenshot](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/12957034/2da9cd45-a609-4acd-8063-3c4cbc2dc25f)

**Additional context**
I did not install new plugins.

**Comment by zsviczian** [comment]
please disable all other plugins. Restart obsidian and check the performance.
Even if you do not install new plugins, plugins get updated and can lead to impact.
I you right click in Excalidraw and select "Stats for Nerds" at the top, how many elements do you have in your drawing?
I work with drawings of 3000+ elements without any performance issues on my MacBook Air M1.

**Comment by koenbunders** [comment]
Thank you! I think I found the plugin that makes Obsidian to behave terribly slow when a 1500+ elements Excalidraw drawing is open. It is Metadata Menu (https://github.com/mdelobelle/metadatamenu).

I would love to use both plugins. How to proceed? Is this an issue to report to Metadata Menu, or is it an Excalidraw issue?

**Comment by zsviczian** [comment]
Yes, others have also mentioned this. This likely has to do with how the
Metadata plugin indexes files and somehow chokes on large files such as
Excalidraw.md files. Something that the metadata plugin should solve.
Ideally - but this is a personal opinion without knowing the details of the
Metadata plugin - that plugin should not create a separate index but make
use of DataView. I think it is a safe assumption that a large majority of
people using the metadata plugin will also have dataview installed. From an
Obsidian performance perspective, it is a waste to double/triple index
files. This is why, for example, ExcaliBrain requires DataView. To save on
resources.

**Comment by koenbunders** [comment]
Similar to what was reported in https://github.com/mdelobelle/metadatamenu/issues/660 , this issue is resolved by turning off
Community Plugins -> Metadata Menu -> Metadata Menu button -> Properties
