### ISSUE TITLE
FR: It is hoped that there is a way to reduce selection when using box selection

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1746]
At present, I use the box selection, can only add new content, but can not subtract the excess part to select. It is hoped that there is a way to reduce selection when using box selection

**Comment by zsviczian** [comment]
Please raise this on Excalidraw.com, this is not something that should be solved in the plugin.
https://github.com/excalidraw/excalidraw
