### ISSUE TITLE
BUG: failed to load excalidraw plugin on obsidian(android )

### ISSUE THREAD

**Issue by 1abvall** [zsviczian/obsidian-excalidraw-plugin#1747]
![Screenshot_2024-04-28-14-30-49-67_51606159b24eff83e24a54116878fe3e](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/168328024/82e9b1fa-778e-4002-87f1-c1afbf49fd52)

**Comment by zsviczian** [comment]
Update Android WebView.
