### ISSUE TITLE
BUG: cannot import library from Excalidraw Libraries on MAC OS

### ISSUE THREAD

**Issue by NoneShell** [zsviczian/obsidian-excalidraw-plugin#1748]
**Your environment**
- MACOS 
- Chrome
- Obsidian: v1.5.12
- Excalidraw: 2.1.6

**Describe the bug**
cannot import library from Excalidraw Libraries on MAC OS. My browser is Chrome

**To Reproduce**
1. Click "Browse libries"
2. on page "https://libraries.excalidraw.com/?target=_blank&referrer=app%3A%2F%2Fobsidian.md&useHash=true&token=Cj0yvZ6JnGY5ss8a96Q1l&theme=dark&version=2&sort=default"
3. choose any library, then click "Add to Excalidraw"
4. Chrome open a new tab, but nothing happens

**Expected behavior**
Chrome should open my Obsidian by url Scheme and import library to Excalidraw. 

**Fix**
when I modify url Scheme from "app://obsidian.md" to "obsidian://", it works

**Comment by zsviczian** [comment]
This is not a bug... Obsidian does not allow external sites to pass information (for your safety).
You need to download the library, then in the stencil library click open to load it.
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/19632853-e2d9-4444-89a9-b20af2648eb3)

**Comment by jbohnslav** [comment]
Hello, I don't even see the "Personal Library" section of Excalidraw on MacOS, version v1.7.7. [Someone else on reddit has the same issue. ](https://www.reddit.com/r/ObsidianMD/comments/17qimqf/where_is_the_excalidraw_library/)
