### ISSUE TITLE
Allow for the Menu "mode" that smaller screens / panes have for any size

### ISSUE THREAD

**Issue by GitMurf** [zsviczian/obsidian-excalidraw-plugin#175]
I love the compact Menu "mode" that smaller width screens / panes have (see screenshot below). Can this be added to the settings to allow this as the default all the time even on larger / wider screens/panes? I would prefer this over the sometimes noisy options that crowd the left side of the screen. I know you can do Zen Mode but it doesn't show the menus at all.

![image](https://user-images.githubusercontent.com/64155612/135918222-068b48df-7713-46f0-8baa-74a4681511ad.png)

**Comment by zsviczian** [comment]
I think this is simply css magic by the core Excalidraw plugin. You can probably fix this with CSS. I’ll take a look, but feel free to experiment as well, and let me know if you are able to work out the css code.

**Comment by zsviczian** [comment]
Just checked it. It is not a CSS thing. I'll look into the Excalidraw sourcecode to see if there is a trivial fix I can apply.

**Comment by GitMurf** [comment]
Sounds good. Thanks for looking into it! I just REALLY like that slim profile of the Menu option like that on shorter widths :-) I am assuming it is meant for Mobile (smaller screens) but I think it would be great as the default for desktops too.

**Comment by GitMurf** [comment]
I think this can probably be closed. I think Tray mode satisfies this request unless you are thinking of something more with this issue @zsviczian ?

**Comment by zsviczian** [comment]
Thanks! you are right!
THough there is still a bug, sometimes you cannot switch back to normal mode, until you resize the window...
