### ISSUE TITLE
BUG: drawing cursor disapearing when using wacom table pen

### ISSUE THREAD

**Issue by rodrigor** [zsviczian/obsidian-excalidraw-plugin#1764]
**Your environment**

Obsidian Version 1.5.12 (Installer 1.4.16)
Excalidraw Version: 2.1.7
OS: MacOS Sonoma 14.4.1

**Describe the bug**
Something weird happens when I use the Obsidian Excalidraw plugin (version 2.1.7).

When I use any Wacom pen tablet ( like https://www.wacom.com/en-us/products/pen-tablets/one-by-wacom) the Draw cursor doesn't appear. The problem happens only with the draw cursor (as seen in the video below). During the video, I started using the trackpad from my computer, and then the cursor appeared. The cursor appears for every other tool, such as Rectangle, Diamont, Circle, etc.

Another point: the problem only happens on the Obsidian plugin. The problem doesn't appear on the desktop app or the web interface( excalidraw.com).

Any insight about what could be happening?

**To Reproduce**
https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/288272/53e35c19-4614-49f3-b73a-67f40a0c0921

**Expected behavior**

The cursor pointer should appear when drawing using the pen table.

**Comment by rodrigor** [comment]
I used to draw using the Wacom pen table. The problem started about four to six weeks ago. Before reporting the issue, I tried to solve the problem from the Wacom side.

**Comment by zsviczian** [comment]
Please search closed issues for a solution. I've answered this question at least 10 times already (here, on YT, on Discord...)
https://github.com/zsviczian/obsidian-excalidraw-plugin/issues?q=is%3Aissue+is%3Aclosed+crosshair
