### ISSUE TITLE
BUG: OB Excalidraw dark mode desaturates / effects linked images.

### ISSUE THREAD

**Issue by ianTevesAcc** [zsviczian/obsidian-excalidraw-plugin#1767]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.

**Describe the bug**
Currently the Excalidraw plugin desaturates linked images in Excalidraw files when the Excalidraw file is in dark mode. I by excluding the dark mode effects on linked notes / files, this problem should be solved. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install OB Excalidraw.
2. Create an Excalidraw file.
3. Set Excalidraw file to dark mode.
4. Link an already existing image in Obsidian into the Excalidraw file.
5. You will then see that the linked image is de saturated.

**Expected behaviour**
The linked image file should be the same colour but is instead de saturated.

**Screenshots**
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/105651670/e9aac25c-f139-4a93-9c6e-b5aba4f788ab)
OG image on the left and Excalidraw linked image on the right.

**Additional context**
The weird is that this doesn't apply to images directly pasted into the Excalidraw file. (just take a screenshot and paste into Excalidraw and you'll see that the image is still the right saturation).

**Comment by zsviczian** [comment]
Excalidraw dark mode was designed for collaboration use-cases when one views the image in light mode the other in dark mode. It serves that purpose sufficiently, however in a PKM setup this is a) not really required b) the solution is not really good from a color accuracy perspective. I am personally not a fan of dark mode. Instead, I use a dark color palette. If color accuracy is important to you, I recommend this approach.

The issue/feature request has been raised with the Excalidraw package multiple times. You can raise it again, I don't expect it will get address any time soon (or ever). So again, we are back to the custom color palette solution...

vibrant colors: https://youtu.be/fypDth_-8q0
palette loader: https://youtu.be/epYNx2FSf2w
configuring color picker: https://youtu.be/diBT5iaoAYo

**Comment by ianTevesAcc** [comment]
Sorry. I couldn't find this issue myself. Thanks for the help!
