### ISSUE TITLE
FR: fold drawing section in markdown mode

### ISSUE THREAD

**Issue by zenz** [zsviczian/obsidian-excalidraw-plugin#1774]
**Is your feature request related to a problem? Please describe.**
Could you please make the Drawing section in markdown mode defaults to folded?

**Comment by zsviczian** [comment]
if you tell me how to... I've been looking at this for some time, but haven't been able to figure out how :(

**Comment by zenz** [comment]
<img width="956" alt="截屏2024-05-14 10 38 33" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/301676/568f514d-32c1-42b9-9e5d-dc82bfb7138c">
Like in this captured, Drawing was unfolded by default, is it possible to make it folded by default?

**Comment by zsviczian** [comment]
solved with 2.2.0

**Comment by zenz** [comment]
> solved with 2.2.0

Thank you!
