### ISSUE TITLE
FR: Page layers cannot be adjusted; embedded linked pages are always on the top layer

### ISSUE THREAD

**Issue by ottopan** [zsviczian/obsidian-excalidraw-plugin#1776]
![Snipaste_2024-05-15_15-39-17](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/18224971/5d28a8ee-2467-42e0-ad50-e4781041b67f)

**Comment by zsviczian** [comment]
This is not a bug, but the consequence of how embeddable are technically implemented. Can't change this.
