### ISSUE TITLE
QUESTION: Click on a Element in Canvas and trigger via ScriptEngine a script.

### ISSUE THREAD

**Issue by foreversun69** [zsviczian/obsidian-excalidraw-plugin#1777]
Hey,

is it possible to trigger a js-script via click on e.g. a "Button"?
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/44213573/9f757543-83b0-479f-bb2f-0bdb93a66b53)

best wishes
foreversun

**Comment by zsviczian** [comment]
Yes. 
1) Create an Excalidraw script.
2) Attach the script to any element with `Insert Obsidian Command as a Link`

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/31ee68e0-064a-4b6f-a4e8-cd514256f6e0)
