### ISSUE TITLE
BUG: PDF Cropping multiple times crashes Excalidraw

### ISSUE THREAD

**Issue by Vonnegut1** [zsviczian/obsidian-excalidraw-plugin#1781]
Macbook Air M2

1. I bring the PDF into Obsidian
2. Drag the PDF onto the Excalidraw canvas as an interactive link
3. Scroll to the page I wan to crop, then trigger the crop tool

After five or so crops from the pdf, the whole screen goes dark and crashes Obsidian

**Comment by zsviczian** [comment]
I am unable to reproduce. I stopped after 13 crops. Can you share a sample PDF, maybe that has some effect on this as well.

**Comment by zsviczian** [comment]
is this still an issue?
