### ISSUE TITLE
BUG: Changes made past first Excalidraw save of SVG or PNG into an embedded file are not showing up on obsidian publish

### ISSUE THREAD

**Issue by devinat1** [zsviczian/obsidian-excalidraw-plugin#1783]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 6.5.0-28-generic
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.4
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 66
	Plugins enabled: 34
		1: Templater v2.3.1
		2: Tab Switcher v1.4.0
		3: Google Photos v1.6.5
		4: Dataview v0.5.66
		5: Editor Syntax Highlight v0.1.3
		6: Minimal Theme Settings v7.5.0
		7: Commander v0.5.1
		8: Canvas Mindmap v0.1.11
		9: Auto Link Title v1.5.4
		10: Admonition v10.2.0
		11: Simple CanvaSearch v0.1.0
		12: QuickAdd v1.8.1
		13: Excalidraw v2.1.8
		14: Todoist Sync v1.13.0
		15: Linter v1.24.0
		16: Readwise Official v2.0.1
		17: Enhancing Export v1.10.5
		18: Zotero Integration v3.1.8
		19: Paste URL into selection v1.7.0
		20: Note Refactor v1.8.2
		21: Canvas Filter v0.9.4
		22: Ghost Fade Focus v3.0.0
		23: Quick Switcher++ v4.2.0
		24: Recent Files v1.3.10
		25: ExcaliBrain v0.2.15
		26: Projects v1.17.3
		27: Periodic Notes v0.0.17
		28: Homepage v3.8.0
		29: Calendar v1.5.10
		30: Longform v2.0.7
		31: BRAT v1.0.1
		32: Slides Extended v2.0.7
		33: Copilot v2.5.2
		34: Plugin Update Tracker v1.5.2

**Describe the bug**
With auto export to SVG or PNG setting turned on, these changes don't show up when publishing to obsidian publish.

**To Reproduce**
![Screenshot from 2024-05-18 16-56-12](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/15788108/358d3d9a-b1a6-4f80-9107-e623608d50c9)
![Screenshot from 2024-05-18 16-56-23](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/15788108/fbf9de8b-50ed-4bb4-8bbf-b35f7eede7a0)

**Expected behavior**
Any changes made update on the embedded page and show up on obsidian publish.

**Additional context**

This is the file contents:
```
![[test 2024-05-18 16.43.23.excalidraw.svg]]
%%[[test 2024-05-18 16.43.23.excalidraw.md|🖋 Edit in Excalidraw]]%%


![[test 2024-05-18 16.49.09.excalidraw.png]]
%%[[test 2024-05-18 16.49.09.excalidraw.md|🖋 Edit in Excalidraw]]%%
```

Where all Excalidraw files and png/svg files are stored in the Files directory.

**Comment by zsviczian** [comment]
Exporting to svg and png is treated with lower priority by the plugin and committed during autosave. To ensure changes are reflected in the auto exported svg and png, for now, I recommend pressing CTRL+S
