### ISSUE TITLE
BUG:  Excalidraw freezes obsidian while saving

### ISSUE THREAD

**Issue by alsoasnerd** [zsviczian/obsidian-excalidraw-plugin#1785]
**Your Environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000 6.9.1-arch1-1
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Encore v2.10.1
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 27
	Plugins enabled: 26
		1: Tldraw v1.0.5
		2: Advanced Canvas v2.7.6
		3: Annotator v0.2.11
		4: Better Word Count v0.10.1
		5: Calendar v1.5.10
		6: Dataview v0.5.66
		7: Tracker v1.14.0
		8: Templater v2.3.1
		9: Spaced Repetition v1.12.4
		10: Natural Language Dates v0.6.2
		11: Recent Files v1.3.10
		12: MySnippets v1.2.3
		13: Markdown table checkboxes v2.0.8
		14: Ledger v0.3.2
		15: Latex Suite v1.9.3
		16: Kanban v1.5.3
		17: Homepage v3.8.0
		18: Excalidraw v2.2.1
		19: Reminder v1.1.15
		20: MAKE.md v0.9.23
		21: ExcaliBrain v0.2.15
		22: Emoji Magic v0.2.2
		23: Style Settings v1.0.8
		24: Day Planner v0.20.4
		25: Super Simple Time Tracker v0.2.2
		26: Better Command Palette v0.17.1

**Describe the bug**
When Excalidraw saves, my entire obsidian freezes. Write with a stylus pen is impossible with this issue

**To Reproduce**
1. Update Excalidraw to v2.2.1
2. Open a Excalidraw file
3. Write something and save
4. Obsidian freezes

**Expected behavior**
A non-freezing obsidian 

**Additional context**
Sorry for my English and thanks for maintain this project. It's awesome to have a tool like Excalidraw inside Obsidian.

**Comment by zsviczian** [comment]
Did this happen once with one specific file, or regularly with all your files?
When you say freezes, do you mean that it completely stops working, or there is just a glitch?
If this is related to a specific file, can you share that file with me?
Do you get the same issue when you disable other plugins?
Are you editing the drawing in the main Obsidian workspace or in a popout window?

**Comment by DevAles** [comment]
Obsidian freezes when working with files over 1-2MB. 
When I say freezes, I mean that the app becomes unresponsive for a few seconds.
Disabling other plugins doesn't fix the issue.
I'm editing in the main Obsidian workspace.

**Comment by alsoasnerd** [comment]
![image](https://github.com/user-attachments/assets/d435c615-49ec-462c-aa31-4e0dd18382c1)

Disable this setting fix the issue, my bad.
