### ISSUE TITLE
BUG: undo/history not properly initialized

### ISSUE THREAD

**Issue by dwelle** [zsviczian/obsidian-excalidraw-plugin#1791]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.2.2

**Describe the bug**

History is not initialized properly. Undo on initial load of a file removes all content. Even after first change is made after load, first undo removes all content.

@zsviczian if you can point to where you initialize/update data, I can take a look.

**Comment by zsviczian** [comment]
Ok. I can reproduce.
Based on my quick testing this only seems to happen when you load another drawing into an already open Excalidraw tab. The issue likely stems from that I reset the Scene, not reload Excalidraw when you change files. I call resetScene() on the Excalidraw API.

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/d05ccc00556467cd4d987abb94d549f4f16a0a93/src/ExcalidrawView.ts#L1804-L1821

**Comment by dwelle** [comment]
`resetScene()` also clears history, so it's not the whole story. Where you do populate the scene with the new file contents?

**Comment by zsviczian** [comment]
I simply call updateScene(). I do it in two steps, first to load the elements, then a successive updateScene to set appState.

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/d05ccc00556467cd4d987abb94d549f4f16a0a93/src/ExcalidrawView.ts#L2198-L2229

**Comment by dwelle** [comment]
Ah. The new history API has changed the `commitToHistory` attribute of `updateScene` to `storeAction`.

You'll want to update `commitToHistory: true` to `storeAction: "capture"`.

(I've also noticed we have incorrect tsdoc saying the default is `capture`, but it is `none` to align with previous behavior).

**Comment by zsviczian** [comment]
Thanks! I notice this is an issue in a number of my scripts as well. I will clean this up for the next release.

**Comment by zsviczian** [comment]
...and I need `storeAction: "update"` at the time of the initial load. 
Done, working, will release in 2.2.3
