### ISSUE TITLE
Obsidian: failed to load obsidian-excalidraw-plugin | Huawei Matepad Pro (Android)

### ISSUE THREAD

**Issue by jon5th5n** [zsviczian/obsidian-excalidraw-plugin#181]
**Describe the bug**
I tried installing the excalidraw plugin on my Huawei Matepad Pro since on my PC I thought the plugin looked quite interesting but sadly when I try to enable it I get a message saying "failed to load plugin obsidian-excalidraw-plugin".
I also tried finding the exact error message but failed at opening the developer console on android so this is all I have...
Does somebody know of this problem and maybe how to fix it?

**To Reproduce**
I am not really sure since on my Android Phone (with Google Services) it loads just fine, so I'm thinking it might actually be a problem with not having Google Services...
Then to reproduce you would just have to try it on another device without them but I'm not certain.

**Expected behavior**
The Excalidraw plugin to just be enabled.

**Smartphone:**
 - Device: Huawei Matepad Pro (2020)
 - OS: Android 10.x.x
 - Browser: Brave (Chromium I guess)

**Comment by zsviczian** [comment]
I am using Excalidraw on a Samsung Note 8/Android 9 phone. It works as expected on my phone.
Since I can't reproduce the issue, I don't really have an idea how to help you.

**Comment by richfan** [comment]
I am using Excalidraw on a Mi9 Xiaomi /Android 10 phone. But it doesn't work.

**Comment by vequa** [comment]
Well I just installed a Chrome APK so I now have the browser but in my setting I still only get shown the Huawei-WebView one.  I also restarted the device in between.
I'm not sure if this is a thing Huawei had to put in place or if I just did something wrong. Maybe there is a way to install Google WebView another way but I couldn't find one myself.

**Comment by montanus2019** [comment]
In my mi9 mobilephone, the webview is "Android system webview 83.0.4103.101"

**Comment by vequa** [comment]
ok I'll try to get another WebView working for some time... I will update on this when I find something.

**Comment by SantiPesce** [comment]
> I now tried for two days to install the Android System WebView or rather get it running but I just couldn't find anything on how to do it. It's quiet weird that I can't find anyone with the same problem or even better an answer for it. Since I couldn't even find a starting point to begin with I will for now just give up and accept the fact that it won't work on my device. Still I want to thank everyone who tried helping and if I'll ever find a fix or anything new I will update it here.

I had the same problem with this plugin and something similar with [Templater](https://github.com/SilentVoid13/Templater); when I read the following comment (by zsviczian) I followed the steps and it seems that everything was fine, but then I remembered that I had not update Android System WebView a long time ago so that I did it and it worked! Now it doesn't throw the startup error and both plugins work properly.

> This could be related to the Android WebView component. Could you open settings / developer options / WebView Implementation and let me know what you see there?

**Comment by zsviczian** [comment]
There is a small chance that I fixed this. Unfortunately, I don't have a device on which it does not work... therefore it is hard to test.
I changed the target from es2020 to es2017 to match the core Excalidraw component. I think there is a chance this might resolve the issue with out-of-date WebViews.

**Comment by subjektivdk** [comment]
Just wanted to add that I can't get the plugin to load on my:
Samsung Tab S6, Android 11, Google WebKit/webview
Updated Obsidian, excalidraw-plugin

**Comment by HoodyEz** [comment]
I had this same problem with my Motorola G24. I installed the System WebView Beta, then in the developer options, I switched from System WebView to System WebView Beta. In Obsidian, I uninstalled Excalidraw and reinstalled it, which solved the problem.

https://android-system-webview-beta.uptodown.com/android

**Comment by dm7500** [comment]
Disregard. I was able to get it working by uninstalling the plugin on Android, letting the change sync, then reinstalling directly on Android.
