### ISSUE TITLE
FR: Support compatibility with Obsidian Linter Plugin

### ISSUE THREAD

**Issue by razetdinov** [zsviczian/obsidian-excalidraw-plugin#1811]
**Is your feature request related to a problem? Please describe.**
[Markdown Best Practices](https://www.markdownguide.org/basic-syntax/#heading-best-practices) state the following:

> You should also put blank lines before and after a heading for compatibility.

[Obsidian Linter plugin](https://github.com/platers/obsidian-linter) has a setting which ensures that [all headings have a blank line both before and after](https://platers.github.io/obsidian-linter/settings/spacing-rules/#heading-blank-lines).

Switching this setting on breaks excalidraw images, as it inserts blank lines before and after the `Text Elements` heading.

**Describe the solution you'd like**
Excalidraw should ignore blank lines before and after `Text Elements` heading. Obsidian itself behaves this way. For example, if you trancslude a referenced block, Obsidian ignores all the blank lines before it.

**Describe alternatives you've considered**
Temporary workaround is to switch off the before mentioned setting in Obsidian Linter plugin preferences.

**Additional context**
Before blank lines are added around headings:
<img width="503" alt="Screenshot 2024-06-03 at 15 44 28" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/2121838/902f7afb-8dae-4582-9798-de1017632678">

After blank lines are added around headings:
<img width="535" alt="Screenshot 2024-06-03 at 15 44 10" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/2121838/7a700f00-7608-4485-8357-09a13133137e">

**Comment by zsviczian** [comment]
My answer has two parts:
1) I do not recommend automatically changing Excalidraw files with Linter or any other metadata plugins, and I cannot manage compatibility with other plugins. That is simply not feasible... I personally avoid any plugins that change files in the background - but that is a personal choice.
2) If you decided to do it anyway, there is a compatibility setting for this introduced in [v 2.2.3](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/2.2.3). 

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/7765ef35-ed37-4736-a51f-690a37470cd7)
