### ISSUE TITLE
FR: 插件在墨水屏中无法使用

### ISSUE THREAD

**Issue by Lhlllll** [zsviczian/obsidian-excalidraw-plugin#1813]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to read my excalidraw notes on my ink device. The brand of my ink device is called iReader.

**Comment by zsviczian** [comment]
Yes, the experience on ink devices is not very good. This is typically due to the low processor performance of these devices... there is not much I can do about it. Sorry.
