### ISSUE TITLE
FR: back-of-note workflow for literature notes

### ISSUE THREAD

**Issue by tnschmid** [zsviczian/obsidian-excalidraw-plugin#1820]
Current problem:
- re-importing Zotero highlights with Zotero Integration (taking incremental notes on books, papers etc.)  requires a persist block (example below) around parts that should not change (Obsidian specific Metadata, general notes, Excalidraw data block ...)
- Excalidraw removes the persist block below Excalidraw data, such that file ends with `%%`

The following example highlights the problem:
```
%% begin excalidraw %% // persist block start
# Excalidraw Data
## Text Elements
%%
## Drawing
...

%% //afterwards everything is removed -> problem for the workflow
%% end excalidraw %% // part removed by excalidraw;  // persist block end

%% Import Date: some timestamp %% // part removed by excalidraw
```

Proposed solution:
- allow additional text (especially the comment based persist block) after the Excalidraw Data

Why this would be helpful:
- enhance the hybrid note approach for the application case of literature notes
- alternative solution requires two separate md files: one for the Zotero highlights (svg drawing can be embedded) and one for the actual Zotero drawing

**Comment by zsviczian** [comment]
To double-check that I understand you correctly, what you are after is for Excalidraw to retain whatever text is added after the closing %% following the json section in `## Drawing`?

**Comment by tnschmid** [comment]
Exactly.

**Comment by zsviczian** [comment]
implemented in 2.2.6
You will need to enable Zotero support under Compatibility Features in Plugin Settings
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/fde76d8f-6e79-41af-898f-7b3c07fe1b21)

**Comment by tnschmid** [comment]
Thank you, I will check it out once it is released!

**Comment by ugolafosse** [comment]
Hello @tnschmid , If the fix you mentioned has been working for you, could you quickly walk me through your workflow?

I’ve been using Zotero for my highlights and notes, but I’ve added template so that I get snippets I can copy-paste and embed inside any excalidraw. However, this still requires having the Zotero note disconnected from the actual drawing, and there’s a bit of a disconnect. 

![CleanShot 2024-06-15 at 10 45 07](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/44898829/2132e59c-5d01-44f7-8858-b58ee9d54eb9)

as you can see in the video I have 2 different note for the book

You mentioned a different approach or workflow, and I m curious about it. Maybe you have a better way to integrate these elements. Could you share your process with me?

Thank you!

**Comment by tnschmid** [comment]
I was talking about the functionality of Excalidraw to have a hybrid note (visual + markdown; see here https://www.youtube.com/watch?v=zmgqMZi6QL8) by just converting a md note via `Excalidraw: Convert markdown note to Excalidraw Drawing`. Now I just create a template for the Zotero Integration plugin with the corresponding default drawing. To not override the excalidraw data block when incrementally updating the literature notes  I'm using a persist block (same as %% begin notes%% in your example) . However, the problem was (and actually still is) that excalidraw removes the necessary %% end ... %% and %% Import Date ...%%  at the end of the md note. 
My goal was/is to have one note containing both the visual version of the note and the highlights on the other side of the note. To make this work excalidraw must not remove the persist block from the Zotero Integration plugin.
To be clear it is still not working that excalidraw keeps the additional part after the excalidraw data block, so I will soon file a bug report / feature request for this.

**Comment by zsviczian** [comment]
did you enable Zotero compatibility in settings?

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/300b56cd-b627-415a-a0d7-13593b95e014)

**Comment by tnschmid** [comment]
Yes.
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/83811597/03881721-41c4-4445-b3ca-55c85ec236e7)
