### ISSUE TITLE
BUG: 🔎🔎🔎"search for" problem🔎🔎🔎

### ISSUE THREAD

**Issue by ZenryW** [zsviczian/obsidian-excalidraw-plugin#1822]
The "Ctrl+F" search function has lost the ability to automatically select text in the latest version 2.2.5.

**Comment by zsviczian** [comment]
Yes, I also noticed and fixed it, but haven't released the fix yet.

**Comment by zsviczian** [comment]
fixed in 2.2.6 (will release later this week)

**Comment by ZenryW** [comment]
Much appreciated. Love your stunning work.
