### ISSUE TITLE
BUG: File completely wiped out and unfix-able out after pressing CTRL + Z to undo a single change

### ISSUE THREAD

**Issue by winston142O** [zsviczian/obsidian-excalidraw-plugin#1823]
**Environment Settings**

```
SYSTEM INFO:
	Obsidian version: v1.6.3
	Installer version: v1.6.3
	Operating system: #1 SMP PREEMPT_DYNAMIC Mon May 27 14:53:33 UTC 2024 6.8.11-300.fc40.x86_64
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: AnuPpuccin v1.5.0
	Snippets enabled: 5
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 5
		1: Excalidraw v2.2.2
		2: Kanban v1.5.3
		3: Dataview v0.5.66
		4: Multi-Column Markdown v0.9.1
		5: MathLive v1.3.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Describe the bug**

This is the second time this happens. When inside a excalidraw, after mistakenly moving something or adding a element and quickly pressing CTRL + Z once to undo said change, the file completely wipes out, and deleting pretty much everything in the markdown and whatever wasn't deleted turns into `compressed-json`. This only happens inside `.excalidraw` files.

**To Reproduce**
1. Enter a excalidraw drawing.
2. Perform an action (eg: moving something, adding an element)
3. Press CTRL + Z once to undo the action
4. See the file go blank before ultimately displaying a blank canvas

**Expected behavior**

The action to be undone and the file to go back to its previous state.

**Screenshots**

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/99276259/6bdef239-d416-4935-b217-c1a8d3ba4173)

**Additional context**

This has happened twice, when a file was large but definitely not huge, for this one, I estimate around 10 pictures, no more than 500 words distributed across text boxes and some handwriting. When this happens, if you try to check the markdown, you can only see the following:

```
---

excalidraw-plugin: parsed
tags: [excalidraw]

---
==⚠  Switch to EXCALIDRAW VIEW in the MORE OPTIONS menu of this document. ⚠== You can decompress Drawing data with the command palette: 'Decompress current Excalidraw file'. For more info check in plugin settings under 'Saving'

# Excalidraw Data
## Text Elements
%%
## Drawing
```compressed-json
N4KAkARALgngDgUwgLgAQQQDwMYEMA2AlgCYBOuA7hADTgQBuCpAzoQPYB2KqATLZMzYBXUtiRoIACyhQ4zZAHoFAc0JRJQgEYA6bGwC2CgF7N6hbEcK4OCtptbErHALRY8RMpWdx8Q1TdIEfARcZgRmBShcZQUebTieGjoghH0EDihmbgBtcDBQMELoeHF0KCwoJMLIRhZ2LjQAdgBmfiLa1k4AOU4xbgBGRoBWAA5Gxp4AFknWvMhCDmIsbghc

AAYqosJmABEU8uJuKFIhBDb5w4khTEIAayEATXwAYU3IADNCfHwAZVhglaCDxvCDMY5sW4IADqJHU3D4c1B4MhfxgAIkQJIINIwmUkg44SyaH65wgbDguGwahgAzWa1J1mU6NQ9MRmG4zkmLXiAE4eGshs0eMKAGxDEU8IakmloZw8HnNbTNYYjHjNHmNSYitY8yaksE4yHPNj4NikFYAYn6CGt1pBmkpt2UOKEi2NpvNEmO1mYFMCGRBFFhkm4k

x5Q20XN1zX6/SGapmw1JkgQhDxlTQkv1CAQl1QQy5Q0a/TW/RGpOdwjgAEliETUNkALqk97kNK17gcITfUkuxYE5j1rs9xGaYSLACiwTSGXrTdJQjgxFwBwGxZGZaGcY3fNJRA4t073fwe7Y2EhefeBDCLc4UB+hCMpX5t4yADFcPovjLUCTEeVMAzdAAAVcFIKAAFvsG7XBUHSVB9DYMwv3SKA2FQMD9AAZ44cx0NYfQfAQVAAAo3yw0h9Bg5gA

EpsUoAAVCoVlA8CoJguCOAQpDCBQjJ0MwnC8NQAiiNI8jKOoujSQAqAAEEiGUBp0GCd5KlJWooHMAgFLTZToHJEE9AyXAFiYDs0GHE9ETNNMFgIJjAJYsDIOg/BYPgxDkMIVCBMooS9BE3ixLIiiqPc2iQVwIQ0IAJXCR9SmOU49zMgAJVN0wGeIhjyABfNoCiKWBEBWXjoiQDSmE6ZT+gVKq6m6XpSn6NVmkFHkRRFHlSQWJZ2QkXB+hBbY9mCV

c0GSs5ESxCQJwAVWaABHABpHkoAARWaCcAHE336Z4AA0HgY6tgKWroQU+b5UWZUETSxfVkWhYN4Sew0EFu0p7uBXtcXxQkBlJclKWpWlWWqVYOCZUoIaKAbUE5VVtGGSURWaLkxQlKVER/OUhjWbQRlVAmWimHgyyTREDQhBB3TNFZvQ4X0wNQ+1HUrV1iHpz0ynIZm/TZ0kg2IOEmhjFG1h4Ym1hGIYFSpyGUzTaRuALEYUfGfptRFaZBVa7Ncw

GZpmilkZozhyBOZrOscmbRFW0/BALNQKy/q5gch2PUkxy5qdUlQud7chxdlwm39103bc6oRSH90PSzvcRU1zyNtAr3wG9qaiKAhHrCBEEWBZlCur5nbzCAeFwRMRWwHhGjWZpNElIaRgQEUywx033hGXAZcmfpq81ZpzZBZh3FKXJqjAP9p/6OZG3ywr/xKFZWxzTwqAamruCFbf6h6Dg+jQHl+kmSVz8b3rFmWQahhG3Z9jT1Apt6ivnFuIYODS
```

and it keeps going, but, even if it's possible to recover this `compressed-json` data (which I am not sure of), the text elements and embeds are completely gone, forever.

**Comment by zsviczian** [comment]
I am sorry this happened. I can see you are using Excalidraw 2.2.2.
This issue was addressed in 2.2.3. See release notes here: https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/2.2.3

You did not share the complete markdown file. If you do I can check if I can restore it for you.

**Comment by winston142O** [comment]
Oops, I will make sure to update next time :(
Thanks for all your work, thanks to you I don't need to use One Note anymore.

It would be really nice if the file can be restored, since I was using this specific file to study for a test I have this week. But if for any reason it cannot be it's all good. Thank you so much for your offer.

[Clase 6 2024-05-28 20.11.50.excalidraw.md](https://github.com/user-attachments/files/15809720/Clase.6.2024-05-28.20.11.50.excalidraw.md)

**Comment by zsviczian** [comment]
here you go:

[Clase.6.2024-05-28.20.11.50.excalidraw.md](https://github.com/user-attachments/files/15810663/Clase.6.2024-05-28.20.11.50.excalidraw.md)

For anyone reading this in the future.
- I pasted the contents of the markdown file into an empty note (instead of opening the file with Excalidraw up front). 
- I ran the command palette action: Decompress Excalidraw
- I did a search and replace for `"isDeleted": true`, changing it to `"isDeleted": false`

When elements are deleted, during the first save they are retained in the file with "isDeleted": true.

**Comment by winston142O** [comment]
Thank you so much!

**Comment by g7-bit** [comment]
I am using Obsidian and excalidraw and updated the plugin when the following issue happened(hence don't remember the version when the file bugged)

I quit the excalidraw after the mouse pointer started glitching, 
When I reopened the excalidraw file it says the same issue the OP is having. 

could you please help me restore the file?
