### ISSUE TITLE
FR: short links

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1857]
![image](https://github.com/scottwillmoore/obsidian-short-links/assets/73203026/d9db9ff3-ef92-4cf7-b2a3-b78b9e657b0b)
It would be nice if it only showed 111
And it is automatically generated，
It is automatically generated, similar to what the plugin does in the MD file and does not need to be manually modified by [[test#111|111]]
Just like this plugin does in the MD file
https://github.com/scottwillmoore/obsidian-short-links

**Comment by zsviczian** [comment]
I don't understand `[[test#111|111]]` will produce what you are looking for...
But this can be easily implemented with Excalidraw script. I suggest you explore the [Set Link Alias](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Set%20Link%20Alias.md) script
