### ISSUE TITLE
BUG: Creating a new image hard crashes Obsidian

### ISSUE THREAD

**Issue by devinat1** [zsviczian/obsidian-excalidraw-plugin#1862]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.6.5
	Operating system: #36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 10:49:14 UTC 2024 6.8.0-36-generic
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.4
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 67
	Plugins enabled: 37
		1: Templater v2.3.3
		2: Tab Switcher v1.4.0
		3: Google Photos v1.6.7
		4: Dataview v0.5.67
		5: Editor Syntax Highlight v0.1.3
		6: Minimal Theme Settings v8.0.2
		7: Commander v0.5.1
		8: Canvas Mindmap v0.1.11
		9: Auto Link Title v1.5.4
		10: Admonition v10.3.2
		11: Simple CanvaSearch v1.0.0
		12: QuickAdd v1.9.2
		13: Excalidraw v2.2.7
		14: Todoist Sync v1.13.0
		15: Linter v1.24.0
		16: Readwise Official v2.0.1
		17: Enhancing Export v1.10.6
		18: Zotero Integration v3.1.8
		19: Paste URL into selection v1.7.0
		20: Note Refactor v1.8.2
		21: Canvas Filter v0.9.4
		22: Ghost Fade Focus v3.0.0
		23: Quick Switcher++ v4.3.0
		24: Recent Files v1.4.1
		25: ExcaliBrain v0.2.15
		26: Projects v1.17.3
		27: Periodic Notes v0.0.17
		28: Homepage v3.8.1
		29: Calendar v1.5.10
		30: Longform v2.0.7
		31: BRAT v1.0.1
		32: Slides Extended v2.0.7
		33: Copilot v2.5.2
		34: Plugin Update Tracker v1.5.2
		35: Kanban v2.0.51
		36: LanguageTool Integration v0.3.7
		37: Copy as HTML v1.1.3

**Describe the bug**
When I have the SVG option enabled and create a new image, Obsidian crashes immediately thereafter

**To Reproduce**
1. Enable "Save as SVG"
2. Create a new image
3. Obsidian hard crashes (have to reopen to be able to connect)

**Expected behavior**

**Screenshots**

**Additional context**
When I reopen obsidian, the new image opens in the popout window and is embedded as expected. However, when I close the excalidraw file, I get a hardcrash again. My fan also starts whirring.

**Comment by devinat1** [comment]
Note that only after I close the original file that my excalidraw SVG is embedded into can I close the excalidraw popout window itself.

**Comment by zsviczian** [comment]
Are you using Obsidian Sync. If yes, there is an Electron bug that has been amplified since the Sync improvements in Obsidian 1.6.x that causes Obsidian to crash when sync is running in the background while closing a popout window.

I have a temporary solution. You can install it with BRAT. This solution will pause Obsidian sync for 1.5 secs when closing a popout window. This has completely solved the crashing issue for me.

https://github.com/zsviczian/obsidian-popout-freeze-workaround

let me know if I misunderstood your issue.

**Comment by devinat1** [comment]
Yes I do have sync. This is likely the problem.

**Comment by zsviczian** [comment]
did my [patch](https://github.com/zsviczian/obsidian-popout-freeze-workaround) help?

**Comment by devinat1** [comment]
Yes that seems to have fixed it.
