### ISSUE TITLE
Add setting or quick command to purge cache after changing Obsidian theme from Light to Dark

### ISSUE THREAD

**Issue by AndriiPetrovDev** [zsviczian/obsidian-excalidraw-plugin#1870]
1. Create Excalidraw file
2. Embed in a note
3. Change Obsidian theme
4. Embedded image stuck in previous theme - this can be inconvinient.

I suggest to add some command to force updating theme for the current file or entire cache. Or add such setting in Excalidraw plugin itself.

Please tell me about such function if I overlooked it

**Comment by zsviczian** [comment]
Try this setting:
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/4b34cbca-6236-4615-96ac-083ed06d9bdb">


Note that, Obsidian does not automatically rebuild views when the theme is changed. You can, however, create a simple, short Templater script:

To update only the currently active markdown file:
```js
<%*
app.workspace.activeLeaf.rebuildView();
tR += app.workspace.activeLeaf.view.editor.getSelection();
%>
```

or if you want to update all open markdown files:
```js
<%*
app.workspace.getLeavesOfType("markdown").forEach(l=>l.reguildView());
tR += app.workspace.activeLeaf.view.editor.getSelection();
%>
```
