### ISSUE TITLE
BUG: How do I open links in the same tab?

### ISSUE THREAD

**Issue by gleyconJ** [zsviczian/obsidian-excalidraw-plugin#1871]
How do I open links in the same tab? Because I want to browse within the same tab and not open tabs for each link I click and then have to close them and pollute my workflow. I can't find an option to enable or disable this in the Excalidraw settings.

**Comment by zsviczian** [comment]
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/2a229e36-ddfb-444b-b23e-14eb09c8e0c9">

By default click in Obisidan opens files in the same tab. CTRL/CMD + Click opens them in the current active tab.
I've aligned link click defaults with Obsidian, thus in a markdown file if you long press on an Excalidraw preview image it will open in the active tab, if your CTRL+long press it will open in a new tab, etc.
When editing an Excalidraw drawing, however, we have a problem. Click has a meaning by itself. Thus you need to press CTRL/CMD to let the plugin know that you are navigating a link... but then that is the Obsidian default to open in a new tab.

You can customize modifier key settings in plugin settings.
One option is, as shown in the screenshot above, is to set up a shortcut like SHIFT+CTRL/CMD click to open in the active pane. If you do this, the same will apply when long clicking an image in markdown view mode.

You can play with these settings to find what works best for you.
