### ISSUE TITLE
BUG: 'Excalidraw: Insert link to file' not working

### ISSUE THREAD

**Issue by j0lev** [zsviczian/obsidian-excalidraw-plugin#1873]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.5.12
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 23.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.2.8

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
Command 'Excalidraw: Insert link to file' does not create a clickable link to another file/ drawing. There is no printed error but there is just no way and no blue icon to click at the object to navigate to another file.

**To Reproduce**
1. In Obsidian Excalidraw drawing, select an object (e.g. text)
2. Ctrl + Shift + K/ Ctrl P -> 'Excalidraw: Insert link to file'
3. Selecting/ typing file name to be linked

**Expected behavior**
Clicking on this object should navigate me to the linked drawing; there should also be a blue icon indicating that a link exists.

**Screenshots**

1. selecting object

<img width="371" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/162876065/dbcfccb5-6646-46e9-9112-ff837c29feab">

2. selecting drawing to link to

<img width="770" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/162876065/2a4d84b1-899b-4a6c-b031-e5654ce82a7d">

3. no link created to other file/ drawing

<img width="294" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/162876065/846e0664-d1a0-441e-8716-8734cbf6f4d9">

**Additional context**
Only stopped working after updating to the latest Obsidian Excalidraw version (2.2.8). It used to work before updating from Obsidian Excalidraw version 2.2.5

**Comment by Cloudplaygit** [comment]
Same problem on my end.

**Comment by tianchenmao** [comment]
+1

**Comment by tianchenmao** [comment]
+1

**Comment by zsviczian** [comment]
I was able to reproduce it. Will fix in the next release

**Comment by zsviczian** [comment]
sorry - this was an error introduced in my refactoring of the code with 2.2.8. I've fixed this (and some other similar issues in 2.2.9). Will release over the weekend.
