### ISSUE TITLE
BUG: stoke, background color Platte all display in white.

### ISSUE THREAD

**Issue by Luminary-S** [zsviczian/obsidian-excalidraw-plugin#1875]
Is there something wrong with my appearance setting. In OB editor, I have reset all appearance setting to default, but still have the same problem.
![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/9197835/59435503-7922-474e-a424-7bf51f2eccc2)

**Comment by zsviczian** [comment]
As requested on the Bug template, please include obsidian debug info: command palette/debug info.

This looks like a custom theme issue. Please try with the default Obsidian theme and disable all your CSS snippets. If that does not help, then please disable all other plugins, restart obsidian and try again. If the problem still persists, let me know (and be sure to include debug info)

**Comment by Luminary-S** [comment]
Thanks for your remind, I have found my problem, it relates to a plugin named "card library", which is a canvas card library plugin. I fix it when I close this plugin.
