### ISSUE TITLE
BUG: When EXcalidraw titles have Spaces in them, I can't rely on clicking the link to go into markdown mode to edit

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1877]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.6.5
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 127
	Plugins enabled: 12
		1: Outliner.md v0.1.5
		2: Excalidraw v2.2.2
		3: Git v2.24.2
		4: Annotator v0.2.11
		5: PDF++ v0.40.8
		6: S3agle v0.3.11
		7: Header Adjuster v1.0.0
		8: Plugins Annotations v1.0.12
		9: Regex Mark v1.7.0
		10: List Outline Helper v1.0.7
		11: Hover Editor v0.11.15
		12: Strange New Worlds v2.1.4

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
When EXcalidraw titles have Spaces in them, I can't rely on clicking the link to go into markdown mode to edit

![4](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/73203026/4d49bbb4-7585-4973-8ef3-10555fab60b4)
There is a space in the first OLD in the figure that I couldn't find in markdown via its link
But the other OLD has no space, so I can find it in markdown through its link

**Comment by zsviczian** [comment]
Fixed in 2.2.9. Will release over the weekend.
