### ISSUE TITLE
BUG: Link disappears after editing the text

### ISSUE THREAD

**Issue by dreyZZ** [zsviczian/obsidian-excalidraw-plugin#1878]
**Describe the bug**
Link disappears after editing the text

**To Reproduce**
1. Add a Text element to Canvas
2. Add link to it
3. Edit the Text

**Expected behavior**
Link should not disappear after editing the text...

**Screenshots**

https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/26909815/6aa2867f-7b0c-4ea8-9c99-07fb3443a530

**Environment**
SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.6.5
	Operating system: Windows 11 Pro 10.0.22631
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Obsidianite v2.0.2
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 35
	Plugins enabled: 32
		1: Advanced Tables v0.21.0
		2: Annotator v0.2.11
		3: Code Editor Shortcuts v1.14.0
		4: Colored Text v1.1.1
		5: Comments v0.2.0
		6: Copy Block Link v1.0.4
		7: File Color v1.1.0
		8: Find orphaned files and broken links v1.10.0
		9: Handwritten Notes v1.3.5
		10: Highlightr v1.2.2
		11: Mousewheel Image zoom v1.0.22
		12: Omnisearch v1.23.1
		13: Image in Editor v2.2.6
		14: Hover Editor v0.11.20
		15: Sortable v0.3.1
		16: Dataview v0.5.67
		17: Remember File State v1.1.2
		18: From Template v0.1.11
		19: Quick Explorer v0.2.8
		20: PDF++ v0.40.8
		21: Templater v2.3.3
		22: Image Toolkit v1.4.1
		23: Image Context Menus v1.8.0
		24: File Tree Alternative v2.6.0
		25: DB Folder v3.5.1
		26: Recent Files v1.4.1
		27: Calendar v1.5.10
		28: Outliner v4.8.1
		29: Zoom v1.1.2
		30: Kanban v2.0.51
		31: Excalidraw v2.2.8
		32: Iconize v2.14.2

**Comment by zsviczian** [comment]
I am able to reproduce.

**Comment by zsviczian** [comment]
fixed in 2.2.9.
Interestingly this issue is not new, it has been there for a number of versions now, but nobody raised the issue. I am surprised...
