### ISSUE TITLE
BUG: Neither insert link to file not working (mouse right click on excalidraw -> insert link to file) nor Command Pallete Excalidraw: Insert link to file

### ISSUE THREAD

**Issue by myownstandard** [zsviczian/obsidian-excalidraw-plugin#1879]
After updating to Obsidian 1.6.7 or Excalidraw 2.2.8 (I dont know when the bug happened exactly) "Insert link to file" stopped working.
I have tried to create new Obsidian vault ->  and install community plugin Excalidraw ,but no result, the same bug.
--------

**Your environment**
Obsidian 1.6.7 ; Excalidraw 2.2.8
Windows 10.
**Describe the bug**

**Screenshots**
https://github.com/user-attachments/assets/f6343282-056c-404a-ad2a-b0bc604b41c5

**Comment by zsviczian** [comment]
same as: #1873

Next time please 
1) follow instructions and include Obsidian debug info. It is not by mistake that I am asking for it. you can help the developer (me) greatly by being a good citizen and following the rules of the game. I am doing this in my hobby time, and it is not fun helping people who don't take the effort to help me back. Sorry for being so blunt. 
2) search issues before raising a new one as that saves me time of unnecessarily answering issues that are already resolved. The solution will be released in 2.2.9.

**Comment by myownstandard** [comment]
👍 sorry my bad..
