### ISSUE TITLE
FR: Auto text color and shape color adjustment based on the theme (Dark/light)

### ISSUE THREAD

**Issue by uvxv** [zsviczian/obsidian-excalidraw-plugin#1882]
As i use transparent background in all my drawings, would like to request the implementation of a feature that allows the text color and the shape color within the Excalidraw canvas to automatically adjust based on the active theme. This would improve readability and provide a more consistent user experience across themes.

**Comment by zsviczian** [comment]
have you explored all the available settings? This has already been implemented

<img width="1043" alt="image" src="https://github.com/user-attachments/assets/a0be6bba-e49b-4fce-bac2-b9be37757078">

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/823745ae-c63d-4c1f-9fdf-5178145ed3e0">
