### ISSUE TITLE
FR: display arrows between 2 frames

### ISSUE THREAD

**Issue by tomspeed22** [zsviczian/obsidian-excalidraw-plugin#1884]
Please have a look at the video shows that the arrows linking 2 boxes disappear when the bos are embedded into 2 different frames. The arrows should allows be visible.

https://github.com/user-attachments/assets/34f897a7-ea55-4037-aed1-0d29339895fd

**Comment by zsviczian** [comment]
use command palette "Toggle frame clipping"

**Comment by tomspeed22** [comment]
Thanks however there is an issue of update when moving the frame. Watch video in attachment from 49sec to 1min. Just wondering if it is intended. 

Another question : Is there a documentation about the toggle frame clipping, and other feature around the frame. 

Thanks for your amazing work !


https://github.com/user-attachments/assets/38bde1e4-e4cf-47eb-8042-ee48ac0fdbb9

**Comment by zsviczian** [comment]
Yeah. Frames are not perfect. I did not build the frame feature and have my own set of issues/headaches with them.
You could simply use a rectangle around the elements instead to visually group them. I personally very rarely use frames.
