### ISSUE TITLE
FR: After the new version update, some of my text and pictures became blurred

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1887]
After the new version update, some of my text and pictures became blurred
![image](https://github.com/user-attachments/assets/e6145544-4443-4851-a544-7db15ac0da0f)

**Comment by zsviczian** [comment]
I cannot reproduce. I am guessing there were some other changes in your Vault as well.

**Comment by jiajiala** [comment]
@zsviczian 
Found the problem, the size of the picture and text are very small, they were normal in the previous version, now they may be too small, fuzzy, it is not clear whether this can be improved
![image](https://github.com/user-attachments/assets/fdeb0b08-b288-425e-b232-306aecbb6e19)

**Comment by zsviczian** [comment]
I still do not understand what you are trying to do. This is either related to the quality of the image you are using or to some other settings. Everything is nice and crisp based on the testing I've just done.

<img width="461" alt="image" src="https://github.com/user-attachments/assets/cab766ea-cc40-4890-971e-f0f9a1cfe504">

<img width="435" alt="image" src="https://github.com/user-attachments/assets/f4ac28ed-cf23-4935-8ebd-9253c28be7ca">

---
and
<img width="453" alt="image" src="https://github.com/user-attachments/assets/309decd6-edaf-4b4e-a6c1-c08d291b524b">

<img width="437" alt="image" src="https://github.com/user-attachments/assets/465b71e0-0197-4644-a658-39a571ddda92">

----
<img width="1141" alt="image" src="https://github.com/user-attachments/assets/60f69182-7df9-4c22-bb88-a0e0586cb056">
