### ISSUE TITLE
FR: Option to add new excalicdraw files in subfolder as current folder 

### ISSUE THREAD

**Issue by Riven53** [zsviczian/obsidian-excalidraw-plugin#1892]
It's always very inconvenient to move new excalicdraw files from one folder to another. It always gets created in the same folder or in root vault instead of the folder I'm working on. Especially when I am in a hurry it is very inconvenient and makes it difficult to sort them..

A possible solution would be to add an option of this kind like the one which is there in obsidian settings for new files
![Uploading image.png…]()

I've had no alternative solution other than manually moving it

This kind of feature would be very helpful

![image](https://github.com/user-attachments/assets/f64f25e2-d189-4231-babd-6a754e2ded70)

**Comment by zsviczian** [comment]
In markdown view are you using any of these command palette actions to create the new image? This should address your need:
<img width="711" alt="image" src="https://github.com/user-attachments/assets/d97a21a8-3ba2-4ae7-8f96-733ba5b2173f">

Additionally, you can right click a folder or even a file and select create new drawing from the context menu. It will create the file in the location you need it.

<img width="393" alt="image" src="https://github.com/user-attachments/assets/8df507ed-9a10-45fa-a381-2a32c964fa28">

**Comment by Riven53** [comment]
Thank you very much. I did not know i could do this. Up until now i was using theshortcut in the ribbon 
![image](https://github.com/user-attachments/assets/d124a39f-36ec-459d-989a-9f9e283eec9f)
