### ISSUE TITLE
FR: Bidirectional file anchor linking

### ISSUE THREAD

**Issue by toooo** [zsviczian/obsidian-excalidraw-plugin#1894]
Hi!

I am trying to recreate https://www.eraser.io/ functionality with Obsidian
Is it possible to have single click from Excalidraw Object to Markdown anchor or line and vice versa?
I would like to mix drawing and text in a side by side view and link from one to another in a seamless one click way.

There is probably onClick event for excalidraw that could then do whatever is possible with obsidian API?
Second thing which I want to incorporate in obsidian is https://casual.pm/

Thank you

**Comment by zsviczian** [comment]
Like this?

https://github.com/user-attachments/assets/0959f265-e638-48b8-80ad-ace9452f9937


Try these settings:
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/c0d85008-6262-45f6-9e3b-5131c6398898">

**Comment by toooo** [comment]
Thank you for answer!

Is it possible to have this in opposite direction?
From file that links to obsidian object?

https://drive.google.com/file/d/1SopqCtH6UyAh8o-y8ptxvZMGOOwmdAwa/view?usp=drivesdk

**Comment by zsviczian** [comment]
The solution is nicely integrated inside Obsidian. I do not keep files I want to link outside Obsidian. But you can play with Obsidian:// links, however, they will only take you to the file, not the element.

https://github.com/user-attachments/assets/4aad674a-2c64-4a0f-bc78-8200b29fc479

**Comment by zsviczian** [comment]
I do not override how Obsidian links work, but you can use area, group, frame links to embed parts of the image, when you long click those, the features will work.

**Comment by toooo** [comment]
Aha Long Click is what I have missed!
Thank you!

**Comment by toooo** [comment]
@zsviczian just it seems this does not work if the other file open in sidebar is the same excalidraw file viewed in Markdown mode

**Comment by toooo** [comment]
I found out that the View mode does exactly that!
