### ISSUE TITLE
BUG: Unable to export obsidian files when excalidraw is enabled

### ISSUE THREAD

**Issue by Riven53** [zsviczian/obsidian-excalidraw-plugin#1896]
**Environment**
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 21
	Restricted mode: off
	Plugins installed: 60
	Plugins enabled: 49
		1: Wrap with shortcuts v1.3.0
		2: Tracker v1.14.0
		3: Templater v2.3.3
		4: Quick Latex v2.6.5
		5: Open Gate v1.11.6
		6: List Callouts v1.2.7
		7: Omnisearch v1.23.1
		8: Linter v1.25.0
		9: Latex Suite v1.9.4
		10: Dataview v0.5.67
		11: Charts View v1.2.7
		12: Charts v3.9.0
		13: Doubleshift v2.2.1
		14: Callout Manager v1.1.0
		15: Better Word Count v0.10.1
		16: Calendar v1.5.10
		17: Obsidian Columns v1.5.2
		18: Convert url to preview (iframe) v0.5.0
		19: Style Settings v1.0.8
		20: Iconize v2.14.3
		21: Advanced Tables v0.21.0
		22: DataLoom v8.16.1
		23: Text Format v3.1.0
		24: Custom File Explorer sorting v2.1.12
		25: DB Folder v3.5.1
		26: Execute Code v1.12.0
		27: Metadata Menu v0.8.7
		28: Math+ v0.7.0
		29: Hover Editor v0.11.20
		30: Ordered List Style v0.1.0
		31: Commander v0.5.1
		32: Paste image rename v1.6.1
		33: Global Search and Replace v0.5.0
		34: Advanced Canvas v3.0.6
		35: Better footnote v1.0.1
		36: PDF++ v0.40.8
		37: Note Definitions v0.24.0
		38: Kanban v2.0.51
		39: Obsidian_to_Anki v3.6.0
		40: Admonition v10.3.2
		41: Image Toolkit v1.4.1
		42: Dictionary v2.22.0
		43: TikZJax v0.5.2
		44: Pinned Notes v2.0.3
		45: Buttons v0.5.1
		46: Media Extended v3.2.4
		47: Completr v3.2.0
		48: LanguageTool v1.0.5
		49: Excalidraw v2.2.9

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

---

**Describe the bug**
When exporting obsidian files to pdf, i keep getting an error of failed to export

![image](https://github.com/user-attachments/assets/138f5255-9616-4b1e-b5c3-7d428b67ddd5)

I updated all of my plugins and reinstalled obsidian updater. I restarted obsidian and my computer multiple times. But whenever excalidraw is enabled export fails.

Exporting worked when i disabled excalidraw.

**To Reproduce**
1. Enable Excalidraw
2. Click on the 3 dots at the top right of the screen

![image](https://github.com/user-attachments/assets/e008721b-5fcc-46ad-ac3d-a49e49c061da)

3. Click on Export to PDF

![image](https://github.com/user-attachments/assets/512a0c82-3b45-4037-b772-075c0091511b)

5. Click on Export to PDF in the new popup

**Expected behavior**
I wanted it to Export as a pdf like it used to

**Screenshots**
![image](https://github.com/user-attachments/assets/fe08787d-f362-44fe-8a7b-9d03469bb6b4)

**Additional context**
I recently changed my excalidraw to create new files and attach them to active note

![image](https://github.com/user-attachments/assets/7bd31d1f-71e8-45ff-8a19-f5b2a03cae17)

But haven't used it in this note at all, i just linked to my excalidraw files like how i used to before and today it suddenly stopped exporting.

**Comment by Riven53** [comment]
This is what the console shows 

![image](https://github.com/user-attachments/assets/4a5d4fe3-653b-40ac-8098-8fd96adf124a)

![image](https://github.com/user-attachments/assets/dc4106cd-903f-4dc1-88ef-13b6f1850df4)

**Comment by Riven53** [comment]
The excalidraw plugin is having the problem when the drawing is inside obsidian columns. i removed all the drawings from my notes which were inside columns and it worked. But is there a way to make it work inside the columns?

**Comment by zsviczian** [comment]
what are "obsidian columns"?

**Comment by zsviczian** [comment]
Ah... I see: Obsidian Columns v1.5.2
Could you raise an issue with the developer of the Obsidian Columns plugin? I do not and cannot spend time making Excalidraw compatible with every plugin out there, except for the very few I use myself.
