### ISSUE TITLE
BUG: Mouse interaction broken/freezes in adjacent Excalidraw window (Win10/11)

### ISSUE THREAD

**Issue by moltob** [zsviczian/obsidian-excalidraw-plugin#1898]
**Your environment**

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.5
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Shimmering Focus v3.622
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 13
	Plugins enabled: 12
		1: Advanced Tables v0.21.0
		2: Tasks v7.6.1
		3: Style Settings v1.0.8
		4: Filename Heading Sync v1.9.1
		5: PDF++ v0.40.8
		6: Better Search Views v0.2.2
		7: Text Extractor v0.5.2
		8: Omnisearch v1.23.1
		9: Dataview v0.5.67
		10: Excalidraw v2.2.10
		11: Homepage v4.0.3
		12: Iconize v2.14.3

**Describe the bug**

Opening an Excalidraw drawing in an adjacent windows does not allow editing. When clicking on a form in order to drag it, the window does not show any interaction. In some cases, the form starts moving once the mouse leaves the Excalidraw window.

This is happening in two different vaults on two different machines (Windows 11 and Windows 10). However, both have a similar set of plugins. The issue persists if I disable all plugins except for Excalidraw and restart Obsidian.

**To Reproduce**
1. Go to a page with an embedded Excalidraw drawing.
2. Open that drawing in an adjacent window.
3. In the drawing, click on one of the forms and try to drag it to a new location.

**Expected behavior**
Form moves.

**Screenshots**
Showing a non-moving form does not come across very explanatory in a screenshot 😄 

**Additional context**
Windows 10 and Windows 11, two machines, separate vaults. Both vaults synced with official sync tool. While not 100% sure I do have the impression I did edit drawing in that mode before. So I'd claim this appeared within the last month or so.

**Comment by zsviczian** [comment]
Like this? Can't reproduce...

https://github.com/user-attachments/assets/35c9a306-e4fc-4093-aeed-48d45c0fbc6a

**Comment by zsviczian** [comment]
or like this?

https://github.com/user-attachments/assets/8cee096d-bd8e-4def-bd05-4c129b777cc0

can you share a screen recording?

**Comment by moltob** [comment]
Hmm... I just updated to the latest version and the effect is gone on my Win11 machine at home. Will retry tomorrow at work.

**Comment by moltob** [comment]
I just retried at work and there, the issue is also gone... I swear this was a problem for at least two weeks or so. But of course I am happy it has disappeared now.

Thanks a lot for providing such a tool and your quick response!

**Comment by zsviczian** [comment]
There was a performance bug introduced in the Excalidraw package and propagated to Obsidian in 2.2.8 and 2.2.9. That got resolved in 2.2.10... maybe the two are related.🤷‍♂️
