### ISSUE TITLE
Select the text 

### ISSUE THREAD

**Issue by JIBLIR** [zsviczian/obsidian-excalidraw-plugin#1899]
I'm always frustrated when I have already written a similar syntax in my previous text and I cannot select the text.

Maybe a system of selection like word might be rather comfortable

**The issue :**
![image](https://github.com/user-attachments/assets/0bc54154-85c2-4abe-8df6-b27568c76718)

**Comment by zsviczian** [comment]
I don't understand what you are looking for. This is the LaTeX editor? Are you looking for a feature to copy the script of a formula to the clipboard without having to open the rendered equation in edit mode?

**Comment by JIBLIR** [comment]
**It's not about formula, but about the selection of a part of a text in order to copy, delete... In obsidian there is a system like that :** 

![Capture d'écran 2024-07-24 105204](https://github.com/user-attachments/assets/d7d909de-fe49-4aa7-addb-f8274688ea01)

**Comment by zsviczian** [comment]
what is that system in Obsidian. Sorry, but the image above does not help my understanding (yet)
