### ISSUE TITLE
support for [[links]]

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#19]

**Comment by walter-cavinaw** [comment]
Honestly this would be huge. I would like to build out some process diagrams, that link to different checklists and this would be perfect. The mermaid diagrams are to restrictive!

You're doing a great job. Thank you for building this plugin.

**Comment by Quorafind** [comment]
If you could make this work, I really appreciate it! I can use it to help my nephew to learn something easily. Thanks for your hard job. This plugin and you are both awesome.

**Comment by Mytakeon** [comment]
Does this mean support for [[links]] in excalidraw files, or better support of [[file.excalidraw]] links in markdown files?

**Comment by FriedrichStein** [comment]
Internal linking would be amazing! Great plug-in. Exactly what I was looking for. Thank you!

**Comment by Ka-hu** [comment]
[[file.excalidraw]] links would be nice, I'd like to link to them from documents to quickly edit drawings without opening them from their folder.

**Comment by zsviczian** [comment]
resolved with Excalidraw 1.1
