### ISSUE TITLE
BUG: The file is moved to the root directory after the rename

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1905]
Renaming the EXcalidraw file through F2 causes the file to be moved to the root directory

![4](https://github.com/user-attachments/assets/48fb549a-764e-4cdb-b19a-369600330f5c)

In addition, it is expected that the file name of EXcalidraw can be completely consistent with the logic of markdown file naming, some file management plug-ins will use the name mechanism to image folders, if the naming logic of EXcalidraw is not consistent with markdown, it is likely to conflict with other plug-ins.

**Your environment**
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.2.11

**Comment by zsviczian** [comment]
ups. my bad. Sorry. fixed in 2.2.12 will release in a moment.
