### ISSUE TITLE
BUG: Can't undo text element that was just pasted

### ISSUE THREAD

**Issue by eelpik** [zsviczian/obsidian-excalidraw-plugin#1906]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: #1 SMP PREEMPT_DYNAMIC Thu Jul 18 21:25:20 UTC 2024 6.9.10-100.fc39.x86_64
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.2.11

**Describe the bug**
When I paste any element or group of elements that has text in it, and then I immediately try to undo the paste, the undo ignores the newly pasted text. If the element is a shape, then the shape itself gets properly removed, but any text inside it stays.

**To Reproduce**
1. Copy an element or group of elements that has text in it
2. Paste it, and don't deselect it
3. Try to undo the action

**Expected behavior**
I expect the pasted text to be removed or "unpasted" when undoing

**Screenshots**
![issue](https://github.com/user-attachments/assets/a6d11062-114e-485b-8cf8-3b14eb62b051)
Just in case it's hard to tell, the GIF ends after the third undo press.

**Additional context**
This happens whether the element was copied from the same document or a different one. Also, if I copy paste just the raw text, undoing works as expected. Lastly, this bug doesn't seem to occur on excalidraw.com.

Thank you!

**Comment by zsviczian** [comment]
Interestingly this only happens if the element remains selected. If after pasting you click the canvas, then undo works as expected.

**Comment by zsviczian** [comment]
will release the fix in 2.2.13, but only next week. 
should you want to use the fix now, you can download this zip, unzip the main.js, and replace main.js in your `Vault/.obsidian/plugins/obsidian-excalidraw-plugin` folder. Note `.obsidian` is a hidden folder.

[main.js.zip](https://github.com/user-attachments/files/16402552/main.js.zip)

**Comment by eelpik** [comment]
Perfect, thanks!
