### ISSUE TITLE
Open new drawing without saving

### ISSUE THREAD

**Issue by gdlazcano** [zsviczian/obsidian-excalidraw-plugin#191]
Would it be possible to have an option for opening a drawing without having a file associated? Kinda like a disposable whiteboard inside of obsidian

**Comment by zsviczian** [comment]
You can always click `more options/delete file` after your whiteboarding session.  Does that work for you?
![image](https://user-images.githubusercontent.com/14358394/137013627-4f4cf7c5-2ab4-493f-9c44-966acdcb0df9.png)

**Comment by DatsGabs** [comment]
yes, but it'd be neat if I didn't have to

**Comment by zsviczian** [comment]
In my view it would be more complicated. How would you differentiate if you want to open a whiteboard for temporary use, or open a new drawing that should be automatically saved?
