### ISSUE TITLE
FR: EXcalidraw文件夹变为.EXcalidraw

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1911]
The EXcalidraw folder becomes. EXcalidraw

EXcalidraw is not my notes folder, it has a lot of plugins and images downloaded in it, but it is not my notes and should not appear in my note tree or search

**Comment by jiajiala** [comment]
![image](https://github.com/user-attachments/assets/4022c1b6-8bfc-4fd0-ae2d-66226d49cb7e)
@zsviczian Just like.obsidian, it should appear in my note tree as a project file, not a note file

**Comment by zsviczian** [comment]
that will not work. Obsidian does not index hidden folders.
Also I disagree with the notion. Excalidraw files are note files, the whole idea is they appear just as any other document. I actually have very few "traditional" markdown files in my vault. Most of them are markdowns including the Excalidraw markup such that they all have a text and a graphical side.
