### ISSUE TITLE
Image Element Preview

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#192]
I tried this version and thought it was great, but I accidentally updated to an older version and found that the images were not saved in the obsidian attachments, causing me to look around for the images I had previously added, I wonder if the ability to store images will be available in the official version

**Comment by zsviczian** [comment]
Yes. the final version will store files in attachments. 

Please be careful with the demo version. The file format will change. I will not include script to update files you modify with the demo version to the final version. You should be able to modify files with a tool like regex replace in notepad++... but it will require some programming skills, and I cannot guarantee outcome.
