### ISSUE TITLE
BUG: Excalidraw is enabled, but behaves as if it is not enabled.

### ISSUE THREAD

**Issue by necvetna** [zsviczian/obsidian-excalidraw-plugin#1921]
SYSTEM INFO:
	Operating system: android 10 (HUAWEI ART-L29)
	Obsidian version: 1.6.7 (149)
	API version: v1.6.6
	Login status: not logged in
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.2.13

The plugin is enabled, but the "draw" button is not displayed. The settings are also unavailable. This is the first download.
![Screenshot_20240804_112605_md obsidian](https://github.com/user-attachments/assets/b80ec262-4cdd-4e8a-8996-f50ea1289343)

![Screenshot_20240804_112629_md obsidian](https://github.com/user-attachments/assets/5567f671-1595-4ec4-abe3-5e6f91fee96f)

![Screenshot_20240804_112646_md obsidian](https://github.com/user-attachments/assets/c4f116f7-06b4-49e0-abe6-597710c47491)

**Comment by zsviczian** [comment]
This sometimes happens on HUAWEI devices. You need to update the Android webview component.  Search closed issues for an answer.

see: #181 
also related: #1747

**Comment by necvetna** [comment]
Thanks, now I know what the problem is. I have the latest version of Huawei WebView installed, but I need Android System WebView. I google how to change it. Two methods are not suitable for me (installing Google services after resetting the device to factory settings, or getting root). I can't do that. But that's my problem.

Thank you very much for help.

**Comment by zsviczian** [comment]
In the past, I was able to install Chorme Browser Beta and it came with its own webview component. I was able to install that webview without any elevated privileges. 

The way I was able to locate the problematic code earlier was by halving the code until I was able to eliminate the part that caused the the webview compiler to choke. This is relatively easy albeit tedious. You need to enable debugging on your android device, hook it up to a PC and start investigating. If you have the skills and want to play with this I am happy to give you a debug build of the main.js. There is probably a single line of code causing this problem, once we know it I can work around it and all the Huawei users would be thankful. Let me know if you want to give this a try.  Warning this can easily eat up multiple days of your time...

**Comment by necvetna** [comment]
I also installed a beta version of the Chrome browser, but it didn't help. 

![IMG_20240804_172718_619](https://github.com/user-attachments/assets/9cd94b58-7739-4342-a190-751d70e341f7)

Unfortunately, I don't have a PC and the necessary skills.
