### ISSUE TITLE
FR: Expose `tex2dataURL()` through the API

### ISSUE THREAD

**Issue by firai** [zsviczian/obsidian-excalidraw-plugin#1930]
**Is your feature request related to a problem? Please describe.**
I'm trying to write a script that could help address #1759, by doing two things:
1. allows resetting the size of an inserted $\LaTeX$ object (image) to the "default" size, by recomputing the image size with [`tex2dataURL()`](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/src/LaTeX.ts#L57) (maybe there's a more efficient way of doing this) and assigning the default image size to the current object (image),[^1] and
2. allows changing the [`scale`](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/src/LaTeX.ts#L59) used to calculate the image size above, which seems to be defaulted/hardcoded as `4` at the moment.

[^1]: I understand that regenerating the LaTeX image from the input and coordinates, and then deleting the original object may cause problems with snapped objects.

**Describe the solution you'd like**
Expose [`tex2dataURL()`](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/src/LaTeX.ts#L57), which does not seem to be accessible from scripts at the moment, through the ExcalidrawAutomate API.

**Describe alternatives you've considered**
- Compute the "default" size with [`addLatex()`](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/src/ExcalidrawAutomate.ts#L1546), retrieving the size from the new object, assigning it to the old object, and then deleting the new object.[^1] However, having to add and delete the new object adds unnecessary complexity, and changing the `scale` isn't possible (at least at the moment).
- Adding a parameter to `addLatex()` to allow the `scale` to be changed.
- Add function(s) in the API that directly do what I proposed above.
- Add commands in the GUI to do what I proposed above.

**Comment by zsviczian** [comment]
I've exposed tex2dataURL in 2.4.0-beta-3. will release soon.
