### ISSUE TITLE
FR: Improve PDF annotation by adding frames instead of rectangles as 'border box'

### ISSUE THREAD

**Issue by JoeKays** [zsviczian/obsidian-excalidraw-plugin#1931]
Currently, when importing a PDF there is the option to 'Add border box', which adds a rectangle around each page.

Having frames instead of rectangles would enable a number of useful features:
1. displaying the page number as the frame title
2. linking to the frame/page by page number
3. selecting all annotations made on a page
4. deconstructing a page including all annotations (using the respective script from the library)

What do you think?

**Comment by zsviczian** [comment]
I was thinking of exactly the same a couple of days ago. In addition, you could use frames to crop PDF pages in place, without needing to create a separate crop file. I also like the idea of page numbers as a frame title - I did not think of that.

The drawback of frames is frame clipping, so if you have arrows pointing from one page to another that can lead to some additional friction in the workflow.

**Comment by zsviczian** [comment]
I've implemented this in `2.4.0-beta-4`, I will release this to the beta channel tonight.

This solution is so good! Why did I not think of this earlier :)

Regarding the arrows pointing between frames, with very little practice you can create arrows outside the frame and this becomes a non-issue.

The additional benefit of this approach is how you can crop pages in place.

I won't release this new feature to community plugins until September, but if you'd like to have it earlier you can install the beta release. I explain how to install beta releases here: https://youtu.be/2poSS-Z91lY
