### ISSUE TITLE
BUG: Writing Responsiveness With Apple Pencil

### ISSUE THREAD

**Issue by HarzIV** [zsviczian/obsidian-excalidraw-plugin#1936]
SYSTEM INFO:
	Operating system: ios 17.5.1 (Apple iPad12,1)
	Obsidian version: 1.6.7 (149)
	API version: v1.6.7
	Login status: not logged in
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 4
	Plugins enabled: 4
		1: Advanced Tables v0.21.0
		2: Excalidraw v2.3.0
		3: Quick Latex v2.6.5
		4: Ink v0.2.6

**Describe the bug**
When writing with an Apple Pencil, there is no way to get a smooth and responsive writing experience, letter often get squished when trying to write fast and over all the tracking doesn’t work correctly.

**To Reproduce**
1. Go to 'Open a excalidraw document'
2. Simply try writing using an Apple Pencil
3. See error

**Expected behavior**
A accurate and responsive tracking like when you write in Goodnotes or apple notes

**Screenshots**
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/c2f34d10-0cc3-4f0f-81ce-2a44492222e9">

**Comment by zsviczian** [comment]
Try setting autosave to "moderate" or "rare". This should likely improve the performance, but keep in mind, Excalidraw is not designed/optimized for long-form handwriting. It is designed as a vector illustration tool that can handle the occasional scribble. As such, handwriting will likely never feel optimal. 

 Please read the description in settings explaining the consequences of changing autosave timing.

You can also experiment with custom pens for a better line smoothing (or rather no smoothing) experience. see this video for more details: https://youtu.be/OjNhjaH2KjI

<img width="1081" alt="image" src="https://github.com/user-attachments/assets/bb5793d2-9a7c-4fde-b466-ce4279282353">

**Comment by HarzIV** [comment]
Thanks for the quick reply this worked perfectly
