### ISSUE TITLE
FR: Multicolor for texts

### ISSUE THREAD

**Issue by 0PandaDEV** [zsviczian/obsidian-excalidraw-plugin#1947]
**Is your feature request related to a problem? Please describe.**
I'm used to this from other whiteboard apps like Affine or Miro, and it's one of the few features holing me back from using Excalidraw. 

**Describe the solution you'd like**
It would be useful to have a popup every time you select a piece of text where you can then choose different formatting options, not only color changes.

**Comment by zsviczian** [comment]
Yeah, currently this is cumbersome. This would need to be solved at the excalidraw component level, not in the plugin. Please raise an issue at https://github.com/excalidraw/excalidraw/issues
