### ISSUE TITLE
BUG: Code block is always over drawing

### ISSUE THREAD

**Issue by axtrace** [zsviczian/obsidian-excalidraw-plugin#1948]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112 23.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 9
	Plugins enabled: 7
		1: Remotely Save v0.5.18
		2: Excalidraw v2.3.0
		3: Dataview v0.5.67
		4: ExcaliBrain v0.2.15
		5: Linter v1.25.0
		6: Shortcuts extender v2.2.0
		7: Tasks v7.9.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
Code block is always over drawing

**To Reproduce**
1. Go to .excallidraw in Obsidian
2. Click right mouse button on and choose "Paste as code""
3. Swich to line tool (press 5)
4. Draw under code block
5. Select code block, rmc and choose (send to back)
6. Nothing happens

**Expected behavior**
Drawing is over code block

**Screenshots**
<img width="383" alt="image" src="https://github.com/user-attachments/assets/3f962281-030f-45d5-ad10-b3e8717f2d53">

**Additional context**
`Bring to front` or `bring forward` on drawnig isn't work too

**Comment by zsviczian** [comment]
not a bug, but a feature of how code blocks are implemented. sorry. Can't change this.

**Comment by GavinPen** [comment]
I ran into this problem when I inserted blocks of code via Paste Code Block, then tried to draw arrows between lines of code. 
Each code block hides the ends of the arrow:  
<img width="878" height="304" alt="Image" src="https://github.com/user-attachments/assets/737befeb-a33c-42b3-9e44-ba32a0cc5c85" />
A partial workaround was to reduce the opacity of the code blocks.  
This meant that the arrow was shown - but the text in the blocks became fainter:  
<img width="889" height="311" alt="Image" src="https://github.com/user-attachments/assets/62311c73-d82c-445b-9e17-9a4a8d1e6987" />

**Comment by GavinPen** [comment]
As an aside, when you hover over a code block node, it displays the text 'click to interact'.  
If you click, you see a menu with 3 options displayed:  
- narrow to heading  
- zoom to fit (ie zoom drawing so that this node occupies the whole visible width of the drawing pane)  
- settings 

However, to edit the text in the node (Edit Code Block), you need to click again.

**Comment by zsviczian** [comment]
@GavinPen , use markdown images instead.
You can configure single click editing in settings.

**Comment by GavinPen** [comment]
Thanks @zsviczian.   
I tried adding a code block in a markdown image and successfully added an arrow on it without the arrow being hidden.   
The 'Single click to edit embedded markdown' setting is also useful.
