### ISSUE TITLE
BUG: Frame outline disappeared (totally invisible)

### ISSUE THREAD

**Issue by Bobatev** [zsviczian/obsidian-excalidraw-plugin#1953]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.7.0
	Installer version: v1.5.12
	Operating system: Windows 11 Pro 
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.7.14
	Snippets enabled: 25
	Restricted mode: off
	Plugins installed: 35
	Plugins enabled: 32
		1: Excalidraw v2.3.0
		2: Recent Files v1.4.1
		3: BRAT v1.0.1
		4: Calendar v1.5.10
		5: Callout Manager v1.1.0
		6: Callout Suggestions v1.0.2
		7: Dataview v0.5.67
		8: Editing Toolbar v2.4.16
		9: floating toc v2.4.7
		10: Heading Level Indent v1.0.3
		11: Highlightr v1.2.2
		12: Homepage v4.0.3
		13: Iconize v2.14.3
		14: Image in Editor v2.2.6
		15: Minimal Theme Settings v8.0.2
		16: Mononote v1.2.2
		17: Multi-Column Markdown v0.9.1
		18: Note Toolbar v1.9.12
		19: Omnisearch v1.24.0
		20: Pandoc Plugin v0.4.1
		21: Paste image rename v1.6.1
		22: Paste URL into selection v1.7.0
		23: Periodic Notes v0.0.17
		24: Readwise Official v2.0.1
		25: Share Note v0.8.14
		26: Style Settings v1.0.8
		27: Tag Wrangler v0.6.1
		28: Templater v2.4.1
		29: Text Format v3.1.0
		30: Timestamp Notes v1.0.8
		31: Tracker v1.14.0
		32: Underline v1.3.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
I just opened a presentation I'm working on (haven't changed anything since yesterday) and all frames disappeared. Slideshow script is working properly but the frames outline is invisible. Here is a short video capture.  https://www.loom.com/share/0644ea356167463d8f05bc90456b0f0d?sid=39c70562-f776-4ba0-b64b-657f07fbbb88

Here's the md:

[Businessmagic VSL.excalidraw - Copy.md](https://github.com/user-attachments/files/16722460/Businessmagic.VSL.excalidraw.-.Copy.md)

I tried to open the file with only Excalidraw plugin enabled - same.

**Comment by zsviczian** [comment]
Yes, this happens sometimes when for some reason the presentation script does not close correctly.
You can open frame settings for the page with the command palette action

![image](https://github.com/user-attachments/assets/0499d9fe-8826-4ac5-a8b5-36baeda309c5)
