### ISSUE TITLE
BUG: Fourth font not loaded

### ISSUE THREAD

**Issue by YandLiu** [zsviczian/obsidian-excalidraw-plugin#1955]
**Describe the bug**
Recently I found the fourth font was not displayed in the option panel, I have to change the font family by directly editing the source code.

Can reproduce using a blank vault.

**Expected behavior**
The fourth font was displayed properly before.

**Screenshots**

![20240824_125036](https://github.com/user-attachments/assets/2d2f1308-343d-4cbe-82e0-6a7e7da86503)

![20240824_124929](https://github.com/user-attachments/assets/c17e6ee3-a2ef-49c4-a7e1-db1efdf92fe9)

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 11 Home China 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.3.0

```

**Comment by zsviczian** [comment]
The fourth font was renamed to "local font". Did you try the Local Font from the font list and it did not work?
If yes, please share the font file so I can take a look.

**Comment by YandLiu** [comment]
Thank you, the issue is resolved. Just noticed "Local Font" is a clickable item, I thought it was a menu separator since it doesn't have an icon before the name.
