### ISSUE TITLE
FR: Tilt for SPEN

### ISSUE THREAD

**Issue by FireRedDev** [zsviczian/obsidian-excalidraw-plugin#1957]
**Is your feature request related to a problem? Please describe.**

tilt doesnt seem to work on galaxy tab s9 fe with spen

**Describe the solution you'd like**

tilt works
**Describe alternatives you've considered**

dealing with it

**Additional context**

**Comment by zsviczian** [comment]
I only support cross platform features. As such I do not support apple pencil buttons, and special spen features. These features would anyway require the relevant vendor SDK to be included in the Obsidian mobile app which is out of my control.
