### ISSUE TITLE
BUG: Links dragged from Zotero to Excalidraw are not recognized correctly

### ISSUE THREAD

**Issue by Kiss-World** [zsviczian/obsidian-excalidraw-plugin#1963]
In the Obsidian editor, it can correctly recognize.

<img src="https://github.com/user-attachments/assets/02f4ba3b-27ba-404a-93fa-82531bdfef9f" alt="示例图片" width="500">

In Excalidraw, it cannot correctly recognize and extracts the link when it encounters the first ")".

<img src="https://github.com/user-attachments/assets/4cbcd781-1b82-441d-85ea-a08a91894798" alt="示例图片" width="500">

This issue has occurred in both the EPUB and web contexts within Zotero. I am using the official version of Zotero 7, Obsidian at V1.7.0, and Excalidraw at 2.3.0.

**Comment by zsviczian** [comment]
Fixed in 2.4.0-rc-1 (will publish tonight)
https://youtu.be/2poSS-Z91lY
