### ISSUE TITLE
BUG: Transclusions do not respect the front/back positioning in the drawing

### ISSUE THREAD

**Issue by denisgorod** [zsviczian/obsidian-excalidraw-plugin#1965]
**Your environment**
(Done in a sandbox vault for clearer results)
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.5
	Operating system: Windows 11 Home 10.0.22631
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.3.0

**Describe the bug**
Transclusions (embedding Markdown files directly) are forced to be on a higher layer than non-transclusions.

**To Reproduce**
1. Embed a Markdown file.
2. Create a filled rectangle
3. "Bring to front" for the rectangle
4. The rectangle is still behind the embed.
(Interestingly enough, the order is changed for selection priority, but not for visualization.)
(In the generated .svg all mardown embeds are always last (= in front) regardless of used commands in Excalidraw. Manually changing the order of the items in the .svg puts the rectangle over the foreignObject managing the Markdown file.)

**Expected behavior**
The rectangle should be in front of the Markdown file.

**Screenshots**
![image](https://github.com/user-attachments/assets/4ce2064e-e59e-41a4-94ad-d9895ec8463a)

**Additional context**
Let me precise the use case: I am embedding lots of small Markdown files (no scrolling needed) in the drawing, and I would like the user to be able to click on the embeds to get to the file (I am using Obsidian Publish, and rely on the generated .svg for this reason). For this I intended to create a transparent filled block with the link **on top** of the embed, which is where I encountered this behavior. Is this expected? If it is, is there a better way to solve my problem?

Thank you for your wonderful plugin :)

**Comment by zsviczian** [comment]
Not a bug, but a "feature" - or at least a consequence of the technical solution. Embeddables live on a layer above the drawing. You can open a feature request for this on https://github.com/excalidraw/excalidraw/issues though I doubt a solution will get worked on any time soon.

**Comment by denisgorod** [comment]
If anyone runs into this: it is possible to regex the generated .svg to reorder the elements in the corresponding <a href = ...> environment so that the solid block which has an attached link is above the embed (the block has to be colored transparent as well, which also can be achieved by a careful regex query).
