### ISSUE TITLE
BUG: Hand-drawn font not working on Windows and iOS

### ISSUE THREAD

**Issue by Laurensdc** [zsviczian/obsidian-excalidraw-plugin#1968]
**Your environment**
```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.5
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Obsidian Nord v0.2.0
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 11
	Plugins enabled: 9
		1: Vimrc Support v0.10.1
		2: Heading Shifter v1.5.1
		3: Relative Line Numbers v3.0.0
		4: Emoji Shortcodes v2.2.0
		5: Local Backup v0.1.7
		6: List Callouts v1.2.7
		7: Linter v1.25.0
		8: WakaTime v1.0.2
		9: Excalidraw v2.3.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Describe the bug**
When opening a new Excalidraw file and typing text with the hand-drawn font shows a generic sans-serif font instead.
![image](https://github.com/user-attachments/assets/fd05e29c-32a9-4e37-8d1e-5d0fa45fd800)

I manually installed the font on my Windows machine as well
![image](https://github.com/user-attachments/assets/2c1d5a4d-07ea-47c4-8882-5525c411b710)

When I enable a fourth font in the miscellaneous options, I can select the default Virgil font and it works when selecting text with the fourth font.
However, all my drawings that I did on MacOS with the hand-drawn font now should be updated to use the fourth font to work around this issue.

**To Reproduce**
1. Open a new Excalidraw file
2. Insert text
3. Select hand-drawn font
4. It's not Virgil

**Expected behavior**
It's the Virgil font.

**Additional context**
On iOS I also have the same issue.

**Comment by zsviczian** [comment]
you seem to have some modification installed. The properties panel does not look as expected. Could this be the theme you are using or your custom snippet, or one of the plugins... I don't know, but I can see you have a different excalidraw running - based on the looks, not 2.3.0.

Please test in an empty vault with only Excalidraw installed.

![image](https://github.com/user-attachments/assets/51eb8843-cdc7-4813-9fc8-14818de67d11)

**Comment by Laurensdc** [comment]
In a Sandbox vault, I'm not having it. So it doesn't seem strictly Windows related.
However, when disabling every plugin except from Excalidraw, and using the default theme, I'm still not seeing the Virgil font.

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.5
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 11
	Plugins enabled: 1
		1: Excalidraw v2.3.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Comment by Laurensdc** [comment]
Ok so getting rid of the plugin and reinstalling it did the trick!
Would it help you if I upload the "broken" version of the plugin?

**Comment by Laurensdc** [comment]
My gut feeling says that Obsidian Sync didn't correctly sync all the files? Maybe the `data.json` got synced with a different version of `main.js` or something like that?

**Comment by zsviczian** [comment]
no need to share the broken plugin. Obsidian sync could have caused a broken data.json or something else...  Glad you got it resolved.
