### ISSUE TITLE
FR: Disable the initial page with the text and drawing

### ISSUE THREAD

**Issue by alltiagocom** [zsviczian/obsidian-excalidraw-plugin#1969]
I would like to see a blank page on every new drawing instead of this:
![image](https://github.com/user-attachments/assets/44773f34-2e80-4429-a2ff-33a93ffcccac)

Can we do that? I tried saving the template without it, but it always comes back. 
I'm aware that this isn't an actual drawing and it goes away as soon as something is added to the canvas, but it's just a personal preference that I would like to see a completely blank page.

Thank you.

**Comment by zsviczian** [comment]
To be honest I was unhappy with your request (at first). Then grudgingly I implemented the feature. Then I tested it and realized... I will probably turn it off for myself as well 😀
You will find this in 2.4.0. I plan to release over the weekend.

![image](https://github.com/user-attachments/assets/1668d4ce-c532-43e8-8152-1e983d541c36)

**Comment by alltiagocom** [comment]
> To be honest I was unhappy with your request (at first). Then grudgingly I implemented the feature. Then I tested it and realized... I will probably turn it off for myself as well 😀 You will find this in 2.4.0. I plan to release over the weekend.
> 
> ![image](https://private-user-images.githubusercontent.com/14358394/362627225-1668d4ce-c532-43e8-8152-1e983d541c36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjU1MjEsIm5iZiI6MTcyNDkyNTIyMSwicGF0aCI6Ii8xNDM1ODM5NC8zNjI2MjcyMjUtMTY2OGQ0Y2UtYzUzMi00M2U4LTgxNTItMWU5ODNkNTQxYzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA5NTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYTJiNzc0M2Y3N2NmOTgzOTYyYjM1MjkzYmE3MWQwMGY0NjdjMWNhODdiYTExOGJjZDdjNzQzMzVjZmZlNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2_Kd_mELiGESMfC_418VyxFH8_S2wjg4yj7Wj67K8qI)

I guess that was one of the things I learned over the years: try it / test it before assuming it's not for me 😉 
Good to know you were ok with implementing it and make it a choice. Maybe some people like to see it.
I appreciate it! 🙌

**Comment by alltiagocom** [comment]
> I guess the splash screen serves its purpose in the beginning. It helps people find help like GitHub or Discord. Later, I can see the value of starting with a blank canvas.

Exactly. As a first "help page", it serves its purpose.
