### ISSUE TITLE
FR: HotKeys implementation

### ISSUE THREAD

**Issue by alltiagocom** [zsviczian/obsidian-excalidraw-plugin#1972]
I don't know if this is possible or easy to implement, but would be great if we could have some hotkeys to make the workflow faster. 2 that I immediately missed was "Duplicate" and "Group Selection".
I use those all the time in Photoshop, and not having them in Excalidraw is a bummer.

If that's something you could implement, I believe it would be a great addition to the app. 💪

**Comment by zsviczian** [comment]
The hotkeys are there.  CTRL+D and CTRL+G.
2.4.0 comes with a feature to override Obsidian built-in hotkeys (such as CTRL+G by default opens graph view). from the next release you can decide which Obsidian Hotkeys to honor and which to override while using Excalidraw.

You can find all the hotkeys here:
![image](https://github.com/user-attachments/assets/2203a371-ae21-4f6d-8e27-fcf00cb45cfa)

If you are missing any hotkeys you can do it yourself by creating a dedicated Excalidraw script and assigning your own hotkey to it.  For example the below script will toggle the shape menu in tray mode when an element is selected. just an example... the options are unlimited:

```js
currentState = ea.getExcalidrawAPI().getAppState().openMenu;
if(currentState === "shape") {
  ea.viewUpdateScene({appState: {openMenu: null}});
} else {
  ea.viewUpdateScene({appState: {openMenu: "shape"}});
}
```


I suggest looking around before opening feature requests...

**Comment by alltiagocom** [comment]
> The hotkeys are there. CTRL+D and CTRL+G. 2.4.0 comes with a feature to override Obsidian built-in hotkeys (such as CTRL+G by default opens graph view). from the next release you can decide which Obsidian Hotkeys to honor and which to override while using Excalidraw.
> 
> You can find all the hotkeys here: ![image](https://private-user-images.githubusercontent.com/14358394/362697712-2203a371-ae21-4f6d-8e27-fcf00cb45cfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mzc2NjIsIm5iZiI6MTcyNDkzNzM2MiwicGF0aCI6Ii8xNDM1ODM5NC8zNjI2OTc3MTItMjIwM2EzNzEtYWUyMS00ZjZkLThlMjctZmNmMDBjYjQ1Y2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEzMTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZjVkMTA4YzliMTk5MzQyYTI1YjE1MmRiYjMzY2MyYjJjZmVhMGQ0YTZkZGFiZjYwOWRjMzdmNDc0MWRhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HrzEqTvCBbOZDy1FBzEVNnZbPZ1aSFFcQFFMO7DDEgk)
> 
> If you are missing any hotkeys you can do it yourself by creating a dedicated Excalidraw script and assigning your own hotkey to it. For example the below script will toggle the shape menu in tray mode when an element is selected. just an example... the options are unlimited:
> 
> ```js
> currentState = ea.getExcalidrawAPI().getAppState().openMenu;
> if(currentState === "shape") {
>   ea.viewUpdateScene({appState: {openMenu: null}});
> } else {
>   ea.viewUpdateScene({appState: {openMenu: "shape"}});
> }
> ```
> 
> I suggest looking around before opening feature requests...

Thank you for the extra info
