### ISSUE TITLE
Warning/Error when loading

### ISSUE THREAD

**Issue by munish259272** [zsviczian/obsidian-excalidraw-plugin#1975]
I do not have any issue but in the developer console it shows this error

`
plugin:obsidian-excalidraw-plugin:98 [Deprecation] Custom state pseudo classes are changing from ":--webkit-scrollbar" to ":state(webkit-scrollbar)" soon. See more here: https://github.com/w3c/csswg-drafts/issues/4805
harvestStyles @ plugin:obsidian-excalidraw-plugin:98
`

If it can be ignored i am ok with that.

**Comment by zsviczian** [comment]
can be safely ignored.
