### ISSUE TITLE
BUG: Filename Not Displayed Correctly

### ISSUE THREAD

**Issue by caiovictor09** [zsviczian/obsidian-excalidraw-plugin#1978]
Description: When saving a file in the Excalidraw plugin for Obsidian, the filename is not displayed correctly if it is too long. If the filename exceeds a certain length, only "..." is shown instead of the actual filename being typed.

Steps to Reproduce:

    Open the Excalidraw plugin in Obsidian.
    Attempt to save a file with a very long filename.
    Observe that as you type, the filename is truncated and replaced with "..." instead of showing the full name.

Expected Behavior: The full filename should be visible as it is typed, regardless of its length.

Actual Behavior: The filename is truncated and only "..." is displayed, making it impossible to see what is being typed.

Environment:
![Captura de tela 2024-08-30 113034](https://github.com/user-attachments/assets/3d47f20c-cd41-47b3-bf50-ef3d4bc22aec)
![Captura de tela 2024-08-30 113043](https://github.com/user-attachments/assets/11007a46-90f2-4157-af5f-b8feab5ae8cc)

    Obsidian Version: [1.6.7]
    Excalidraw Plugin Version: [2.3.0]
    Operating System: [Windows 11]

Additional Information: This issue makes it difficult to manage files with long names and can lead to confusion or errors in file naming.

**Comment by zsviczian** [comment]
do you see the full filename for normal markdown files? i.e. does this only impact Excalidraw or this is general Obsidian behavior?

**Comment by caiovictor09** [comment]
My bad, this is a general Obsidian behavior. I tested creating a lot of notes with long names, but this error persists.

**Comment by zsviczian** [comment]
I don't think this is an error BTW - but I can understand you have a different preference. If I were you I'd call this a feature request. anyway, I will close this issue. If you want you can open a feature request with Obsidian.
