### ISSUE TITLE
FR: I hope to customize the settings to adjust the character width when dragging Zotero annotations into Excalidraw

### ISSUE THREAD

**Issue by Kiss-World** [zsviczian/obsidian-excalidraw-plugin#1980]
I often use Zotero to directly drag annotations into Excalidraw. However, due to some texts being longer, and the dragged content only displaying in one line, I have to manually adjust it every time, which is quite cumbersome. See the diagram below for an illustration.

![image](https://github.com/user-attachments/assets/ce6d3198-4153-41ad-b2b3-0304dfe7aef7)

**Comment by zsviczian** [comment]
If you copy/paste the text will be wrapped.

**Comment by Kiss-World** [comment]
Thank you, I have tried it and it indeed works. The current issue is that Zotero cannot directly copy the annotation text + annotation link content that we currently need. I have used the Zotero plugin TAGS, which provides some functionality for copying annotations, but unfortunately, its features are not fully complete, and I have already inquired about it.

https://github.com/windingwind/zotero-actions-tags/discussions/115#discussioncomment-8731031

Is it possible to implement formatting for this kind of drag behavior?
@zsviczian

**Comment by zsviczian** [comment]
everything can be developed, but it all takes time. Since this is a passion project, not a commercial product I am very reluctant to spend my time on features I do not use. Sorry... that is just how it is.

But you can investigate ExcalidrawAutomate. It is possible to implement an onDropHook where you can program your own processing.

**Comment by Kiss-World** [comment]
I found that I can first drag it over, and then quickly format it by copying the content and pasting it. Although it adds an extra step, it doesn't matter, it's already very good. Thank you.
@zsviczian
