### ISSUE TITLE
Process Question: "Back of the page" - first toggle fails but then works

### ISSUE THREAD

**Issue by ms3056** [zsviczian/obsidian-excalidraw-plugin#1985]
Hi - I have my meeting note template include a barebones Excalidraw drawing and the appropriate properties - I think :) This is from a video that you and Nichole uploaded a while ago. I have a Excalidraw drawing in EVERY note now - and its wonderful. 

What happens lately (it didn't always work this way) is when I hit my hotkey to switch to the Excalidraw view at first it is an empty page. I click the hotkey AGAIN and the Excalidraw session opens. After this INITIAL hiccup the switch is perfect back and forth - it is only the initial switch that doesn't work on the first try, it takes 2. I am wondering if something is wrong in my template? 

The hotkey is: Toggle between Excalidraw and Markdown mode. 

[t.meeting.md](https://github.com/user-attachments/files/16832249/t.meeting.md)

I have made an image to try to explain. After the initial "double toggle" the toggle works perfectly. I am just wondering if this is "known", if I am doing something "wrong" or is it a "bug". 

![image](https://github.com/user-attachments/assets/06fa522e-bb72-4bb9-94ae-751b649f9697)

**Comment by zsviczian** [comment]
Can you share the template that you include in your meeting note template?
this:
 
<img width="106" alt="image" src="https://github.com/user-attachments/assets/0bcee93f-62c2-4c06-b336-c432555a23c2">

**Comment by ms3056** [comment]
Hi! Thanks for your reply. It's in the post - let me know if you can't see it. It's t.meeting.md.

**Comment by ms3056** [comment]
Hi - same thing for me. Perhaps it is something going on with a plugin or styling or the way I have my files setup.

**Comment by ms3056** [comment]
I will close now and try with a default empty vault when I have time. Thanks for looking into it - for now - it DOES work - it just takes me 2 clicks of the hotkey.
