### ISSUE TITLE
BUG: Many lag spikes (on a medium size note) prevent writing. Makes it nearly unusable for note-taking

### ISSUE THREAD

**Issue by Bugsia** [zsviczian/obsidian-excalidraw-plugin#1989]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 11 Home 10.0.26100
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 16
	Plugins enabled: 16
		1: Self-hosted LiveSync v0.23.20
		2: Advanced Tables v0.21.0
		3: Calendar v1.5.10
		4: Editing Toolbar v2.4.16
		5: Kanban v2.0.51
		6: Mind Map v1.1.0
		7: Tasks v7.9.0
		8: Custom File Explorer sorting v2.1.12
		9: Symbols Prettifier v1.2.0
		10: Latex Suite v1.9.5
		11: Dataview v0.5.67
		12: Obsidian Functionplot v1.2.1
		13: Number Headings v1.16.0
		14: Image Caption v0.0.15.alpha
		15: Truth Table+ v1.1.0
		16: Excalidraw v2.4.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

When I am writing on my note, that is roughly 83 big squares tall, every few seconds I cant write anything for a couple seconds. The lag spike. After that all the end- and start-points of where I drew during the lag spikes is drawn. Which isn´t readable at all, as any intermediate points are disregarded.
Like this:
![image](https://github.com/user-attachments/assets/c55326a6-07f1-4173-b242-770849605d2e)
(Taken from https://github.com/excalidraw/excalidraw/issues/6474)

And this happens very frequently which makes writing really annoying. And it has been happening for a while, so also before the note was at its current size of 83 big squares.

### Steps to reproduce

1. Open a new Excalidraw drawing
2. Write a bit
3. Notice how its lagging

### Expected behavior

I should be able to contiunsly write without these lags. Especially not this often.

### Additional context

I have also increased the time between auto-saves and have disabled synchronization of live-sync which hasn´t changed anything.
I am also always zoomed into a small part of the note and it also happens, when I zoom away of any of the already existing notes. 
The excalidraw file is 1.172KB large

**Comment by zsviczian** [comment]
https://excalidraw-obsidian.online/Hobbies/Excalidraw+Blog/How-to/Troubleshooting+Excalidraw+performance+issues
