### ISSUE TITLE
BUG: Embedded text out of focus on editing

### ISSUE THREAD

**Issue by Eusorph** [zsviczian/obsidian-excalidraw-plugin#1990]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.5.11
	Operating system: Windows 10 Home 10.0.22631
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.7.18
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 95
	Plugins enabled: 54
		1: BackItUp v1.0.0
		2: Better Word Count v0.10.1
		3: Book Search v0.7.4
		4: BRAT v1.0.2
		5: ExcaliBrain v0.2.15
		6: File Diff v1.1.1
		7: Movie Search v1.3.1
		8: Note Refactor v1.8.2
		9: Novel word count v3.11.1
		10: Onyx Boox Annotation & Highlight Extractor v1.1.0
		11: Pandoc Plugin v0.4.1
		12: Templater v2.6.0
		13: Text Transporter v1.0.11
		14: Wrap with shortcuts v1.3.0
		15: Colored Text v1.2.0
		16: Commentator v0.2.0
		17: Excalidraw v2.4.0
		18: File Color v1.1.0
		19: File Order v0.0.10
		20: HelpMate v1.0.6
		21: Kanban v2.0.51
		22: Minimal Theme Settings v8.1.1
		23: Paste URL into selection v1.7.0
		24: Persistent Links v0.2.0
		25: Pomodoro Timer v1.2.3
		26: Projects v1.17.4
		27: Show Whitespace v0.2.2
		28: Smart Typography v1.0.18
		29: Style Settings v1.0.9
		30: Text Format v3.1.0
		31: Timer v1.1.2
		32: Canvas Filter v0.9.4
		33: Canvas Links v1.1.4
		34: Status Bar Organizer v2.1.2
		35: Note to Canvas v0.1.1
		36: Local Images Plus v0.15.9
		37: Advanced URI v1.44.1
		38: Local REST API v2.5.4
		39: Extract url content v0.12.1
		40: Omnivore v1.10.4
		41: Canvas Style Menu v0.0.6
		42: MAKE.md v0.9.1007
		43: Highlightr v1.2.2
		44: Dataview v0.5.67
		45: Custom File Explorer sorting v2.1.12
		46: Linter v1.26.0
		47: File Explorer++ v1.2.1
		48: Media DB v0.7.2
		49: Slide Note v0.0.16
		50: Typing Transformer v0.4.0
		51: Advanced Canvas v3.1.0
		52: Hider v1.5.1
		53: Apply Patterns v2.1.2
		54: Writing Goals v0.10.11

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

Text of embedded documents always goes out of focus on editing. It looks normal on preview, but goes out of focus when double cliking to edit text.

### Steps to reproduce

1. Create excalidraw document
2. Embed a text document previously created
3. Double click in the text frame do edit text

### Expected behavior

Editing text should look in focus

**Comment by zsviczian** [comment]
Yeah, I can see that switching to edit mode for an embedded markdown file is a little flaky. In most cases it switched as expected, but indeed, in some cases it snapped out of edit mode.

This is probably an unintended side effect of the single click editing feature. Btw - you can try that to see if that helps:
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/e232e666-d768-439a-8699-167f6711e074">

Also note, that you can switch to edit mode by selecting the embeddable and pressing ENTER (that is my preferred approach, and it also works reliably).

**Comment by Eusorph** [comment]
Thank you for your reply. I tried everything you suggested, but Excalidraw is still showing me blurred text on editng.

**Comment by Eusorph** [comment]
Even after creating a new Excalidraw fie and a new text file to embed, text on editing becomes blurry.

**Comment by zsviczian** [comment]
ah... by focus you mean blurred not that the component loses focus (i.e. becomes inactive) :)
I recall someone mentioning that text becomes blurred if the edges are round. Try changing to "Sharp" edges.
Also blurriness can happen depending on the relative zoom of your canvas and of the embedded document. You can enlarge your component to the size you want to edit it, then use the embeddable elements menu to reset the zoom level. 

<img width="1597" alt="image" src="https://github.com/user-attachments/assets/f82e24be-4a0c-4f9c-9dd1-68d9ef95b9fa">

There is also a command palette action for this that is active when the embeddable is selected. You could set up a hotkey for this if required.

<img width="683" alt="image" src="https://github.com/user-attachments/assets/de330632-8717-4793-9e80-dfd7b47d1955">

**Comment by zsviczian** [comment]
Also try it with the base Obsidian theme to see if that solves your issue. This is a styling problem that may be influenced by the custom theme you are using.

**Comment by Eusorph** [comment]
Corners were already square. The "relative" button doesn't affect the result unless the text gest very big and unusable. Theme doesn't affect result. This is very unfortunate, because I work primarly with text and wanted to move away from Canvas.

**Comment by Eusorph** [comment]
Should I 

1) delete and reinstall Exalidraw?
2) Turn off all plug-ins?
3) Something else?

**Comment by zsviczian** [comment]
Also very strange, as you can see from my screenshots, I don't experience the same issue.

Additional ideas: 
1) Try resetting obsidian font size and zoom level to see if that makes a difference.
<img width="776" alt="image" src="https://github.com/user-attachments/assets/33309763-1779-4a09-ac45-469569070eb6">

2) You have many plugins installed. It could be that this is caused by one of the other plugins (I am led to think this since I do not experience the same issue). Create an empty Vault and install only Excalidraw and see if the same issue happens. If not, then start to install plugins and see which one creates the problem.

<img width="585" alt="image" src="https://github.com/user-attachments/assets/dd9eee39-ed83-468f-b4ce-936216fcfcf7">

**Comment by zsviczian** [comment]
just judging by the names of the plugins, these are the first ones I would turn off, restart Obsidian and see what happens:

15: Colored Text v1.2.0
16: Commentator v0.2.0
22: Minimal Theme Settings v8.1.1
27: Show Whitespace v0.2.2
28: Smart Typography v1.0.18
29: Style Settings v1.0.9
30: Text Format v3.1.0
32: Canvas Filter v0.9.4
33: Canvas Links v1.1.4
35: Note to Canvas v0.1.1
36: Local Images Plus v0.15.9
41: Canvas Style Menu v0.0.6
43: Highlightr v1.2.2
44: Dataview v0.5.67
49: Slide Note v0.0.16
50: Typing Transformer v0.4.0
52: Hider v1.5.1
53: Apply Patterns v2.1.2

**Comment by Eusorph** [comment]
It's Typing Transformer

**Comment by zsviczian** [comment]
so the "transformation" is to make the text blurry :)
If you need Typing Transformer, please open an issue with the developer.
