### ISSUE TITLE
BUG: The LaTeX formula is not working correctly with duplicates.

### ISSUE THREAD

**Issue by HoodyEz** [zsviczian/obsidian-excalidraw-plugin#1994]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 11 Home 10.0.22631
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: off
	Base theme: light
	Community theme: none
	Snippets enabled: 12
	Restricted mode: off
	Plugins installed: 18
	Plugins enabled: 15
		1: Banners v1.3.3
		2: Calendar v1.5.10
		3: Callout Manager v1.1.0
		4: Homepage v4.0.4
		5: Image Context Menus v1.9.0
		6: Opener v2.1.2
		7: Image Converter v1.1.7
		8: Projects v1.17.4
		9: Tray v0.3.5
		10: Custom File Explorer sorting v2.1.12
		11: Tasks v7.9.0
		12: Outliner v4.8.1
		13: Latex Suite v1.9.5
		14: Excalidraw v2.4.1
		15: Reminder v1.1.15

### Describe the bug

[screen-capture.webm](https://github.com/user-attachments/assets/5fd7221e-4b76-4462-82e5-e94ba7659814)

### Steps to reproduce

1. Create a LaTeX formula
2. Duplicate the formula
3. Edit the duplicated formula
4. Notice that the original LaTeX formula is changed instead of the duplicated formula

### Additional context

"I tried in Obsidian Sandbox and the same problem appears."

**Comment by firai** [comment]
Seems like a problem with the Alt+Drag operation. If I use the Duplicate button in the Edit panel, the Duplicate command in the right-click menu or copy and paste the formula, editing the formula changes the right object.

**Comment by zsviczian** [comment]
Thanks @firai!
Another example of why I don't like to develop features I do not use. I never use LaTeX and as such don't come across these issues, nor feel the sense of urgency to act on them... sorry, I got to manage my time and sanity somehow.

...and yeah. Alt+drag has many issues. It is on the list to be reworked. I'll wait until the Excalidraw team do their magic before spinning my wheels on this in Obsidian. for more info see: [#8435](https://github.com/excalidraw/excalidraw/issues/8435)

**Comment by zsviczian** [comment]
@firai, your observation has helped a bunch. I thought of a quick solution to this problem which I am releasing in 2.4.2 later today.
