### ISSUE TITLE
BUG: Issue with complex Excalidraw graphics not displaying after the update

### ISSUE THREAD

**Issue by Hans-701** [zsviczian/obsidian-excalidraw-plugin#1997]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO: (PC)
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 14
		1: BRAT v1.0.2
		2: Editing Toolbar v2.4.16
		3: Obsidian Columns v1.5.2
		4: Copy Block Link v1.0.4
		5: Multi-Column Markdown v0.9.1
		6: Templater v2.7.1
		7: Iconize v2.14.3
		8: Diagrams.net v1.0.4
		9: Exercises v0.1.2
		10: Icons v0.3.0
		11: Hover Editor v0.11.20
		12: Inline Admonitions v1.4.5
		13: Admonition v10.3.2
		14: Excalidraw v2.4.1
RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

ANDRODI:
SYSTEM INFO:
	Operating system: android 14 (Xiaomi 23129RA5FL)
	Obsidian version: 1.6.7 (149)
	API version: v1.6.7
	Login status: not logged in
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 11
		1: BRAT v1.0.2
		2: Editing Toolbar v2.4.16
		3: Obsidian Columns v1.5.2
		4: Copy Block Link v1.0.4
		5: Multi-Column Markdown v0.9.1
		6: Templater v2.7.1
		7: Iconize v2.14.3
		8: Exercises v0.1.2
		9: Hover Editor v0.11.20
		10: Admonition v10.3.2
		11: Excalidraw v2.4.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

After updating Excalidraw, some of my more complex graphics are no longer displaying correctly, particularly on mobile devices. This issue occurs not only with files created before the update but also with new complex graphics. When I open the notes in reading mode in Obsidian, I see a sequence of letters instead of the expected graphic. Simpler drawings do not have this issue. The problem occurs on both PC (Windows) and Android devices, and I have tested this in multiple vaults where the issue still persists.

### Steps to reproduce

1. Create complex graphics in Excalidraw (either before or after the update).
2. Update Excalidraw.
3. Insert the graphics into an Obsidian note.
4. Open the note on mobile and switch to reading mode.
5. Notice that the graphic does not display correctly.

### Expected behavior

I expected that both older and newer complex graphics created in Excalidraw would display correctly in my notes, whether on PC or mobile, and would not be replaced by a sequence of letters in reading mode.

### Additional context

The issue seems to be related to complex graphics and primarily affects mobile devices. Simpler drawings do not seem to be affected. The problem persists even in a new vault with only Excalidraw installed and occurs on both PC (Windows) and Android.
Androi:

![image 1](https://github.com/user-attachments/assets/4ff18b4d-9d43-4556-87a9-790a902e2870)

https://github.com/user-attachments/assets/d68157b7-a032-453f-8f6b-62ab4cc8f854

PC (windows):
![Pasted image 20240905115150](https://github.com/user-attachments/assets/ff561a10-b9a5-4f38-8b01-2c48de158424)
![Pasted image 20240905115307](https://github.com/user-attachments/assets/82240903-ff5b-4791-a8f4-ea3d45076bea)

**Comment by zsviczian** [comment]
I see you've ticked the box "Yes, I have verified the issue persists.". Have you actually created a new Vault, created a drawing using Excalidraw 2.3.0, then upgraded to test the process? Or how have you tested in an empty Vault?

What happens if you open the old complex drawing and press CTRL+S to save it. Save will force the cache to reload the drawing.

alternatively you could try to purge the image cache.

In plugin settings under Embedding Excalidraw into your Notes and Exporting can you try Purging the cache?

<img width="795" alt="image" src="https://github.com/user-attachments/assets/5bf25c4f-7118-4212-915e-e21496ef6739">

**Comment by zsviczian** [comment]
This seems related: #1896 (Excalidraw drawings do not render in markdown when Multi-Column Markdown plugin is installed.... so did you test in an empty Vault as you indicated in the issue report??

You can find list of known compatibility issues here.

**Comment by Hans-701** [comment]
Yes, I tested it in a new empty vault. At first, it seemed like the issue was resolved, but then I created a couple of new graphics and the same problem occurred. Additionally, I have tried Purge Cache, but the problem persists.

Sorry if I’m interrupting, and thank you so much for your help!!!

https://github.com/user-attachments/assets/6f75d3bd-3d16-48eb-8584-f57d8f0934ec

**Comment by zsviczian** [comment]
please disable Multi-Column Markdown v0.9.1 and restart Obsidain, does the issue persist?

**Comment by zsviczian** [comment]
> Yes, I tested it in a new empty vault. At first, it seemed like the issue was resolved, but then I created a couple of new graphics and the same problem occurred.

So you created a new vault, installed Excalidraw and started to create drawings, and after a time you experienced this in the new Vault?

**Comment by zsviczian** [comment]
@Hans-701 , can you test this solution? This was confirmed to solve the problem in the [related issue](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1995#issuecomment-2333886357)

Please replace main.js in `.obsidian/plugins/obsidian-excalidraw-plugin` with the main.js in the attached [main.js.zip](https://github.com/user-attachments/files/16906990/main.js.zip) and let me know if this resolves the issue.

**Comment by zsviczian** [comment]
resolved in 2.4.2

**Comment by Hans-701** [comment]
Friend, thank you so much for the update, you're the best! I really value and appreciate your work with this plugin. I’m a 17-year-old student who doesn't speak English haha (I'm using AI to translate this), and your plugin really helps me a lot. I hope you have much success!
