### ISSUE TITLE
FR: Once the content of Embedded files is searched, it is a whole string of text that is searched, making the search almost unreadable

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#1999]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/98f1d37f-b5a9-44eb-b946-ee45c825a2e8)
This is the result of a backlink. When the EXcalidraw file appears in the result, there is often a lot of useless link information, because there is no blank line between each link of embedded files, resulting in a lot of useless information being displayed in the search results, making the search results verbose
![image](https://github.com/user-attachments/assets/325bedd5-82de-4279-acf8-dd676f56a104)
It's the same problem with Element links

**Describe the solution you'd like**
![image](https://github.com/user-attachments/assets/df6de1e0-6f15-4a94-8146-695774612df8)
As shown in the figure, I should get search results with only this one useful information displayed
![image](https://github.com/user-attachments/assets/7e0d6b12-bc63-4f88-bfb5-f61d89793a77)
As shown, simply leaving each link with an empty line can help a lot

Thanks again for this amazing plugin EXcalidraw

**Comment by zsviczian** [comment]
Thanks! great suggestion. I think this change can be made with very limited impact to the file structure!

**Comment by zsviczian** [comment]
solved in 2.4.2
