### ISSUE TITLE
Excalidraw-only notes getting auto-deleted during Obsidian launch or ongoing run.

### ISSUE THREAD

**Issue by Fierce-Ninja** [zsviczian/obsidian-excalidraw-plugin#200]
Obsidian is auto-deleting Excalidraw files on its launch and sometimes, at random.  I keep recovering but it keeps deleting those files and any new files in Excalidraw.  Also, only Excalidraw files are getting deleted, no other notes are.

To reproduce, just start Obsidian.

More information: 
I use google drive folder as my vault with google drive desktop app on windows 10. It works flawlessly with all my obsidian folders until I started using Excalidraw. For some reason, Excalidraw plugin or Obsidian (I don't know who) keeps deleting my files, ONLY in excalidraw folder of the vault. Rest of my files in various folders in the same vault for Obsidian are intact and nothing happens to them. If it had something to do with google drive, I would have expected such behavior with other files in non-excalidraw folders. But that doesn't happen. It is only in Excalidraw folder. So my rough guess is there is something weird happening in Obsidian or Excalidraw plugin. Any thoughts on this?

**Comment by zsviczian** [comment]
these are excalicraw.md files or *.excalidraw files? In other words are you using any of the compatibility mode settings?

![image](https://user-images.githubusercontent.com/14358394/137851176-7c225d01-3754-44c0-9073-2c13985ed881.png)

**Comment by Fierce-Ninja** [comment]
> 1. Can I ask you to create a test vault. Place it on your local drive, not on google drive. Install only the Excalidraw plugin. Test if the issue is there.

The error is not happening anymore in this test case. Only Excalidraw. No other community plugins.

> 2. If you cannot reproduce the issue in test 1, then please create a second test vault this time on google drive, and test again.

The error is not happening anymore in this test case either. Only Excalidraw. No other community plugins. This means not a google drive issue either.

> 3. If you still cannot reproduce the issue, the please try to disable all the other plugins in your main vault and see if the issue persists.

I was hoping you won't say this :-)  This is a pretty big undertaking and investment of time. I will do it if that's the only choice I have.  I was hoping you could make some connections in the earlier detailed message I just left and maybe some plugin (like templater?).  I don't know.  Anyways, I will wait for your response before investing this kind of time.  Please advise.

**Comment by zsviczian** [comment]
Thanks for the many updates. This is very strange. 

Can you share with me your data.json file from the .obsidian/plugins/obsidian-excalidraw-plugin folder?
Note this file includes your stencil library as well… if you wouldn’t want to share the data.json, then please share screenshots covering all your excalidraw settingings.

Did you try setting a different Excalidraw default folder… If it is the Excalidraw plugin causing the issue, I would think the same random issue should happen even if the folder name is different. Also, do you have any special characters in your folder name?

**Comment by Fierce-Ninja** [comment]
Hi there. Below are the screenshots covering the settings below.  
First, to answer your other questions, once I moved the excalidraw files to the main parent folder (folder above Excalidraw folder), all new diagrams are now being created at that level.  This is even after specifying a different folder as default for Excalidraw files in the settings.

No, I do not have any special characters in my folder name.

Screenshots:

![image](https://user-images.githubusercontent.com/12793089/138219166-ad3bfb31-b8be-4dc9-aa74-2074be5e550f.png)

![image](https://user-images.githubusercontent.com/12793089/138219205-7bb21bb1-5237-4b59-aef2-cac59d047c0b.png)

![image](https://user-images.githubusercontent.com/12793089/138219230-5be275f5-8ae4-43ac-86fe-5e2a3f8b2d9d.png)

![image](https://user-images.githubusercontent.com/12793089/138219256-6511d331-36b7-49fa-acca-a696176a153a.png)

![image](https://user-images.githubusercontent.com/12793089/138219287-59b3f533-aabe-438d-aea7-f5db1e4b66db.png)

I don't mind giving data.json as long as it only contains the data from Excalidraw folder and no other folder. Please confirm and then I can send that if you still need it.

**Comment by Fierce-Ninja** [comment]
Thank you.  If I uninstall and reinstall Obsidian, it would be just the program only, right?  I don't have to touch my folders, right?  Or do I need to first back up all my notes data and the delete all the "." files from the vaults too manually?

**Comment by zsviczian** [comment]
It is just the Obsidian app. you don't need to touch your vaults. after
reinstall you will need to reopen your vaults and confirm you allow
plugins..  but that's all

**Comment by Fierce-Ninja** [comment]
Okay I did what you said.  Uninstalled and reinstalled Obsidian. Only the Excalidraw files still got auto-deleted, but like the last few tests, they would do so only if they are in the Excalidraw folder.  When I move them to root folder they remain un-deleted.  Secondly, any new Excalidraw note created doesn't obey the default folder setting in Excalidraw plugin settings.  So even if I mention "Excalidraw" as default folder, or pick another folder not created yet, a new Excalidraw file would just go into the root folder.  I am scratching my head here.
