### ISSUE TITLE
FR: The mode of operation with the pen

### ISSUE THREAD

**Issue by MaksFoxerProgrammer** [zsviczian/obsidian-excalidraw-plugin#2001]
When working with the pen in tablet mode, I can drag the canvas with two fingers. But I can't scale it, which is very very inconvenient. You already have similar functionality when working with a laser pointer - I can draw with a pointer with a stylus, and at the same time scale the canvas with two fingers.   

Please make working in tablet mode more convenient, it would be just fine!

**Comment by zsviczian** [comment]
Turn on Allow pinch zoom in pen mode.

Plugin settings > Excalidraw Appearance and Behavior:

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/6fb524b4-9c65-4cf0-aa63-562cb2739406">

**Comment by MaksFoxerProgrammer** [comment]
Oh my God! Thank you so much! How I missed it!!! Thank you very much!!!
