### ISSUE TITLE
BUG: Table not fully showing when inserting as image

### ISSUE THREAD

**Issue by MBlais13** [zsviczian/obsidian-excalidraw-plugin#2005]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.5.3
	Operating system: Darwin Kernel Version 21.6.0: Thu Jun  8 23:57:12 PDT 2023; root:xnu-8020.240.18.701.6~1/RELEASE_X86_64 21.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.4.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

when inserting a file in the form of an image the tables within the page get cut off.
This is only an issue when inserting in the form of an image not an embed.

### Steps to reproduce

Create a table in markdown
Make a new draw file
Insert said table/page via image
See result

### Expected behavior

I expected the entire table to be imported just like the embeddable one.

### Additional context

![Screenshot-4](https://github.com/user-attachments/assets/1350e180-3a82-4a3c-980b-fdbda9e0fb82)
![Screenshot](https://github.com/user-attachments/assets/c81d1e3f-6746-4148-9ddf-ac2f0fa79169)

**Comment by zsviczian** [comment]
If I understand you well, this is a how-to question, not a bug.

CTRL+Win / CTRL+CMD +Click on the image  ( or select the image and use the command palette `Excalidraw: Open the image link or LaTeX formula editor`) to edit the dimensions of the markdown embed image.

<img width="686" alt="image" src="https://github.com/user-attachments/assets/802a0b1a-9ff9-4083-8662-b9e4b8316520">

You can set the defaults in plugin settings:
<img width="820" alt="image" src="https://github.com/user-attachments/assets/0a4c6dfe-4341-443f-886b-fd13ab916c09">


https://raw.githubusercontent.com/zsviczian/obsidian-excalidraw-plugin/master/images/excalidraw-modifiers.png
