### ISSUE TITLE
BUG: can't exit arrow tool on phone

### ISSUE THREAD

**Issue by LeonelRFF** [zsviczian/obsidian-excalidraw-plugin#2006]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Operating system: android 14 (OPPO CPH2363)
	Obsidian version: 1.6.7 (149)
	API version: v1.6.7
	Login status: not logged in
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.4.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

I try to use the arrow tool in a way that allows me to manipulate it to create curves, but the action cannot be closed. In other words, I can't do anything else unless I close the note and re-enter, and simply drawing a straight arrow works fine.

### Steps to reproduce

1. On the mobile phone in a vault with no plugins installed, only Excalidraw, create 2. a new drawing.
3. Insert the arrow tool with a single tap on the screen to manipulate it.
4. Try to use another tool by double-tapping on the screen to exit the arrow tool.

### Additional context

https://github.com/user-attachments/assets/2a886978-803a-4d8c-95a8-6235e56dd7a4

As you can see, I am unable to exit the arrow tool. I constantly use this tool on my mobile device, and this issue didn't occur before.

**Comment by zsviczian** [comment]
Yeah - I am able to reproduce the issue and it is really frustrating. The check button is intended to terminate the drawing, but I see it is not clickable.

![image](https://github.com/user-attachments/assets/7db1c677-9545-4df7-8981-d9723f67c0ab)

**Comment by zsviczian** [comment]
The fix is also available if you install 2.4.3-rc-1 using BRAT. More on BRAT and beta releases here: https://youtu.be/2poSS-Z91lY

**Comment by LeonelRFF** [comment]
OK thanks
