### ISSUE TITLE
FR: Change the color of the grid lines

### ISSUE THREAD

**Issue by kin30528** [zsviczian/obsidian-excalidraw-plugin#2007]
How to change the color of the grid lines？ Does anyone know?
It is more eye-catching than the notes.

ob: v 2.4.2

**Comment by zsviczian** [comment]
There is no such setting at the moment. This could be a feature request.

**Comment by kin30528** [comment]
> There is no such setting at the moment. This could be a feature request.

Hi @zsviczian, I wish I could modify the color of the grid lines, I often use excalidraw to create notes for illustrations. A few months ago,  I modified the background color and create translucent rectangle for me to form a theme, which I thought was interesting, but the current grid line color doesn't fit the more background color.

For example, I would prefer to add a light gray grid line with a blue tone on a dark gray blue background, which would make my notes more visible!

Hope you will consider this suggestion, thank you!~~

# current note
<img width="717" alt="Snipaste_2024-09-11_16-09-05" src="https://github.com/user-attachments/assets/0600bf7b-9ff4-4cf1-b9a4-c70f92c2d615">
te


# Expected results
<img width="717" alt="new" src="https://github.com/user-attachments/assets/951e08e9-ca80-4529-abf3-de7abab415b6">

**Comment by zsviczian** [comment]
You are going to like 2.5.0 :)

<img width="796" alt="image" src="https://github.com/user-attachments/assets/4cf88989-f3b3-4365-b799-1444cab41480">

If you'd like to try it before the next public release you can install 2.5.0-beta-3 using BRAT. This video explains how to configure [BRAT for Excalidraw](https://youtu.be/2poSS-Z91lY?si=xhU9rE4-9iPbWd2h&t=330)
