### ISSUE TITLE
#BUG #HELP

### ISSUE THREAD

**Issue by DBaob** [zsviczian/obsidian-excalidraw-plugin#2009]
### Have you checked the documentation and searched existing issues?

- [X] Yes, I have reviewed the documentation and searched for related issues.

### Your question

I have added the desired font in my valut, turned on the 'detect all file extension', and selected the fourth font. But still I am not able to change the default font.
I noticed that someone has already raised this issue, but it hasn't been resolved yet. Therefore, I am submitting this question again, hoping to receive your assistance.
![2024-09-08_22-54-06](https://github.com/user-attachments/assets/7ea55108-b151-47c4-b8e0-bb5b86f38944)
![PixPin_2024-09-08_22-59-55](https://github.com/user-attachments/assets/f6a4ffc6-39b2-49a1-bed7-391dc063ff60)

**Comment by DBaob** [comment]
![PixPin_2024-09-08_23-15-13](https://github.com/user-attachments/assets/b03e6b6b-d317-4f35-a930-7a2368ea7be0)
I have created the "font" folder and Obsidian can detect the .tff file.

**Comment by zsviczian** [comment]
This typically happens when the font file for some reason is not loaded by the browser (under the hood Obsidian runs in a browser called Electron).

First practice the process with a font from google fonts: https://fonts.google.com/
If that works, and your font does not, then look for sites that convert .ttf files to .woff2 files. .woff2 fonts are also better from an SVG export size perspective. This site was the first on the Google result list: https://cloudconvert.com/ttf-to-woff2

**Comment by DBaob** [comment]
I don't know why, but the fonts in Google Fonts are not working. Even after converting my fonts to .woff2, they are still not effective.The second picture is a list of my plugins. Maybe some of them are causing conflicts?Thank you for your assistance.
![2024-09-09_18-40-20](https://github.com/user-attachments/assets/a4e98346-5bbc-43ff-9767-10b000d18815)
![2024-09-09_18-44-08](https://github.com/user-attachments/assets/9baa38d8-0692-4f7d-bc13-3c9b4b0d87b7)

**Comment by zsviczian** [comment]
Please create a new empty vault. Only add your test font from google and Excalidraw. turn on the local font in plugin settings and see if it works.

**Comment by DBaob** [comment]
I'm afraid that it doesn't work.
![2024-09-09_20-25-49](https://github.com/user-attachments/assets/d947e26e-e285-4a0c-bd30-6845a7ea0412)

**Comment by zsviczian** [comment]
please share command palette/ debug info so I can see your configuration.

**Comment by zsviczian** [comment]
I did some testing of my own. I downloaded this font: https://fonts.google.com/specimen/Playwrite+CU

the ttf file in the root folder of this font did not work: 
![image](https://github.com/user-attachments/assets/ae6dba5c-9d85-4a56-9075-8b9c318162e9)

But the font in the static folder did:
![image](https://github.com/user-attachments/assets/ce5a06d1-80b4-43b8-9e3b-5e2297110fa0)

I tried the "Regular" file.

**Comment by DBaob** [comment]
I'm sorry, but I'm not quite sure what you mean (I'm not a computer science student, just an amateur enthusiast). My Obsidian version number is v1.6.7.
![2024-09-09_20-44-53](https://github.com/user-attachments/assets/ffa4c7cb-c4e5-470e-8f2f-d5805640060d)

**Comment by DBaob** [comment]
Good news, I repeated your test and successfully found the font you used for testing. However, the previous font still did not display.
![2024-09-09_20-50-40](https://github.com/user-attachments/assets/f85a0384-ef49-49a9-a072-e7139bc4ef0e)

**Comment by zsviczian** [comment]
Command Palette is the Obsidian Command Palette. (CTRL+P)
Debug info is an action on the command palette.
But this info is no longer required. We now know the feature is working. Please consult local forums and user groups to figure out which font file to use.

**Comment by DBaob** [comment]
Thank you very much for your help! By the way, I just used the PlaywriteCU-VariableFont_wght.ttf file from the root directory, and it worked fine on my computer. It seems to be an issue with the font file, so I will look for other font files that I like to use.

**Comment by IceKirinCool** [comment]
As a Chinese font user, I also encountered this problem after recent update. But I found that wasn't really a problem. No matter which font you select in the Settings, excalidraw displays the "Local font" instead of the name of the font itself. Just move your mouse over the "local font" and the font will change.

**Comment by zsviczian** [comment]
yes - that is correct. The current solution will call which ever additional font you select the "Local Font". There is some development planned in Excalidraw which should allow unlimited number of personalized fonts. When that is implemented fonts will display with their correct name. for now, however they are called local font, also to inform you that if you change the font in settings, it will affect existing drawings.
