### ISSUE TITLE
BUG: size of action area becomes enormeous after last update

### ISSUE THREAD

**Issue by rmurawka01** [zsviczian/obsidian-excalidraw-plugin#2011]
### Have you searched for existing issues (including closed ones)?

- [x] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [x] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.1
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 23.5.0
	Login status: logged in
	Language: en
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: Obsidian Nord v0.2.0
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 74
	Plugins enabled: 60
		1: Excalidraw v2.4.2
		2: ExcaliBrain v0.2.15
		3: Dataview v0.5.67
		4: Buttons v0.5.1
		5: Tag Wrangler v0.6.1
		6: Frontmatter Tag Suggest v0.4.1
		7: PlantUML v1.8.0
		8: QuickShare v1.3.1
		9: Editor Syntax Highlight v0.1.3
		10: Kanban v2.0.51
		11: Pandoc Plugin v0.4.1
		12: Checklist v2.2.13
		13: Templater v2.7.1
		14: Tracker v1.14.0
		15: Map View v5.0.3
		16: Outliner v4.8.1
		17: Text Generator v0.7.37
		18: Local images v0.14.2
		19: Homepage v4.0.4
		20: Folder Note Core v1.3.5
		21: Supercharged Links v0.12.1
		22: Metadata Menu v0.8.7
		23: Style Settings v1.0.9
		24: Tag & Word Cloud v1.4.1
		25: ReadItLater v0.5.1
		26: Timestamp Notes v1.0.8
		27: Antidote Grammar Checker Integration v2.1.2
		28: Commander v0.5.1
		29: BPMN v7.2.0
		30: Quick Switcher++ v4.4.0
		31: Mermaid Tools v1.1.3
		32: Markdown Table Editor v0.3.1
		33: Iconize v2.14.3
		34: Banners v1.3.3
		35: TagFolder v0.18.7
		36: Share Note v0.8.16
		37: Slash Commander v0.2.16
		38: Whisper v1.5.5
		39: Extract url content v0.12.1
		40: Advanced URI v1.44.1
		41: Media Notes v1.3.0
		42: Find orphaned files and broken links v1.10.1
		43: YTranscript v0.9.2
		44: Nested tags graph v1.0.2
		45: Tab Selector v0.7.0
		46: Multi Properties v1.1.2
		47: File Explorer Note Count v1.2.2
		48: Bookmarks Caller v0.5.1
		49: Medium Importer v0.2.2
		50: Tags Overview v1.0.4
		51: Text Extractor v0.5.2
		52: Smart Memos v1.1.7
		53: Smart Templates v1.0.37
		54: Unofficial Fabric Integration v1.3.3
		55: AI Tagger v1.1.7
		56: markdown export v1.0.24
		57: Local Images Plus v0.15.9
		58: BRAT v1.0.2
		59: Find and replace in selection v1.0.1
		60: Smart Connections v2.2.67

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

the size of these zones became enormous after my last update (cf screen copy)
![image](https://github.com/user-attachments/assets/30209148-53bb-494e-b93f-b88014f9f16b)

### Expected behavior

these areas take up too much space on my screen. i hope to be able to restore them to their original size (before update) or to be able to set a zoom level via a configuration parameter?

**Comment by zsviczian** [comment]
Yes, I've noticed as well.
The change does not come from Excalidraw but Obsidian 1.7.1. They have changed the styling of Obsidian that has downstream effect on Excalidraw. I've not had the energy to try to fix this... sorry.

Trying to keep Excalidraw plugin stable and functional with the whirlwind of changes in Obsidian and the Excalidraw core component takes more effort than you'd think. 

If you reset obsidian Font size and Zoom to defaults Excalidraw will look normal as well.

![image](https://github.com/user-attachments/assets/731f90d4-8617-4c2b-8d20-774f13b34adb)

**Comment by rmurawka01** [comment]
thanks for the solution.
the workaround is more than enough.
as an integrator of software solutions from several software vendors, i sympathize with the effort it takes to implement new functionalities, taking into account the increasingly time-consuming evolution of vendor solutions.

**Comment by zsviczian** [comment]
.... I don't see this as a workaround, but as the actual solution. If you want to use footnotes, you need to enable them. I will update the setting description, so it includes footnotes not just Zotero.
