### ISSUE TITLE
BUG: Disappearing Footnote

### ISSUE THREAD

**Issue by ejelasko** [zsviczian/obsidian-excalidraw-plugin#2012]
### Have you searched for existing issues (including closed ones)?

- [ ] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

When putting a footnote under the Excalidraw markdown section, and then changing some of the drawings, the footnote will disappear. 
Pre:
 
![ex01](https://github.com/user-attachments/assets/f4f3f460-39f3-42b5-bfaa-a7f3f357ccca)

 
Post:
 
![ex02](https://github.com/user-attachments/assets/11587dd0-936c-4685-b019-2a4fd461f551)

**Comment by zsviczian** [comment]
Try this setting (Zotero compatibility):

![image](https://github.com/user-attachments/assets/3e4d52c4-ceb2-4b84-ae10-1d7826f142e8)

**Comment by zsviczian** [comment]
modified setting title under Compatibility Features to include footnotes in 2.5.0
