### ISSUE TITLE
FR: ability to edit and render .excalidraw and .excalidraw.png files produced by pomdtr.excalidraw-editor plugin for vscode

### ISSUE THREAD

**Issue by Dmit1812** [zsviczian/obsidian-excalidraw-plugin#2021]
### Is your feature request related to a problem? Please describe.

- I am unable to re-use excalidraw diagrams created in vscode using the vscode plugin in obsidian with excalidraw extension. VSCode plugin: https://github.com/excalidraw/excalidraw-vscode, extension ID: pomdtr.excalidraw-editor, (which creates .excalidraw and .excalidraw.png) 

- I am unable to export the excalidraw diagram from obsidian excalidraw plugin as a vscode supported PNG file to share with those who don't use obsidian and excalidraw plugin (The PNG file from VScode plugin actually contains all the excalidraw meta information, which makes such PNG a single container of both rendered diagram and excalidraw metadata to make it editable) which is so sweet. 

- In the list of notes in Obsidian I always have the excalidraw MD file (with diagram) and the PNG file that I export for every diagram so always in 2 copies in the notes tree, if excalidraw plugin for obsidian supported the excalidraw.png files then there would be only one PNG file with both excalidraw information and the actual image which would be also sweet.  

### Describe the solution you'd like

1. Would be great that excalidraw obsidian plugin would allow:
- render, edit and save notes that have extension *.excalidraw.PNG with all excalidraw data embedded produced by VSCode plugin directly in obsidian
- render, edit and save notes that have extension *.excalidraw  produced by VSCode plugin directly in obsidian
- have ability to export a normal obsidian&excalidraw diagram MD as an *.excalidraw.PNG with all excalidraw data embedded inside of it or as *.excalidraw
- have ability to export excalidraw drawing as a .PNG without metadata as before to allow to share "read only" as .PNG

### Real-life usage scenarios

1. With such a feature I would be able to recieve the excalidraw or excalidraw.png from my VSCode friends and be to drop them in my knowledge space and be able to edit them immediately
2. With feature to export  I would be sending the digarams I produced in obsidian&excalidraw to my friends with vscode and they would be able to see and edit it as well. 
3. With support for excalidraw.PNG files both metadata to edit and picture would be in one file, so never have 2 files with the same info(one .md with diagram and one .png with it's render), option to export PNG without metadata would be also great so I could export a read only diagram.  

### Additional context

How currently PNG with embedded excalidraw metadata looks like in obisidan with excalidraw plugin:
![obsidian_excalidraw_editable_png_overlook](https://github.com/user-attachments/assets/a6713242-ab1b-43bb-9be4-facb600ce7c7)

How editing PNG with embedded excalidraw metadata looks like in vscode with excalidraw plugin from (pomdtr):
![how_editing_excalidraw_png_looks_like_in_vscode_plugin](https://github.com/user-attachments/assets/d63a3498-4c46-4373-95e3-2b0d4dd21a77)

This is the actual file produced by vscode plugin, that would be great to be able to edit in obsidian with your excalidraw plugin: ( I have successfully downloaded it from githib and was able to edit in excalidraw plugin in vscode, so would be just great if same could be done with obsidian/excalidraw plugin)
![test excalidraw](https://github.com/user-attachments/assets/3fd80ca2-bd92-4640-aaa2-08fcfb428b1c)

**Comment by zsviczian** [comment]
Let's keep fingers crossed the existing compatibility feature still works. It's been 2 years since I last used it. It was designed for use cases like yours.

<img width="1165" alt="image" src="https://github.com/user-attachments/assets/43cbf069-7c6e-4dcb-82da-b1d5deab70e6">

**Comment by zsviczian** [comment]
yeah, you can drop a .png into excalidraw and it will unpack the scene, but it does not support the excalidraw.png format (which is not an official Excalidraw format). I am not planning to implement support for .excalidraw.png

**Comment by Dmit1812** [comment]
Ok, so I guess then there is no feature.

**Comment by zsviczian** [comment]
Yeah, sorry about that.
