### ISSUE TITLE
BUG: The Frame tool broke the link

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#2027]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: none
	Snippets enabled: 18
	Restricted mode: off
	Plugins installed: 82
	Plugins enabled: 1
		1: Excalidraw v2.2.9

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

![5](https://github.com/user-attachments/assets/6cf747c9-7400-4db4-9328-2e94b07b7f93)
As you can see, I click 1111 to open markdown correctly and editBut once my excalidraw is added to a frame, 1111, I can no longer open the corresponding markdown position

Ps: all the files in my library are excalidraw, excalidraw, the heads of my own md
![image](https://github.com/user-attachments/assets/043f2f43-6c40-423f-82a7-40d415e374a5)
I'm going to put all the content in excalidraw's md mode and link them to the excalidraw boardI think it's the great of excalidraw, it's my md desktop

### Steps to reproduce

1

### Expected behavior

Whenever I click on a link in EXcalidraw, I can go to the opposite side of it

**Comment by zsviczian** [comment]
fixed in 2.5.1-beta-2

I will release beta-2 later today.
Watch this video to understand how to install the beta: https://youtu.be/2poSS-Z91lY
