### ISSUE TITLE
BUG: Excalidraw cannot open the link file in the hover editor's hover window, as the md file does

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#2030]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: none
	Snippets enabled: 18
	Restricted mode: off
	Plugins installed: 82
	Plugins enabled: 2
		1: Excalidraw v2.2.9
		2: Hover Editor v0.11.20

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

1
![5](https://github.com/user-attachments/assets/f852ecc7-6136-403f-88b2-acc62e1f4f61)

If a link in EXcalidraw points to a result that has already been opened in the hover window, then in any case you cannot activate the link again and make it appear in the hover window, leading to the common belief that the link is faulty
This does not happen in md mode, where links can normally be activated at any time and displayed in the suspended window

2
![5](https://github.com/user-attachments/assets/67c5a673-f1ef-49ed-9e0b-889d940e85cb)

In the md pattern, I can open a window through the link and show the text that is linked at the bottom of the documentIn excalidraw, I can't open the suspension window to display the linked text in any case, and there seems to be a force that prevents me from opening two excalidraw documents of the same nameMany of the content in the md pattern of excalidraw will not be open in a suspension window, only where it can't be seen at the bottomThe experience of this kind of completely different experience is difficult to suffer

### Expected behavior

Hopefully, like md, I can display it by a suspension window if it's a link

**Comment by zsviczian** [comment]
sorry - I do not deal with issues with other plugins there are over 1800 plugins, I'd go crazy if I tried to maintain compatibility with all.
