### ISSUE TITLE
FR: add function can modify Excalidraw hot-key 

### ISSUE THREAD

**Issue by yCupid-u** [zsviczian/obsidian-excalidraw-plugin#2034]
### Is your feature request related to a problem? Please describe.

my other plugin use ctrl+G,and excalidraw also use ctrl+G (function:Group selection)i want to change it

### Describe the solution you'd like

can u prove a panel to change hot-key

**Comment by zsviczian** [comment]
This is something you need to raise with excalidraw.com. https://github.com/excalidraw/excalidraw/issues
I will not work on this feature.
If ctrl+g conflicts with another hotkey (e.g. graphview) you can add it to hotkey overrides under appearance and behavior

<img width="791" alt="image" src="https://github.com/user-attachments/assets/190b08bc-9885-4fcb-9703-99c27132e614">
