### ISSUE TITLE
SUPPORT: Outdated color palette information in README

### ISSUE THREAD

**Issue by mxsdlr** [zsviczian/obsidian-excalidraw-plugin#2037]
### Have you checked the documentation and searched existing issues?

- [X] Yes, I have reviewed the documentation and searched for related issues.

### Your question

**TL;DR:**: `README.md` is outdated:
- [README.md:107](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/0c28e822121fefe4bc9354ed729dc881de534bb0/README.md?plain=1#L107): `"colorPalette": {` instead of `"customColorPalette": {`
- [README.md:112](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/0c28e822121fefe4bc9354ed729dc881de534bb0/README.md?plain=1#L112): Add: `"topPicks": {"canvasBackground":[], "elementBackground":[], "elementStroke": []},`

---

Good day Zsolt,

first of all, thank you very much for your awesome work on the Obsidian excalidraw plugin. I am not sure how to post this as it is neither a bug, nor a feature request but a small correction in the README.

I recently updated an old version before the color picker and the compressed data format. It uses a template to get the palette from and I as I only use one palette, I did not want to install the palette loader. Thereby, I discovered two minor issues in the `README.md` that have not been updated yet:

1. In [README.md:107](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/0c28e822121fefe4bc9354ed729dc881de534bb0/README.md?plain=1#L107) it states `"customColorPalette": {` which is outdated. Instead it should be `"colorPalette": {`
2. In [README.md:112](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/0c28e822121fefe4bc9354ed729dc881de534bb0/README.md?plain=1#L112) I suggest adding the new `"topPicks"` as it took quite long to figure out how these work (in fact I had to understand the code of the palette loader plugin).

Best regards

### Additional context

To give you an easy copy+paste solution, here is the upated `README.md` text I suggest:

```md
#### Templates

- Template for new drawings. The template will restore stroke properties. This means you can set up defaults in your template for stroke color, stroke width, opacity, font family, font size, fill style, stroke style, etc. This also applies to ExcalidrawAutomate.
  - Via the template, you can customize the color palette used by Excalidraw.
    - Switch to Markdown view.
    - Scroll down to the bottom of the file and find `"AppState": {`.
    - Find `"colorPalette": {` at the end of the AppState section.
        - You may specify the 3 palettes used in Excalidraw by adding any or all of the following 3 variables:
            - `"canvasBackground":[], "elementBackground":[], "elementStroke": []`.
            - Add a comma-separated list of valid HTML colors (e.g. `#FF0000` for red) in the array for each of the variables.
        - To change the previewed colors, a `"topPicks": {` may be specified containing the same three keys:
            - `"canvasBackground":[], "elementBackground":[], "elementStroke": []`.
            - Note that the corresponding arrays must contain 5 elements.
    - See my videos above for further help.
```

**Comment by zsviczian** [comment]
resolved with #2038
