### ISSUE TITLE
BUG: zoom to fit drawing does not work as expected in split pane

### ISSUE THREAD

**Issue by n-konig** [zsviczian/obsidian-excalidraw-plugin#2039]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.2
	Installer version: v1.6.5
	Operating system: Windows 10 Education 10.0.19045
	Login status: logged in
	Language: en
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.5.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

Essentially: pressing Shift+1 should zoom to fit the contents of the drawing.
In a single pane, this works.
When splitting the pain - down or right - pressing Shift+1 zooms away from the content.

### Steps to reproduce

1. Open Drawing
2. Confirm Shift+1 zooms to fit (by scrolling out, then pressing Shift+1)
3. Run command "Split down" to open the same drawing in another pane below
4. Press Shift+1 in the bottom pane

### Expected behavior

Step 4 - pressing Shift+1 in the "split down" pane - is expected to zoom to fit, just as in Step 1.

### Additional context

Sorry I don't have a key-press logger that shows when I press Shift+1 in the recording.. 

You'll see that when I press Shift+1 in the bottom pane, it zooms away from the drawing, displaying the "Scroll back to contents" button. Pressing this does focus on the contents in the drawing, but very zoomed out.

![ObsidianExc_zoombug](https://github.com/user-attachments/assets/b2449f0d-edb9-479d-bfc3-4cd14fe27c9d)

Additionally, this also happens if splitting right, or if using Shift+2 to focus on individual objects.

**Comment by zsviczian** [comment]
Fixed in 2.5.1. Will release in the next few days.

**Comment by imran1khan** [comment]
Hi @zsviczian 
I tried using your code to see how it works, but I didn’t get any different results. I’m testing it on Chrome.

Another thing I noticed: when we press "Shift+1," we expect all the shapes/content to fit on the screen, correct? If the content is too large, we should zoom out, and if it’s too small, we should zoom in. Is that right? Please correct me if I’m wrong, but I didn’t see that behavior in your code.

If you don’t mind, could you please explain what the code is supposed to do? I just want to understand your solution and the problem it addresses.

**Comment by zsviczian** [comment]
If you are "testing it on Chrome" then you are not in the right issue log. This is the Obsidian-Excalidraw issue log. This version does not work in browsers. You need to head over the https://github.com/excalidraw/excalidraw/issues.

**Comment by n-konig** [comment]
Hi! Just discovered that this bug seems to have found its way back. Specifically for vertically split panes.. 

SYSTEM INFO:
	Obsidian version: v1.10.3
	Installer version: v1.6.5
	Operating system: Windows 11 Education 10.0.22631
	Login status: logged in
	Language: en
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.17.1

https://github.com/user-attachments/assets/1b7c2e21-c2de-4992-9b12-7b8f0ea6ae59
