### ISSUE TITLE
When simultaneously using the hover editor, the title does not appear when the EXcalidraw is opened in the hover window. This can help you

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#2042]
### Have you checked the documentation and searched existing issues?

- [X] Yes, I have reviewed the documentation and searched for related issues.

### Your question

![image](https://github.com/user-attachments/assets/aff324c0-ef16-4c38-a91d-8d8f104e7064)
If you find that EXcalidraw's embedded block does not display the title when using the hover window the following css can help you

`/*导致标题无法显示*/
.hover-popover .inline-title, .inline-embed .inline-title {
    display: flex;
}/*修复又会导致 嵌入块在md里 额外多一个标题号*/
/*禁用嵌入标题*/
.markdown-embed-title,
.markdown-embed .mod-header+ div > :is(h1, h2, h3, h4, h5, h6) {
  display: none;
}`

ps：I am not a programmer and my English is not very good, but I hope this will help you

**Comment by jiajiala** [comment]
@zsviczian 
> I am sorry, but I do not plan to look at issues involving the Hover Editor plugin.很抱歉，但我不打算查看涉及 Hover Editor 插件的问题。

Well, I understand that you will not resolve the conflict between hover and EXcalidraw
Thank you very much for the plugin

Maybe my expression is not accurate, this article is not for you, but for the future, if someone else has the same problem, they can use the css I gave to help him overcome difficulties, this is left to the kindness of the future

**Comment by zsviczian** [comment]
you can try opening an issue with Hover editor.

**Comment by jiajiala** [comment]
Yes, I have done this, but there is no other way but to modify the css myself.
It's okay, I don't have this problem here anymore, and rely on my own css to fix it
