### ISSUE TITLE
Need a icon for local font

### ISSUE THREAD

**Issue by dmscode** [zsviczian/obsidian-excalidraw-plugin#2049]
![choice-font](https://github.com/user-attachments/assets/46596986-2ff1-442e-8b30-5d0c2b5b2874)

Like this, the Local Font option does not have an icon in front of it, which is different from other fonts, and is very similar to the small headings above. I have to say, I searched for it for a long time.

**Comment by zsviczian** [comment]
you can easily create your script and add a button to the right sidebar or create a hotkey in Obsidian. I understand this approach requires a bit of investigation on your side, however, long term the superpower of Excalidraw scripting outweighs the difficulty of learning to script.


Here's the script, save it to Excalidraw/Scripts or whatever folder you have set up in plugin settings... You can then add a hotkey for this in Obsidian Hotkeys or long press on the icon in the Obsidian Tools Panel in Excalidraw to pin it to the side bar.  The rest you need to figure out yourself. Good luck.

[Local Font Action.md](https://github.com/user-attachments/files/17177558/Local.Font.Action.md)

```js
//set selected font family to local font
ea.viewUpdateScene({appState:{currentItemFontFamily: 4}});

//if there are text elements selected change them to local font
const textEls = ea.getViewSelectedElements().filter(el=>el.type==="text" && el.fontFamily !== 4);
if(textEls.length > 0) {
  ea.copyViewElementsToEAforEditing(textEls);
  ea.getElements().forEach(el=>el.fontFamily = 4);
  await ea.addElementsToView();
} else {
  //if there are no text elements selected start the text editing tool
  ea.getExcalidrawAPI().setActiveTool({type: "text"});
}
```
