### ISSUE TITLE
FR: Option to disable caching when exporting note to PDF

### ISSUE THREAD

**Issue by Aezral** [zsviczian/obsidian-excalidraw-plugin#2050]
### Is your feature request related to a problem? Please describe.

When I export my dark mode notes as PDF, the embedded drawings don't match the light theme of the export due to cache being enabled

### Describe the solution you'd like

I'd like to have an option to disable cache ONLY when exporting to PDF, but still have it enabled when using it normally
Another solution could be to have an obsidian command to disable and enable cache easily, so I don't have to go to settings and look for the button

### Real-life usage scenarios

1. My obsidian is in dark mode, I export my notes to light mode, I want the excalidraw stuff to match the light theme of the exported note without disabling cache

### Describe alternatives you've considered

The only way I know to achieve this is to disable cache when I'm going to export, and then enable it again.

### Additional context

Ugly
<img width="538" alt="Captura de pantalla 2024-09-28 a la(s) 11 42 45 p m" src="https://github.com/user-attachments/assets/e87b119a-a8ce-4178-beeb-7ec7f18cf795">

Good
<img width="555" alt="Captura de pantalla 2024-09-28 a la(s) 11 43 52 p m" src="https://github.com/user-attachments/assets/ea2023f0-3901-4699-8d6e-a7328bc0a03a">

**Comment by zsviczian** [comment]
I don't think this is a caching issue. I suggest playing with the export settings to configure excalidraw export to follow the Obsidian theme. Unfortunately I don't have first hand experience with this. I only use Obsidian in dark mode and Excalidraw exclusively in light mode (but a dark/light color palette). I dislike Excalidraw dark mode because the colors are not accurate. https://youtu.be/fypDth_-8q0

**Comment by Aezral** [comment]
I'm sorry, when I checked I missed  this configuration, thank you for taking the time to respond.

<img width="776" alt="Captura de pantalla 2024-09-29 a la(s) 12 01 03 p m" src="https://github.com/user-attachments/assets/83a7b9e8-04de-41cb-bbec-cc805943386c">
