### ISSUE TITLE
SUPPORT: Auto-OCR written text

### ISSUE THREAD

**Issue by Alec-lgtm** [zsviczian/obsidian-excalidraw-plugin#2051]
### Have you checked the documentation and searched existing issues?

- [X] Yes, I have reviewed the documentation and searched for related issues.

### Your question

Is there any way to have excalidraw to automatically scan my written text into the task bone OCR after I'm done typing. And replace the written text with the OCR-ed version of the text?

### Steps you've already tried

1. I've tried using ExcalidrawAutomate to script this process but I can't seem to figure it out.
2. I have tried figure out a way to get the command to OCR text (`Excalidraw: OCR full drawing`) as a separate button in Excalidraw on my iPad but haven't had any luck 

### Expected outcome

Either a) a way to automatically turn my written text into OCR-ed more neat text 
b) a less cumbersome way to OCR text and replace the written text (given the difficulty in getting to the command palette from iPad)

**Comment by zsviczian** [comment]
I'll think about this. In the past this has crossed my mind, however, there are many issues that come up that would need to be handled. As an interim step I could publish the OCR function to ExcalidrawAutomate (currently not published). Then you could write your own script to run in the background... this is more complex than appears on the surface.

If I am not mistaken, this video might give you some insight into how to execute a command palette action from script. https://youtu.be/OX5_UYjXEvc

unfortunately I am very stretched on time, else I'd love to help you...

**Comment by Alec-lgtm** [comment]
Thanks for the help. I think the video is more than sufficient for my needs for now.
