### ISSUE TITLE
Hide compressed json from reading and editing view

### ISSUE THREAD

**Issue by alloc33** [zsviczian/obsidian-excalidraw-plugin#2053]
I'm quite new to Obsidian (TS/CSS too).. Is it possible to hide this thing somehow?(or make it visible only in source mode)
<img width="375" alt="image" src="https://github.com/user-attachments/assets/ea325712-509a-4754-8086-791e006366c4">

**Comment by zsviczian** [comment]
This explains your options. Worth watching the whole, but the immediate answer to your question is here: 06:07
https://youtu.be/dV0NEOwn5NM

Plus in plugin settings under misc features see fade out
![image](https://github.com/user-attachments/assets/002dc361-afc2-43fd-950a-0c84edecc804)
