### ISSUE TITLE
BUG: Copy/Paste container with text, text gets disconnected + save error notification

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#2054]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Steps to reproduce

- Create a rectangle
- Add text (to the rectangle)
- CTRL+K on the rectangle and add a link
- CTRL+S to save the drawing
- The text is now selectable and gets detached from the container

**Comment by kin30528** [comment]
@zsviczian I've been experiencing this bug lately.
https://youtu.be/QxknKvsqCzQ

**Comment by zsviczian** [comment]
yes, it is the same. only happens if the container has a link. I haven't had time to fix it. Will get to it eventually.

**Comment by kin30528** [comment]
This gives me a reminder that I'll use the unlinked box for now.
And add the link when note are all done finally~~

**Comment by zsviczian** [comment]
Resolved in 2.5.2. I plan to release the fix in the next few days (maybe today)
