### ISSUE TITLE
BUG: Significant drop in performance in new release

### ISSUE THREAD

**Issue by Skarlso** [zsviczian/obsidian-excalidraw-plugin#2055]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 24.0.0: Mon Aug 12 20:54:30 PDT 2024; root:xnu-11215.1.10~2/RELEASE_X86_64 24.0.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Border v1.9.9
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 17
		1: Iconize v2.14.3
		2: Tasks v7.10.2
		3: Tracker v1.14.0
		4: Dangling links v0.3.0
		5: Dataview v0.5.67
		6: Heatmap Calendar v0.7.1
		7: Excalidraw v2.5.1
		8: Emoji Toolbar v0.4.1
		9: Quick Latex v2.6.5
		10: Omnisearch v1.24.1
		11: Calendar v1.5.10
		12: Editor Syntax Highlight v0.1.3
		13: Projects v1.17.4
		14: Leaflet v6.0.5
		15: Style Settings v1.0.9
		16: Vault Explorer v1.46.0
		17: Buttons v0.5.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

### Describe the bug

Seeing considerable performance drop in plain drawing mode.

See attached Gif:

https://github.com/user-attachments/assets/8b2463c1-2099-47da-9490-9c156e08ecbf

This only goes away if I completely restart the ENTIRE computer.

It does NOT go away if I just restart Obsidian. It's weird, because this never happened before. I was drawing completely fine before a couple of releases ago. I just started to notice this and I didn't touch my obsidian before either.

### Steps to reproduce

I leave obsidian open and after a while it starts to do this. The while is like.. a day maybe? Yesterday, I drew fine, this morning it started lagging.

**Comment by zsviczian** [comment]
In short, I do not experience similar performance drops... so we need to understand your environment better.

Does this happen if you have the default Obsidian theme and no other plugins?

You make an assertion: "drop in performance in new release". Can I ask you to test by downgrading to the previous release to support your claim? Nothing changed in the new release that would indicate such a drop (though I don't know which release you were using earlier), but 2.5.0 and 2.5.1 have minor differences. All I am suggesting is things might have changed in your environment, not Excalidraw (maybe you updated to Obsidian 1.7.3, maybe you update other plugins...). 
To downgrade, download style.css and main.js from [here](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/2.5.0). Quit Obsidian and go to Vault/.obsidian/plugins/obsidian-excalidraw-plugin folder and replace main.js and style.css. 

I recommend reviewing these two articles:
https://excalidraw-obsidian.online/WIKI/06+Troubleshooting/Compatibility+Issues+-+Plugins+to+Watch+Out+For
https://excalidraw-obsidian.online/WIKI/06+Troubleshooting/Troubleshooting+Performance+Issues

If this happens after a day, then as a workaround I recommend restarting Obsidian daily.

**Comment by Skarlso** [comment]
👍 

I'll try downgrading. I didn't try with all the rest of the plugins turned off so that's a good idea. I shall investigate further.

**Comment by zsviczian** [comment]
Though not listed on the list of plugins to watch out for, I remember installing OmniSearch and then removing it after few days as it had a major impact on my Vault's performance. This happened over a year ago, maybe this has been fixed since, I haven't tried OmniSearch since... so I don't know.

**Comment by Skarlso** [comment]
That's actually a good thought. I only "recently" use omnisearch... 

![coincidence](https://github.com/user-attachments/assets/23273d4e-c6e4-43eb-a1d7-e87adea2b0ea)

**Comment by zsviczian** [comment]
Did you get this issue resolved? What was the solution?

**Comment by Skarlso** [comment]
I keep testing this, and get this, after I uninstalled Omnisearch, I haven't been able to reproduce the problem. :O

**Comment by Skarlso** [comment]
So for now, I'm going to close this and be happy about it. :) Omnisearch was a good guess. :)
