### ISSUE TITLE
BUG: wrong colors of callouts from PDF++, when dark mode is turned on

### ISSUE THREAD

**Issue by ShengliYanZHAW** [zsviczian/obsidian-excalidraw-plugin#2056]
### Have you searched for existing issues (including closed ones)?

- [x] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [x] Yes, I have verified the issue persists.

**Comment by zsviczian** [comment]
would be great if you could share a screenshot so I understand what you mean.

**Comment by ShengliYanZHAW** [comment]
it was an issue on my part, I'm sorry for the wrong bugreport. nothing wrong with it.

On 13 Oct 2024 11:46, zsviczian ***@***.***> wrote:

would be great if you could share a screenshot so I understand what you mean.
