### ISSUE TITLE
FR: Seperate libraries, be able to collapse / expand them or delete a specific library!

### ISSUE THREAD

**Issue by emnik** [zsviczian/obsidian-excalidraw-plugin#2062]
### Is your feature request related to a problem? Please describe.

Let's suppose someone uses many many libraries with a lot of stuff inside them... The in a library with all these items, it is a pain to find which item you are looking for! Also If one does not need a previously installed library anymore as it is right now he has to select all the relative items and remove them...

### Describe the solution you'd like

It would be nice if we had something like categories - headers in the library section. Each for a different library that they would also be collapsible and expandable and with a button to delete the whole library. 

### Additional context

I think this is related with [https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/2061](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/2061)

**Comment by zsviczian** [comment]
This is an excellent idea. This should be implemented not in the Obsidian plugin, but the core Excalidraw component. Please raise the FR here: https://github.com/excalidraw/excalidraw
