### ISSUE TITLE
FR: Add option for modifier key+click in View mode to open images, potentially add setting to configure double click timeout

### ISSUE THREAD

**Issue by HoodyEz** [zsviczian/obsidian-excalidraw-plugin#2075]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 11 Home 10.0.26100
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 11
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 7
		1: Excalidraw v2.5.3-beta-5
		2: Spaced Repetition v1.13.2
		3: Image Converter v1.1.7
		4: Tray v0.3.5
		5: Hover Editor v0.11.21
		6: Imgur v2.6.2
		7: Zen v0.6.5

### Describe the bug

You can't navigate the canvas without accidentally double-tapping an image, it's incredibly annoying. It doesn't matter if you hold down the spacebar or activate presentation mode, it's impossible to navigate comfortably.

### Steps to reproduce

Only double click the image or link in presentation mode.

### Additional context

I don't mind links to other notes, as they only require one click, but for images or external links, it's very annoying. It would be better if there were a way to open them by holding down Ctrl.

**Comment by zsviczian** [comment]
You are talking about navigating a canvas in view mode?

**Comment by HoodyEz** [comment]
> You are talking about navigating a canvas in view mode?

Yesssssss plssss

**Comment by zsviczian** [comment]
implemented in 2.6.0, you'll find the setting under appearance and behavior / link click...

I will release the update likely over the weekend.
