### ISSUE TITLE
FR: Option to toggle one finger pan.

### ISSUE THREAD

**Issue by SiBachmann** [zsviczian/obsidian-excalidraw-plugin#2080]
### Is your feature request related to a problem? Please describe.

One finger pan is great if your tablet has decent palm rejection, sadly tablets like the Samsung galaxy tab s9 or Z Fold devices do not have great palm rejection.
I get permanent false pan input every time my palm meets the screen faster then the pen driving me nuts.
On my windows machine this is less of an issue as it has smarter palm rejection.

That's why an option would be very much appreciated!  :)

### Describe the solution you'd like

An option to toggle one finger pan off.

**Comment by zsviczian** [comment]
Sorry for that. I was considering to include that option up front, but then thought I'd wait for some feedback.

**Comment by SiBachmann** [comment]
No worries,  not your fault that wacom based devices have poor palm rejection. 

Thanks for your amazing work, especially on the performance side of things. Always welcome!

**Comment by SiBachmann** [comment]
One thing though that is more a bug: with one finger scroll you can not place a text inpit anymore with the finger. You need a mouse or pen.

1. Select the text tool 8
2. Try to place it somewhere with the finger. -> Won't work. 
3. If you use a pen or mouse it works.

**Comment by zsviczian** [comment]
that is indeed a bug.

**Comment by zsviczian** [comment]
fixed and added in 2.6.1
