### ISSUE TITLE
BUG:  text sizing issue

### ISSUE THREAD

**Issue by Daniel21b** [zsviczian/obsidian-excalidraw-plugin#2086]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.4
	Installer version: v1.6.3
	Operating system: Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112 24.1.0
	Login status: logged in
	Language: en
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Excalidraw v2.2.6
		2: Tasks v7.4.0

### Describe the bug

When creating notes in Excalidraw within Obsidian, text elements are experiencing a persistent display issue:
Behavior:

Text displays correctly while actively typing/editing
Approximately 80% of text elements get cut off on the right side after clicking away/losing focus
The content is still there but visually truncated

### Steps to reproduce

Steps to Reproduce:

Open Excalidraw in Obsidian
Create a text element
Type content that extends beyond a few words
Click away from the text element
Observe the right-side text truncation

### Expected behavior

Current Workaround:

Manually interacting with the text element temporarily restores proper display
Issue returns after losing focus again

**Comment by zsviczian** [comment]
Please share screenshot.
Which font are you using, does this happen with all fonts?

**Comment by HoodyEz** [comment]
Same here
![image](https://github.com/user-attachments/assets/415a605a-9eb7-416d-8902-dc7bd9b60bc2)

**Comment by zsviczian** [comment]
This is a font loading issue. 
Are sizes reset if you double click text elements?
@HoodyEz, please also share the Obsidian debug info so I can see your environment.

**Comment by zsviczian** [comment]
@Daniel21b,
1) After resetting sizes and saving the document, when you open it again are sizes correct or wrong again?
2) Does this happen to all your documents or only to some?
3) Are these "normal" text elements, or `![[transclusions#^block_id]]`?

**Comment by HoodyEz** [comment]
1. When I reopen it, it displays correctly.
2. With all the Excalidraw notes.
3. Only normal text elements.

Additional Context: When Excalidraw is closed and reopened, all the notes you’ve written have the error. Additionally, if the Excalidraw plugin is disabled and re-enabled, the error disappears.

[screen-capture.webm](https://github.com/user-attachments/assets/b25f3074-51ac-4f8b-a636-e39cbf327456)

**Comment by zsviczian** [comment]
Yes, this is clearly a font loading issue. When you restart Excalidraw fonts are already loaded.

Can you try the following?
- Close all tabs
- Restart Obsidian
- Before opening an Excalidraw document, open Developer Console (CTRL+SHIFT+i) and run the following command `ExcalidrawLib.registerFontsInCSS()`;

**Comment by HoodyEz** [comment]
[screen-capture (1).webm](https://github.com/user-attachments/assets/f89383e1-f81f-4206-9f4e-625064526e8c)

**Comment by Daniel21b** [comment]
Yea, same issue when I run the command ExcalidrawLib.registerFontsInCSS();

**Comment by zsviczian** [comment]
Yeah, come to think of it, loadFontFromFile is not initialized until you open an excalidraw view.

Please unzip [main.js.zip](https://github.com/user-attachments/files/17611757/main.js.zip) and replace main.js in the `vault/.obsidian/plugins/obsidian-excalidraw-plugin` folder. Then restart Obsidian and try again `ExcalidrawLib.registerFontsInCSS()` before opening a drawing.

@Daniel21b, please respond to my [earlier questions](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/2086#issuecomment-2453496238).

**Comment by HoodyEz** [comment]
![image](https://github.com/user-attachments/assets/129f8f13-a694-4e37-901a-9e2f7d2a8723)
When I start Obsidian and open an Excalidraw note, the error appears; however, when I open another note, the error disappears
**First Time after Obsidian starts**
![image](https://github.com/user-attachments/assets/58d14d2b-4b63-48b1-bc98-3f6adc7e2d67)
**Next Time**
![image](https://github.com/user-attachments/assets/96557386-60dd-40d9-b6dd-b27cbe45a5a1)

**Comment by zsviczian** [comment]
exactly, this is a font loading issue. The bit I don't understand is why it happens on your device, but not on mine. These fonts are embedded in the plugin. Loading of fonts is triggered and awaited when you open the drawing.

@HoodyEz
- please share Obsidian Debug info so I can see the environment you are using.
- Did you download and replace the main.js, then run registerFontsInCSS() as mentioned [above](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/2086#issuecomment-2453548437). What did you find?

**Comment by HoodyEz** [comment]
SYSTEM INFO:
	Obsidian version: v1.7.4
	Installer version: v1.6.7
	Operating system: Windows 11 Home 10.0.26100
	Login status: logged in
	Language: en
	Catalyst license: none
	Insider build toggle: off
	Live preview: off
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 11
	Plugins enabled: 9
		1: Backlink Cache v1.11.2
		2: Hover Editor v0.11.21
		3: Hotkeys for specific files v1.4.1
		4: Imgur v2.6.3
		5: Latex Suite v1.9.7
		6: PDF++ v0.40.13
		7: Spaced Repetition v1.13.2
		8: Tray v0.3.5
		9: Excalidraw v2.6.4

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by HoodyEz** [comment]
> exactly, this is a font loading issue. The bit I don't understand is why it happens on your device, but not on mine. These fonts are embedded in the plugin. Loading of fonts is triggered and awaited when you open the drawing.
> 
> @HoodyEz
> 
> * please share Obsidian Debug info so I can see the environment you are using.
> * Did you download and replace the main.js, then run registerFontsInCSS() as mentioned [above](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/2086#issuecomment-2453548437). What did you find?

I downloaded and replaced the main.js of the Excalidraw plugin, this is the result
![image](https://github.com/user-attachments/assets/44c6bbc6-c1e6-4b5a-9c44-5d0669adec65)

**Comment by zsviczian** [comment]
I found a device on which I am able to replicate the issue. I will debug tonight.

**Comment by zsviczian** [comment]
@HoodyEz and @Daniel21b:  Please test 2.6.5-beta-1
You can install beta releases using [BRAT](https://youtu.be/2poSS-Z91lY?si=3LmDpWzYXPy7EhjF&t=331)

**Comment by HoodyEz** [comment]
Yeeahh, the bug is gone 🎉🎉
