### ISSUE TITLE
BUG: When I upgraded to the latest version of Obsidian v1.7.4, the toolbar of Excalidraw became very large.

### ISSUE THREAD

**Issue by sparky1** [zsviczian/obsidian-excalidraw-plugin#2087]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.4
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 22.6.0: Sun Dec 17 22:18:09 PST 2023; root:xnu-8796.141.3.703.2~2/RELEASE_X86_64 22.6.0
	Login status: not logged in
	Language: zh
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 22
	Plugins enabled: 17
		1: Advanced Tables v0.18.1
		2: Templater v1.18.0
		3: QuickAdd v1.2.1
		4: Emoji Toolbar v0.4.1
		5: Quiet Outline v0.3.19
		6: Mermaid Tools v1.1.0
		7: Diagrams v1.5.0
		8: Search on Internet v0.5.0
		9: Customizable Menu v2.2.0
		10: Colorizelt v0.0.2
		11: Week Planner v0.1.4
		12: Custom Frames v2.4.7
		13: Dataview v0.5.67
		14: Day Planner (OG) v0.5.26
		15: Excalidraw v2.6.2
		16: Mousewheel Image zoom v1.0.22
		17: Kanban v2.0.51

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

1. When I upgraded to the latest version of Obsidian v1.7.4, the toolbar of Excalidraw became very large.
2. Excalidraw plugin can't be enabled in a new empty valut.
<img width="1331" alt="image" src="https://github.com/user-attachments/assets/63753ea4-f5e6-4e94-a593-bbcf5b4f251f">

### Expected behavior

- toolbar size as normal as before

**Comment by zsviczian** [comment]
yeah, this is not a bug, but an Obsidian feature. Obsidian changed the stylesheet, as a consequence font size setting and zoom level in Obsidian settings impacts Excalidraw. I couldn't find a way to counter act it... thus it's a feature (one I am not very happy with).

So in short, you need to change the font size in Obsidian setting and Excalidraw size will be back to normal.

<img width="1077" alt="image" src="https://github.com/user-attachments/assets/8b758874-cfd0-4c8c-a4b1-71642b41feb3">

**Comment by sparky1** [comment]
> yeah, this is not a bug, but an Obsidian feature. Obsidian changed the stylesheet, as a consequence font size setting and zoom level in Obsidian settings impacts Excalidraw. I couldn't find a way to counter act it... thus it's a feature (one I am not very happy with).
> 
> So in short, you need to change the font size in Obsidian setting and Excalidraw size will be back to normal.
> 
> <img alt="image" width="1077" src="https://private-user-images.githubusercontent.com/14358394/381747300-8b758874-cfd0-4c8c-a4b1-71642b41feb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDAyNjYsIm5iZiI6MTczMDMzOTk2NiwicGF0aCI6Ii8xNDM1ODM5NC8zODE3NDczMDAtOGI3NTg4NzQtY2ZkMC00YzhjLWE0YjEtNzE2NDJiNDFmZWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAxNTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZGQ4NTYwZjNjYzE5NWIxOGUwOWY5NzU4ODQxYjA4ZmZkOTQyY2Y5NDlhYTYxZThmYTAyOGMxY2FlMjQ2MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wz4iijjUBy0VqJNfv9qT18T_9d7qHa5j3JJjG2kAkI0">

it works, thanks!

**Comment by sparky1** [comment]
I found the very very useful features of Excalidraw are also been effected. for example, "Zoom to fit all elements" and "Zoom to selection".  😞

**Comment by zsviczian** [comment]
found a solution. releasing it in 2.6.5
You'll find the setting under Appearance and Behavior

<img width="1047" alt="image" src="https://github.com/user-attachments/assets/1bc39350-7c11-4f45-8d93-b2dd71296f87">
