### ISSUE TITLE
FR: Allow drawing on top of embedded files

### ISSUE THREAD

**Issue by breannar888** [zsviczian/obsidian-excalidraw-plugin#2089]
### Is your feature request related to a problem? Please describe.

For my notes I like to circle/highlight important sections and add comments, but this feature isn't currently possible with embedded notes. I would like to import a note, embed it within an excalidraw file and write on top of the embedded note. 

### Describe the solution you'd like

Allow drawing on top of the embedded note, similar to how pens can draw on top of images and PDF files.

### Real-life usage scenarios

1. I would use this to add hand written comments for my notes, especially complex code snippets
2. Add revision notes to papers I've written

### Describe alternatives you've considered

Adding an option to include the line numbers for embedded files would be helpful to connect comments to blocks of text

### Additional context

<img width="903" alt="Screenshot 2024-10-30 111533" src="https://github.com/user-attachments/assets/1b9bed8e-8320-45fa-af0c-c8db8b636e5b">

**Comment by zsviczian** [comment]
sorry, technically not possible. You can raise a feature request on https://github.com/excalidraw/excalidraw/issues but likelihood of getting this implemented is low. I've discussed the question with the lead Excalidraw developer and he confirmed the technical blockers why this is not possible. Sorry.

I agree, that this would be very nice!

**Comment by dangehub** [comment]
For this kind of requirement, there's a workaround: lower the transparency of the embedded note so that the handwriting underneath stands out more.

![Image](https://github.com/user-attachments/assets/5583951b-0d54-459d-9d35-d5197836dd5a)
