### ISSUE TITLE
SUPPORT: After updating to 2.6.3, it is not possible to load excalidraw.

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#2095]
### Have you checked the documentation and searched existing issues?

- [X] Yes, I have reviewed the documentation and searched for related issues.

### Your question

I just upgraded to the latest version, but another problem has occurred. As shown, the display plugin cannot be loaded. Even if I close and reopen the plugin, it won't work, and restarting Obsidian doesn't help either. It seems that I can't just upgrade casually...

### Steps you've already tried

I close and reopen the plugin, it won't work, and restarting Obsidian doesn't help either. It seems that I can't just upgrade casually...

### Expected outcome

![image](https://github.com/user-attachments/assets/4e7c53fc-2ca9-4970-a2d4-ef5fb3d0d649)

### Additional context

SYSTEM INFO:
	Obsidian version: v1.7.4
	Installer version: v1.7.4
	Operating system: Windows 11 Pro 10.0.22631
	Login status: logged in
	Language: zh
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Blue Topaz v2024071502
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 56
	Plugins enabled: 39
		1: Projects v1.17.4
		2: 增强编辑 v0.6.4
		3: Advanced Tables v0.22.1
		4: Auto Note Mover v1.2.0
		5: Better Export PDF v1.9.2
		6: Better footnote v1.0.1
		7: BRAT v1.0.5
		8: Buttons v0.5.1
		9: Calendar v1.5.10
		10: Canvas Mindmap v1.0.2
		11: Clear Unused Images v1.1.1
		12: Commander v0.5.2
		13: Custom Frames v2.4.7
		14: Dataview v0.5.67
		15: Easy Typing v5.5.5
		16: Editing Toolbar v2.4.16
		17: File Cleaner v0.1.5
		18: Floating Search v4.0.0
		19: Hotkey Helper v0.3.20
		20: Word Splitting for Simplified Chinese in Edit Mode and Vim Mode v1.12.0
		21: Virtual Linker / Glossary v1.5.1
		22: Unique attachments v1.0.3
		23: Templater v2.9.1
		24: Tag Wrangler v0.6.1
		25: Table Extended v1.6.1
		26: Style Settings v1.0.9
		27: Shell commands v0.22.0
		28: Settings Search v1.3.10
		29: Remove Unused Block IDs v1.0.9
		30: Recent Files v1.7.0
		31: QuickAdd v1.11.3
		32: Plugin Update Tracker v1.6.0
		33: Pane Relief v0.5.5
		34: Open Gate v1.11.6
		35: Mousewheel Image zoom v1.0.22
		36: Linter v1.27.1
		37: Kanban v2.0.51
		38: Icon Shortcodes v0.9.7
		39: Excalidraw v2.6.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by zsviczian** [comment]
Can you share a screenshot of the Developer Console?

CTRL+SHIFT+i (or CMD+OPT+i on a Mac), click "Console" on the top before making the screenshot


<img width="1203" alt="image" src="https://github.com/user-attachments/assets/270f2e4a-d5c4-400e-8570-ea0c02f47bdd">

**Comment by zsviczian** [comment]
Please update to 2.6.4. Watch the screen for any error notifications during Excalidraw startup (i.e. when enabling the plugin in community plugins). Let me know what notifications (if any) you see.

**Comment by zsviczian** [comment]
Please download and unzip: [main.zip](https://github.com/user-attachments/files/17615613/main.zip)
Copy it to the `Vault/.obsidian/plugins/obsidian-excalidraw-plugin` folder. Note, the .obsidian folder is a hidden folder.
After running it, look for a warning with this text in the console log, and send me a screenshot:

"ScriptEngine.getScriptName unexpected basename"

something that looks similar to this:
![image](https://github.com/user-attachments/assets/e024627d-8be3-4be9-bd76-a65bf2d23738)

**Comment by zsviczian** [comment]
Resolved in 2.6.4
Completely resolved in 2.6.5

To the best of my assessment the error is unrelated to 2.6.3, but related to incomplete logic in the script loader. The script loader got confused by finding `Scripts/excalidraw-family-tree`  while the scripts folder is `Scripts/excalidraw/`.
