### ISSUE TITLE
BUG: Online Images Doesn't Save when Cropping

### ISSUE THREAD

**Issue by HoodyEz** [zsviczian/obsidian-excalidraw-plugin#2096]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.4
	Installer version: v1.6.7
	Operating system: Windows 11 Home 10.0.26100
	Login status: logged in
	Language: en
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.6.3

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Steps to reproduce

1. Drag and Drop Image (Online)
2. Crop the image
3. Save (Error)

### Additional context

[screen-capture.webm](https://github.com/user-attachments/assets/9677b2ef-4b18-48ac-bc5f-e82d84aaac7f)

**Comment by zsviczian** [comment]
fixed in 2.6.4 will release it later today.

**Comment by HoodyEz** [comment]
![image](https://github.com/user-attachments/assets/5176aa55-8037-414c-8fbe-bf51e7aa7d7a)
This was the 1000. 🎉🎉
