### ISSUE TITLE
PNG and SVG export does not seem to work?

### ISSUE THREAD

**Issue by alextroop** [zsviczian/obsidian-excalidraw-plugin#21]
This is a wonderful plugin, thank you for making it!

The export to PNG and SVG does not seem to work -- I get the attached error. Is there a permission I need to enable?

<img width="560" alt="Screenshot 2021-04-26 at 14 53 07" src="https://user-images.githubusercontent.com/68741305/116095279-2cb57600-a6a0-11eb-932e-eef3ceb57167.png">

I am using v.0.11.13 on macOS v.11.2.1

**Comment by zsviczian** [comment]
Thanks! I did not notice that... however unfortunately this is a limitation imposed by Obsidian. This limitation is a good thing as it protects your PC from plugins accessing files on your system.

The workaround you can do is to use the context menu as explained [here](https://youtu.be/2cKlEwo8WU0?t=169) to copy the image as an SVG or PNG to the clipboard. Or you can do screen clipping using what ever feature your operating system provides. I am on Windows and I can press shift+Win+S for screen clipping to capture any impage to PNG.

I will remove the the Export button.

**Comment by alextroop** [comment]
Oh, I see, thanks! The workaround I used was to simply upload the file to the excalidraw.com and then export from there.
