### ISSUE TITLE
FR: Permanently Remove Excalidraw Properties From Obsidian Properties

### ISSUE THREAD

**Issue by toldeveloper** [zsviczian/obsidian-excalidraw-plugin#2102]
### Is your feature request related to a problem? Please describe.

Excalidraw is flooding the Obsidian properties panel with useless values.
It makes the whole panel messy, while providing nothing of value to the panel.
People are not gonna filter for "excalidraw-linkbutton-opacity".

### Describe the solution you'd like

Remove them. To me, they seem like something that should not be there, yet somehow for functionality did. They seem like something that should be "under the hood", not together with user-created properties.
Obsidian properties were introduced in 2023, and i assume the plugin worked before that, so i dont know why they are integrated together now.

### Real-life usage scenarios

Lots of obsidian users are very OCD on their system setup. This goes in a ruins my list of properties, while providing no value.

### Additional context

A video of me trying to delete all these properties, which reappear when restarting.
![Obsidian_oO6Enz21wi](https://github.com/user-attachments/assets/28b68d33-4d96-4667-ad2e-79a73d4939b0)

**Comment by toldeveloper** [comment]
While i like the plugin and the flexibility of creating doodles when needed, im leaning towards just uninstalling it, so it does not mess with my setup...

**Comment by zsviczian** [comment]
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/a04b469f-e3f5-4a72-8ba2-a4b11f6f81d5">

**Comment by zsviczian** [comment]
Excalidraw offers lots of power features via properties, that is why they are loaded by default.
