### ISSUE TITLE
Bug: Image link in excalidraw not updating when changing the name of the image

### ISSUE THREAD

**Issue by KALKI-the-avataar** [zsviczian/obsidian-excalidraw-plugin#211]
**Describe the bug**
Suppose I pasted an image in excalidraw and then I cntrl click image. 
- it opens image in obsidian
- now If I rename the image  and go back
- then it shows some box with some symbol(essentially image link is not updated in the markdown file)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by zsviczian** [comment]
I think I found the issue. It is with the handling of relative links. I will correct it tomorrow.

**Comment by zsviczian** [comment]
Fixed in 1.4.3. The issue was the handling of relative links.
