### ISSUE TITLE
FR: use Obsidian color for light and dark mode

### ISSUE THREAD

**Issue by nousernameavailableanymore** [zsviczian/obsidian-excalidraw-plugin#2110]
### Is your feature request related to a problem? Please describe.

Maybe I m missing something here, but I would simply like to follow the background of the canvas the Obsidian colors (--background-primary) colors for light and dark mode, just like the built-in canvas feature that.
That works flawlessly and you always know / can set what color you get in both modes, instead of hoping for the best what the color inversion makes of it.

This also goes for the other colors. It should be possible to set them manually and separately for both light and dark mode, completely avoiding the automatic inversion.

This is the main reason why I dont use Excalidraw despite really wanting to and trying several times.
It just feels like "hacked in" component instead of a native feature.

### Describe the solution you'd like

Just add an option to manually set the canvas background separately for light and dark mode.

For the other colors there should be slots (#1, #2...) and each color should be manually configurable for light and dark mode.
So that you know exactly what color you get in both light / dark mode, when writing something with the color in slot #1.

### Describe alternatives you've considered

Using built-in canvas.

**Comment by zsviczian** [comment]
I understand. I will not work on this. Sorry.

The Excalidraw package comes with it's own elaborate stylesheet and changing it would break upgradability when new features are released, not to mention the unbelievable amount of time it takes to tweak css. I don't enjoy that. 

If you have skills and time and can propose a non-invasive workaround in the code to make this happen, let's talk about it, I am always happy when people contribute with solutions. PRs are welcome!

That said, there are few options you might want to explore:
In settings under appearance and behavior / themes and styling you have a few settings that might be helpful:
![image](https://github.com/user-attachments/assets/d33f953d-b7b7-4039-9d84-f0a3f0d13c99)
 
You can set up your own color palette and template to match whatever colors you like:
- [Dynamic Styling and Color Inversion](https://youtu.be/fypDth_-8q0)
- [New Color Picker and Updated Palette Loader](https://youtu.be/diBT5iaoAYo)
- [Mastering Excalidraw Templates: 4 Hands-on Techniques to Boost Your Productivity](https://youtu.be/jgUpYznHP9A)
- [The Excalidraw-Obsidian Showcase: 57 key features in just 17 minutes](https://youtu.be/P_Q6avJGoWI)
  - 08:40
  - 10:47

**Comment by nousernameavailableanymore** [comment]
@zsviczian 
First of all, thank you for your swift response.
However, both the template and color palette workaround do not tackle the actual issue (at least if I understand it correctly), which is the automatic color inversion.

So while I can set the canvas background manually for one mode (dark or light), when switching to the other one, the background will be automatically converted to some "random" color.

So while I understand that you dont want to make any major changes, an "easy" solution would be to just add an option to disable the automatic color inversion.
There is already a color picker for both the background and the color palette in place.
It would just need to remember those for both light and dark mode and _not_ do an automatic inversion.

Would something like that (option to disable automatic color inversion) be possible?

**Comment by zsviczian** [comment]
These features are already there. Automatic color inversion is something you've configured in plugin settings. Use the settings described above to control this. Most of the relevant settings are under "Appearance and Behavior" in plugin settings, and for image embeds the color inversion or not is under "Embedding Excalidraw into your notes". Plus, you can override the embedding features at the individual drawing level via document properties.

I do not use dark mode in Excalidraw because of the color distortion, instead I use a custom color palette. There is also a color inversion script that uses a more accurate library/logic to change colors that you may want to experiment with.
