### ISSUE TITLE
BUG: icon on ribbon menu keep freshing every time reopen Obsidian

### ISSUE THREAD

**Issue by how2051** [zsviczian/obsidian-excalidraw-plugin#2115]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.6
	Installer version: v1.2.8
	Operating system: Windows 10 Home China 10.0.22631
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 5
	Restricted mode: off
	Plugins installed: 15
	Plugins enabled: 12
		1: Dataview v0.5.67
		2: Excalidraw v2.6.6
		3: Homepage v4.0.7
		4: Hider v1.5.1
		5: Tracker v1.14.0
		6: Recent Files v1.7.1
		7: Waypoint v2.1.0
		8: DIDA(滴答清单) v1.0.0
		9: Templater v2.9.1
		10: Image auto upload Plugin v3.7.0
		11: File Explorer Note Count v1.2.2
		12: Task Status v1.2.1

RECOMMENDATIONS:
	Update installer: installer version too low, please download from https://obsidian.md/download?os=win&arch=x64 and reinstall.
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

as title, this excalidraw icon on ribbon menu keep freshing every time reopen Obsidian, even if I remove this icon from the ribbon menu in setting, this icon still will show up next time I reopen Obsidian.

### Steps to reproduce

reopen the Obsidian

### Expected behavior

if I remove excalidraw icon from setting in ribbon menu, when I reopen obsidian, it should not appear again.
if I drag excalidraw icon to a certain place in ribbon menu, it should always be here, not go to the bottom of the ribbon menu every time I reopen the Obsidian.

**Comment by zsviczian** [comment]
Fixed in 2.7.0. However, I do not plan to publish 2.7.0 until December.
You can access the beta using BRAT, however, I will push this change to the beta channel in the next few days.
