### ISSUE TITLE
FR: Adding Images to the stencil library

### ISSUE THREAD

**Issue by einsteinfreak** [zsviczian/obsidian-excalidraw-plugin#2116]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.6
	Installer version: v1.7.5
	Operating system: #135-Ubuntu SMP Fri Sep 27 13:53:58 UTC 2024 5.15.0-125-generic
	Login status: not logged in
	Language: de
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 1
		1: Excalidraw v2.6.7

### Describe the bug

My image is not added to the library.
Instead I get an error message that the function "Adding images to the library will be supported soon". 

![error when trying to add png image to library](https://github.com/user-attachments/assets/d3724f9f-5c1e-4b17-9e88-bf7769df8852)

### Steps to reproduce

1. Add a png image to a new drawing
2. Open the library
3. Press + button

Now the error message should appear. 

### Expected behavior

Image upload to library worked on older Excalidraw versions.

### Additional context

When I updated Excalidraw today to version 2.6.7, I saw that in the release comment there have been some other issues regarding the library. So maybe this is just another bug related to this. 
Hope my tickets helsp to clarify this.

**Comment by zsviczian** [comment]
Not a bug, but a feature request.
However, this is a feature I do not plan to implement since images are not stored in notes, only image links are stored in notes. Storing the image link in the library, those links would not be updated when you move files around in Obsidian resulting in broken links all over the place in the library.

**Comment by zsviczian** [comment]
This is my workflow for managing a library of icons: https://youtu.be/_OEljzZ33H8

**Comment by einsteinfreak** [comment]
Wow! How could I possibly miss this yet?! THANKS for the link. I appreciate your video a lot and got my own Icon Library running in my vault. Very smart way of doing it 💡😃

One key fact that I finally understood is: **An image is NOT an image.** 💥
What I mean:

- When I draw sth. within ExcaliDraw, then IT IS POSSIBLE to add such an 'image' to the Library. This is what I have done in the past. BUT this is sth. else than what I did yesterday, which was... 
- Drawing sth., then copy it as png (or svg), then paste it to my drawing and then try to add this 'image' to the Library. And this IS NOT POSSIBLE.

Small difference, huge impact. 
I understand now the obvious reasons why this did not work. Thanks again for you explanation and the solution as well.  🤩
