### ISSUE TITLE
BUG: restarting or reloading app does not respect `Create new drawing` icon position and toggle in ribbon

### ISSUE THREAD

**Issue by bfeitknecht** [zsviczian/obsidian-excalidraw-plugin#2121]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.7.7
	Operating system: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020 24.1.0
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.6.7

### Describe the bug

changing the position or show / hide toggle of the `Create new drawing` icon in the ribbon is not consistent on restart or reload of the app

### Steps to reproduce

1. install and enable excalidraw plugin from community store in sandbox vault
2. hide excalidraw icon `Create new drawing` from ribbon or change its position with drag and drop
3. execute `Reload app without saving` from command palette
4. icon reappears at the bottom!

### Expected behavior

icon being hidden or position changed stays consistent

### Additional context

this is undesired behavior. i don't want to have inconsistency in my UI and this bug has forced me to basically never quit obsidian which leads to at times useless background activity.

### Suspicions

after reload and restart of the app, the icon only appears after about some half a second. maybe the plugin loading time is too long to register the check of the ribbon menu configuration? wild speculations here, just guessing.

**Comment by Graywaren** [comment]
I'm adding this on here because I suspect it's related, but the Add Drawing icon also does not respect drag & drop order on the ribbon menu either. It resets to the bottom on reload/restart etc.
