### ISSUE TITLE
SUPPORT: How do I move my Excalidraw files from 2.5.2 to the latest version?

### ISSUE THREAD

**Issue by back-lacking** [zsviczian/obsidian-excalidraw-plugin#2128]
### Have you checked the documentation and searched existing issues?

- [X] Yes, I have reviewed the documentation and searched for related issues.

### Your question

How do I move my Excalidraw files from 2.5.2 to the latest version? I tried to update my plugin to 2.6.x, but in doing so, all of my excalidraw files were broken and not able to be rendered properly. This was fixed by rolling back to 2.5.2 version. 

### Steps you've already tried

1. Be on v2.5.2 of the plugin
2. Update the plugin to latest release
3.  Try to open Excalidraw files, see that they open like markdown notes and get errors. 

### Expected outcome

I can open my Excalidraw files when in the new version

**Comment by zsviczian** [comment]
please share what errors you are encountering.
There should be no issue opening files from 2.5.2 with 2.6.7 - the errors likely stem from another source (maybe you updated other plugins as well and they have caused the issue, maybe you synchronized files and that cause the issue, there can be many root causes) ... but unless I see what's on your screen and what error you are receiving I cannot help you.

**Comment by back-lacking** [comment]
@zsviczian sorry for the late response. 
So i just updated the plug in in a copy of my vault, and the update went through with no issue. all my excalidraw files were still accessible. same thing with the real copy of my vault. 
iirc, the error i had before was related to a json syntax.
