### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by shisunsun** [zsviczian/obsidian-excalidraw-plugin#2137]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

macos sequoia 15.1.1 
obsidian 1.7.7
Excalidraw 2.6.7

### Describe the bug

color pick could not scroll, so sometimes cant see the input box and set hexadecimal color at the bottom

![image](https://github.com/user-attachments/assets/8218ab36-f295-4fe8-a650-8e00c9ff24be)

### Steps to reproduce

1. select a box shape
2. set the stroke color of the box
3. scroll the color picker of stroke to the bottem
4. cant see the input box of hexadecimal color

### Expected behavior

1. select a box shape
2. set the stroke color of the box
3. scroll the color picker of stroke to the bottem
4. see and set the input box of hexadecimal color

**Comment by zsviczian** [comment]
I recommend a smaller palette :)

**Comment by shisunsun** [comment]
> I recommend a smaller palette :)我推荐一个较小的调色板:)

Hahaha, that's how I'm dealing with it right now.

The reason I use a large color picker that contains so many colors is because I want to select different saturations. If the custom colors，for the lines and undertones,  can set up a dozen or so standard colors, and then just shortcut to select the different saturations(shades) like we set up a canvas background color.It would be even better if it could do that.

![image](https://github.com/user-attachments/assets/9c27f083-149e-420a-ac7a-579d2f348056)

**Comment by zsviczian** [comment]
You can set up shades for all colors (stroke, background, canvas). I
recommend you read this article:
https://excalidraw-obsidian.online/WIKI/03+Advanced+Usage/Color+Palette

**Comment by shisunsun** [comment]
@zsviczian Thanks, your reply helped me a lot!🎉🍻
