### ISSUE TITLE
BUG: Volatile data

### ISSUE THREAD

**Issue by jiajiala** [zsviczian/obsidian-excalidraw-plugin#2158]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [ ] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.7.6
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Language: zh
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 137
	Plugins enabled: 10
		1: Better Search Views v0.2.2
		2: Hover Editor v0.11.18
		3: Plugin Update Tracker v1.6.0
		4: Plugins Annotations v1.7.8
		5: Recent Files v1.7.1
		6: Copy Block Link v1.0.4
		7: Find Orphan Block Identifiers v1.0.3
		8: Git v2.30.1
		9: I18N v1.6.0
		10: Excalidraw v2.6.8

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

When I was using git to manage versions, I found that even if I moved a small piece of content, it would change the length and width of the elements of the entire file, resulting in a lot of useless backups
![image](https://github.com/user-attachments/assets/5e77f539-3831-4f55-8b5e-6bea305ded90)

### Steps to reproduce

Move an element, then ctrl+z, and you will find that the data of the other content has changed

### Expected behavior

The value of the element is expected to remain stable when no one touches it

**Comment by zsviczian** [comment]
This is not a plugin issue, but an Excalidraw component issue. You need to raise this with the Excalidraw project: https://github.com/excalidraw/excalidraw/issues

However, I don't understand your comment, since if you "move a small piece of content" that means you made a change to the file and regardless of the width/height change this would generate an update of the file.
