### ISSUE TITLE
BUG: Deleting fullscreen drawing causes "broken" obsidian fullscreen view

### ISSUE THREAD

**Issue by nobkd** [zsviczian/obsidian-excalidraw-plugin#2161]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

```
SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.7.7
	Operating system: #1 SMP PREEMPT_DYNAMIC Thu Dec  5 18:38:25 UTC 2024 6.11.11-300.fc41.x86_64
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.7.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```
- OS: Fedora Linux 41 (KDE Plasma) x86_64 (Wayland)

### Describe the bug

Stays in weird fullscreen mode, after file deletion. Escape key does nothing.

### Steps to reproduce

1. Create Excalidraw drawing
2. Enter full screen mode
3. Delete Excalidraw drawing from file explorer
4. Be stuck in weird fullscreen mode (until obsidian restart)

### Expected behavior

Exit fullscreen mode on file deletion

### Additional context

https://github.com/user-attachments/assets/bce3db20-bd92-4ed5-bc86-867dcee3dadc

I don't know if this can be fixed on your end, or if this is more of an Obsidian problem.

**Comment by zsviczian** [comment]
fixed in 2.7.1 (will release it a bit later)
