### ISSUE TITLE
BUG: Incorrect text elements detection with empty lines

### ISSUE THREAD

**Issue by Alezy80** [zsviczian/obsidian-excalidraw-plugin#2168]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.7.7
	Operating system: Windows 10 IoT Enterprise 10.0.19045
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Things v2.1.20
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 37
	Plugins enabled: 28
		1: Lazy Plugin Loader v1.0.18
		2: Dataview v0.5.67
		3: Outliner v4.8.1
		4: Periodic Notes v0.0.17
		5: Templater v2.9.1
		6: Tasks v7.14.0
		7: Automatic Table Of Contents v1.5.0
		8: Advanced URI v1.44.2
		9: Copy as HTML v1.1.3
		10: Smart Typography v1.0.18
		11: Tag Wrangler v0.6.1
		12: Calendar v1.5.10
		13: Commander v0.5.2
		14: Janitor v1.0.7
		15: Linter v1.27.1
		16: Minimal Theme Settings v8.1.1
		17: QuickAdd v1.11.5
		18: Style Settings v1.0.9
		19: Show Whitespace v0.2.5
		20: Omnisearch v1.25.1
		21: Share Note v0.8.17
		22: Excalidraw v2.6.8
		23: ExcaliBrain v0.2.15
		24: Kanban v2.0.51
		25: Markmind v3.0.9
		26: Local Images Plus v0.15.9
		27: Paste image rename v1.6.1
		28: Auto Link Title v1.5.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

I'm using Excalidraw and Linter plugins. Linter has setting "All headings have one blank line both before and after". When I've got edit Excalidraw document as Markdown, Linter inserts a blank line after `# Excalidraw Data` and `## Text Elements`. After that, document rendered incorrectly - the first text box contains `## Text Elements` prepended to text.

### Steps to reproduce

1. Create Excalidraw drawing.
2. Add any text.
3. Open file with text editor, like Windows notepad
4. Add empty lines after `# Excalidraw Data` and `## Text Elements`
5. Look at the drawing - the text changed to  `## Text Elements original text`
6. If you draw another text in diagram, there are will be two `## Text Elements` in source.

### Expected behavior

Special section detection must ignore empty lines. The first empty line (or maybe all empty lines) after `## Text Elements` header mustn't be added to text block.

**Comment by Alezy80** [comment]
Seems related to #1861

**Comment by zsviczian** [comment]
It does seem related.
I will take a look, however the basic recommendation is not to lint excalidraw files. `# Excalidraw Data` is auto generated and not intended to be modified.
