### ISSUE TITLE
BUG: Obsidian 1.7.7 and exalidraw 2.7.1 not working on iPad and Iphone

### ISSUE THREAD

**Issue by r00ta** [zsviczian/obsidian-excalidraw-plugin#2170]
### Have you searched for existing issues (including closed ones)?

- [x] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [x] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Operating system: ios 16.5.1 (Apple iPad8,9)
	Obsidian version: 1.7.7 (172)
	API version: v1.7.7
	Login status: logged in
	Language: en
	Catalyst license: none
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.7.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

Just installed Obsidian 1.7.7 and the exalidraw plugini version 2.7.1 on iPad and iPhone and when I create a new exalidraw only the markdown is displayed. 

On the top right corner there is an error 

Error loading drawing: undefined is not an object (evaluating 'A.reduce') try manually fixing the file or rrestoring an earlier versiion from sync history. 

### Steps to reproduce

1) install obsidian
2) install the plugin
3) create a new exalidraw file

### Expected behavior

the default welcome file is properly displayed

### Additional context

same issue on iphone

![IMG_0065](https://github.com/user-attachments/assets/d45da503-8041-4832-8eeb-751377121906)

**Comment by kevinscottcoleman** [comment]
Same issue. I additionally see a message that says - "Loading fonts... This is taking longer than expected. If this delay occurs regularly then you may download the fonts locally to your Vault."

**Comment by r00ta** [comment]
I confirm this is fixed in 2.7.2. Thank you very much @zsviczian for the quick fix and for developing/maintaining such an awesome plugin ❤️

**Comment by rawatraghav** [comment]
Hi Team, 
The same issue popped up today for me.

Operating system: ios 18.3.1 (Apple iPad 10th Gen)
Obsidian version: 1.8.7 
Excalidraw version: 2.8.3

Could you help out? Thanks alot!
