### ISSUE TITLE
BUG: Flash bang

### ISSUE THREAD

**Issue by Dopairym** [zsviczian/obsidian-excalidraw-plugin#2178]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Describe the bug

When you are in dark mode and you enter a drawing it first shows a white screen 

https://github.com/user-attachments/assets/45eb5943-a9fe-4482-a285-b82996d34445

### Expected behavior

don't show the white screen

**Comment by zsviczian** [comment]
fixed in 2.7.4
