### ISSUE TITLE
BUG: Excalidraw Files Not Displaying Correctly in PDF Export of Nested Embedded Notes

### ISSUE THREAD

**Issue by yizhenAllen** [zsviczian/obsidian-excalidraw-plugin#2184]
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:  
Obsidian version: v1.7.7  
Installer version: v1.7.7  
Operating system: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 23.6.0  
Login status: logged in  
Language: en  
Catalyst license: none  
Insider build toggle: off  
Live preview: on  
Base theme: adapt to system  
Community theme: none  
Snippets enabled: 0  
Restricted mode: off  
Plugins installed: 1  
Plugins enabled: 1  
1: Excalidraw v2.7.3

### Describe the bug

The drawing is embedded into **NoteA**, **NoteA** is embedded into **NoteB**, and **NoteA** has YAML section(or properties)
Then export **NoteB**, the drawing cannot show properly.

### Steps to reproduce

1. Install Excalidraw Plugin, enable it
2. Create a new note named **NoteA**
3. Open Command Palette, choose “Excalidraw: Create new drawing - in a new tab - and embed into active document”
4. Draw something, save and close the canvas
5. You should see your drawing in **NoteA** now
6. Create another note named **NoteB**, embed **NoteA** into it
7. You should see your drawing in **NoteB** now
8. Export **NoteB** as pdf, the drawing shows well
9. Add **YAML section** to **NoteA**, for example, add a tag property (Even the section only contains two `---` and no properties, it can cause the export problem)
10. You shoud see your drawing in **NoteB** well, but just inside Obsidian!
11. Export **NoteB**, the Drawing will only export **as markdown file**, as below: 
![image|300*300](https://forum.obsidian.md/uploads/default/optimized/3X/c/c/cc10b35ca243abc619b2b7a5e6e1999ef97c5d87_2_690x417.png)

### Expected behavior

The export result of **NoteB** shows the drawing properly, just as inside Obsidian
(the drawing is embedded into **NoteA**, **NoteA** is embedded into **NoteB**, and **NoteA** has properties)

**Comment by zsviczian** [comment]
Interesting scenario and well documented. I was able to reproduce the issue.

Unfortunately, Obsidian's PDF export is not really exposed formally to Plugins via the API, thus the solution is a bit shaky, This scenario I never tested.

**Comment by zsviczian** [comment]
Please test this file and let me know what you find.
When testing I am more interested in all other possible scenarios for PDF export and document previews, not just the one you describe. This version fixes your case... but I want to be sure it does not break others.

to install:
- Download [main.zip](https://github.com/user-attachments/files/18268699/main.zip)
- unzip
- Copy main.js to your plugin folder (click the folder icon in community plugins, then open `obsidian-excalidraw-plugin` subfolder)
![image](https://github.com/user-attachments/assets/1ef1fdf0-2b5e-4f55-9b7e-25f1c5b2e457)
- replace main.js with the one in the zip and restart Obsidian

**Comment by yizhenAllen** [comment]
Thank you! After using your file, the drawing displays properly in the scenarios I tested:
> All the notes below have properties
- [x] Simply embed a drawing into NoteA, export NoteA
- [x] Then, embed NoteA into NoteB, export NoteB
- [x] Then, embed NoteB into NoteC, export NoteC
- [x] ...

Will the fix be included in the next update?

**Comment by zsviczian** [comment]
of course, but I don't plan to release a new update in the near future.
In the meantime, please keep testing PDF exports and let me know if anything breaks.

**Comment by yizhenAllen** [comment]
Alright, thanks, I'd love to.

**Comment by yizhenAllen** [comment]
@zsviczian Hi there, I found a new bug: when Excalidraw notes/elements are embedded in a table, they cannot be resized correctly, the maximum size is limited.

I would like them to be resizable freely, just like when they are outside the table, thanks in advance!

<img width="1756" alt="image" src="https://github.com/user-attachments/assets/4ef2d16b-1146-447d-b563-340ec27511cb" />

**Comment by zsviczian** [comment]
Hi @yizhenAllen, a closed bug is not the right place to raise this. This request will definitely get lost this way.
Please open a new Feature Request.

**Comment by yizhenAllen** [comment]
Alright
