### ISSUE TITLE
request: basic CSS styling options

### ISSUE THREAD

**Issue by firinael** [zsviczian/obsidian-excalidraw-plugin#22]
I use a specific CSS styling for all my embedded images, but Excalidraw drawings don't utilize the same CSS class, so the styling doesn't apply to them.

I ask that settings for styling like border, border radius, margins, etc be provided in the Excalidraw plugin menu.

Not exactly urgent, but it'd be nice to have for people that aren't fond of fiddling with snippets and themes.

Thanks!

edit: while there aren't any native options, anyone that wants to style their embed image can use the following
```
.excalidraw-svg svg {
	put stuff here
}
```

**Comment by zsviczian** [comment]
Excellent suggestion. I will add some styling options.
Any concrete suggestions of what classes you are looking for?

.excalidraw-svg.left
.excalidraw-svg.right
.excalidraw-svg.center
.excalidraw-svg

were you looking for anything more?

**Comment by firinael** [comment]
> were you looking for anything more?

Nope! I think those are more than enough, not like there's that much to do with styling images.

**Comment by zsviczian** [comment]
Please test this release, I hope to have resolved your request:
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.6-test

**Comment by zsviczian** [comment]
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.6
