### ISSUE TITLE
Make pen width smaller

### ISSUE THREAD

**Issue by YesterKo** [zsviczian/obsidian-excalidraw-plugin#220]
**Is your feature request related to a problem? Please describe.**
I use Excalidraw for solving math and physics problems. For that I use the pen function most of the time, but the problem is that the pen's width is too big for my handwriting. It is also looks off when I then use the line or arrow tool, due to the differences in widths. (See first screenshot)

**Describe the solution you'd like**
I'd like an option to change the default widths in the left pane, or a box for entering a custom size. It would be perfect if we could change the pen width seperately.

**Describe alternatives you've considered**
For now I've been switching to markdown view and manually changing the `currentItemStrokeWidth` to 0.5.

**Additional context**

Example with stroke width 1 for arrows and text:
![image](https://user-images.githubusercontent.com/12015722/139060706-74ad61e7-dd9c-43f9-8d2c-4c1654f72a29.png)

Example with stroke width 0.5 for arrows and text:
![image](https://user-images.githubusercontent.com/12015722/139061815-f2b0b916-cb22-4310-9eaa-c991bec4a085.png)

Example with stroke width 1 for arrows and 0.5 for text:
![image](https://user-images.githubusercontent.com/12015722/139061134-a3eb5096-0ef3-4f44-8747-81b11d19b902.png)

I also tried to make a Templater script for it, but unfortunately it didn't work unless I'm in markdown view. If the ExcalidrawAutomate can update `Appstate`, I'd love to hear about it.

**Thank you zsviczian for making and updating this awesome plugin!**

**Comment by zsviczian** [comment]
I added a fourth thinner line with [1.5.23](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.5.23)

**Comment by arximboldi** [comment]
I am having this issue. When using a tablet (e.g Wacom) the pen width is incredibly large compared to the widths in other elements.
