### ISSUE TITLE
Nested drawing gets squashed on refresh

### ISSUE THREAD

**Issue by mure** [zsviczian/obsidian-excalidraw-plugin#223]
**Describe the bug**
After nesting a drawing within another drawing, reloading the parent drawing will cause the nested one to get its dimensions squashed.

**To Reproduce**
It seems to be related to the size of the parent drawing or how far away the nested drawing is from the center of the parent. On a small drawing, it doesn't reproduce (or maybe it's just not noticeable).

https://user-images.githubusercontent.com/9257800/139341797-f8d720c6-027a-4d29-983c-75ac3b95c1a4.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 1.4.1

**Comment by zsviczian** [comment]
I was able to reproduce. This happens when you resize the image and accidentally change the aspect ratio. If you resize hold the CTRL (I guess CMD on Mac), then the image will keep its aspect ratio.

I will investigate what I can do to fix this.

**Comment by zsviczian** [comment]
Fixed in 1.4.3. 
Issue was not calling `ea.reset()` before calling `ea.createSVG()`.
