### ISSUE TITLE
Custom Font Settings

### ISSUE THREAD

**Issue by locriacyber** [zsviczian/obsidian-excalidraw-plugin#225]
Currently there is no way to change the font used for Hand written, Sans, and Code fonts. Adding a list of fonts to consider would also solve #169 .

Also, I hope there is Serif and Sans - two options - instead of Normal.

**Comment by YesterKo** [comment]
Hi!

I can't help you with changing the font used for the fonts, but you can change the default font by:

1. Make a new drawing
1. Go to markdown view from "More options" and select "view as Markdown".
2. Find a line named `"currentItemFontFamily"` and change the value of it to `2`. This will change it to Normal font.
The line should then look like this: `"currentItemFontFamily": 2,`
3. Make it your default template under `Obsidian settings > Excalidraw > Excalidraw template file`
4. Done! Now all of your new drawings will default to Normal font.

**Comment by zsviczian** [comment]
The forth font option was implemented in [1.5.17](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.5.17)
