### ISSUE TITLE
Latex command not in command palette

### ISSUE THREAD

**Issue by erex** [zsviczian/obsidian-excalidraw-plugin#227]
**Describe the bug**
I'm anxious to have Latex ability in Excalidraw (and Obsidian).  However, insert Latex not appearing in Command palette

**To Reproduce**
Trying to duplicate demonstration shown in Video dated 01Nov21
- Current version of plugin is 1.4.4
- Create new note
- Open command palette (ctrl-P)
- No entry for "Excalidraw: Insert Latex formula"

**Expected behavior**
Can't insert a formula if there is no command to do so

**Screenshots**
My command palette
![image](https://user-images.githubusercontent.com/330744/139824116-e7b549b1-f19a-4dfd-8366-37cf142f5c63.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian 0.12.19

**Additional context**
Is there a plug-in dependency that I'm missing?

**Comment by zsviczian** [comment]
- This command palette action will only show if you have an Excalidraw drawing as the active pane.
Open a new drawing. (if you create a new empty note, you can use CTRL+P and select convert to Excalidraw drawing, or you can create a new drawing using the ribbon button, or by right clicking the folder in the file manager and selecting create new drawing)
- Click in the canvas to ensure it is the active view.
- Press CTRL+P and the LaTeX command should be there

**Comment by erex** [comment]
Apologies, makes sense.  I understand.
