### ISSUE TITLE
Transclude rendered markdown notes 

### ISSUE THREAD

**Issue by HiRolla** [zsviczian/obsidian-excalidraw-plugin#229]
Hello! Your obsidian-excalidraw-plugin ia amazing! I'm happy since i found it! Thank you for your work and great explonation videos!

Is there any way to transclude a rendered (processed) markdown text into the drawing? First of all I need transcluded links to be rendered and clickable.  Now I can get just a raw text of transcluded notes. That is not bad already, so thank you for that!

**Comment by zsviczian** [comment]
What I was thinking is to build on the image element and use it to transclude images of rendered documents (much like how I process LaTeX equations) This won’t solve the links you are after though.

My best recommendations for the links to work currently is to use the over preview of links in a drawing. that will bring up the rendered page with links working.

**Comment by HiRolla** [comment]
> What I was thinking is to build on the image element and use it to transclude images of rendered documents (much like how I process LaTeX equations) This won’t solve the links you are after though.

Yes, I understand. Pictures would be a good solution!

> 
> My best recommendations for the links to work currently is to use the over preview of links in a drawing. that will bring up the rendered page with links working.
Thank you! I'll use your recomedation

**Comment by zsviczian** [comment]
#239
