### ISSUE TITLE
drawing alignment

### ISSUE THREAD

**Issue by bagameow** [zsviczian/obsidian-excalidraw-plugin#23]
I want to align image in the screen by something like
```
'''excalidraw
[[excalidraw/drawing.excalidraw|100|left]]
'''
```
so the drawing in preview mode will show on left side instead middle of screen.

please also support 'right' side option

**Comment by zsviczian** [comment]
Great suggestion. I will look into this.

**Comment by zsviczian** [comment]
Please test this release, I hope to have resolved your request:
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.6-test

**Comment by zsviczian** [comment]
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.6
