### ISSUE TITLE
make a frame linkable 

### ISSUE THREAD

**Issue by JJger148** [zsviczian/obsidian-excalidraw-plugin#231]
**Is your feature request related to a problem? Please describe.**
sometimes I want to link to a specific area in my drawing.

**Describe the solution you'd like**
I suggest to give a label to a frame, which can be used as a markdown link.

**Comment by zsviczian** [comment]
sounds doable. Great idea. I'll come up with a solution.

**Comment by JJger148** [comment]
> sounds doable. Great idea. I'll come up with a solution.

Hi zsviczian, do you know [muse](https://museapp.com/)?
I think it has amazing features, which could serve as an inspiration for excalidraw. 
I don't want to make to many suggestions, because I don't know what is feasible, but maybe you can use it as an inspiration for more features that help with a visual pkm or "workspace".

**Comment by JJger148** [comment]
> sounds doable. Great idea. I'll come up with a solution.

I nice additional feature, would be if this linked frame would become a visual alias if there is a "!" in front of the link. It would be like a block reference, but only visual. That means wherever it is linked with a "!" I can edit this particular section of an excalidraw file.

**Comment by zsviczian** [comment]
Frame support was implemented in [1.6.0](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.6.0). You can add markdown links to elements.
