### ISSUE TITLE
Low PNG quality on Ubuntu

### ISSUE THREAD

**Issue by ssakhavi** [zsviczian/obsidian-excalidraw-plugin#234]
**Describe the bug**
When exporting to PNG, the image is no longer crisp. 

**To Reproduce**
Export any drawing from Excalidraw in Obsidian. 

**Expected behavior**
Visually appealing image. Currently, my screenshot is better than the exported image. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by ssakhavi** [comment]
Screenshot:
![Screenshot from 2021-11-07 10-59-08](https://user-images.githubusercontent.com/6030203/140630782-e36d9890-5324-4c19-a1a0-0c28e824c2fd.png)


Exported Image
![Drawing 2021-11-06 16 33 31 excalidraw](https://user-images.githubusercontent.com/6030203/140630791-d4936349-494c-49d7-9db6-750e97f07b45.png)

**Comment by zsviczian** [comment]
Did you check the PNG export settings?
![image](https://user-images.githubusercontent.com/14358394/140657750-ccc7a4ed-d281-4350-9115-76893d410372.png)

**Comment by ssakhavi** [comment]
Yes. I've tried with different scales and the quality is still not good.

**Comment by zsviczian** [comment]
Do you experience the same when you export to PNG from https://excalidraw.com ?

**Comment by ssakhavi** [comment]
Strangely, yes. 
I'm assuming it's an Excalidraw problem then?

**Comment by ssakhavi** [comment]
I found this Pull Request and a link to the preview build:
https://github.com/excalidraw/excalidraw/pull/3530

When I exported with 3x it works very well.

**Comment by zsviczian** [comment]
Looks like a minor change. I'll test this. If it works well I may deploy to Obsidian-Excliadraw.

**Comment by zsviczian** [comment]
so I looked at the proposed pull request. Unfortunately it addresses a similar issue but in a different part of the code. I don't have the expertise (yet) to apply the solution to the API function I am using. In case you know what to do, I'd appreciate some help with a PR.

This is the code that would need to be modified:
https://github.com/zsviczian/excalidraw/blob/8a612f1fa969f247987e7fbbb7c4a47a5b1dad09/src/packages/utils.ts#L51-L81

**Comment by zsviczian** [comment]
The PNG quality is not low, the DPI is low. I've now tried several approaches including 
- [excalidraw/excalidraw#3530](https://github.com/excalidraw/excalidraw/pull/3530)
- [sharp](https://www.npmjs.com/package/sharp)
- [changedpi](https://www.npmjs.com/package/changedpi)

I was able to change the dpi of the image, but could not effectively resample with higher DPI to achieve matching width.
canvas.toBlob() sadly only supports 72dpi output.

Thus the image is not low quality, but `img.style.width` needs to be set to a lower value if you want it to look sharp.

Sorry. Can't fix. If someone can offer a working solution, I am happy to implement it.
Entry points to the code:
Obsidian plugin:
https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/16b547202476a252dd7c589078c15c5b1710901c/src/Utils.ts#L230-L246

Excalidraw core:
https://github.com/excalidraw/excalidraw/blob/620b6620858883c1037b09d420efb59cfa78e9ca/src/packages/utils.ts#L51-L81

**Comment by ssakhavi** [comment]
Thank you for the clarification.
I hope someone can help with this.
