### ISSUE TITLE
Big files crash obsidian mobile app all togather while indexing  

### ISSUE THREAD

**Issue by echo-saurav** [zsviczian/obsidian-excalidraw-plugin#235]
I have a excalidraw file (36mb) with 20 image imported. With this file in my vaulf i can't open obsidian app on mobile. I had to delete this file then open obsidian app

**Comment by zsviczian** [comment]
So I’ve also experienced performance issues, but haven’t tried files of this size. I will consult Licat how I can exclude content from indexing. Maybe I will have the cut the file into two: a hidden / non-markdown file with the drawing and the snapshot SVG, and a markdown file with the text contents. I already have the drawing and the snapshot in codeblock encapsulated in a comment block…

**Comment by echo-saurav** [comment]
Okay cool, there is another issue, while i search all files. It also searches excalidraw json, so maybe move all json data to config folder??

**Comment by zsviczian** [comment]
yes, it has to do with the same issue

**Comment by zsviczian** [comment]
Just to let you know, this is my top priority issue right now. I see my approach is causing some unwanted behavior in Obsidian. I am looking for a way around it...

**Comment by zsviczian** [comment]
Are you using Templater?
Can I ask you to try and disable `Trigger Templater on new  file creation`. Doing this has solved the issue in my test setup.

![image](https://user-images.githubusercontent.com/14358394/140780641-50b0aafc-c04d-4406-b510-9a6ad4ec89dd.png)

**Comment by zsviczian** [comment]
can you try switching off all the plugins and test syncing a large file that way?
Are you using Obsidian sync or some other solution?

**Comment by echo-saurav** [comment]
I am using syncthing for syncing
ok, i made another vault for testing with just one excalidraw file but it still crashed

**Comment by zsviczian** [comment]
what mobile device are you using? and which version of the mobile app?

**Comment by echo-saurav** [comment]
Ok maybe i found the problem. Any excalidraw file created with templater plugin turnd on crashes mobile app. I made a new vault and created a excalidraw file (17mb). And now its works fine. Though still take some time to load the file

**Comment by echo-saurav** [comment]
> what mobile device are you using? and which version of the mobile app?

Device: Samsung A20 (3gb Ram)
os: Android 11

**Comment by echo-saurav** [comment]
Ok, so i made another 35mb file and it crashes. 
Is there a limit to how far i can go? or is it device spacific?

**Comment by zsviczian** [comment]
So I tested this and also experience crashing but I could not link the crash to file size. Also when I restarted the app, the file was there. 

You did not state which version of the mobile app you are using.

I will raise this issue with Licat, but I want to isolate the issue a bit better first.

**Comment by echo-saurav** [comment]
App version: Obsidian mobile v1.0.5

Do you recommend keeping the file on the vault?

**Comment by zsviczian** [comment]
you don't need to remove Templater, just turn the trigger on new file creation off. 

I created an issue for this with Templater: https://github.com/SilentVoid13/Templater/issues/439

So the issue is resolved?

**Comment by echo-saurav** [comment]
The issue solved for files under 30 mb

**Comment by zsviczian** [comment]
1.4.8-beta will fix the large file issue (if you enable auto export SVG) this means you will have two files in your vault the excalidraw and the SVG, but the issue with the file size will no longer cause a problem.

Note it is still a beta and you need to manually install it from releases (not from community plugins)

**Comment by echo-saurav** [comment]
> thank you

**Comment by zsviczian** [comment]
I just published 1.4.9 to community plugins. that should solve your problem completely. This update will run a housekeeping process 7 minutes after its first run and will trim SVG snapshot from all the files, making them much-much smaller.
