### ISSUE TITLE
Allow flipping of elements

### ISSUE THREAD

**Issue by slockers37** [zsviczian/obsidian-excalidraw-plugin#238]
Allow flipping of elements horizontally and vertically. It would be amazing to have and would save lots of time.

**Comment by zsviczian** [comment]
Excalidraw supports flipping of individual elements, not groups of elements.
select the element and press SHIFT+V or SHIFT+H to flip. You can also use the right click context menu to select flipping.

**Comment by slockers37** [comment]
> Excalidraw supports flipping of individual elements, not groups of elements. select the element and press SHIFT+V or SHIFT+H to flip. You can also use the right click context menu to select flipping.

I didn't know about that. Thank you.

You can close the issue now then.
