### ISSUE TITLE
add option to add custom markdown formatted text to drawing

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#239]
![image](https://user-images.githubusercontent.com/14358394/140557748-2d75b99b-38f4-4d38-9136-8cb8c6d13990.png)

Here's the [sample SVG file](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/7488061/formatted.text.zip) I am using in the example. You can simply open it with either excalidraw.com or Obsidian-Excalidraw and it will work.

_Originally posted by @zsviczian in https://github.com/zsviczian/obsidian-excalidraw-plugin/discussions/233_

**Comment by HiRolla** [comment]
@zsviczian This is good idea! 
I would use this feature a lot.

**Comment by zsviczian** [comment]
https://stackoverflow.com/questions/12092532/how-to-convert-html-to-valid-xhtml

**Comment by zsviczian** [comment]
https://stackoverflow.com/questions/16254651/auto-height-for-a-foreignobject-in-svg

**Comment by zsviczian** [comment]
delivered with 1.4.13
