### ISSUE TITLE
  Blinding white screen while "Loading scene..."

### ISSUE THREAD

**Issue by HiRolla** [zsviczian/obsidian-excalidraw-plugin#241]
Hello! I use the dark mode mostly. And often I need to switch between my drawings. All of them are in dark mode. But while I'm switching I get white impact. When it is night and the scene is too big to load quickly I want to solve this issue somehow.

**Comment by zsviczian** [comment]
This is easy to solve. Save a template with the dark mode. https://youtu.be/ibdS7ykwpW4

You can also go to Excalidraw settings and turn these settings on:
![image](https://user-images.githubusercontent.com/14358394/141506449-69cbd6f2-d73d-4e47-bdbc-f6e3487238f8.png)

**Comment by HiRolla** [comment]
@zsviczian Thank you! I did the second one, and now my dark mode is TOTAL as I needed

**Comment by zsviczian** [comment]
I fixed this in 1.7.10, you no longer need a css snippet. I will release it in a few days.
