### ISSUE TITLE
Cannot create new linked page from text with shortcut

### ISSUE THREAD

**Issue by mhep** [zsviczian/obsidian-excalidraw-plugin#243]
When I click (CMD + ALT + CLICK) a text box with the content `text`, which is not yet linked to a file, I get the following error:

`No ImageElement is selected or TextElement is empty, or [[valid-
link alias]] or [alias] (valid-link) is not found`

Only when I manual add `[[` and `]]`, so that the text box reads `[[text]]`, am I able to create a new file by the name `text` when using the keyboard shortcut CMD + ALT + CLICK.

**Comment by zsviczian** [comment]
as far as I can see this is not a bug, but a feature.
Some of the older videos may still refer to just using text as link, but since you need proper wiki links for linking.
