### ISSUE TITLE
create new drawing with key+clicking   

### ISSUE THREAD

**Issue by JJger148** [zsviczian/obsidian-excalidraw-plugin#248]
**Is your feature request related to a problem? Please describe.**
When I create a new [[Link]] I often want to open it as a new drawing. 
 

**Describe the solution you'd like**
I would like to see a hotkey that would create a new drawing with the [[LINKE TITLE]] as soon as I press the key and click the link.

**Comment by zsviczian** [comment]
Not sure I fully understand. Does the command palette action "Create new Drawing and embed into the active document" not do the job for you?
![image](https://user-images.githubusercontent.com/14358394/142767197-044b2ff3-4d4d-46ab-ae7f-ab2b28ad6ccb.png)

**Comment by JJger148** [comment]
I don't have that command available for some reason. 
Do I have to change something in my Settings? 

<img width="577" alt="Bildschirmfoto 2021-11-21 um 20 57 52" src="https://user-images.githubusercontent.com/68868949/142776969-1fccfbee-000e-492a-82ac-fcac93a8ca3d.png">

**Comment by zsviczian** [comment]
Which version of the plugin are you using?
You should have a markdown document open/active when opening the command palette. Some of the actions only show in the relevant context.

**Comment by JJger148** [comment]
That makes sense, now it worked when I had the markdown file open. 
However will this feature also become available for use without the markdown file open, but simply in the drawing?

**Comment by zsviczian** [comment]
I recognize I never got back to you on this. 
Since a few versions ago, if you create a new link in the drawing e.g. [[my new drawing]], and click the link if the file does not exist, you will be prompted if you want to create a drawing or a markdown file. I hope this completely solves this issue for you.
