### ISSUE TITLE
request: open drawing in new pane

### ISSUE THREAD

**Issue by firinael** [zsviczian/obsidian-excalidraw-plugin#25]
Hi, currently the "Open an existing drawing or create a new one" command can only open a drawing in the current pane (will create a new pane if none are active).

This is an issue because if you want to create a drawing, you have to open another panel first and then open the drawing.

I'd simply like to be able to open/create a drawing in a new pane, instead of the one I'm currently editing.

**Comment by zsviczian** [comment]
sure, no problem. Will add this as well.

**Comment by GitMurf** [comment]
+1 on this. I was just going to post a request for the same feature :) Also would be nice if it creates in a new pane when clicking the button/icon on the left. 

![image](https://user-images.githubusercontent.com/64155612/116288007-e61a5700-a745-11eb-8cbd-a96f63c3881a.png)

**Comment by zsviczian** [comment]
Please test this release, I hope to have resolved your request:
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.6-test

**Comment by zsviczian** [comment]
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.6
