### ISSUE TITLE
Windows 10: Export to PDF - note with transcluded Excalidraw crashes Obsidian

### ISSUE THREAD

**Issue by veefwoar** [zsviczian/obsidian-excalidraw-plugin#252]
**Describe the bug**
When exporting a note with a transcluded Excalidraw diagram to PDF, Obsidian crashes and has to be killed with Task Manager

**To Reproduce**
1. Produce diagram in Excalidraw. No images. Rectangles and formal text with arrows only
2. Transclude ![[Drawing.excalidraw]] into note
3. Open command palette type 'Export to PDF'
4. Accept all defaults, click 'Export to PDF'
5. Nominate output file name hit enter
6. Open Task Manager, expand Obsidian group
7. One thread shows up to 16% utilisation
8. 'crashpad_handler' thread has been started but running at 0%
9. Eventually Obsidian screen will go dark and utilisation will drop to 0% but no recovery

**Expected behavior**
When excalidraw diagram is transcluded as a PNG, the PDF will open within about 5-10 seconds.

**Screenshots**
![image](https://user-images.githubusercontent.com/25582780/141943166-c2ed2566-3a72-47df-bf16-ca4ea01147e8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19043 Build 19043
 - Browser: Chrome Version 95.0.4638.69 (Official Build) (64-bit), Edge Version 95.0.1020.53 (Official build) (64-bit)

**Additional context**
 - Print spool service is running

**Comment by zsviczian** [comment]
I can reproduce. I will check this. This worked previously, but haven't tested it since the introduction of the image element.

**Comment by zsviczian** [comment]
Found the error. Working on a solution.

**Comment by veefwoar** [comment]
Nice work all round my friend!

**Comment by zsviczian** [comment]
solved in 1.4.10. 
You'll need to wait 10 minutes after installing 1.4.10 - as sadly I need to patch all files again.
The root cause was the way I solved Obsidian 0.13.2 WYSIWYG Live Preview. I created an infinite loop of file references. solved.

**Comment by veefwoar** [comment]
Nice work mate. I'm clicking that buy me a coffee button

**Comment by zsviczian** [comment]
Thanks!
