### ISSUE TITLE
automatically rearrange text 

### ISSUE THREAD

**Issue by JJger148** [zsviczian/obsidian-excalidraw-plugin#253]
**Describe the solution you'd like**
Drag and Drop text blocks. The other text should rearrange accordingly. 
An example can be seen here at the museapp update 
https://museapp.com/email-updates/018/

**Comment by zsviczian** [comment]
I agree this would be very nice. I don't see this being implemented - sorry.
You may try to raise this feature request with the core Excalidraw product team, but I doubt they will pick this up. https://github.com/excalidraw/excalidraw/issues
