### ISSUE TITLE
export PDF hangs obsidian

### ISSUE THREAD

**Issue by insanum** [zsviczian/obsidian-excalidraw-plugin#255]
I've noticed when exporting to PDF a file that contains an excalidraw element, Obsidian will hang. If I remove the excalidraw element then exporting works as expected.

Anyone else experience this? I'm on macOS.

**Comment by Alekssavin** [comment]
A week ago I was able to successfully generate a PDF with excalidraw embedded in the markdown file… Now if I create files with excalidraw embedded, pdf export fails. The old excalidraw drawings that have been embedded long ago however do not cause obsidian to freeze.

May be some recent updates messed this up?

**Comment by zsviczian** [comment]
Which Excalidraw version are you using? I resolved this issue with 1.4.10 two days ago.
I just tried PDF export and it worked without any issues.
see #252 

If you are still experiencing PDF export issues with 1.4.10, please provide more specifics so I can replicate the problem.

**Comment by zsviczian** [comment]
Note that you will need to wait 7-8 minutes after installing 1.4.10 for it to patch Excalidraw files. Once you installed 1.4.10, you can also manually correct existing drawings (if for some reason the patching would not execute) by removing the circular reference from the Excalidraw.md files at the top of the file, right under the front matter

![image](https://user-images.githubusercontent.com/14358394/142393140-97602645-d5f3-4b3d-a7f0-6f05540d6fd1.png)

**Comment by insanum** [comment]
Ah yes. Export is working with 1.4.10. I was on 1.4.9.
Thank you. :-)
