### ISSUE TITLE
open dropdown when linking to a file with "[["

### ISSUE THREAD

**Issue by JJger148** [zsviczian/obsidian-excalidraw-plugin#256]
**Describe the solution you'd like**
I would like to see the dropdown window, when I want to link to a file.

**Comment by zsviczian** [comment]
Unfortunately, that is not so simple to implement. I have two workarounds for you:
- You can use the command palette action "insert link to file" (CTRL+SHIFT+K)
- You can open excalidraw and excalidraw markdown side-by-side, and edit the text elements in markdown

https://user-images.githubusercontent.com/14358394/142463036-dd4abf02-106f-4d70-bfa7-f7fe11fc4664.mp4
