### ISSUE TITLE
Filename substring trigger to shut down the color inversion

### ISSUE THREAD

**Issue by HiRolla** [zsviczian/obsidian-excalidraw-plugin#259]
@zsviczian I'm going to build a powerful clip image gallery for my drawing process. So, maybe it is also possible to make some filename substring trigger to shut down color inversion. I would be happy to have this feature too. 
E.g 
Excalidraw/gallery/[no_invert]/prettyWoman.png
Excalidraw/gallery/[no_invert]/islandMap.svg

>This is a good idea. I am planning to work on the SVG inversion this weekend.

_Originally posted by @zsviczian in https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/258#issuecomment-974233029_

**Comment by zsviczian** [comment]
SVG inversion is not so simple as it seems. I have a partial solution. I don't think I'll have a full solution any time soon. I simply don't have the time to experiment with this.

**Comment by zsviczian** [comment]
Inversion sort of works for me (except for the iPad where Safari does not support the required CSS). I am closing this for now.
