### ISSUE TITLE
request: add "remove UI clutter" to options

### ISSUE THREAD

**Issue by firinael** [zsviczian/obsidian-excalidraw-plugin#26]
Hi, people might want to remove the GitHub and the encryption icon, so it'd be nice to have that as an option.

This can be done using the following CSS:

```
.excalidraw .github-corner, .excalidraw .layer-ui__wrapper .encrypted-icon {
	display: none !important;
}
```

**Comment by zsviczian** [comment]
In the next version, it is already removed.  I will publish in hopefully 1-2 days... just need to do some testing on other features.

I've added this to the CSS:
```
.excalidraw .github-corner {
  display: none;
}
```
