### ISSUE TITLE
Some bugs and features for better mobile support

### ISSUE THREAD

**Issue by echo-saurav** [zsviczian/obsidian-excalidraw-plugin#262]
Excalidraw works really great on pc but on mobile i think we need some improvements
**Two feature i think would be realy useful**
- Specify initial open mode in settings. like on mobile i dont usealy draw but just open them to look at it. Maybe it would be better if the initial opening mode is on `Zen mode` and `View Mode`
- As mobile has less space , there could be a button to revel all the other buttons

**some bugs i faced**
- Text get cut off by the end like "obsidian" into "obsidia"
- zoom dont work at `View mode`
- Pen tool make a mess while zooming
- After zooming my selected tools get unselected. Like if i select Rectangle and then zoom and then try to  draw rectangle i need to select that again

**Comment by zsviczian** [comment]
Thanks!
I can address some of these, but sadly not all. Text cut off for example depends on the mobile device. From the phones and tablets, I have available the issue only occurs on my Galaxy Note 8. See discussion here. I never found a solution. https://github.com/excalidraw/excalidraw/discussions/3829

Can you test if the bugs you've found are also present on excalidraw.com? If yes, then it is better to open an issue directly there: https://github.com/excalidraw/excalidraw/issues

I will add the default zen and view mode options to settings.

**Comment by zsviczian** [comment]
I added default mode to 1.4.11. Will be released a bit later today. The feature also includes a new front-matter key:
```
excalidraw-deafult-mode: normal
excalidraw-deafult-mode: view
excalidraw-deafult-mode: zen
```

**Comment by echo-saurav** [comment]
> I added default mode to 1.4.11. Will be released a bit later today. The feature also includes a new front-matter key:
> 
> ```
> excalidraw-deafult-mode: normal
> excalidraw-deafult-mode: view
> excalidraw-deafult-mode: zen
> ```

Hy thanks for the front-matter!

**Comment by echo-saurav** [comment]
> Can you test if the bugs you've found are also present on excalidraw.com? If yes, then it is better to open an issue directly there: https://github.com/excalidraw/excalidraw/issues
Will do that
