### ISSUE TITLE
(Bug) There's resizing sidebar line when trying to export Excalidraw scene

### ISSUE THREAD

**Issue by jokysatria** [zsviczian/obsidian-excalidraw-plugin#27]
Sorry, my English is bad, hope this video describing the bug well.

https://user-images.githubusercontent.com/69371378/116155367-324ca380-a714-11eb-878c-e914f0d9324f.mp4

And thank you so much for the plugin 🙏.

**Comment by zsviczian** [comment]
Thanks for raising. I am aware of the issue, but haven't yet found a solution. I considered this as a low priority problem, as overall it does not impact application functionality.

I will keep this open, and may get back to this later.

**Comment by jokysatria** [comment]
I think this issue can be closed (?) Since you implemented this.

![image](https://user-images.githubusercontent.com/69371378/116640673-54088d80-a995-11eb-9423-442d697bf345.png)

Thank you!

Out of curiosity (off topic) : there is a save button, is that mean we need to save manually at the end of drawing? is my drawing still there if I close it without saving it?

**Comment by zsviczian** [comment]
There is auto saving. Auto saving will be much improved in the next version 1.0.8. And I will probably remove this button.
