### ISSUE TITLE
Provide more than 100% "Zoom to selection" feature zoom level 

### ISSUE THREAD

**Issue by HiRolla** [zsviczian/obsidian-excalidraw-plugin#272]
Hello! 
Now I can't dive to the selection deeper than 100% using Shift+2 hotkey or the context menu. Almost every time I have to zoom and scroll manually, that's slows down a drawing process.

It would be great to have an option to set up the max zoom level for "Zoom to selection" feature. Maybe it can be something like we already have in the "Zoom to fit max ZOOM level".  Or maybe it can be a single option for both cases.

Thank you!

**Comment by zsviczian** [comment]
I just realized you can solve this issue with a simple Excalidarw Script Engine script.
You can find the script here: [ea-scripts/Zoom to Fit Selected Elements.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Zoom%20to%20Fit%20Selected%20Elements.md)
More about the script engine here: https://youtu.be/hePJcObHIso

**Comment by HiRolla** [comment]
@zsviczian, Thank you! 
Is there any api command to refresh view during the script run?
I want to check if there can be a smooth zooming
