### ISSUE TITLE
[BUG] Auto crop of .svg files

### ISSUE THREAD

**Issue by Mylloon** [zsviczian/obsidian-excalidraw-plugin#273]
**Describe the bug**
When auto-export to SVG file is activated, the result is cut at the top and bottom of the image.

**To Reproduce**
1. Make a new excalidraw (I am using the .md)
2. Let the extension export it automatically

**Expected behavior**
The exported image is identical to the excalidraw view

**Screenshots**
excalidraw view             |  svg view
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/29067904/143142957-85203354-6d46-43a4-9e61-3fe722ec328d.png" alt="excalidraw view" width="400"/>  |  <img src="https://user-images.githubusercontent.com/29067904/143143014-f3119350-7c7a-43d7-b440-c6c08d56ebe2.png" alt="svg view" width="400"/>

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Excalidraw Plugin Version 1.4.12 and Obsidian 0.12.19

**Comment by zsviczian** [comment]
I'll add a setting to provide more control over cropping.

**Comment by zsviczian** [comment]
This is really embarrassing... but I completely forgot about this request.
I am releasing this feature in 1.5.29 tonight.
