### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#274]
![image](https://user-images.githubusercontent.com/29135984/143253580-9d0405d1-38a3-463f-9089-ff8761816dad.png)
![image](https://user-images.githubusercontent.com/29135984/143253796-cf33597b-ee2d-40a0-aece-8f0c7169a691.png)
![image](https://user-images.githubusercontent.com/29135984/143255090-7eaff7e7-712e-4571-95e0-eb716e957824.png)

1. The notes are placed in .md files, not .svg images
2.  The Excalidraw.md file is not in the set 103-Excalidraw folder, but in the Attachment folder along with the .svg

**Comment by zsviczian** [comment]
The Excalidraw folder is only used when you use the ribbon button or these two actions from the command palette:
![image](https://user-images.githubusercontent.com/14358394/143310499-57cd734f-f4a3-4bdb-9918-5a2fbf54fb71.png)

When you use these other two actions, then files are created in the attachments folder following your Obsidian settings.
![image](https://user-images.githubusercontent.com/14358394/143310559-9748f124-21b1-4319-be8c-626d05696e3b.png)

You need some other settings as well to auto-embed an SVG. See this video. There are two issues though:
1) Markdown preview does not refresh when the SVG is saved. You need to navigate away and back for the SVG to show up.
2) When you rename the drawing the SVG is renamed (if you have the keep in sync option enabled), but Obsidian does not update the SVG link. I will check what I can do with this issue.
https://user-images.githubusercontent.com/14358394/143310110-a254d72c-1573-4411-8ff7-4945afb18ce2.mp4

**Comment by zhl111** [comment]
Thank you very much, after many tests I don't put in .svg images anymore because it adds a lot of extra steps and has subsequent problems.

**Comment by zsviczian** [comment]
opened #282 to address renaming of SVG files
