### ISSUE TITLE
Data loss

### ISSUE THREAD

**Issue by JJger148** [zsviczian/obsidian-excalidraw-plugin#276]
**Describe the bug**
Describe the bug
When I close a new drawing, the data is lost most of the time.
It only happens with new files I create.
I have this issue maybe since a week.
I already have the most recent update and still it happens.

**To Reproduce**
1. Open new drawing 
2. Draw 
3. Close drawing 
4. Reopen

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by zsviczian** [comment]
hm. I am sorry to hear that. I can't reproduce the error.
How do you create the drawing? Can you maybe share a screen capture of the process?

**Comment by JJger148** [comment]
I reinstalled the plugin, and now everything is okay

**Comment by zsviczian** [comment]
Great to hear!
