### ISSUE TITLE
The font does not change colour?

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#277]
![image](https://user-images.githubusercontent.com/29135984/143725989-6370adca-026b-4ee0-81d4-6cdb7fa0ddd4.png)
![image](https://user-images.githubusercontent.com/29135984/143725998-57185b83-ce39-4a04-9e51-c22ecd3d68fb.png)
0. Theme is default
1. I closed all the plugins and kept only Excalidraw
2. I have set the default colour to skyblue
3. But the colour has not changed
![image](https://user-images.githubusercontent.com/29135984/143726012-8dd1ecc9-10f8-4e90-b2fd-2ec52a52bd47.png)
4. adding the following frontmatter-key is ok

**Comment by zsviczian** [comment]
I can’t reproduce the issue. Could you send me a screenshot of your settings page as well?

**Comment by zhl111** [comment]
Normal after updating 1.4.14。thanks
