### ISSUE TITLE
[BUG]Cannot Drag And Drop MD Files

### ISSUE THREAD

**Issue by Quorafind** [zsviczian/obsidian-excalidraw-plugin#283]
**Describe the bug**
Just DND but nothing showed.

**To Reproduce**
1. Drag the md file
2. Drop on Excalidraw Whiteboard
3. Nothing Showed
4. See error: Uncaught (in promise) TypeError: Cannot read property 'parentElement' of null

**Expected behavior**
DND and show something

**Screenshots**
Nothing showed

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 0.14.14

**Comment by zsviczian** [comment]
Does this happen with all your markdown embeds or a particular file?

**Comment by Quorafind** [comment]
@zsviczian it is weird that I could dnd in a new vault, so some plugins cause this error.

**Comment by zsviczian** [comment]
Did you manage to figure out which plugin may have caused this error?
