### ISSUE TITLE
Excalidraw embeds in editor mode not working with new update

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#284]
https://github.com/excalidraw/excalidraw/issues/4337

I have downloaded the latest version which includes embedded pages in excalidraw but my excalidraw drawings are no longer rendering when transcluded in edit mode on a md page using Ozan's Image plugin

**Comment by zsviczian** [comment]
This is possible. I've tested all features with 0.13.6. I am also not sure I will spend much effort trying to make the old version work, I hope WYSIWYG will get released soon enough.

**Comment by dwelle** [comment]
There may be a transpilation issue. I'll be making a fix (moving from es2015 to es2017 target) tomorrow. May also be completely unrelated. Lemme know your findings.

**Comment by zsviczian** [comment]
@dwelle It was completely unrelated, an issue in my plugin. I refactored the code and left a variable uninitialized in the process.
@thomascurro Fixed in 1.4.15
