### ISSUE TITLE
First LaTeX formula per pane not being added to drawing, and LaTeX not editable anymore

### ISSUE THREAD

**Issue by yuvve** [zsviczian/obsidian-excalidraw-plugin#287]
**Describe the bug**
LaTeX insertion not working properly in 2 ways (since some patches ago):
1. Every time you open a new Excalidraw pane your first latex insertion does not produce any result (but an image is still created).
2. LaTeX is not editable like it used to be (ctrl+click opens an image instead of formula editor).

**To Reproduce**
(Reproduceable even in a clean vault without any other plugins)
1. Create or a open an Excalidraw pane.
2. Insert a LaTeX formula with the command palette or with a hotkey.
3. An image of your formula will be created, but nothing will be embedded into the Excalidraw drawing. 
4. Do stage 2 again.
5. This time the formula will appear inside the drawing.
6. Ctrl+click the formula.
7. An image will open (instead of the editing popup).

**Expected behavior**
The formula should be added to the drawing every time. LaTeX formulas should be editable like they used to be before.

**Screenshots**
![FudxHfAlMN](https://user-images.githubusercontent.com/37124628/144089342-178736bc-d72c-4160-b7bc-628a5e3ceea9.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by zsviczian** [comment]
Thanks for raising. Hope to fix it tonight.

**Comment by zsviczian** [comment]
Thanks for raising This! 
Very embarrassing 😊... this is what happens when I create a feature that I do not use on a daily basis... I don't notice when I break it. It was a silly little mistake in the code. I fixed it in 1.4.16. Already in community plugins.

**Comment by yuvve** [comment]
No problem, thanks for making this!
