### ISSUE TITLE
Export PNGs at a higher resolution

### ISSUE THREAD

**Issue by nickmilo** [zsviczian/obsidian-excalidraw-plugin#289]
**Is your feature request related to a problem? Please describe.**

When I export as a PNG from Obsidian, the image quality is low. 

When I load the same excalidraw file into the online version and export as a PNG, I am able to choose `3x` and that gives me the ideal sharpness upon export.

Any way we could be able have the ability to export `3x` within this awesome Obsidian plugin?

**Comment by zsviczian** [comment]
Did you try the setting for this?
![image](https://user-images.githubusercontent.com/14358394/144316055-aa6e8967-8960-4e9d-9206-63b329f9a464.png)

**Comment by nickmilo** [comment]
Ahh, no I didn't, and that solves my issue. Sorry for the bother.
