### ISSUE TITLE
mouse malfunction after hand drawing

### ISSUE THREAD

**Issue by bagameow** [zsviczian/obsidian-excalidraw-plugin#29]
**Describe the bug**
When using iPad, the mouse left click (draw) will not work again after you use finger to draw.

**To Reproduce**
- open excalidraw in iPad
- draw something with mouse 
- use your finger to draw
- witness the malfunction

**Expected behavior**
mouse click should work again.

**Comment by zsviczian** [comment]
Thanks! There is a known issue working with the Obsidian mobile apps. I've discussed with Obsidian developers and I understand it should be solved in one of the next releases. I will park this issue until the new Obsidian iOS version is out, as I hope the next version will solve this without me having to change code.

**Comment by zsviczian** [comment]
I think this has been solved sometimes along the way.
