### ISSUE TITLE
Unable to insert the markdown note in excalidraw

### ISSUE THREAD

**Issue by KALKI-the-avataar** [zsviczian/obsidian-excalidraw-plugin#291]
I have tried both ways of inserting the markdown files to excalidraw and both have failed.

This how console looks like for 1 of the file.

![unknown](https://user-images.githubusercontent.com/80031164/144702507-de4b50f5-4dc9-4c04-9a51-9fa96a62911a.png)

This error occurs for almost all files(as I remember 3 days before I ways able to insert 1 file but not rest I know don't remember which file was that and I have tried with more than 30 files but it does not work.

I am on windows 10
obsidian version 0.12.19 and same for the installer version

excalidraw version 1.4.17

I don't know but may you have release update for the insider's built and that may be causing problem in this one

**Comment by KALKI-the-avataar** [comment]
---
Status: [<% tp.file.cursor(1) %>]
Supermemeorised: []
---

A Determinant is a Square Matrix Which has a Defined way of solving it.
It is a sort of a representation which makes calculations easier

It has applications in many fields like **Solving system of equations** ,(when I think I only know it's this use only currently)
as Use coordinate geometry is nothing but really solving a system of equations.

A Determinant may be represented as $\Delta$.


Below I represent a general Determinant:

![[General representation of a Determinant.png]]

**Comment by KALKI-the-avataar** [comment]
above is 1 of the markdown file for example

**Comment by zsviczian** [comment]
could you make a screenshot with the error expanded?
![image](https://user-images.githubusercontent.com/14358394/144703958-08dc3ffc-cf67-4df2-ac7f-2b9f2d700510.png)

Also, do you have a plugin that might be abbreviated BCPlugin?

When you look at the source markdown page in Obsidian preview mode, does it show correctly?

**Comment by KALKI-the-avataar** [comment]
Yes BC plugin is Bread crumbs

**Comment by zsviczian** [comment]
can you try turning Bread crumbs off and test if you can insert markdown into Excalidraw?

**Comment by KALKI-the-avataar** [comment]
After closing bread crumbs it was showing this error
![image](https://user-images.githubusercontent.com/80031164/144709159-02f67e61-a6ed-41e1-be88-5345e2d2b9ea.png)

As this error has banner plugin its  name so I closed it and it worked.

**Comment by zsviczian** [comment]
can you raise the issue with the dev for the BannersPlugin?
