### ISSUE TITLE
After inserting image or latex equation it treats the excalidraw native elements also as image when trying to insert in library

### ISSUE THREAD

**Issue by KALKI-the-avataar** [zsviczian/obsidian-excalidraw-plugin#292]

**Comment by KALKI-the-avataar** [comment]
![NErG1N6D9T](https://user-images.githubusercontent.com/80031164/144702841-9069f48f-bd65-4df8-853d-9ca90a98e59c.gif)

**Comment by zsviczian** [comment]
I was able to reproduce. This is an error in the core Excalidraw package. I will investigate.
In the meantime, you can add elements to the library by opening the library and adding items from there

https://user-images.githubusercontent.com/14358394/144704683-29d9bc55-7bcf-48df-887c-6affc83e7948.mp4

**Comment by zsviczian** [comment]
Fixed it [#4356](https://github.com/excalidraw/excalidraw/pull/4356). Will deploy fix today.
