### ISSUE TITLE
'Failed to load plugin obsidian-excalidraw-plugin'

### ISSUE THREAD

**Issue by EmSixTeen** [zsviczian/obsidian-excalidraw-plugin#295]
**Describe the bug**
When I try to enable the plugin, I receive the following error:

>  'Failed to load plugin obsidian-excalidraw-plugin'

**To Reproduce**
1. Go to 'Community plugins'
2. Click on the toggle to enable, or alternatively click 'Enable' in plugin settings
3. Receive the error 'Failed to load plugin obsidian-excalidraw-plugin'

**Expected behavior**
Plugin enables as expected.

**Desktop (please complete the following information):**
- OS: Windows 10 Enterprise N (Version 1909)
- Obsidian version: v0.12.19
- Plugin version: 1.4.19
- Folder location: iCloudDrive\iCloud~md~obsidian\Obsidian Notes\.obsidian\plugins

**Smartphone (please complete the following information):**

**Additional context**
Installed plugins:
- cm-editor-syntax-highlight-obsidian
- code-block-copy
- obsidian-checklist-plugin
- obsidian-collapse-all-plugin
- obsidian-excalidraw-plugin
- obsidian-icons-plugin
- obsidian-toggl-integration
- tq-obsidian
- url-into-selection

**Comment by zsviczian** [comment]
can you start Obsidian Developer Console (CTRL+SHIFT+i) and execute the following command? What result do you get?
`process.versions.electron`
![image](https://user-images.githubusercontent.com/14358394/145255102-b6da8c8d-b7da-420c-ba1f-16a7881d185e.png)

**Comment by EmSixTeen** [comment]
Have just installed the latest update today, plugin version 1.5.2, and all has enabled as it should.

**Comment by onlyjokers** [comment]
> can you start Obsidian Developer Console (CTRL+SHIFT+i) and execute the following command? What result do you get? `process.versions.electron` ![image](https://user-images.githubusercontent.com/14358394/145255102-b6da8c8d-b7da-420c-ba1f-16a7881d185e.png)

The version of my console output is 12.0.14, but the plugin still fails to load
My computer is the m1 version of the MacBook

**Comment by cryptocj** [comment]
hello, i have a same problem, and my version is
`"13.6.2"`

**Comment by cryptocj** [comment]
ok, finally know the problem, need to download `main.js` and put it into this plugin directory.

**Comment by printempts** [comment]
> ok, finally know the problem, need to download `main.js` and put it into this plugin directory.

Hi, where can I find the main.js

**Comment by cuicuicuicuixi** [comment]
> ok, finally know the problem, need to download `main.js` and put it into this plugin directory.

hello, could you tell me where is this `main.js` file to download, i search it in this repo but i can't find it.

**Comment by cuicuicuicuixi** [comment]
> ok, finally know the problem, need to download `main.js` and put it into this plugin directory.
thanks, i find it in release page

**Comment by MrChloride** [comment]
Hello I also has the same problem, my electron version is 25.8.1 but it is on my tablet
