### ISSUE TITLE
copy+pasted LaTeX formulas both change when one is edited

### ISSUE THREAD

**Issue by SteffenMuehle** [zsviczian/obsidian-excalidraw-plugin#297]
# Bug
Two copy+pasted LaTeX formulas both are modified when only one of them is edited.

# Reproduce
1. Make new drawing
2. Add LaTeX formula via command palette
3. Select the rendered formula inside your drawing
4. ctrl+c, ctrl+v: copy paste it
5. ctrl+click one of the two formulas to edit it
6. upon hitting ENTER, now both versions have been changed.

# Expected Behaviour
Is this simultaneous editing intended behaviour, or a bug?
For me as a user it is often common to copy+paste an existing formula and then edit the new copy, rather than always start typing from scratch.
I would thus expect the _original copy_ to remain unchanged when the _copied copy_ is altered and vice versa.

# System
Windows 10
Obsidian v0.12.19
Excalidraw 1.4.19

# Related question
On Android's (v11) Obsidian, is there a way to edit inserted formulas as well? On Windows, I can just crtl+click, not sure how to do it on Android.

**Comment by zsviczian** [comment]
Thanks. I fixed this. I will deploy the fix in a few minutes as part of 1.5.0.
Use the link button at the top to edit the LaTeX formula on a mobile: 
![image](https://user-images.githubusercontent.com/14358394/145683293-e3a585d3-b52d-43ec-a0d6-e58e633f72af.png)

**Comment by SteffenMuehle** [comment]
Thanks for your work!
