### ISSUE TITLE
lost focus on Esc when entered text, so formatting hotkeys don't work

### ISSUE THREAD

**Issue by HiRolla** [zsviczian/obsidian-excalidraw-plugin#299]
Hello.
I used to choose text color by the S hotkey after I press Esc when finish typing. But maybe 5 updates ago this stopped working. 
I checked that on excalidraw.com, it works there.

Also I would like to know: how can I add additional hotkeys for Text align or font family?

Also I failed trying to replace standart hand-drawn font by another which fits better for my purposes. Maybe you know how I shoud do this?

**Comment by zsviczian** [comment]
I will investigate the text color hotkey. As of now, I have no clue why it does not work.

Hotkeys depend on the core product, but, using the new Script Engine, you can easily create a script to change font family or alignment.

Setting different default fonts needs to be developed as an Excalidraw core feature, I don't have a solution for you. The best alternative I can offer is using markdown embeds as explained in this video: https://youtu.be/K6qZkTz8GHs

**Comment by zsviczian** [comment]
I know this is not the solution you were looking for, but a solution. You can add the following scripts to Excalidraw and assign hotkeys. This will allow you to set text alignment and font family via keyboard shortcuts.

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Text%20Align.md
and
https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Font%20Family.md

See this video about using these scripts: https://www.youtube.com/watch?v=hePJcObHIso

**Comment by zsviczian** [comment]
Escape fixed in 1.5.2.

The request for additional hotkeys needs to be raised with the [core Excalidraw product](https://github.com/excalidraw/excalidraw/issues), and/or the Script Engine, as demonstrated above, may prove to be a sufficient workaround.
