### ISSUE TITLE
Button in the left menu doesn't open a drawing

### ISSUE THREAD

**Issue by kzdanowicz** [zsviczian/obsidian-excalidraw-plugin#3]
Issue: the button in the left menu opens a list of drawings but does nothing when I choose any of them. It works once, when I restart Obsidian, after I open any other note or file it stops working. No matter if other notes are opened or all closed.
Opening drawings from the command palette works, only via button not. Obsidian v.0.11.13, MacOS

**Comment by zsviczian** [comment]
very strange. I will try to reproduce the error on a different machine. BTW it works for me.

**Comment by zsviczian** [comment]
Can you test if the button in release 1.0.6 now works properly?
