### ISSUE TITLE
[Request] Also add option to insert excalidraw as png/svg instead of transclude

### ISSUE THREAD

**Issue by TobiasKlosek** [zsviczian/obsidian-excalidraw-plugin#30]
Hello,
first of all thanks for this amazing plugin.

Im using Anki Flashcards and would also like to use my drawings as content for that. Since Anki don’t understand excalidraw, it would be nice to embed via CNTRL+P directly the generated pictures.

i would use it like this:

this is my frontcard #flashcard
![[picture_generated_from_excalidrawing.png/svg]]

**Comment by zsviczian** [comment]
I have something similar in mind. Simply to generate the SVG / PNG parallel to the .excalidraw file. This will ensure the PNG/SVG stays in sync with the .excalidraw file.

This will be available in the next release. See Issue: #24
