### ISSUE TITLE
Laggy drawing performance compared to excalidraw.com 

### ISSUE THREAD

**Issue by bwv656** [zsviczian/obsidian-excalidraw-plugin#303]
**Description**
First of all, what a great plug-in. It's incredible to have this plug-in inside Obsidian! And this is not a bug, but I just noticed that the drawing performance on Obsidian-Excalidraw feels much laggier than excalidraw.com. In excalidraw.com I can comfortably do handwriting but not in Obsidian version. 

It seems like the line stabilizing/smoothing setting is much stronger in Obsidian-Excalidraw. And also, it has velocity based thickness variation. If these things are slowing down the performance, would you please give us the option to toggle this off?

Thank you so much!

OS: macOS 12.1
Obsidian version: 0.13.12
Obsidian-Excalidraw Version: 1.5.3

**Comment by zsviczian** [comment]
I'll take a look, however, with regards to stabilizing / smoothing I am simply using the Excalidraw package out of the box. I am not doing anything additional.

Obsidian has many background processes that could impact performance, this might be exacerbated if you have many plugins enabled. Some plugins, if not optimized properly, may impact drawing performance.

To understand the impact of plugins, can I ask you to do a test?
- turn off all plugins, except for Excalidraw
- restart Obsidian
- test to see if performance has improved or not

Thanks!

**Comment by bwv656** [comment]
Thanks for the reply. 
I've been using the plug-in all day today, and I truly love how you integrated everything. 

I just turned off all the plug-ins (I don't have many), and the interactivity feels the same. However, I am very much used to it now. 

Drawing and sketching from Metal accelerated apps like Pixelmator Pro made the initial impression very laggy, but this plug-in is not for marking sketches, and I think I can live with it. So I guess I shouldn't ask you to spend your time on it. If you happen to find something, that's great, but otherwise, please mark it resolved.

Once again, thank you so much for sharing the plug-in!!!

**Comment by zsviczian** [comment]
I am constantly on the lookout to improve performance, I will keep an eye on this.

**Comment by bwv656** [comment]
I know this is closed, but I just wanted to leave a note.
I recently upgraded from the 2015 MacBook Pro to the latest 2021 MacBook Pro with M1 Max, and the drawing performance is phenomenal. I don't see any lag that I was experiencing with the 2015 Mac. So indeed, it was my hardware issue, not Excalidraw's problem.

**Comment by zsviczian** [comment]
Awesome! I am very happy for you!

**Comment by rsmyst** [comment]
Hijacking thread to say the issue exists too hard on my system.
onenote works flawlessly but i like obsidian too much. while excalidraw works flawlessly for the first few minutes while i write a few sentences, it instantly worsens continually after that to the point where i can't write. 
I don't think my machine is weak enough to not be able to handle excalidraw either since my laptop is from around 2017-18.

Good luck on the performance improvements! looking forward to it

**Comment by PAHXO** [comment]
> Hijacking thread to say the issue exists too hard on my system. onenote works flawlessly but i like obsidian too much. while excalidraw works flawlessly for the first few minutes while i write a few sentences, it instantly worsens continually after that to the point where i can't write. I don't think my machine is weak enough to not be able to handle excalidraw either since my laptop is from around 2017-18.
> 
> Good luck on the performance improvements! looking forward to it


The same issue here, running an I7-7700K, and while looking at obsidian on the task manager CPU usage did not cross 30% with all plugins enabled.

Tho, issue was resolved after disabling all the other plugins.
