### ISSUE TITLE
Can't add excalidraw to a note

### ISSUE THREAD

**Issue by fredches** [zsviczian/obsidian-excalidraw-plugin#305]
**Describe the bug**
I can create a drawing in obsidian, but when I want to embed it in a note, it doesn't work. I created a drawing in a note, and it was fine, but when I created a second one, 

**To Reproduce**

**Expected behavior**
the drawing being displayed in view mode

**Screenshots**
![Capture d’écran 2021-12-19 à 12 38 16](https://user-images.githubusercontent.com/96376029/146673976-2b7ee781-57c7-4d4c-bdef-d0be8836aadf.png)
![Capture d’écran 2021-12-19 à 12 51 52](https://user-images.githubusercontent.com/96376029/146673983-acef4b09-c4a6-434b-a432-c917deb651ce.png)
![Capture d’écran 2021-12-19 à 12 52 06](https://user-images.githubusercontent.com/96376029/146673986-132aa6bf-93c4-44d4-8e3a-ead3771cdb5f.png)
![Capture d’écran 2021-12-19 à 12 53 07](https://user-images.githubusercontent.com/96376029/146673988-24a3eeea-ae8c-42a3-896a-d9b629650659.png)

**Desktop (please complete the following information):**
 - OS: iOS Monterey 12.0.1
 - Browser chrome
 - Version  96.0.4664.110 (Build officiel) (arm64)

**Comment by zsviczian** [comment]
Does this only affect `Schema atome.excalidraw`?
Can you open `Schema atome.excalidraw` for editing in Excalidraw, and it only does not show when you embed it into a document, or you are not even able to edit `Schema atome.exclaidraw`?

**Comment by fredches** [comment]
You mean editing it with the plugin in Obsidian ?

**Comment by fredches** [comment]
If I close the window, I can't fhave it anymore, that's what I get :
![Capture d’écran 2021-12-19 à 13 14 21](https://user-images.githubusercontent.com/96376029/146674512-e86fbc08-6ef0-428d-8f92-b27bcea3321e.png)

**Comment by fredches** [comment]
And it's the same with another drawing
![Capture d’écran 2021-12-19 à 13 19 22](https://user-images.githubusercontent.com/96376029/146674626-7b54df9b-8139-4a36-b0be-fbe944061996.png)
![Capture d’écran 2021-12-19 à 13 19 57](https://user-images.githubusercontent.com/96376029/146674633-8e155a5b-7354-4520-b628-7ad2ace13e24.png)
![Capture d’écran 2021-12-19 à 13 20 03](https://user-images.githubusercontent.com/96376029/146674636-07927984-f2b7-410a-9c02-d46b7bd74500.png)

**Comment by zsviczian** [comment]
This means something happened to the file... we need to figure out what.
What version of the plugin are you using?
Can you send me the files that do not open?

**Comment by fredches** [comment]
I downloaded the plugin this morning, so I guess it's the last version.
[schema atome.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/7740850/schema.atome.excalidraw.md)
[test.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/7740852/test.excalidraw.md)
[construire un atome.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/7740854/construire.un.atome.md)

I also added the note with the excalidraw file created inside.

Thank you

**Comment by zsviczian** [comment]
Did you manually edit this file?

This:
![image](https://user-images.githubusercontent.com/14358394/146677222-c345bc28-ad50-4112-8172-475d58d0adb4.png)

Should look like this:
![image](https://user-images.githubusercontent.com/14358394/146677251-3279700b-90c0-483a-8c53-4019c261036a.png)

Do you by any chance have another plugin installed that automatically updates the heading of a document?

[schema.atome.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/7740890/schema.atome.excalidraw.md)

![image](https://user-images.githubusercontent.com/14358394/146677388-4bbf6b1c-c5d1-441e-84c8-1b8ab2fbb735.png)

**Comment by fredches** [comment]
Yes I do have this plugin. I guess I need to disable it for this kind of file, no ?

**Comment by zsviczian** [comment]
What's the name of that other plugin?

And yes, you'll need to see if you can disable it for Excalidraw files. If you cannot, then I suggest opening an issue with the developer for the plugin to implement the feature.

**Comment by fredches** [comment]
The plugin is File_Heading_Sync.
I'm supposed to be able to disable it for some files, but I can't so I think I'm going to look at some tutorials to solve my problem (but I prefer having drawings and no sync than the opposite)
Thank you so much for your reactivity.

**Comment by zsviczian** [comment]
The feature you need ideally is to disable File_Heading_Sync for files that have excalidraw-plugin key in the front-matter.

**Comment by zsviczian** [comment]
I've opened an issue with File_Heading_Sync: see link just above

**Comment by fredches** [comment]
OK, I don't use front-matter yet, so I need to learn.

**Comment by fredches** [comment]
There's a french guy who uses both plugins. I'm gonna ask him how he does.

**Comment by fredches** [comment]
I established an exception rule in filename_heading_sync : no sync if the file is an excalibraw one. And it works !
