### ISSUE TITLE
Shortcuts for layers and Grid not work

### ISSUE THREAD

**Issue by Foreversun87** [zsviczian/obsidian-excalidraw-plugin#306]
**Describe the bug**
Hey, i have an issue with the shortcuts for:

*Layers*
- CTRL + ]
- CTRL + [
- CTRL + Shift + ]
- CTRL + Shift + [

*Show grid*
- CTRL + '

They are don't work for me, tested on Ubuntu 20.04 and Windows 10.

have a good one

**Comment by zsviczian** [comment]
What keyboard layout/language are you using?

**Comment by Foreversun87** [comment]
Hello, i use a QWERTZ-Layout and language is german

**Comment by zsviczian** [comment]
One more question. Do the shortcuts work on excalidraw.com?

**Comment by Foreversun87** [comment]
On Ubuntu don't work the shortcuts. On Windows i will testing in approximately 3 hours

**Comment by zsviczian** [comment]
Keyboards are a mess - not in Excalidraw, but generally.
Try using the keys where they would be on a US keyboard:

![image](https://user-images.githubusercontent.com/14358394/146758830-10601a15-19e1-4eb7-a900-67ee83a70725.png)

**Comment by Foreversun87** [comment]
Yes, this works for me, thank you very much :-)
