### ISSUE TITLE
Feature request: default character count for transclusion overflow/ word wrapping 

### ISSUE THREAD

**Issue by rushikb** [zsviczian/obsidian-excalidraw-plugin#308]
**Is your feature request related to a problem? Please describe.**
Currently — every time I try to add a new block embed within an excalidraw drawing — it defaults to no wrapping for long pieces of text. i.e. every new embed requires a user to manually add [[link]]{char count} — this can be a bit painful and repetitive.

**Describe the solution you'd like**
Within excalidraw settings —set a default character count for transclusion overflow/wrap to avoid having to do {character count} each time after adding block references / header embeds. So that by default it wrapped at XX characters and then you could change it by adding the [[link]]{100} if you didn't want to use the default. 

**Additional context**
![CleanShot 2021-12-09 at 17 57 15](https://user-images.githubusercontent.com/6484525/147040469-7084bb96-c564-4318-952a-703dcfdf0808.gif)

**Comment by zsviczian** [comment]
see sticky notes feature in 1.5.4

**Comment by zsviczian** [comment]
Having thought about this feature a bit more, now that sticky notes offer text wrapping, setting a default wrap length will impact the text wrapping in sticky notes.

I will not implement the default wrap line length feature. Instead I recommend transcluding text within a sticky note.

**Comment by rushikb** [comment]
That makes a lot of sense. Thanks
