### ISSUE TITLE
Adding "Convert Excalidraw to Image" to the Commandpallete

### ISSUE THREAD

**Issue by TobiasKlosek** [zsviczian/obsidian-excalidraw-plugin#31]
Im using Anki Flashcards within my Notes which follows this Syntax:
```
This is the front #flashcard
This is the back
```

and would like to use Excalidrawings as the Back/Front of my Cards. Since Anki dont understand Excalidraw,
it would be nice to embed generated pictures of these drawings like this:

```
This is the front #flashcard
![[And_this_is_the_generated_pictures_of_excalidrawing_nr_10.png]]
```

By now everything must be converted/screenshotted and copied, where i have to open/find the corresponding drawings.
An corresponding Command in the Palette "Convert Excalidraw to Image" would be saving much time.

**Comment by zsviczian** [comment]
great. I will first implement #24. Let's return to this is you still feel this is needed after that issue is delivered.

**Comment by zsviczian** [comment]
Please test this release, I hope to have resolved your request:
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.6-test

**Comment by zsviczian** [comment]
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.6
