### ISSUE TITLE
How to set the padding of Sticky Notes？

### ISSUE THREAD

**Issue by 1-2-3** [zsviczian/obsidian-excalidraw-plugin#310]
**Is your feature request related to a problem? Please describe.**
Many thanks to the authors for adding Sticky Notes in 1.5.4. But the padding of 30 is sometimes a little too big. 

**Describe the solution you'd like**
I want the plugin to allow users to customize the padding size.

**Describe alternatives you've considered**
Users can change the default padding in plugin Settings and the padding in the box properties.

**Additional context**
![excalidraw-stickynote](https://user-images.githubusercontent.com/235531/147376029-4dac53dc-2eb1-410c-b998-b48d08471037.png)

**Comment by zsviczian** [comment]
The feature is not available yet (https://twitter.com/aakansha1216/status/1473262463218946049?s=21)
You may open a feature request for this with the core product team: https://github.com/excalidraw/excalidraw/issues

**Comment by 1-2-3** [comment]
Thank you for your reply!
