### ISSUE TITLE
Setting storkeStyle in Script does not take effect

### ISSUE THREAD

**Issue by 1-2-3** [zsviczian/obsidian-excalidraw-plugin#311]
**Describe the bug**
I tried to set the border style of the box in Scripts with `el. StorkeStyle ='dotted'`, but it didn't work.

**To Reproduce**
```js
let width = (ea.getViewSelectedElement().strokeWidth??1).toString();
width = await utils.inputPrompt("Width?","number",width);
const elements=ea.getViewSelectedElements();
ea.copyViewElementsToEAforEditing(elements);
ea.getElements().forEach((el)=>el.strokeWidth=width); // working
ea.getElements().forEach((el)=>el.storkeStyle='dotted'); // NO working
ea.addElementsToView();
```

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Version obsidian v0.13.14, obsidian-excalidraw-plugin v1.5.4

**Comment by zsviczian** [comment]
You have a little type :) It is `strokeStyle` not `storkStyle`

**Comment by 1-2-3** [comment]
Thank you for your reply. It's my fault！But ExcalidrawAutomate seems to have a spelling error.
I found that the following code did not work:
```js
ea.style.strokeStyle='dotted';
id = ea.addRect(
	box.topX - padding,
	box.topY - padding,
	box.width + 2*padding,
	box.height + 2*padding
);
console.log('style:', ea.elementsDict[id]);
```
The last line of the code above will print：
![excalidraw-style](https://user-images.githubusercontent.com/235531/147382822-25b094e6-05e2-4726-b17e-c7e05fe7c676.png)
And the following code works：
```js
id = ea.addRect(
	box.topX - padding,
	box.topY - padding,
	box.width + 2*padding,
	box.height + 2*padding
);
ea.elementsDict[id].strokeStyle='dotted';
```

**Comment by zsviczian** [comment]
amazing... I have it misspelled 6 times! 😳
![image](https://user-images.githubusercontent.com/14358394/147383306-8f331216-0d00-4124-b521-b325f17f0944.png)

Will be corrected in the next release
