### ISSUE TITLE
Improve gesture to move the view with one finger on Android

### ISSUE THREAD

**Issue by slimhk45** [zsviczian/obsidian-excalidraw-plugin#313]
Currently we need 2 fingers to move the canva view, it would be better to have the same gesture as Onenote to move it (single finger only).

**Comment by zsviczian** [comment]
but you also use your one finger to select elements and to draw. How do I know you want to pan instead of select?

**Comment by slimhk45** [comment]
Double click to select. 

Double click to start drawing and a quick button in the corner to stop it.

It's very important to be able to navigate smoothly on this kind of infinite canva,so zooming/dezooming and relocating the canva is one of the most important gesture.

**Comment by zsviczian** [comment]
Needs to be addressed in the core product. See related issue I opened just a few days ago:
https://github.com/excalidraw/excalidraw/issues/4448
