### ISSUE TITLE
Sync dragged markdown file (deleting it from the canva delete it too in the filesystem)

### ISSUE THREAD

**Issue by slimhk45** [zsviczian/obsidian-excalidraw-plugin#317]
Im using exclusively Excalidraw on Obsidian, and I would like to be able to have a two way sync between markdown file and their corresponding embedding object on the canva when I delete them. I don’t want to clutter my filesystem with unused markdown file I have forgotten and are not appearing on my canva.

**Comment by zsviczian** [comment]
How would you distinguish that you are deleting something permanently vs. just removing a document from the canvas?

The same logic could hold for the images as well.

**Comment by slimhk45** [comment]
Maybe a shortcut could work (ctrl+del), or a pop-up ?

**Comment by zsviczian** [comment]
ctrl+del is a good idea. I'll implement this for markdown and for image embeds as well.

**Comment by zsviczian** [comment]
Added command palette action to delete image / markdown + file. You can add a hotkey to the command palette action if you'd like.
