### ISSUE TITLE
iPad Pro - Keyboard disappears after focusing on Canvas Hex Box

### ISSUE THREAD

**Issue by pixelinkmedia** [zsviczian/obsidian-excalidraw-plugin#318]
**Describe the bug**
On iPad Pro (iOS 15 - Obsid. ver 1.05)
When you tap in the Canvas Hex text box where you can manually edit the Hex code.
Once there is a focus, the iPad keyboard displays for about 1 second, then disappears.
There is no way to edit the Hex text.
So, if I want to make the Canvas background "transparent" I can't
This functionality work perfectly fine on the Desktop version of Obsid.

**To Reproduce**
1. Tap finger (or Pen) on the Canvas Hex text box
2. The keyboard will display- then disappear in one second.
3. That's it... cannot do anything else

**Expected behavior**
Keyboard should stay open so I can edit the Hex value or paste a value.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 15

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - Browser, safari]
 - Version: Obsidian 1.05 - Excalidraw 1.5.5

**Additional context**
I used to be a programmer. I think the Hex text box is losing focus after keyboard displays, then the keyboard disappears because the Hex box has also lost focus. It's a circular bug.
Hope this will be a top priority bug because I can edit the text box at all.
If just fixing the focus issue doesn't work... maybe...
Possible fix, is to not allow manual edit, but instead put a button that opens a modal text box so it stays open, then the keyboard should stay open as well.

**Comment by zsviczian** [comment]
I could not reproduce on iOS 14.8. Installing iOS 15.1 to see if it will behave differently

**Comment by zsviczian** [comment]
spoke too soon. Yes, I can reproduce. I also know the root cause. Working on it.

**Comment by zsviczian** [comment]
will release fix in few minutes. solved in 1.5.6

**Comment by pixelinkmedia** [comment]
Wow... that was quick. Thank You!!
Hope you are not working on Christmas day.

**Comment by pixelinkmedia** [comment]
Updated and still does it. Sorry.
