### ISSUE TITLE
How to open embedded markdown file on Android (there is no command in the palette) 

### ISSUE THREAD

**Issue by slimhk45** [zsviczian/obsidian-excalidraw-plugin#320]
On Android there is no keyboard. So how to open the embedded file? I don't see any command in the palette. 

PS: It's not an Excalidraw question, but how do we create a shortcut button to press to launch important command we use on Android? I want a shortcut button to open markdown file and delete them along their embedded view as you recently added this amazing feature 👍

**Comment by zsviczian** [comment]
select the element and click the link button in the top
![Screenshot_20211226-144509_Obsidian](https://user-images.githubusercontent.com/14358394/147410131-8bf3f189-0f5c-4a42-ae85-7ea3151ccaf4.jpg)

**Comment by slimhk45** [comment]
Nice thx 👍
