### ISSUE TITLE
Changing the default location for insertion of new objects

### ISSUE THREAD

**Issue by Archie-2021** [zsviczian/obsidian-excalidraw-plugin#323]
**Is your feature request related to a problem? Please describe.**

lets say create a new link in markdown mode of a excalidraw, or I select something from library, it is going to be shown at the center of drawing screen by default, but the center is most common place to be use so it is going to get entangled with already created content and it makes a lot of friction

**Describe the solution you'd like**

I think it is better to create new items in some other place, somewhere not very far from what already exists but a bit on the side.

thanks

**Comment by zsviczian** [comment]
When you insert a markdown link, it will be created at the last pointer location, not the center.
When you add an element from the library it will be created at the center. For the library, you need to open a feature request with the core Excalidraw product team. https://github.com/excalidraw/excalidraw/issues

**Comment by Archie-2021** [comment]
> When you insert a markdown link, it will be created at the last pointer location, not the center. When you add an element from the library it will be created at the center. For the library, you need to open a feature request with the core Excalidraw product team. https://github.com/excalidraw/excalidraw/issues

What I mean by markdown link was to create a new note in markdown view (or in case whatever element is need to created in that mode which has not block reference to it), I think you are referring to inserting a link to an already existing note in excalidraw view, which is not an issue for me.

sure ,I will open a request for that. thank you
