### ISSUE TITLE
Bad colors of background element of Exalidraw interface 

### ISSUE THREAD

**Issue by dariuszkowalski-com** [zsviczian/obsidian-excalidraw-plugin#326]
**Describe the bug**
Bad colors of background element of Exalidraw interface when Theme of Exalidraw is not the same as theme of Obsidian.

**To Reproduce**
I have got minimal theme installed, controlled by advanced apperance plugin

**Expected behavior**

* Obsidian theme - Dark,  Exalidraw "theme" - Light
![image](https://user-images.githubusercontent.com/37656900/147573287-a0c6fb0f-5bbf-43ec-b806-dd5dcddb1c14.png)

* Obsidian theme - Light,  Exalidraw "theme" - Dark
![image](https://user-images.githubusercontent.com/37656900/147573245-c3eee84f-f951-4a7a-bb75-5c57aae7ced5.png)

**Screenshots**

* Obsidian theme - Dark,  Exalidraw "theme" - Light
![image](https://user-images.githubusercontent.com/37656900/147573022-73b43b98-8af4-4c74-b24d-958c35fee085.png)

* Obsidian theme - Light,  Exalidraw "theme" - Dark
![image](https://user-images.githubusercontent.com/37656900/147573197-66713df1-a64b-440a-a13d-5e75f1324398.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: all 
 - Version: Exalidraw: 1.5.7 , obsidian 0.13.16

**Additional context**
This problem start to appear when this options were added:
![image](https://user-images.githubusercontent.com/37656900/147573548-b08fb80a-3665-4137-a9d5-c0735d0f3bed.png)

**Comment by zsviczian** [comment]
does the same issue happen when you use the default obsidian theme?

**Comment by dariuszkowalski-com** [comment]
I have got this issue with minimal theme - with default theme it works fine.

**Comment by dariuszkowalski-com** [comment]
body .excalidraw {
--input-border-color: 
    --button-gray-1: var(--background-tertiary);
    --button-gray-2: var(--background-tertiary);

**Comment by dariuszkowalski-com** [comment]
Issue was in Theme Minimal. Closed
