### ISSUE TITLE
Show only excalidraw drawings in graph view

### ISSUE THREAD

**Issue by slimhk45** [zsviczian/obsidian-excalidraw-plugin#328]
Since I'm using  Obsidian with Excalidraw as a OneNote replacement, I use markdown file only as a text box in my Excalidraw drawings. So I don’t need to see them in the graph view (they cluttered it). Is it possible to hide them and show only links between Excalidraw drawings ? Or is it a thing that can only be developed by the Obsidian team ?

Thx :)

**Comment by zsviczian** [comment]
Awesome! You are implementing my dream solution!
If you tag your markdown files in the front-matter you can filter them out in graph view:

![image](https://user-images.githubusercontent.com/14358394/147686421-ef3e3448-08d8-4293-afa9-821ba5d044e6.png)

![image](https://user-images.githubusercontent.com/14358394/147686378-b8e0f7c5-ba9b-4c8f-a0e1-a422a63c1475.png)

You can create a template for new files, so all your new files automatically get this front-matter tag.

**Comment by slimhk45** [comment]
Thanks for the tips 👍
