### ISSUE TITLE
Impossible to undo deletion with command "delete selected image or markdown file from the vault"

### ISSUE THREAD

**Issue by slimhk45** [zsviczian/obsidian-excalidraw-plugin#329]
Sometime I want to undo a deletion after having deleted both an attachment file and its embedded view with the command "delete selected image or markdown file from the vault". 

I'm facing the problem that the plugin only restores the embedded view without the corresponding file in the vault. I think this is solvable on PC but not on mobile without a rewriting of how Obsidian deletes files in the vault (making a trash in the vault to empty manually mimicking how OneNote deals with deleted pages could solve the problem).

**Comment by zsviczian** [comment]
I have Obsidian Sync. I can see the deleted file there, and I can restore it.

![image](https://user-images.githubusercontent.com/14358394/147707194-22ef9945-e13d-4b20-8e53-cba2e6eb9eb8.png)

![image](https://user-images.githubusercontent.com/14358394/147707228-481079a0-9222-4d57-9766-4df987dd500a.png)

**Comment by slimhk45** [comment]
Any possibility set the default behavior of the undo command to restore both the file with obsidian sync and the embedded? 

Thx for your reply :)

**Comment by zsviczian** [comment]
Unfortunately the Obsidian.Sync API is not published, I cannot access the restore function.

For your use case, you might be better off with a cleanup script that you run every once in a while to cleanup all files not linked to a drawing. 

The below script will identify all files in your vault that are not linked to an Excalidraw drawing. If you uncomment the final bit in the code, the script will immediately delete those files as well. ⚠⚠⚠ Only uncomment that part of the code, if you are absolutely sure you know what you are doing!!! make sure you have a full backup before you experiment with this on your main vault. ⚠⚠⚠

Note, that depending on the size of your vault, and the speed of your computer, this script might run for a couple of minutes before producing a result.

```javascript
function cleanup() {
  ea = ExcalidrawAutomate;
  const notExcalidrawFiles = app.vault.getFiles().filter((f)=>!ea.isExcalidrawFile(f));
  const filesNotLinkedToADrawing = notExcalidrawFiles.filter((f)=>{
    const backlinks = app.metadataCache.getBacklinksForFile(f);
    const backlinkFiles = Object.keys(backlinks.data);
    let isLinkedToDrawing = false;
    for(path of backlinkFiles) {
      const f = app.vault.getAbstractFileByPath(path);
      if(f && ea.isExcalidrawFile(f)) isLinkedToDrawing = true;
    }
    return !isLinkedToDrawing;
  });
  //be careful with this... test it first! make a backup!!!
  //uncomment only if you are sure you know what you are doing!
  //filesNotLinkedToADrawing.forEach((f)=>app.vault.delete(f));

  return filesNotLinkedToADrawing.map((f)=>f.path);
}

cleanup();
```

**Comment by zsviczian** [comment]
I am sorry, but I don't think I can do more on this.
