### ISSUE TITLE
Perfomance Issues

### ISSUE THREAD

**Issue by TobiasKlosek** [zsviczian/obsidian-excalidraw-plugin#33]
Using this Plugin inside Obsidian causes about 20% more of CPU/GPU usage than working inside the browser..this results to delayed displaying of shapes/handdrawn figures and so on.. In the Webinterface on excalidraw it works properly.

Im using an Surface Book 1 (i5/8Gig) on WIndows 10-

**Comment by zsviczian** [comment]
I will investigate. Just today I was reading on the Excalidraw discord about a performance issue impacting older devices, and surface book was specifically mentioned. There is also a fix proposed. I will look into it tonight.

https://github.com/excalidraw/excalidraw/issues/3505
https://discord.com/channels/723672430744174682/723672430744174685/836321098546413589

**Comment by TobiasKlosek** [comment]
I discovered that issue on excalidraw and mentioned that in the Discord. 
There was a GPU draw of about 60-70% which is now reduced to 40%.
Using Excalidraw Plugin inside Obsidian increases somehow the Load and is not really usable...

**Comment by zsviczian** [comment]
That is a shame. I am sorry to hear that. This must be something Obsidian is doing on top. I am really not adding any additional code to Excalidraw, simply embed it into an Obsidian Workspace Leaf. 

I am afraid I won't be able to help you with this one.

**Comment by wokawoka** [comment]
I'm experiencing the same problem

**Comment by jiajiala** [comment]
I'm experiencing the same problem……

**Comment by zsviczian** [comment]
This is typically caused by other plugins or themes. Typical culprits are the Metadata Menu and Minimal Theme.
Turn off all plugins and switch to the default theme. Restart Obsidian and check if the performance issue is still there. If yes, please let me know. If not, please identify which other plugin or theme is causing the issue and raise an issue with the relevant developer.
