### ISSUE TITLE
Insert + create new page at the same time with 1 click to speed up the workfkow

### ISSUE THREAD

**Issue by slimhk45** [zsviczian/obsidian-excalidraw-plugin#331]
I would like to create and insert a page at the same, rather than creating first the page in the vault then inserting it. At first glance it seems a useless feature, BUT IT WOULD SPEED THE PROCESS OF INPUTING TEXT ON A PAGE SO MUCH (especially on mobile device).

Thx :)

**Comment by zsviczian** [comment]
Install 1.5.10
then download this ExcalidrawAutomate script: https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Create%20new%20markdown%20file%20and%20embed%20into%20active%20drawing.md
