### ISSUE TITLE
Overloading Obsidian search when the "Show more context" of search is enabled

### ISSUE THREAD

**Issue by Pyrodusk** [zsviczian/obsidian-excalidraw-plugin#335]
**Describe the bug**
I noticed that when I do searches in the Obsidian search and toggle the "Show more context", if my result includes some text from a Excalidraw drawing, Obsidian becomes very laggy and seems to have a hard time processing the search (because the whole JSON part of the drawing is being displayed in the search pane).

**To Reproduce**
Do an Obsidian search for words included in a drawing of your vault and toggle "Show more context".

**Expected behavior**
Managing to hide this part from the Obsidian search.

**Comment by zsviczian** [comment]
I am afraid there is not much I can do here. I have already enclosed the JSON in %%markdown comments%% to avoid impacting preview performance. Unfortunately, it seems that "show more context" will include markdown comments as well. Can I ask you to bring this question up with Licat?

I could monitor if search results include excalidraw JSON... but I can only hide the information once it is displayed, thus adding this monitoring would further degrade performance - though it might help the readability of search results.

**Comment by Pyrodusk** [comment]
I understand no worry, I'll ask it on the forum as a feature request. I was thinking it could possibly be solved in one of two ways : (1) by allowing users to add default path exclusion to their searches to be able to exclude `.excalidraw.md` files (I know it is kind of a trade off) or (2) add a search filter so that comments does not show up in searches (maybe like a little button or switch in the search pane. Keep in mind tho, I'm not a dev or a programmer so my "solution" might be somewhat basic but if you have any other feedback about it, I'll gladly take them.

And btw, thank you very much for your plugin, it is truly amazing!

**Comment by zsviczian** [comment]
One thing I could do is to add a setting to zip the JSON in Excalidraw files. To allow manual editing of the file, I would add a command under more options, to open the file in markdown view without zipping. By zipping the JSON the resulting random sequences of characters would not show up when you search for words in search.

**Comment by HongMind** [comment]
This seems like a good idea and I'm really looking forward to see this in the coming builds. It will make searching and retriving ideas from different Excalidraw notes a lot cleaner and easier.

**Comment by Pyrodusk** [comment]
Yes absolutely! Thanks you
