### ISSUE TITLE
Cannot update because of version number's error

### ISSUE THREAD

**Issue by Quorafind** [zsviczian/obsidian-excalidraw-plugin#34]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zsviczian** [comment]
Thanks. Please check again. It should now work. I made a mistake when posting a test release.

**Comment by zsviczian** [comment]
1.0.6 now available in Community Plugins
