### ISSUE TITLE
Can this set the font I want? How do I do that?

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#341]
I tried to add it in script, but it didn't work
![image](https://user-images.githubusercontent.com/29135984/148238215-5c6fa03f-6fa7-4b2f-84ef-9419541d1773.png)

**Comment by zsviczian** [comment]
unfortunately not.

**Comment by zsviczian** [comment]
support for fourth font for text elements is now available in 1.5.17
