### ISSUE TITLE
Cannot get a Resized view of an embedded excalidraw Image on a .md file in Obsidian in Live Preview mode. 

### ISSUE THREAD

**Issue by gigazen** [zsviczian/obsidian-excalidraw-plugin#344]
Hi there. Resized view of an embedded excalidraw image on a .md file in Obsidian can only be seen in Reading mode but cannot get a Resized view in Live Preview mode. Please resolve the issue.

**Comment by zsviczian** [comment]
Resolved this in 1.5.15

**Comment by gigazen** [comment]
Many thanks @zsviczian. This will be really helpful. ❤
