### ISSUE TITLE
With the `Box Selected Elements` script, the newly created boxes are located on top of the wrapped boxes

### ISSUE THREAD

**Issue by 1-2-3** [zsviczian/obsidian-excalidraw-plugin#347]
**Describe the bug**
With the `Box Selected Elements` script, the newly created boxes are located on top of the wrapped boxes and their hierarchy often needs to be manually adjusted. It would be more convenient if the script could adjust the newly created box to the lower layer of the wrapped box.

**To Reproduce**
You can reproduce the problem by following the steps for the GIF image below.
![box](https://user-images.githubusercontent.com/235531/148668653-768fb7cc-3bad-43bf-a3e9-b3492e0b8bd3.gif)

**Expected behavior**
The newly created box is located below the wrapped box.

**Comment by zsviczian** [comment]
Good point. This is due to the way I am adding modifications... right now you cannot add new elements to the back with ExcalidrawAutomate. New elements will always be on top of elements in the view. 

I think I'll implement/expose "send to back" and "bring to front" on ExcalidrawAutomate API.

**Comment by zsviczian** [comment]
see the solution in 1.5.16
