### ISSUE TITLE
"Create and Embed" command creates new file in root directory instead of Excalidraw directory

### ISSUE THREAD

**Issue by BurningSquid** [zsviczian/obsidian-excalidraw-plugin#348]
**Describe the bug**
When using the "Create a new drawing - IN A NEW PANE - and embed into active document" command the .excalidraw file is not created in the excalidraw directory. 

**To Reproduce**
1. Create a new document
2. CTRL-P to open commands
3. Search Excalidraw and Select "Excalidraw: Create a new drawing - IN A NEW PANE - and embed into active document". Also happens when opening in the current active pane

**Expected behavior**
Excalidraw file should be created in the Excalidraw (or otherwise defined) folder

**Screenshots**
![image](https://user-images.githubusercontent.com/13892894/148688419-df9a3d2b-6a1e-4ed8-849f-23e0ccd952b2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v0.13.19

**Additional context**

**Comment by zsviczian** [comment]
The create and embed command follows the default obsidian settings for attachments. Is the vault root your Obsidian default attachment folder?
