### ISSUE TITLE
iPad : Missing command palette options

### ISSUE THREAD

**Issue by Elaws** [zsviczian/obsidian-excalidraw-plugin#349]
**Describe the bug**
On iPad, not all command palette options are available. E.g. : I can't find the "Create a new drawing and embed" options.

**Smartphone (please complete the following information):**
 - Device: iPad Pro 2018
 - OS: iPadOS 15.1

**Additional context**
Obsidian Excalidraw version : 1.5.16
iPadOS Obsidian version : 1.0.5

**Comment by zsviczian** [comment]
Strange, it shows up on my iPad.
The "Create a new drawing and embed" options are only visible when you are editing a markdown document. Is that how you've tried to use the command?

**Comment by Elaws** [comment]
Oops, I wrote this issue probably too late in the evening ! Indeed, I was not at all editing a markdown document, hence it's logical the option did not appear.

Thank you and sorry for the disturbance !
