### ISSUE TITLE
Typesetting functions

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#35]
![image](https://user-images.githubusercontent.com/29135984/116484281-54345a80-a8bb-11eb-8e76-17b82ddf1458.png)

The image is displayed to the left and the text at the bottom moves to the right, this is a good situation but cannot be actively controlled, is there a way to do the typography shown below?

![image](https://user-images.githubusercontent.com/29135984/116484539-dae93780-a8bb-11eb-92b4-1bdb1cf3de63.png)

**Comment by zsviczian** [comment]
Good suggestion. Just released 1.0.7 to address this issue.
use `|left` to align without wrapping and `|left-wrap` for text wrapping. Same with `|right` and `|right-wrap`
