### ISSUE TITLE
Filename setings for embed drawings

### ISSUE THREAD

**Issue by AlexanderKhmelnytsky** [zsviczian/obsidian-excalidraw-plugin#350]
**Is your feature request related to a problem? Please describe.**
When i use the command: _Create a new drawing - ... - and embed into active document_ – an excalidraw file is created with the type header: `Note header + YYYY-MM-DD HH.mm.ss`

I would like the title of the newly inserted Excalidraw file to be in the format: `YYYY-MM-DD HH.mm.ss`

Why I need this: 
When I take notes of some material (e.g. YouTube videos) – I take a lot of screenshots, insert them in a note through Excalidraw, and highlight important points, but:
When I search for this note, I find a lot of unnecessary files and it degrades the workflow.

**Describe the solution you'd like**
In the Excalidraw settings in the * Filename * or * Embed & Export * section, add the following lines:
- toggle button: Name of the new inserted drawing starts with the name of the note.
- Filename prefix for embed drawings.

**Comment by zsviczian** [comment]
I'll try to include this for you in the next release, likely published this coming weekend.

**Comment by zsviczian** [comment]
will be released in 1.5.20
