### ISSUE TITLE
Ctrl D shortcut does not duplicate an item

### ISSUE THREAD

**Issue by phil31753** [zsviczian/obsidian-excalidraw-plugin#352]
Ctrl D shortcut does not duplicate an item

1. select a drawing object or line point
2. Type Ctrl D

The drawing object or line point should be duplicated.

 - Lenovo 740C
 - Windows 10
 - Obsidian 0.13.19
 - Excalidraw  1.5.16

Works in the web-based version of Excalidraw

**Comment by zsviczian** [comment]
duplicate item. see: #355
