### ISSUE TITLE
Right click menu not fully visible

### ISSUE THREAD

**Issue by phil31753** [zsviczian/obsidian-excalidraw-plugin#353]
The right click menu is not fully visible with the bottom portion displayed off screen.

1. Select a drawing object or line point
2. Right click on the drawing object
3. The right click menu is displayed but with the bottom portion displayed off screen

![Screenshot 2022-01-13 113442](https://user-images.githubusercontent.com/95326157/149262381-a82ce001-fe58-454a-8c28-1f36aeef793d.png)

The right click menu should be fully visible on screen.

 - Lenovo 740C
 - Windows 10
 - Obsidian 0.13.19
 - Excalidraw  1.5.16

Works on web-based version of Exclalidraw.

**Comment by zsviczian** [comment]
Duplicate item. See: [#4572](https://github.com/excalidraw/excalidraw/issues/4572)
