### ISSUE TITLE
[Bug] Cmd+D doesn't work in obsidian on iPad

### ISSUE THREAD

**Issue by unfamiliarish** [zsviczian/obsidian-excalidraw-plugin#355]
## Description
'Cmd+D' in obsidian does not duplicate object. Does duplicate in excalidraw.com.

## Expected behavior
Cmd+D typed on keyboard for selected object would duplicate object.

## Environment:
- iOS 15.1 (2020 iPad Pro 12.9")
- Excalidraw v1.5.16 in Obsidian v1.0.5
- excalidraw.com in Safari
- Logitech Combo Touch iPad Pro (5th gen)

## Video
https://www.dropbox.com/s/cpx81yovxbemmhj/excalidraw_obsidian_ipad_cmd%2Bd_not_recognized.mp4?dl=0

### Repro steps
* In Obsidian:
  * Using finger, draw diamond
  * Using keyboard, delete (success), cmd+z (success), cmd+d, cmd+d (nothing)
* In excalidraw.com:
  * Using finger, draw diamond
  * Using keyboard, delete (success), cmd+z (success), cmd+d, cmd+d (success)

**Comment by zsviczian** [comment]
Do you have an Obsidian hotkey for Cmd+D? If yes, that will take priority over the Excalidraw hotkey settings.
I just tried Cmd+D on my iPad, and it worked once I removed the cmd+D hotkey I had configured in Obsidian hotkeys

**Comment by unfamiliarish** [comment]
Excellent, that fixed it for me. Thanks!
