### ISSUE TITLE
Transclusion has issues with code blocks

### ISSUE THREAD

**Issue by ShravanSunder** [zsviczian/obsidian-excalidraw-plugin#357]
**Describe the bug**

- Referencing embeds of headings with `code blocks` in them  or normal embed in them causes excalidraw to have errors on reload.  `e.g. javascript`
- I think this is because of quotes `'` in code blocks that escape the JSON that excalidraw needs as a data source in the text 

**To Reproduce**
1. Create an excalidraw diagram
2. copy an embed to a code block OR copy embed to heading with code block underneath
2. paste transclusion
3. save close document
4. reload document and see error

**Expected behavior**
It should handle code blocks (typescript, javascript)

**Desktop (please complete the following information):**
 - OS: mac

**Comment by zsviczian** [comment]
you are probably right in your analysis. Until I fix this, an alternative that will probably result in a nicer looking outcome is to embed the code as a markdown document. You can see an example here: https://twitter.com/zsviczian/status/1468897640020692993?s=21

**Comment by zsviczian** [comment]
resolved in 1.5.22
