### ISSUE TITLE
could you add Chinese handwritten font,there is an added excalidraw project for reference

### ISSUE THREAD

**Issue by shi-jie01** [zsviczian/obsidian-excalidraw-plugin#359]
Hello, can you add Chinese handwritten font? Thank you very much
Here is an excalidraw project that already supports Chinese handwriting, which can be used as a reference
url :  https://github.com/mebtte/excalidraw

**Comment by zsviczian** [comment]
I will release 1.5.17 soon, that will solve this issue.
