### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by alextroop** [zsviczian/obsidian-excalidraw-plugin#36]
Should the sync work for .excalidraw files? It does not seem to at the moment. I am running Obsidian v.0.11.13 with Excalidraw 1.0.7 installed, on macOS 11.3. Sync is turned on for all the listed options, and works for everything else to another mac.

Thanks again for the wonderful plugin. Great to have PNG export working.

**Comment by zsviczian** [comment]
Sync only works on the files you can set in sync settings.
![image](https://user-images.githubusercontent.com/14358394/116586298-98564800-a919-11eb-9339-487d42fc0642.png)

This was my question to Licat on 24 April: 
*It would be great to have an option to add registered file types to sync. In particular, I am interested in .excalidraw files. Typical use case: sketching on your iPad and editing your notes at your desktop. Can .excalidraw files be added as an option to sync?*

... and Licat's response: 
*We will figure out a way once we start working on Sync again - we tackle one area of the app at a time and right now we're doing another push for mobile in preparation for going to insiders soon*

For this reason, I am using OneDrive to sync. I use Obsidian on Windows, Android and ChromeOS. I use [Autosync for OneDrive](https://play.google.com/store/apps/details?id=com.ttxapps.onesyncv2) on my Android and Chromebook and overall I am satisfied with the sync experience.

This will likely resolve itself once Licat gets back to working on sync.

**Comment by zsviczian** [comment]
I thought of one other solution.

You can also use Obsidian Sync in conjunction with "Obsidian Git" (find it in community plugins). Set up git to ignore all files except for .excalidraw by adding the following to `.gitignore`. Obsidian Git does not work on mobile, but on Android you can use an app like MGIT to sync your `.excalidraw` files from/to the git repository.
  ```
  #ignore all kind of files
  *.*
  #except excalidraw files
  !*.excalidraw
  ```
