### ISSUE TITLE
Pen width,Eraser

### ISSUE THREAD

**Issue by edmlover** [zsviczian/obsidian-excalidraw-plugin#361]
The smallest pen width of writing function still too thick，can you change it to the pixel mode(or add a new mode)，for example，it can be adjust the pen width from 1 pixel to 10 pixel, this plugin is excellent,I can feel you put a lot of effort into it.

I use it for surface , surface pen is a little awkward when use on it, hope you can also add eraser to it, thanks!!!!

**Comment by zsviczian** [comment]
So this would need to be changed in the core Excalidraw package. However, you can do a workaround using Excalidraw Scripts. Try to install the `Modify Stroke Width of Selected Elements` script.

you can learn more about the script engine store here.
[![plugin store](https://user-images.githubusercontent.com/14358394/147889174-6c306d0d-2d29-46cc-a53f-3f0013cf14de.jpg)](https://youtu.be/lzYdOQ6z8F0)

**Comment by kazdonkai** [comment]
Is it possible to install the Apple Pencil Kit for iOS?
That way there would be no malfunctions caused by the hand.

**Comment by Signynt** [comment]
@zsviczian it seems that an eraser will soon be [coming to core Excalidraw](https://github.com/excalidraw/excalidraw/issues/3682), I'm guessing this will simultaneously also be added to this version, right?
Really excited to finally get this feature!

**Comment by zsviczian** [comment]
Yes. However, to manage expectations, my understanding is that this won't
be the apple pencil SDK kit, that is you won't be able to double-tap your
pencil to activate it, and it will delete complete elements... i.e. much
like select element and press delete on the keyboard today.

**Comment by zsviczian** [comment]
an eraser will be added in 1.6.18 - it won't be the Apple Pencil eraser though... there are further enhancements to the eraser being worked by the Excalidraw team.
