### ISSUE TITLE
Manually set the size of a shape

### ISSUE THREAD

**Issue by mrkoz** [zsviczian/obsidian-excalidraw-plugin#367]
I would like to be able to set the size of a shape in the text box, at the moment it seems like i can only change the size by dragging the handles. For example if i create a box, i'd like to set the PX size manually.

It would be nice to be able to edit the shape stats in the "stats for nerds" pane by clicking on them.

I consider that i can probably set this in the source code.

**Comment by zsviczian** [comment]
You may be interested in the Excalidraw Script Engine. I created it for small automation tasks that are not natively available in the Excalidraw package. You can access the "Script Store" by clicking the button in the top right:
![image](https://user-images.githubusercontent.com/14358394/149630054-5f2950e3-124b-4fe8-98f1-0b72991a9062.png)

Look for the `Dimensions` script in the list.

Finally here's a video about the script store:
[![plugin store](https://user-images.githubusercontent.com/14358394/147889174-6c306d0d-2d29-46cc-a53f-3f0013cf14de.jpg)](https://youtu.be/lzYdOQ6z8F0)

**Comment by zsviczian** [comment]
Beyond the workaround of using the Script Engine, I agree, it would be great if Stats for Nerds would be editable. Please raise a feature request on the Excalidraw product page: https://github.com/excalidraw/excalidraw/issues
