### ISSUE TITLE
Text-align lost when embedding "sticky notes"

### ISSUE THREAD

**Issue by PurpleGuitar** [zsviczian/obsidian-excalidraw-plugin#376]
**Describe the bug**
When embedding a drawing containing "sticky notes" onto another page, the notes are all rendered as left-aligned even if they are centered or right-aligned.  (Or possibly it's a margin/padding issue; maybe the text is aligned properly but the text block is left aligned within the sticky-note.)

**To Reproduce**
1. Create a drawing with sticky notes that with center or right text-alignment.
2. Embed the drawing on another page.
3. Observe that the sticky notes are all left-aligned.

**Expected behavior**
Sticky notes should maintain their text alignment even when embedded.

**Screenshots**
![image](https://user-images.githubusercontent.com/1095575/150384160-97199bad-a7a4-47cc-8466-b84e5faac6be.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Obsidian v0.13.21, Excalidraw 1.5.15

**Additional context**
Thank you for your hard work on Excalidraw!  I love using it and I appreciate how much effort you put into maintaining it.

**Comment by zsviczian** [comment]
I am able to reproduce the issue. 

🤔 Very strange... the svg and png exports generate an output with the correct alignment, only when embedding a drawing into a document does the error occur... but when I generate the preview of an embedded drawing, I simply create an svg or png export on the fly (depending on settings).

**Comment by zsviczian** [comment]
fixed in 1.5.20 (will be released later this weekend)

**Comment by PurpleGuitar** [comment]
Just got the new version, and it looks great now!  Thanks for fixing it so quickly.

![image](https://user-images.githubusercontent.com/1095575/150689166-11b85ae0-165c-4e04-b340-8e9e4e798db6.png)
