### ISSUE TITLE
Using the new "binding text to shapes" feature when "Insert link to file"

### ISSUE THREAD

**Issue by nicolasmarc1** [zsviczian/obsidian-excalidraw-plugin#377]
As Excalidraw core implemented sticky/ binding text to shapes [feat: bind text to shapes when pressing enter and support sticky notes 🎉 by ad1992 · Pull Request #4343 · excalidraw/excalidraw](https://github.com/excalidraw/excalidraw/pull/4343), would it be possible to use this updated method when we use the "Insert link to file" command? 

Current Behavior and alternatives:
Currently the text box the note title is coming in isn't wrappable so i have to copy that text, create another box, click inside to get a wrappable text box and paste the note title in it. 

Totally doable, but having this as a default would be a nice Quality of Life Improvement.

Thanks!

**Comment by zsviczian** [comment]
This is technically simple to implement, but difficult to predict what people want/need. Do they want a box around the text to show it is a sticky note, or should the border be transparent? Should the inserted box be as wide as the text, or be wrapped to a certain width by default. Do they want a sticky note by default, or prefer a regular text element?...

Instead please check if you find this comfortable? If not, we can always return to deciding the preferred default behavior of inserting a link...

Are you familiar with the Excalidraw Script Store?
I added a script for you: Convert selected text element to transparent sticky note

[![plugin store](https://user-images.githubusercontent.com/14358394/147889174-6c306d0d-2d29-46cc-a53f-3f0013cf14de.jpg)](https://youtu.be/lzYdOQ6z8F0)

**Comment by nicolasmarc1** [comment]
You're right, it didn't occur to me that some people would not like having wrappable note title. The script works well thank you!
