### ISSUE TITLE
Add Next Step process's Settings : Ending arrowed on none is triangle

### ISSUE THREAD

**Issue by Yot67** [zsviczian/obsidian-excalidraw-plugin#388]
Script : Add Next Step process 

Bug : Ending arrowhead on NONE draws ARROW

![Obsidian_AzLAstsvhv](https://user-images.githubusercontent.com/14005233/150918840-fe5b2229-8fa2-42e1-8428-77edb1dc0f5c.png)

![Obsidian_EdmgsZPdHB](https://user-images.githubusercontent.com/14005233/150919236-c80b5c68-a28b-4041-ad2b-c2f51123f29f.png)

**Comment by zsviczian** [comment]
I fixed the script with a temporary patch. It works as expected now. 
I will keep this issue open, as I need to apply a permanent fix in ExcalidrawAutomate

Need to check for `typeof formatting?.startArrowHead === 'undefined'` to allow null as a valid value here:
https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/f8126709ccf2b46b2084e8646510edcd6500d2bd/src/ExcalidrawAutomate.ts#L789-L796
