### ISSUE TITLE
Script to place objects by the same horisontal distance between their centers.

### ISSUE THREAD

**Issue by HiRolla** [zsviczian/obsidian-excalidraw-plugin#394]
That would be great and handy to have a script that distributes objects horisontally with the same distance between their centers.
This button makes the spacing to be the same, not the center to center distance.
![image](https://user-images.githubusercontent.com/7746812/150989953-44902319-3da3-4598-80e4-f9780c45699b.png)

**Comment by zsviczian** [comment]
@1-2-3, this request is similar to your [Fixed spacing](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Fixed%20spacing.md) and [Fixed vertical distance](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Fixed%20vertical%20distance.md) scripts. Would you be interested/open in creating this script, or adding this feature to the existing scripts and include the distribution method as a setting?

**Comment by 1-2-3** [comment]
@zsviczian @HiRolla good idea. I'll do this.

**Comment by zsviczian** [comment]
Two new scripts added by @1-2-3, already available in the script store:
- Fixed horizontal distance between centers
- Fixed vertical distance between centers

**Comment by 1-2-3** [comment]
@zsviczian @HiRolla 
The `Fixed horizontal distance between centers` script can easily achieve this effect:
![scripts-fixed-horizontal-distance-between-centers](https://user-images.githubusercontent.com/235531/151503425-7a32299f-5282-4bb3-ae9a-c02b696eb141.png)

But it is not easy to achieve this effect：
![scripts-fixed-inner-distance](https://user-images.githubusercontent.com/235531/151503517-6152595b-971f-42b4-b3ef-5b7a435b9ffa.png)

So I created a new script called `Fixed inner distance` and just submitted a PR.

**Comment by HiRolla** [comment]
@1-2-3 @zsviczian 
That's really great! Thank you
