### ISSUE TITLE
Script to select only connectors (or desect all but connectors)

### ISSUE THREAD

**Issue by HiRolla** [zsviczian/obsidian-excalidraw-plugin#399]
Hi! I would wonder to have a script that selects all of connectors or deselects all but connectors if there is some selection.
Is it worth it?

**Comment by zsviczian** [comment]
you mean selects all the arrows and lines, or just the arrows, or just the arrows that are connected to an element?

**Comment by HiRolla** [comment]
I mean arrows and connect-lines. Often I draw schemes in a rush and finally I need to send-to-back all connectors, change line type and opacity. Now I have to pick every arrow to get it selected.

**Comment by zsviczian** [comment]
See [Select Elements of Type](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Select%20Elements%20of%Type.md) in GitHub.

This is also very handy when you want to select only text elements to change the color of the text, but leave everything else unchanged.

**Comment by 1-2-3** [comment]
> 



> See [Select Elements of Type](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Select%20Elements%20of%20Type.md) in GitHub.
> 
> This is also very handy when you want to select only text elements to change the color of the text, but leave everything else unchanged.

Great, this is exactly what I need
