### ISSUE TITLE
Resizing and repositioning the excalidraw embeds in the notes

### ISSUE THREAD

**Issue by KALKI-the-avataar** [zsviczian/obsidian-excalidraw-plugin#4]
# repositioning the embeds
as If now the embeds is default to left side of the pane.
Is there a way to make it float and and wrap text around it.
The behavior some what similar to ambidition blocks.
also can you add a feature to resize images by using syntax like [[exalidraw_example|300]]

**Comment by zsviczian** [comment]
Excellent suggestion, working on it now. 
What are ambidition blocks? googled it, but couldn't find any relevant match

**Comment by zsviczian** [comment]
Solved resizing.
Opened feature request for the text wrapping and floating functionality. See #8
