### ISSUE TITLE
Excalidraw.md files disappearing

### ISSUE THREAD

**Issue by dcoales** [zsviczian/obsidian-excalidraw-plugin#401]
**Describe the bug**
I created a new Excalidraw file and worked on it for a couple of hours.  I have auto save to SVG and Excalidraw turned on with the sync option to keep the excalidraw and .md versions in sync.  Twice now, when I finally close the file I find that the .md file has disappeared and the remaining excalidraw file is very old.  At least an hour or so of work old.  

This has happened twice now.  The first time I thought I must have accidentally deleted the file but now I'm pretty sure it's a bug.
Before I closed the file a second time I forced a PNG export.  The PNG shows how the file should look so everything was fine just before I closed the file.  The automatically created SVG and excalidraw files however are very out of date and the .md file has disappeared for good.

I'm currently using the desktop version of Obsidian at version 0.13.23 and Excalidraw at version 1.5.23

For now I have turned off the excalidraw export option and I'll see if it happens again.

**Comment by dcoales** [comment]
Weirdly I have now found the .md file but it's in the default Excalidraw folder and it isn't up to date but is the same old version as the SVG and .excalidraw file.  This is weird.  I'll keep digging.

**Comment by zsviczian** [comment]
You got me scared! There are a few things I am afraid of more, then causing data loss…
This happened with 1.5.23 or with a version earlier?

In 1.5.23 I added a file backup step in the save process, because I noticed that if you terminate the Obsidian process (i.e. switch apps on the ipad and iOS recycles the memory, or simply close obsidian on the PC without closing Excalidraw first) workspace.on(“quit”) does not always await until the whole save operation is completed. This resulted in half saved files. Thus now, I first make a backup copy before saving. This way you should not lose more than 30 seconds of work.

There is an autosave in the plugin. Every 30 seconds an update should be saved, thus several hours of difference is very strange. It has one side effect: sometimes, when you switch devices i.e. move from desktop to ipad or back, Excalidraw autosave saves a version quicker then sync delivers the files, in those cases you may end up with an older version, but then in sync history you will always find the right version of the file. Could this be the case? Have you looked in sync history?

**Comment by dcoales** [comment]
I've been trying to figure out what might have happened but haven't had
much luck and haven't been able to force repeat it.  Either it's a rare
edge case I happen to have hit upon or I've just made some silly mistake
and done it twice.  The latter is perfectly possible.

Thinking back, the first time this happened was with a file that I
originally created on the Excalidraw website in a shared online design
meeting.  I exported this from the website to my Obsidian vault on my
laptop and then the following day spent a couple of hours working on the
file.  This probably was an old style excalidraw file as I don't recall
upgrading it - although I might have done - so there may never have been a
.md version of this file.  I finished working on the file late at night and
went to bed - I don't recall if I closed the file or Obsidian before going
to bed.  The next day I carried on working in obsidian but as usual started
the day by switching to my "Work" workspace which would have closed any
open files and opened my ToDo and Inbox files.  Later that day I went to
continue working on the drawing and when I opened it looked exactly as it
did when I first downloaded it.  None of the work I had done the previous
day was in the file, nor in the SVG export that went along with it.  I
searched my vault using windows search tools for other excalidraw files
that might contain my work but couldn't find any.  At some point in this
process I will have moved the file from the root directory to a sub-folder
and possibly renamed the file but I couldn't say exactly when I did that.

I then decided to redo the missing work.  So I copied the version I had
into a new file (in the .md format) and worked on it for an hour.  I then
discussed the new version with a colleague, making some more edits, before
closing the file and working on other things.  Later that evening I
re-opened the file and worked on it some more for an hour.  This time,
before closing the file, I decided to export the file to PNG before closing
it because I was feeling a little paranoid.  I then closed the file.  When
I looked in the sub-directory in which I expected to see my files, I
couldn't see a .md file, only the .excalidraw and .svg files - both of
which were as they were after my meeting with my colleague without any of
the changes I had made in the previous hour.  That's when I made the bug
report.  Later I found the .md in the default Excalidraw directory - also
with a .svg file but when I opened it, it too showed the version from just
after my meeting with my colleague.

What I couldn't understand is how the .md file ended up in a different
directory from the .excalidraw file and the .svg file.  Maybe I created the
file in the Excalidraw folder and then moved just the .excalidraw and .svg
version into the sub-folder but not the .md file.

Unhelpfully, I have since remade the edits in a copy of the file, checked
that it saved okay and then tidied up all the old copies which I realise
isn't very useful for determining if this is an actual bug or a user
error.  I have tried to replicate the problem but it hasn't recurred so
perhaps it was just a one-off error.  Anyway, I'll keep an eye out and let
you know if it happens again.

Cheers,
David

**Comment by zsviczian** [comment]
It's been a long time since I tested the import/convert function. I will spend some time trying to break it.

I pretty much always copy/paste from excalidraw.com to Obsidian and vice versa, never save and load. This is maybe why I have not encountered this problem.

**Comment by YesterKo** [comment]
> Excalidraw autosave saves a version quicker then sync delivers the files, in those cases you may end up with an older version, but then in sync history you will always find the right version of the file. Could this be the case? Have you looked in sync history?

Hi! Is it possible to disable it? I'm getting problems with excalidraw reverting things I have wrote or drawn ( about 30 seconds back). The problem started last week, but I haven't used Excalidraw for a long time so the bug could have came in before that.
BTW, this has happened once with the sync addon disabled, too.

**Comment by zsviczian** [comment]
and do you have the drawing open on two devices in parallel?

**Comment by zsviczian** [comment]
I've added two settings in 1.6.3. You can disable autosave. Also, you can change the autosave interval to less frequent.

**Comment by FatsharkGo** [comment]
I got this data loss problem too, no matter how many times I try to `Ctrl + S` or click the save icon on the drawing page，when I switch the document out and in, some elements in the drawing disappeared. The version of obsidian is v0.13.23 and obsidian-excalidraw is v1.6.3

**Comment by zsviczian** [comment]
has this recently happened? Can I close this issue?

**Comment by dcoales** [comment]
This hasn't reoccurred so please go ahead and close the issue.

Thanks
David

**Comment by YesterKo** [comment]
Yep, mine is also fixed.
