### ISSUE TITLE
Auto-embed SVG missing .excalidraw file extension

### ISSUE THREAD

**Issue by luscra0** [zsviczian/obsidian-excalidraw-plugin#409]
**Describe the bug**
When creating and embedding a drawing through the command palette, if you have auto-export to SVG and auto-embed to SVG on, it will create the 'drawingname.excalidraw.md' and 'drawingname.excalidraw.svg' files, however it will try to embed a file called 'drawingname.svg', without the excalidraw extension, which does not exist.

**To Reproduce**
1. Enable 'Auto-export SVG' setting
2. Select SVG on the 'Type of file to insert on document' setting
3. Open the command palette while inside a file
4. Use the 'Excalidraw: Create a new drawing and embed into active document'
5. Draw something

**Expected behavior**
The plugin should embed the file with the correct filename.

**Screenshots**
![image](https://user-images.githubusercontent.com/89718602/152276086-6d4dcd99-7105-47f5-a94b-494a2728b0c2.png)
![image](https://user-images.githubusercontent.com/89718602/152276114-82561944-6e50-4367-be8a-e3dd3b0abbaa.png)

**Desktop:**
 - OS: Windows 10
 - Obsidian version: v0.13.23
 - Excalidraw plugin version: 1.5.29

**Comment by zsviczian** [comment]
Thanks! will fix this soon.

**Comment by zsviczian** [comment]
I just released 1.5.30 which should fix this issue. Thank you for raising!
