### ISSUE TITLE
Update Excalidraw filenames in the embed blocks after renaming them

### ISSUE THREAD

**Issue by Ka-hu** [zsviczian/obsidian-excalidraw-plugin#41]
As the title says. The filenames (or rather paths) in the embed blocks should be updated.

Currently, the filenames are not updated in the embed blocks, so if we rename a drawing, that embedded drawing will stop working (loading).

**Comment by zsviczian** [comment]
Here's 1.0.8-test3. It resolves this issue as well. 
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.8-test3

**Comment by zsviczian** [comment]
1.0.8 release solves this
