### ISSUE TITLE
Can you add a button

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#410]
There are too many scripts, there will be too many shortcut keys, can you add a button for easy selection?
![image](https://user-images.githubusercontent.com/29135984/152368304-123041b1-b218-49b9-8e85-22f534c8d75e.png)

**Comment by zsviczian** [comment]
Yeah, I've been thinking about that. For now, I recommend using the Customizable Page Header buttons plugin.

![image](https://user-images.githubusercontent.com/14358394/152391326-83f4f94a-281e-439c-8d98-6446cb8147d1.png)

**Comment by zsviczian** [comment]
Solved with the Obsidian Tools Panel.
