### ISSUE TITLE
New Link Icons

### ISSUE THREAD

**Issue by phil31753** [zsviczian/obsidian-excalidraw-plugin#418]
Massive fan, but the new link icon results in too much visual clutter on diagrams (see attached). There should be an option to suppress or disable. Alternatively display the icon only when hovering over the element.

![Screenshot 2022-02-09 152357](https://user-images.githubusercontent.com/95326157/153141871-8d1d2efc-7614-4432-aa7b-15c1e1f9535a.png)

The size of the icon is not relative to the zoom setting, resulting in huge icons when zoomed and overly large icons for diagrams that use small text.

When multi-line text is used, the connection between the text block and the icon is not clear, as it is located in the top right corner of the text box (see attached).  In dense diagrams, it is not always clear which item the icon refers refer to.

![Screenshot 2022-02-09 153253](https://user-images.githubusercontent.com/95326157/153143185-e9d4f7a7-ec63-48f1-b3dc-bd4478f6ea37.png)

Have many diagrams, representing many hours of work, that now render in a somewhat ugly fashion. I feel that updates should not change the appearance of a diagram, or at least provide the option to maintain a reference, or default, appearance based on how Excalidraw renders the diagram. Actually this update has sort of broken compatibility with Excalidraw diagrams.

**Comment by zsviczian** [comment]
I am 100% with you, and this is definitely top of my list as well.
As a minor improvement you can set the link prefix to "" in Excalidraw settings. The link icon will still be there though.

**Comment by zsviczian** [comment]
Here's the first change I plan to implement.
See screenshots here: https://github.com/excalidraw/excalidraw/pull/4763
Test it here: https://excalidraw-izmgadz9m-excalidraw.vercel.app/

**Comment by zsviczian** [comment]
I released two improvements in [1.6.6](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.6.6)
- Below 100% zoom level, link icon size is adaptive. As the image size decreases, so will link icons. Above 100% the link Icon size is fixed.
- I added a setting where you can change the opacity of the link icon
![image](https://user-images.githubusercontent.com/14358394/153295236-3e316029-50bf-4688-a540-7eb2534b5295.png)

**Comment by phil31753** [comment]
Thanks.  That's a big improvement and has restored the appearance of my diagrams.

A fine tuning might be to allow positioning of the icon relative to the object. Currently the icon is positioned relative to the top right corner of the object's bounding box. Maybe holding down shift-ctrl to allow positioning anywhere relative to the object (including inside the object's bounding box)?

![image](https://user-images.githubusercontent.com/95326157/153326404-98a5008b-ccfa-4b7f-bad0-a695be338ca6.png)

**Comment by zsviczian** [comment]
I could make it a setting to choose positioning from a could of presets, but then that will apply to all your links. Setting it one by one per link would require lots of customizations compared to the core Excalidraw product.

**Comment by phil31753** [comment]
Understand. Just a suggestion. I may grow to love the link icon as I draw new diagrams differently :)

**Comment by zsviczian** [comment]
I've grown accustomed to the new link icon. The opacity setting and the adaptive sizing solves most of the issues for me. I am closing this for now.
