### ISSUE TITLE
Directly open draw pane by  embed file

### ISSUE THREAD

**Issue by Connor-yang96** [zsviczian/obsidian-excalidraw-plugin#42]
Is possible directly open draw pane by  embed file ?

If I have to edit the diagram when see the note, how the paths to go edit ?

1. ctrl + e , go to edit model. 
2. copy file name, 
3. go to search pane.
4. paste file name. 
5. ctrl + click file.
too long ,too slow

**Comment by zsviczian** [comment]
Good idea. I will investigate how to... I think I can put an event listner on the embedded image, to listen to click events and open the drawing on a new pane.

**Comment by mehmet-safak** [comment]
Yes that would be great! Like: right-click, edit.

Great job with your plugin!

**Comment by zsviczian** [comment]
resolved with Excalidraw 1.1
