### ISSUE TITLE
Mobile view mode for menu when on Desktop

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#423]
as per request from @gitmurf

![image](https://user-images.githubusercontent.com/14358394/153358193-b86e332a-0fb2-414a-a42a-b8e235f5b039.png)

**Comment by GitMurf** [comment]
Thanks for adding this! Next time I will create Issue in GH so you don't have to do extra work :-)

**Comment by zsviczian** [comment]
resolved in 1.6.8 and 1.6.9 (remember tray-mode)
