### ISSUE TITLE
Lost focus when using a Wacom pen on Desktop

### ISSUE THREAD

**Issue by jordansmithsgames** [zsviczian/obsidian-excalidraw-plugin#426]
**Describe the bug**
When using a Wacom pen and tablet (perhaps other pens too) to draw, sometimes the window loses focus, so hotkeys such as CTRL-Z and CTRL-X or the options hoykeys (1-10 number keys) are unresponsive until I use my mouse to click back into the Obsidian window. This is came to my attention when I tried to change the color of the pen, went to draw something, and then tried to undo it, but not being able to undo the drawing.

**To Reproduce**
1. Draw something with a Wacom pen (or maybe another tablet pen setup)
2. With the pen, navigate to the change color option for the pen and change it to something else.
3. Draw something and try to use the hotkey CTRL-Z to undo it
4. You are unable to undo the change or switch to a different option with the number keys

**Expected behavior**
The plugin should maintain focus when using a Wacom pen to draw something, all hotkeys should function without issue when drawing/interacting with the plugin with the pen.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - v1.6.3

**Comment by zsviczian** [comment]
Thanks. I am able to reproduce the issue. I also see, this is not a problem on excalidraw.com. I will investigate

**Comment by jordansmithsgames** [comment]
> I just released 1.6.9. Please confirm this version solves your issue.

Confirmed that the fix works. Thanks for quickly addressing this!
