### ISSUE TITLE
Support for Chinese fonts

### ISSUE THREAD

**Issue by Doslin** [zsviczian/obsidian-excalidraw-plugin#427]
![image](https://user-images.githubusercontent.com/29807388/153552174-4db40451-2e93-4485-bd04-c677b8a8fae0.png)

**Describe the solution you'd like**
The default Chinese font of the tool is not very good. I hope to have a hand-drawn Chinese font
![image](https://user-images.githubusercontent.com/29807388/153552324-5c498a19-8c20-4b0f-91c0-007927d6e80a.png)

**Reference**
https://blog.magicdu.cn/744.html
https://anhoder.github.io/media/excalidraw/

**Comment by zsviczian** [comment]
Are you aware of this?

[![fourtfont](https://user-images.githubusercontent.com/14358394/149659524-2a4e0a24-40c9-4e66-a6b1-c92f3b88ecd5.jpg)](https://youtu.be/eKFmrSQhFA4)

**Comment by zsviczian** [comment]
Can you confirm if the fourth font feature resolves your issue?

**Comment by Doslin** [comment]
Thanks! It works very well
