### ISSUE TITLE
How do I draw Bezier curves on the iPad?

### ISSUE THREAD

**Issue by kazdonkai** [zsviczian/obsidian-excalidraw-plugin#429]
I want to draw a Bezier curve on my iPad, but I can't draw a new curve, as shown in the image.

https://user-images.githubusercontent.com/90127278/153611972-5b8bff7c-4c88-4170-82d5-2cf5db473186.MOV

**Comment by zsviczian** [comment]
select the line tool.
touch the screen with two fingers a bit apart.
click to add new points.
press the "check" button in the bottom left to finish adding points.

**Comment by zsviczian** [comment]
Here's some additional help:
https://twitter.com/dluzar/status/1416841489448046604?s=20&t=fdo3QRv_r5_ibp3V0qpVzg

**Comment by kazdonkai** [comment]
thx. I saw how to do the tweeter and it was easy.

(I think it would be a shame to close this issue.
If you have time, it would be useful for us if you could make a small tip on how to do it on Youtube).
