### ISSUE TITLE
Copy embed file code for embed file.

### ISSUE THREAD

**Issue by Connor-yang96** [zsviczian/obsidian-excalidraw-plugin#43]
when I'm drawing, I want to embed file to a note. 

currently we have to 
1. ctrl + p
2. type  exal
3.  click embed command 

or set shortcut for embed command , press it as step 1. 

4. or 2. find file name in so many files . ( this finding file need to take some time)..

if allow set embed file code or in "..." menu. that will quickly embed .

**Comment by zsviczian** [comment]
I could add a command to embed last active drawing... Then it is a single click (if you have a shortcut)

**Comment by zsviczian** [comment]
I added additional command palette commands in 1.1.4 to create drawings and simultaneously insert a link into the active document.
