### ISSUE TITLE
Getting a lot of sync errors (Obsidian sync) for the drawing.excalidarw.md.bak file

### ISSUE THREAD

**Issue by GitMurf** [zsviczian/obsidian-excalidraw-plugin#432]
**Describe the bug**
As I am drawing I am consistently getting a lot of sync errors (Obsidian sync) for the drawing.excalidarw.md.bak file. See screenshots below. This happens on the ipad and my windows laptop (all devices I have tried)

**Screenshots**

![image](https://user-images.githubusercontent.com/64155612/153724670-704f3052-ef06-4e9f-9eab-90db24a397a1.png)
![image](https://user-images.githubusercontent.com/64155612/153724674-4173f7c8-2e00-4f1b-849c-2777f4e624ae.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 and ios (ipad) 

I am on the newest version of excalidraw v1.6.8

**Comment by zsviczian** [comment]
yes. I noticed. I will release a solution tomorrow. I will name temp bak files starting with a "." (dot). I am hoping sync will ignore then

**Comment by zsviczian** [comment]
solved in 1.6.9
