### ISSUE TITLE
permenant default stroke width change

### ISSUE THREAD

**Issue by ananthuthilakan** [zsviczian/obsidian-excalidraw-plugin#433]
**Is your feature request related to a problem? Please describe.**
any possible way to change stroke width to 0.5 for all elements and drawings for any new drawing i will be creating.

**Describe the solution you'd like**
a setting which allow to change default stroke width in plugin settings

**Describe alternatives you've considered**
i being changing stroke width to 0.5 by search an replace in md file

**Additional context**

**Comment by zsviczian** [comment]
You can achieve this by editing the template for your drawings. Simply change to: `"strokeWidth":  0.5`
Tutorial about setting up a template: https://www.youtube.com/watch?v=ibdS7ykwpW4

![image](https://user-images.githubusercontent.com/14358394/153739814-8a7a43c5-d8be-42ac-8d44-d64eb6728b95.png)

**Comment by ananthuthilakan** [comment]
Great 👍🏻👍🏻
