### ISSUE TITLE
can't export .excalidraw file in obsidian.

### ISSUE THREAD

**Issue by Connor-yang96** [zsviczian/obsidian-excalidraw-plugin#44]
![image](https://user-images.githubusercontent.com/81000027/117138360-7e1adf00-addd-11eb-9aa5-dc0d45b748a8.png)

**Comment by zsviczian** [comment]
How did you try to export? Indeed it is not allowed, this is sandboxed by Obsidian / Electron Browser. I took off the button for export... that's why I am asking where you found this action... will try to hide that as well.

**Comment by Connor-yang96** [comment]
here ![image](https://user-images.githubusercontent.com/81000027/117154729-ba0a7000-adee-11eb-9ff3-90e6c1993a69.png)

**Comment by zsviczian** [comment]
Here's 1.0.8-test3. I hid this button in this update.
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.8-test3

**Comment by zsviczian** [comment]
Can't fix. 1.0.8 release hides the export button.
