### ISSUE TITLE
Freedraw Paramaters as Settings

### ISSUE THREAD

**Issue by Signynt** [zsviczian/obsidian-excalidraw-plugin#440]
Handwriting using Freedraw has now become feasible due to the palm rejection feature, however I still found handwriting to feel awkward and unreliable on iPad. The smoothing feels way too strong, and I get too many errors (for example the top two points of a `U` will often connect). I tried this [perfect-freehand demo](https://perfect-freehand-example-steveruizok.vercel.app) ([GitHub](https://github.com/steveruizok/perfect-freehand)), and immediately found it way more comfortable to use. It would be great if Excalidraw would be able to offer support for a similar style of freedraw, or an option to manually adjust the smoothing of the pen to make it more comfortable!

Weirdly the [demo linked on the GitHub ](https://perfect-freehand-example.vercel.app) does not feel as great as the demo I've linked above 🤔

**Comment by zsviczian** [comment]
Thanks. Great suggestion. It would be best to raise this with the Excalidraw product team. I limit the Obsidian related modifications to the core package to minimum, to ensure the Obsidian community can continue to benefit from the on-going development of the core package. The freedraw feature would need to be developed in the core package. https://github.com/excalidraw/excalidraw/issues

**Comment by zsviczian** [comment]
on a second thought, I will look into the source to see if there are some parameters of freedraw I can make into a setting in Obsidian, so you can customize the ink flow to your needs.

**Comment by Signynt** [comment]
Sure, I've moved the issue over to the core package, but I'll leave this one here and rename it to reflect the FR to have freedraw paramaters available in the Obsidian options. 👍

**Comment by chaecramb** [comment]
I wonder if there's something else other than the stroke option settings going on here. I've been digging around the excalidraw.com repo trying to understand the issue.

On an iPad I'm getting excellent handwriting results on https://perfect-freehand-example.vercel.app/, significant degraded results on excalidraw.com, and even more significantly degraded results on Obsidian Excalidraw. This seems to be a common experience from what I've read.

The issue certainly feels like there's excessive smoothing, but as has been pointed out in a [excalidraw.com issue](https://github.com/excalidraw/excalidraw/issues/4802#issuecomment-1043026597), the stroke options are near identical to the Perfect Freedraw demo, but the results at least for me are definitely not. Perhaps fiddling with stroke options can still improve handwritting, but I wonder if the rendering on excalidraw.com and Obsidian is causing them to miss points entirely while drawing, and so it appears that excessive smoothing is being applied, when actually those points were just never registered in the first place. I'm not sure why this problem would be exacerbated in Obsidian Excalidraw compared to excalidraw.com though.

Perhaps I just don't have enough understanding of the work Excalidraw is doing under the hood, but given the Perfect Freehand demo achieves such nice handwriting results it's tempting to think that should be achievable in Excalidraw somehow.

**Comment by nonoMain** [comment]
hey! any update on this? I really like excalidraw and I use it a lot for diagrams but I'd also like to use it for my math notes as it is amazing with the amount of settings and options for all the shapes and the useful library but the 'auto smooth' makes it really hard to draw small numbers or symbols

**Comment by zsviczian** [comment]
This has been implemented in the mean time. See: Obsidian-Excalidraw 1.8.12 - QoL Improvements: pens, pinned scripts, panning tool, and color picker https://youtu.be/OjNhjaH2KjI
