### ISSUE TITLE
Images imported in scenes disappear next time opening obsidian

### ISSUE THREAD

**Issue by maxime1992** [zsviczian/obsidian-excalidraw-plugin#445]
**Describe the bug**

Excalidraw added support to embed images into a scenes a few months ago.

I've tried using this with the plugin and at first it looked great but when I closed down obsidian and came back to it a little after, I had this:

![image](https://user-images.githubusercontent.com/4950209/154423588-14c954b8-1dba-40d4-98ea-4c4448add302.png)

If I reimport the same image it'll somehow end up in the same spot so it's something! But I can imagine that it'd be hard to deal with when someone has more than 1 image.

**To Reproduce**
1. Create a new excalidraw file anywhere in your vault
2. Click on the button (top right of excalidraw panel) and choose any png or jpg picture
3. It should now show up in the scene
4. Close obsidian
5. Open Obsidian and go back to the excalidraw file
6. You should see the size of the picture but instead of the picture itself the placeholder that I showed at the top

**Expected behavior**
Retrieve images correctly

**Screenshots**
See screenshot above

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Not sure what you mean here because it's running in Obsidian but I've got Chrome and Brave installed

**Additional context**
Thanks a lot for that brilliant tool <3

**Comment by zsviczian** [comment]
hm... I cannot (yet) reproduce the error.
Are there any special characters in the filename or foldername?
After you insert the image, please switch to markdown mode "Open as Markdown". Do you see the link to the image there? Does it open?

> If I reimport the same image it'll somehow end up in the same spot so it's something!
Excalidraw generates the image ID based on the image, thus when you re-import the same image, it will receive the same ID. 

The only issue I was able to reproduce was: if I add an image using the "Insert Image" button, and then immediately terminate Obsidian, then the image does not get saved... but in this case, not even the placeholder is displayed when I reopen Obsidian. But this is a different issue from the one you have raised.

**Comment by maxime1992** [comment]
> Are there any special characters in the filename or foldername?

Not at all. There are some spaces though for example I've got a folder which is "Smart home" so I don't know if you count space character as a special one or not.

> After you insert the image, please switch to markdown mode "Open as Markdown". Do you see the link to the image there? Does it open?

Umh something is odd at that level. In the "Embedded files" section of the document, the image link seems to be incorrect. It's called "pasted image[some number].png". When I ctrl + click onto it, it created a new file at the root of my repo called `pasted image[some number].png` (matching the exact filename from the document). When I open that file it seems to be an empty file :thinking:. 

While now I'm using the load image widget to add my images back, I remember initially that I tried to copy/paste the image directly into the document. Maybe that changes something.

Uuuh ok I'm onto something here. I think I understood what's going on. When adding pics to an excalidraw documents it does copy the picture at the root of the repo, which I don't want. So I thought I could go around this by removing the picture, manually put the png file next to my excalidraw document and then from the document load that image, thinking it'd use the current path.
And this work while you keep obsidian open. As soon as you close it it doesn't. But if you let the image at the top level it's working fine. That said, it'd be quite annoying to have all the pictures from all my excalidraw files at the root of the repo :thinking:

**Comment by zsviczian** [comment]
Excalidraw simply uses your default Obsidian setting to place files.

Moving files (e.g. drag and drop in the obsidian file manager) should be ok as you have the "Automatically update internal links" option enabled.

Obsidian creates a new file when you click a link, in case it cannot resolve the file location. This behavior depends on the `new link format` setting.

![image](https://user-images.githubusercontent.com/14358394/154532358-d8b657b8-a08f-4753-9e1a-ce41ef244248.png)

**Comment by maxime1992** [comment]
Thanks! Didn't know about these options. I've set it to the same as above but still no luck.

I've re-created a new excalidraw document and same behavior. I don't even need to quit Obsidian actually, if I just close top right the current file and open it again the image is gone.

When I look into the markdown I can see the following:

![image](https://user-images.githubusercontent.com/4950209/154649180-67032bb2-13c0-48e3-bef4-0b77e4f70ec8.png)

![image](https://user-images.githubusercontent.com/4950209/154649287-a142c423-f61d-4326-bf2f-9048d9f5d9d6.png)

So the link seems ok to me and I have the file right next to it now

![image](https://user-images.githubusercontent.com/4950209/154649473-46ffe3b6-8485-4939-9cb8-dd79bde6f8db.png)

But same behavior I'm afraid

**Comment by maxime1992** [comment]
What I've noticed: I've been trying to use an image that I had next to my excalidraw file by clicking the import icon on excalidraw UI. Not copy pasting one. 

If I paste a random image in the document it correctly shows up and stay there even after I closed it. BUT, when I copy/paste an image into the document, for some reason I get 2 files locally?

![image](https://user-images.githubusercontent.com/4950209/154649876-2e955822-4d29-4eb2-8e53-a907aeefc5d3.png)

So I think there are 2 issues here:
- Copy pasting an image seems to create 2 images locally
- Importing a file that is already there instead of copy pasting a new one directly into the document only work while the document is open and as soon as it's closed it's not working anymore

**Comment by zsviczian** [comment]
I'll test Excalidraw on Ubuntu over the weekend to see if has anything to do with the environment.
I don't this has anything to do with the issue, but can you confirm your Obsidian version?

**Comment by maxime1992** [comment]
Obsidian version: `0.13.23` _(seems to be latest)_

I tried to open the console, no error whatsoever when opening the document with the broken image

**Comment by zsviczian** [comment]
I am more interested if there is an error when you add the image and close the drawing (i.e. when it does not get saved).

I am running out of ideas... I'll get my hands on an Ubuntu this weekend to see if I can reproduce the error there. If not, I might ask you to join me for a quick zoom call to figure out what is going on.

**Comment by zsviczian** [comment]
I did a number of changes to save. There were some race conditions, which could have led to your experience. Please test 1.6.12

**Comment by maxime1992** [comment]
@zsviczian everything works as expected now :tada: Nice one for the fix! Thanks a lot :smile:
