### ISSUE TITLE
Auto save 

### ISSUE THREAD

**Issue by Connor-yang96** [zsviczian/obsidian-excalidraw-plugin#45]
Auto save drawing without click .

Auto save by when update drawing or 1-3 mins.

Thanks.

**Comment by zsviczian** [comment]
There is no need to autosave, Obsidian does it by itself, however, there was an error with saving in some cases when the file was closed. This is now resolved in 
Excalidraw 1.0.8-test3
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.8-test3

**Comment by Connor-yang96** [comment]
If not auto save . after edited, the embed file didn't update itself. 

![image](https://user-images.githubusercontent.com/81000027/117393389-a104da80-af26-11eb-84e3-56677501ada0.png)

**Comment by zsviczian** [comment]
Real-time update of the rendered image is not desirable as that will eat unnecessary resources. I added an additional feature this morning to save when the drawing loses focus, i.e. when you click on hello the drawing will update.

**Comment by zsviczian** [comment]
1.0.8 release solves this
