### ISSUE TITLE
No Settings for Installed Scripts on Excalidraw 1.6.11

### ISSUE THREAD

**Issue by tchansun** [zsviczian/obsidian-excalidraw-plugin#453]
I reinstalled Excalidraw but still no settings for installed scripts ?

Note that when I activate Excalidraw, it says "Welcome to Obsidian-Excalidraw 1.4"

![image](https://user-images.githubusercontent.com/40065157/154658744-42cfcfa0-1ab8-476e-996d-d0b384964ab4.png)

Although I seem to have the last version:

![image](https://user-images.githubusercontent.com/40065157/154659023-9c2dc40b-fe82-4dfe-af15-ff1720a7525e.png)

On Manjaro Linux, 

Thank you!

**Comment by zsviczian** [comment]
Yes, I should really update the welcome splash screen :)
Script settings only show after the first time you run the script.

**Comment by zsviczian** [comment]
Did starting the script once resolve the missing settings? Can I close this issue?

**Comment by tchansun** [comment]
Yes it does. Thank you

Le dim. 20 févr. 2022 à 23:23, zsviczian ***@***.***> a
écrit :
