### ISSUE TITLE
Script Repository does not open after update

### ISSUE THREAD

**Issue by Hansilein00726** [zsviczian/obsidian-excalidraw-plugin#455]
I cannot open the script repository after last update (today). Looks the same like when it happened last time. Nice weekend.

**Comment by Hansilein00726** [comment]
New update, repository still doesn't open. I am speaking of the Android version with Samsung Tablet S4.

**Comment by zsviczian** [comment]
I also had issues opening the script repository on my Samsung Note 8... but it did open after a little while. It seems that for some reason it is very slow.

I will investigate what might be causing this, however, I want to rework / improve the whole script store experience. I was thinking to address this issue then.

You can manually download scripts and place them in the Excalidraw/Scripts folder (depending on your plugin settings). You can find the scripts here: https://github.com/zsviczian/obsidian-excalidraw-plugin/tree/1.6.14/ea-scripts

**Comment by Hansilein00726** [comment]
I cannot open the script repository on

**Comment by Hansilein00726** [comment]
Curious & thrilled to hear.

**Comment by Hansilein00726** [comment]
Problem solved! I just installed the new update and the script repository is back. From my point of you this issue is resolved.

**Comment by zsviczian** [comment]
Thanks. Great to hear that it is working. I hope to have an improved plugin store available in few weeks time. I have so many ideas... and not enough hours in a day to get everything implemented.

I'll close the issue for you.
