### ISSUE TITLE
Enable Palm Rejections immediately when in Freedraw

### ISSUE THREAD

**Issue by Signynt** [zsviczian/obsidian-excalidraw-plugin#456]
Currently the palm rejection is only turned on after Freedraw is used to actually draw something, however this is pretty impractical, since I would like to lay my hand on my screen before I actually start writing or drawing, so it would make much more sense to activate it as soon as Freedraw is selected.

**Comment by zsviczian** [comment]
I agree. Can I ask you to open this issue on the main Excalidraw product page: https://github.com/excalidraw/excalidraw/issues

**Comment by Signynt** [comment]
Done, I'll close this issue here.
