### ISSUE TITLE
embed svg/png as markdown link - create option

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#457]
Browsing I did find that option which was evading my eyes earlier :) and this appears to solve both SVG by default and editing in Excalidraw. 

Is there any way to make it more native markdown link for embedding as opposed to the wikilink format. My workflow involves for exporting using Typora and wikilink does not work.  I can do this manually but was wondering if this could be an option in the plugin. 

![image](https://user-images.githubusercontent.com/4916255/154342301-2b00a7be-74d7-4e3a-bfad-598947b227e8.png)

_Originally posted by @aravindk100 in https://github.com/zsviczian/obsidian-excalidraw-plugin/discussions/442#discussioncomment-2191238_

**Comment by zsviczian** [comment]
included in Excalidraw 1.6.14

**Comment by aravindk100** [comment]
Awesome, thanks
