### ISSUE TITLE
still warming：only 15 colors （custom color pallet）

### ISSUE THREAD

**Issue by shisunsun** [zsviczian/obsidian-excalidraw-plugin#459]
**Describe the bug**
custom color pallet still warming：only 15 colors

**To Reproduce**
1. set the template
2. creat a new excalidraw file
3. pop up and warming “only 15 colors...” and there's only 15 colors that I can pick

**Expected behavior**
creat a new excalidraw file and allows me  to pick numbers of colors （more than 15）

**Screenshots**
<img width="319" alt="image" src="https://user-images.githubusercontent.com/21273224/154813510-ae4b909a-cfee-4752-b13d-12139c9d5a5d.png">

<img width="250" alt="image" src="https://user-images.githubusercontent.com/21273224/154813728-d2ae7ee9-3a4b-48c3-82f6-fe1a385a063f.png">

**Environment (please complete the following information):**
 - OS including version: [e.g. iOS 15.1, Android 9, Windows 11, etc]
  -   macos Monterey 12.1
 - Plugin version: 
  - excalidraw 1.6.13 
 - Obsidian version: 
  -Obsidian v0.13.23

thank you very much

**Comment by zsviczian** [comment]
This is very, very, very strange. The warning string is no longer even included in the main.js file.
Please restart Obsidian... and let's see if that helps.

**Comment by zsviczian** [comment]
If the problem persists, please download the main.js again from the 1.6.13 release and copy it to the plugin folder.

**Comment by shisunsun** [comment]
> If the problem persists, please download the main.js again from the 1.6.13 release and copy it to the plugin folder.

Thank you and you were right. 
- It was exactly main.js problem that caused the bug.
- This problem is resolved by your wise advice - "download the main.js again from the 1.6.13 release and copy it to the plugin folder".
    - It seems that this file failed to be updated during the plugin update: manifest.json and styles.css were updated (lastest edited date:2022-02-20)except main.js (lastest edited date:2022-01-16).

Thanks again.

**Comment by shisunsun** [comment]
It seems difficult to repeat the problem so I'd better close this issue.
