### ISSUE TITLE
Excaidraw Help Menu overlap with Status Bar

### ISSUE THREAD

**Issue by dvdmtw98** [zsviczian/obsidian-excalidraw-plugin#460]
When using the Minimal Theme with Excalidraw the help icon gets hidden the status bar
The issue could be present on other custom themes as well

Maybe some padding could be added around the help button to make it visible

![excalidraw](https://user-images.githubusercontent.com/31100937/154841086-b44d03d1-774f-42f9-8a6a-35d449601f0e.png)

**Comment by zsviczian** [comment]
Many people find all the buttons and panels intrusive as it takes away space from drawing. For this reason, I've been on a mission on getting these components out of the way (see tray mode for example). If the help button is an issue for you, I recommend adding a custom css snippet of your own or asking the theme developer to add some customization to the minimal theme.
