### ISSUE TITLE
Excalidraw plugin in background slows down obsidian application

### ISSUE THREAD

**Issue by Ares-III** [zsviczian/obsidian-excalidraw-plugin#466]
This appears to be a very new bug. With the plugin enabled in the background, typing in a normal note on obsidian lags a few characters behind. Disabling the extension brings the performance back up.

Plugin version 1.6.14 on Obsidian v.0.13.23

Thank you!

**Comment by zsviczian** [comment]
hm... very strange, I am not experiencing the same. I did implement a change yesterday to address a feature removed in Obsidian 0.13.26... but I am not seeing a negative impact on my end.

when you restart Obsidian is the effect still there?
Also, can you see any errors on the developer console? CTRL+SHIFT+i ?

**Comment by zsviczian** [comment]
I am thinking you might have another plugin that actively modifies documents in the background and triggers excalidraw onModify metadata cache trigger to run...

can I ask you to run the following command in Developer console and share the result with me?
`console.log(app.plugins.enabledPlugins.join("\n"))`
![image](https://user-images.githubusercontent.com/14358394/154930221-a4e2ebb4-2142-4ee7-b022-870abc08c923.png)

**Comment by zsviczian** [comment]
Can you try to replace your main.js in the .obsidian/obsidian-excalidraw-plugin folder with this one and then restart Obsidian? Is the performance better?
BTW. how many excalidraw files do you have in your vault.
Do you extensively use yaml frontmatter metadata in all your documents?
How large is your vault, how many files (approximately is enough)?

[main.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/8108305/main.zip)

**Comment by zsviczian** [comment]
There was a problem with the code. I corrected it. Not sure if that was causing the performance impact though...

**Comment by Ares-III** [comment]
Thanks for following up. I downloaded the update, restarted Obsidian, and the performance impact is gone. Not sure what you fixed, but it seemed to do the trick. Thanks!
