### ISSUE TITLE
SHIFT+Drop to insert images on Mac

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#468]
Here are payloads for CTRL+drop and SHIFT+drop. For CMD and ALT modifier keys there is no event received. In order to be able to use CTRL modifier key, it has to be pushed after `drag` event, otherwise CTRL+left mouse opens context menu in file  explorer. Also SHIFT+drag does not work in this order. It has to be first drag and then SHIFT.

![image](https://user-images.githubusercontent.com/1130547/154941463-3b2e830d-a404-49a2-b8da-92bfb041dcaa.png)

Using SHIFT to insert images would be great solution.

_Originally posted by @miluoshi in https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/304#issuecomment-1046749620_

**Comment by zsviczian** [comment]
@miluoshi, run this in developer console:
`ExcalidrawAutomate.onDropHook = (data) => {data.event.metaKey=data.event.ctrlKey=data.event.shiftKey; return false;}`
then try to shift drag an image onto the canvas. Did it work?

**Comment by miluoshi** [comment]
> @miluoshi, run this in developer console: `ExcalidrawAutomate.onDropHook = (data) => {data.event.metaKey=data.event.ctrlKey=data.event.shiftKey; return false;}` then try to shift drag an image onto the canvas. Did it work?

Yes, this works

**Comment by zsviczian** [comment]
the change will be included in 1.616

**Comment by miluoshi** [comment]
Great, thank you!
