### ISSUE TITLE
Organic line script doesn't seem to work

### ISSUE THREAD

**Issue by tchansun** [zsviczian/obsidian-excalidraw-plugin#469]
I draw a line with free draw and run organic line script (from the command palette or from a button)  and nothing happens : the line is not changed, as if I had done nothing ?
I reinstalled the script but with no success.
Thank you.

**Comment by zsviczian** [comment]
This will require a bit of investigation... 

And you are using the latest Excalidraw version (1.6.15)?
Maybe just the effect is not visible, did you try to make the line thicker?
Can you try to click save after you run the "organic line" script, did that make a difference?
What if you switch to another file and back, is the line updated?

**Comment by tchansun** [comment]
Excalidraw 1.6.15
Make  the line thicker has no effect, as well as saving after running the script, or switching back and forth to another file.
I am on Linux by the way.

**Comment by zsviczian** [comment]
Do you see an error message on developer console (CTRL+SHIFT+i)?
Do other scripts work?
Just to be sure, can you open the script in Excalidraw/Downloads/Organic Line.md and take a look that it looks ok. i.e. the file is there and it has proper content?

**Comment by tchansun** [comment]
I got this error :
![image](https://user-images.githubusercontent.com/40065157/154984610-7518da1b-46e9-4bf9-ae7a-4390fea3074e.png)
And the code in the file is 
![image](https://user-images.githubusercontent.com/40065157/154984826-76507888-b389-4e1d-91d4-3a6cd2ce0e94.png)

**Comment by zsviczian** [comment]
Can you click VM114:48 in the error message and send me a screenshot?

**Comment by tchansun** [comment]
![image](https://user-images.githubusercontent.com/40065157/154986480-d7523f2b-92c0-46b0-af9c-38059d8f25ba.png)

**Comment by zsviczian** [comment]
And please confirm that you have the opening comment block /* above your screenshot at the start of the document.

**Comment by tchansun** [comment]
Which document ?

**Comment by zsviczian** [comment]
> Which document ?
`Excalidraw/Downloads/Organic Line.md`


also, let's see if the script is started at all:
can you edit the script by adding the `debugger;` command as the first line, see the image as example:
![image](https://user-images.githubusercontent.com/14358394/154987092-73513e74-fe9d-4e5f-96cd-87114d1a5abc.png)
Then start the script with the developer console open on the side. Did the script stop? if yes, please use F10 to execute the script step by step, to see on which line it breaks.

**Comment by tchansun** [comment]
Yes there is a /* at the top.
I have a prompt after running the script. Pressing F10 has no effect ?

**Comment by tchansun** [comment]
![image](https://user-images.githubusercontent.com/40065157/154989567-1abdb2bd-9429-4d50-b8fe-5f4a76018df3.png)

**Comment by zsviczian** [comment]
This is how it should look, and that is the button to press. On windows, the shortcut is F10, maybe it is different for you.
![image](https://user-images.githubusercontent.com/14358394/154990400-d880b35e-a66d-4a63-bed4-55f1567d9e6f.png)

**Comment by tchansun** [comment]
See line 3 : "# Organic Line"
![image](https://user-images.githubusercontent.com/40065157/154991482-d9c9e3e8-f7a7-421c-a326-0889fe854711.png)

**Comment by tchansun** [comment]
Yes, it was the Obsidian Filename Heading Sync plugin. I excluded the Excalidraw directory and reinstalled the script and it works now !
Thank you for your help !
