### ISSUE TITLE
[Bug] Weird behaviors in file naming

### ISSUE THREAD

**Issue by Elaws** [zsviczian/obsidian-excalidraw-plugin#470]
If I understood correctly, drawings are named as follows :

`{prefix}(optional) {note name}(optional) {date}.excalidraw`

I noticed several weird behaviors :

1. {prefix} never appears in my drawings name (no matter if `Filename prefix for embedded files` is on or off).
2. If I write nothing in "date" and in "prefix" (but `Filename prefix for embedded files` is on), I get the following error when trying to create a drawing (the note name is simply "Workbench", without special characters) :

```Uncaught (in promise) Error: File name cannot contain any of the following characters: * " \ / < > : | ?```

So, you can't have a filename as follows :

`{note name}.excalidraw` (with a number that would be appended and incremented if there are several drawings in a given note).

3. When creating drawing with the same name, drawing is saved as :

`{filename}.excalidraw_0` instead of `{filename}_0.excalidraw`

More generally speaking, it would be great if your plugin allowed a more flexible file naming. For example, use the following variables in any order, and all optional :

- ${note name}
- ${custom expression}
- ${date}

Thanks for your feedback on this issue !

**Comment by zsviczian** [comment]
I resolved most of the points you mention and added more flexibility in 1.6.18. Will be released tomorrow.
