### ISSUE TITLE
[Mobile] Back gesture tight space

### ISSUE THREAD

**Issue by Elaws** [zsviczian/obsidian-excalidraw-plugin#471]
On mobile, once a drawing is opened, back gesture can be triggered but only from the thin border around the drawing which is a bit tricky.

Maybe displaying the mobile toolbar would help for that. Or adding a button to go back to previous note (or next)

Thanks !

**Comment by zsviczian** [comment]
Yes, I realize that. It was a tradeoff between having the full screen available for drawing and access to Obsidian features. I may make this a plugin setting. I left a 1px margin to still provide a way for gestures.

Until I find a proper solution, you can install the customizable page header plugin from the app store to add a back button to navigate to the previous page.

**Comment by Elaws** [comment]
Oh ok ! Well, this is already great that you allowed the back gesture, it helps a lot.

**Comment by zsviczian** [comment]
In 1.6.16 you can swipe on the tools panel to open the slide-in panes. Is that a good enough solution for this problem?
https://youtu.be/gMIKXyhS-dM?t=54

**Comment by Elaws** [comment]
Thanks for the update, this is a nice feature, it will ease things a bit !

**Comment by zsviczian** [comment]
is this still an issue, or with the Obsidian Panel the solution is fit for purpose?

**Comment by Elaws** [comment]
Hello @zsviczian, sorry I forgot to close this request. Thanks again !
