### ISSUE TITLE
Make mousewheel zoom by default

### ISSUE THREAD

**Issue by nousernameavailableanymore** [zsviczian/obsidian-excalidraw-plugin#474]
Is it possible to add an option for making zoom the default behavior for mousewheel (changing ctrl + wheel for scroll)?
Many other programs offer similar settings, so this would be a great addition.

Thank you.

**Comment by Ampa** [comment]
Came here to ask for the same enhancement.

Muscle memory is so strong from all my other drawing software!

**Comment by zsviczian** [comment]
Sorry for having you wait this long for this feature. I will release this as an option in 1.8.11.
