### ISSUE TITLE
Tools Panel Mouse Dragging: floats to right bottom screen

### ISSUE THREAD

**Issue by thomasdick-tortuetec** [zsviczian/obsidian-excalidraw-plugin#493]
**Describe the bug**
When opening the Tools Pandel and click-moving it with the Mouse, the panel moves to the right, bottom direction of the screen.

**To Reproduce**
1. Open a new Excalidraw Drawing and click on the Tools Panel
2. Try clicking on the 3 stripes on the panel top and moving the panal around
3. When moving the mouse, the panel will tend moving to the bottom right direction

**Expected behavior**
Usual move of panel with the mouse indicator.

**Environment (please complete the following information):**
 - OS including version: Win11
 - Plugin version: 1.6.1
 - Obsidian version: v0.13.23

**Comment by zsviczian** [comment]
I tried the steps described above, but I can reproduce. Can you send a screen recording to make sure I understand the issue correctly?

Do you use any plugins that modify the layout of Obsidian (e.g. sliding panes?). What theme are you using?

**Comment by thomasdick-tortuetec** [comment]
Thank you for creating this very helpful plugin!
1. I deactivated all community plugins. Then still the problem persists.
2. I switched to the default theme, then the problem disappears. When using the Cybertron or LYT Theme, the problem re-appears.

**Comment by zsviczian** [comment]
as a first next step, please raise this issue with the developer of these themes

**Comment by zsviczian** [comment]
I did some testing of my own. I was able to reproduce with the LYT theme (@nickmilo), but not with the Cyberton theme.

**Comment by thomasdick-tortuetec** [comment]
Yes, you are right, there is no problem with Cybertron theme.

**Comment by zsviczian** [comment]
I am closing the issue here, as I cannot do much with it in Excalidraw.
