### ISSUE TITLE
Excalidraw file type on embed doesn't include fills in read mode

### ISSUE THREAD

**Issue by timmcd** [zsviczian/obsidian-excalidraw-plugin#495]
As a note, I also use Ozan's Image in Editor Plugin.

With an embedded .excalidraw (![[xyz.ecalidraw]]), fills show up in edit mode. But if I switch to view mode, all fills are lost. Lines and everything else look fine. This persists to PDF exports as well.

If instead I set up the plugin to use the auto-exported PNG, fills show up just fine. SVG has the same issue as above.

Hopefully I'm just missing something!

![image](https://user-images.githubusercontent.com/112259/156507813-8a8fe5c5-9d6e-4f0c-9917-10903d4469af.png)

![image](https://user-images.githubusercontent.com/112259/156507861-bac195dc-f0b3-490e-9b68-2871b1bbba39.png)

**Comment by zsviczian** [comment]
Thanks, yes, this is already on my list : #443 
I haven't yet found the time to investigate.
I am going to close this issue and handle it under #443
