### ISSUE TITLE
Bug with the edit panel when trying to edit the text inside a sticky note

### ISSUE THREAD

**Issue by nicolasmarc1** [zsviczian/obsidian-excalidraw-plugin#496]
Hi, I'm no longer able to access the edit panel for the text inside sticky notes.

1. Create a rectangle
2. double click in the center, to create a sticky note, and add text
3. try to click on the "edit" panel
-> if the edit panel was not open, clicking on the edit panel will make the edit panel icon disappear
-> if the edit panel was already open, you can see the edit option for the text inside but you when click on a option/value, the panel disappear

**Environment (please complete the following information):**
 - Windows 11
 - Plugin version:  last one released, 1.6.16

I also made a video demo, you can't see the text because it has th same color as the box and i can't change it because of this problem but you can see the red underline of the spelling check at least.

https://user-images.githubusercontent.com/51007222/156579165-f04190fa-17ce-4fe5-bec4-538d53e135cd.mp4

Thank you!

**Comment by nicolasmarc1** [comment]
also not sure if it's linked but the stroke of the containing box seems to be also used for the stroke of the inner text of the sticky note: if i put transparent to remove borders of the containing box the inside text disappear as it also get stroke as transparent (that's why on the demo we can't see the text)

**Comment by zsviczian** [comment]
this seems to be an issue with the Excalidraw package. I raised an issue with the team: [#4863](https://github.com/excalidraw/excalidraw/issues/4863)

There are two workarounds you can apply now.
1) switch from tray mode to normal more and change the color
2) instead of clicking the color selector, click the edit box next to the color and type in the color you want (e.g. black, blue, white, etc.)

**Comment by nicolasmarc1** [comment]
> this seems to be an issue with the Excalidraw package. I raised an issue with the team: [#4863](https://github.com/excalidraw/excalidraw/issues/4863)
> 
> There are two workarounds you can apply now.
> 
> 1. switch from tray mode to normal more and change the color
> 2. instead of clicking the color selector, click the edit box next to the color and type in the color you want (e.g. black, blue, white, etc.)

Thanks, stopping the tray mode, worked for me

**Comment by zsviczian** [comment]
This is resolved in 1.6.18. I will release tomorrow.
