### ISSUE TITLE
Link to another element in the same drawing

### ISSUE THREAD

**Issue by gmkado** [zsviczian/obsidian-excalidraw-plugin#498]
**Is your feature request related to a problem? Please describe.**
Not sure if this is already a feature, but can you create a link from one element to another within the same drawing?  I have large diagrams that I'd like to be able to jump between elements.  I tried block references but doesn't seem like I can assign a block id to an element.

**Describe the solution you'd like**
Block links would make sense to me, not sure what technical hurdles there are.

**Comment by zsviczian** [comment]
Block links are a good idea. I will explore how I can make this a reality.

**Comment by gmkado** [comment]
awesome thanks!  great work on this plugin btw!

**Comment by zsviczian** [comment]
I've included this feature in 1.6.17.  I expect to release 1.6.17 later today.
You now have two ways to reference items within the canvas, or pointing to another canvas:
1) You can reference text headings on your canvas like headings in a document
i.e. you have a text element that includes a valid markdown heading:
```markdown
# My Heading
details...
```
or 
```markdown
text element text
# my reference
```
You can reference these like this respectively: `[[#My Heading|display alias]]` and `[[#my reference|alias]]`

![image](https://user-images.githubusercontent.com/14358394/156890231-5a23bcb3-40a4-4ad7-b366-74c328620159.png)

2) using element id
- I will add a button to the Obsidian Tools Panel to get the link to any single element on the page
- links will take this form `[[#^elementID|alias]]`

**Comment by zsviczian** [comment]
got bogged down with another issue. I will release 1.6.17 tomorrow.
