### ISSUE TITLE
CTRL+C not working on LINUX?

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#501]
![B5FD3385-1021-4F4D-93D8-0543D5734699](https://user-images.githubusercontent.com/14358394/156637510-d4fa5961-7db4-4121-be1c-8faefff52399.jpeg)

**Comment by zsviczian** [comment]
I just tested this on Ubuntu 20.04.3 LTS x86_64 and I wasn't able to reproduce your error.

**Comment by zsviczian** [comment]
Keyboard handling is a difficult problem (this is an understatement, for: it is a MESS) due to the differences between national and other keyboard layouts and differences in keyboard behavior between operating systems. This issue is in turn exacerbated by how different browsers (chrome, firefox, safari, etc.) have implemented related javascript API functions.

To identify if this is an Obsidian plugin issue, or a problem that should be addressed in the core excalidraw product, can you confirm if CTRL+C works for you on https://excalidraw.com?

Obsidian runs on an Electron browser, which is essentially a chrome browser. When you test excalidraw.com, please let me know what browser you were using.

**Comment by suuuehgi** [comment]
Hey zsviczian!


Thank you so much for opening the issue for me!

I just noticed that the issue is related to the vim mode of Obsidian.

On Ctrl+C, my (vanilla) Obsidian leaves Insert Mode - probably before the copying happens.
This should not happen.

Ctrl+X/V works fine.

CTRL+C works on the plain-text interface as well as on https://excalidraw.com/ using Firefox.

**Comment by zsviczian** [comment]
That is good news. Obsidian has a way to override hard coded shortcuts.. I just use this sparingly, because it is to some extent a hack (albeit recommended by the Obsidian devs). I will add CTRL+C to the list.

**Comment by suuuehgi** [comment]
Cool, thank you so much!

Can you reproduce it on your machine?

And do you know what shortcut Ctrl+C is?

**Comment by zsviczian** [comment]
I haven't tried to reproduce yet. Frankly I am not familiar with vim mode.

**Comment by suuuehgi** [comment]
> I haven't tried to reproduce yet. Frankly I am not familiar with vim mode.

`i`: Enter Insert Mode
`Esc`: Leave current mode

If Ctrl+C leaves Insert Mode, then it should be present.

**Comment by zsviczian** [comment]
I just tested this on windows. Vim mode had no effect on CTRL+C in Excalidraw. I'll try to get my hands on a Linux PC over the weekend to see if I can reproduce the error.

**Comment by suuuehgi** [comment]
What should I now do about it? It's only present within Obsidian.
