### ISSUE TITLE
Background color for the document is not preserved

### ISSUE THREAD

**Issue by alanalvarado** [zsviczian/obsidian-excalidraw-plugin#503]
**Describe the bug**
I customize the color of the drawing, when reopening the file the bg color has been reset

**To Reproduce**
1. Create new diagram
2. Set the bg color for the document
3. create any drawing
4. exit the app, change focus of the document
5. reopen the document, now the bg color has been reset to the default

**Expected behavior**
preserve customization of the work environment

**Environment (please complete the following information):**
 - OS macOS Monterey 12.1
 - Plugin version: 1.6.16
 - Obsidian version: 0.13.23

**Comment by zsviczian** [comment]
yes, I noticed as well just recently... Excalidraw will preserve the bg-color if you click the save button, only Excalidraw does not "notice" if you only change the bg color. I will see how I can fix this.

**Comment by zsviczian** [comment]
fixed in 1.6.17. Will release tomorrow.
