### ISSUE TITLE
"Could not open ScriptEngine repository" error

### ISSUE THREAD

**Issue by nicolasmarc1** [zsviczian/obsidian-excalidraw-plugin#504]
When i try to click on the "Install or update Excalidraw scripts" button, i get this error message "Could not open ScriptEngine repository".
I'm on windows with the 1.6.16 version of the plugin.

Thanks!

**Comment by zsviczian** [comment]
Does this link work for you?
https://raw.githubusercontent.com/zsviczian/obsidian-excalidraw-plugin/master/ea-scripts/index-new.md

Can you try again, and if you get this error again then send me a screenshot of the "console" tab of the developer console? You can open the developer console with CTRL+SHIFT+i

![image](https://user-images.githubusercontent.com/14358394/156736676-5c440098-431c-4e09-95df-47da957b1fa9.png)

**Comment by nicolasmarc1** [comment]
> Does this link work for you? https://raw.githubusercontent.com/zsviczian/obsidian-excalidraw-plugin/master/ea-scripts/index-new.md
> 
> Can you try again, and if you get this error again then send me a screenshot of the "console" tab of the developer console? You can open the developer console with CTRL+SHIFT+i
> 
> ![image](https://user-images.githubusercontent.com/14358394/156736676-5c440098-431c-4e09-95df-47da957b1fa9.png)

Hi,
not the sure i understand what to do with the link you sent me but anyways it's working now!

**Comment by Ahmed-mo-rizk** [comment]
I have the same issue, i turned off the image caption plugin and it worked 

[Image caption plugin link](https://github.com/bicarlsen/obsidian_image_caption)
