### ISSUE TITLE
Paste Style does not work with keyboard shortcuts

### ISSUE THREAD

**Issue by Missionary2112** [zsviczian/obsidian-excalidraw-plugin#506]
**Describe the bug**
I can copy style using keyboard shortcuts (option + command + C), but I cannot paste style with the shortcut (option + command + V)
However, it does work when I right-click and choose the option in the popped up menu

**To Reproduce**
1. Use keyboard shortcut (option + command + C) to copy style
2. Use keyboard shortcut (option + command + V) to paste style
3. See error: Cannot paste style

**Expected behavior**
It should paste style as it would when right-click and choose the option to paste style

**Environment (please complete the following information):**
 - OS including version: macOS Monterey Version 12.2.1
 - Plugin version: Version 1.6.17
 - Obsidian version: v0.13.29

**Feature Request**
- It would be great if I could also copy the text style. At the moment, Excalidraw would only allow to copy the shape style.

**Comment by zsviczian** [comment]
To identify if this is an Obsidian plugin issue, or a problem that should be addressed in the core excalidraw product, can you confirm if this works for you on excalidraw.com?

**Comment by Missionary2112** [comment]
Yes, I just replicated the same issue from the https://excalidraw.com.

**Comment by zsviczian** [comment]
I'd propose opening a ticket for this on Excalidraw's GitHub. What keyboard layout you are using, the type and version of the web browser, etc.

**Comment by Missionary2112** [comment]
I use Safari and the magic keyboard from MacBook Pro 2019.

**Comment by zsviczian** [comment]
It looks like this issue needs to be addressed in Excalidraw, not the Obsidian plugin.
