### ISSUE TITLE
Set the default number of characters for a block references newline

### ISSUE THREAD

**Issue by MILKMILKKING** [zsviczian/obsidian-excalidraw-plugin#508]
Set the default number of characters for a block references newline, ! [[myfile#^blockref]]{xx} 

Can a new default option be added to set the default newline characters for block references. Currently I need to type ! [[myfile#^blockref]]{20} is a bit annoying.

This is a great plugin! Thanks for all your hard work!

**Comment by zsviczian** [comment]
I can, however, you might consider using the `![[myfile#^blockref]]` inside a sticky note, then text wrapping will be automatic, and can be resized with the container as desired.

**Comment by MILKMILKKING** [comment]
This is a very good way to go, thanks! However, I found that inserting a block reference into a sticky note has to be placed relatively in the middle for it to embed smoothly. (Sometimes not placed in the particular middle, the embedding is not completed)
Still very much appreciated, and it works perfectly for my use!
Direct insertion of block references just to be lazy, and a specific number of words of the line break, can not achieve similar to put in the sticky notes can be customized in the form of size, but rather rather dull. I think it is possible to close this problem.
