### ISSUE TITLE
Move side option panel

### ISSUE THREAD

**Issue by RodrigoValente97** [zsviczian/obsidian-excalidraw-plugin#510]
Hi!, First of all, excellent plugin!!!! it's perfect to think while drawing!!!

I am left-handed and the side panel (with the colour and shape options) is in a terrible place where I try to write or draw on my laptop. There is a simple way to move that panel?

**Comment by zsviczian** [comment]
I raised a request for this with Excalidraw.
If you switch to Tray-Mode, then you can use this css snippet to move the tools panel to the right.

1) Download and unzip this [file](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/8204584/excalidraw-tray-lefthanded-mode.zip)
2) Copy the `excalidraw-tray-lefthanded-mode.css` file into the `.obsidian/snippets` folder
3) Open settings/appearance and enable `excalidraw-tray-lefthanded-mode`
![image](https://user-images.githubusercontent.com/14358394/157208686-dfff51aa-a96d-4597-8164-2ad7f787499e.png)
4) Switch to tray-mode
![image](https://user-images.githubusercontent.com/14358394/157208312-264e9fff-c0b6-4970-b850-c02c6475eefd.png)

**Comment by zsviczian** [comment]
I added basic support for left-handed users in 1.6.18. You can enable left-handed mode in plugin settings under the "Display" section. Currently, only affects the position of the elements tray in tray-mode.

I will release 1.6.18 probably tomorrow.
