### ISSUE TITLE
Use ellipsis instead of clipping for transcluded documents

### ISSUE THREAD

**Issue by charleshan** [zsviczian/obsidian-excalidraw-plugin#516]
I thought excalidraw wasn't pulling the latest changes for transcluded documents. Maybe they were cached or something... After going through the excalidraw settings, I found "Page transclusion max char count: 200" which was the source of the problem. Simply adding `text-overflow: ellipsis` or some equivalent would fix this issue.

**Comment by zsviczian** [comment]
I am not convinced that it is this simple, but I will take a look. 
Elements are painted on the canvas, and their canvas is cached. When you edit the text element it is temporarily replaced with a text area, but when the edit is finished, only the cached canvas is displayed.

**Comment by charleshan** [comment]
Gotcha. I might have underestimated the work required 😅

Keep up the good work!
