### ISSUE TITLE
Support [[link]] suggester when editing Text Elements

### ISSUE THREAD

**Issue by red-co** [zsviczian/obsidian-excalidraw-plugin#518]
- Obsidian's editor can supplement the contents of [[]] and is easy to add obsidian link and text blocks,
Could support it?
Thank you very much for your work，(｡･ω･｡)ﾉ♡

**Comment by zsviczian** [comment]
This is on my longer term plans, but not a short term priority. You can use the command palette action to insert a link from your Vault. you can also drag and drop links.

**Comment by Contrigra** [comment]
First of all, it is my first time participating in some discussion on github, so sorry, if it's an inappropriate place. 

Without this feature, it's basically impossible to link to specific lines or blocks of texts, unless you use headings for everything. As I understand, Obsidian creates links to specific lines on its own and provides autos-uggestions by doing this way. 

Unfortunately, command palette action to insert a link lacks such feature. 

![image](https://user-images.githubusercontent.com/60583667/183152075-41d87e7c-7246-406d-93f9-c13da8f8b105.png)

Excalidraw, seems to render links correctly, even though you have to create them manually. By manually asigning adress to these lines, and then reference them in Excalidraw. 

![image](https://user-images.githubusercontent.com/60583667/183153799-fa738450-6345-4585-90c8-635d5868b0cc.png)

**Comment by zsviczian** [comment]
Yes, this would be an absolutely great feature to have. Transclusions should work both for text elements as well as when you are embedding a markdown document as an image. 

I pretty much always create block references manually, even in markdown. For example I keep quotes, one quote per file, and all the quotes have the block reference `^q` so this is easy to remember. 

Block references can be any sequence of characters, so it is pretty easy to come up with your own naming conventions for them. If you have naming conventions, then it is not that hard to manually create the references in Excalidraw.

You have two alternatives.
1) you can create a text element, then switch to Markdown view of the Excalidraw drawing, there the link/block suggester will work.
2) you can create the link in another markdown document and copy the ready link to Excalidraw.

**Comment by zsviczian** [comment]
Scribble helpers solves this. See https://youtu.be/BvYkOaly-QM
