### ISSUE TITLE
[Feature request] - markdown embed settings in frontmatter

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#519]
specify if drawing should be embedded/exported with background color or transparent, in dark mode or light mode. would override plugin settings.

**Comment by zsviczian** [comment]
I will release this in 1.6.20
`excalidraw-export-transparent: true`
If this key is present it will override the default excalidraw embed and export setting. true == Transparent / false == with background. 

`excalidraw-export-dark`
If this key is present it will override the default excalidraw embed and export setting. true == Dark mode / false == light mode.

`excalidraw-export-svgpadding`
If this key is present it will override the default excalidraw embed and export setting. This only affects export to SVG. Specify the export padding for the image.

**Comment by zsviczian** [comment]
Implemented in 1.6.20

**Comment by mavam** [comment]
Is there method that "syncs" the export with the current Obsidian mode? When Obsidian is in light mode, I'd like to see the light mode version of the excalidraw, and when Obsidian is in dark mode, only then I'd like to set `excalidraw-export-dark: true`.

So what I'm actually looking for is something like `excalidraw-export-dark: auto` that does The Right Thing based on how my Obsidian looks.

**Comment by zsviczian** [comment]
`excalidraw-export-dark: true` overrides other settings. If you don't have this setting at the file level then the setting under Embed & Export: `Excalidraw preview to match Obsidian Theme` will achieve what you are looking for.

You may also want to play with settings under Display. The display settings effect how Excalidraw opens a drawing for editing. Again, the frontmatter key overrides the effect of these.

**Comment by mavam** [comment]
Perfect, the settings have everything I was looking for. Thanks!
