### ISSUE TITLE
Clickable SVG where boxes are buttons...

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#53]
https://discord.com/channels/686053708261228577/840286238928797736/840645214246142003

**Comment by tinyheero** [comment]
This would be an amazing enhancement!

**Comment by zsviczian** [comment]
Auto-generate image map using the links in drawings.

**Comment by zsviczian** [comment]
solved in [1.6.16](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.6.16)
