### ISSUE TITLE
Is there a way to link to canvas elements from other notes?

### ISSUE THREAD

**Issue by nicolasmarc1** [zsviczian/obsidian-excalidraw-plugin#530]
Hi, 

I tried the features to link to canvas elements from the same note/drawing and it works great. But is there a way to do it from other files too?

I tried the [[note#headerFromDrawing blockIDFromTextFile]] syntax suggested when you search with [[note#, and i tried also the  [[note#headerFromDrawing]] and [[note#^blockIDFromTextFile]] syntaxes but none are working.

The alternative is to use search or refactor the drawing in smaller drawing inserted back in the bigger drawing and link to these smaller drawing like frames. So it's not a big need, just curious to know if it's possible to do without too much hassle for you?

Thanks

**Comment by zsviczian** [comment]
This should work. Here's my demo. Let me know if I misunderstood something.
There is another issue, that links don't convert into parsed links after paste... but that has nothing to do with the linking capability.

https://user-images.githubusercontent.com/14358394/158531898-f3150a92-f704-4091-b62d-cf6c45514b6d.mp4

**Comment by red-co** [comment]
At least it's valid to link to text, and if you want to link to a drawing element, you might use a workaround like "name the drawing element" to locate it.
hope it can help you,

**Comment by zsviczian** [comment]
I did one more test linking from one drawing to a section heading. That seems to work as well...

https://user-images.githubusercontent.com/14358394/158891901-954a5830-93bd-46d0-bbed-823f57ea3f6a.mp4

**Comment by zsviczian** [comment]
@nicolasmarc1, I think all the linking scenarios work. Even some very special cases... see this example: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/535#issuecomment-1075490125

Have I answered your issue, or am I misunderstanding something? Can I close this issue?

**Comment by nicolasmarc1** [comment]
> @nicolasmarc1, I think all the linking scenarios work. Even some very special cases... see this example: [#535 (comment)](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/535#issuecomment-1075490125)
> 
> Have I answered your issue, or am I misunderstanding something? Can I close this issue?

Hi, sorry for the delay.

This is weird because sometimes it feels like it work and then it doesn't. Every test seems to differ that's why it took time to reply. Seeing the other ticket you linked i retested and understood some of the problems that might have been occurring:

- 1: I was surprised that you managed to make your header "# toc" without it getting an appended block id renaming the header as "# toc ^bMIA00N9"  in the other example you linked so i did some more tests. That's because i was trying to only put the header in the element so the block id was appended to my header unlike in your example where you added bullets below. I needed to add a line break! Maybe adding a line break in the file by default for the block id would remove some confusion?
- 2: Another problem happened when headers have similar names (ex "# frame", "# frame 1") as the link will open on the area between these 2 header elements, the same way it does when you make a text search. I thought that you were using the block id to zoom on the element, not sure why it seems to look at text ?

Thanks!

**Comment by zsviczian** [comment]
Thanks. This is very helpful. I think I can resolve these.

**Comment by zsviczian** [comment]
> # toc ^bMIA00N9

This is not an issue in Excalidraw because I first read the text from markdown into the text elements and read the value from the text elements, thus ^blockref is not there when I search for the match.

Changing this such that the block reference is in the next line would cause backward compatibility issues. I'd rather not touch that, because that comes with lots of complications.

When you want to link, you can always create `# Toc` elements such that you add an empty line after. I understand this is not perfect, but I also don't feel that this is such a major inconvenience.

> when headers have similar names (ex "# frame", "# frame 1") as the link will open on the area between these 2 header elements

I've resolved this in 1.6.21. I will release it later today.
