### ISSUE TITLE
Layers and Actions buttons in floating left menu are inline instead of block on Tablet (Island.App-menu__left)

### ISSUE THREAD

**Issue by neurosock** [zsviczian/obsidian-excalidraw-plugin#532]
**Describe the bug**
The buttons on the 'Layers' and 'Actions' elements are vertically organized instead of next to each other. Makes it really hard to delete items on tablets using the trash can button as one has to scroll down every time to find it.

**To Reproduce**
1. Open Excalidraw in an S7 tablet

**Expected behavior**
As in desktop, the buttons on Layers and Actions are next to each other instead of vertically aligned

**Screenshots**
This can be seen in a previous video by @MrGerrit
https://photos.app.goo.gl/eTqERZE6RkTSTPgc9

**Environment (please complete the following information):**
 - Android 11, Obsidian App 1.0.5

**Additional context**
This doesn't happen if opening Excalidraw in a regular Chrome browser tab on the same tablet. Also not on Desktop even if the screen is resized or with simulated screen sizes like IPad Pro (Chrome inspector). I can reproduce it on Desktop if forcing display to 'grid' on 'div.buttonList'. Are you aware of a way to inspect on Android? would be happy to take a look.

Thanks!

**Comment by neurosock** [comment]
Oops.. seems like you might be familiar with it too ... https://www.youtube.com/watch?v=qbPIAZguJeo

**Comment by zsviczian** [comment]
I think this was a deliberate choice by the Excalidraw team. However, this is a CSS thing, which should be easy to change, even for your self with a CSS snippet in Obsidian. I'll take a look.

**Comment by zsviczian** [comment]
You can create a css snippet with the following code:

```css
.is-mobile button {
    width: initial !important;
}
```
