### ISSUE TITLE
It seems to automatically copy infinitely as soon as the mouse hits the file name again

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#54]
![image](https://user-images.githubusercontent.com/29135984/117626621-e2f18300-b1a9-11eb-8778-fd6f51b57755.png)

**Comment by zsviczian** [comment]
I am not sure I understand you. which file name does the mouse hit? using the 1.0.9 production version or the latest 1.0.10-test version?

**Comment by zsviczian** [comment]
You forgot to upload the file. 
The family tree example was developed by @shabegom, you may want to chat to him on Discord on the OMG server.
Maybe there is an error in your script.

**Comment by zsviczian** [comment]
This seems to be an issue with the dataviewjs script used, not an error in the plugin. I am closing for now... please raise again with additional details, if you feel this is a plugin error and not a script error.
