### ISSUE TITLE
Typo in script - Add link to object

### ISSUE THREAD

**Issue by RobOK2050** [zsviczian/obsidian-excalidraw-plugin#540]
**Describe the bug**
I copied the script of Git and it had a typo and would not run. Typo in the property "length"

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Add%20Link%20to%20Existing%20File%20and%20Open.md

**Comment by zsviczian** [comment]
Thanks. I corrected it. you can download the updated version from the script library.
