### ISSUE TITLE
[Feature request]: Activate link if mouse is over any part of the element, not just the link icon

### ISSUE THREAD

**Issue by RobOK2050** [zsviczian/obsidian-excalidraw-plugin#541]
**Describe the bug**
Using script: Add Link to Existing File and Open.md 
In settings, have it set to open in New Pane
Click on link and drawing is replaced with file in same pane, not new pane

**Expected behavior**
Should open in new pane.

**Environment (please complete the following information):**
 - Mac OS

**Comment by zsviczian** [comment]
> Click on link and drawing is replaced with file in same pane, not new pane

This sentence makes me feel that we might be misunderstanding each other. "Add link to Existing file and open" will not have a "long-term" effect on the link that is created, i.e. next time you click the link, it will open in the same pane or a new pane just like any other links. You need to hold down CMD+Shift to open the file in a new pane

This is how the setting works for me:

https://user-images.githubusercontent.com/14358394/159184286-eccf03ea-66d8-438e-813e-31374fa9a15f.mp4

And here's the demonstration of CMD+shift clicking the link and clicking the link:

https://user-images.githubusercontent.com/14358394/159184472-bd1d5ba1-1a4e-4d2f-a8ca-4d983994471e.mp4

**Comment by RobOK2050** [comment]
You are correct, I was misunderstanding the intent of the setting.

For me, when I am constructing a diagram, I don’t want the linked thing to be opened at all (so I will have it set for new pane and just close it).

You can close this ticket.

From: zsviczian ***@***.***>
Date: Sunday, March 20, 2022 at 4:23 PM
To: zsviczian/obsidian-excalidraw-plugin ***@***.***>
Cc: Rob O'Keefe ***@***.***>, Author ***@***.***>
Subject: Re: [zsviczian/obsidian-excalidraw-plugin] Link not opening in new pane (Issue #541)

Click on link and drawing is replaced with file in same pane, not new pane

This sentence makes me feel that we might be misunderstanding each other. "Add link to Existing file and open" will not have a "long-term" effect on the link that is created, i.e. next time you click the link, it will open in the same pane or a new pane just like any other links. You need to hold down CMD+Shift to open the file in a new pane

This is how the setting works for me:

https://user-images.githubusercontent.com/14358394/159184286-eccf03ea-66d8-438e-813e-31374fa9a15f.mp4<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F14358394%2F159184286-eccf03ea-66d8-438e-813e-31374fa9a15f.mp4&data=04%7C01%7Crfo%40arcaspicio.com%7Cd89dfa2a5465495c72ad08da0aaf6cdd%7Cb8831c210fc94cf28997a7123cf2dfa4%7C1%7C0%7C637834045834302062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000&sdata=a8G5wLISjK3f%2B%2BYp66%2BqF5jj6o8TmsfWfHDlCROEfAM%3D&reserved=0>

And here's the demonstration of CMD+shift clicking the link and clicking the link:

https://user-images.githubusercontent.com/14358394/159184472-bd1d5ba1-1a4e-4d2f-a8ca-4d983994471e.mp4<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F14358394%2F159184472-bd1d5ba1-1a4e-4d2f-a8ca-4d983994471e.mp4&data=04%7C01%7Crfo%40arcaspicio.com%7Cd89dfa2a5465495c72ad08da0aaf6cdd%7Cb8831c210fc94cf28997a7123cf2dfa4%7C1%7C0%7C637834045834302062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000&sdata=5BuhjhYBs8QxTi%2Bo%2FJ2HPD0YG1KveYIXAHr01fRto6Y%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzsviczian%2Fobsidian-excalidraw-plugin%2Fissues%2F541%23issuecomment-1073342052&data=04%7C01%7Crfo%40arcaspicio.com%7Cd89dfa2a5465495c72ad08da0aaf6cdd%7Cb8831c210fc94cf28997a7123cf2dfa4%7C1%7C0%7C637834045834302062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000&sdata=ZEUfUAcDg%2FdrObHv4TGZpNXpPDK4ZGfXcZ2NQn4B4Fo%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANIGT3XH55NKFOFDVGLAWALVA6CKDANCNFSM5RF6DDRQ&data=04%7C01%7Crfo%40arcaspicio.com%7Cd89dfa2a5465495c72ad08da0aaf6cdd%7Cb8831c210fc94cf28997a7123cf2dfa4%7C1%7C0%7C637834045834302062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000&sdata=zynLfn9EWdkBdLXiS8xGjASrK9vHR%2FQl0wiKsAzirfM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfo%40arcaspicio.com%7Cd89dfa2a5465495c72ad08da0aaf6cdd%7Cb8831c210fc94cf28997a7123cf2dfa4%7C1%7C0%7C637834045834302062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000&sdata=jdkSjiYpa4yrLrUAl%2BiINI1ZDKMCDpYZCeizbFFgsUw%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfo%40arcaspicio.com%7Cd89dfa2a5465495c72ad08da0aaf6cdd%7Cb8831c210fc94cf28997a7123cf2dfa4%7C1%7C0%7C637834045834302062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000&sdata=sHrhf7Kv5jSUoq%2FgmNk358QkiYEn%2B5MvwF6jvds51bE%3D&reserved=0>.

**Comment by zsviczian** [comment]
So you want to add a link pointing to an existing file in your vault to an element other than a text element? 
You can use the command palette action (insert link to existing file) to insert a text link. You can then copy that link and add it as a link to an element.

I could add a command palette action to attach a link to an element.

https://user-images.githubusercontent.com/14358394/159186227-af2a4fd4-5940-480f-a686-4ba91263ca47.mp4

**Comment by zsviczian** [comment]
@RobOK2050, Has the above answered your question? May I close this issue?

**Comment by RobOK2050** [comment]
Yes, you can close it.

What I would ideally like is clicking anywhere on an object to trigger the page opening, not having to go to the link icon.

I am envisioning a Mind Map with each node being fully clickable and taking you to a page in the next pane. A navigation drawing on top of a complex set of topics in a graphic.

**Comment by zsviczian** [comment]
This sounds doable. I'll add it to the to-do list, though I do not promise any timeline because the todo list is already very long.

**Comment by zsviczian** [comment]
> What I would ideally like is clicking anywhere on an object to trigger the page opening, not having to go to the link icon.

I will release this in 1.6.24
