### ISSUE TITLE
Excalidraw plugin conflics with others (i.e. Sliding Panes (Andy Matuschak Mode)

### ISSUE THREAD

**Issue by tadsn3w** [zsviczian/obsidian-excalidraw-plugin#542]
**Describe the bug**
I have several plug ins and Excalidraw conflicts with Sliding Panes.  It is not a big deal, I can work around it.  You don't even have to fix it, but I wanted to make you aware and prevent something bigger.
The two plugs ins are:

- Excalidraw Version 1.6.16 installed.
- Sliding Panes (Andy Matuschak Mode) Version 3.2.3

**To Reproduce**
1. Have Excalidraw and Sliding panes installed and active.
2. Open at least 2 panes (more are better and one of them is a excalidraw one.  It is better if excalidraw file is not the first one, so you can see how it behaves.)  
3. Start with the first pane from the left
4. Use Shift and scroll bar button to slide the panes.
5. Panes start sliding.  Keep sliding until you reach the excalidraw file.  You see the pane moving and then stops and the drawing start moving and not the pane.  Even the diagram goes out of the available display area.  
6. Start Shift and scroll bar to the other side and the diagram comes back, but the pane never slides again.
7. The Sliding panes stopped, and you have to manual click in another pane to make it work again.

**Expected behavior**
I was expecting the panes keep sliding as normal.  If I wanted to work on the excalidraw file then I should click on the file.  That is the behavior expected from the Sliding panes.  All the panes sliding to right or left and when you want to work in one file you click on it.

**Screenshots**

https://user-images.githubusercontent.com/44947400/159186084-a3c71aef-7254-42f5-a322-a8a4313e9f0f.mp4

**Environment (please complete the following information):**
 - OS: Linux fedora 5.16.15-201
 - Plugin version: 
   - Excalidraw Version 1.6.16 installed.
   -  Sliding Panes (Andy Matuschak Mode) Version 3.2.3
 - Obsidian version: 0.13.33

**Additional context**
It is nothing that a simple click in another pane and the workaround solves the problem.  It is more that a heads up of potential issues.

**Comment by zsviczian** [comment]
I will definitely take a look to see if I there is anything I can do on my side... Unfortunately plugins that play with CSS such as the sliding panes plugin, but also some of the themes tend to cause these issues (here's an [example](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/493). I already have some code for compatibility with sliding panes, I wasn't aware of this issue though. 

You might also want to open an issue with Sliding Panes... as in my understanding the root cause is not in Excalidraw, but in the way sliding panes is implemented.

**Comment by zsviczian** [comment]
I can't reproduce. Could this be your theme + sliding panes together causing this issue? What theme are you using?


https://user-images.githubusercontent.com/14358394/160272517-336806b3-11b3-4dbc-8fb6-c4ffec09d62f.mp4

**Comment by tadsn3w** [comment]
You hit the nail on the head.
I tried several other themes and only happen when I use "Dracula for Obsidian".
I tried the default, Cyber Glow, Cybertron without any side effects.

Good find!!!.
Please close the issue.  It is not excalidraw plug-in  issue.

**Comment by tadsn3w** [comment]
I took the liberty to close it myself.

amazing plug-in by the way!
