### ISSUE TITLE
Feature request: Create a link to the box around text.

### ISSUE THREAD

**Issue by kazdonkai** [zsviczian/obsidian-excalidraw-plugin#543]
It is possible to create links for shapes, Sticky notes and images, but not for the box with text enclosed in script. 
These appear to be the same, but the inability to create links only in the case of boxes is inconsistent.

**Comment by zsviczian** [comment]
This needs to be resolved in the core product.
I opened an issue for this: [#4959](https://github.com/excalidraw/excalidraw/issues/4959)
