### ISSUE TITLE
cannot open embedded drawing in obsidian mobile

### ISSUE THREAD

**Issue by slonik-az** [zsviczian/obsidian-excalidraw-plugin#547]
**Describe the bug**
I am using latest excalidraw plugin version 1.6.20 and latest iOS mobile obsidian version 1.1.1 running on an iPad under iPadOS 15.3.1. 

Tapping on an embedded drawing `![[foo.excalidraw]]` does not open it. I tried single tap, double tap, tap and hold. Nothing works. 

A work-around is to temporarily remove `!` from the obsidian link converting it to a normal link `[[foo.excalidraw]]` without embedded preview. Now tapping  the link opens the drawing. Edit, close, then restore `!`. Ugly hack. :disappointed:

**To Reproduce**
1. Create a drawing `foo.excalidraw`
2. Embed it in a note as `![[foo.excalidraw]]`
3. Tap the embedded drawing (tap and tap until fingers get tired ...)
4. See nothing happening :disappointed:

**Expected behavior**
Like in a desktop version, tap or click on the image should open the drawing.

**Environment (please complete the following information):**
 - OS including version: iPadOS 15.3.1
 - Plugin version: 1.6.20
 - Obsidian version: obsidian mobile for iOS, version 1.1.1 (48)

**Comment by zsviczian** [comment]
How Obsidian handles links in live preview is not something I can fix. However, if you tap the excalidraw image, and then tap it again, it will open in excalidraw and you can edit it. Again, I can't do anything with the need for the double taping, it's a single tap on a desktop, I am sure the Obsidian devs have a good reason for making it a double tap on iOS.

**Comment by slonik-az** [comment]
Double tap as you described does not work for me either.

**Comment by slonik-az** [comment]
By trial and error I think I found the problem in the "Blue Topaz" theme. When I switch to the "Default" theme a single tap opens the drawing. I will report the problem in the appropriate issue tracker for the "Blue Topaz" theme.
