### ISSUE TITLE
WebP images

### ISSUE THREAD

**Issue by StefanoCecere** [zsviczian/obsidian-excalidraw-plugin#548]
SVG is great, but files ar huge
png is better (as fiel size)... but WebP is much better!

i'm converting all jpg and png to WebP, saving about 60%. WebP is now supported by everything.. so what do you think?

**Comment by zsviczian** [comment]
This needs to be developed in the core Excalidraw product. I can't fix it in the Obsidian plugin. Please raise the issue here: https://github.com/excalidraw/excalidraw/issues
