### ISSUE TITLE
enabling on mobile causes loading of "workspace" to take several mins

### ISSUE THREAD

**Issue by brimwats1** [zsviczian/obsidian-excalidraw-plugin#55]
I've tested this on there android devices. Turned off all plugins except this one. Enabling this causes the "workspace" part of starting the app to massively increase.

**Comment by brimwats** [comment]
hm... can you tell me more. I have this on Android as well and it loads without any issues.
Which version of the Android app?

0.19

How large is your vault? I do an indexing of files to see which drawing is transcluded (embedded) in which document, for handling automated update of file names in transclusions... that is what I can imagine being the culprit.

about 5000 items

What's the model of your phone?

Samsung galaxy S10, replicated on the S8, The Oynx Boox, and The Galaxy Tab 6

Did you experience the same issue with 1.0.9 as well? or just with 1.0.10

This report was from 1.0.9. I will try again with the update. 


Could you try with an empty vault to see if the loading takes similarly long?

Sure

**Comment by zsviczian** [comment]
S10 should be powerful enough. 5000 documents is definitely more than I have in my vault... I have an idea, I will release an update tonight, I will be curious to know if that solves your issue.

**Comment by zsviczian** [comment]
Thanks! Working on it!

**Comment by brimwats** [comment]
it's fixed!! worked beautifully
