### ISSUE TITLE
Autosave not working > force-save to update always red when editing -> esc active pane = data lost

### ISSUE THREAD

**Issue by SKnight1207** [zsviczian/obsidian-excalidraw-plugin#551]
**Describe the bug**

**To Reproduce** and **Expected behavior**
1.1. Create an ACTIVE PANE and make a large enough mindmap (i.e just something that takes 4 hours to make)
1.2. AND don't MANUALLY press the force-save to update when RED + in settings: ENABLE AUTOSAVE set to 15s or whatever 
3. Escape the ACTIVE PANE by any means possible or CREATE another COPY of the ACTIVE PANE
4. See error: PARTIAL or TOTAL DATA LOST due to AUTOSAVE not working
5. Workaround (bug?): If force-save to update is pressed and doesn't show RED anymore -> data saved
6. Problem: AUTOSAVE not working as intended 

**Screenshots**
![before closing](https://user-images.githubusercontent.com/63585568/160264779-b6870a08-c7c6-4a88-bffb-d8f69ee6dd79.png)
![after closing](https://user-images.githubusercontent.com/63585568/160264781-b654a9ae-be13-466b-b9d3-055d56620f7c.png)

**Environment (please complete the following information):**
 - OS including version: Windows 10 on PC
 - Plugin version: 1.6.20, no scripts installed (latest?)
 - Obsidian version: 0.13.31 for Windows

**Additional context**

Obsidian's file recovery just doesn't save most of the changes in Excalidraw to snapshots which make recovery really really difficult or downright impossible
Main issue is red force-save to update and autosave not working
If this isn't a bug then the autosave feature sometimes is just too slow to save all of what I have been working on
Companion bug: somtimes force-save to update is pressed but keeps showing red, esc or change to new pane will DELETE DATA RECENTLY EDITED

**Comment by zsviczian** [comment]
Hi SKnight1207, I am really sorry that you have lost some of your work. I will spend today attempting to reproduce your error.

>  Escape the ACTIVE PANE by any means possible or CREATE another COPY of the ACTIVE PANE

I understand the length of time causes frustration, however, I need your help to be more specific as to how you can reproduce the error.  Can you be specific what you did in this step?

---

I created a test drawing with 1236 elements including 180 text elements.

Normally Excalidraw saves when the active pane loses focus. When you click the Obsidian file explorer save is not triggered, however, when I open another document the file was saved before opening the other document.

So far I was able to produce 1 bug, but even that did not lead to data loss. With the disk icon still red, I switched over to file explorer and right clicked on my file, and selected to make a copy. The copy was created before the file was saved, thus my copy missed my latest changes, however, the original drawing saved everything as expected. I will fix this.

----

What other plugins do you have installed and activated?

**Comment by zsviczian** [comment]
After many hours of trying I was able to reproduce the error. I will release a fix later today.

**Comment by zsviczian** [comment]
Related issue [4979](https://github.com/excalidraw/excalidraw/issues/4979)

**Comment by zsviczian** [comment]
I will release the fix in 1.6.21.

**Comment by SKnight1207** [comment]
thank you so much <3, it's actually really awesome to know that my opinion managed to reach you and helped better the plugin as a whole for the community surrounding Excalidraw.
