### ISSUE TITLE
"Create a new drawing - IN THE CURRENT ACTIVE PANE - and embed into active document" does not work as intended when an Excalidraw pane is already open.

### ISSUE THREAD

**Issue by yuvve** [zsviczian/obsidian-excalidraw-plugin#559]
**Describe the bug**
If you have multiple panes open and one of them is an Excalidraw pane, then the command "Create a new drawing - IN THE CURRENT ACTIVE PANE - and embed into active document" will always open the new drawing inside the Excalidraw pane, even if it's not the active pane.

**To Reproduce**
1. Open two panes, one regular .md and one Excalidraw.
2. Make sure the .md pane is active, and from the command palette choose "excalidraw: Create a new drawing - IN THE CURRENT ACTIVE PANE - and embed into active document".
3. See error

**Expected behavior**
The new Excalidraw drawing should open in the active pane when that specific command is used.

**Screenshots**
![Obsidian_uBaMVVtHUK](https://user-images.githubusercontent.com/37124628/160647490-addfca35-e618-4f3c-bc1f-1637cd80a323.gif)

**Environment (please complete the following information):**
 - OS including version: Windows 11
 - Plugin version: 1.6.21
 - Obsidian version: 0.14.2

**Additional context**
The bug exists even on a fresh vault with no other plugins installed.

**Comment by zsviczian** [comment]
Solved. It will be released in 1.6.22
Looking at my code, this was one of those moments... of "what was I thinking?", and "this code has been there since April 2021, how come I never noticed it, and nobody ever complained?" Amazing.
