### ISSUE TITLE
About links on sticky notes 

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#561]
From YouTube by Jim McLaughlin

> When I copy an element (e.g., a rectangle) that has a link, that link persists, even if I change the text within the element. I click on the link in the menu and that allows me to add a link but not edit the original link. What am I missing?

Sticky notes (object with text) are tricky as they can have two links. One for the rectangle and another for the text.

https://user-images.githubusercontent.com/14358394/160766728-95435634-b47c-4d47-a7d8-7e9bbfb01010.mp4

**Comment by kazdonkai** [comment]
These two links are hard to distinguish.
Especially when the marks are in the same position and close to each other, it is difficult to select one from the other.
For example, could the text link mark be placed in the upper right corner and the sticky notes link mark be placed in the lower right corner

https://user-images.githubusercontent.com/90127278/160898145-245d2385-5f8a-44f7-9219-c6576fab3e3d.mov

?
