### ISSUE TITLE
Transclusion in a rounded shape - text cut off

### ISSUE THREAD

**Issue by RobOK2050** [zsviczian/obsidian-excalidraw-plugin#564]
**Describe the bug**
I am transluding text into a box. Selected rounded corners. The first line of text overlaps into the rounded corner.

**Expected behavior**
Expected a bit of spacing when using rounded corners so the text is cleanly in the box.

**Screenshots**
![CleanShot 2022-03-31 at 14 09 55](https://user-images.githubusercontent.com/55601646/161122141-382a997e-2ec0-4af9-8ba7-9603e3cd3d6c.png)

**Environment (please complete the following information):**
Mac OSX

**Comment by zsviczian** [comment]
Thanks. Yes, this is a known issue. This is how the sticky note feature was implemented in Excalidras.
- I can add a configuration to settings to specify the margin in sticky notes, however, that will apply to all sticky notes, not just round shapes.
- You can apply a workaround. Simply add an empty line before and after the transclusion, that will result in a padding at the top and the bottom.

**Comment by RobOK2050** [comment]
Thank you! You can close this
