### ISSUE TITLE
Include Excalidraw links in backlinks of reference files

### ISSUE THREAD

**Issue by dcoales** [zsviczian/obsidian-excalidraw-plugin#566]
Hi,

I've noticed that if I use the link functionality of Excalidraw to add a link to an internal file this works great. I get the icon to show there is a link and if I hover over it the popup editor appears.  The only issue is that the details of the link only appear in the JSON description of the drawing in the "link" attribute and not in the markdown text so none of these links show up in the backlinks section of the target file nor does renaming the target file rename the link - I guess because Obsidian doesn't change text inside code blocks.

Is there any way around this or should I just not use the Excalidraw link functionality for internal links - just for external links.

Thanks,
David

**Comment by zsviczian** [comment]
I am afraid I might be misunderstanding you. Could you send me a screen capture to demonstrate the issue:?

See my demo. I place all the element links to Text Elements as well exactly for this reason.


https://user-images.githubusercontent.com/14358394/161367781-d60af417-2516-4704-baf1-9aa3666a0cbd.mp4

**Comment by dcoales** [comment]
I'll try to do it when I get back to my computer. I don't create the links though by typing [[filename]] into the text in the diagram. Instead I simply write the text then select it and in the excalidraw menu that opens on the left I scroll to the bottom where there is a link icon. I click this and a dialog opens where i can enter a link. In this dialogue i type [[filename]]. The text I type in this dialogue doesn't go into the markdown portion of the file but is added to a "link" attribute in the JSON description of the diagram.  This is not updated when the file name changes, either because excalidraw doesn't update links in code blocks or because the code blocks is encrypted in excalidraw.

**Comment by dcoales** [comment]
In fact much of the time I add the link using a script that sets the "link" property of the element to a filename retrieved from a selection popup.  This leads to the same situation though.

**Comment by zsviczian** [comment]
Ok. I am able to reproduce. I wonder why... but I shall soon find out :)

**Comment by zsviczian** [comment]
Ok. This happens for you only when adding links to text elements or to other elements as well. I recommend creating links in text elements by simply creating the text element including the markdown link. If you don't want to display the filename, set an alias (even an empty alias). The root cause with text elements is a conflict with the element ID since I use the element ID to store the link text as well as the text itself. In the case of text elements, there is a conflict.
 This will require a bit more invasive change to fix. I don't promise a fix very soon.

**Comment by dcoales** [comment]
Okay, no worries.  For now I'll do as you say and move over to using markdown links in the text itself.  Thanks.

**Comment by zsviczian** [comment]
I have finally resolved this. The solution will be rolled out as part of 1.7.23. My solution is the following:

If a textElement has a link but there is no markdown link within the text (i.e. only in the .link property), it will be saved as part of the textElement text like this:
```markdown
# Text Elements
%%***>>>text element-link:[[this is the link]]<<<***%%This is the rest of the text element ^textid01

Next text element is without a link ^textid02

This text has a [[file]] link in the text ^textid03

This text element has a [[file]] link different from the "other file" in the Elemenet.link property. In this case [[file]] will prevail and link to "other file" will be overwritten.
This matches current behavior, in case there are two links, the link in the
text will prevail ^textid04

...
```
