### ISSUE TITLE
Text moves along with line/arrow

### ISSUE THREAD

**Issue by Dcarnik** [zsviczian/obsidian-excalidraw-plugin#570]
The arrow/line which connects two figures follows the figure when figure is moved to other position. That is great! We use text to identify the line (for process diagram), like numbers or other text parameters. In case the text is placed next to the line, after moving the figure, the line follows the  figure, yet text stays in same position (see fig. 1, 2)  

It would be nice that text moves together with lane (see fig. 3). 

The ideal solution. The line/arrow when double clicked allows to add text which is then connected with line/arrow. The line/arrow separates into 2 parts (see fig. 4). In case text manually moved to other position which do not intersects line, the line/arrow's 2 segments become as 1 segment. 
Good realization of that was said above at: https://www.diagrams.net/ 
Thanks.

![image](https://user-images.githubusercontent.com/57209269/161514050-c0f60359-f422-4501-8e76-924aec14e424.png)

**Comment by zsviczian** [comment]
I agree, this would be a very useful feature. I transferred this issue to the core Excalidraw product issue list.
