### ISSUE TITLE
[Question] Where to find autosave in plugin settings?

### ISSUE THREAD

**Issue by i-c-u-p** [zsviczian/obsidian-excalidraw-plugin#579]
When I go to the plugin settings for Excalidraw, I see this:
![Excalidraw plugin settings snippet](https://user-images.githubusercontent.com/96894903/162601352-a5700d85-e8c5-45d0-b665-1e1520f95df4.png)
I don't know Typescript/Javascript, but looking at `src/settings.ts` and `src/lang/locale/en.ts` I assume the settings for autosave would appear under the "Compress Excalidraw JSON in Markdown" setting. I've scanned over the settings page a few times and can't find anything related to autosave. Am I looking in the wrong place for this setting, or is the fact it isn't appearing a bug?

**Comment by zsviczian** [comment]
I hid autosave settings in 1.6.21 because it was a source of user error, also unnecessary. It is the normal user expectation that autosave simply happens - you shouldn't need to set it. See [release log](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.6.21).

**Comment by i-c-u-p** [comment]
> I hid autosave settings in 1.6.21 because it was a source of user error, also unnecessary. It is the normal user expectation that autosave simply happens - you shouldn't need to set it. See [release log](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.6.21).

Ah, ok. Thank you!
