### ISSUE TITLE
Option for file name convention

### ISSUE THREAD

**Issue by mehmet-safak** [zsviczian/obsidian-excalidraw-plugin#58]
I would love to see an option to determine the naming of new excalidraw drawing. 

Or at least, avoid spaces and dots in file names.

**Comment by zsviczian** [comment]
I will look into this. In the meantime, you know you can do this simply using templater.

[https://zsviczian.github.io/obsidian-excalidraw-plugin/API/utility.html](https://zsviczian.github.io/obsidian-excalidraw-plugin/API/utility.html)

```javascript
<%*
const default = tp.date.now("YYYYMMDD-HHmm");
const title = await tp.system.prompt("Title of the drawing?", default);
const ea = ExcalidrawAutomate;
ea.reset();
ea.create({filename:title, foldername:"Excalidraw/", templatePath: "Excalidraw/template.excalidraw", onNewPane: true});
%>
```

**Comment by zsviczian** [comment]
See settings in 1.1.5 - just released.
