### ISSUE TITLE
Excalidraw is not compatible with Chinese

### ISSUE THREAD

**Issue by MartinYuan1995** [zsviczian/obsidian-excalidraw-plugin#583]
Hi Buddy,
    I am a user who is from China. Recently, I was exposed to Excalidraw which is a nice tool in Obsidian. But I found that when I typed Chinese long words that reached the box edge, Chinese would be broken into Pinyin which is a system of writing the Chinese language in the Roman alphabet officially recognized in China. So, please tell me how to solve this problem, thanks
![iShot2022-04-13_10 14 50](https://user-images.githubusercontent.com/47047658/163115289-88af61a2-dfda-4724-920a-25e5b3180e9f.gif)
.

**Comment by zsviczian** [comment]
I am sorry, but I don't know. I know there are many Chinese users and I haven't come across this question from others, thus I assume this works for others. I recommend you raise this question on the OMG Discord. 

@zhl111 can you maybe help?

**Comment by zhl111** [comment]
是的，我没有遇到过这样的问题。obsidian升级到最新版本了吗？输入法更换一个试试呢？

**Comment by MartinYuan1995** [comment]
您好，我的ob已经是最新版本了，excalidraw插件也更新到最新了，也尝试过换输入法，例如：搜狗、Mac原生输入法，问题依然存在。

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/163314360-b38ff32c-62c7-4d2f-a0d8-7cad48497a73.png)
我打多长都不上屏，所以不会出现你说的问题。

**Comment by zsviczian** [comment]
What input method are you using?
As a test, please create a new Obsidian Vault and only install the Excalidraw plugin and test to see if the same issue is happening.

**Comment by MartinYuan1995** [comment]
> ![image](https://user-images.githubusercontent.com/29135984/163314360-b38ff32c-62c7-4d2f-a0d8-7cad48497a73.png) 我打多长都不上屏，所以不会出现你说的问题。

我的是Mac电脑，所以打字的时候会上屏幕。

**Comment by MartinYuan1995** [comment]
> What input method are you using? As a test, please create a new Obsidian Vault and only install the Excalidraw plugin and test to see if the same issue is happening.

Thanks for your suggestion. I just tried as you told me. Unfortunately, the same problem still exists on  my mac.

**Comment by MartinYuan1995** [comment]
The problem will appear when I type Chinese words in a small shape, such as a rectangle, or circle.

**Comment by zsviczian** [comment]
As a workaround, can you try installing the scribble helper script from the Excalidraw script library?

![image](https://user-images.githubusercontent.com/14358394/163333245-eb158532-daf0-40df-a3fc-81bd7f32bf06.png)

**Comment by MartinYuan1995** [comment]
> As a workaround, can you try installing the scribble helper script from the Excalidraw script library?
> 
> ![image](https://user-images.githubusercontent.com/14358394/163333245-eb158532-daf0-40df-a3fc-81bd7f32bf06.png)
![2022-04-14 15-21-30 2022-04-14 15_22_24](https://user-images.githubusercontent.com/47047658/163334758-aa9e8fc0-84d6-4b73-9816-039dd359130a.gif)

Hi, I just tried but it's useless.

**Comment by zsviczian** [comment]
I am sorry, but I don't think I can help with this.
If you find a solution please share it here so others with a similar issue can benefit from it as well.

**Comment by dcHHH** [comment]
> Hi Buddy,
> I am a user who is from China. Recently, I was exposed to Excalidraw which is a nice tool in Obsidian. But I found that when I typed Chinese long words that reached the box edge, Chinese would be broken into Pinyin which is a system of writing the Chinese language in the Roman alphabet officially recognized in China. So, please tell me how to solve this problem, thanks
> ![iShot2022-04-13_10 14 50](https://user-images.githubusercontent.com/47047658/163115289-88af61a2-dfda-4724-920a-25e5b3180e9f.gif)
> .

我也遇到这个问题了，可能mac上是有bug，你有解决方案了吗？
