### ISSUE TITLE
Drag and Drop multiple files at once onto drawing

### ISSUE THREAD

**Issue by derekvan** [zsviczian/obsidian-excalidraw-plugin#589]
**Is your feature request related to a problem? Please describe.**
I would like to organize notes on a whiteboard, where I can group them together in clusters, sort of like what you demo in your planning video (https://www.youtube.com/watch?v=3Qt9WbkcGa4), but instead of just text, they would be links to notes (sort of like the combining that video with the clothesline video). However, I don't want to make all the links manually. I want to take a folder of notes, or several of them, and drag them onto the canvas at once.

**Describe the solution you'd like**
I would like to shift-select multiple notes in the Obsidian file explorer and drag/drop them onto Excalidraw canvas and have each one appear as a small square with the note title inside.

**Describe alternatives you've considered**
I've tried dragging notes one by one, but this is tedious when there's more than 20.

**Comment by derekvan** [comment]
Another possible approach to achieving the end result could be through the scripting engine. A script that prompted users for a search expression (similar to Obsidian's overall search, allowing a mixture of path, tag, keyword, etc.) and then created a set of rectangles on the canvas. Each rectangle functioning as a link to a different note and having X characters of the note name as its label.

**Comment by zsviczian** [comment]
I fixed drag&drop for multiple files in 1.6.26. I will release the fix later tonight or tomorrow.

https://user-images.githubusercontent.com/14358394/166109270-369667e0-f659-463c-b07d-a214a942dd04.mp4

A script as you describe could be developed. It is a nice challenge to learn Excalidraw scripting. I recommend that you give it a try.

As yet another alternative you can drag and drop search results from Obsidian search as well.

**Comment by Stronskiy** [comment]
I ran into a problem that when converting a fragment of the board into SVG for my own purposes, the drawings move to the side. How can I make sure that they do not move out and everything remains the same as on the board when converting?
