### ISSUE TITLE
Text contrast color between editor(set color) and note embed

### ISSUE THREAD

**Issue by julianstoerig** [zsviczian/obsidian-excalidraw-plugin#59]
After making a little **fully black** graphic in the integrated excalidraw editor, I embedded it in a note.
![image](https://user-images.githubusercontent.com/55281225/118926388-8546fe80-b940-11eb-91ca-9de56d1fdc72.png)

However, the text seems to have gone from a full black to an around 50% grey without good reason:
![image](https://user-images.githubusercontent.com/55281225/118926275-59c41400-b940-11eb-9088-a12000432cc2.png)

This behavior existed on the previous version and has not changed after the 1.1 release.

**Comment by zsviczian** [comment]
I just released a fix. Please test version 1.1.2 and confirm that your issue is resolved.
