### ISSUE TITLE
The Brain Navigation don't work for some notes

### ISSUE THREAD

**Issue by Liu-Yitao** [zsviczian/obsidian-excalidraw-plugin#591]
**Describe the bug**
The brain navigation script can only work for some specific notes. And I didn't get the pattern for it. 

**To Reproduce**
I record a video about it. And it behaves the same after restarting Obsidian.

https://user-images.githubusercontent.com/59553921/164393564-2088e4af-e13e-4f86-a58c-3ef784a32712.mov

**Expected behavior**
How can I make the script run properly for every note?

**Environment (please complete the following information):**
 - OS including version: macOS 12.3.1
 - Plugin version: 1.6.25
 - Obsidian version: 0.14.6

I really appreciate your work on the Excarlidraw Plugin!

**Comment by zsviczian** [comment]
I am rewriting TheBrain navigation into its own plugin. I hope to have the first version out this weekend. Hopefully, that will solve your issue.

Are you using the latest version of the script? Please check if there is an update in the script library.
- in the latest version you no longer need to refresh the breadcrumbs index, in fact, I no longer rely on the breadcrumbs plugin, only on data view.

Can you create a screenshot of the console log of the developer console when the error happens? CMD+SHIFT+i

**Comment by Liu-Yitao** [comment]
I found out that removing a "?" from my markdown filename solves the problem!
- the filename used to be "xxxx ?".
- I turned it to "Q xxxx".
- And it all worked!

So maybe this is because the mark "?" is not acceptable for the plugin or script?

**Comment by zsviczian** [comment]
? is not an allowed character in filenames. This is not a plugin thing, but an operating system thing. Obsidian also does not allow changing filename to include `?`.

![image](https://user-images.githubusercontent.com/14358394/164643118-97fb4468-093c-4fc3-8891-4a71db950c79.png)

I use the unicode `？` instead. That is allowed. https://www.compart.com/en/unicode/U+FF1F

I even have a simple Templater script to insert special unicode characters.
```javascript
<%*
tR += await tp.system.suggester(
  ["question mark","backslash","colon"],
  ["？","＼","："]
);
%>
```

**Comment by zsviczian** [comment]
If this is still a problem, please raise an issue in the ExcaliBrain issue list. https://github.com/zsviczian/excalibrain/issues
