### ISSUE TITLE
"Hover preview without CTRL/CMD key" doesn't work

### ISSUE THREAD

**Issue by Missionary2112** [zsviczian/obsidian-excalidraw-plugin#595]
**Describe the bug**
"Hover preview without CTRL/CMD key" doesn't work. Though I enable that function, I have to hold down CMD every single time if I want to see the popped up preview.

**To Reproduce**
1. Go to Setting > Excalidraw > Enable "Hover preview without CTRL/CMD key" 
2. In Excalidraw drawing, Create a link to any file within the vault
3. See error: Hover the cursor over the link will not pop up the Preview window unless hold CMD in advance

**Expected behavior**
It should pop the Preview window without hold CMD.

**Screenshots**
Not to mention, some Preview window shows empty content 
![Screenshot - 2022-04-22 17 37 35 (Obsidian)](https://user-images.githubusercontent.com/98799613/164838685-c5a93645-67f2-4e40-986a-066633eeea81.jpg)

**Environment (please complete the following information):**
 - OS including version: macOS Monterey. Version 12.3.1
 - Plugin version: 1.6.25
 - Obsidian version: v0.14.6

**Comment by zsviczian** [comment]
I made some improvements that I will release in 1.6.26 later today or tomorrow.
I also added some clarification to the setting:
![image](https://user-images.githubusercontent.com/14358394/166099499-0b81e741-9b9a-4f2f-b228-4c27e6184fa0.png)

**Comment by Missionary2112** [comment]
In Excalidraw normal mode, the preview does not show immediately when I hover the blue link icon. I have to hold CMD for it to pop up. Can you fix that error ? Thank you.
