### ISSUE TITLE
Internal Link display without bracket

### ISSUE THREAD

**Issue by Missionary2112** [zsviczian/obsidian-excalidraw-plugin#596]
**Is your feature request related to a problem? Please describe.**
I would like to display the internal link the way it's editable. E.g. instead of default display `[[Mom]]`, I would like it to be displayed `Mom` or `Mother` or anything without the bracket. 

**Describe the solution you'd like**
I would like to create a family tree with Excalidraw. And it would be awesome if I see people's name without brackets. It would look neat and clean.

**Describe alternatives you've considered**
There is no alternative for me at the moment but to accept `[[file.name]]` with bracket. 

**Additional context**
This is default internal link display looks like.
![Screenshot - 2022-04-22 17 42 09 (Obsidian)](https://user-images.githubusercontent.com/98799613/164842276-e6e3ca8c-6189-4ba0-be74-854dfc2ea285.jpg)

This is what I would like it to look like.
![Screenshot - 2022-04-22 17 42 01 (Obsidian)](https://user-images.githubusercontent.com/98799613/164842576-52153baa-06a6-4f2b-8d37-31bdd49c488f.jpg)

**Comment by zsviczian** [comment]
I might have misunderstood you. But this is already existing functinality.

https://user-images.githubusercontent.com/14358394/164980025-8034a44e-339b-42c6-ac0b-1e5537dea9c7.mp4

**Comment by Missionary2112** [comment]
Wow, thank you sir. Very clear instruction video. I realize I should disable "Show Bracket option".

One more thing I would like to ask you about the "Hover Preview". It does not work in my case, though I enable the option in Excalidraw setting. 
/Users/missionary/Library/Application Support/CleanShot/media/media_7bACo9MFl9/Screenshot - 2022-04-24 14.15.02 (Obsidian).mp4

**Comment by zsviczian** [comment]
Hover preview without CTRL was fixed in [1.6.26](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.6.26)
