### ISSUE TITLE
Display linked block/section on hover rather than full page.

### ISSUE THREAD

**Issue by chaecramb** [zsviczian/obsidian-excalidraw-plugin#597]
**Is your feature request related to a problem? Please describe.**
I frequently link Excalidraw objects to specific blocks or sections of documents. Following the link correctly takes me to the linked block/section, but if I hover the link in Excalidraw to view it, it shows me the whole document.

Example - I would like only "Linked Block" and its child to show, not the whole list:
![image](https://user-images.githubusercontent.com/4717624/164891996-3eedac26-aa98-4dba-8d00-8419e5942e1f.png)

**Describe the solution you'd like**
I would love to have the same behaviour in Excalidraw as hovering block/section links on pages, where only the linked block/section is displayed on hover.

Example: 
![image](https://user-images.githubusercontent.com/4717624/164892049-1ddf216d-5255-4e0b-8583-1e155321c8d8.png)

**Describe alternatives you've considered**
The only workaround I have is extracting the block/section to its own document so that it previews as I would like in Excalidraw. This isn't always appropriate though.

**Comment by zsviczian** [comment]
Thanks for raising. This used to work... I made some changes to support the hover editor. It seems in the process I broke some functionality.
I am busy working on something right now... and will have a busy week next week. It will probably take until next week to get this working again. Sorry.

**Comment by zsviczian** [comment]
I will release the fix in 1.6.26 either today or tomorrow.
