### ISSUE TITLE
Ability to drag files from dataview results onto drawings

### ISSUE THREAD

**Issue by dcoales** [zsviczian/obsidian-excalidraw-plugin#599]
If I drag a file from a dataview table onto another note it creates an internal link in the form "[[The Extended Mind]]".  
When I drop the same thing onto an Excalidraw drawing instead I get an external link in the form "obsidian://open?vault=PKM&file=Study%2FThe%20Extended%20Mind".  

Is there any way we could have this drop in using the internal link format ?

**Comment by zsviczian** [comment]
Absolutely doable. 
I'll try to get to this.
I am busy building the ExcaliBrain plugin... so will be a bit slower to respond on this one. I hope by end of next week I can get this working for you.

**Comment by dcoales** [comment]
That's fantastic.  Thank you.

**Comment by zsviczian** [comment]
Done. I will release the change in 1.6.26 (likely tomorrow).

**Comment by dcoales** [comment]
That's brilliant. Thank you so much.

**Comment by dcoales** [comment]
Hi, I just gave this a go and noticed that the string it adds to Excalidraw is the full path to the file instead of just the file name.  Would it be possible to have an option to just have the filename inside square brackets without the full path ?  I'm using atomic notes and the filename is usually a condensed version of the idea so that's what I want to appear on the drawing with a link to the file. The full path can sometimes be quite long and clutters the drawing so that I then have to remove them by hand.

Sorry to be such a pain :-(
