### ISSUE TITLE
Huge icon 

### ISSUE THREAD

**Issue by bagameow** [zsviczian/obsidian-excalidraw-plugin#6]
**Describe the bug**
A huge icon occurred on the left toolbar.

**To Reproduce**
I'm using theme "California Coast". 
After installing excalidraw and closed an open drawing, it just occurred. 

**Expected behavior**
normal size icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/9460797/115425916-a083f880-a232-11eb-8e8d-315ec21bf620.png)

**Desktop (please complete the following information):**
 - OS: Mac Bigsur

**Comment by zsviczian** [comment]
Thanks for raising. I have fixed the issue. Will be there in the next alpha release!
