### ISSUE TITLE
Show matches for excalidraw files (internal links) while typing

### ISSUE THREAD

**Issue by Ka-hu** [zsviczian/obsidian-excalidraw-plugin#60]
#19 is resolved with version 1.1, thank you! :+1: I see the match function is missing for excalidraw files. Is it possible to show the matches while typing internal links and embeds for excalidraw files?

Both `[[filename.excalidraw]]` and `[[Excalidraw/filename.excalidraw]]` (and embeds with `![[link]]`) work fine if I type them out correctly, but no matches while typing.

Plugin version: 1.1.1
Obsidian version: 0.12.3

![screenshot1](https://i.imgur.com/uC0ApMG.png)
![screenshot2](https://i.imgur.com/bAD7UxL.png)
![screenshot3](https://i.imgur.com/6heHRJ9.png)

**Comment by zsviczian** [comment]
Do you know a plugin that has solved this well? I don't think I can solve it. This is an obsidian feature I don't really think would be good to override... also not sure I can do it without impacting other obsidian functionality.

I suggest you set a shortcut for the command palette action to insert an Excalidraw drawing.

If that helps, I can add command palette actions to insert links, not just transclusions.

**Comment by Ka-hu** [comment]
I see. I didn't know that. Command palette & hotkeys will be fine, thank you!
