### ISSUE TITLE
The drawing is automatically modified.

### ISSUE THREAD

**Issue by FarleyYin** [zsviczian/obsidian-excalidraw-plugin#602]
**Describe the bug**
The drawing is automatically modified.

Issues:
1. Create a canvas
2. Select an arrow, and zoom in
3. Exit
4. Re-enter the canvas
5. The arrow size is changed and becomes small.

**Screenshots**
![image](https://user-images.githubusercontent.com/104541891/165662621-652b7edd-2f64-4ae4-9d0f-49a8bffc3499.png)

**Comment by zsviczian** [comment]
I am able to reproduce. The issue does not seem to occur on excalidraw.com. I'll take a look what might be causing this.

**Comment by zsviczian** [comment]
I can't reproduce any more. Seems like the recent changes to the Arrow/Line editor in Excalidraw have resolved this. 
Please re-open if you are still able to reproduce the issue.
