### ISSUE TITLE
Option to not include path details in link from dropping a dataview entry onto drawing

### ISSUE THREAD

**Issue by dcoales** [zsviczian/obsidian-excalidraw-plugin#610]
When you drag a file link from dataview onto an drawing the test element added includes the full path to the file instead of just the file name. Would it be possible to have an option to just have the filename inside square brackets without the full path ? I'm using atomic notes and the filename is usually a condensed version of the idea so that's what I want to appear on the drawing with a link to the file. The full path can sometimes be quite long and clutters the drawing so that I then have to remove the path details by hand.

Sorry to be such a pain :-(

**Comment by zsviczian** [comment]
good point. I will calculate the link using `app.metadataCache.fileToLinktext`

**Comment by dcoales** [comment]
Thank you

**Comment by zsviczian** [comment]
will be included in 1.6.28.

When dropping a link from a DataView query into Excalidraw the link will honor your "New link format" preferences in Obsidian adding the shortest path when possible (if that is your setting). If the link includes a block or section reference, then the link will automatically include an alias, such that only the filename is displayed (shortest path possible allowing) [#610](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/610)

**Comment by dcoales** [comment]
Just to let you know.  I've upgraded to 1.6.28 and it still drops the full path name onto the drawing even if I have the new file link option set to shortest possible. I've tried changing the setting to something else and back again and exiting Obsidian and restarting but it doesn't appear to make any difference.  Is there another setting I need to set ?

**Comment by zsviczian** [comment]
Did I misunderstand your request?

https://user-images.githubusercontent.com/14358394/167314460-de1d6a51-b250-4c6c-ba63-02a7d57447e1.mp4

**Comment by dcoales** [comment]
After some more testing I think the issue is the ampersand in the directory name.

**Comment by zsviczian** [comment]
I'll take a look at this, however, I generally try to avoid characters like the ampersand in file and folder names (https://www.mtu.edu/umc/services/websites/writing/characters-avoid/)

An alternative approach is for you to handle this special case in a custom onDropHook via ExcalidrawAutomate.

**Comment by dcoales** [comment]
Agreed.  I will change my directory names to remove the ampersands as that's a pretty easy workaround for me :-)

Thanks very much for your help.
