### ISSUE TITLE
showing Link Prefix icon only function fail

### ISSUE THREAD

**Issue by TrillStones** [zsviczian/obsidian-excalidraw-plugin#614]
**Describe the bug**
showing Link Prefix icon only function fail

**To Reproduce**
1. see screenshot.

**Expected behavior**
showing Link Prefix icon only,but it show brackets also.

**Screenshots**

<img width="896" alt="image" src="https://user-images.githubusercontent.com/32927876/167287631-704e4566-830a-4eb0-a890-1a3822602a11.png">

<img width="801" alt="image" src="https://user-images.githubusercontent.com/32927876/167287772-795fa362-ce50-43b8-af0f-06761f6dda88.png">

my excalidraw config:
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/32927876/167287208-e1c8ee43-3a62-4889-a9e8-7d93ee1205c3.png">

**Environment (please complete the following information):**
 - OS including version: Mac Montery 12.2.1
 - Plugin version:  1.6.27
 - Obsidian version:  0.14.6

**Additional context**
none

**Comment by zsviczian** [comment]
I am sorry. I do not understand the problem.

**Comment by TrillStones** [comment]
> I am sorry. I do not understand the problem.
I fill some detail in origin comment.

**Comment by zsviczian** [comment]
check your settings:

![image](https://user-images.githubusercontent.com/14358394/167288166-1b765f78-8276-4c89-9c39-9848fa9024c0.png)

**Comment by TrillStones** [comment]
> check your settings:
> 
> ![image](https://user-images.githubusercontent.com/14358394/167288166-1b765f78-8276-4c89-9c39-9848fa9024c0.png)

it works.thx.
