### ISSUE TITLE
horizontally flipped images inside drawing show un-flipped when embedded

### ISSUE THREAD

**Issue by jmsancho** [zsviczian/obsidian-excalidraw-plugin#617]
**Describe the bug**
Embedding an image inside of an excalidraw drawing and flipping it horizontally works as intended; however, when the drawing is seen from within another note (i.e. the drawing is embedded), the flipped element is on its original orientation. Opening the drawing  again reveals the image flipped as intended.

This does not happen with vertical flipping.

**To Reproduce**
1. Create drawing
2. Embed image
3. Flip image horizontally
4. Embed drawing on another note

**Expected behavior**
Image should remain flipped whether inside the drawing or seen from within an embed

**Environment (please complete the following information):**
 - OS including version: Windows 10
 - Plugin version: 1.6.27
 - Obsidian version: 0.14.6

**Comment by zsviczian** [comment]
Thanks. It seems this is a known issue... unfortunately it also seems there has been no movement on this since Feb.
https://github.com/excalidraw/excalidraw/issues/4850

**Comment by zsviczian** [comment]
Fixed in 1.7.21 - I will release it later today.
