### ISSUE TITLE
[Bug] Pasting / Uploading Screenshot into Excalidraw

### ISSUE THREAD

**Issue by 23727** [zsviczian/obsidian-excalidraw-plugin#620]
**Describe the bug**
I take a screenshot of something on macOS and paste it (also tried to upload directly) to Excalidraw. I receive error messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/84650530/167791261-777ce9f4-1e37-4b3c-ae71-0455df448abd.png)

**Environment (please complete the following information):**
 - OS including version: macOS Monterey v12.3.1
 - Plugin version: 1.6.28
 - Obsidian version: 0.14.6

**Comment by zsviczian** [comment]
I am not able to reproduce the error.
Is this something that regularly (always) happens when you insert a screenshot?
Do you see an error message in Obsidian Developer Console (CMD+SHIFT+I/Console tab).

**Comment by 23727** [comment]
Hi, @zsviczian 

I started using the plug-in recently, and it happens consistently (always). I will try to uninstall and reinstall.

Here is the log: [obsidian.md-1652416105692.log](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/8684083/obsidian.md-1652416105692.log)

I hope it helps

**Comment by zsviczian** [comment]
I will investigate a bit further

**Comment by zsviczian** [comment]
I added some additional error handling in 1.6.29, but I am unable to reproduce the error how ever hard I try

**Comment by 23727** [comment]
Thank you @zsviczian
