### ISSUE TITLE
Error displaying note title label when clicking on a link

### ISSUE THREAD

**Issue by accept82** [zsviczian/obsidian-excalidraw-plugin#621]
Good afternoon! Help solve the problem
- if you made a link to the note, then when you click on the note, the name of the note appears and it accompanies me everywhere (sometimes it is not shown and I'm glad about it, but this happens very rarely)
This thing is very annoying, especially if you need to read or write something
How can I get rid of her?

https://user-images.githubusercontent.com/90281362/167928691-a4b933ef-f566-4fc3-8f94-be7922121414.mp4

**Comment by zsviczian** [comment]
thanks. I am aware of the issue, I just haven't prioritized it high to resolve it. I will look into it.

**Comment by accept82** [comment]
Good afternoon, thank you very much for your time. I really hope that a fix will be released in the next releases

**Comment by zsviczian** [comment]
I've made some changes, hopefully, these will resolve this error. I will release the new version (1.6.29) tomorrow.

**Comment by accept82** [comment]
Good afternoon! Thank you for your prompt response to this issue, looking forward to the new fix!

**Comment by accept82** [comment]
Installed the new plugin update (1.6.29) but unfortunately the problem remains, can you confirm that the problem has been fixed in this release?

**Comment by accept82** [comment]
I also found that if you hold on the links and a shortcut appears, then everything is ok when you go, but if you quickly click on the link (and I do it quickly), then the problem described above in the messages remains. I really hope that this bug will be fixed. He really gets in the way!
