### ISSUE TITLE
Zen mode in small window issue

### ISSUE THREAD

**Issue by shawnpaak** [zsviczian/obsidian-excalidraw-plugin#623]
**Describe the bug**

Decreasing the window size in Zen mode increases the size of the bottom menu. 
In fact, Zen mode doesn't work in a small window.

In addition, I want to adjust the size of the Top menu(Blue box) 
and the menu at the bottom(Red circle) is it possible change the 'style.css' ?
If possible, which part of the value should I modify?

I'd greatly appreciate any help you can offer.

**Screenshots**
![Screenshot 6](https://user-images.githubusercontent.com/103835042/168453573-00751654-c814-4c47-a260-611044c85db9.jpg)

![Screenshot 7](https://user-images.githubusercontent.com/103835042/168453578-cfb7c297-d485-42cd-8217-98e9fe19c699.jpg)

**Environment :**
 - OS including version: mac OS Monterey 12.3.1
 - Plugin version: 1.6.28
 - Obsidian version: v.0.14.6

**Comment by zsviczian** [comment]
You can tweak the sizes with a css snippet. Extract this file ([excalidraw-tweaks.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/8736805/excalidraw-tweaks.zip)) and copy the .css to your Vault/.obsidian/snippets folder. Then open Obsidian settings, click Appearance and scroll down to CSS Snippets. Click to refresh the list and activate the snippet. This should solve the problem for you. You can adjust size by changing the width and height figures in the snippet.
