### ISSUE TITLE
Cannot load any library

### ISSUE THREAD

**Issue by ultron** [zsviczian/obsidian-excalidraw-plugin#625]
**Describe the bug**
Loading a library of predrawn shapes fails. 
No error message is given but no shapes appear.

**To Reproduce**
1. In Excalidraw, go to Library (0)
2. Click on Load
3. Select a file with a library downloaded from https://libraries.excalidraw.com/
4. Library is not loaded. No error is given.

**Expected behavior**
Library is loaded into the palette.

**Environment (please complete the following information):**
 - Tested on both Windows and Linux with the same result.
 - Plugin version: 1.16.29
 - Obsidian version: 0.14.6

**Additional context**
Tested on 1.16.24 and the problem did NOT occur.
Upgraded to 1.16.29 and the problem occurs.
I've tried a few different libraries, restarting obsidian, reinstalling excalidraw plugin, and clearing all my existing libraries (so now I have none)

**Comment by nihitkhandelwal-eng** [comment]
I am also experiencing the same.

**Comment by a20110** [comment]
Same here.

**Comment by daogilvie** [comment]
Hi @zsviczian, firstly thanks for creating a great plugin!

I'm also unable to add libraries, with no obvious error or feedback as to why.

I'm on Macos 12.4, Obsidian 14.6, plugin 1.16.29.

I've tried with clean installs of both Obsidian and the plugin, and in a new empty vault.

I doubt it's related but I do see a 404 error in the console when I open the library panel:

```
GET https://unpkg.com/@zsviczian/excalidraw@0.11.0-obsidian-20/dist/excalidraw-assets/Virgil.woff2 net::ERR_ABORTED 404
```

(It looks like another comment about this has been added to closed issue #20)

**Comment by zsviczian** [comment]
There were some changes made to libraries in the core excalidraw package. It seems this has an impact. I can reproduce the issue. I will check what is going on…

**Comment by zsviczian** [comment]
I am investigating now... until I find the problem, I found a workaround that works. You can drag and drop an .excalidrawlib file from your OS File Explorer onto the canvas and it will be added to the library (at least on Windows this works for me).

**Comment by zsviczian** [comment]
Good news! Load library button also does not work on excalidraw.com... At least it is not something that I broke :)

**Comment by zsviczian** [comment]
Found the solution. Will release it in 1.6.30 soon.

**Comment by nihitkhandelwal-eng** [comment]
You are awesome!
Thanks!

**Comment by nihitkhandelwal-eng** [comment]
Just a follow up:
Some of the library files load up in the "excalidraw section" & some are loading up in the "personal library", for example: the biology set loads in the excalidraw, but "awesome icons" shows up in personal library

**Comment by zsviczian** [comment]
The personal library and the excalidraw sections were introduced a few months ago. I can imagine that older libraries don't have the necessary metadata and are loaded as personal libraries.

**Comment by nihitkhandelwal-eng** [comment]
Okay, thanks for the clarification & sorry for stretching out this conversation but I do have one more thing, where I need your help, it's about getting the mindmap script to work. [I posted this in discord as well](https://discord.com/channels/686053708261228577/840286238928797736/976517698186014761)
