### ISSUE TITLE
Black text convert into white when editing and writing on mobile

### ISSUE THREAD

**Issue by Stepanvar** [zsviczian/obsidian-excalidraw-plugin#626]
**Describe the bug**
I wrote some text in black color (#000000) and exit from text block. Then I double clicked on text and it all was selected and has a white color already. No changes in stroke. Then I moved cursor to the end of line. Text was still white even unselected and after exiting text block it became black again. With other colors it didn't happen. Probably it is because **the light mode**. While writing it is white too. I use Android  v 11, Phone: redmi note 9 pro, miui version 12.5.2.

**To Reproduce**
1. Create text block (8)
2. Set color as black (#000000) default
3. Start typing
4. Text became white
5. Exit text block
6. Edit block
7. Text became white

**Expected behavior**
It should be still black because white color is unreadable on white canvas

**Screenshots**
![0Mode](https://user-images.githubusercontent.com/84638149/168815643-75971d06-c4af-4f2d-9b1a-9b25dc34b528.jpg)
![1](https://user-images.githubusercontent.com/84638149/168815762-116bebe5-4bc7-4733-9923-77e5d980b806.jpg)
![2](https://user-images.githubusercontent.com/84638149/168815844-f62b9515-5c4d-4d08-9242-a5bac
![3](https://user-images.githubusercontent.com/84638149/168815869-8ba600eb-1347-4ab5-9c1c-1cfee57f04f7.jpg)
75a2604.jpg)

**Environment (please complete the following information):**
 - Android  v 11, Phone: redmi note 9 pro, miui version 12.5.2
 - Plugin version: 1.6.29
 - Obsidian version: 1.2.0 (50)

**Additional context**

**Comment by zsviczian** [comment]
Based on the screenshot you are using Excalidraw in dark mode, but with a white canvas color.
In dark mode colors are inverted. This might be a bit confusing, but in this case black is white and white is black, thus #000000 will be displayed as white. To check change the canvas color to a different color e.g. red, and you will see the text in white. If you want a white canvas, I recommend that you switch to the light theme.

**Comment by Stepanvar** [comment]
Thank you for your answer. I know about text in white while editing. However, in any theme mode I choose while editing text is very hard to see(in dark mode the text in black while editing and in light mode - white). I walk around this two ways: just changing color of text on gray and create text in the bottom of the display(then appear black square)

![Screenshot_2022-05-25-09-46-05-459_md obsidian](https://user-images.githubusercontent.com/84638149/170198005-65ce2eca-d879-43c2-bd37-567b53ee1d89.jpg)

![Screenshot_2022-05-25-09-46-17-122_md obsidian](https://user-images.githubusercontent.com/84638149/170197970-60b45290-2852-411a-8c05-b3809df6f8df.jpg)
