### ISSUE TITLE
color picker preset hotkey can't work

### ISSUE THREAD

**Issue by HibariX** [zsviczian/obsidian-excalidraw-plugin#627]
**Describe the bug**
When I use "Show stroke color picker" by pressing the key "s", cannot via "12345qwertasdfg" to select the color. Similarly, "Show background color picker" by pressing the key "g", it doesn't work too.

**To Reproduce**
1. Press the Keyboard "s"
2. Press preset hotkey is don't work

**Expected behavior**
When I press the preset hotkey like "12345qwertasdf" one of them, It can change the storke color.

**Screenshots**
<img width="875" alt="image" src="https://user-images.githubusercontent.com/54231315/169197066-616d48e8-d45a-47a6-bb4d-c934503c9076.png">

**Environment (please complete the following information):**
 - OS including version: macOS Monterey 12.3.1
 - Plugin version: 1.6.30
 - Obsidian version: 0.14.6

**Additional context**
one day I update the excalidraw plugins, but after this function can't work.

**Comment by anatoliibakhtin** [comment]
same situation, attached a [video file:](https://1drv.ms/v/s!Aug1AU2reREylj1o90yfAVyl98Xz?e=hfaJhf)

**Comment by HibariX** [comment]
There is a temporary solution. I put the local Obsidian excalidaraw plugin folder in `main.js`, `manifest. json`, `styles. CSS` replace with [Excalidraw 1.6.28](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.6.28) Files in assets

**Comment by zsviczian** [comment]
so in your assessment this feature broke after 1.6.28?

**Comment by HibariX** [comment]
I tested it and it worked fine after rolling back to 1.6.28. It may also be 1.6.29, but I haven't tested it.

**Comment by anatoliibakhtin** [comment]
> so in your assessment this feature broke after 1.6.28?
@zsviczian, yes

**Comment by zsviczian** [comment]
fixed in 1.6.31. will release later today.
