### ISSUE TITLE
LaTeX support did not load. Using fallback solution. Try checking your network connection.

### ISSUE THREAD

**Issue by Huary007** [zsviczian/obsidian-excalidraw-plugin#628]
I have updated to the latest version 1.6.31, but when I open an excalidraw drawing containing a formula, I get the following error message: "LaTeX support did not load. Using fallback solution. Try checking your network connection."
My computer system is win10, and the version of obsidian is 0.14.6.
There is no error message when opening safe mode. When I open only the excalidraw plugin I get the error message. So I suspect that there is an error in excalidraw.

**Comment by zsviczian** [comment]
Unfortunately, I haven't been able to resolve to load of the LaTeX libraries. In my experience, once every 10-15 times this error message is displayed, and I can't find the root cause.  

Did you try to reload Obsidian? Did that solve your issue?

**Comment by Huary007** [comment]
I had this problem after May 17, 2022. Until now I have not found a solution. Whenever I open the excalidraw file containing formulas, it keeps reporting the error and then obsidian gets stuck. This may be because I inserted too many formulas in excalidraw? I tried restarting and reinstalling obsidian, but it still reports the error. I tried to return excalidraw to version 1.6.28 and that didn't solve the problem either.

**Comment by zsviczian** [comment]
when you click this link does this open?
https://cdn.jsdelivr.net/npm/mathjax@3.2.1/es5/tex-svg.js

**Comment by Huary007** [comment]
I can' t access this site.

**Comment by zsviczian** [comment]
see here: https://docs.mathjax.org/en/latest/web/start.html

![image](https://user-images.githubusercontent.com/14358394/169867667-a0f86d1d-7427-4e90-885b-a4c7a5e152a3.png)


Does this work for you?
https://unpkg.com/mathjax@3.2.1/es5/tex-svg.js

**Comment by Huary007** [comment]
I tried to open these six URLs. Only [https://cdnjs.com/](https://cdnjs.com/) and [https://unpkg.com/](https://unpkg.com/) are accessible properly.

**Comment by zsviczian** [comment]
I added a setting for you to choose which server you download mathjax from. You will need to change it in settings under compatibility features.

I will release the change in the coming days, in the meantime, however, you can install the change temporarily, by downloading this zip file: [main.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/8756892/main.zip), unzipping it and copying main.js into your `Vault/.obsidian/plugins/obsidian-excalidraw-plugin` folder.

![image](https://user-images.githubusercontent.com/14358394/169873679-a62fe000-4354-4a5f-bd68-30d77a20fb0e.png)

**Comment by zsviczian** [comment]
you may need to restart obsidian after changing the setting in compatibility features for the change to take effect.

**Comment by zsviczian** [comment]
I deployed the fix in 1.6.32

**Comment by Huary007** [comment]
Thank you so, so much! I've updated to version 1.6.32. After switching to unpkg I was able to use excalidraw normally. Excalidraw has become an integral part of my daily work. It really bothered me for a long time when LaTeX support didn't work. You really did an amazing job, thank you so much!

**Comment by EricR** [comment]
@zsviczian I’ve also run into a similar issue when network connectivity is unstable. Is there a reason MathJax needs to be loaded remotely? Couldn’t it be bundled with the plug-in and loaded locally via an obsidian:// URL? I imagine that would also benefit security, as it would mean you aren’t fetching and loading JS over the Internet within the context of Obsidian’s runtime whenever the plug-in loads.
