### ISSUE TITLE
Some drawings don't render

### ISSUE THREAD

**Issue by JuanM04** [zsviczian/obsidian-excalidraw-plugin#63]
**Describe the bug**
After the 1.1 update, some drawings doesn't work.

![image](https://user-images.githubusercontent.com/16712703/119404865-ce87ad00-bcb6-11eb-8a31-1db258b808b1.png)

**To Reproduce**
1. Add [these files](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/6534869/drawings.zip) to your vault.
2. Create this file:
```md
# Test

![[Cicloalcanos 1.excalidraw]]

![[Cicloalcanos 2.excalidraw]]

![[Cicloalcanos 3.excalidraw]]

![[Cicloalcanos 4.excalidraw]]
```

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Obsidian v0.12.3
 - Excalidraw Plugin v1.1.5

**Additional context**
It worked before v1.1

**Comment by zsviczian** [comment]
I am sorry to hear that! Thanks for raising. I will investigate tonight.

**Comment by zsviczian** [comment]
Ok. I can reproduce the error. I hope to correct it tonight.
![image](https://user-images.githubusercontent.com/14358394/119493433-7907da80-bd60-11eb-8bdc-0b6182c71226.png)

**Comment by zsviczian** [comment]
1.1.6 resolves the issue. Please test.

**Comment by JuanM04** [comment]
It works, thank you!
