### ISSUE TITLE
Drag png files onto diagram to embed image

### ISSUE THREAD

**Issue by dcoales** [zsviczian/obsidian-excalidraw-plugin#632]
If I paste an image from the web onto an Excalidraw diagram it imports the image as a png file and embeds it in my diagram.  This is great.  If I already have a png file in my vault however, I don't know how to add this as an embedded image in an Excalidraw diagram.  It would be great if I could drag and drop an image file onto Excalidraw and instead of adding a text link to the file it actually embedded the image in the same way it would if I pasted the image.

Thanks.

**Comment by dcoales** [comment]
Okay I feel foolish now.  Turns out you can already do this by holding the control key and dragging the file onto the diagram. One caveat though is that it includes the full path to the file rather than just the file name and if you move the file then the link is lost.

Similarly renaming the file causes the link to be lost.  Would it be possible to
a) change the drop behaviour to create the shortest possible link to the file to avoid the full path where possible 
b) propagate file name changes to the Embedded Files section of the backing markdown file.

**Comment by zsviczian** [comment]
First reaction... including the path to the file should not cause the problem, obsidian will update the path as well. What is more likely is that the way I cache images for copy/paste between drawing, or autosave overwriting the file is causing the problems.... it may be that I broke this functionality when I was implementing the sync support for shared vaults as I did not test this use-case.... so lots of options here for what might be wrong. All I know is that I have tested this in-depth in the past and it worked well at the time.

**Comment by zsviczian** [comment]
It is my new shared vault sync support causing the problem. I'll try to release a fix today. Sorry...

**Comment by zsviczian** [comment]
fixed :). Will release an update tonight.

**Comment by dcoales** [comment]
Thank you.  I though I was going mad :-)  It seemed to work then not work
then work again.

**Comment by zsviczian** [comment]
solved in 1.6.32
