### ISSUE TITLE
Embedded drawings are not updated 1.6.32

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#637]
**Describe the bug**

**Embedded drawings** **stops updating** if I start **interacting** with elements on the **parent canvas**. Embedded drawings are updated if the parent canvas is open and there has been no interaction with items on it. 

[demonstration](https://1drv.ms/v/s!Aug1AU2reREylkVX1MVnDVpjLBur?e=nwwO2W)

This problem did not exist in version 1.6.31.

**To Reproduce**
1. create canvas (main)
2. embed drawing
3. interact with the elements on the main canvas
4. go to inserted drawing
5. draw
6. go back - no changes are visible (you need to reload the parent canvas so that the embedded images are automatically updated again)

**Expected behavior**
Embedded drawings will update automatically, without the need to reload the parent canvas, with the ability to interact with elements on it. 
In an extreme case, it could be a script that would reload the entire canvas manually.

**Comment by zsviczian** [comment]
I may have misunderstood you. It seems to work as designed.

I am not updating all the open drawings unless the pane is active, but that is on intention, to avoid a constant performance drag every time autosave is completed.

https://user-images.githubusercontent.com/14358394/170524820-b8ef4136-a9d5-4a4f-bf44-032504508b3f.mp4

**Comment by anatoliibakhtin** [comment]
@zsviczian try to repeat my steps 1 in 1, now you are using 2 different windows (it works for me here as well), I do everything in one window.

(Just to be on the safe side, I've done it all over again)

https://user-images.githubusercontent.com/71871141/170553023-dff599ff-655f-4f1e-a868-dacf9ab3c75d.mp4

Steps:

1. Create a canvas Parent 
2. Create a canvas Child 
3. Open canvas Parent
4. Insert canvas Child into Parent
5. Close all windows
6. Open canvas Parent
7. Interact with elements on the Parent (this seems to be where the problem starts)
8. Open the Child in the same window
9. Interact with the Child's elements
10. Back to Parent
11. Child unchanged

Conclusion: After interacting with the parent canvas - the child (embedded drawing) stops updating **when using the same window**. If you only interact with the kids (going straight in, no interaction with the parent), everything updates itself.

**Comment by zsviczian** [comment]
Thanks! I was able to reproduce the bug!

**Comment by zsviczian** [comment]
Resolved in 1.6.33

**Comment by anatoliibakhtin** [comment]
@zsviczian Thanks a lot ! everything works great!
