### ISSUE TITLE
Subscript and Superscript Text

### ISSUE THREAD

**Issue by tinyheero** [zsviczian/obsidian-excalidraw-plugin#64]
**Is your feature request related to a problem? Please describe.**

Chemical formulas contain subscripts and right now there is no way to add a subscript.

**Describe the solution you'd like**

An option to specify a subset of the text to be a subscript or superscript

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by zsviczian** [comment]
I raised an issue with Excalidraw on your behalf: https://github.com/excalidraw/excalidraw/issues/3636

**Comment by tinyheero** [comment]
Thanks @zsviczian!
