### ISSUE TITLE
Script  "Add Link to New Page and Open" does not use a template for a new drawing.  

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#643]
The script ["Add Link to New Page and Open"](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Add%20Link%20to%20New%20Page%20and%20Open.md) is very cool ! But now it doesn't use templates for the new drawing specified in the settings. This problem doesn't burn much it would be great if you fix it and script will create new drawing with template specified in the settings. 

https://user-images.githubusercontent.com/71871141/171159289-ee94e510-dd28-49a1-9b83-d0a131165c61.mp4

Thank you !

**Comment by zsviczian** [comment]
seems the issue is not with the script, but with ExcalidrawAutomate. I will fix it in a few days. Planning to release the next update next Monday.

**Comment by zsviczian** [comment]
fixed. You should be able to download the fixed script from the scrip library.
