### ISSUE TITLE
Replace text display inside a link

### ISSUE THREAD

**Issue by Missionary2112** [zsviczian/obsidian-excalidraw-plugin#648]
**Is your feature request related to a problem? Please describe.**
I would like to replace link title with any text. 
![Screenshot - 2022-06-03 09 49 07 (Obsidian)](https://user-images.githubusercontent.com/98799613/171910249-17941d1c-adb7-4fd0-9658-3f31c2ed2378.jpg)
In this example, instead of displaying `Dad`, I would like to display `Father`, exact principle in Obsidian.

**Describe the solution you'd like**
- The link can be displayed in any text with this format `[[link | text]]`

**Describe alternatives you've considered**
- I can rename the file but it's not intuitive and time-consuming.

**Comment by zsviczian** [comment]
Please install the "Set link alias" script from the Script Engine library.

https://user-images.githubusercontent.com/14358394/172128571-53e36948-5fdc-4414-a8d3-2daa950b54e7.mp4
