### ISSUE TITLE
Can I sync Excalidraw plugin in Obsidian dark/light mode with the system settings or at least keep last one I have set?

### ISSUE THREAD

**Issue by AMGMNPLK** [zsviczian/obsidian-excalidraw-plugin#65]
I have to click in the mode to set dark mode for every note that I take.

I would like to get this synced with the system config or remember the last one.

**Comment by zsviczian** [comment]
You can use templates for this: https://youtu.be/oNPYZEpmuJ8

**Comment by zsviczian** [comment]
Once 1.2.0 is released to Community Plugins you'll be also able to create a markdown template with your preferred settings. Obsidian v0.12.9 now supports synchronizing settings - including Excalidraw plugin settings. If you do not use insider builds, then you'll need to wait a few days (maybe weeks), but the settings sync is on its way (for all plugins, not just Excalidraw).

**Comment by sortedcord** [comment]
Hi, I believe this caters to if one wants to set a (fixed) canvas color scheme. Since, my pc switches between light and dark mode depending on the time of the day, I would like excalidraw to follow the Base Color Scheme of obsidian as it changes.. Is there any way I could do that?

**Comment by zsviczian** [comment]
yes, this is supported. check in settings. Under Excalidraw appearance and behavior
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/fcab0709-c0b8-4697-93d7-687702156066">
