### ISSUE TITLE
Show specific part of drawing on file preview

### ISSUE THREAD

**Issue by Fdms-3741** [zsviczian/obsidian-excalidraw-plugin#650]
**Is your feature request related to a problem? Please describe.**
Whenever I'm solving a big math problem (I like to do it by hand and keep it in my notes for later reference), there are specific parts of the drawing that I'll want to reference later in my notes. When the drawings are small, the image preview is excellent to make such references, but when the file is big I need to make a lot of other small drawings to segregate the parts that I'm interested in referencing later. 

**Describe the solution you'd like** 
It would be nice to have either a shortcut to create a new drawing and embed it automatically or have the rectangles be referencable in a way that they define the image preview boundaries of the image preview. 
I'm aware of the button for embedding an image and that it can be used for excalidraw drawings, this button could change its behaviour so that if the user types a non-existing name it creates an excalidraw image, embeds it and (optionally) opens the image on the active pane.
Even with the quick approach IMO the first one would be better because it would reduce the number of drawings made and make it easier to work on a file in case I need to check something somewhere else and not on the defined area. In any case, I believe either option would fit nicely with the plugin.

**Describe alternatives you've considered**
My current alternative is to repeat a quite tedious process:
1. Create a new drawing
2. Set a title so I can find it
3. Find the file through the aforementioned "insert image" menu or Ctrl+drag it from the Excalidraw folder

**Additional context**
I believe there's nothing else to say except thank you for this extraordinary and feature-rich plugin!

**Comment by luutuankiet** [comment]
+1 this feature request. Would powercharge the already great linking ability of obsidian / excalidraw!

**Comment by trlee02** [comment]
If you haven't already seen, this feature was implemented. See this [video](https://www.youtube.com/watch?v=yZQoJg2RCKI).
