### ISSUE TITLE
drag & drop link of file/folder from OS to canvas

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#654]
hi 🌻
**feature/problem**

Sometimes I need to organize folders and files on my computer, for this it is convenient for me to use the excalidraw canvas (I first draw what is contained in the folder, file, then I arrange them on the canvas in heaps), but the links are not inserted when dragging

**I'd like**

Ability to add link to canvas (Control + drag & drop) file/folder just like i can do it now with .md document. Those. I don't need these files in storage, it's temporarily.

**video**

https://user-images.githubusercontent.com/71871141/173010580-3add7157-fa55-4a6c-b879-e02d3bade7da.mp4

thanks for your attention !

**Comment by zsviczian** [comment]
You mean the link would point to a location on your desktop but outside your Vault?

**Comment by anatoliibakhtin** [comment]
Yes, I understand as soon as I move the files to another location or rename it, the links stop working in Vault.

**Comment by anatoliibakhtin** [comment]
!!! https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.9.24 😍

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/71871141/4f8bc599-9e11-4dfc-b0d0-594aedab384e)

You can also see from the screenshot how much has changed `obsidian-excalidraw-plugin` WOW !!!
