### ISSUE TITLE
Text suddenly detached from the shape/box when moving or dragging to duplicate

### ISSUE THREAD

**Issue by KimhengMok** [zsviczian/obsidian-excalidraw-plugin#657]
Obsidian Version: v0.14.15 (Installer Version v0.12.15)
Excalidraw Plugin Version 1.6.33
MacOS Big Sur: Version 11.5.2

Right now, I'm facing an issue when duplicating elements.
The text is getting out of shape when duplicating or moving.

It's been happening for a while now. I'm really not sure about what exactly is causing that, but it happens after I'm editing excalidraw for about 3-5 minutes later or after I'm creating several elements.
This bug sometimes spreads to the other shapes/elements if I undo the action when I encountered the bug.

I realise it becomes messy after drawing a huge graph, which might sometimes accidentally lead to the deletion other elements.

I hope my description of this issue clear enough to help. 
You can find the attached bug illustration video below.

Thank you.

https://user-images.githubusercontent.com/84358917/173106205-1e77ebb6-1e77-4746-895d-0fbcba23e147.mp4

**Comment by zsviczian** [comment]
The description is clear.

**Comment by zsviczian** [comment]
I was able to reproduce like this:

https://user-images.githubusercontent.com/14358394/173406461-061e4164-a000-483e-a3ad-a9154e2174c2.mp4

**Comment by zsviczian** [comment]
So, I am not sure I was able to address the original problem, but I found the root cause for the error I was able to reproduce. I will release it with the next release.

**Comment by KimhengMok** [comment]
@zsviczian Great to hear that, anyway thank you for your great plugins. 🙏🏼 It helps a lot, especially for those who struggle to learn just by text. :)

**Comment by zsviczian** [comment]
> especially for those who struggle to learn just by text. :)

Which is over 60% of the population. Interestingly those who think in "text" are the minority, but until now tools were not up to the task to support the majority.

**Comment by zsviczian** [comment]
I resolved the root cause of this about a month ago. I've not experienced the issue since.
