### ISSUE TITLE
obsidian version 0.15.1, excalidraw can't move pages and edit content in a new window.

### ISSUE THREAD

**Issue by MILKMILKKING** [zsviczian/obsidian-excalidraw-plugin#662]
![image](https://user-images.githubusercontent.com/69726213/174012669-083f755f-c7d9-4560-bf8f-ddaa3721e3da.png)
excalidraw can't move pages, edit content in a new window. It is almost impossible to perform any operations.

And as the picture shows, the interface icons are enlarged a lot.

**Comment by anatoliibakhtin** [comment]
@MILKMILKKING  hi,💐 Try changing the theme in obsidian. 
Now I would give this answer as you have given little context: how it happened, when it first happened, etc. it is much easier to solve a problem when more is known about it rather than less.

**Comment by zsviczian** [comment]
I am aware and working on it. Unfortunately, this is a difficult change because Obsidian has made some big changes. Right now I can't yet guarantee that Excalidraw will work in Obsidian popup windows... but I'll try to make it work.

**Comment by zsviczian** [comment]
You can manually install the 1.7.0 pre-release. It addresses these problems.
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.7.0
