### ISSUE TITLE
v1.7.1 crashed

### ISSUE THREAD

**Issue by Steven-AA** [zsviczian/obsidian-excalidraw-plugin#663]
**Describe the bug**
![sp20220620_103900_458](https://user-images.githubusercontent.com/22387129/174515769-aa809672-5bea-4b92-836f-04b17a0d2c15.png)

**To Reproduce**

open any graph include brain graph

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS including version: win10
 - Plugin version:  v 1.7.1
 - Obsidian version:  v 0.15.2

**Additional context**

Obsidian crashed when I open Brain graph in another window.  I cannot open any excalidraw graph now, with or without new window.

**Comment by Steven-AA** [comment]
Everything works fine when I downgraded it to 1.7.0.
Also, pop out window works fine in v 1.7.0.

**Comment by zsviczian** [comment]
Yes, however, 1.7.0 is not going to be supported going forward. It required heavy changes to the core Excalidraw component which is not sustainable, and it also has a number of hidden errors that may not be visible up front but will trip you up later.

And also yes, I am aware of the issues with 1.7.1. Unfortunately given the changes to Obsidian architecture, some of these issues don't have a proper solution at the moment. That said, I am using 1.7.1 for some time now, and it performs mostly stable for me. I will be releasing 1.7.2 later today, which should bring more stability.
