### ISSUE TITLE
Support image in excalidraw

### ISSUE THREAD

**Issue by Yaozhuwa** [zsviczian/obsidian-excalidraw-plugin#67]
**Is your feature request related to a problem? Please describe.**
Some times we need to refer some image in our sketch.

**Describe the solution you'd like**
- Drag and drop any image onto the window/canvas
- Paste from image clipboard
- Support resize and roate image

**Comment by zsviczian** [comment]
Hi Yaozhuwa, awesome feature request. 
I am only developing the Excalidraw Obsidian plugin, not Excalidraw itself. Please raise this issue with the Excalidraw team here:
https://github.com/excalidraw/excalidraw/issues
