### ISSUE TITLE
Is there any way to bulk change the item width to a given value?

### ISSUE THREAD

**Issue by WaytrueDeng** [zsviczian/obsidian-excalidraw-plugin#670]
Sorry I can't write the script myself, So I have to ask for help here. 
There is a script to unify the width, but after that if I want to adjust them again, I don't know how to do it.

**Comment by zsviczian** [comment]
In the script library search for the `Set stroke width of selected elements` script

![image](https://user-images.githubusercontent.com/14358394/175764903-30b40be2-effb-4f03-858d-430dbe1c52e1.png)

**Comment by WaytrueDeng** [comment]
> In the script library search for the `Set stroke width of selected elements` script
> 
> ![image](https://user-images.githubusercontent.com/14358394/175764903-30b40be2-effb-4f03-858d-430dbe1c52e1.png)

Sorry my English is not precise, I mean that  the weight in the sticky note weight and height
