### ISSUE TITLE
Is there a way to  fasten  the binding of arrow between two items?not the magnetical way.

### ISSUE THREAD

**Issue by WaytrueDeng** [zsviczian/obsidian-excalidraw-plugin#673]
Excalidraw provide us the feature like the magnet it which can bind the end of arrow to the close item. It is very good but when we sometime move a third item approach the connection point, the arrow may change it's binding point to the third one, which is annoying sometime.

Some white board apps provide the feature to bind arrow or line end point to the middle points of rectangle 4 lines then it could never be changed by coincidence. Could we do that in excalidraw?

**Comment by zsviczian** [comment]
You can hold down the control key when moving objects to avoid automatic binding.

**Comment by WaytrueDeng** [comment]
> You can hold down the control key when moving objects to avoid automatic binding.

Thanks, mainly not the happening in the movement itself, it will happen if I put the third one too close to connection point, then it will change the bind point to the new one ,If I move again the arrow will move following the third one, which is truly annoying sometime.

**Comment by WaytrueDeng** [comment]
> You can hold down the control key when moving objects to avoid automatic binding.

Sorry I don't know how to program, I have to ask for help  here. I guess could we define this endpoint belong to the given item in the config file, If we don't actively change the endpoint, then the relationship will never be changed?

**Comment by WaytrueDeng** [comment]
> You can hold down the control key when moving objects to avoid automatic binding.

right now, maybe I should use the lock function:)
