### ISSUE TITLE
A way to transform beautiful svg files into even more beautiful excalidraw files

### ISSUE THREAD

**Issue by pterusgithub** [zsviczian/obsidian-excalidraw-plugin#679]
**Is your feature request related to a problem? Please describe.**

-> frustrated =  not really :-)

**Describe the solution you'd like**
Is it possible to import a classic svg in a way that transform drawing into a beautiful excalidraw style ? 

import 
![a square](https://upload.wikimedia.org/wikipedia/commons/d/dd/Square_-_black_simple.svg)
would result in something like this
![something to play with](https://miro.medium.com/max/1400/1*Wx0UhKihPuCbMeXb7mvcmg.gif)

It would be very interesting if it works with more complexe file like this:

![a beautiful svg file](https://craftmegood.com/wp-content/uploads/2021/08/swirl-butterfly-free-svg.jpg)

Is there any way to do so ?

Thank you

**Comment by zsviczian** [comment]
I've seen an attempt to convert SVG into Excalidraw, but it could only support simple shapes/paths.
This is my solution :) https://youtu.be/pQ-V6J3cCOY

**Comment by pterusgithub** [comment]
Thank you very much. 
It seems that I've adopted very similar solutions  ;-) ... But when I saw your video, it clearly appeared to me that I need to improve my way of using the line tools ;-) 
Best regards !

**Comment by zsviczian** [comment]
Seems I am going to be releasing importSVGtoExcalidraw in 1.7.27. If things go well, I might release it today, else tomorrow.

**Comment by Hexara7777** [comment]
How to achieve this functionality? I have some SVG images/files that I want to import as an excalidraw format (to avoid every single imported svg file to be saved as a separate file in my vault's attachments folder)

**Comment by MahmadSharaf** [comment]
> How to achieve this functionality? I have some SVG images/files that I want to import as an excalidraw format (to avoid every single imported svg file to be saved as a separate file in my vault's attachments folder)

Click on Obsidian Icon, under Insert actions, click on the last icon called "Import an SVG file as Excalidraw strokes"
