### ISSUE TITLE
Provide location to export images to

### ISSUE THREAD

**Issue by tinyheero** [zsviczian/obsidian-excalidraw-plugin#68]
**Is your feature request related to a problem? Please describe.**

Not immediately obvious where an exported image is saved to. I didn't realize it saved it into the same folder as the "Excalidraw folder"

**Describe the solution you'd like**

A popup (?) or setting to decide where exported images go. 

**Describe alternatives you've considered**

N/A

**Additional context**

First, great work on this plugin. It is absolutely amazing!

Some additional context, when exporting an image the intent is generally for me to share the image with a collaborator. I don't intended to keep the image in the vault since I have the .excalidraw file already and it appears in my pages. As such, it would be ideal for me to save to say my "Desktop" or "Downloads" folder, which are folders I originally clear. Rather than having to go into the "Excalidraw folder" and then clearly out that .png or .svg each time.

**Comment by zsviczian** [comment]
Thanks. I will explore this feature request and get back to you.

**Comment by zsviczian** [comment]
Export option added to [1.2.0-alpha-1](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases)
