### ISSUE TITLE
Parse output markdown outside of excalidraw

### ISSUE THREAD

**Issue by antonmihaylov** [zsviczian/obsidian-excalidraw-plugin#688]
This is not a feature request for the plugin, but a roadblock in integrating the output of this plugin into another system. I have a node app that needs to read the output from this plugin, parse it and turn it into a PNG/SVG preview.

My plan is to use exportToBlob from to do that @excalidraw/excalidraw. But first I must parse the data out of the markdown.

What I've tried is to use ExcalidrawData class, but it depends on an ExcalidrawPlugin instance, which seems to have a lot of excalidraw-related data and would be hard to mock.
I also tried to use parts of the ExcalidrawData code to create a make-shift parser, but I still can't figure out which parts are related to excalidraw and which are just for parsing the markdown.

Is there an easy way to do this that I'm missing, or am I on the right path, just need to work a bit more on it?

**Comment by zsviczian** [comment]
ExcalidrawAutomate has functions for this purpose.
https://zsviczian.github.io/obsidian-excalidraw-plugin/API/introduction.html

See createPNG(), it does exactly what you want.
https://zsviczian.github.io/obsidian-excalidraw-plugin/API/utility.html#createpng

**Comment by antonmihaylov** [comment]
This seems like it could work
Meanwhile, I figured we can just enable the Auto export to SVG option and embed that instead.

Thanks for the quick response and for the awesome plugin!
