### ISSUE TITLE
Rubber feature missing

### ISSUE THREAD

**Issue by 3nzoFerrari** [zsviczian/obsidian-excalidraw-plugin#69]
I'm missing a rubber I can select to erase single lines of my writings. It would be nice if I could select the rubber using the lower button of my stylist (Wacon Bamboo Ink). 
It's a really nice plugin. Thank you!

**Comment by zsviczian** [comment]
Hi! This is an excellent feature idea. Please register the request with the Excalidraw project. I am only developing the integration of the Excalidraw component into Obsidian, I don't develop Excalidraw itself.

https://github.com/excalidraw/excalidraw/issues

**Comment by zsviczian** [comment]
this issue was resolved just today with 1.6.18
