### ISSUE TITLE
Issue with updating links after renaming

### ISSUE THREAD

**Issue by Ljqd** [zsviczian/obsidian-excalidraw-plugin#692]
https://user-images.githubusercontent.com/30119650/178106407-dc15dbbc-121a-48b1-8b82-41e123e24d49.mp4

As I've saw at #517 this feature's already implemented.

**Comment by Ljqd** [comment]
In addition, ExcaliBrain also doesn't recognize that link.
So, maybe it's I misunderstand something?
![excalibrain](https://user-images.githubusercontent.com/30119650/178120663-4c303b31-74d8-4354-a665-39504743fedc.png)

**Comment by zsviczian** [comment]
Yes, this is a little confusing at first, but once you understand it works well. Unfortunately, links work slightly differently for elements such as rectangles, lines, ellipses, etc., and text elements. This has partly a historical reason, as Excalidraw in Obsidian supported links before Excalidraw.com developed their link support, and for reasons of backward compatibility, I decided not to change my approach.

You should create links in text elements by typing the link directly into the text element. i.e. in your case, you should create a text element `[Let's create some link](Leaf A.excalidraw)` or `[[Leaf A.excalidraw|Let's create some link]]`, which will work as expected. In fact, for a text element, the link (as you've added it) will be overwritten by the link in the text element text.

In the case of a rectangle, or any other element that is not a text element, you can use the create link action to add a link, and that link will be updated and recognized by Obsidian as expected.

It is worth taking a look at the markdown view of the Excalidraw file, and you will better understand what is going on.

https://user-images.githubusercontent.com/14358394/178150502-f6770b62-d595-4e95-b3f3-53835450df2c.mp4

**Comment by Ljqd** [comment]
Okey, I got it
Really appreciate you for the detailed answer)
