### ISSUE TITLE
Set custom default size for preview windows

### ISSUE THREAD

**Issue by mateusfbsoares** [zsviczian/obsidian-excalidraw-plugin#696]
**Is your feature request related to a problem? Please describe.**
Everytime I open a specific preview window, I have to resize it for it to be the optimal size for me.

**Describe the solution you'd like**
It would be awesome if I could set a custom default window size for it on the plugin configurations to avoid having to resize it everytime I open it :)

**Describe alternatives you've considered**
I believe there's no alternative. I have to resize it everytime I open it.

**Additional context**
![reduced_gif4](https://user-images.githubusercontent.com/43099047/178519894-aa46264b-13b1-4974-8005-e7bf7ba2536e.gif)

**Comment by zsviczian** [comment]
The Hover Editor is not developed by me, nor is it part of the Excalidraw package. This is a request to the hover editor developer.

**Comment by mateusfbsoares** [comment]
Thanks! There is indeed a default window size setting in the Hover Editor plugin.
