### ISSUE TITLE
inserted picture not visible (only shows link)

### ISSUE THREAD

**Issue by 7flash** [zsviczian/obsidian-excalidraw-plugin#697]
**Describe the bug**
When I drag&drop picture it should show the image.. that is normal excalidraw behaviour.. but currently when using together with obsidian it only shows clickable link..

![image](https://user-images.githubusercontent.com/4569866/178651617-04b569b4-e3dc-44ed-be6f-9cdb42ea5274.png)

**Comment by 7flash** [comment]
Thanks.. that works when taking the picture from side bar vault.. but perhaps another issue when dragging a picture from the web browser.. it saves a link and not a picture as expected..

**Comment by zsviczian** [comment]
Why not copy/paste from the browser?

**Comment by zsviczian** [comment]
I just tried dragging an image into Microsoft Word from a browser. A link is inserted. 
I tried the same with Miro. An image was inserted.
My takeaway, there is no standard way to approach this. I think copy/paste is fit for purpose.

What is missing, and this is on the backlog for a long time but I haven't had the time to deal with it, is linking an image from the web. Currently you can only use images in Excalidraw that are stored in your Vault. This btw matches my use case. I do not like to link to images on the web, as I plan my PKM for decades... an links have a tendency of changing over a period of years... thus if I want to save something, I save my own copy.

**Comment by 7flash** [comment]
The issue that current behaviour differs from excalidraw behaviour I am used to.. where drag&drop the image from browser to document works by default..

**Comment by zsviczian** [comment]
I see. I did not notice this being different on excalidraw.com. I'll check if I can do something to address this situation.

**Comment by zsviczian** [comment]
I resolved this in 1.7.9. I will be releasing it later today.
