### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by KALKI-the-avataar** [zsviczian/obsidian-excalidraw-plugin#7]

**Comment by zsviczian** [comment]
Can you provide a bit more information. 
What did you experience? Did you have the background color of your drawing set to transparent or to a specific color? What behavior were you expecting when using the dark mode?

If you could attach a screenshot that would be immensely helpful.

**Comment by zsviczian** [comment]
I assume the issue was due to the transparent drawing background.
I added a white background to Excalidraw so even transparent will work ok with different themes. Hope this solves the issue.
