### ISSUE TITLE
Problem with link to header with space.

### ISSUE THREAD

**Issue by cybexmind** [zsviczian/obsidian-excalidraw-plugin#704]
Llink a note with a header containing the space character?

1. create a link [[note#header with space]] in a drawing
2. click link
3.  works partially, goes to the note but does not select the header.

**Expected behavior**
Goes to the note with the block header selected

**Environment (please complete the following information):**
 - OS including version: win10
 - Plugin version: last
 - Obsidian version: last

**Comment by zsviczian** [comment]
Thanks I will fix this. This seems like something I broke when I was working on markdown embed enhancements. I am currently on holiday, without access to my desktop… thus I can’t make any changes currently. It will take few weeks until I can get this resolved.

**Comment by cybexmind** [comment]
No problem, take it easy. Congratulations on your very useful plugin.

Il Gio 21 Lug 2022, 15:16 zsviczian ***@***.***> ha scritto:

**Comment by zsviczian** [comment]
Fixed it in 1.7.9. Will release it later today.
