### ISSUE TITLE
It would be cool if we can add pallete of styles for each shape

### ISSUE THREAD

**Issue by kksharma1618** [zsviczian/obsidian-excalidraw-plugin#706]
**Is your feature request related to a problem? Please describe.**
When creating diagrams like mind map or other thinking maps. There is a set of styles, I like to use for consistency. 
For example in mindmap the root node is rectangle with text. That rectangle should be of specific style (combination of stroke, background, font size and type and such). Then other child nodes should be of specific styles. Same goes for arrows, lines, circles. 
My problem is that currently, I have to do all of that manually. I will create a node, set all my consistent styles, then I will add another type of node, I again have to manually apply consistent style.

**Describe the solution you'd like**
It would be great if we can setup style pallets for each shape. Just like we provide stroke and background palletes to choose from predefined colors, we can provide a user-managed style pallete. A dropdown in this ui
![image](https://user-images.githubusercontent.com/2723026/179668502-1712b726-c700-4ea3-9171-0543866c942e.png)
We just pick the one we want, and it will fill all the relevant styles in that ui (stroke, background, font, etc).

Use case would be:
Creating pallete entry.
I create a shape. Setup it's style just the way I want. In UI I add it to the style pallete.

Using pallete.
I select shape tool from top bar. In style menu instead of changing each style individually I pick the style group I want from the pallete dropdown. It fills in all the style. And then I create the shape in canvas with that style.

**Describe alternatives you've considered**
I tried creating another document and adding all the shapes with all the styles I want. Then I have to manually copy style from there to the main document element. It doesn't work that well.

**Comment by zsviczian** [comment]
This is absolutely doable. It is a nice idea for a script engine script.
Also with very limited scripting knowledge you can create these templets for yourself with the script engine. I understand it is not so comfortable as clicking on the user interface, but something completely within your own controls to develop, customize and further refine.

**Comment by kksharma1618** [comment]
Thanks. I will look into the script engine.

**Comment by zsviczian** [comment]
I hope this short script example and video will help get you started.
Each Excalidraw script engine script can be assigned a command palette hotkey, so you can define your styles and use the command palette to choose between them.
One thing to pay attention in the video is how I use the code suggester to find out the valid values for fill style. You can apply the same trick for the other values as well.

Good luck!

```javascript
ea.getExcalidrawAPI().updateScene({
  appState: {
	currentItemStrokeColor: `red`, //string;
	currentItemBackgroundColor: `yellow`, //string;
	currentItemFillStyle: `cross-hatch`, //ExcalidrawElement["fillStyle"];
	currentItemStrokeWidth: 3, // number;
	currentItemStrokeStyle: `dotted`, //ExcalidrawElement["strokeStyle"];
	currentItemRoughness: 0, // number;
	currentItemOpacity: 100, // number;
	currentItemFontFamily: 0, //FontFamilyValues;
	currentItemFontSize: 20, //number;
	currentItemTextAlign: `right`, //TextAlign;
	currentItemStrokeSharpness: `round`, //ExcalidrawElement["strokeSharpness"];
	currentItemStartArrowhead: null, // Arrowhead | null;
	currentItemEndArrowhead: null, // Arrowhead | null;
	currentItemLinearStrokeSharpness: `round`, //ExcalidrawElement["strokeSharpness"]
  }
});
```

https://user-images.githubusercontent.com/14358394/180373707-00647184-9d23-4214-a585-5c0b87141cf7.mov

**Comment by kksharma1618** [comment]
Hey @zsviczian,

I created a plugin for managing these style palettes. https://github.com/kksharma1618/excalidraw-obsidian-tool-palettes
Any thoughts before I publish?
