### ISSUE TITLE
fail to run cmd + click + [[link]]  to open them

### ISSUE THREAD

**Issue by TrillStones** [zsviczian/obsidian-excalidraw-plugin#708]
**Describe the bug**

**To Reproduce**
1. Go to my drawing
2. cmd + [[link]] fail
3. See error one the top right.

**Expected behavior**
Jump to another note fail.

**Screenshots**
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/32927876/179897871-c5344618-03d3-44e8-892d-b98ae480da05.png">

**Environment (please complete the following information):**
 - OS including version: macOS monterey 12.4
 - Plugin version: 1.7.8
 - Obsidian version: 0.15.6

**Additional context**

**Comment by Geralt-TYH** [comment]
Same problem as yours, I reverted the version back to 1.7.2,it works

**Comment by zsviczian** [comment]
I am sorry, but I am away on holiday, without access to a desktop for two weeks, so I can’t test / reproduce the error on my iPad.

In general I do not recommend downgrading to 1.7.2. 1.7.0, 1.7.1, and 1.7.2 were early versions of trying to make Excalidraw work with Obsidian 0.15.x.

Do you experience this error when Excalidraw is open in the main Obsidian window, or when it is open in a popout window?
Do you experience the issue also when selecting an element and clicking the link icon header button in the top right?

**Comment by Geralt-TYH** [comment]
@zsviczian Thanks for your work and enjoy the holiday!

I encountered this error in the main Obsidian window, and as you mentioned, this problem occurs when selecting an element and clicking the link icon header button in the top right (just Internal links [[...]] ).

I want to add a situation:  I use cmd+shift+click to open the embedded markdown document for the first time,  it works, and a new window pop up showing the markdown file. But every time I use cmd+shift+click on the embedded markdown file in the excalidraw view later, it always reported this error.

**Comment by zsviczian** [comment]
Ok, thanks, I’ll investigate.

**Comment by zsviczian** [comment]
Please check 1.7.9 (will be released later today). Hopefully, all your issues have been addressed.

**Comment by zsviczian** [comment]
I've not seen this error pop up lately. I consider silence as agreement that this issue is resolved.
