### ISSUE TITLE
Can we get rid of the "update video" advertisement when the plugin is updated?  

### ISSUE THREAD

**Issue by wealthychef1** [zsviczian/obsidian-excalidraw-plugin#713]
**Is your feature request related to a problem? Please describe.**
Great plugin.  However every time I update Excalidraw, I get a popup window with a video and stuff and it's very intrusive and unnecessary to re-introduce me to the plugin with every update.  Can you please make Excalidraw stop doing that please?  :-) 

**Describe the solution you'd like**
I would like the plugin to just quietly update itself like all the other plugins do. 
Thanks!

**Comment by zsviczian** [comment]
I might be misunderstanding you… in that case I apologize for being direct, please clarify.

Once more, I am sorry, but I am going to be more direct than usual.

1) Have you read the message in the popup, at least until the end of the first short paragraph? Yes, you can disable the popup with the very first setting in plugin settings.

2) This is not an advertisement, though one would be probably appropriate considering the amount of effort that goes into making this plugin. These are release notes to help you make better use of the tool. I sometimes share important details here regarding changes.

**Comment by wealthychef1** [comment]
Ah, thank you so much for pointing out that I can disable the message.  I just installed it and haven't really used it much, just exploring it, so I didn't even look through the settings very closely obviously!  It is clear that you have poured enormous effort and I don't blame you for being proud of that.  It's a great plugin man.  I just hate that popup window.  :-). Thanks for the help!  
<img width="743" alt="2022-07-25 10 12 29 CleanShot Obsidian" src="https://user-images.githubusercontent.com/4825448/180813291-1644f029-9431-46f6-b95d-f2da85e173c7.png">

Today I Learned
