### ISSUE TITLE
Default location for embedded drawing failure

### ISSUE THREAD

**Issue by NeoMixlax** [zsviczian/obsidian-excalidraw-plugin#718]
## **Excalidraw is not using the Obsidian default folder location for attachments**
Apparently, when Excalidraw tries to create a new embedded drawing in the current active pane, it gets in trouble using the obsidian settings for attachments. The error makes not only the drawing doesn't become created (when there is a defined name for the subfolder for attachments), but also changes the Obsidian settings for attachments to "Same folder as current file"(if there is no defined name for the subfolder it's supposed to become created).

### **To Reproduce the error**
0. Install Excalidraw plugin
1. Go to settings and then to "Files & Links" tab
2. Scroll down to "Default location for new attachments" and set it to "In subfolder under current folder" (You can get different errors whether you type a custom subfolder's name or not)
3. Exit from settings and create a new note
4. Open command palette and search for "Excalidraw: Create a new drawing - IN THE CURRENT ACTIVE PANE - and embed into active document", click on it.
5. See error

### **Expected behavior**
A new drawing file gets created in a subfolder under the current note which in its turn references the drawing

### **Environment**
 - OS including version: Windows 10 Home
 - Plugin version: 1.7.8
 - Obsidian version: v0.15.9

**Comment by zsviczian** [comment]
Thanks. I will explore this error. I am currently traveling, but I have also noticed some issues with the "Create a new drawing" command palette action. Unfortunately I only have an iPad with me, thus I cannot do any debugging or software development... I will look at this bug once I get home.

**Comment by zsviczian** [comment]
Please check 1.7.9 (to be released later today) to see if the issue has been resolved.

**Comment by NeoMixlax** [comment]
Yep, the issue has gone!

Thank you again zsviczian. Have a nice day!
