### ISSUE TITLE
flip horizontal does not work

### ISSUE THREAD

**Issue by lhebates** [zsviczian/obsidian-excalidraw-plugin#726]
I am new to obsidian and Excalidraw. As I played around with this amazing drawing tool today, the *flip horizontal* option did not work. After clicking on the option, there is no effect, although the *flip vertical* option works as expected. 

Just want to bring this issue to your attention. Thank you for such a fantastic tool.

**Comment by zsviczian** [comment]
Thanks for raising this. Seems like this is a new bug (a collateral impact of implementing some changes to the core product). You should be able to flip rectangles and diamonds, only lines and arrows not. Also testing this issue I noticed that you can no longer rotate lines and arrows. 

I raised two issues for this on the main excalidraw github:
- https://github.com/excalidraw/excalidraw/issues/5536
- https://github.com/excalidraw/excalidraw/issues/5535

**Comment by zsviczian** [comment]
Solved in 1.7.11

**Comment by lhebates** [comment]
Amazing! Thank you very much!
