### ISSUE TITLE
Rightclick Menu isn't scrollable (too long for my screen)

### ISSUE THREAD

**Issue by 0x4c46** [zsviczian/obsidian-excalidraw-plugin#73]
If I'm doing a right click while drawing, some parts of the menu are not on the screen because the menu is bigger than my laptop screen. You could fix it by making it scrollable. 

![image](https://user-images.githubusercontent.com/80718878/121060829-6dd29700-c7c3-11eb-9cdc-627e386bf29b.png)

Thanks for your effort.

**Comment by zsviczian** [comment]
Thanks for raising. This is a behavior of the Excalidraw plugin I am using in the Obsidian plugin. I have opened an issue for this with the developers of Excalidraw.

In the meantime, I'll try to see if I can fix this by tweaking the stylesheet.

**Comment by zsviczian** [comment]
This was resolved with [#4030](https://github.com/excalidraw/excalidraw/pull/4030) in July 2022
