### ISSUE TITLE
UI for selected tool takes up far too much space

### ISSUE THREAD

**Issue by quartzar** [zsviczian/obsidian-excalidraw-plugin#731]
Using the plugin on a Samsung Galaxy Tab S8+, the UI boxes are enormous and take up way too much space.

Please add an option to be able to:
- Minimise the UI boxes
- Resize the UI boxes
- Hide the UI boxes all-together

I am aware of zen mode. [There is another issue present when using that](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/730)

**Screenshot:**
![Screenshot_20220807-165643_Obsidian](https://user-images.githubusercontent.com/79379455/183300771-df859926-4b79-43ee-b357-941dc7c0edc6.jpg)

**Comment by zsviczian** [comment]
Click the Obsidian menu (the button next to the stencil library).
Click the TM button (Tray Mode)
I also have a plugin setting for left-handed mode that will move the tray to the other side.

**Comment by quartzar** [comment]
Oh my goodness me...

Well that works perfectly. Thank you!

Closing issue.
