### ISSUE TITLE
Allow automatic export of individual files to PNG/SVG based on frontmatter

### ISSUE THREAD

**Issue by MosheSteinberg** [zsviczian/obsidian-excalidraw-plugin#732]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the advanced slides plugin which claims to require export to one of SVG or PNG to work, but I don't want to do this to all the excalidraw files in my vault

**Describe the solution you'd like**
A frontmatter selection that makes an individual file auto-export to SVG or PNG

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by zsviczian** [comment]
will try to include this in the next release. It likely won't be until the end of next week as I am planning to be away for a couple of days.

**Comment by zsviczian** [comment]
Implemented in 1.7.12.  I will release it soon.
Use frontmatter key `excalidraw-autoexport` valid values are `none`, `both`, `svg` and `png`.
