### ISSUE TITLE
Can't zoom arrow，which has been drawn

### ISSUE THREAD

**Issue by shisunsun** [zsviczian/obsidian-excalidraw-plugin#735]
**Describe the bug**
Can't zoom arrow，which has been drawn.

zooming worked at version 1.7.09，but can't zoom it since version 1.7.11，which

**To Reproduce**
1. draw an arrow which have multiple points
2. select this arrow
3. only can move any point or move the arrow
4. Can't zoom(resize the arrow proportionally) this arrow

**Expected behavior**
1. draw an arrow which have multiple points
2. select this arrow
3. can move any point or move the arrow
4. can resize the arrow proportionally

**Screenshots**
<img width="228" alt="image" src="https://user-images.githubusercontent.com/21273224/183799781-336e3455-edb1-483f-a9c3-33c0663d5033.png">
where is the resize button？

**Environment (please complete the following information):**
 - OS including version: macos
 - Plugin version:  version 1.7.11
 - Obsidian version: 0.15.9

**Comment by zsviczian** [comment]
This issue is linked to [#5535](https://github.com/excalidraw/excalidraw/issues/5535). A fix is in the works by the Excalidraw team [#5554](https://github.com/excalidraw/excalidraw/pull/5554) I hope it will be released soon. Once released I can bring it over to Obsidian as well.

**Comment by shisunsun** [comment]
> 

THX a lot！

**Comment by zsviczian** [comment]
Fixed in 1.7.12. I will release soon.
