### ISSUE TITLE
Add zoom % display in mobile TM mode

### ISSUE THREAD

**Issue by GitMurf** [zsviczian/obsidian-excalidraw-plugin#737]
When in regular mode (desktop) there is a display showing the % zoom and allows you to change it and also you can click the zoom % box and it will reset to 100%. I do not see this in mobile TM mode so I constantly have to switch out of it to see what zoom I am at and then reset to 100% (if that is what I desire). Often on mobile I tend to need to zoom in and out by pinching to see where I am at in my drawing but then want to return to 100% zoom so my writing size is consistent with my Apple Pencil.

Preferred solution: add the same zoom display button into TM mobile mode.

Alternative solution: have a button that can be added to the obsidian crystal menu that resets your zoom to 100%.

Thanks a lot!

**Comment by zsviczian** [comment]
Yes, I've been thinking about it for a while. Your issue is a good nudge to make it happen.

**Comment by zsviczian** [comment]
I am releasing this in 1.7.16 in a few minutes...

**Comment by GitMurf** [comment]
Thank you!! This is such a big QoL improvement for me when using ipad with apple pencil and handwriting :)
