### ISSUE TITLE
Canvas turns white when adding point for curved line

### ISSUE THREAD

**Issue by JuergenKaettnis** [zsviczian/obsidian-excalidraw-plugin#738]
**After adding a point to an arrow or a line, the canvas turns blank.**
If I go to a markdown file and come back everything the canvas is back, until I make a new point.

**To Reproduce**
1. Draw line or arrow
2. Double click on line/arrow
3. Press Alt-key to add a point.
4. When releasing Alt -Key,  the Excalidraw canvas turns white.

**Expected behavior**
I tried to add a point for a curved line/arrow

**Screenshots**

**Environment (please complete the following information):**
 - OS including version:  Android 
 - Plugin version: 
 - Obsidian version: 

All software should be up to date.
**Additional context**
I use Samsung S4 Tablet. The curved line feels very nice, easy to manipulate. Just when releasing the Alt key, the canvas turns white. After leaving and returning to the Excalidraw file, the file is reloading. Takes maybe a second.

**Comment by zsviczian** [comment]
I can't (yet) reproduce. I've tried this on an iPad. Pressing the option button to add points to a line and also to an arrow worked without any issues.

**Comment by zsviczian** [comment]
I just tried it with my Note 8 and a keyboard. I also can't reproduce. Will continue to try.
Can you confirm that you are able to reproduce this with a completely blank drawing?

**Comment by RichardEvert** [comment]
The page only goes blank when you release the alt key.
I am using Windows 10.
I can add as many additional points as I want to as long as I keep holding the alt key down.
I tested with a blank canvas and one line with two points.
As soon as I let the alt key go, screen/canvas goes to the default background color but the title bar shows that the note is still open on the excalidraw file "Drawing 2022-08-14 20.27.33.excalidraw"
As stated by Hansilein00726, by sequence of "open as markdown" and back again with "Open as excalidraw drawing", the drawing is visible again.

**Comment by zsviczian** [comment]
I was able to accidentally reproduce the issue. I also have a hunch as to what might be causing the problem. Let me dive deeper into the issue.

**Comment by zsviczian** [comment]
Similar to: [#5602](https://github.com/excalidraw/excalidraw/issues/5602)

**Comment by zsviczian** [comment]
I think I have found the solution [#5606](https://github.com/excalidraw/excalidraw/pull/5606). I will release the fix in 1.7.15

Let me know if the problem persists after release 1.7.15. The release should be out in a few minutes.
