### ISSUE TITLE
Strange white frame around excalidraw drawingzone

### ISSUE THREAD

**Issue by 0x4c46** [zsviczian/obsidian-excalidraw-plugin#74]
On the top and the left side of my drawing window there are black/white dots and lines, depending on background color. I don't know if it's your "mistake" or if it is the same in native excalidraw. 
Nevertheless, I really like your plugin for making nice sketches and mind maps.
Edit: It isn't always there but yet I don't know for sure when it appears. Maybe when I'm drawing and writing much at once.
 
![image](https://user-images.githubusercontent.com/80718878/121083358-a3857900-c7df-11eb-864b-ef978922bda5.png)

**Comment by zsviczian** [comment]
Thanks! I will investigate. It looks like a stylesheet issue. 
Which Obsidian theme are you using?

**Comment by 3nzoFerrari** [comment]
I'm using minimal theme.

**Comment by zsviczian** [comment]
Sorry, I can't reproduce this error.

**Comment by 3nzoFerrari** [comment]
I don't know when it happens, sometimes it does, most of the time it doesn't. I only use one snippet for having justified text in preview and PDFs, but it won't make an issue. 
Right now I also can't reproduce it. I'll keep an eye open the next time it appears.

Thanks for your effort.

**Comment by zsviczian** [comment]
I still couldn't reproduce the issue. Please let me know if you can figure out when this happens.
