### ISSUE TITLE
Create new folder not working from Excali draw sometimes :c 

### ISSUE THREAD

**Issue by raspberriesonmyprofilepic** [zsviczian/obsidian-excalidraw-plugin#741]
If I make oduble bracket text in excalidraw, and try to later make new file from it, I get the pop up box of whether I want excali draw or md but if I click the md file, nothing happens
![2022-08-12 19-57-03](https://user-images.githubusercontent.com/8075975/184407672-3fdaa94e-4db5-4c4b-842c-87142c0694d9.gif)

**Comment by zsviczian** [comment]
Thanks. I was able to reproduce. Indeed if the folder does not exist create new note does not seem to work. I will fix this in the next release.

**Comment by zsviczian** [comment]
resolved in 1.7.14
