### ISSUE TITLE
Support for rendering symbols using mathjax 

### ISSUE THREAD

**Issue by AvijeetPrasad** [zsviczian/obsidian-excalidraw-plugin#75]
It would be really nice if we can support the rendering of math symbols using mathjax, as used in Obsidian. This will be very helpful when annotating axis of drawings. For example, writing $\theta$ for some angle.
![image](https://user-images.githubusercontent.com/45669486/121726806-a5d22680-cab0-11eb-8811-5d8b268391e7.png)

**Comment by zsviczian** [comment]
Thanks!
What I may be able to do is to open a popup dialog where you can enter the formula and I would insert the corresponding math symbols as text into the drawing. I will explore this idea in an upcoming release.

**Comment by AvijeetPrasad** [comment]
Thanks! That would be very useful. Looking forward to it.

**Comment by zsviczian** [comment]
see 1.1.9
