### ISSUE TITLE
Any tutorial for using charts in the library?

### ISSUE THREAD

**Issue by shaggyfeng** [zsviczian/obsidian-excalidraw-plugin#76]
Is it possible to use the `data-viz.excalidrawlib` and `graphs.excalidrawlib` sets provided in the Excalidraw library? Is there a way to input data and then select chat style? So far, I can only open them as icons/diagrams, but not chats or graphs with data. If it is not possible, please let me know. 

Thanks

**Comment by zsviczian** [comment]
I'm afraid those charts don't work as proper diagram templates - like in Excel.
Check out this video for a demonstration of what is possible: https://youtu.be/2cKlEwo8WU0?t=118
