### ISSUE TITLE
Excalidraw crashes

### ISSUE THREAD

**Issue by selpolselpol** [zsviczian/obsidian-excalidraw-plugin#760]
I can not view images since 1 week aprox (I have not use Excalidraw a long time ago, so the problem could occur before), but the new ones that I import yes.

Excalidraw crashes a lot. For example:
1. Create a line
2. Double click
3. keyboard key Alt for a new point
4. Crash (I see a transparent image, like my Theme background, and anything

[obsidian.md-1661094181918.log](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/9389393/obsidian.md-1661094181918.log)
[obsidian.md-1661094174551.log](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/9389394/obsidian.md-1661094174551.log)
[obsidian.md-1661094178888.log](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/9389395/obsidian.md-1661094178888.log)

![image](https://user-images.githubusercontent.com/55896022/185797434-5b14bb2a-7cfc-4e66-8c9a-75faac6fcff8.png)
 more).

**Comment by zsviczian** [comment]
Thanks for raising this issue, and I am very sorry that you are experiencing problems.
This looks very familiar to a known issue that was recently reported to the core Excalidraw product team [#5602](https://github.com/excalidraw/excalidraw/issues/5602).

Can you tell me more about your environment. What operating system are you on? Which version of Obsidian?
Can you confirm if the problem still occurs on the latest (1.7.14) version?

**Comment by zsviczian** [comment]
The logs are super useful! I'll look into this tonight.

**Comment by zsviczian** [comment]
Could you replace the main.js in the .obsidian/plugins/obsidian-excalidraw-plugin folder with the main.js in this archive ([main.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/9389756/main.zip)) and send me the log again after the next crash?

I was able to find one error based on the log, but I don't think that it was causing the crash. For the rest, I need more detailed debug info.

**Comment by zsviczian** [comment]
no need. I was able to reproduce the error.

**Comment by zsviczian** [comment]
Found the solution [#5606](https://github.com/excalidraw/excalidraw/pull/5606). Will release the fix in 1.7.15

**Comment by selpolselpol** [comment]
Sorry for not giving you all the information (I just uptdated more info). I am new in GitHub and I do not know how this publication for a bug works. Anayway, thanks for everything zsviczian.
