### ISSUE TITLE
Add option to export both light and dark versions of an image 

### ISSUE THREAD

**Issue by aadimator** [zsviczian/obsidian-excalidraw-plugin#763]
**Is your feature request related to a problem? Please describe.**
When you publish your website, you can't match the theme of the image, as you can do in Obsidian. There's only a single image export, either using light theme or dark. Websites with both dark and light modes have a difficulty in reading a certain image in a particular mode.

**Describe the solution you'd like**
Add an option to export the image in both modes, i.e. light and dark. The user should be able to choose which theme is default, so it would have the name of the drawing, and the other would have the mode appended to the end. For example, if there's an Excalidraw drawing called `my-drawing.excalidraw.md`, if user decides to make the light themed image as default, then the exported image names should be `my-drawing.excalidraw.png` (or .svg, based on preference) which corresponds to the Light Themed image, while the other one should be named `my-drawing.excalidraw.dark.png`. The same goes for the other way around, i.e. if the user decides to make Dark mode the default, then it should also export `my-drawing.excalidraw.light.png`.

**Describe alternatives you've considered**
For now, you have to make the background of the image a specific color, instead of using `transparent`. If you use `transparent`, it would work well on some colors, and not others.

**Additional context**
Here's an image which works well with Light background but has low readability in Dark background. I've exported it as a transparent image, and I've also used light opacity.

![Dark Mode](https://user-images.githubusercontent.com/10383542/186072528-fddb74f9-70bc-4839-9cdd-f51ddbcac14c.png)

![Light Mode](https://user-images.githubusercontent.com/10383542/186072589-6a0079bf-251f-4566-bf1b-6141b3b4c205.png)

**Comment by zsviczian** [comment]
sounds very doable. I'll try to get this in the next release.

**Comment by zsviczian** [comment]
I am publishing 1.7.16 now, but this feature is not included. Someone discovered a high-impact issue, that I had to take care of... I will do this in 1.7.17

**Comment by aadimator** [comment]
No problem, take your time. It's not very urgent.

Also, can you include the link to the `alternate image` in an Obsidian Comment, just like you post a link to `Edit in Excalidraw`. I'm saying this because if we use other plugins like `Clear Unused Images`, those `light or dark` images don't get deleted.

**Comment by zsviczian** [comment]
My solution proposal. I will add a setting: `Auto export both light and dark images at the same time.`. This will create two files: `image.dark.png` and `image.light.png`.
I will also modify the code to keep these filenames in sync with the drawing.

**Comment by zsviczian** [comment]
deployed in 1.7.17
