### ISSUE TITLE
Excalidraw canvas is empty after saving and re-opening

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#768]
See a demonstration of the issue on youtube here: https://youtu.be/1Pqb71y2LA8

If you copy an image to the clipboard and paste it by accident as a text element... this will corrupt the Excalidraw file and result in a file that won't load, however, can be manually repaired.

It is deceptive because you can continue to edit the drawing as if nothing happened... until you close and open it.

**Comment by zsviczian** [comment]
fixed in 1.7.16

**Comment by Macha-l** [comment]
Hi ! I watched the video, and indeed the bug looks like this and it is true that I often use images to illustrate my mind maps, especially in neurology... 
But this is not always the case, one of the missing files was without image.

If I understand correctly, you can't just copy/paste an image to excalidraw? This will damage the file without it being noticeable right away

What should I do and not do in the future, to avoid this happening again ?
By the way, I copy/paste the images I want to transform into text with the OCR function (another incredible function for me!). I shouldn't either?

**Comment by Macha-l** [comment]
I tried to open a damaged file in markdown, But it seems to me that I don't have the possibility.

While on a valid file, I can
<img width="515" alt="Sans" src="https://user-images.githubusercontent.com/112097188/186717893-fe593133-11e1-4ed8-bb85-4ed9e404217c.png">
![Uploading avec.png…]()
