### ISSUE TITLE
block transclusions in obsidian 

### ISSUE THREAD

**Issue by zxcmaqi** [zsviczian/obsidian-excalidraw-plugin#769]
I use block transclusions in excalidraw, if the block happens to be the last.
The button of switching RAW mode to PREVIEW mode will never work, like it stucks.

first create markdown file and use block transclusions like this
- ![image](https://user-images.githubusercontent.com/15138945/186512860-c3efb69f-26e4-428f-883b-f5678835bcc9.png)

second use this link in excalidraw,and clik the button over times, it works
![work](https://user-images.githubusercontent.com/15138945/186641757-fd315274-b171-4bdc-98d1-9c96f6ec111f.gif)

third back to the previous .md file and give it a carriage return and space key
![third](https://user-images.githubusercontent.com/15138945/186642948-814c3b65-6408-4d37-9ddb-2486ce4f9678.gif)

fourth turn to the previous excalidraw file ,click the button,it stucks
![stuck](https://user-images.githubusercontent.com/15138945/186643507-fbb113a0-e2fa-4d3a-98c3-93a715829b53.gif)

if it still works ,repeat the third step and fourth step,sometimes you need repeat some times

**Comment by zsviczian** [comment]
I am unable to reproduce.
Do you just open an empty drawing and experience this issue? Or did the drawing have anything on it before that was deleted?
Can you reproduce any time, or was this just a once-off experience?

**Comment by zsviczian** [comment]
I was able to reproduce.

**Comment by zsviczian** [comment]
### Steps to reliably reproduce
1. create empty document in "parsed" mode
2. Add text element with transclusion
3. Switch to markdown mode
4. Manually change "parsed" to "raw" in front matter
5. Switch to Excalidraw mode
6. Switch to Preview (parsed) mode

7.a. Double click element (it looks OK)
8.a. After autosave completes - block reference is gone

7.b. Add another element to the scene
8.a. After autosave - the block reference is gone

**Comment by zxcmaqi** [comment]
i change the comment you can see it

**Comment by zxcmaqi** [comment]
thanks your advice
