### ISSUE TITLE
FR: Ability to turn off automatic check for newer version availability

### ISSUE THREAD

**Issue by gala8y** [zsviczian/obsidian-excalidraw-plugin#770]
First and foremost, thanks for developing Obsidian-Excalidraw.

Feature Request: I think Excalidraw is the only plugin which checks for updates on its own among all plugins I use. 
That would be great to have ability to turn this on/off presented as an option in plugin settings.

**Describe the solution you'd like**
Option in plugin settings to turn checking for newer versions on/off.

**Comment by zsviczian** [comment]
sure. Will do that.

**Comment by zsviczian** [comment]
The solution will be included in 1.7.17.
Excalidraw will still notify you when 1.7.17 becomes available 😉 You can then go to settings to disable version update notification.
