### ISSUE TITLE
what if obsidian 0.14.15 ≤ excalidraw 1.7.18 ?

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#773]
Hello, dear developer!
[What can happen ](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases?page=2#:~:text=Excalidraw%201.7.4-,%E2%9A%A0,%E2%9A%A0,-Obsidian%200.15.3%20support) if I use your updates on an old obsidian (the plugin I need doesn't work in the pop up version) ?
- the drawings could disappear? (bad)
- the program will freeze up? (not so bad)

Thanks for your attention !

**Comment by zsviczian** [comment]
Excalidraw 1.7.18 does not work with Obsidian 14. You can find the version dependency in this file: https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/versions.json

In short, you need Obsidian 0.15.6 or newer to use Excalidraw 1.7.18.  If you install the plugin from the Obsidian Community Plugin store, Obsidian should not even allow you to install a version that is not compatible with your Obsidian version.

**Comment by anatoliibakhtin** [comment]
I see, so at the moment the main problem - no auto update, I really like what you do, so I update manually - I replace 3 files style, main, manifest, at the moment everything works fine 😃

I roughly understand that further development of the plugin and my using it with an old version of obsidian can lead to some problems (it's like riding a train with different rails and wheels, which do not change in coordination with each other)

I didn't get a super alarming message from you that trouble was going to happen, so I'll keep using for a while, keeping the driveway and rails in mind, thanks for the reply!
