### ISSUE TITLE
CTRL+Click a text field to open based on alias name

### ISSUE THREAD

**Issue by roamhacker** [zsviczian/obsidian-excalidraw-plugin#78]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently if I ctrl+click on a text object it will open the file with same name as text in text object. I would suggest that alias names can be used as well. This will allow for an alternative text in the text object, but still open the intended file.

So I might have a page called: My Page. Then in that page I have defined front matter YAML using the aliases collection:

```
---
aliases: [ MyPage, MP]
---
```

Now MyPage or MP can be used in the excalidraw text object and the ctrl+click will work.

**Comment by zsviczian** [comment]
I've been thinking about this, but I don't yet have a good solution. You think all files can have YAML front matter, not just *.md files?

**Comment by roamhacker** [comment]
Actually what I am thinking is in the target MD file for the link We define the aliases (just as we do with files now. Excalidraw plugin looks through file names for a match, if none exists it looks through the aliases for all files for a match. 

https://help.obsidian.md/How+to/Add+aliases+to+note

**Comment by zsviczian** [comment]
I don't look through filenames, just run an API call. I need to find the
other API call for resolving aliases.

**Comment by zsviczian** [comment]
I will be releasing v2.0 this weekend. It will support aliases as per markdown standard [alias](link) and [[link|alias]].

**Comment by zsviczian** [comment]
Aliases are available in [1.2.0-alpha-1](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases)
