### ISSUE TITLE
lags in drawing due to auto saving drawing

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#782]
Hello dear developer ! 

**My problem:**

lags in drawing due to auto saving drawing with compression at inappropriate moment for me.   

I get noticeable delays 🟥 while painting on a heavy canvas, with compression mode, especially on a weak device (computer<phone).
 
**To Reproduce**

1. turn on the compression function
2. open the heavy canvas
3. draw short arcs

https://user-images.githubusercontent.com/71871141/187909911-18cc9b57-59fa-41ad-a1f1-225a28eb2fa7.mp4

 pc - computer
 m - mobile

**Expected behavior**

- I want to save drawings with compression, auto-save function, remove lags, even on a heavy canvas.
- (as an option to solve this problem) If I understood correctly the order of 💾 auto save (1, 2: 2.1, 2.2), could you:
  
  - [x] Add a hotkey for force-save, along with the compression function if it is enabled in the settings ?
  - [x] Move compression function to the moment when user leaves the canvas or press force save (auto-save still works while I'm drawing, it doesn't get in the way as much as the compression) ? This would reduce the amount of lag while drawing.
 
**Additional context**

- The file is saved in 2 ways automatically after an action, after pressing the force-save key. (there don't seem to be any others)
- As far as I understand it, 💾 auto save works like this: 1- there is an interaction with the canvas, it is over, 2- file saving starts if compression is enabled: 2.1-compression, 2.2-preservation. 
- Compressing a file reduces its size by about 3 times. It also takes about 3 times as much time to save (judging by the number of errors in the compressed vs uncompressed version)	
- - [x] Clarification - if I have 1000 pictures, compressed and 1000 uncompressed, will obsidian find the answer faster in the compressed version ? (if so, it is vital that I leave the compression of the drawings.)

**Environment :**
  - OS including version: Android 9, Windows 10]
 - Plugin version: 1.7.18
 - Obsidian version: 0.15.9
 
 Thank you for your attention ! 🌼

**Comment by zsviczian** [comment]
I'll explore the idea of saving uncompressed during autosave and only saving with compression when closing the file. Compression does not make search faster, but it helps avoid lots of false positives when searching for words in the JSON

**Comment by zsviczian** [comment]
In 1.8.1 I have added plugin settings to allow for less frequent autosave intervals. Will release it in the coming days.

**Comment by anatoliibakhtin** [comment]
@zsviczian it seems you solved this problem in version [1.8.1 ](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.8.1): save on canvas output + you added interval (this is something I forgot to mention here), save button, thanks a lot ! 
I'm going back to mode with compression and a big smile :)
