### ISSUE TITLE
Can't find the fourth font family button in 1.7.18

### ISSUE THREAD

**Issue by ccll** [zsviczian/obsidian-excalidraw-plugin#785]
Greetings, obsidian-excalidraw is so awesome that I can't live without it now. Thanks for this great integration.

**Describe the bug**
According to #14, #341, #427 and various sources, from 1.517 a fourth font button is added to the UI, but I can't find it in current release 1.7.18

**Expected behavior**
There should be a button.

**Screenshots**

![image](https://user-images.githubusercontent.com/5366582/188116109-e46a7672-1754-4044-97d2-f7e9762ed4ee.png)

**Environment (please complete the following information):**
 - OS including version: Ubuntu 20.04 LTS
 - Plugin version:  1.7.18
 - Obsidian version: v0.15.9

**Comment by zsviczian** [comment]
1) you need to save the font file in your vault
2) go to Excalidraw plugin settings, scroll down to "Experimental Features"
3) Enable the fourth font, and set a font file.

![image](https://user-images.githubusercontent.com/14358394/188194611-1d1eecce-37d1-457f-b6f7-03d66807da59.png)

**Comment by ccll** [comment]
Oops, my fault, missed the option.
It's works like a charm, thanks again for this great plugin!
🎉
