### ISSUE TITLE
Block reference parts image is not shown in the page

### ISSUE THREAD

**Issue by dumbdreamed** [zsviczian/obsidian-excalidraw-plugin#788]
hi, thanks for your efforts on this beautiful add-on.
I have a problem when I create a link from a block and paste it into a separate page ,the link is correct and guides me to the exact block but the problem is that it doesn't show the thumbnail of the selected block.
as shown in this picture
![image](https://user-images.githubusercontent.com/64626106/188282155-eb05a003-708e-4969-a0a8-e11dedb59fa6.png)

**Comment by zsviczian** [comment]
You need to put an `!` in front of the link to make it an embed.
This is a link to a block: `[[file#^group=block]]` and this is an embed (transclusion) `![[file#^group=block]]`
