### ISSUE TITLE
CTRL-Click a grouped collection of objects does not open the page based on the embedded text

### ISSUE THREAD

**Issue by roamhacker** [zsviczian/obsidian-excalidraw-plugin#79]
**Describe the bug**
Hard to say if this is a bug or feature request. Imagine a text object with text in it, then a rectangle drawn around it. Then these two objects are grouped together (CTRL+G). Standard stuff for flow charting.

When CTRL+Clicking the grouped object, nothing happens. Can the excalidraw plugin "look" into the grouped object for a text object and open the page based on its text? 

Of course multiple text objects can be grouped, so not sure what the behavior would be in this case.

**Additional context**
Zsolt rocks!

**Comment by zsviczian** [comment]
I guess I could solve this for the car when there is only a single text element in the group

**Comment by roamhacker** [comment]
Do you diagram like that?

yes a single text object I think is the most common scenario. Especially if someone wants to link to a file.

**Comment by zsviczian** [comment]
Solved. Update to 1.1.10
