### ISSUE TITLE
Wrap text around embedded image and float to left/right/center

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#8]
Is there a way to make it float and and wrap text around it.
Behavior somewhat similar to ambidition blocks.

**Comment by zsviczian** [comment]
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.6

**Comment by VivCh14** [comment]
Hi @zsviczian,

Thank you so much for such a great plugin! I am having issues to have my text wrap around the embedded Excalidraw file. I use the below in my Obsidian note:
`![[image.excalidraw|400|right-wrap]]`

But my text does not wrap around the embedded file. I have seen this work in your YouTube video but I can't seem to have it work for me. 
<img width="534" alt="Obsidian_6pDegRyG7Q" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/67145013/936fed89-0506-4a3b-811a-84863dc1e357">

Any suggestions to make it work ?
