### ISSUE TITLE
range of font-size in sticky notes is limited and doesn't change with resize of the block

### ISSUE THREAD

**Issue by aliamini87** [zsviczian/obsidian-excalidraw-plugin#807]
Usually I use sticky notes in different size blocks. Sometimes after some writing, I decided to make box larger. In many conditions there is no way to make the font-size larger. For example in the below image both boxes have XL fonts and there is no way to make font of larger box, larger then this.

![image](https://user-images.githubusercontent.com/91720545/190311731-6d9b6bc9-8c81-4d8c-8ed3-43e4490c5491.png)

**Comment by zsviczian** [comment]
hold down shift while resizing the block

**Comment by aliamini87** [comment]
Vow. I didn't know that.
Thanks a lot.
Problem solved.
