### ISSUE TITLE
When creating arrow that goes around corner you need to press "Esc" while holding Mouse and Alt to create

### ISSUE THREAD

**Issue by ReaderGuy42** [zsviczian/obsidian-excalidraw-plugin#81]
**Describe the bug**
When I'm trying to create an arrow that goes around a corner, i.e. bending the arrow, I hold the Alt button and the arrow goes to where the mouse is pointing. However, when I click it seems like the arrow is staying there, but when I let go of Alt it goes back to its original position. I need to press "Esc" in order to "fix" the arrow.

**To Reproduce**
1. Double click arrow to get the "red dots" at points 1 and 2 that you can drag around.
2. Hold Alt while point to a third location.
3. Click and the arrow appears to be fixed.
4. Release Alt and see that the arrow has gone back to point 2 again.
5. Hold Alt again and the arrow goes to the mouse again.
6. Press escape while holding mouse and Alt to get arrow to where it's supposed to be.

**Expected behavior**
I would imagine it's supposed to work by just clicking while holding Alt or even just releasing Alt.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1 (Cinnamon)
 - Obsidian 0.12.5
 - Excalidraw 1.1.10

**Thanks** :)

**Comment by zsviczian** [comment]
Thanks for raising this.  I am sorry, but I am unable to reproduce the bug.

1. Double click
2. Hold Alt while dragging the point to a third location
3. Click
4. Let go the Alt key

https://user-images.githubusercontent.com/14358394/123509688-37c45c80-d677-11eb-9453-d8fefc58e572.mp4
