### ISSUE TITLE
Can't embed as MD a note with Banner

### ISSUE THREAD

**Issue by AMGMNPLK** [zsviczian/obsidian-excalidraw-plugin#814]
Having a note with banner (Banner plugin) and trying to embed to a excalidraw file with drag and drop function (with Control pressed) the console throw this error and can't accomplish the embedding.

**Environment (please complete the following information):**
 - OS including version: Windows 10
 - Plugin version: 1.7/20
 - Obsidian version: v0.15.9

**Comment by zsviczian** [comment]
I patched Excalidraw 1.7.21 to filter out the banner if present. This will temporarily solve your issue.

Since the source of the error is not Excalidraw but the Banners plugin, I raised an issue for Banners here: [#73](https://github.com/noatpad/obsidian-banners/issues/73)

**Comment by zsviczian** [comment]
The workaround is now released.
