### ISSUE TITLE
FR: Tasks render as - [ ]  Task

### ISSUE THREAD

**Issue by munafsheikh** [zsviczian/obsidian-excalidraw-plugin#819]
![image](https://user-images.githubusercontent.com/6186112/191920062-d18d0ae1-7c09-4d4b-9723-c759d3a57314.png)

Awesome plugin, super-useful. Can we please get checkboxes to render - similar to how links are rendered. 

Links: 
![image](https://user-images.githubusercontent.com/6186112/191921418-55870e57-dc76-48b7-8042-6b19d1129556.png)

**Comment by zsviczian** [comment]
cool idea! Let me see what I can do.

**Comment by zsviczian** [comment]
released in 1.7.21
