### ISSUE TITLE
Please add 3x / 2x .png export option

### ISSUE THREAD

**Issue by yoursamlan** [zsviczian/obsidian-excalidraw-plugin#82]
I'm using excalidraw for a while now and your plugin is very helpful for productivity.
However, I miss one useful feature.

### Feature Request:
 **Please add the option to export in 2x / 3x .png format**. 

### Why I miss it?
As I use excalidraw to create mindmaps, it contains lots of elements. When I export those mindmaps in png format outside the obsidian, It literally becomes unintelligible while zooming. Now, svg is a handy option, but it doesn't support predefined fonts (virgil and cascadia) and the browser default font just shatters the aesthetic of the mind map (as in my case).

### Example:

- 1x png export:
![1xpng](https://user-images.githubusercontent.com/33586885/123507761-db6a3880-d688-11eb-8475-06d4cd035083.png)

- 3x png export:
![1xpng](https://github.com/yoursamlan/mind-map/blob/main/980798bfb586b137ca022694e2027be40f142bbd/img/preamble-dark.png?raw=true)

### Conclusion

Under such circumstances, I, therefore, request you to add an option of 2x/3x export to your plugin. 

Thank you.
:)

**Comment by zsviczian** [comment]
Awesome drawings!
Are you sure about SVG? In early versions of the plugin, indeed SVG export did not carry the fonts and did not display well. Since I think 1.1.0  I am embedding base 64 encoded fonts into the SVG. The exported SVGs are self-contained and should display correctly. I just tried and it works great.

Please test SVG once more. If you still experience problems, I'll implement 2x and 3x PNG for you.

**Comment by yoursamlan** [comment]
Thank you so much, and I'm extremely sorry. I've just updated the extension to 1.1.10 and the SVG is working flawlessly. Thank you so much for the beautiful extension. :-)

**Comment by zsviczian** [comment]
Great! I like SVG better than PNG as you can zoom in to whatever depth!

**Comment by zsviczian** [comment]
Hi @yoursamlan, just to let you know, I added this feature in release 1.2.10. You can set PNG scaling in settings.

**Comment by yoursamlan** [comment]
Wow! That's amazing. Thank you so much for adding this. :)
