### ISSUE TITLE
Keyboard shortcuts not working on non Qwerty layouts

### ISSUE THREAD

**Issue by aziham** [zsviczian/obsidian-excalidraw-plugin#827]
**Describe the bug**
I'm using Dvorak keyboard layout and keyboard shortcuts aren't working.

**To Reproduce**
Switch to Dvorak and try the keyboard shortcuts.

**Expected behavior**
The shortcuts should work as I type the equivalent characters using Dvorak.

**Screenshots**
- Not applicable

**Environment (please complete the following information):**
 - OS including version: Debian GNU/Linux 11 (bullseye)
 - Plugin version: 1.7.22
 - Obsidian version: 0.15.9

**Comment by zsviczian** [comment]
Keyboard shortcuts are a pain in the backside when it comes to development and testing. There are other issues as well, for example CMD+C not copying on iOS... Please try shortcuts in their QERTY physical location, i.e. regardless of where the key is on your keyboard layout check to see which physical key it is supposed to be on QWERTY and try that shortcut. I've seen this trick work in the past.

In addition can you test if shortcuts work for you on excalidraw.com? This way I can understand if I am messing something up in the Obsidian plugin or if this is a product issue, in which case I'd like to kindly ask you to open a linked ticket for this with Excalidraw.

**Comment by aziham** [comment]
> can you test if shortcuts work for you on excalidraw.com

I got the same result. It's an excalidraw's issue.

Thank you Zsolt, I'll try to open a linked ticket as you suggested.

**Comment by aziham** [comment]
> open a linked ticket for this with Excalidraw

@zsviczian How do I open a linked ticket?

I've tried to open a new issue, but it seems that I can't figure out how to open a linked one

**Comment by zsviczian** [comment]
You can open an issue on the excalidraw.com github here: https://github.com/excalidraw/excalidraw/issues

**Comment by zsviczian** [comment]
Sorry... I did not read your question carefully enough. this is what you get when you try to multitask.
Once you have created the issue on the excalidraw issue list, please copy the URL of the issue you created and drop it as a response here. That will link the two.

**Comment by aziham** [comment]
> Sorry... I did not read your question carefully enough. this is what you get when you try to multitask.

Don't worry, it happens to the best of us. I really appreciate your work on the obsidian's excalidraw plugin, and benefited a lot from your Youtube videos.

>Once you have created the issue on the excalidraw issue list, please copy the URL of the issue you created and drop it as a response here. That will link the two.

Thanks

**Comment by aziham** [comment]
https://github.com/excalidraw/excalidraw/issues/5739

**Comment by zsviczian** [comment]
Can you test if [this](https://github.com/excalidraw/excalidraw/commit/79bd3b8cdafa7bb1cdfddcc8182e1a72aba1b3f6) change has fixed the issue for you?

Please download the [main.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/9854546/main.zip), unzip the file and replace main.js in `.obsidian/plugins/obsidian-excalidraw-plugin` folder and restart Obsidian.

**Comment by aziham** [comment]
@zsviczian

🟢 Working
🔴 Not Working
🔵 Not Sure

![image](https://user-images.githubusercontent.com/94932043/198585464-117718b6-8160-4dc3-a3fe-fbfd5e2c8183.png)
