### ISSUE TITLE
Shortest path when possible, now - NOT always

### ISSUE THREAD

**Issue by anatoliibakhtin** [zsviczian/obsidian-excalidraw-plugin#829]
**Describe the bug**
I have the link file insertion mode ![SV5ySpgW4c](https://user-images.githubusercontent.com/71871141/193470472-24e477e2-061c-4743-977f-a1d7ed76a469.jpg), it works if file import as **Text Elements**, but if as **Embedded files**, the link is inserted in a different mode. This can be problematic when I move files to other folders inside the vault, but not through the obsidian, so the links don't update themselves (because it's not convenient to organize files in obsidian).

**Video demonstration:**

https://user-images.githubusercontent.com/71871141/193470707-390e537f-3843-4eda-a8ab-a9689bdc90cc.mp4

**Expected behavior**
I want the files to always be inserted in a mode "Shortest path when possible", if that is possible.

**Environment (please complete the following information):**
 - OS including version: Windows 11
 - Plugin version: 1.7.20
 - Obsidian version: 0.15.9
 
 Thank you for your attention !🏵️

**Comment by zsviczian** [comment]
Thanks. This is a legacy from the time when I didn't yet have code to handle the shortest path... I will see if I can spot all the locations where this happens.

**Comment by zsviczian** [comment]
I hope to have fixed it in 1.7.23. Let me know if the issue pops up anywhere else.
