### ISSUE TITLE
Feature Request: turn gridMode on by default

### ISSUE THREAD

**Issue by M3NIX** [zsviczian/obsidian-excalidraw-plugin#83]
I would love to have a setting which allows me to turn the grid mode on by default when I create new drawings/open existing drawings. Right now it is needed to toggle it every time with Ctrl+'.
Currently I have patched the main.js to achieve the desired effect, which has to be done after each update.

**Comment by zsviczian** [comment]
I thought templates already did this... but I see grid is not saved with the .excalidraw file. I'll add this to the template as well.

**Comment by zsviczian** [comment]
[Release 1.2.0-alpha-1](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.2.0-alpha-1) solves this issue.
