### ISSUE TITLE
mobile: Trying to zoom over an image opens the image 

### ISSUE THREAD

**Issue by pikatwinky** [zsviczian/obsidian-excalidraw-plugin#837]
This is a problem when having drawings with a lot of images, im wondering if there is a workaround to this problem

*Attachments are from the desktop version, but the behavior is the same as I describe below on mobile (this last is the platform where i have the problem, the desktop version is OK) 
* I'm using the latest versions of obsidian (insiders mobile and desktop), and the latest version of the plugin

Steps to reproduce:
On mobile, in view mode touch with two fingers on an image (trying to zoom inside the image)
e.g putting my two fingers on the red circle bellow (with zooming intentions)
![image](https://user-images.githubusercontent.com/31860235/194402295-6d91f89f-0b11-4d93-ad5b-18fa397e2ab3.png)

The image file itself is opened in an undesired way
![image](https://user-images.githubusercontent.com/31860235/194403140-3e66b8a4-b8cf-4811-b2bb-9c538eccd003.png)

Then when returning to my drawing the zoom is reset, which a bit annoying try to find where i was when the image was opened (this is more accentuated in drawings filled with more images)
![image](https://user-images.githubusercontent.com/31860235/194401600-cc3869a0-7561-4fa5-bae9-3dc4ea15978b.png)

I think to lock the images in view mode and using a one-finger double-tap to open it could be better, maybe?

**Comment by zsviczian** [comment]
Thanks for raising this. I rarely use Exclidraw in view mode on Mobile, thus I never experienced this issue before. If you are in edit mode, the issue does not happen. 

I can see how this is a really frustrating bug. I will investigate and solve it.

As a quick pain relief, you can try to disable auto zoom. You'll find it in Excalidraw Plugin Settings under Display:

![image](https://user-images.githubusercontent.com/14358394/194741192-3ee68074-1545-4ae3-a723-cc2f2f0661f9.png)

**Comment by zsviczian** [comment]
Fixed. Will release the fix with 1.7.23 later today.

**Comment by pikatwinky** [comment]
Thank you so much Zsolt! You're amazing!
