### ISSUE TITLE
Fix: update the excalidraw to fix extra dot

### ISSUE THREAD

**Issue by YIRU69** [zsviczian/obsidian-excalidraw-plugin#839]
https://github.com/excalidraw/excalidraw/pull/5727

@zsviczian

**Comment by zsviczian** [comment]
Thanks! No need to highlight updates to the main excalidraw.com product. I anyway try to merge updates from the main product into the Obsidian fork once every week (if I don't have time, then after two weeks). This will be merged as well in due time.
