### ISSUE TITLE
Cannot enable excalidraw

### ISSUE THREAD

**Issue by mpiko** [zsviczian/obsidian-excalidraw-plugin#842]
Trying to install excalidraw into my production vault which appears to install correctly. When trying to enable, I get a "failed to load" message.

I had previously set excalidraw up in a testing vault which worked perfectly. Environment:
Ubuntu Mate 22.04.1 LTS (Jammy Jellyfish)
Obsidian-0.15.9
Excalidraw 1.7.23

Is there a log file which will tell me what is preventing it from loading?

**Comment by jiiiijiij** [comment]
+1 same problem

**Comment by Kylar22** [comment]
I also have the same issue.  Looking at the `\.obsidian\plugins\obsidian-excalidraw-plugin` folder there are only 2 files:
- `manifest.json`
- `styles.css`
Should there also be `main.js` and `data.json`? as it says in #804

**Comment by ObsidianPC** [comment]
Yup, same problem here.  Windows 10 64bit

**Comment by kefir** [comment]
same on Manjaro. source does not contain main.js and data.json.

**Comment by alfurka** [comment]
Same here. Ubuntu 20.

**Comment by printempts** [comment]
same on win 11

**Comment by artificialflow** [comment]
Error: Failed to load plugin obsidian-excalidraw-plugin.
On macOS

**Comment by Xuxiaotuan** [comment]
same on macOs Monterey 12.5.1

**Comment by cuongphan1408** [comment]
same on mac m1 12.2.1

**Comment by zsviczian** [comment]
I am sorry. I missed the main.js from the release. I now corrected it. Something went wrong during drag and drop.
