### ISSUE TITLE
DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

### ISSUE THREAD

**Issue by devinat1** [zsviczian/obsidian-excalidraw-plugin#843]
I am running the latest version of Obsidian and Excalidraw version 1.7.24. I am getting the following error on my windows 11 machine:
![image](https://user-images.githubusercontent.com/15788108/194967358-229a07a6-7acb-48be-ac27-a2bd3c1258b9.png)
I am simply opening a couple excalidraw files from within my vault.
Obsidian itself becomes very laggy as a result of this DOMException.

**Comment by devinat1** [comment]
I closed then reopened the obsidian vault and the issue seemed to go away.
However, it comes back sometimes which I'm not sure exactly when so I cannot reproduce.

**Comment by yandiro** [comment]
I am having the same issue.

In my case, we try to print text and an image
