### ISSUE TITLE
Pop-in with a prompt when exporting to png

### ISSUE THREAD

**Issue by Krakor92** [zsviczian/obsidian-excalidraw-plugin#844]
Hello,

Thanks for this incredible plugin, I've been using it for about 2 weeks now and it's unreal how a game changer it is.
It legitimates the use of Obsidian all by itself.

But i'm having some frustrations when it comes to exporting to png.
Right now, the only way (that I know of) to change the settings for a specific export is to dive into the Excalidraw plugin options and play with the settings I want to modify before exporting.
It's a bit annoying and the lack of an outliner to quickly go to headers inside the plugins settings doesn't help.

So I think it would be very handy to have the export options appearing in a pop-in when trying to export an excalidraw into a png.

> Something like that
![image](https://user-images.githubusercontent.com/24924824/195137793-5e51cd75-d646-400d-b940-a7820a5cd3e8.png)

I know it wouldn't be perfect based on some scripts i've tried that only have one prompt when using them.
But i'm sure it would be better to type something like [3,0,0] to export with 3x the size, no background and 0 padding rather than doing a deep dive in the settings each time I want to export something.

---

Actually i think maybe it would be better to introduce a new command rather than modifying the current one, with a name like:
`EXCALIDRAW Save as PNG next to the current file (Specify settings)`

OR

You could update the current command and add a new checkbox in the settings allowing users to disable the prompt when running it to only use default parameters (like right now).

What do you think?

**Comment by zsviczian** [comment]
you can set image specific export using front matter keys in the image file. 
Switch to markdown view and try these front matter keys:

excalidraw-export-transparent: true
excalidraw-export-dark: true
excalidraw-export-padding: 5
excalidraw-export-pngscale: 1

you can also add these to your template file if you need to.

**Comment by Krakor92** [comment]
The new "Export Image" dialog in version 1.8.10 addresses everything I listed in this issue (and more).
Thank you very much for your hard work.
I can close this now.
