### ISSUE TITLE
Connection between elements are missing with line/arrow tool

### ISSUE THREAD

**Issue by Wit4r7** [zsviczian/obsidian-excalidraw-plugin#849]
The automatic connection between the two elements is missing. So, what I mean is when I draw a line or an arrow from one element (like a rectangular) to another element previously I got the grey area around the element and the line/arrow was moved with the element when it was moved. This is not working anymore, the line is now a "stupid" element with no function. Also, the grey area is not appearing. 

 - OS including version: MacOS 12.6
 - Plugin version: 1.7.24
 - Obsidian version: 1.0.0

I'm not sure if I miss something, because the existing drawings and the existing lines are still working. Newly drawn lines are not working (same in complete new drawings).

**Comment by zsviczian** [comment]
The connection box is only shown when using the arrow tool not the line tool. This is by design. Can you confirm that it is missing for the arrow, or only just the line?
You can convert an arrow into a line by changing the arrow ending to straight line.

**Comment by Wit4r7** [comment]
oh. I'm not sure, why I thought this is also working with the line tool. 

I can confirm, that it's working with the arrow tool as aspected.
