### ISSUE TITLE
Illustration elements shift and displacement after adding a link to a note in the illustration text

### ISSUE THREAD

**Issue by martialebeau** [zsviczian/obsidian-excalidraw-plugin#850]
**Describe the bug**

**To Reproduce**
1. create a new excalidraw drawing with many images and picture files.(.gpg  etc)
2. insert text on the drawing
3. use the double bracket [[]] to create a link  to an existing note (or create a new note) in the text you just created on the illustration
4. repeat step 3 many times

**Expected behavior**
Next time you come back to the drawing, instead a being displayed straight when you zoom or move in it, the latest element of the drawings (which include the links to notes) are shifted to the right  and tilted (some time, as much as  45 degrees angle )

This is only happening with large drawing including many icon and .gpg and .png)

**Screenshots**
![excalidraw bug (illustration 1) ](https://user-images.githubusercontent.com/113141807/196543242-881515ac-8ef3-41da-8519-970ab2d537db.png)

![excalidraw bug (illustration 2) ](https://user-images.githubusercontent.com/113141807/196544544-9bd1b087-7290-4d2c-a522-9dee1c63151a.png)

![excalidraw bug (illustration 3) ](https://user-images.githubusercontent.com/113141807/196549480-ab880448-8b4a-4e98-82c3-49025ee83138.png)

**Environment (please complete the following information):**
 - OS including version:  Windows 10
 - Plugin version: latest (as of oct 18)
 - Obsidian version: latest (as of oct 18)

**Comment by zsviczian** [comment]
This is a very strange error... I am not even sure I understand the issue correctly. I've never seen text rotate unintended. I tried it now, but could not reproduce anything similar.

I added many images and many links, then closed and opened the drawing, but everything was ok.

Can you send me the file that has this issue so I can take a look?

**Comment by martialebeau** [comment]
Hi !

You need to zoom in and out the drawing (ctrl- rotate mouse weel) for the displacement to occur.

Here is a link to the file:

obsidian://open?vault=My%20Obsidian%20Vault%20(On%20Robot_PC)&file=Excalidraw%20White%20boards%2FCycle%20de%20liberation%20de%20la%20SOLITUDE%2FOrigine%20Psycho-Social%20de%20la%20SOLITUDE%20(Test%20for%20bug%20report)

**Comment by martialebeau** [comment]
Here is the markdown file

[Image shift and displacement bug markdown file.txt](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/9852423/Image.shift.and.displacement.bug.markdown.file.txt) in notepad ++

Hope this help !!

thank you very much :O))

**Comment by martialebeau** [comment]
Hi,

Monday on GitHub  I sent you a  link to the defective drawing (residing in
my vault) and a text file of the code . Let me know if you need anything
else

Many thanks

Martial Lebeau

**Comment by zsviczian** [comment]
I am able to reproduce.

**Comment by zsviczian** [comment]
solved in 1.7.26, will release it soon

**Comment by martialebeau** [comment]
Awesome,

You are the best !!!!

 thanks!

Martial Lebeau, B.A.A, TRAmd
Téléphone : 514 927-5458
