### ISSUE TITLE
Whenever I drag and drop an excalidraw md file into my vault, or have a very large excalidraw file, obsidian crashes

### ISSUE THREAD

**Issue by devinat1** [zsviczian/obsidian-excalidraw-plugin#859]
On the latest version (1.0.3) of obsidian (happened in earlier versions as well), when I drag and drop an excalidraw file from my computer into my vault, obsidian freezes for a very long time (around 2 minutes). Either I have to wait that long, or close down the program and reopen it. This behavior is also true on a samsung galaxy s7+ tablet, and ipad pro tablet, an android pixel and samsung phone, and a windows 11 machine. This would imply that since the file I am dragging and dropping is very large, obsidian sync halts the program while it is syncing. On android devices, I have to restart the app multiple times in order to get it to run.
This was true on multiple versions of excalidraw and also the latest version (1.7.25).
A crash also happens when on tablets, I zoom out, and have drawn a lot on the screen. I end up having to swipe away the app and reopen it, then quickly close the active excalidraw window.

**Comment by zsviczian** [comment]
Do you have Templater installed?
Please disable "Trigger Templater on new file creation" in Templater settings.
Unfortunately this is an issue that has been there with Templater for a long time now, and for some reason is not really getting recognized by the developers.
I have raised this as an issue couple of times and added a pull request to fix it, you may try to raise the priority of the issue on the Templater Github page.

My pull request to fix the issue:
https://github.com/SilentVoid13/Templater/pull/874

The related issues:
https://github.com/SilentVoid13/Templater/issues/873
https://github.com/SilentVoid13/Templater/issues/439

**Comment by devinat1** [comment]
I do. And I think it was merged just now, and now even with templater trigger template on new file creation, it works to drag and drop excalidraw files! 
However, on my ipad, the only 3rd party extension that is installed is excalidraw. On there, obsidian crashes every time I open the app, if I have excalidraw zoomed out to around 10% or less, and there are a lot of elements on the screen (if I drew a lot).
The issue also occurs with my samsung tablet.
On my windows 11 machine, this issue does not occur, even with templater installed.

**Comment by devinat1** [comment]
I have created a new issue #863 since it is probably not directly related to the drag and drop issue.

**Comment by zsviczian** [comment]
> f I have excalidraw zoomed out to around 10% or less, and there are a lot of elements on the screen (if I drew a lot).
The issue also occurs with my samsung tablet.

Can you try 1.7.26? There was an error when zooming below 10%. Now zoom is restricted to max 10%. Does it still crash?

**Comment by devinat1** [comment]
No crash!
