### ISSUE TITLE
Question:  Is there a way to auto export svg with the scene like in excalidraw app?

### ISSUE THREAD

**Issue by ShravanSunder** [zsviczian/obsidian-excalidraw-plugin#860]
This is a question:  Is there a way to auto export svg with the scene like in excalidraw app?

It is the embed scene option below

<img width="846" alt="2022-10-28 1017 Brave Browser Excalidraw" src="https://user-images.githubusercontent.com/5294949/198585115-48717cc0-ea98-4830-bc95-5e154c05eaa2.png">

**Comment by zsviczian** [comment]
Not at the moment.  Can you help me with a practical usecase?

**Comment by ShravanSunder** [comment]
hmm, so currently i'm creating diagrams in obsidian.  Somethings i want to export them as png to a repo in github.  I could take the step to do so by just exporting it as excalidraw.

**Comment by zsviczian** [comment]
So you can auto-export to SVG, PNG, and to Excalidraw formats. You can even set up dual auto export so you have a light and a dark-themed export generated automatically.  In plugin settings, you'll find the Excalidraw format auto-export under Compatibility Features, and the SVG and PNG under Export Settings.

What you cannot do right now is export the PNG file with the embedded native Excalidraw scene embedded.

**Comment by ShravanSunder** [comment]
@zsviczian I guess the use case is the ability to auto export to PNG with the embedded scene.  This way they can be published in get or other blogs or docs and people would be able to use them with excalidraw.

**Comment by angrykoala** [comment]
I would appreciate a feature like this as well, as it would allow me to only keep `.png` files in my vault, which would make it easier for me to organize it, instead of having to keep track of the source `.excalidraw` and the exported files

**Comment by Neykah** [comment]
This feature would be super helpful to my workflow.
While I enjoy using this excalidraw obsidian plugin, we often exchange `.excalidraw.png` files with colleagues on GitHub or Slack, which makes me switch back and forth between Obsidian and the web version of Excalidraw.
This export feature in Obsidian would allow me to ditch the web app altogether.

**Comment by ShravanSunder** [comment]
> This feature would be super helpful to my workflow. While I enjoy using this excalidraw obsidian plugin, we often exchange `.excalidraw.png` files with colleagues on GitHub or Slack, which makes me switch back and forth between Obsidian and the web version of Excalidraw. This export feature in Obsidian would allow me to ditch the web app altogether.

This is my usecase as well

**Comment by zsviczian** [comment]
I am implementing this in 1.8.8

**Comment by ShravanSunder** [comment]
wow thanks @zsviczian!
