### ISSUE TITLE
"Could not open ScriptEngine repository" error

### ISSUE THREAD

**Issue by YIRU69** [zsviczian/obsidian-excalidraw-plugin#867]
![image](https://user-images.githubusercontent.com/48148292/199367032-08d130fc-5177-491e-abac-72fa843612b7.png)

Same as https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/504

The excalidraw and the obsidian vision is the newest. 17.2 & 1.03

And I can open it.  https://raw.githubusercontent.com/zsviczian/obsidian-excalidraw-plugin/master/ea-scripts/index-new.md

**Comment by YIRU69** [comment]
I try to use the excalidraw on new empty folder and it works. 
 Maybe it happen error that I setting something and cause it>
I believe it works if I reinstall it.

**Comment by YIRU69** [comment]
OH< 
I find the reason what it cause the scriptengine could not open.
It is fact as me that when I install and open plugin:obsidian42-strange-new-worlds and the excalidraw scriptengine can't open.

**Comment by yiguang20** [comment]
Same reason. Helps a lot!

**Comment by TfTHacker** [comment]
Hi Everyone. @zsviczian has informed me of the issue and I will get an SNW fix out today if not by tomorrow at the latest. Sorry for the inconvenience it may have caused any of you.

**Comment by TfTHacker** [comment]
@zsviczian I have updated SNW to 1.0.3, and I think this is now resolved.

**Comment by YIRU69** [comment]
@TfTHacker @zsviczian  Thanks! It solved.
