### ISSUE TITLE
Edit link icon does not update link

### ISSUE THREAD

**Issue by badjerphoenix** [zsviczian/obsidian-excalidraw-plugin#871]
When I click the edit link icon for an existing link I cannot actually edit the link so that it links up to a different file

I click the link, the edit link icon (notepad with pencil) pops up & I edit the text. When I click away/ control + enter to save the edited text it has not been saved in the link itself. If I click the link to open the edit mode it does show the link changed but it is not changed in the preview of it with Excalidraw. However, once I close the drawing & open the file again the text that was updated in the link has also reverted back to the original text

To reproduce
1. Click the link I want to edit
2. Choose the edit option that appears
3. Replace text with the link that you want
4. Click away to save it
5. Preview is not updated
6. Click link again & the text that shows up is the edited text but only from the edit not the preview
8. Close file or Obsidian
9. Open file & link shows link reverted to original again

**Comment by zsviczian** [comment]
Is this about a text element that also has a [[link]] in the text?

If you have a [[link]] in the text element that will take precedence over the link in the element link and will overwrite the element link. This is by design.

**Comment by badjerphoenix** [comment]
I believe so if I am understanding correctly. 

I link the text element to a file in my vault. IE as per example 1 below I would type [[Excalidraw test-link]]. Later on it becomes apparent that I would be better suited to connect the text to a different file so I edit it accordingly. In example 1 the [[Excalidraw test-link]] now becomes [[Excalidraw test-child]]

By the sounds of things the design is for the text element (presumably this refers to the preview, what the user sees on the canvas) to stay the same. So the edit only effects the link element itself.

That would mean the  purpose of the link edit icon is just to edit the link element but not the text element itself? So if I needed to edit the text element I would need to start from scratch. That is, delete the entire link. Meaning that the text element & link element  are both deleted. Create a new text element & in turn the link element will also be populated

If what I have listed above is correct there is one other thing I need clarification on. In a scenario where I edit the link element (thus the text element stays the same) should the link element not now stay to what it was changed/ saved to?

Once I close the file & open it again the link element reverts back to the original link element  as per example 2. For instance, in example 1 I changed the link element from [[Excalidraw test-link]] to [[Excalidraw test-child]]. Then I close the Excalidraw file & later on open it. When I do so the link element is now [[Excalidraw test-link]] again not [[Excalidraw test-child]].

Perhaps I am still misunderstanding but I don't believe this is expected behaviour as well, is it?

![example 1](https://user-images.githubusercontent.com/78933852/200125352-86d75279-94e1-4095-a90b-366195414f7a.png)

![example 2](https://user-images.githubusercontent.com/78933852/200128585-60c5c9f8-ec7c-4f3f-a8eb-bf6d7eaec430.png)

**Comment by zsviczian** [comment]
The reason for the design is heritage more than anything else. The Excalidraw-Obsidian plugin supported links well before the Excalidraw.com component implemented element links. Unfortunately, these two resulted in a slightly confusing setup - that you are experiencing now. The same design conflict is apparent in the element link icon that is included in front of the text element as well as in the top right corner for text elements. Sorry for that ...

The primary use case supported by the plugin is that for text elements you should edit the text in the text element and not the element link. The element link will always be a copy of the [[link]] in the text element's text. If, however, you don't include a [[link]] in the text element text, then you can use the element link as you would for any other element (rectangle, circle, etc) it won't be overwritten.

You can always add a [[link|alias]] if you want to display a different text compared to the name of the linked file.

hope this explains.

**Comment by badjerphoenix** [comment]
Ok that makes more sense then. Basically these icons were put in place due to the Excalidraw.com plug in vs the Obsidian plug in.

To edit the text element simply double click within it & edit. Just ignore the icon option

> You can always add a [[link|alias]] if you want to display a different text compared to the name of the linked file

Sounds good. That is what I used to do before I saw the icon. Will keep doing so

> If, however, you don't include a [[link]] in the text element text, then you can use the element link as you would for any other element (rectangle, circle, etc) it won't be overwritten.

Could you expand a bit more on this? Having troubles visualising this part
