### ISSUE TITLE
iPad load stencil does not work.

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#88]
Confirmed by RoamHacker.

**Comment by zsviczian** [comment]
Seems to be related to other plugins. Turning everything else off resulted in Excalidraw working as designed.

**Comment by afenc** [comment]
Turning off all other plugins on my ipad makes my pencil working.

**Comment by zsviczian** [comment]
I never really managed to get to the bottom of this issue.
In the meantime, I have purchased an iPad, but I am not able to reproduce
the error.
Were you able to find which plugin is causing the issue?
