### ISSUE TITLE
.svg is not deleted when .excalidraw is deleted

### ISSUE THREAD

**Issue by dcoales** [zsviczian/obsidian-excalidraw-plugin#89]
It looks like the most recent version (1.2.4) doesn't delete the .svg files when the corresponding .excalidraw file is deleted - tested in legacy mode.

**Comment by zsviczian** [comment]
Thanks! I've corrected this in 1.2.5
Your issue also highlighted a bigger problem with migration (also corrected in 1.2.5). When files are converted from myDrawing.excalidraw to myDrawing.excalidraw.md, SVG files weren't updated from myDrawing.svg to myDrawing.excalidraw.svg.

If you have the compatibility feature to automatically generate .excalidraw files parallel to .md files, the .md file is the master; for files to stay in sync you need to rename, delete, etc. the .md file and the .excalidraw and .svg or .png files will follow. If you just update the .excalidraw file then the .md file will get disconnected, but the .svg and .png files will follow the change.  The logic is not perfect, but I decided to leave it at this to avoid the logic getting too complex and consequently very hard to maintain.

**Comment by dcoales** [comment]
Excellent.  Thanks very much.
