### ISSUE TITLE
BUG:  Excalidraw is not working on my iPhone

### ISSUE THREAD

**Issue by Rexlolol** [zsviczian/obsidian-excalidraw-plugin#894]
**Your environment**

SYSTEM INFO:
	Operating system: ios 13.1.3 (Apple iPhone)
	Obsidian version: 1.4.1 (83)
	API version: v1.0.3
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Blue Topaz
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 6
	Plugins enabled: 3
		1: Dataview v0.4.26
		2: Advanced Tables v0.17.3
		3: Excalidraw v1.7.30

**Describe the bug**
I'm not able to use Excalidraw on my iPhone. 

**To Reproduce**
1. Click on create a new Excalidraw
2. Screenshot below

**Expected behavior**
Expected to work as it's on PC

**Screenshots**
![image](https://user-images.githubusercontent.com/69944627/202824967-d5b3d1f4-61f8-43c0-ba72-97cf5a8a7d37.png)

**Comment by zsviczian** [comment]
I was able to reproduce something that looks similar on a 14.7.1 device. Just to make sure we are talking about the same issue: if you open a new drawing, Excalidraw shows correctly, but when you add an element to the canvas, the canvas goes black, and only if you then pull on the right sidebar does it show again?

On my iPad with iOS 15.6.1 I don't experience the same.

**Comment by zsviczian** [comment]
I have upgraded my phone to iOS15.7 which resolved the issue.
Please try the next release 1.7.31 (likely released tomorrow). I will build it with a lower compatibility setting... it seems the old iOS does not support some new javascript functionality. Maybe the compatibility setting will solve your issue.
If not, there isn't much more I can do for you. I am sorry.

**Comment by Rexlolol** [comment]
> I have upgraded my phone to iOS15.7 which resolved the issue.
> 
> Please try the next release 1.7.31 (likely released tomorrow). I will build it with a lower compatibility setting... it seems the old iOS does not support some new javascript functionality. Maybe the compatibility setting will solve your issue.
> 
> If not, there isn't much more I can do for you. I am sorry.
> 
> 

Thank you so much 😊. I would just have  use Excalidraw on PC instead if it still don't work. Or maybe just have to update my system which I don't want
