### ISSUE TITLE
Editing issues when used in combination with Sliding Panes plug-in

### ISSUE THREAD

**Issue by bwydoogh** [zsviczian/obsidian-excalidraw-plugin#9]
When used together with the (popular) Sliding Panes plug-in editing issues occur: when a note is open AND you open an Excalidraw file in a new pane, editing of that drawing is not possible (drawing appears, but you cannot select any existing element of that drawing). 

Issue does not occur when that sliding panes plug-in is disabled.

**To Reproduce**
1. Activate "Sliding Panes" plugin
2. Open a note
3. Open an existing Excalidraw file
4. Try to edit that drawing

**Expected behavior**
Drawing can be edited.

**Desktop (please complete the following information):**
 - OS: macOS
 - Latest 1.0.0 version of the plug-in

**Comment by zsviczian** [comment]
Hopefully resolved in 1.0.2 Please test. Should be out in 15 mins.

**Comment by bwydoogh** [comment]
Fixed. Thanks!
