### ISSUE TITLE
Minor: Deleting an excalidraw drawing does not close the pane

### ISSUE THREAD

**Issue by davecahill** [zsviczian/obsidian-excalidraw-plugin#90]
**Describe the bug**
Deleting the currently opened excalidraw drawing does not close the pane.

**To Reproduce**
* Create a new excalidraw drawing
* With the pane of the excalidraw drawing selected, click on the kebab menu (3 dots) of and click Delete this file.
* The pane does not close - however, if you close it manually and open Quick Switcher and search excalidraw, you will see that the drawing has been deleted.

**Expected behavior**
I expect the drawing pane to be closed when I click Delete this file.

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Obsidian Version v0.12.10
 - Excalidraw plugin version 1.2.5

**Comment by zsviczian** [comment]
Thanks! I will take a look at this. It may take a while though, as I am now focused on cleaning out some of the more serious teething issues.

**Comment by zsviczian** [comment]
Fixed in 1.2.6
