### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by shivanshu-semwal** [zsviczian/obsidian-excalidraw-plugin#906]
README file is cluttered and have mamy images and have no particular sections and is not navigable.  I think the videos should be in a list and not in table with images, and each link can have a description. Features should have sections to navigate.

Here is a sample I created from the README

[https://gist.github.com/shivanshu-semwal/52a6d024b0e72be5b3ba0247fc7c7840](https://gist.github.com/shivanshu-semwal/52a6d024b0e72be5b3ba0247fc7c7840)

**Comment by zsviczian** [comment]
Awesome! Thank you.
I haven't read it through in detail, but it looks very readable. Did you build this based on the latest version of the readme? Apart from the video images, did you delete anything else?

**Comment by shivanshu-semwal** [comment]
I removed the images which was in start and in end (for ExcaliBrain). I think adding only the logos will be sufficient and not a big thumbnail (for that you can make a new screenshot section). Rest everything is same just divided into sections and long points into multiple points.

I removed the thumbnails and replaced them with the caption and the title of youtube video, but adding some description to the video links will also be helpful.

**Comment by zsviczian** [comment]
Thank you! I deployed the new Readme.
I very much welcome any help I can get to keep on top of this plugin. In case you have suggestions to improve the content... please do.
