### ISSUE TITLE
Is it possible to preserve scroll position

### ISSUE THREAD

**Issue by echo-saurav** [zsviczian/obsidian-excalidraw-plugin#907]
For big sketch its cumbersome to scroll and zoom to the position every time i open the file.  
It would be great if it scroll to the position i last left 
also , I don't know if its possible, can there be multiple link for scroll area? like multiple link to open the sketch and focus on different  part of the sketch

**Comment by zsviczian** [comment]
I will add an additional setting to prevent autozoom altogether.

**Comment by zsviczian** [comment]
will include in 1.8.1

**Comment by echo-saurav** [comment]
Hey , I couldn't find the auto zoom settings. Did you add auto zoom to 1.8.1??

**Comment by zsviczian** [comment]
I did.
It's in the "Display" section of the plugin settings:

![image](https://user-images.githubusercontent.com/14358394/204981984-7b120536-e085-4b7b-8aa5-e86cc28633e2.png)

**Comment by echo-saurav** [comment]
Strange ! for me its not showing 
<img width="806" alt="Screenshot 2022-12-03 at 12 44 35 AM" src="https://user-images.githubusercontent.com/76121100/205364377-d255d344-d83a-44ba-bfe5-ae6eb899dd15.png">
<img width="806" alt="Screenshot 2022-12-03 at 12 44 55 AM" src="https://user-images.githubusercontent.com/76121100/205364404-f6683edb-3789-4db2-8207-07b807f5de1a.png">

**Comment by echo-saurav** [comment]
found it in 1.8.2 , thanks
