### ISSUE TITLE
Will it support the feature of inserting image from url?

### ISSUE THREAD

**Issue by Mickychen00** [zsviczian/obsidian-excalidraw-plugin#913]
**Is your feature request related to a problem? Please describe.**
Will it support the feature of inserting image from url?

**Describe the solution you'd like**
In the past, I always upload my image to the cloud and insert the url of this image to Obsidian editor. This measure will keep our vaults tiny. Obsidian will display this image correctly as clear as the local image. But now Excalidraw only supports local images, I think it will be very useful if it supports this feature.

**Describe alternatives you've considered**
I don't know how to achieve it.

**Comment by zsviczian** [comment]
that has been on my todo for ages. Yes, definitely my plan... just need to get to it.

**Comment by zsviczian** [comment]
This feature is coming in 1.8.11 🎉
