### ISSUE TITLE
FR: Double click on embedded drawings to edit them

### ISSUE THREAD

**Issue by SandWoodJones** [zsviczian/obsidian-excalidraw-plugin#920]
Currently clicking an embedded drawing once opens the canvas to edit it. This is frustrating when i click it accidentally or when I want to change the link or image size.

I'm used to clicking once on latex equations to open and edit them so I'd like the same behavior on excalidraw drawings.

An option for double clicking to open in canvas would be appreciated.

**Comment by zsviczian** [comment]
I like this idea. I also sometimes accidentally open images... Why haven't I thought of the double click option?
I hope to add this to the next release.

**Comment by zsviczian** [comment]
I've added this to 1.8.4. Will release it probably today.
