### ISSUE TITLE
BUG: Not able to use pencil to add text input on ipad

### ISSUE THREAD

**Issue by saeedesmaili** [zsviczian/obsidian-excalidraw-plugin#927]
**Your environment**
```
SYSTEM INFO:
	Operating system: ios 16.1.1 (Apple iPad)
	Obsidian version: 1.4.1 (83)
	API version: v1.0.3
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 6
	Plugins enabled: 3
		1: Dataview v0.5.47
		2: Icon Shortcodes v0.9.7
		3: Excalidraw v1.8.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Describe the bug**
When I try to add a text input using an apple pencil on an iPad, it switches back to the text input tool (or selection tool, depending on if `keep selected tool activate after drawing` is selected). I can add text input with apple pencil without a problem on excalidraw.com. A video recording of both this plugin and excalidraw.com:

https://user-images.githubusercontent.com/13351748/205993924-4dca792d-edec-40ad-8100-ad62aba5349d.mp4

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zsviczian** [comment]
hm... I did not notice that it (sort of) works on excalidraw.com. I just tried it now on Excalidraw.com - my issue was that words kept being written together... I could not reliably get the space in between words.

After some experimentation I also managed to get it to work in Obsidian as well, the trick was to start writing on the cursor as it appeared.

For Obsidian I added the Scribble Helper script. It is a workaround, and it is not elegant... but it works reliably for me. I recommend installing and using it for now. 

I will try and investigate what might be the source of the difference in behavior between excalidraw.com and Obsidian-Excalidraw. But to manage your expectations, unfortunately, Apple makes it technically and literally impossible to debug an iPad if you are not using a Mac... which makes solving these issues extra difficult and often impossible for me. I guess this is the other side of the balance when building a closed ecosystem as Apple tends to do :(

**Comment by saeedesmaili** [comment]
Thanks for looking into this issue and recommending the Scribble Helper script. I will give it a shot.
Yeah, I also can't get the space in between the words in excalidraw.com as well, and I wish they fix it some day.
By the way, I have a mac and a bit of technical knowledge, and I'd be more than happy to help with debugging the apple pencil issues and improving its experience with this plugin. Let me know if I can do anything.

**Comment by zsviczian** [comment]
Thinking on your issue over night... I have an idea why scribble is not working (i.e. the issue with getting the spaces between words) and if I solve that it will also solve the editing issue - and I don't even need to debug the iPad for this :)

**Comment by zsviczian** [comment]
[![](https://i9.ytimg.com/vi_webp/BvYkOaly-QM/maxresdefault.webp?v=64442f6a&sqp=CLiMxaYG&rs=AOn4CLBC1qUq3KTHY-luJdoWEJh2p8bxSg)](https://youtu.be/BvYkOaly-QM)
