### ISSUE TITLE
BUG: Sometimes LaTeX color does not work

### ISSUE THREAD

**Issue by SandWoodJones** [zsviczian/obsidian-excalidraw-plugin#928]
**Your environment**
```
SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v0.15.9
	Operating system: Windows 10 Education 10.0.19043
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Atom
	Snippets enabled: 8
	Restricted mode: off
	Plugins installed: 15
	Plugins enabled: 15
		1: Obsidian Git v2.12.1
		2: Paste URL into selection v1.7.0
		3: LanguageTool Integration v0.3.3
		4: Better Word Count v0.9.0
		5: Editor Syntax Highlight v0.1.3
		6: Outliner v4.1.1
		7: Quick Latex for Obsidian v2.5.1
		8: Desmos v0.6.4
		9: Advanced Tables v0.18.0
		10: Better footnote v1.0.1
		11: Footnote Shortcut v0.0.9
		12: Tidy Footnotes v0.1.1
		13: Multi-Column Markdown v0.7.6
		14: Excalidraw v1.8.4
		15: Commander v0.4.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Describe the bug**
Sometimes, not all times, embedded drawings with LaTeX formulas using `\color` break. This usually can be fixed with closing and opening obsidian but sometimes it gets stuck as broken.

**To Reproduce**
1. Create new drawing
2. Insert LaTeX formula
3. `\color{white}X`

**Expected behavior**
LaTeX formula with the specified color.

**Screenshots**
![image](https://user-images.githubusercontent.com/35671374/206039238-6c0289d1-884e-4d3a-9677-0fb3db957cd4.png)

**Additional context**
After installing the last update I closed and reopened obsidian and all my drawings with formulas were like this. Further closing and opening did not help in this case. I have tried rolling back to a previous release but it still didn't work.

**Comment by zsviczian** [comment]
This looks like an issue with loading the LaTeX library. The fallback is to use the library loaded in Obsidian by default, but that has limitations. Try changing this setting to another mirror:

![image](https://user-images.githubusercontent.com/14358394/206134580-7482ee89-9c0e-498b-a3a0-d5147c34563a.png)

**Comment by SandWoodJones** [comment]
This worked but i'm curious as to what those limitations are

**Comment by zsviczian** [comment]
If you are interested in technical details... The issue is that Obsidian uses the tex-chtml package, but Excalidraw requires the tex-svg package. This creates a number of challenges for he plugin... practically when I am not able to load the tex-svg package then I use the tex-chtml package and print the resulting HTML to a canvas and save that as an SVG image. In this process some of the formatting is lost.

https://docs.mathjax.org/en/latest/web/components/combined.html
