### ISSUE TITLE
 Drag notes and [[add them]] to the drawing #3830 

### ISSUE THREAD

**Issue by cristianvasquez** [zsviczian/obsidian-excalidraw-plugin#93]
Thanks for the 'store in markdown' feature,
it's really a game-changer as we can use excalidraw to build visual MOCs!

To make that process easier, drag and drop can help

**Comment by zsviczian** [comment]
I am working on that. Unfortunately I ran into some blockers... as of now I can't promise a delivery timeline, but the feature is definitely on my roadmap.

**Comment by zsviczian** [comment]
Solved in v1.3.1
