### ISSUE TITLE
High Ms(ping of excalidraw plugin)

### ISSUE THREAD

**Issue by paranjay245** [zsviczian/obsidian-excalidraw-plugin#937]
![image](https://user-images.githubusercontent.com/120307516/206925687-1a3c5b2f-667b-4249-aea6-9f8f6b0fe6e1.png)

High Ping for each device be it be mac or ipad or windows everywhere i am experiencing high ms

and

1. I Tried With new vault same issue
2. I Also Tried Formating Mac & With Fresh OS & Vault

**Comment by zsviczian** [comment]
Yes, this is because the Excalidraw package is large, this is simply the time for the javascript interpreter to initialize the excalidraw package with all its components. There is not much I can do about it. Sorry.
