### ISSUE TITLE
BUG: When there is text on the arrow, the exported svg image is inconsistent.

### ISSUE THREAD

**Issue by skyline-123** [zsviczian/obsidian-excalidraw-plugin#941]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.

**Describe the bug**

<img width="524" alt="image" src="https://user-images.githubusercontent.com/22638687/207845846-40fa4bd4-fa5e-47e9-8de5-11e2abdb7312.png">
<img width="437" alt="image" src="https://user-images.githubusercontent.com/22638687/207845868-b352ddb1-7994-4f13-a0b2-f2e19bd72935.png">
When there is text on the arrow, there is a problem with the exported svg, but there is no problem on the excalidraw website

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by skyline-123** [comment]
BTW, PNG images have the same problem.

**Comment by zsviczian** [comment]
I am able to reproduce. I will look into this.

**Comment by zsviczian** [comment]
fixed in 1.8.5
