### ISSUE TITLE
BUG: Reset prompt repeats

### ISSUE THREAD

**Issue by skyline-123** [zsviczian/obsidian-excalidraw-plugin#942]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.

**Describe the bug**

<img width="212" alt="image" src="https://user-images.githubusercontent.com/22638687/207865804-48360656-4416-4188-9355-ad42ead72c76.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zsviczian** [comment]
fixed in 1.8.5
