### ISSUE TITLE
BUG: Excalidraw hard FPS drop when too much draw/png

### ISSUE THREAD

**Issue by OignonFrit** [zsviczian/obsidian-excalidraw-plugin#948]
**Describe the bug**
Hello !
I noticed that when i draw too much on the same page (i'm also used to paste many image from flaticon), it becomes hard to add anything on it 
The stat for nerds shows that i'm at 1600 elements 
![image](https://user-images.githubusercontent.com/119637652/208761232-2b555c1f-18bf-4b7c-b3e2-4f2ed43909c9.png)

**Additional context**
Sometimes when launching the draw it's written "Loading scene" permanently

And nothing to see with this problem but it also concern excalidraw : 
- i can't create new drawing anymore and i don't know why 
Shortcut or ribbon icon does nothing, the only way i have to create a new drawing is to convert an existing into excalidraw  

- On tablet drag and dropping image shows https

**Already tried**
- Disable all my plugins 
- Disable snippet

Thanks for any response

**Your environment**
SYSTEM INFO
	Obsidian version: v1.1.8
	Installer version: v1.0.3
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Obsidian Nord v0.1.7
	Snippets enabled: 9
	Restricted mode: off
	Plugins installed: 21
	Plugins enabled: 21
		1: Excalidraw v1.8.6
		2: Admonition v9.0.5
		3: Advanced Tables v0.18.0
		4: Banners v1.3.3
		5: Calendar v1.5.10
		6: Customizable Menu v2.2.0
		7: Dataview v0.5.47
		8: Editor Syntax Highlight v0.1.3
		9: Emoji Shortcodes v2.2.0
		10: Enhancing Mindmap v0.2.4
		11: Image Toolkit v1.3.1
		12: Mind Map v1.1.0
		13: Note Refactor v1.7.1
		14: Quick Latex for Obsidian v2.5.1
		15: Review v1.6.4
		16: Spaced Repetition v1.9.1
		17: Style Settings v0.4.12
		18: Commander v0.4.1
		19: Natural Language Dates v0.6.1
		20: Editing Toolbar v2.2.3
		21: Homepage v2.5.1

**Comment by zsviczian** [comment]
Try reducing the autosave frequency in Plugin Settings
![image](https://user-images.githubusercontent.com/14358394/209066541-52ca2878-608f-4a24-b847-d75f7d869b4d.png)

Try using the deconstruct image script to break your canvas into parts:
https://youtu.be/HRtaaD34Zzg
https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Deconstruct%20selected%20elements%20into%20new%20drawing.md

**Comment by OignonFrit** [comment]
Hey zsviczian ! 
Firstly i want to thanks you for this amazing plugin and all the work you're doing around it, that's a pleasure to use and it really makes my medecine course easy to ingest combined to obsidian link

**Deconstruct plugin**
Thanks for your answer, the deconstructed solution you gave me worked perfectly it's not laggy anymore but...
On your youtube video you are clicking on the new deconstructed drawing to open it 
I tried SHIFT + CLICK / CTRL + CLICK / Double click nothing works 

**Reduce Saving time**
I already tried this option on mobile (where it lags the most) but i didn't see any improvement 
I'll still going to try it over a longer period of time to see if there's any change

**New excaldraw drawing icon**
Sorry to bother you but do you have any solution to make this icon or shortcut works again

**Comment by zsviczian** [comment]
CTRL+click should open the image...

In Excalidraw plugin settings under links and transclusions there is a setting to enable / disable CTRL+click. Maybe that is turned off for you?

![10442D98-CD02-42F7-A72D-C7DD62405510](https://user-images.githubusercontent.com/14358394/209283505-615dedfb-f80e-47e7-88ba-c1790c9562ac.jpeg)

Try clicking on an area where you see a line or color filled object, not clicking in an empty part of the picture.

**Comment by OignonFrit** [comment]
Ok nevermind i'm just lost with all these options : it works ✔️ 

No idea for the "new drawing icon/shortcut" not working anymore ? It's handicaping to convert note => excalidraw every time

I really tried to turn off every option one by one, every plugin and snippets but nothing, i can't get it back
Do i have to reset obsidian ?

**Comment by zsviczian** [comment]
Yes, the number of settings has grown over the past two years... 

Just to make sure I understand you correctly, you are referring to the ribbon button?

![image](https://user-images.githubusercontent.com/14358394/209362484-4870a439-9431-489e-b86a-648080de8968.png)

Are you getting an error message in the Developer Console when pressing the ribbon button? (CTRL+SHIFT+i or CMD+SHIFT+i on a Mac)

You can also create a new drawing by right-clicking the folder in the Obsidian file explorer:
![image](https://user-images.githubusercontent.com/14358394/209362809-96c08aed-3d43-4524-bf11-883c36701266.png)

and you can create a new drawing via the command palette as well
![image](https://user-images.githubusercontent.com/14358394/209362892-bfb62ed4-a76c-4be7-b3ac-699abc6ec394.png)

hope this helps

**Comment by OignonFrit** [comment]
Ok the issue is solved i guess it's a bug maybe the last update ?
If you leave the "Filename prefix" empty it won't create new drawing anymore no matter if you use the ribbon icon, shortcut, right click or command palett
```
"drawingFilenamePrefix": "",
```
As soon as you fill with anything in there it will works again
Note : Even if it is written "drawin" this is empty on the following image
![image](https://user-images.githubusercontent.com/119637652/209365409-e14134b3-5894-4b28-a9b5-e605092c7767.png)
