### ISSUE TITLE
BUG: Cannot exit fullscreen mode

### ISSUE THREAD

**Issue by mbbowker** [zsviczian/obsidian-excalidraw-plugin#950]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.1.8
	Installer version: v0.15.9
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v1.8.6

**Describe the bug**
Pressing the "F" key enables "Obsidian fullscreen" (i.e. it hides the Window's task bar). This mode can be exited by pressing "F" again or pressing "Esc".

To get "Excalidraw fullscreen" (i.e. hide the tabs list and all the Obsidian buttons) you press the "fullscreen button"
![image](https://user-images.githubusercontent.com/120921767/209318128-719cd91d-a260-4834-9e7a-90523ef28a65.png)

Once in "Excalidraw fullscreen" mode, there does not seem to be any way to exit it. Pressing "Esc" does not work. If there is a button, it may be hidden by the Windows "Minimize / Restore Down / Close" buttons. The Obsidian actions button is hidden by these.
![image](https://user-images.githubusercontent.com/120921767/209318595-7b6e29de-2f37-4a42-b3b3-e13427cb86b9.png)

The only way I can find to exit this fullscreen mode is to close obsidian and re-open it, at which point the Excalidraw tab appears in the tab list with the rest of my tabs that were open before I enabled "Excalidraw fullscreen". 

**To Reproduce**
1. Open an Excalidraw tab
3. Click on 'fullscreen mode' button
4. Try to exit by pressing "Esc"
5. See error

**Expected behaviour**
Fullscreen mode to exit when "Esc" is pressed.

**Screenshots**
![image](https://user-images.githubusercontent.com/120921767/209318128-719cd91d-a260-4834-9e7a-90523ef28a65.png)
![image](https://user-images.githubusercontent.com/120921767/209318595-7b6e29de-2f37-4a42-b3b3-e13427cb86b9.png)

**Comment by huiyang-work** [comment]
[Excalidraw 1.8.0](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.8.0)
New and improved full-screen mode

- Activate using the Obsidian tools panel, the Obsidian Command Palette, or the Alt+F11 shortcut

- The ESC key no longer closes full-screen

- Full-screen mode works properly on iOS as well
