### ISSUE TITLE
Intelligent image width setting 

### ISSUE THREAD

**Issue by jiewangjs** [zsviczian/obsidian-excalidraw-plugin#955]
Current, there is a setting parameter controlling the width of embedded excalidraw image width.
However, I found when embedded image is small, the image would be extended to meet the aforementioned width setting.
Could you make the less-than-prescribed-width images stay their original 100% size, only those larger-than-prescribed-width images shrinked to meet the image width setting ? 
![image](https://user-images.githubusercontent.com/11204422/209901140-dc733e40-8164-4c66-813b-c93f46d6e1b4.png)

**Comment by zsviczian** [comment]
good suggestion. I'll check what impact it would have if I'd change `width: `, to `max-width:` in the style. That would achieve exactly what you are looking for.

**Comment by zsviczian** [comment]
will be solved in 1.8.8

**Comment by jiewangjs** [comment]
Hi, I see the new release. 
But I didn't see this issue being handled well. 
I think maybe we have some misunderstanding. 
What I mean is when content (texts, drawings etc) in the excalidraw canvas is little (far more less than max-width setting), all these contents (texts, drawings etc) should preserve their orginal sizes (say, 12 fontsize, 1px line width etc), and should not be extended to meet the max-width setting (say, 24 fontsize, 2px line width etc).
![image](https://user-images.githubusercontent.com/11204422/211157195-bd84e70f-ee90-442e-b1a5-630757589efc.png)

**Comment by jiewangjs** [comment]
Er... I found a strange problem, that is my installation says that I am using version 1.8.8, while my excalidraw pane keeps notifying me that I am using version 1.8.7.
Then I uninstalled and reinstalled, and voila, it all works. 
Sorry for the confusion.
