### ISSUE TITLE
FR: Add the ability to let users download your example pens, download user created pens and add pens to a public library with a preview image from Awesome Pen

### ISSUE THREAD

**Issue by rorar** [zsviczian/obsidian-excalidraw-plugin#962]
**Is your feature request related to a problem? Please describe.**
I'm not an experienced GitHub user and I bet grandmas secret soup reciepe there are a lot of Obsidian Excalidraw users like me out there. There is no download option for your example pen.

**Describe the solution you'd like**
From UX perspective it seems to be a good idea to have a download option for example pens inside of Obsidian Excalidraw.
Also it would be a huge helper to download pens created by other users to have an universal library (Also with a sight in the fiture if Alternative pens would be intregrated into Excalidraw itself)

**Describe alternatives you've considered**
Copy and pasting the "code" from the GitHub repository

btw. thanks for the Awesome Pen Script 👍

**Comment by zsviczian** [comment]
was already solved in a later release. custom pens can be configured in plugin settings. https://youtu.be/OjNhjaH2KjI
