### ISSUE TITLE
FR: Eraser for Microsoft Surface Pen 2 Support

### ISSUE THREAD

**Issue by devinat1** [zsviczian/obsidian-excalidraw-plugin#965]
I know it is possible to have eraser support due to https://github.com/excalidraw/excalidraw/issues/5281 and since it works on websites which enable it, such as the Microsoft whiteboard website. Could eraser support be added for obsidian Excalidraw as well? If the official Excalidraw does not support it, then it could be added, perhaps as a script like in issue 5281.

**Comment by zsviczian** [comment]
So I tested the approach of using `event.button` with my Huion tablet & pen, my Samsung + sPen, and my iPad + pencil. Unfortunately in all these cases, the button had no effect, event.button was always === 0.

You could implement #5281 with a template startup script that would add this listener to your Obsidian vault and generate an "E" keypress when you pressed the button. This seems relatively simple to do based on the description of the issue you are referencing. Unfortunately, I can't do this for you, as I can't test it... thus I won't know if it is working. If you make this work with a template startup script, please share the result so others with a surface tablet can take advantage of it.

I have an example of using a startup script here:
https://youtu.be/LtR04fNTKTM

**Comment by githubbapoopa** [comment]
+1 for Wacom pens

**Comment by devinat1** [comment]
Thanks for the new feat! Eraser works great.

**Comment by ojcobb** [comment]
@devinat1 would you mind elaborating on how you used the above to get eraser support? 🙏

**Comment by devinat1** [comment]
@ojcobb once I installed the hardware eraser plugin, it worked where I was able to click the button for that plugin and then use the eraser on the surface pen.

**Comment by ojcobb** [comment]
@devinat1 sorry for such a stupid question, but how do I install the hardware eraser plugin?

**Comment by devinat1** [comment]
@ojcobb When you open an excalidraw file, there is a button on the top right to install excalidraw scripts.

**Comment by ojcobb** [comment]
Got it! Thanks a lot!
