### ISSUE TITLE
FR: canvas moving tool

### ISSUE THREAD

**Issue by hlageek** [zsviczian/obsidian-excalidraw-plugin#966]
While moving around the canvas works great on mobile and desktop (and the plugin is just amazing overall), I have a use case with an external touch monitor (keyboard/mouse out of reach, but stylus available) for which it would be helpful to have the possibility of having a tool in the toolbox that would allow me to navigate the canvas with a stylus. 🙏

**Comment by zsviczian** [comment]
What stylus are you using? On my Huion drawing tablet, I configured the second pen button to the "Space" button. When I press it I can pan the page with the pen in hand. Btw, I configured the first button to "E", and it activates the eraser. The second time I press it, I get back the drawing tool I was using previously.

**Comment by hlageek** [comment]
I'm using an external touch monitor (electronic whiteboard) that registers as a monitor, not as a mobile device. The touch/stylus therefore only registers as the mouse pointer in this setting. Hence I would like to have a way of activating the panning tool without a keyboard. Apologies, my description of the feature made it seem like I am talking about a tablet/mobile context, but this is actually intended for the desktop environment.

**Comment by hlageek** [comment]
Solved in [1.8.12](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.8.12) via excalidraw/excalidraw/pull/6141 👍
