### ISSUE TITLE
BUG:  Issues with the dimensions of area transclusions.

### ISSUE THREAD

**Issue by Ruminov** [zsviczian/obsidian-excalidraw-plugin#967]
**Your environment**

SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Windows 10 Home Single Language 10.0.19045
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 42
	Plugins enabled: 17
		1: Excalidraw v1.8.9
		2: Alias from heading v1.0.12
		3: Banners v1.3.3
		4: Code Editor Shortcuts v1.11.0
		5: Dataview v0.5.53
		6: Hider v1.2.4
		7: Hotkeys for specific files v1.2.1
		8: Hotkeys for templates v1.4.3
		9: Kanban v1.5.1
		10: Meld Encrypt v2.0.4
		11: Metadata Menu v0.4.10
		12: MetaEdit v1.7.2
		13: Pane Relief v0.4.1
		14: Quick Explorer v0.2.7
		15: QuickAdd v0.8.0
		16: Templater v1.16.0
		17: Underline v1.2.1

**Describe the bug**
I really like this plugin and I'm using it daily, but since the last updates 1.8.8/1.8.9, all my area transclusions have had errors with the height and width of the selected area ID, maybe this is related with the bug #963 .

**To Reproduce**
1. Select the element (Transparent rectangle with white borders) inside excalidraw.
![image](https://user-images.githubusercontent.com/74424348/211645084-7ba5c3c5-6c73-449e-83b7-9c5a990199de.png)
2. Ctrl+p (Excalidraw: Copy 'area=' markdown link for selected element to clipboard)
3. Paste in the note as an embed ![[link#^area=block_id]]
4. See the transclusion ignoring the limits imposed by the rectangle
![image](https://user-images.githubusercontent.com/74424348/211646468-d59a0865-39b8-467c-92be-a61348db5515.png)

**Expected behavior**

The respective note transclusion should look like this:
![image](https://user-images.githubusercontent.com/74424348/211644762-bfbddbec-0a16-423b-b6e2-92cbd70fa581.png)

**Additonal context**

If I add more forms to the sides, it expands the transclusion area.

In Excalidraw:
![image](https://user-images.githubusercontent.com/74424348/211648243-e7beec26-6182-4bd7-8f92-320998c141ff.png)

Note transclusion:
![image](https://user-images.githubusercontent.com/74424348/211648432-e8539fd5-d844-4d33-ba3e-2bedb4749154.png)

**Comment by sstar0016** [comment]
I am having this bug too, it seems to be affected by the size of the image too?
All images below are only changed by selecting area+image and manually increasing their scale

![image](https://user-images.githubusercontent.com/124852454/217715857-158399b0-83bf-43c3-bb24-8b1145e9c729.png)
![image](https://user-images.githubusercontent.com/124852454/217716048-459ea911-a82b-41e6-8229-afaccf2c8bd4.png)
![image](https://user-images.githubusercontent.com/124852454/217716168-043f10b6-fcfd-4a85-9469-5d1bda471783.png)
