### ISSUE TITLE
FR: Automatically enter Draw mode on pen input

### ISSUE THREAD

**Issue by devinat1** [zsviczian/obsidian-excalidraw-plugin#969]
I know that obsidian-excalidraw can correctly go into pen mode on the touch of a pen. It would be great if it automatically also goes to draw mode when I am using the pen and on some different input. If this were made into a setting, it would be great in saving time not having to click the draw button every time I go back and forth from inputs.

**Comment by zsviczian** [comment]
I understand, I don't think I will develop this feature, for two reasons. 1) this again would need a change in core Excalidraw which makes it ever more difficult to deploy excalidraw.com improvements to Obsidian, and 2) I am cautious about adding more settings, the plugin is already very complex for users because of the many settings and customizations.

**Comment by devinat1** [comment]
For 2, it doesn't need to add a setting. Most drawing apps automatically behave this way.
For 1, couldn't it be added as some form of obsidian excalidraw script? Though I agree that it would be better as a core excalidraw change as you said. Still, pen features seem to be non intuitive as it stands.

**Comment by zsviczian** [comment]
Unfortunately, Excalidraw is designed as a desktop drawing app, and pen and mobile seem to be an afterthought.
I will think about what I can do. I have some plans to port more of the internal events to Excalidraw Automate, to allow custom tools to be defined as Excalidraw Scripts like for example an intelligent eraser or pen presets. When I do this porting I will keep this requirement in mind.

**Comment by devinat1** [comment]
As of the new script auto draw for pen, this is exactly the functionality I needed. Thanks for the new script update!
