### ISSUE TITLE
FR: Open in Web App

### ISSUE THREAD

**Issue by acarter5** [zsviczian/obsidian-excalidraw-plugin#971]
**Is your feature request related to a problem? Please describe.**
The excalidraw obsidian plugin is unresponsive on ipad (i.e. it misses strokes). However, the excalidraw web app works well on ipad.

**Describe the solution you'd like**
1. An automation to convert the saved .excalidraw.md file to the .excalidraw format and open it in the web application. 
2. An automation to convert the exported .excalidraw file from the web app to the .excalidraw.md format that's readable by obsidian

**Comment by zsviczian** [comment]
The feature is there:
![image](https://user-images.githubusercontent.com/14358394/212252659-c0b448ff-575c-4216-8160-221a1a173d81.png)

Note you will face limitations with some of the linking and other features (e.g. custom pens, fourth font) since these are not supported on Excalidraw.com
