### ISSUE TITLE
FR: Select all lines or arrows

### ISSUE THREAD

**Issue by Connor-yang96** [zsviczian/obsidian-excalidraw-plugin#973]
**Is your feature request related to a problem? Please describe.**

I need to change all arrows of color and size . One by One selection is too complex and need more time.  

---
Oh! I got it. select all, and change the color are still work. 

[ closed this issue ]

**Comment by zsviczian** [comment]
Try also the [Select Elements of Type](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Select%20Elements%20of%20Type.md) script from the script library. It can do wonders!
