### ISSUE TITLE
FR: support for scratchblocks

### ISSUE THREAD

**Issue by ksdavidc** [zsviczian/obsidian-excalidraw-plugin#974]
**Description**

Hold on to your hat, this is a tricky one that will take some explaining. Please bear with me.

## Background (just get the rough idea)
I use  [scratchblocks](https://github.com/scratchblocks/scratchblocks) in my website.
Scratchblocks take 'simple text' and convert them into embeddable scratchblock svg images.
![scratchblocks](https://user-images.githubusercontent.com/62230004/212385311-d0849330-fb33-4156-8894-699376d94d5c.svg)
It can do this in various places, including wikis, wordpress, and html, and now obsidian.

[This is a web version that shows how the conversion](https://scratchblocks.github.io/#?style=scratch3&script=when%20gf%20clicked%0Asay%20%5Bthese%20are%20scratchblocks%5D) takes place.

To implement this on an standard html website you add a scratchblocks.js file into your file system, add the link to it in your header, and in a script, call scratchblocks.renderMatching function with parameters to determine which html tags will be converted, usually some kind of pre or code block, and how. [Details here](url)

This doesn't work in obsidian, since getting the js to run is hard, but a very kind person wrote [a plugin that allows me to do it](https://github.com/shabegom/obsidian-scratchblocks). It works beautifully.

In addition to the results being visible in my Obsidian vault, as a matter of fact, my vault is fed into the digital-garden plugin and is posted online. To see it in action, [look at this page](https://digitalgardenforjrcoders.netlify.app/digital-garden/torchlight/torchlight-episode-1/). You can see the blocks there, alongside with some excalidraw drawings.

## Excalidraw

All well and good, so far. Now, if I import a markdown file with scratchblocks in it into an excalidraw drawing, miraculously it works out nicely that the scratchblocks javascript is grabbing the codeblocks and trying to convert it. I know this because I can see the shape of the blocks. 

Screenshot:
![Untitled 2023-01-13 20 25 29 excalidraw](https://user-images.githubusercontent.com/62230004/212388357-93c6837c-36ca-4048-81ca-360c0c9017cf.png)
This is the accompanying excalidraw markdown file
[Untitled 2023-01-13 20.25.29.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/10414170/Untitled.2023-01-13.20.25.29.excalidraw.md)
a zipped version of the excalidrawlib file.
[Untitled 2023-01-13 20.25.29.excalidrawlib.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/10414243/Untitled.2023-01-13.20.25.29.excalidrawlib.zip)

HOWEVER, it is all black. And that is what I am hoping could be fixable.

I know this is an usual request, as it involves a mashup of several technologies (scratchblocks, obsidian, the obsidian scratchblocks plugin, digital garden,, excalidraw...), none of which was expecting to meet each other in this dark alley, let alone make babies together. Still, I am so close, I feel like it might be possible with the right tweak.

**Describe the solution you'd like**
make the scratchblocks visible when imported from markdown file. My subsequent aim is to make slideshows I can use in class.

Thank you for the quite amazing plugin, great features, and for your time in reading this...
D

**Comment by zsviczian** [comment]
Yes, I am familiar with scratch. My kids learned programing with scratch. 
I'll look into this. My guess however the solution will be in the other plugin that displays the blocks in the markdown document. Depending on how the image is rendered it will or will not show up in Excalidraw. But I'll take a look.

**Comment by ksdavidc** [comment]
> Yes, I am familiar with scratch. My kids learned programing with scratch. I'll look into this. 
Thank you! 
> My guess however the solution will be in the other plugin that displays the blocks in the markdown document. Depending on how the image is rendered it will or will not show up in Excalidraw. But I'll take a look.
Understood. I am talking to that developer as well, and even knowing what questions to ask him would be helpful, for example. I will see what he says.

**Comment by ksdavidc** [comment]
Some on the scratchblock repo gave me a hint that it might be due to a missing  style file. I looked around for a way to hack that in, but I don't have a clue. Perhaps you know what it means.. https://github.com/scratchblocks/scratchblocks/issues/467#issuecomment-1399406564

**Comment by ksdavidc** [comment]
I added the filename of a css file to the css section of the excalidraw settings, with the scratchblocks css, and ran the 
ExcalidrawAutomate.mostRecentMarkdownSVG command and I can see the css in the style section:
ExcalidrawAutomate.mostRecentMarkdownSVG

and I can see the style info in the log:
<svg xmlns=​"http:​/​/​www.w3.org/​2000/​svg" width=​"800px" height=​"239px">​<style>​.sb3-label{font:500 12pt Helevetica Neue,Helvetica,sans-serif;fill:#fff;word-spacing:1pt}.sb3-motion{fill:#4c97ff;stroke:#3373cc}.sb3-motion-alt{fill:#4280d7}.sb3-motion-dark{fill:#4c97ff}.sb3-looks{fill:#96f;stroke:#774dcb}.sb3-looks-alt{fill:#855cd6}.sb3-looks-dark{fill:#bd42bd}.sb3-sound{fill:#cf63cf;stroke:#bd42bd}.sb3-sound-alt{fill:#c94fc9}.sb3-sound-dark{fill:#bd42bd}.sb3-control{fill:#ffab19;stroke:#cf8b17}.sb3-control-alt{fill:#ec9c13}.sb3-control-dark{fill:#cf8b17}.sb3-events{fill:#ffbf00;stroke:#c90}.sb3-events-alt{fill:#e6ac00}.sb3-events-dark{fill:#c90}.sb3-sensing{fill:#5cb1d6;stroke:#2e8eb8}.sb3-sensing-alt{fill:#47a8d1}.sb3-sensing-dark{fill:#2e8eb8}.sb3-operators{fill:#59c059;stroke:#389438}.sb3-operators-alt{fill:#46b946}.sb3-operators-dark{fill:#389438}.sb3-variables{fill:#ff8c1a;stroke:#db6e00}.sb3-variables-alt{fill:#ff8000}.sb3-variables-dark{fill:#db6e00}.sb3-list{fill:#ff661a;stroke:#e64d00}.sb3-list-alt{fill:#f50}.sb3-list-dark{fill:#e64d00}.sb3-custom{fill:#ff6680;stroke:#f35}.sb3-custom-alt{fill:#ff4d6a}.sb3-custom-dark{fill:#f35}.sb3-custom-arg{fill:#ff6680;stroke:#f35}.sb3-extension{fill:#0fbd8c;stroke:#0b8e69}.sb3-extension-alt{fill:#0da57a}.sb3-extension-line{stroke:#0da57a}.sb3-extension-dark{fill:#0b8e69}.sb3-obsolete{fill:#ed4242;stroke:#ca2b2b}.sb3-obsolete-alt{fill:#db3333}.sb3-obsolete-dark{fill:#ca2b2b}.sb3-grey{fill:#bfbfbf;stroke:#909090}.sb3-grey-alt{fill:#b2b2b2}.sb3-grey-dark{fill:#909090}.sb3-input-color{stroke:#fff}.sb3-input-number,.sb3-input-string{fill:#fff}.sb3-literal-dropdown,.sb3-literal-number,.sb3-literal-number-dropdown,.sb3-literal-string{word-spacing:0}.sb3-literal-number,.sb3-literal-string{fill:#575e75}.sb3-comment{fill:#ffffa5;stroke:#d0d1d2;stroke-width:1}.sb3-comment-line{fill:#ffff80}.sb3-comment-label{font:400 12pt Helevetica Neue,Helvetica,sans-serif;fill:#000;word-spacing:0}.sb3-diff{fill:none;stroke:#000}.sb3-diff-ins{stroke-width:2px}.sb3-diff-del{stroke-width:3px}]svg{border:2px solid;color:goldenrod;transform:scale(.95)}</style>​

but it's all still black (light mode) or dark (light mode).
