### ISSUE TITLE
BUG: Some shortcuts not working (Win)

### ISSUE THREAD

**Issue by deadrubbish** [zsviczian/obsidian-excalidraw-plugin#976]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.1.12
	Installer version: v1.1.9
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Royal Velvet v0.0.0
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 26
	Plugins enabled: 18
		1: Calendar v1.5.10
		2: Better Word Count v0.9.1
		3: Checklist v2.2.12
		4: Daily Activity v0.4.0
		5: Quick Switcher++ v2.3.5
		6: Dynamic Highlights v0.3.1
		7: Zotero Integration v2.2.35
		8: Advanced Tables v0.18.1
		9: Dataview v0.5.53
		10: Tasks v1.22.0
		11: Templater v1.16.0
		12: Natural Language Dates v0.6.1
		13: QuickAdd v0.8.0
		14: Readwise Official v2.0.1
		15: Commander v0.4.9
		16: PodNotes v2.3.1
		17: Obsidian Git v2.15.0
		18: Excalidraw v1.8.10

**Describe the bug**
Some Excalidraw shortcut not working;
Esc to exit fullscreen not working

**To Reproduce**
1: Go into Fullscreen using button on top right
2: Try and exit fullscreen with Esc - nothing happens
3: top right buttons obscured by Window controls - restoring window does not change this. 

**Expected behavior**
Esc- exit fullscreen - *N.B. - using Exit FullScreen shortcut icon from Utility Actions _does_ work

**Screenshots**
<img width="529" alt="image" src="https://user-images.githubusercontent.com/12722628/212559748-d1a04f21-6b2b-4ce7-85e3-0725ed0a3b6b.png">

**Additional context**

**Comment by deadrubbish** [comment]
Update:

My bad;  Ctrl-D _was_ another hotkey - changing this resolved this. 

But Esc not closing fullscreen still applies.

Apologies for misinormation

**Comment by zsviczian** [comment]
:) Escape not closing full screen was a deliberate development requested by multiple users.
Esc also exits the text editor when you are creating a new text element, and the line editor when you are changing the points of a line. People were frustrated that escape closes full screen mode when they only wanted to stop editing text.

**Comment by zsviczian** [comment]
You can also set up a custom hotkey for going to and exiting full screen mode:

![image](https://user-images.githubusercontent.com/14358394/212842683-62527997-b3de-440c-88de-6cffbd7b1d2b.png)

**Comment by deadrubbish** [comment]
Hi, thank you so much for your reply and explanation. Makes perfect sense.
I'm a recent starter, so missed that discussion. Just to say there is still
a message saying to use ESC to exit full screen when entering FS. I'll use
the hotkey option, which I had missed. I love your work and videos, found
them via Nicole VDH. Subscribed on KoFi to say thanks.

**Comment by zsviczian** [comment]
Thanks! I found the reference to "ESC" in the code and changed the hint text.
