### ISSUE TITLE
FR: direct hotkey for slideshows

### ISSUE THREAD

**Issue by ksdavidc** [zsviczian/obsidian-excalidraw-plugin#978]
To initiate a slideshow I have to click the menu button (I don'T know what to call it...??) which reveals a panel (??), and then select the slideshow plugin, which is a bit distracting in the middle of a presentation. 

It would be nice if there were a hotkey that would go directly into the slideshow.

I looked for such a command in the settings but could not find it. Did I miss it?

thanks for the great plugin.

**Comment by zsviczian** [comment]
You can set up a hotkey for any of the scripts. Simply go to Obsidian/Hotkey settings:
![image](https://user-images.githubusercontent.com/14358394/212841965-343d8ca5-8c15-4b6b-afe7-2b18425e4357.png)

Does this solve your issue?

**Comment by ksdavidc** [comment]
Only seeing first option....

<img width="824" alt="Screen Shot 2023-01-18 at 4 23 28 AM" src="https://user-images.githubusercontent.com/62230004/212993201-d2cdebf7-364f-49cf-9c91-bf90201185bc.png">


https://user-images.githubusercontent.com/62230004/212994122-a3d2c643-f366-4cf8-9c48-19826c9a0f8e.mov

**Comment by zsviczian** [comment]
And? did you set a shortcut for `Excalidraw: (Script) Downloaded/Slideshow`?

**Comment by ksdavidc** [comment]
Oh, that's the one! I didn't understand what "downloaded" meant. I was expecting something like "Excalidraw: Start Slideshow"
