### ISSUE TITLE
Quality of Life Improvement - Optimizing UX for writing with pen

### ISSUE THREAD

**Issue by claws99** [zsviczian/obsidian-excalidraw-plugin#986]
![](https://i.imgur.com/cjo2zcP.png)

#### Expanding custom pens functionality
Expanding custom pens to modify properties like `strokeWidth, strokeColor, strokeStyle & opacity` along with perfect-freehand-options using say something like:

```json
{
  constantPressure: true,
  hasOutline: false,
  outlineWidth: 4,
  strokeWidth: 6,
	strokeColor:  "#C22031",
	strokeStyle: "solid",
	fillStyle: "hachure",
	opacity: 50,
  options: {
    smoothing: 0.4,
    thinning: -0.5,
    streamline: 0.4,
    easing: "linear",
    start: {
      taper: 5,
      cap: false,
    },
    end: {
      taper: 5,
      cap: false,
    },
  }
}
```

allows users to create multiple 
- Different colored pens (with desired properties)
- Highlighters (= pens with wider strokeWidth & less opacity values)
- 

#### Adding custom actions button to `mobile-misc-tools-container`

 as shown here: https://excalidraw.com/#json=QJr5PswEnZW1VbJpIGBYi,bH927s61IL3eLEmvNN0FoA

**Comment by claws99** [comment]
I'm a school teacher who takes lot of math & science problems by hand. Everytime clicking so many buttons isn't allowing me to fully migrate to obsidian combined with excalidraw. With these features, one can start using Excalidraw Obsidian as a full-fledged substitute of OneNote, Good Notes & Notability. 

@zsviczian Its a humble request, if you don't want these to to be implemented in your plugin, please leave some clues about how to go about achieving these. I'll try and implement them & start using for myself. If they work well, I'll submit a pull request. Kindly consider this.

**Comment by mikebarkmin** [comment]
If you modify the current alternative pens scripts, you can apply the stroke properties. You just need to add replace the end of the script from line 197 to the end with this one:

```js
const {strokeWidth, strokeColor, strokeStyle, fillStyle, opacity, ...strokeOptions} = penJSON;
//--------------------------
// Apply pen
//--------------------------
const newAppState = {
  currentStrokeOptions: strokeOptions
}
if (strokeWidth) newAppState.currentItemStrokeWidth = strokeWidth;
if (strokeColor) newAppState.currentItemStrokeColor = strokeColor;
if (strokeStyle) newAppState.currentItemStrokeStyle = strokeStyle;
if (fillStyle) newAppState.currentItemFillStyle = fillStyle;
if (opacity) newAppState.currentItemOpacity = opacity;
await api.updateScene({
  appState: newAppState
});
api.setActiveTool({type:"freedraw"});
```

If you do so, I would recommend setting the strokeWidth, strokeColor and so on for all of your custom pens. Otherwise, the settings of the last selected pen are still active. For example, you have a thick red pen, and then you select a pen with no color and width set. This pen will also be thick and red.

Here is an example for a thick red pen:

```js
{ strokeWidth: 6, strokeColor:  "#C22031", strokeStyle: "solid", fillStyle: "hachure", opacity: 50, constantPressure: true, options: { smoothing: 0.4, thinning: -0.5, streamline: 0.4, easing: "linear", start: { taper: 5, cap: false, }, end: { taper: 5, cap: false, }, } }
```

**Comment by mikebarkmin** [comment]
This sounds excacly like what we are needing to make this happen. https://blog.excalidraw.com/redesigning-editor-api/

**Comment by zsviczian** [comment]
I think you are going to love the next release :)
You will be able to configure custom pens from within Excalidraw, and you will be able to pin scripts and pens to the side.

I will release it tomorrow.

![image](https://user-images.githubusercontent.com/14358394/215258636-a55538ce-7408-4a7c-8853-cbb90a9de35a.png)

![image](https://user-images.githubusercontent.com/14358394/215258759-93333103-3d08-4ec1-9d31-40daeae2b508.png)

**Comment by ryanmccool** [comment]
Hi @zsviczian, where do you get access to this pen configuration screen? I can't find it anywhere.

**Comment by zsviczian** [comment]
double click on the custom pen icon in the toolbar on the right (or top right)
