### ISSUE TITLE
FR: Opening links in a new tab

### ISSUE THREAD

**Issue by Alejandro-Stolz** [zsviczian/obsidian-excalidraw-plugin#995]
**Describe the solution you'd like**
At the moment, links are opened in the same tab as Excalidraw (with shift+click) or in a new pane (with ctrl+click). I would like to open a link in a new tab.

**Additional context**
I have set (ctrl+click) to open links are in a new tab so I would like to have this functionality in excalidraw also (I do not mind it being another keyboard shortcut, even better would be the option to customize them).

**Comment by zsviczian** [comment]
Windows click will open the drawing in a new window.
I need to clean up shortcuts and make all of these into settings: open in the same pane, open in a new pane, open in a new tab, open in a new window, open in the adjacent pane, open in the adjacent tab... there is a lot of combination of options to handle in a logical manner. As Obsidian added new ways of opening documents, the Excalidraw plugin did not keep up, resulting in the current, somewhat chaotic approach...

**Comment by Alejandro-Stolz** [comment]
> 

Thank you very much for the insight on this.

**Comment by zb5700** [comment]
i really want to open in the adjacent pane, but i find i can't do that in new version of excalidraw, the adjacent option is not working!!!

**Comment by zsviczian** [comment]
Have you looked at this cheatsheet in the Plugin Readme?
Open in adjacent pane is called "Open in new Tab Group" on the cheatsheet:
https://github.com/zsviczian/obsidian-excalidraw-plugin#hyperlinks-and-drag--drop-support

Did you try CTRL+ALT (CMD + OPT) click to open a link in an adjacent pane?

**Comment by Alejandro-Stolz** [comment]
UPDATE to my problem: it is fixed, now I can open links in new tabs with `Ctrl + click` and the rest of the shortcuts in the cheatsheet work perfectly too. Thank you very much.
