### ISSUE TITLE
Tiff support?

### ISSUE THREAD

**Issue by AnthonyMcDougal** [zsviczian/obsidian-excalidraw-plugin#996]
Is it possible to include tiff support? I know that Obsidian can't handle tiffs but I'm hoping it doesn't impact excalidraw directly...
Otherwise I'm stuck using powerpoint!

**Comment by zsviczian** [comment]
I added tiff support (mime type "image/tiff"), but unfortunately, Excalidraw still did not correctly load these images. I am afraid you are stuck with ppt in this case.
